### ISSUE TITLE
Provide more control over SSH connectivity to Git

### ISSUE THREAD

**Issue by akila-affle** [spring-cloud/spring-cloud-config#101]
Allow configuration of Known Hosts

```
  jsch.setKnownHosts(new FileInputStream(knownHostsFile));
```

and allow disabling host checking

```
session.setConfig("StrictHostKeyChecking", "no");
```

**Comment by dsyer** [comment]
Pull requests welcome. The defaults should not change of course.

**Comment by dsyer** [comment]
See also #146

**Comment by shakuzen** [comment]
I'm putting together a pull request for configuring the StrictHostKeyChecking from a property since I ran into that issue at work today from one of our CI servers. I'll submit it tomorrow.

**Comment by bitsofinfo** [comment]
bump

**Comment by shakuzen** [comment]
Oops. Sorry I never finished that pull request and submitted it. We ended up just working around the StrictHostKeyChecking issue we were facing. When/If I find some free time I'll look into this again, but anyone else please feel free to work on it.

**Comment by bitsofinfo** [comment]
Also see #431

**Comment by damaru-inc** [comment]
I assume this issue exists to solve the problem that when you have an ssh url for a git repo, you see a message in the log file saying something like "Do you accept this fingerprint?" and spring-cloud-config can't get past that.

I found a way to work around this by providing a custom jgit CredentialProvider class, and using that instead of the standard jgit UsernamePasswordCredentialProvider in org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.

Should I open a new issue/pull request for this, or does it belong here in this issue?

**Comment by spencergibb** [comment]
@damaru-inc the `help wanted` label means PRs are welcome

**Comment by damaru-inc** [comment]
Thanks - I understood that. I just wanted to know if this is the right issue for that change.

**Comment by damaru-inc** [comment]
I never did a pull request before. I assume I need to create a fork - obviously I can't create my own branch in this repo?

I've read this:
https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md

and this:
https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

Anything else I need to know?
thanks

**Comment by ryanjbaxter** [comment]
Yup you need to create your own fork.  Those two links should provide everything you need to know.  Of course let us know if you have any questions.

**Comment by spencergibb** [comment]
String host key checking was added in #535.

**Comment by spencergibb** [comment]
Closed in favor of #775

**Comment by Winnie2018** [comment]
Hi @spencergibb, I'm facing a warning "Could not fetch remote for master remote: git@**:**/***.git", and the ssh key is not working in my config server demo. Can you give some advices? thanks!

**Comment by ojhughes** [comment]
@Winnie2018 If you need advise with your configuration can you ask in https://gitter.im/spring-cloud/spring-cloud please
