### ISSUE TITLE
Loading a 5MB configuration file takes 1:30

### ISSUE THREAD

**Issue by gustavo-armenta** [spring-cloud/spring-cloud-config#1010]
Bug report

ConfigServer should cache on disk the processed configurations. During a refresh, it should continue serving the old configuration until the new config is stored on disk.

Using the attached files, every new request for the same configuration is taking around 1 minute and 30 seconds.

PS C:\> $a=curl.exe -u configurator:{password} -H $accept "$appUrl/configurator/Development"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.5M    0 11.5M    0     0   134k      0 --:--:--  0:01:28 --:--:-- 3619k

[configurator-Development.zip](https://github.com/spring-cloud/spring-cloud-config/files/1998021/configurator-Development.zip)

**Comment by dsyer** [comment]
It's probably a mistake to have a 5MB YAML configuration file (it's certainly a smell). I'm not sure cacheing is the answer anyway. Can you identify what the server is doing for 90seconds? Attach some thread dumps maybe? Is it any quicker if you put the large config file locally in the app?
