### ISSUE TITLE
How to refresh beans which created from configuration files ?

### ISSUE THREAD

**Issue by Vorh** [spring-cloud/spring-cloud-config#1011]
Hello, I have service which getting configuration files from config service.

Example: 
spring.data.mongodb.authentication-database: root
spring.data.mongodb.username: root
spring.data.mongodb.password: root
spring.data.mongodb.host: mongo 
spring.data.mongodb.port: 27017

Spring will create a mongodb bean. 
In the code I do not declare the bean.

How I cat refresh parameters this bean ( e.g. host or username)  using config-service?

**Comment by tdanylchuk** [comment]
since it's bootiful spring data it's not refresh scoped by default,
I guess you can try to override bean from `MongoDataAutoConfiguration`
`
@Bean
@RefreshScope
	@ConditionalOnMissingBean(MongoDbFactory.class)
	public SimpleMongoDbFactory mongoDbFactory(MongoClient mongo) throws Exception {
		String database = this.properties.getMongoClientDatabase();
		return new SimpleMongoDbFactory(mongo, database);
	}
`

**Comment by Vorh** [comment]
Oh, can another way exists ?

**Comment by ryanjbaxter** [comment]
Nope it needs to be annotated.
