### ISSUE TITLE
Bitbucket support X-Event-Key equal to repo:refs_changed

### ISSUE THREAD

**Issue by prasadramas** [spring-cloud/spring-cloud-config#1015]
Currently spring cloud config supports Bitbucket cloud webhook payload 
https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html

Bigbucket server webhook request payload for the **X-Event-Key**=**repo:refs_changed** is not supported currently.

Enhancement:

Bitbucket Server Webhook request payload support as part of spring cloud config monitor: 

https://confluence.atlassian.com/bitbucketserver055/event-payload-940682389.html

![image](https://user-images.githubusercontent.com/18919467/40200535-2f381472-59e2-11e8-8e0d-d52fa5c6a3b6.png)

Thanks in advance.

**Comment by spencergibb** [comment]
I don't understand what you are asking for. A screenshot of the bitbucket ui tells me nothing. What would `X-Event-Key` give me?

**Comment by spencergibb** [comment]
OK, looking at our current support, you mean specifically for if `X-Event-Key` is qual to `repo:refs_changed`?

**Comment by prasadramas** [comment]
Bitbucket server webhook makes the below request when the repository commit and push is happens to notify the external system like config server monitor end point:
http://<ConfigServer>:8888/monitor

POST Request Headers:

X-Event-Key | repo:refs_changed

X-Request-Id | 796104a0-cf67-48e7-8511-ce60a765684b


Request Body:
{
	"eventKey": "repo:refs_changed",
	"date": "2018-05-17T06:46:57-1200",
	"actor": {
		"name": "rs07399",
		"emailAddress": "rama@gmail.com",
		"id": 1,
		"displayName": "Rama",
		"active": true,
		"slug": "rs07399",
		"type": "NORMAL"
	},
	"repository": {
		"slug": "config-repo",
		"id": 2,
		"name": "config-repo",
		"scmId": "git",
		"state": "AVAILABLE",
		"statusMessage": "Available",
		"forkable": true,
		"project": {
			"key": "~RS07399",
			"id": 2,
			"name": "Rama Prasad Sadanakari",
			"type": "PERSONAL",
			"owner": {
				"name": "rs07399",
				"emailAddress": "rama@gmail.com",
				"id": 1,
				"displayName": "Rama ",
				"active": true,
				"slug": "rs07399",
				"type": "NORMAL"
			}
		},
		"public": false
	},
	"changes": [{
		"ref": {
			"id": "refs/heads/master",
			"displayId": "master",
			"type": "BRANCH"
		},
		"refId": "refs/heads/master",
		"fromHash": "e3ecbdddd35fb3f9e8d181fb5008ff4f78ec150d",
		"toHash": "8a40a5ed1fbc162f337deb3547d091f8432e2f3c",
		"type": "UPDATE"
	}]
}

**Comment by gpjacobs** [comment]
@spencergibb  I'm also interested in adding support for these headers as I'm also using Bitbucket server. I can submit a pull request with the changes if you'd like.

**Comment by ryanjbaxter** [comment]
PRs are always welcome
