### ISSUE TITLE
How to retrieve multiple files in a single rest call

### ISSUE THREAD

**Issue by SravanTatikonda** [spring-cloud/spring-cloud-config#1021]
Question

How do I retrieve multiple xml files from config server with same extension (.xml)?

To read single file: `https://localhost:8888/config/RESOURCE/default/develop/base/a.xml`

if I have multiple files in the base folder with same extension and all of them are of same schema.
I created models accordingly with xml binding annotations and able to read a specific file successfully.

Tried:

```
restTemplate.exchange(resourcePath + space + "/", HttpMethod.GET, null,
        new ParameterizedTypeReference<List<Object>>() {
        });
```

with return type: ResponseEntity<List<Object>>

```
Error:
org.springframework.web.client.HttpClientErrorException: 404 Not Found
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:85)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:707)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:660)
	at org.springframework.web.client.RestTemplate.execute
```

**Comment by dsyer** [comment]
There's no such endpoint in the config server. I guess it would be a new feature, but I doubt if it is going to get implemented, unless there's something I'm missing - there's quite a lot of moving parts there implicitly in your requirement.
