### ISSUE TITLE
Dont work on Linux

### ISSUE THREAD

**Issue by brunosc** [spring-cloud/spring-cloud-config#1022]
Hi all,

My config server dosen't create temp files.

[my repo](https://github.com/brunosc/spring-ms-in-action)

I try change basedir but dosen't affect too.

On windows it works!

**Comment by ryanjbaxter** [comment]
Is there an exception that is thrown or some kind of error message in the console?  Can you provide that?

**Comment by brunosc** [comment]
No exceptions.

When I hit cloud-config (http://localhost:8888/licensingservice/dev), show only this:
```
2018-05-24 11:17:04.763  INFO 10087 --- [nio-8888-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2018-05-24 11:17:04.763  INFO 10087 --- [nio-8888-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2018-05-24 11:17:04.799  INFO 10087 --- [nio-8888-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 36 ms
```

My loggin level is:
```
logging:
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG
```
Another info: the folder is created on "/tmp/config-repo-RANDOM"
same as me utilize the configuration with basedir:

```
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brunosc/config-repo-ms-in-action/
          searchPaths: licensingservice,organizationservice
          basedir: /home/bruno/dev/cfgsrv/
```

**Comment by ryanjbaxter** [comment]
So the problem is that you do not have permissions to `/tmp` but even with `basedir` set it is still trying to create the repo in `/tmp`?

**Comment by spencergibb** [comment]
Your code doesn't have basedir set anywhere

**Comment by brunosc** [comment]
The basedir it's on my local repo:

`server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brunosc/config-repo-ms-in-action/
          searchPaths: licensingservice,organizationservice
          basedir: /home/bruno/dev/cfgsrv/

logging:
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG`

Not work on Edgware.SR2 and Edgware.SR3

**Comment by brunosc** [comment]
Problem found

I change https to ssh and added github on know_hosts
