### ISSUE TITLE
Config-server responds with incorrect health status during network partitions

### ISSUE THREAD

**Issue by fahimfarookme** [spring-cloud/spring-cloud-config#1024]
We follow the config first approach where requests to config-server is resolved via a server-side load-balancer. The load-balancer monitors the health of config-server instances by invoking the /health endpoints. However the config-server responds with incorrect health status (`{"status":"UP"}`) during network partitions - **i.e. when the remote repository is not accessible.**

### Steps to recreate the issue
1. Start the config server
2. Invoke the `/health` endpoint for the firs time.
   - Config server clones the repository
   - Responds with correct status - `{"status":"UP"}`
3. Simulate a network partition so that the the remote repository is not accessible
4. Invoke the `/health` endpoint again
   - Responds with incorrect status - `{"status":"UP"}`

This is because, at step 4, a `org.eclipse.jgit.errors.TransportException` is thrown, however it's swallowed and not propagated in `JGitEnvironmentRepository#fetch()` and `JGitEnvironmentRepository#merge()` methods. (`SvnKitEnvironmentRepository#update()` as well).

Is it by design? When the remote repository is not accessible, ideally the config-server status should be `DOWN` since it cannot respond with updated configurations from remote repo. Otherwise load-balancer will continue to route `/refresh` requests from microservices to config-server instances having the network partition.

Sample project and script to recreate the issue is [here](https://github.com/fahimfarookme/config-server-incorrect-health-issue)

**Comment by ryanjbaxter** [comment]
I think this PR tries to address this issue
https://github.com/spring-cloud/spring-cloud-config/pull/677

**Comment by ryanjbaxter** [comment]
If so maybe we can revive the PR and try to address it.

**Comment by fahimfarookme** [comment]
Issue #584 and PR #677 are about health status when the working directory is dirty and `force-pull` is off. However I believe it addresses the issue I reported as well - setting a flag rather than propagating the exceptions.

**Comment by fahimfarookme** [comment]
Partially. i.e.


- It does not cover `SvnKitEnvironmentRepository`
- Failure in `JGitEnvironmentRepository#merge()` could also be considered.

**Comment by ryanjbaxter** [comment]
Interested in working on a PR then?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
