### ISSUE TITLE
can not find the latest config from svn

### ISSUE THREAD

**Issue by yangpancode** [spring-cloud/spring-cloud-config#1025]
can not find the latest config from svn, but the /tmp/config-repo have the config file, if you delete the config-repo- , you can fetch the latest config immediately. how to solve this problem. thank you very much, best wishes!

**Comment by yangpancode** [comment]
cloud-config version is spring-cloud-config-server-1.3.2.RELEASE.jar

**Comment by ryanjbaxter** [comment]
Please provide a sample that reproduces the issue.

**Comment by yangpancode** [comment]
spring-boot-starters version is 1.5.2.RELEASE, should I miss some config properties?  this problem sometimes okay, but sometimes can not fetch  the latest repo, I checked the tmp/config-repo-, can find the latest proprties info. but the config server sometimes cannot fetch the latest.
server.port=8751
spring.application.name=lina-config-server
eureka.client.serviceUrl.defaultZone=http://10.2.108.12:8761/eureka/,http://10.2.108.13:8761/eureka/
eureka.instance.preferIpAddress=true
eureka.instance.instance-id=${spring.cloud.client.ipAddress}:${server.port}

spring.profiles.active=subversion
spring.cloud.config.enabled=true
spring.cloud.config.server.svn.uri= http://svn.***.com.cn:1580/svn/lina-config-center
spring.cloud.config.server.svn.username=test
spring.cloud.config.server.svn.password=123456
spring.cloud.config.server.default-label=lina-common-server

**Comment by ryanjbaxter** [comment]
Again please provide a sample that reproduces the issue

**Comment by yangpancode** [comment]
https://github.com/yangpancode/lina-config-server.git, this is my project. thank you very much.

**Comment by ryanjbaxter** [comment]
This project doesnt compile because it is missing the parent pom

**Comment by rajpushpa1** [comment]
spring.cloud.config.server.default-label=lina-common-server

what is "lina-common-server" ?
