### ISSUE TITLE
Activate profiles in profile-specific config file

### ISSUE THREAD

**Issue by ccit-spence** [spring-cloud/spring-cloud-config#103]
Not sure if this is possible now.  Use case is to have some common application configs based on profiles.

Example:  Using the following Spring Profiles.  
`spring.application.name=customers`
`spring.profiles.active=production,database`

Within the git repo having it possible to load the following based on the profiles provided.

`application.yml` => Happens Now
`application.yml#production` => Happens Now
`customers-production.yml` => Happens Now
`application-database.yml#production` => This does not happen now.  (or I don't know how)

The idea would be to have some common things such as database, rabbitmq, etc... that are fairly common in the application but not always needed for every service.  Then when you want one of the common items just include that in the profile.  This is the tricky part is then having it read a sub-profile within the file i.e. `production`?

**Comment by spencergibb** [comment]
you could use a `production` branch.  I don't think there is a notion of sub-profiles.

**Comment by ccit-spence** [comment]
Is using a branch where you use the `label`?  And yeah the sub-profile thing does not exist.  Just trying to figure out how it would process the profile within the file once it was inside.  Then you could have each profile for the database within one file.

**Comment by spencergibb** [comment]
yes, the `label` translates to a git branch.

**Comment by spencergibb** [comment]
Seems like you wouldn't want a `database` profile because you always want a database.

**Comment by ccit-spence** [comment]
Not always, it could be some type of aggregate service with no `database` needed.  Example would be Zuul.

**Comment by spencergibb** [comment]
right, but having the configuration for it in `applicaiton.yml` wouldn't hurt because you wouldn't have the needed jars for auto-configuration to work.

**Comment by ccit-spence** [comment]
Yes, true.  That was my approach originally.  When the number of services starts getting over 100 I am finding you can run into a very large application.yml that introduces unwanted things into some of the services.  Which database?  To take my example a little further. You could need a decent number of database profiles.  MySQL, Mongo, Neo4J etc.

Mainly just trying to think of a way to share some of the config without the ball of mud affect happening within the `application.yml`

**Comment by dsyer** [comment]
If this is a feature request it is in the wrong place. Needs to go in Spring Boot.

**Comment by ccit-spence** [comment]
I can put it in Spring Boot.  Sounds like if a concept of sub-profile existed it would be possible for the config-server to handle it.

**Comment by dsyer** [comment]
Profiles are processed in order. Maybe if you ask for `spring.profiles.active=database,production` it would already work?

**Comment by ccit-spence** [comment]
I can give it a try.  Pretty sure I tried that already.

**Comment by ccit-spence** [comment]
I may not be 100% clear on my understanding of how it works.  If I have a file named `application-database.yml`  It is not called if I have set a profile of `database,production`.  It seems if I have any mention of profiles within `applciation-database.yml` it is ignored.  If I remove the profiles and just have a single set of properties within the `appllication-database.yml` it will be read.

**Comment by dsyer** [comment]
Yes, that is correct. And there's already an issue in spring boot. You can't set new profiles inside a profile specific config file. Seems reasonable to me (and doesn't corrspond to your original description of the problem).

**Comment by ccit-spence** [comment]
So then right now the only way would be to do something like `appllication-databaselocal.yml` etc...  Then call them in profiles as needed.  The difference being that you could have to repeat yourself (file wise) a few times for each config.  Do you have the link to that Spring Boot issue?

**Comment by dsyer** [comment]
I can't find an active Spring Boot issue (which doesn't mean there isn't one).

**Comment by dsyer** [comment]
Here's the Boot issue: https://github.com/spring-projects/spring-boot/issues/340

**Comment by xiaochangg** [comment]
if my file is testing-dev.json. shall i access the testing-dev.json in config client ??

**Comment by dsyer** [comment]
Sorry, I didn't understand the question. Also please don't ask questions in comment on closed issues. Try Gitter or StackOverflow?

**Comment by xiaochangg** [comment]
Sorry, But I hope you can help me out。my question：
1.If the Git repository file is the .json suffix (as xxx.json)，not .yml or .properties suffix. The spring cloud config server can be accessed through the url (http://localhost:8888/application/default/master/xxx.json),
But How should the spring cloud config client access the spring cloud config server to get the xxx.json file content ?
2. How should  a spring cloud config client access the Multiple Files（.json suffix）?

Thank you very much
