### ISSUE TITLE
NPE on Windows due to improper use of lastIndexOf(File.separator) (Finchley.RC2)

### ISSUE THREAD

**Issue by SladeRun14** [spring-cloud/spring-cloud-config#1032]
org.springframework.cloud.config.server.environment.HttpClientConfigurableHttpConnectionFactory.lookupHttpClientBuilder(URL url)

Line 68:

`spec = spec.substring(0, spec.lastIndexOf(File.separator));`

Issue:
The statement above results in an NPE on Windows since a `File.separator` on Windows is a backslash and therefore will never be found in a URL String (which only ever contains forward slashes). This code will work fine on operating systems having forward slashes as file separators, but makes Finchley.RC2 unusable in a Windows environment.

Context:
```
private HttpClientBuilder lookupHttpClientBuilder(URL url) throws MalformedURLException {
  String spec = url.toString();
  HttpClientBuilder builder = httpClientsByUri.get(spec);
  while (builder == null) { 
    spec = spec.substring(0, spec.lastIndexOf(File.separator));
    builder = httpClientsByUri.get(spec); 
  }
  return builder;
}
```

**Comment by ryanjbaxter** [comment]
@pivotal-dylan-roberts ^^^

**Comment by pivotal-dylan-roberts** [comment]
working on this now

**Comment by fahimfarookme** [comment]
Faced the same issue. This worked for me.

```
private HttpClientBuilder lookupHttpClientBuilder(URL url) throws MalformedURLException {   	
        final Optional<HttpClientBuilder> cb = httpClientsByUri.entrySet()
                .stream()
                .filter(entry -> url.toString().startsWith(entry.getKey()))
                .map(Map.Entry::getValue)
                .findFirst();
        return cb.get();
}
```

**Comment by bingbingll** [comment]
Currently, there is no good solution but to reduce the version, using 1.5.14.

**Comment by fahimfarookme** [comment]
Until #1037 is released, you can define a custom [ConfigurableHttpConnectionFactory](https://github.com/fahimfarookme/config-server-stuck-thread-issue/blob/master/config-server-fix/src/main/java/me/fahimfarook/config/server/TimeoutHttpConnectionFactory.java) class and a [bean](https://github.com/fahimfarookme/config-server-stuck-thread-issue/blob/master/config-server-fix/src/main/java/me/fahimfarook/config/server/ConfigServerApplication.java#L22)
