### ISSUE TITLE
Document skipSslValidation property for Git backends

### ISSUE THREAD

**Issue by ojhughes** [spring-cloud/spring-cloud-config#1039]
Document skipSslValidation property as described in SCS documentation:https://docs.pivotal.io/spring-cloud-services/1-5/common/config-server/configuring-with-git.html

**Comment by ojhughes** [comment]
⬆️ @fifthposition

**Comment by ryanjbaxter** [comment]
Make sure to also document timeout property https://github.com/spring-cloud/spring-cloud-config/pull/1040#issuecomment-395066283
