### ISSUE TITLE
Upgrading to Finchley.RC2 download wrong configurations

### ISSUE THREAD

**Issue by HelLViS69** [spring-cloud/spring-cloud-config#1045]
Hi,
I have a microservices application with config server running on Spring Boot 2.0.1 and Spring Cloud Finchley.RC1.

The problem is raising upgrading the stack to Spring Boot 2.0.2 and Spring Cloud Finchley.RC2. In this setup, Config Server correctly downloads my git repo, but also it downloads and serves configurations from the https://github.com/spring-cloud-samples/config-repo, causing my services to not start

**Comment by dsyer** [comment]
I guess you need to share your code so we can reproduce the problem?

**Comment by HelLViS69** [comment]
Hi,
I replicated the bug with a minimal code, pushed to https://github.com/HelLViS69/spring-cloud-config-issues-1045
When bootRun the project, in /tmp you can find config-repo-XXXX with my conf repo, config-repo-YYYY empy and config-repo-ZZZZ with sample configuration

**Comment by HelLViS69** [comment]
Hi.
Thanks, it works now. Btw I wonder how it worked until today (this project started with Spring Boot 1.4)

**Comment by ryanjbaxter** [comment]
In my testing locally it worked the same way in Edgware.SR3 and Finchley.RC1.
