### ISSUE TITLE
HttpClientConfigurableHttpConnectionFactory/File.separator-problem

### ISSUE THREAD

**Issue by Dylandelon** [spring-cloud/spring-cloud-config#1047]
Hi ,
springCloudVersion=Finchley.RC2
springBootVersion=2.0.2.RELEASE

![qq 20180606150809](https://user-images.githubusercontent.com/16143966/41023797-fd98d992-699f-11e8-9120-bc1671e3c278.png)

I found a problem with the spring-cloud-config-server   
when Load configuration file , a git repository URL:https://github.com/Dylandelon/salemonitor.git
details:

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dylandelon/config-repo.git
          search-paths: sale-repo
      label: v1.0

jar:spring-cloud-config-server  class:HttpClientConfigurableHttpConnectionFactory   method :lookupHttpClientBuilder
In the method, File.separator is  \  in the windows system, 
so it can not get the files on guthub. Do we consider adding the appropriate judgement here? 
Or do it in the way in the previous version

my example :
https://github.com/Dylandelon/salemonitor.git

Thanks in advance.
dylan (delong)  .

**Comment by spencergibb** [comment]
This is a duplicate

**Comment by Dylandelon** [comment]
ok ,i see,thanks
