### ISSUE TITLE
Plain text files with composite environments not correctly resolving

### ISSUE THREAD

**Issue by dimitrydeclercq** [spring-cloud/spring-cloud-config#1052]
When using [Ordered Composite Environments](http://cloud.spring.io/spring-cloud-config/1.4.x/single/spring-cloud-config.html#_composite_environment_repositories) and trying to serve [Plain Text files](http://cloud.spring.io/spring-cloud-config/1.4.x/single/spring-cloud-config.html#_serving_plain_text) the resource repository and/or controller does not seem to adhere to the order specified in the configuration.
Version: 1.4.1.RELEASE

application.properties:
```
spring.profiles.active=native, git
# GIT Backend
spring.cloud.config.server.git.uri=file:///path/to/git/
spring.cloud.config.server.git.search-paths={application}
spring.cloud.config.server.git.order=1
# File system backend
spring.cloud.config.server.native.searchLocations=classpath:/config/{application}
spring.cloud.config.server.native.order=2
```

If we add for example 'nginx.conf' in the jar file and another version in the git repository, it should return the git version but it returns the native version.

Some quick research indicates that this might be related to the `GenericResourceRepository` not implementing `Ordered`, but I'm not familiar with the internals.
I've started it in debug and the `ResourceRepositoryConfiguration` gets wired with a `SearchPathLocator` that only contains the `searchLocations` for the native profile (so in this case `classpath:/config/{application}`)

Is this expected? Am I missing something?

**Comment by ryanjbaxter** [comment]
Could you provide a sample that reproduces the problem?
