### ISSUE TITLE
spring cloud config cannt decrypt "javax.crypto.IllegalBlockSizeException"

### ISSUE THREAD

**Issue by LX1993728** [spring-cloud/spring-cloud-config#1053]
in my config-server
application.yml
`encrypt:
  key: foo`

then run the application and use curl to test,but appear error when i to decrypt
`javax.crypto.IllegalBlockSizeException: Input length must be multiple of 16 when decrypting with padded cipher
`

**Comment by ryanjbaxter** [comment]
Please provide a project that reproduces the error.
