### ISSUE TITLE
Multi-repo shortcut syntax no longer works

### ISSUE THREAD

**Issue by gregjobe** [spring-cloud/spring-cloud-config#1055]
Hello,

According to https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html, it should be possible to specify a Git config repository per application with: 

`spring.cloud.config.server.git.repos.simple: https://github.com/simple/config-repo`

I'm using version 2.0.2.RELEASE (Finchley.RC2) and I get the following error in that case:

`Failed to bind properties under spring.cloud.config.server.git.repos.admin to org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentProperties$PatternMatchingJGitEnvironmentProperties:`

    `Property: spring.cloud.config.server.git.repos.admin
    Value: git@...:.../admin.git
    Origin: class path resource [bootstrap.yml]:13:20
    Reason: No converter found capable of converting from type [java.lang.String] to type [org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentProperties$PatternMatchingJGitEnvironmentProperties]`

Note that if I only use "spring.cloud.config.server.git.uri", it works but i would like to have some exceptions to the default rule.

Thanks in advance!

**Comment by ryanjbaxter** [comment]
Can you show us your entire configuration, or even better provide a sample that reproduces the problem?  Did this work in Edgware.SR3?

**Comment by gregjobe** [comment]
Please find a sample: [config.zip](https://github.com/spring-cloud/spring-cloud-config/files/2090929/config.zip)
Yes it was working fine in Edgware.SR3.
