### ISSUE TITLE
Spring Cloud Config unable to read configuration from filesystem

### ISSUE THREAD

**Issue by dgt-amexio** [spring-cloud/spring-cloud-config#1056]
I succedeed in having a simple Spring Cloud Config Server run and i addded some local configuration files.
But it seems that i cannot serve those configuration through the server (i cannot succeed in viewing my configuration through the proper requests.

Maybe am I doing something wrong or missing extra configuration to achieve this.

my server application.properties is (I'm running on a Windows host, reason why file:/// with 3 /)

```
spring.cloud.config.server.native.searchLocations=file:///${user.home}/test.config
```

Inside folder test.config, i placed a application-default.properties file with the following content
```
foo.bar=test
```

Once server is started, if i try to retrieve configuration using http://localhost:8080/application/default, i get a 404 error.

Any idea ?

**Comment by spencergibb** [comment]
I don't think you need `-default` on the file name

**Comment by indraneelb1903** [comment]
'Default' is the default profile , right? If the profile was , lets say 'dev' then the configServer does return properties from application-dev.properties. If the default profile is used , then you should not name your file as application-default.properties. Any reason for this disparity? @spencergibb

**Comment by spencergibb** [comment]
Did it work or not? Standard spring boot behavior AFAIK.

**Comment by dgt-amexio** [comment]
My bad ... the project generated through start.spring.io was missing the @EnableConfigServer annotation.
Once added, server works properly.
Ticket can be closed

Thx
