### ISSUE TITLE
profile active native conflict with multi-Environment config

### ISSUE THREAD

**Issue by vvsuperman** [spring-cloud/spring-cloud-config#1059]
hello, I want put config files in local system, so I use
```
spring:
   profiles:
      active: native
```
and also I want to use mutli-configs for different enviroments, e.g  dev, test, prod, so I run config like that
`java -jar -Dspring.profiles.active=test config-service.jar`
but if you do that, the `spring.profiles.acitve` became sth like `test`,so the local config couldn't work, and will raise exception like that
`you need to configure a uri for the git repository`

**Comment by spencergibb** [comment]
If you're using Finchley RC2 this is a duplicate and has been fixed

**Comment by vvsuperman** [comment]
oh, we will level up our project to Finchley 2 month ago, but now we are on 1.5.9. So, If I am in Finchley, how to solve this problem?

**Comment by ryanjbaxter** [comment]
Finchley is only compatible with Spring Boot 2.0.x.
