### ISSUE TITLE
Bug: Config not being refreshed when map size is modified

### ISSUE THREAD

**Issue by ismail-s** [spring-cloud/spring-cloud-config#1062]
# Steps
- Start a Spring microservice with version 1.5.13 of spring-boot and version 1.6.3 of  `spring-cloud-services-starter-config-client` that is setup to connect to a spring config server. Make sure that the microservice has a config class looking something like:

```java
@ConfigurationProperties
public class SomeConfig {
    private final Map<String, String> something = new LinkedHashMap<>();
    public Map<String, String> getSomething() {
        return this.something;
    }

    @PostConstruct
    public void someMethodName() {
        System.out.println("Attach a debugger here");
    }
}
```

with config server config looking something like:

```yaml
something:
  a: b
  c: d
```

- Upon startup, the microservice will pull in the config from the config server
- Modify the config to look like:
```yaml
something:
  a: b
  c: d
  e: f # This has been added
```
- Call the `/refresh` endpoint. The config successfully gets pulled in.
- Modify the config to look like:
```yaml
something:
  a: b
  c: d
```
- Call the `/refresh` endpoint.

# Expected
- `getSomething()` returns a map with 2 entries

# Actual
- `getSomething()` returns a map with 3 entries

# Additional
- Changing an individual config value works fine. It is only adding/removing map entries that don't get picked up, but only after at least 2 refreshes
- A quick workaround is to add a `RefreshScope` annotation to the config class. The downside to this is that this means the config class gets lazy-loaded on refreshing, including the application of any validation annotations.
- I am not sure if this is a bug in this repo, or in spring-boot.

**Comment by ryanjbaxter** [comment]
Please provide a project that reproduces the problem.  Also this repo does not support spring cloud services, it is only for the open source spring cloud config project.
