### ISSUE TITLE
Feature Request - Insight endpoint for Config Server

### ISSUE THREAD

**Issue by indraneelb1903** [spring-cloud/spring-cloud-config#1066]
So , this was a problem we were generally facing while deploying our applications. As different environment/profile files grew in complexity , often it would happen that there would be few properties which would be present in one profile property file and absent in other , as addition of properties was done manually by an individual.

For example - Consider you have 4 profiles , DEV , SIT1 , SIT2 , UAT . So you have 4 profile specific file , application-DEV.yml , application-SIT1.yml , application-SIT2.yml , application-UAT.yml.

As , these files grew in complexity , it would often happen , that an individual would forget to add some properties in one file , or maybe mixed up the values in between environments . As were deploying our applications as a WAR and using legacy infrastructure , if a certain property was missing in one environment , obviously an application would not start as it was expecting that , but the amount of time taken , to identify what is missing and change the property files , make them consistent , and restart the application , as it was legacy infrastructure , would take 30 minutes and screw up productivity .

I propose to add an endpoint by which after deploying the config Server , you can demand to see the 'diff' between property files . This would return the response , where it would tell you the difference between property files . Difference like how many properties are present in one file and how many in other . Are there any properties present in one and not in other , if the same property exists in both , what is difference in their values and so on .

**Comment by spencergibb** [comment]
Not sure how this would work because not all repositories use files.

**Comment by indraneelb1903** [comment]
By that u mean jdbc and vault?

**Comment by spencergibb** [comment]
Indeed

**Comment by indraneelb1903** [comment]
I have never personally used either of them , but when property sources objects get sent to the config client , what are the name fields populated with?

**Comment by dsyer** [comment]
Maybe we wouldn't need files, but we might need history (which those stores do not support). I'm kind of unsure at the moment, though, what the actual requirement is. Since you have a real use case, do you think you could expand a bit? You mentioned an "endpoint". What would it's contract be? Show use some example requests and responses.

**Comment by indraneelb1903** [comment]
Okay I will post a detailed example in the evening.

**Comment by indraneelb1903** [comment]
This is a very basic example . 

The endpoint would be `/compare/{application}/{profiles}` . Here application is the prefix  of the file's name  and profiles is a comma separated list of profile values . So , if application is given the value of TemplatingApp and profiles is DEV,UAT. So your request is ,

`http://localhost:8081/compare/application/DEV,UAT`

In such a scenario , you will first check if such a prefix exists for any file , and if the prefix exists , do these various profiles exist. So , in a nutshell , it will look for files - `TemplatingApp-DEV.yml` and `TemplatingApp-UAT.yml` , if either or both are not found , it will throw back a response with status code 
`404 Files not found`.

In the happy scenario it would send back a response which would be a comparison between `TemplatingApp-DEV.yml` and `TemplatingApp-UAT.yml` . 

This is a very basic implementation I have created right now , the response is , 

                                  {
                                     "Comparing UAT to DEV": {
                                         "commonKeys": [
                                              "c",
                                              "d",
                                               "e"
                                         ],
                                         "differentKeys": [
                                              "f",
                                              "g",
                                              "l"
                                          ],
                                     "description": [
                                         "Same key found but values are different.Key is:c and values are fgh and ere respectively.",
                                          "Same key and value found . Key is d and value is fdf",
                                          "Same key found but values are different.Key is:e and values are lki and hghj respectively.",
                                          "Key not found.Key is f and value is lmn",
                                          "Key not found.Key is g and value is opq",
                                          "Key not found.Key is l and value is abc"
                                         ]
                                  },
                                       "Comparing DEV to UAT": {
                                           "commonKeys": [
                                             "c",
                                             "d",
                                             "e"
                                            ],
                                           "differentKeys": [
                                            "a",
                                             "b"
                                             ],
                                          "description": [
                                             "Key not found.Key is a and value is abc",
                                             "Key not found.Key is b and value is dsd",
                                             "Same key found but values are different.Key is c and values are ere and fgh respectively.",
                                             "Same key and value found . Key is d and value is fdf",
                                              "Same key found but values are different.Key is e and values are hghj and lki respectively."
                                           ]
                                   }
                   }

Obviously , this response can be improved and made more user friendly . This is my initial draft on the above . Let me know what you guys feel about it.

**Comment by dsyer** [comment]
The semantics of what the profile values mean is kind of problematic there. What if the you want to know the difference between configuration using 2 profiles and the default?

In summary, I'm not sure we should get into this business. The data are all available to you, so you can create the report  yourself with a bit of command line fu.

**Comment by indraneelb1903** [comment]
Yeah I have already done it myself. Closing the issue then, as I could not convince u guys.
