### ISSUE TITLE
Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean

### ISSUE THREAD

**Issue by Jayaram123** [spring-cloud/spring-cloud-config#1079]
hi folks I am trying to run spring boot 2.0 web application by sing application class, but it show the above error.

here is my Application class

@ComponentScan(basePackages="com.ram.microsevices.resfulwebservices")
@EnableAutoConfiguration
@SpringBootApplication
public class RestfulWebservicesApplication {

	public static void main(String[] args) {
		SpringApplication.run(HelloWorldController.class, args);
		
	}
}

Please  tell me the solution to this problem

**Comment by spencergibb** [comment]
This doesn't seem to have anything to do with spring cloud config. If you'd like some help, please provide a project to clone.

**Comment by bingbingll** [comment]
If you use the external "tomcat" we need to inherit SpringBootServletInitializer this class
instance：
```
@EnableAutoConfiguration
@SpringBootApplication
public class Application{
    public static void main(String[] args) throws Exception {
        SpringApplication.run(Application.class, args);
    }
}
```
```
public class Application extends SpringBootServletInitializer {   
    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(Application.class);
    }
}
```
