### ISSUE TITLE
Spring-cloud-config support to getting the config bu calling RESTFUL API?

### ISSUE THREAD

**Issue by eastwoodwang** [spring-cloud/spring-cloud-config#1088]
Currently , i want to get the sping-boot config by calling the restful api, what should i do?

**Comment by spencergibb** [comment]
Have you looked here? https://github.com/spring-cloud/spring-cloud-config/blob/master/docs/src/main/asciidoc/quickstart.adoc

On mobile or I'd give an example

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
