### ISSUE TITLE
When refresh,server logs "The local repository is dirty"

### ISSUE THREAD

**Issue by simon518** [spring-cloud/spring-cloud-config#1090]
version:   spring-cloud-config-server  :1.3.0.Release

when is refresh the config,the server use git to merge local and remote git commits,but i encourt some warn logs,such as:
     1.The local repository is dirty. Resetting it to origin
How does it occured;
Following,use git reset command to discard local changes,but there also has some warn logs,such as:
      1.Could not reset to remote for [label] (current ref=[ref])

As a result:  The refresh change keys is empty!!!
can some help me solve these problem;

**Comment by ryanjbaxter** [comment]
Can you please try using Edgware or Finchley?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
