### ISSUE TITLE
Log exception in ConfigServerHealthIndicator

### ISSUE THREAD

**Issue by tjuchniewicz** [spring-cloud/spring-cloud-config#1091]
Would be useful to log at debug level exception in [ConfigServerHealthIndicator](https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/ConfigServerHealthIndicator.java#L69).

**Comment by ryanjbaxter** [comment]
want to submit a pr?

**Comment by tjuchniewicz** [comment]
Sure. I will prepare PR.
