### ISSUE TITLE
Config server throw  "Forbidden" error for /encrypt and /decrypt endpoints

### ISSUE THREAD

**Issue by harinathbk** [spring-cloud/spring-cloud-config#1093]
I have implemented spring security for spring cloud config-server. Applications are fetching properties and working fine. But /encrypt and /decrypt endpoints are throw "Forbidden" error. Please find below request and response for same. we can disable csrf protection but i have to fix in other way( other than disabling  csrf protection).Can you please help me to fix this issue.

Thanks in advance.

Input
====
$ curl -kv  -H "Content-Type: text/plain" http://<config-server-host>:<port>/encrypt -d "password" -u username:password

Response
=======
{"timestamp":1532372262915,"status":403,"error":"Forbidden","message":"Could not verify the provided CSRF token because your session was not found.","path":"/encrypt"}

**Comment by harinathbk** [comment]
Thanks for your reply,Ryan.I need to generate CSRF token and pass it in each time when i call encrypt. Please share some sample if you have any.

Thanks in advance.
Harinath.

**Comment by ryanjbaxter** [comment]
Having CSRF enabled for the '/encrypt` and `/decrypt` endpoints does not make sense, it is only necessary for browser clients and these endpoints are not used by the browser.  My recommendation is to configure Spring Security so CSRF is disabled for those endpoints.
https://docs.spring.io/spring-security/site/docs/current/reference/html/csrf.html#when-to-use-csrf-protection

**Comment by Junior-Sousa** [comment]
Ryan, I am having a similar issue, I trying to execute the command:
$ curl -X POST http://localhost:8888/encrypt -d mysecret -u abcdef but I don't get any response from config-server. 
If I remove the dependency spring-cloud-security from config-server project and execute the command:
$ curl -X POST http://localhost:8888/encrypt -d mysecret the encryption works.

According with this scenario, do you see any relashionship with CSRF configuration? What I did until the moment was add in my config-server.yml the property: spring.security.enable-csrf=false, but the problem persists if I keep the spring-cloud-security dependency. 

The spring cloud version I am using is Finchley.SR1

Thanks,
Junior Sousa

**Comment by ryanjbaxter** [comment]
It is hard to say if it is CSRF that is causing your issue or not.  It could be.  I dont think the property you are using is correct either.  I think it should be `security.enable-csrf=false` (this is deprecated in Boot 2).  

Does the response you get back from the config server indicate that the CSRF token is missing?

**Comment by mmoayyed** [comment]
Something like this perhaps? 

```java
    @Autowired
    @Bean
    public WebSecurityConfigurerAdapter casConfigurationServerWebSecurityConfigurerAdapter(final ServerProperties serverProperties) {
        return new WebSecurityConfigurerAdapter() {
            @Override
            protected void configure(final HttpSecurity http) throws Exception {
                super.configure(http);
                val path = serverProperties.getServlet().getContextPath();
                http.authorizeRequests().antMatchers(path + "/decrypt/**").authenticated().and().csrf().disable();
                http.authorizeRequests().antMatchers(path + "/encrypt/**").authenticated().and().csrf().disable();
            }
        };
    }
```

Shouldn't this be something handled by Spring-Config-Cloud automatically? If so, I'd be happy to submit a pull request to handle this.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by benspylee** [comment]
Thanks for this thread It helped. when i am using without csrf disabled for /encrypt and /decrypt endpoints i am receiving 302 status code even though i have authorization header in place. when i disabled csrf for those endpoint its working fine.@spring-issuemaster look into this.
