### ISSUE TITLE
jgit file:/// hard resets removing local commits

### ISSUE THREAD

**Issue by a1dutch** [spring-cloud/spring-cloud-config#1095]
When using the latest Finchley release with a file uri to a local git repository that is a ahead of the remote repository its changes get hard reset.

This behaviour is different to Edgware which does not reset any local commits ahead of the remote.

Steps to reproduce:

1) clone a remote git repo
2) configure spring cloud with a file:// uri to the cloned repository
3) make some config changes and commit them, but dont push them to the remote
4) start the config server
5) make a request for some config
6) the latest commit gets removed and reset to the same state as the remote.

**Comment by ryanjbaxter** [comment]
This is due to #875.

Why would you keep commits locally and not push them to the remote.

**Comment by a1dutch** [comment]
For local testing whilst doing development, if I make a change and have to push it could break existing code.

**Comment by a1dutch** [comment]
Seems silly to have to push it just to fix a scenario that probably should of been handled by a git revert rather than a reset and a force push.

**Comment by ryanjbaxter** [comment]
You could just use a native repo instead of a git repo for testing

**Comment by a1dutch** [comment]
i will take a look at the native repo.
