### ISSUE TITLE
Spring Cloud Config is trimming leading and trailing spaces in .properties

### ISSUE THREAD

**Issue by pawelpanek81** [spring-cloud/spring-cloud-config#1100]
Spring Cloud Config is trimming leading and trailing spaces in .properties and .yml

Start config server and type in application.properties
```
security.jwt.prefix=Bearer 
```
and in application.yml
```
security:
  jwt:
    prefix: Bearer 
```

go to: `http://config-server:9090/%20/default` (type your host and port)
the output is
```
"propertySources":[
      {
         "name":"classpath:/cfg/application.properties",
         "source":{
            "security.jwt.prefix":"Bearer"
         }
      },
      {
         "name":"classpath:/cfg/application.yml",
         "source":{
            "security.jwt.prefix":"Bearer"
         }
      }
   ]
```

config version: 2.0.1.RELEASE

**Comment by shakuzen** [comment]
I believe it is Spring Boot, not Spring Cloud that would be doing the trimming. See https://github.com/spring-projects/spring-boot/issues/13602
As noted in that issue, leading spaces being trimmed from `.properties` files' values is the specification

**Comment by ryanjbaxter** [comment]
OK I will close this issue then.  Thanks.
