### ISSUE TITLE
RefreshScopeBeanDefinitionEnhancer prevents placeholders resolution on FactoryBeans (cloud config client 2.X)

### ISSUE THREAD

**Issue by juanpablo-santos** [spring-cloud/spring-cloud-config#1108]
### Background
A couple of years ago, we migrated some old Spring applications (xml configuration) to a more modern Spring Boot 1.x + Spring Cloud Config 1.y based stack. We are now in the process of migrating from Spring Boot 1.5.15 + Spring Cloud Config 1.4.4 to Spring Boot 2.0.4 / Spring Cloud Config 2.0.1, when we have stumbled upon something weird (there's a minimal [sample attached](https://github.com/spring-cloud/spring-cloud-config/files/2286791/sample-project.zip) showing the issue): seems that on factory beans (and only on factory beans) `${}` placeholders don't get resolved anymore.

### Steps to reproduce
with the attached [sample-project.zip](https://github.com/spring-cloud/spring-cloud-config/files/2286791/sample-project.zip):

* on `sccs` folder, `mvn clean spring-boot:run`
* http://localhost:8888/demo/default shows values for `demo`application
* on `app` folder, `mvn clean spring-boot:run`
* should fail with a nasty
```
[...]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.

2018-08-14 13:03:03.737 ERROR 1976 --- [           main] o.s.boot.SpringApplication               : Application run failed

javax.xml.ws.WebServiceException: Illegal endpoint address: ${jaxws.endpoint}
        at com.sun.xml.internal.ws.api.EndpointAddress.create(EndpointAddress.java:149) ~[na:1.8.0_121]
        at com.sun.xml.internal.ws.client.RequestContext.setEndPointAddressString(RequestContext.java:131) ~[na:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
[...]
        at com.sun.proxy.$Proxy87.getBinding(Unknown Source) ~[na:na]
        at com.example.demo.config.JaxWsHandlersAdderBeanFactoryApplicationListener.addSOAPHandlerIfNotPresent(JaxWsHandlersAdderBeanFactoryApplicationListener.java:41) ~[classes/:na]
        at com.example.demo.config.JaxWsHandlersAdderBeanFactoryApplicationListener.onApplicationEvent(JaxWsHandlersAdderBeanFactoryApplicationListener.java:33) ~[classes/:na]
        at com.example.demo.config.JaxWsHandlersAdderBeanFactoryApplicationListener.onApplicationEvent(JaxWsHandlersAdderBeanFactoryApplicationListener.java:20) ~[classes/:na]
[...]
```

* on `app` folder, edit `pom.xml` file, lines 18 and 26 so they get to be `1.5.15.RELEASE` and `1.4.4.RELEASE` respectively, and then again, `mvn clean spring-boot:run`
* should be able to reach one of http://localhost:8080/demo/try/d1, http://localhost:8080/demo/try/d2, http://localhost:8080/demo/try/ws1, http://localhost:8080/demo/try/ws2, http://localhost:8080/demo/try/env which interact with some application Spring beans.

### Things to note:
* Seems to happen only with factory beans (e.g. also with `org.springframework.ejb.access.SimpleRemoteStatelessSessionProxyFactoryBean`)
* The `app` application configuration class is loaded through `META-INF/spring.factories` file, due to some internal requirements, but that shouldn't interfere with the `${}` resolution. In our case, the Configuration classes usually `ImportResource` a pre-existing, legacy application-context xml file, and over time that configuration gets gradually migrated to Java classes. That's why this specific Spring configuration.
* The unusual behaviour seems to only happen on the `${}` resolution, when using the Spring Cloud config client, not on the Environment values retrieval
  * on `app` folder, if the `spring-cloud-starter-config` is commented out and then `mvn clean spring-boot:run`, the application successfully starts up with Spring Boot 2, retrieving values from the `com/examples/demo/props.properties` file
  * The `app` folder also contains a custom factory bean, but the JaxWs factory beans showcase better the error, as the application doesn't start up. Also, we've an `ApplicationListener` which mangles with the jaxws factory beans. Commenting it out on the configuration class and also commenting out the values at the `com/examples/demo/props.properties` file allows the application to start, but then http://localhost:8080/demo/try/ws1 shows that the value hasn't been resolved.
  * `${jaxWs.endpoint}` isn't resolved, but `#{environment['jaxWs.endpoint']}` is. http://localhost:8080/demo/try/ws1 and http://localhost:8080/demo/try/ws2 do the same thing but the former uses a bean with `${}` and the latter `#environment['jaxWs.endpoint']` (first one points out the expression hasn't been resolved, second one says endpoint is unreachable)
  * Also, while debugging we're able to see that the `Environment` contains the appropiate values when loading the FactoryBeans.

**Comment by juanpablo-santos** [comment]
Some follow-up on this

`org.springframework.cloud.autoconfigure.RefreshAutoConfiguration`, instantiates the `RefreshScopeBeanDefinitionEnhancer` bean, which is itself a `BeanDefinitionRegistryPostProcessor`, so it gets called before every other "normal" bean factory post processors (e.g.: `PropertySourcesPlaceholderConfigurer`).  

At certain point, the `RefreshScopeBeanDefinitionEnhancer` bean does (`RefreshAutoConfiguration`, lines 162-163):
`this.environment = ((BeanFactory) registry).getBean(Environment.class);`

With the given sample, querying for the `Environment` there, this line ends up on `org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory` line 838, which calls `org.springframework.beans.factory.support.AbstractBeanFactory` line 1514, which instantiates the (JaxWsProxyPort)FactoryBean, without having registered yet the `PropertySourcesPlaceholderConfigurer`. Hence the bean factory creates the bean, too early and without resolving the placeholder.

Later on, the `PropertySourcesPlaceholderConfigurer` post-processor kicks in, but it is too late then, the factory bean has already created the bean.

Our current work-around is to disable the `RefreshAutoConfiguration` class by declaring `spring.cloud.refresh.enabled=false` for all applications.

**Comment by spencergibb** [comment]
Can you try 2.1.0 snapshots? We've changed how this works. It may be worth backporting the work.

**Comment by juanpablo-santos** [comment]
Hi @spencergibb ,

thanks for taking a look at this. I've tried with 2.1.0-BUILD-SNAPSHOT and the problem still remains. At the moment of requesting the Environment on `RefreshAutoConfiguration$RefreshScopeBeanDefinitionEnhancer`, 
* the `PropertySourcesPlaceholderConfigurer` post processor hasn't been instantiated yet
* all other FactoryBeans do get instantiated as a result of requesting a bean to the beanFactory, out of their proper order

in our case that means that the jaxWs1 factorybean gets instantiated, but its placeholder isn't resolved. Note that this is a side effect of the second point above; we have issues with the placeholder resolution, but  may be there are other issues if other bean factory post processors are defined.

I've update the [sample project](https://github.com/spring-cloud/spring-cloud-config/files/2296751/sample-project-v2.zip) to further highlight this issue, extending some standard Spring classes in order to make it more clear. Basically, after unzipping and `mvn clean spring-boot:run` first on `sccs` folder and second on `app`, you should see on the latter's sysout the following chain of events:

* `RefreshAutoConfiguration$RefreshScopeBeanDefinitionEnhancer` requests a bean of type `Environment`
* `setEndpointAddress` of `jaxWs1` factory bean is called. There isn't yet any placeholder resolution in place, so the endpoint gets set as `${jaxws.endpoint}`
* `PropertySourcesPlaceholderConfigurer(WithJaxWs1BeanLog)` gets instantiated
* `jaxws.endpoint` gets resolved
* `getObject` of `jaxWs1` factory bean is called; as the value was set as `${jaxws.endpoint}`, without resolution, that value is used to create the bean

HTH,
juan pablo

**Comment by juanpablo-santos** [comment]
@spencergibb, tried to clarify as much as possible the proposed change on the former comment, please let me know if there is anything else needed.

thanks in advance,
juan pablo

**Comment by juanpablo-santos** [comment]
Hi,

upgraded this afternoon the sample to Greenwich.RC2 and the issue has been fixed (there have been changes on `RefreshAutoConfiguration$RefreshScopeBeanDefinitionEnhancer`), so I'm closing the issue. 

best regards + happy christmas :-)
juan pablo
