### ISSUE TITLE
Spring config sending it's own configuration to any request after we hook refresh

### ISSUE THREAD

**Issue by SumitBhawsar** [spring-cloud/spring-cloud-config#1109]
We are running zuul and config server in cloud where after the web hook event zuul calls spring config to refresh it's configuration in the response config-server sends its own configuration rather than zuul's.
Spring config version :spring boot:1.5.10.RELEASE.

**Comment by SumitBhawsar** [comment]
The configuration is

spring:
  cloud:
    config:
      server:
        git:
          url: https://stash/scm/api_cf/spring-config-server-config.git
          username: username
          password: password
          timeout: 60
          repos:
            zuul-api:
              pattern: zuul-api*
              url: https://stash/scm/api_cf/zuul-gateway. git
              username: username
              password: password
              timeout: 60
              force-pull: true
              clone-on-start: true

**Comment by SumitBhawsar** [comment]
Your Spring-config-server should a branch with the same name and should have a application.properties file with the same profile as zuul.

When you remove the rout "config-server" and refresh config server it's own config rather than zuul's. 

It might take some repeatations of adding and deleting the "config-server" route to replicate the issue

**Comment by SumitBhawsar** [comment]
The actual problem is at the time of we hook config server tries to clone the repo and fails to delete *.pack file.

The same bug https://github.com/spring-cloud/spring-cloud-config/issues/1109

It happening in unix and Windows both

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

> Spring config version :spring boot:1.5.10.RELEASE
This is the Spring Boot version not the Spring Cloud version, which version of Spring Cloud are you using?

**Comment by SumitBhawsar** [comment]
it's 1.4.3.RELEASE.

The root cause of the issue is ".pack" is not able to delete. 
We are facing this issue on both the Windows and unix (openshift v3) OS.

**Comment by ryanjbaxter** [comment]
It seems like this would be specific to your environment (something causing the file not to be deleted).  We are not seeing reports of this anywhere else.  Are you seeing it outside of OpenShift?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
