### ISSUE TITLE
EncryptionController error message not totally true

### ISSUE THREAD

**Issue by kizux** [spring-cloud/spring-cloud-config#1118]
https://github.com/spring-cloud/spring-cloud-config/blob/410b0ccc06b7f97a5b529497dd5d5195317a0996/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/encryption/EncryptionController.java#L218

Hello, I tried to use a custom TextEncryptor to use different encryption methods depending of application and profiles as suggested inside your documentation : https://cloud.spring.io/spring-cloud-config/single/spring-cloud-config.html#_key_management

As a first test I just tried to use an encryptor which returns the same text received in parameter either on encrypt or decrypt endpoints. Of course due to the line quoted, I got the error message : 
`No key was installed for encryption service `
because of : 
https://github.com/spring-cloud/spring-cloud-config/blob/410b0ccc06b7f97a5b529497dd5d5195317a0996/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/encryption/EncryptionController.java#L168

Which is not true. Not a big deal but I suggest to create a specific use case if the encryptor is too weak.

Up to you ! Thank for your job !

**Comment by ryanjbaxter** [comment]
Feel free to submit a PR if you would like.

**Comment by kizux** [comment]
Resolved with #1119
