### ISSUE TITLE
Enhancement [spring-cloud-config-server]: Add endpoint for .json similar to .properties, .yml, and .yaml endpoints

### ISSUE THREAD

**Issue by kevincmanning** [spring-cloud/spring-cloud-config#112]
.yml, .yaml, and .properties require 3rd party libraries to parse whereas a json can be parsed natively by JavaScript interfacing with the config server api.

The outputs coming from {name}/{profiles} is verbose (great for debugging) but does not resolve the property that is to be used. If you want to use JSON, the logic of selecting the correct property is delegated to the client.

Suggestion: Add an endpoint for {name}-{profiles}.json and for /{label}/{name}-{profiles}.json

I have this code already implemented on forked repo and committed (with tests added and small refactor). If you think this is a good idea, may I submit a pull request?

**Comment by spencergibb** [comment]
PRs are always welcome.

**Comment by kevincmanning** [comment]
Cool. :+1:

Here is the pull request: https://github.com/spring-cloud/spring-cloud-config/pull/113

**Comment by kevincmanning** [comment]
Sorry if there was a way I could have attached that pull request to this issue. My github experience is limited.

**Comment by spencergibb** [comment]
by mentioning the issue in the PR they get linked
