### ISSUE TITLE
Any pointers how to integrate spring cloud config with dropwizard

### ISSUE THREAD

**Issue by arkadutta87** [spring-cloud/spring-cloud-config#1123]
I would like to know whether its possible to use Spring Cloud Config with DropWizard. Any pointers would be highly helpful. We are using **Guice** for dependency injection.

**Comment by ryanjbaxter** [comment]
Spring Cloud Config requires Spring Boot

**Comment by spencergibb** [comment]
You can use the restful API https://github.com/spring-cloud/spring-cloud-config/blob/master/docs/src/main/asciidoc/quickstart.adoc

**Comment by bobtiernay-okta** [comment]
Might want to look at how Micronaut has done this: https://github.com/micronaut-projects/micronaut-core/tree/master/discovery-client/src/main/java/io/micronaut/discovery/spring/config
