### ISSUE TITLE
Config Server integration with Google Code Repository

### ISSUE THREAD

**Issue by aamol** [spring-cloud/spring-cloud-config#1126]
Hi , I have added this to stackoverflow as well but did not get any response there. Essentailly Config server can integarte with git repo. In google code repo they use .gitcookies for authentication but in config server we dont have any way to use that. Is there a plan to get that implemented or any other workaround for google git integration.

**Comment by ryanjbaxter** [comment]
We use GJit as the Git client, and it does not appear they support this yet
https://bugs.eclipse.org/bugs/show_bug.cgi?id=488572

**Comment by spencergibb** [comment]
Closing as this is a jgit issue.
