### ISSUE TITLE
ConfigClient not working with CloudFoundry's Discovery Client when configPath is set

### ISSUE THREAD

**Issue by andresoviedo** [spring-cloud/spring-cloud-config#1127]
I have a configserver published on custom "/config" path.

*Problem*
* With Eureka Discovery the ConfigClient connects succesfully to config server.
* However, when using CloudFoundry Discovery the ConfigClient connects to the wrong URL (with no prefix)

*As far as I understand*
* DiscoveryClientConfigServiceBootstrapConfiguration is getting the "configPath" from the ServiceInstance metadata.
* When using Eureka, the EurekaClientConfigServerAutoConfiguration registers the "configPath" to the Service Registry into the metadata and the EurekaDiscoveryClient gets metadata from instance, so it works like a charm.
* However, when using CloudFoundry Discovery, I didn't find the corresponding Post-Processor who should contribute to this metadata, so there is not "configPath" published to the metadata. Moreso, CloudFoundry's ServiceInstance interface apparently doesn't support access to the metadata got from the registry (class is ignoring metadata).  And CloudFoundry's CloudEntity containing the instance data got from the Service Registry has "meta" but it isn't variable. It has an "env" properties but it's actually the cloud-foundry's environments variables.

*Question*
How can I workaround this?

**Comment by spencergibb** [comment]
I guess there needs to be an analogous EurekaClientConfigServerAutoConfiguration in spring cloud cloud foundry, want to open the issue there?

**Comment by andresoviedo** [comment]
Thanks.  I opened the issue there:  https://github.com/spring-cloud/spring-cloud-cloudfoundry/issues/25
