### ISSUE TITLE
PropertySource trigger a RefreshScope

### ISSUE THREAD

**Issue by efenderbosch** [spring-cloud/spring-cloud-config#1131]
I've got a ``PropertySource`` that periodically polls a remote service for config. When I detect a config change, I'd like to trigger a ``RefreshScope::refreshAll`` (or optionally a sub-set of beans).

I've tried injecting a ``RefreshScope``, but none are available. I've tried injecting an ``ApplicationEventPublisher`` and publishing an ``EnvironmentChangeEvent``, but that doesn't seem to trigger a context refresh.

Is there a way to get this to happen automatically without a manual POST to actuator/refresh?

**Comment by spencergibb** [comment]
There is a `ContextRefresher` bean, but depending on when you create the `PropertySource`, it may not be available.

**Comment by efenderbosch** [comment]
We create it in the bootstrap context with a ``org.springframework.cloud.bootstrap.config.PropertySourceLocator``

**Comment by spencergibb** [comment]
If it's not there at construction, you could inject an `ObjectProvider<ContextRefresher>` and get a reference at the point of needing it.

**Comment by efenderbosch** [comment]
``ObjectProvider::getIfAvailable`` is returning null
and ``getObject`` is throwing ``NoSuchBeanDefinitionException``

I'm getting the ``ObjectProvider`` in the ``PropertySourceLocator`` like this:

```java
   @Inject
    public SSMPropertySourceLocator(AWSSimpleSystemsManagement ssm,
                                    ObjectProvider<ContextRefresher> contextRefresherProvider) {
// ...
}
```
Is there an autoconfig I haven't enabled? I've set ``management.endpoints.web.exposure.include: refresh`` in ``bootstrap.yml``

**Comment by spencergibb** [comment]
and you can't use it in the constructor

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
