### ISSUE TITLE
import project into intellij idea cause many dependency errors

### ISSUE THREAD

**Issue by clevertension** [spring-cloud/spring-cloud-config#1133]
### OS version and IDE version
macOS High Sierra 10.13.6
intellij idea 2018.2.3

when i import the project into intellij idea, it will cause many errors, it can't recognize the spring boot dependencies

![image](https://user-images.githubusercontent.com/346723/45482303-4409f400-b780-11e8-86e6-7db3eb4a01b8.png)

**Comment by clevertension** [comment]
we can see many spring boot class can not be found

![image](https://user-images.githubusercontent.com/346723/45485612-dc0cdb00-b78a-11e8-948d-8ef4513c1e6a.png)

**Comment by clevertension** [comment]
please refer to the PR
https://github.com/spring-cloud/spring-cloud-config/pull/1134

**Comment by spencergibb** [comment]
You need to activate the spring maven profile in intellij

**Comment by clevertension** [comment]
@spencergibb why this issue is closed? can you tell me the reason, very thanks

**Comment by clevertension** [comment]
i test this situation with **spring** profile activation, but it can't work, because there is no specific ${spring-boot-version} in project to depend on

**Comment by spencergibb** [comment]
I don't know what to tell you. The spring boot version is defined in the parent. We've been working with this project for 4 years in intellij successfully.
