### ISSUE TITLE
config server not add {application-name}-{profile}.yml

### ISSUE THREAD

**Issue by shenfengok** [spring-cloud/spring-cloud-config#1135]
my config server version is 2.0.1 release
in my git config repo . I have config files like below 
` application-dev.yml

 application-pro.yml

 application-qa.yml
 application.yml
 THOR-QUEST-DEV.yml
 THOR-QUEST-PRO.yml
 THOR-QUEST-QA.yml
 THOR-QUEST.yml
 THOR-USER-DEV.yml
 THOR-USER-PRO.yml
 THOR-USER-QA.yml
 THOR-USER.yml`

but when i get the url http://config-server:port/thor-user/dev

only application.yml and applicaton-dev.yml is added to property sources .

 THOR-USER-DEV.yml and  THOR-USER.yml were not added .

how can i resolve this ? thanks

**Comment by shenfengok** [comment]
> There's always been an issue using dashes in spring.application.name and config client.

I have changed my config files like this 
`application-dev.yml
application-pro.yml
application-qa.yml
application.yml
THORQUEST-DEV.yml
THORQUEST-PRO.yml
THORQUEST-QA.yml
THORQUEST.yml
THORUSER-DEV.yml
THORUSER-PRO.yml
THORUSER-QA.yml
THORUSER.yml
`

and get url http://config-server:port/thoruser/dev

sadly,it still does not not work

**Comment by spencergibb** [comment]
why are they in all caps?

**Comment by shenfengok** [comment]
> why are they in all caps?
do you mean remove the prefix 'thor',yes i just did ,when fetch http://config-server:port/user/dev,
I got  the same issue
`application-dev.yml

application-pro.yml
application-qa.yml
application.yml
QUEST-DEV.yml
QUEST-PRO.yml
QUEST-QA.yml
QUEST.yml
USER-DEV.yml
USER-PRO.yml
USER-QA.yml
USER.yml
`

**Comment by spencergibb** [comment]
I mean `THORQUEST-DEV.yml` vs `thorquest-dev.yml`. it is case sensitive.

**Comment by shenfengok** [comment]
> I mean `THORQUEST-DEV.yml` vs `thorquest-dev.yml`. it is case sensitive.

OK,I see , http://config-server:port/USER/DEV ,and it works . thanks a lot.
