### ISSUE TITLE
Git branch not updated when refreshRate is used

### ISSUE THREAD

**Issue by LukasVyhlidka** [spring-cloud/spring-cloud-config#1136]
Following scenario results in non updated configuration being returned.

- Client asks for two labels - **test** and **master** (in this order)
- RefreshRate is set (e.g. to 10 seconds)
- There is a new commit into the master branch
- When client asks for both labels again, following happens:
  - when asking for test label, remote repository is fetched and test branch is merged to fast-track the remote branch.
  - when asking for master label (in the 10 seconds window) the remote repository is not fetched, there is only a checkout to master that is not being fast-tracked - new commit is not processed (when git status in the repo it shows info that master is behind the origin/master)

I am going to create a PR that fixes this issue together with an integration test.

**Comment by LukasVyhlidka** [comment]
I would like to backport this change to 1.4.x as well... Is that possible? The altered class is pretty much the same in both versions.

**Comment by ryanjbaxter** [comment]
Closed via 80f98c3
