### ISSUE TITLE
How to use cloud config to refresh @FeignClient url properties

### ISSUE THREAD

**Issue by sj853** [spring-cloud/spring-cloud-config#1144]
i have a feignclient like this:
`@FeignClient(value = "chnbiot", url = "${ch.cloud.api-host}", path = "${ch.cloud.api-path}", fallbackFactory = DeviceApiHystrix.class)
public interface DeviceApi {
ommited 
}`
so i have a yml config like this
`ch:
  cloud:
    api-host: test.com`
when i  change ch.cloud.api-host=abc.com 
and  post refresh-url http://localhost:8888/actuator/bus-refresh
ch.cloud.api-host is changed in env 
but feign still visit the url test.com

**Comment by ryanjbaxter** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-config/issues/848
