### ISSUE TITLE
Config Server is DOWN when it can't fetch remote git repository

### ISSUE THREAD

**Issue by rsareth** [spring-cloud/spring-cloud-config#1145]
**Spring Cloud Version**: Finchley.RELEASE

**Issue**:
Our spring cloud server fetches the configuration from a git repository. Unfortunately, when git server faces a down time, our spring cloud config server goes down and then our spring boot applications go down too.

**Question**:
How can we set the frequency of the polling on the spring cloud server ?
According to the [Spring Cloud Config Server Documetation](https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html), there is no option on that. We see this in our logs:

{
"@timestamp": "2018-09-17T15:01:15.558+02:00",
"@version": "1",
"app": "app",
"env": "prod",
"level": "WARN",
"logger_name": "org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository",
"thread_name": "http-nio-8080-exec-3",
"message":
"Could not fetch remote for master remote: https://<URL_REPO>/config-prod"
}

When the git server doesn't respond at all, our server config goes down, then our spring boot applications too ! At the end, our service is down for everybody. We switch to another git server. But this approach is very ugly because we have to maintain the same repo on different git servers.

For people having solved their issue, did you switch to another way to fetch the configuration? We are thinking of using a KV database like consul.

I didn't find answer or topic here.

So, can you guide us on this issue, please?

Thank you

**Comment by ryanjbaxter** [comment]
There is `spring.cloud.config.server.git.refreshRate` which will dictate the amount of time the config server will wait (in seconds) after a failed request before trying again.

**Comment by rsareth** [comment]
Thank you @ryanjbaxter for your quick response.

But in the case, if when our config server went down because of our git repository, how does the config server behave?

Does it keep in some kind of cache the previous state of our application.properties without failing ?

Can you give me more information about that, please?

Thank you very much!

Rasmey

**Comment by ryanjbaxter** [comment]
I believe it just uses the locally cloned git repo.

**Comment by rsareth** [comment]
Thank you!
