### ISSUE TITLE
Config server to not to pull the git repo every time App is scaled

### ISSUE THREAD

**Issue by dilipmighty245** [spring-cloud/spring-cloud-config#1148]
Question

How can we make the config server to not to pull from git every time a request comes from Client?

Whenever I scale my app, Config Server is pulling the git repo and I don't wanna pull the git repo regularly, I want the client app to get the configurations from the local cache(Eg: /tmp/config-repo, where config server pull by default).

Is there any way we could make the Config Server pull the Git repo on demand?

Can anyone please suggest?

**Comment by ryanjbaxter** [comment]
Try setting `spring.cloud.config.server.git.refreshRate`.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by dilipmighty245** [comment]
Hi @ryanjbaxter 

Thanks a lot, but the use case here is config server should not take clone git unless and until I forcefully refresh(manually).
In other words, I want _spring.cloud.config.server.git.refreshRate=infinty_ , meaning, I want application to take config properties from local cache only.
Assume 5000 applications are scaling up and down in regular intervals, . so each time I scale an app, it should take from local repo only. our main goal is to lower the load on Gitlab server as much as possible.

Can you please suggest any workaround?

Thanks and regards,
Dilip

**Comment by spencergibb** [comment]
Set the refresh rate as high as possible, it should get you plenty of time between refreshes. We don't support checkout once and never update.

**Comment by dilipmighty245** [comment]
@spencergibb thanks a lot for confirmation.

**Comment by deeravi** [comment]
Hi @dilipmighty245, Were you able to find a work around to your problem ? I am facing a similar issue and would like to know if its possible to use a cache ?

**Comment by spencergibb** [comment]
We don't support that. You could manually clone the repo and use a native environment repository

**Comment by sandeepvchowhan** [comment]
I am not sure if this chat is still open,  I set this property to spring.cloud.config.server.git.refreshRate=43200(12 hours), but I still see calls to GitHub very frequently from config server, this config server is serving 40+ app clients.

I am trying to ensure that calls to GitHub happen only twice a day regardless of the number of times the client apps restart (they should get the properties config server has at that time from the previous pull).

**Comment by tamilselvan-chinnaswamy** [comment]
@sandeepvchowhan are you having health check to your config server ? at every health check it makes call to git. to avoid you can use this property `spring.cloud.config.server.health.enabled=false`

**Comment by nikolasvargas** [comment]
Thank you @tamilselvan-chinnaswamy; I was having the same problem.
