### ISSUE TITLE
When spring-cloud-context dependency added in classpath, the `org.springframework.context.ApplicationContextInitializer` will be called twice.

### ISSUE THREAD

**Issue by guanchao-yang** [spring-cloud/spring-cloud-config#1151]
### Question

When `spring-cloud-context` dependency added in classpath, the `org.springframework.context.ApplicationContextInitializer` will be called twice. If we have many ApplicationContextInitializer implementation with Spring Boot ,when `spring-cloud-context` dependency 
 added ,our application starter ApplicationContextInitializer run twice. If we have and best practice or will add some identification to distinguish bootstrap context and application context?

### Bug report

When spring-cloud-context dependency added in classpath, the `org.springframework.context.ApplicationContextInitializer` will be called twice.

### Enhancement

Suggest that when init twice `org.springframework.context.ApplicationContextInitializer` ,we should have obvious identification  to distinguish bootstrap context and application context。

Thank you so much for your reply and advice！

**Comment by guanchao-yang** [comment]
<!--
Thanks for raising a Spring Cloud issue. What sort of issue are you raising?

### Question

When `spring-cloud-context` dependency added in classpath, the `org.springframework.context.ApplicationContextInitializer` will be called twice. If we have many ApplicationContextInitializer implementation with Spring Boot ,when `spring-cloud-context` dependency 
 added ,out application starter ApplicationContextInitializer run twice. If we have and best practice or will add some identification to distinguish bootstrap context and application context?

### Bug report

When spring-cloud-context dependency added in classpath, the `org.springframework.context.ApplicationContextInitializer` will be called twice.

### Enhancement

Suggest that when init twice `org.springframework.context.ApplicationContextInitializer` ,we should have obvious identification  to distinguish bootstrap context and application context。

Thank you so much for your reply and advice！

**Comment by guanchao-yang** [comment]
@ryanjbaxter  @spencergibb Thank you so much for your reply and advice！

**Comment by spencergibb** [comment]
This is not a bug. It is the way the bootstrap context is loaded.

**Comment by guanchao-yang** [comment]
@spencergibb @ramaiahkk  Can we provide identification to distinguish bootstrap context and application context?

**Comment by spencergibb** [comment]
Check the ID of the context

**Comment by guanchao-yang** [comment]
> Check the ID of the context

The Bootstrap Application Context maybe like `org.springframework.context.annotation.AnnotationConfigApplicationContext@5d2a4eed` before `org.springframework.boot.context.ContextIdApplicationContextInitializer#initialize` handled!!!

I think this way will be ok from your official document [Here](https://cloud.spring.io/spring-cloud-static/spring-cloud.html).

```
The additional property sources are:

"bootstrap": an optional CompositePropertySource appears with high priority if any 
PropertySourceLocators are found in the Bootstrap context, and they have non-empty 
properties. An example would be properties from the Spring Cloud Config Server. See
 below for instructions on how to customize the contents of this property source.
```

We can use use environment to distinguish bootstrap context and application context like this:

```java
public static boolean isSpringCloudBootstrapEnvironment(Environment environment) {
    if (environment instanceof ConfigurableEnvironment) {
        ConfigurableEnvironment configurableEnvironment = (ConfigurableEnvironment) environment;
        PropertySource propertySource = configurableEnvironment.getPropertySources().get(BOOTSTRAP_PROPERTY_SOURCE_NAME);
        if (propertySource != null) {
            logger.debug("Current application context environment is bootstrap");
            return true;
        }
    }
    return false;
}
```

@spencergibb  @ramaiahkk  What do you think about？Agree or not?

**Comment by guanchao-yang** [comment]
@spencergibb @ramaiahkk Thank you and Waiting for your answer !
