### ISSUE TITLE
When spring-cloud-context dependency added in classpath, the `org.springframework.context.ApplicationContextInitializer` will be called twice

### ISSUE THREAD

**Issue by guanchao-yang** [spring-cloud/spring-cloud-config#1152]
> Check the ID of the context

The Bootstrap Application Context maybe like `org.springframework.context.annotation.AnnotationConfigApplicationContext@5d2a4eed` before `org.springframework.boot.context.ContextIdApplicationContextInitializer#initialize` handled!!!

I think this way will be work from your official document [Here](https://cloud.spring.io/spring-cloud-static/spring-cloud.html).

```
The additional property sources are:

"bootstrap": an optional CompositePropertySource appears with high priority if any 
PropertySourceLocators are found in the Bootstrap context, and they have non-empty 
properties. An example would be properties from the Spring Cloud Config Server. See
 below for instructions on how to customize the contents of this property source.
```

We can use environment to distinguish bootstrap context and application context like this:

```java
public static boolean isSpringCloudBootstrapEnvironment(Environment environment) {
    if (environment instanceof ConfigurableEnvironment) {
        ConfigurableEnvironment configurableEnvironment = (ConfigurableEnvironment) environment;
        PropertySource propertySource = configurableEnvironment.getPropertySources().get(BOOTSTRAP_PROPERTY_SOURCE_NAME);
        if (propertySource != null) {
            logger.debug("Current application context environment is bootstrap");
            return true;
        }
    }
    return false;
}
```

@spencergibb  @ramaiahkk  What do you think about？Or give some suggestion, Thank you very much!

> [Reference Issue](https://github.com/spring-cloud/spring-cloud-config/issues/1151)

**Comment by guanchao-yang** [comment]
@ryanjbaxter Thank You

**Comment by spencergibb** [comment]
Closing as you've opened this before
