### ISSUE TITLE
Make POST request to /monitor get status 401

### ISSUE THREAD

**Issue by scheshan** [spring-cloud/spring-cloud-config#1153]
I'm using an embedded Spring Cloud Config Server. I add the dependency of `Spring Security` and `Spring Cloud Monitor`, and set `spring.security.user.password=111111`. 

I can retrieve application's configuration, the call `curl http://user:111111@localhost:8888/myapp-dev.yml` works fine. But I can't push notifications. I make a HTTP call by using `curl -X POST -d "" -v http://user:111111@localhost:8888/monitor` and get status 401 error. When I remove Spring Security, I call the `/monitor` again and now get status 400. It seems right because I didn't pass any body.

Now I'm not sure what's the problem and if there is any settings I've missed.

**Comment by spencergibb** [comment]
You have to disable csrf

**Comment by scheshan** [comment]
@spencergibb Thanks, it works.
