### ISSUE TITLE
i want to access the * .properties, *. yml on the sub directory . Is there another way?

### ISSUE THREAD

**Issue by JangCool** [spring-cloud/spring-cloud-config#1156]
hi.

I have a question.

When accessing the git configuration file from the spring-cloud-config server, I want to access the directory structure rather than application-local.propertiesor application-dev.properties. Is there another way?

ex) 

app name : gateway

git url : https://github.com/test

spring-cloud-config server http access : 

    url : http://localhost:8888/gateway/dev

   - it is general a way.
     - file path : /gateway-dev.properties
     - file path :/gateway-service/gateway-dev.properties

  - i want it

    - git sub directory

       - gateway = {application} folder
          - local = {profiles} folder
            - application.properties file
          - dev = {profiles} folder
            - application.properties file

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

The config server only serves the configuration for the app, it does not expose the directory structure from the Git repo.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
