### ISSUE TITLE
How to make plain text files application specific in Spring cloud config server?

### ISSUE THREAD

**Issue by Swatikp** [spring-cloud/spring-cloud-config#1159]
I am working with microservices and using Spring cloud config server to store configurations centrally in a GIT repo. I have some application specific xml files which I am able to get the xml file from config server by using the following URL:
**{Spring-cloud-server-uri}/{name}/{profile}/{label}/{path}**

I am able to segregate files based upon profiles such as development, test etc., But is there any way to mention application name while saving a xml file to make it application specific.

Lets assume for yml or properties file we save them something like this :

**{application-name}-{profile-name}.properties**

But according to spring cloud documentation it gives us option only for storing it according to profile:

**https://cloud.spring.io/spring-cloud-config/multi/multi__serving_plain_text.html**

But what I want is something like this:
**log-{application-name}-{profile-name}.xml**

because withour this I dont know what is the significance of 'application' in 
**{Spring-cloud-server-uri}/{applicationname}/{profile}/{label}/{path}**

Thanks in advance, let me know if I am thinking in some direction that is not a supported feature of spring cloud config.

**Comment by ryanjbaxter** [comment]
I dont believe there is a way to do that today.

@spencergibb @dsyer any ideas?

**Comment by dsyer** [comment]
Confused. What did you think the `{name}` was in the URI path?

**Comment by ryanjbaxter** [comment]
I think what they are saying is if `{name}` in the path is the name of the file how would the distinguish that same file for multiple applications.  For if you had a file called `log.xml` but you have a `log.xml` for app A and app B how could you distinguish them?

I guess the only way to do that is to name them like `logappa-profile1.xml` and `logappb-profile1.xml`.

**Comment by dsyer** [comment]
But `{name}` _is_ the name of the application. The file name is denoted above as `{path}`. I'm confused still why that isn't what you asked for.

**Comment by Swati-Raj** [comment]
@dsyer actually that was a part of my question. Because we are just passing random value or * over there in place of 'name' to get the file, and the name doesn't actually signify anything and is there to increase the confusion. Maybe if you could tell how can we use them in application context?

**Comment by dsyer** [comment]
The `{name}` is the same as in the normal config properties endpoint - it is the application name. Whatever you use to get the config properties will work for plain text files.

**Comment by Swati-Raj** [comment]
@dsyer but log files aren't application specific, they can be read by any application, so how does it matter?

**Comment by dsyer** [comment]
It's up to the caller to put whatever value makes sense to it in the `{name}`. Normally "application" is shared between apps (because that's the way the config properties work), but if you don't use placeholders it's irrelevant. The original question was "How to make plain text files application specific?" and the answer is "they already are".

**Comment by Swati-Raj** [comment]
Yeah Thank you so much @dsyer

**Comment by ryanjbaxter** [comment]
@dsyer so if i make a request to `/app1/dev/log.xml` the file that will get returned is `app1-dev-log.xml`?

**Comment by dsyer** [comment]
No, it is returned as a binary blob (I don't know if there is a way to attach a filename, since I don't think it is multipart). The "app1" part is only significant in the way the contents are resolved from the backend.

**Comment by Swatikp** [comment]
@ryanjbaxter this is what I was looking for, from the way of using it I thought the normal behaviour should be like this.
