### ISSUE TITLE
spring-cloud-config-client should not depend on spring-boot-starter

### ISSUE THREAD

**Issue by voidengineer** [spring-cloud/spring-cloud-config#116]
As `spring-cloud-config-client` is first and foremost a library and not an application, it should not depend on `spring-boot-starter` which in turn pulls in `spring-boot-starter-logging` which in turn pulls in `logback-classic` which most likely is not needed by `spring-cloud-config-client` at all.

IMHO libraries should carefully define which libraries they need and only depend on those. Applications/microservices on the other hand can use the Spring Boot Starter POMs to get a consistent set of dependencies.

I would guess `spring-cloud-config-client` only needs `spring-boot`, `spring-boot-autoconfigure` and `slf4j-api` (and `spring-security-crypto`, which is managed by its own anyway).

**Comment by dsyer** [comment]
I think `spring-boot-starter` is pretty innocuous (just some logging dependencies and spring-boot), but I suppose I take the point. We probably won't change anything in 1.0.*. If you don't like logback you can exclude `spring-boot-starter-logging`.
