### ISSUE TITLE
config server does not point out proper git clone errors 

### ISSUE THREAD

**Issue by maslano** [spring-cloud/spring-cloud-config#1160]
I have migrated from spring cloud edgware to finchley. The config server stopped serving configuration with a 404 and JSON response

{
    "timestamp": "2018-10-09T11:41:55.500+0000",
    "status": 404,
    "error": "Not Found",
    "message": "Cannot clone or checkout repository: MYREPOSITORYURI",
    "path": "/application/development/develop"
}

I could not figure out what is wrong, so I have started debugging. It turned out that there is a certificate validation issue in JGitEnvironmentRepository, GitAPIException is being caught in line 562 and is theoretically rethrown further up the stack. The problem was that there is a new property 'skipSslValidation' which I had to set. In edgeware that was a default and such property did not exist. Obviously this property is not a problem, except that I did not know that its SSL that is a problem.

What is the real problem, its that the certificate exception was swallowed and did not show up anywhere. I even turned on log level TRACE before I started debugging and still was not able to figure out what is the problem. It seemed like the repository is not found, and I would have assumed that If I didnt know the supplied URI did work on edgeware.... 

So I believe there is a need for some additional logging or additional REST responses, so whoever needs to figure out what is wrong with their repository does not need to debug the entire spring cloud config server code to find out the location where its failing and see the real exception....

**Comment by ryanjbaxter** [comment]
Closed via 2e5933a
