### ISSUE TITLE
RabbitMQ CachingConnectionFactory with @RefreshScope Annotation to Report Error

### ISSUE THREAD

**Issue by cambierr** [spring-cloud/spring-cloud-config#1166]
In my current setup, I have a configuration class exposing a `CachingConnectionFactory` bean like so:

```java
@Bean
    @RefreshScope
    public CachingConnectionFactory cachingConnectionFactory() throws Exception {
        
        RabbitConnectionFactoryBean factory = new RabbitConnectionFactoryBean();
        factory.setPort(port);
        factory.setUsername(username);
        factory.setPassword(password);
        factory.setVirtualHost(vhost);
        factory.setRequestedHeartbeat((int) (heartbeatPeriod / 1000));
        factory.setMetricsCollector(metricsCollector);
        factory.afterPropertiesSet();

        String localApplicationName = context.getId().split(":")[0];
        AtomicInteger connectionCounter = new AtomicInteger();

        CachingConnectionFactory connectionFactory = new CachingConnectionFactory(factory.getObject());
        connectionFactory.setConnectionNameStrategy(connectionFactory1 -> localApplicationName + "#" + connectionCounter.incrementAndGet());

        List<ServiceInstance> rabbitHosts = discoveryClient.getInstances("rabbitmq");
        StringJoiner sj = new StringJoiner(",");
        if (rabbitHosts.size() > 0) {
            LOGGER.info("Found " + rabbitHosts.size() + " instances of RabbitMQ, using them !");
            for (ServiceInstance rabbitmq : rabbitHosts) {
                sj.add(rabbitmq.getHost() + ":5672");
            }
        } else {
            LOGGER.info("No instance of RabbitMQ, falling back to ${rabbitmq.hosts} !");
            for (String rabbitmq : hosts) {
                if (!rabbitmq.isEmpty()) {
                    sj.add(rabbitmq);
                }
            }
        }

        if (sj.length() > 0) {
            connectionFactory.setAddresses(sj.toString());
        }

        return connectionFactory;
    }
```

and this is fine for months. Bu I'm now looking at adding `@RefreshScope` to both my configuration class and the exposed `CachingConnectionFactory` bean, which creates this error:

```text
...
Caused by: java.lang.NullPointerException: null
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:585) ~[spring-rabbit-1.7.10.RELEASE.jar:na]
	at <internal>
	at <internal>
	at <internal>
	at <internal>
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at <internal>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	... 161 common frames omitted
```

This seems to be thrown here:
```java
@Override
	public final Connection createConnection() throws AmqpException {
		Assert.state(!this.stopped, "The ApplicationContext is closed and the ConnectionFactory can no longer create connections.");
		synchronized (this.connectionMonitor) {  // <---- connectionMonitor is null, as well as all other fields
```
but, `connectionMonitor` is declared using: `private final Object connectionMonitor = new Object();`

So at this point, I'm not sure to know how to solve this.

Base on **boot 1.5.16.RELEASE** and **cloud Edgware.SR3**

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by cambierr** [comment]
Hi @ryanjbaxter ! thanks for quick reply.
Here is a sample minimalist project that showcases the error I'm encountering: [sample.zip](https://github.com/spring-cloud/spring-cloud-config/files/2477604/sample.zip)

Here is the stacktrace I'm seeing:
```txt
java.lang.NullPointerException
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:585)
	at be.rc.rabbitrefresherror.Application.run(Application.java:29)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at be.rc.rabbitrefresherror.Application.main(Application.java:21)
```

**Comment by ryanjbaxter** [comment]
Appears to be the same issue as https://github.com/spring-cloud/spring-cloud-config/issues/986

**Comment by cambierr** [comment]
I saw it but since it was closed a just created this one. Any idea of where this behavior is coming from ?

**Comment by ryanjbaxter** [comment]
No looked at it a bit and it seems like it might have to do with the class being a proxy but I cant explain why.  I am going to bring this up at our team meeting next week

**Comment by cambierr** [comment]
Any news on this one ?

**Comment by spencergibb** [comment]
I have no idea. Maybe @garyrussell could help?

**Comment by garyrussell** [comment]
I have no idea - I am not familiar enough with `@RefreshScope` but I thought it only works with passive objects (such as properties etc). The connection factory is an active object maintaining RabbitMQ connections and channels, so swapping it out at runtime will likely cause many problems.

There is definitely something weird going on; the NPE is on this line...

```java
synchronized (this.connectionMonitor) {
```

And we have

```java
	private final Object connectionMonitor = new Object();
```

So it is impossible to get an NPE, unless there's some mojo going on that avoids normal object instantiation.

**Comment by ryanjbaxter** [comment]
@garyrussell so are we saying that we should not put the connection factory in a `@RefreshScope`?  So is it not supported?

**Comment by garyrussell** [comment]
@ryanjbaxter I simply don't know.

Assuming a refresh will call `destroy()` (it's a `DisposableBean`), then any users of the connection maintained by the old instance will get an error and reconnect (presumably via the new instance). So, on the face of it, it should work (albeit with some nasty side-effects for in-process operations), but I can't explain why (s)he's getting an NPE on a `final` field.

I'll try to find to some to play with it.

**Comment by garyrussell** [comment]
I just ran his/her test app and the problem is refresh scope uses a CGLIB proxy by default and

```java
	public final Connection createConnection() throws AmqpException {
		Assert.state(!this.stopped, "The ApplicationContext is closed and the ConnectionFactory can no longer create connections.");
		synchronized (this.connectionMonitor) {
```

CGLIB can't proxy final methods.

Using `@RefreshScope(proxyMode = ScopedProxyMode.INTERFACES)` and injecting via its `ConnectionFactory` interface works.

```java
    @Autowired
    private ConnectionFactory cachingConnectionFactory;
```

But, as I said, you'll get some nasty side effects if the factory is refreshed; in particular publish operations will need to be configured with retry.

**Comment by ryanjbaxter** [comment]
Thanks @garyrussell
