### ISSUE TITLE
Set accept header in ConfigServicePropertySourceLocator

### ISSUE THREAD

**Issue by deveth0** [spring-cloud/spring-cloud-config#1169]
We currently face an issue which was already reported multiple times:

https://github.com/spring-cloud/spring-cloud-config/issues/306
https://github.com/spring-cloud/spring-cloud-config/issues/368

If you run a spring-cloud server and eureka-server in the same service, the output of the config-server does no longer default to JSON but XML.
This especially breaks the usage of lists in your configuration as they are not serialised correctly.

A workaround is to exclude the jackson-xml dependency in the eureka-server but this might cause other problems. 
As by now, I ask myself if it would not be the easiest/best solution to explicitly set the accept header in config-client so that it requests the correct serialised version of the configuration. 
This bypasses the serialisation into XML and communication between config-server / config-client works fine again.

**Comment by ryanjbaxter** [comment]
This is certainly an edge case, I dont think so many people are combining the config server and eureka server.  If you want to submit a PR that makes it work that would be welcomed.

**Comment by deveth0** [comment]
ok :) before I do something wrong: is there any case, when the client should NOT use JSON?

**Comment by ryanjbaxter** [comment]
the client can serve text and html files as well

**Comment by deveth0** [comment]
you mean consume, right?

**Comment by ryanjbaxter** [comment]
I meant the server not the client (edited my original comment)

**Comment by deveth0** [comment]
ok thanks :) will try to get something in place!

**Comment by deveth0** [comment]
Can you please have a look into this?

**Comment by ryanjbaxter** [comment]
If you would like us to look at something please submit a PR.

**Comment by spencergibb** [comment]
Closed via 7f9c9dd4ca2f571cba4d957049ee2c5b5bc9deba

**Comment by deveth0** [comment]
Thx!
