### ISSUE TITLE
Webhooks can't find the page with the url

### ISSUE THREAD

**Issue by Laverrr** [spring-cloud/spring-cloud-config#1173]
![_20181026170424](https://user-images.githubusercontent.com/39804660/47556853-ee5d6580-d941-11e8-8b73-0107440f2c18.png)
![_20181026170504](https://user-images.githubusercontent.com/39804660/47556855-ef8e9280-d941-11e8-8fa2-1bbdeb89b673.png)
![_20181026170539](https://user-images.githubusercontent.com/39804660/47556858-f0bfbf80-d941-11e8-8c2c-6839f902791a.png)
 Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (PushbackInputStream); line: 1, column: 286] (through reference chain: java.util.LinkedHashMap["commits"])

**Comment by Laverrr** [comment]
what‘s more, my spirng cloud version is Finchley.SR1

**Comment by ryanjbaxter** [comment]
Can you provide the request being made by GitHub?

**Comment by Laverrr** [comment]
@ryanjbaxter the payload is as follow
{
  "ref": "refs/heads/master",
  "before": "fbcf8161e33e2e2af849ddba5a75be0ff18be27f",
  "after": "0fd91ae87cc05f15c6218cf131f7b8545d8c4f1c",
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/Laverrr/config/compare/fbcf8161e33e...0fd91ae87cc0",
  "commits": [
    {
      "id": "0fd91ae87cc05f15c6218cf131f7b8545d8c4f1c",
      "tree_id": "00b74ebb0ba6c37baff3bdfb456ecd9167990cc0",
      "distinct": true,
      "message": "Update order-dev.yml",
      "timestamp": "2018-10-26T16:46:27+08:00",
      "url": "https://github.com/Laverrr/config/commit/0fd91ae87cc05f15c6218cf131f7b8545d8c4f1c",
      "author": {
        "name": "Laverrr",
        "email": "39804660+Laverrr@users.noreply.github.com",
        "username": "Laverrr"
      },
      "committer": {
        "name": "GitHub",
        "email": "noreply@github.com",
        "username": "web-flow"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "order-dev.yml"
      ]
    }
  ],
  "head_commit": {
    "id": "0fd91ae87cc05f15c6218cf131f7b8545d8c4f1c",
    "tree_id": "00b74ebb0ba6c37baff3bdfb456ecd9167990cc0",
    "distinct": true,
    "message": "Update order-dev.yml",
    "timestamp": "2018-10-26T16:46:27+08:00",
    "url": "https://github.com/Laverrr/config/commit/0fd91ae87cc05f15c6218cf131f7b8545d8c4f1c",
    "author": {
      "name": "Laverrr",
      "email": "39804660+Laverrr@users.noreply.github.com",
      "username": "Laverrr"
    },
    "committer": {
      "name": "GitHub",
      "email": "noreply@github.com",
      "username": "web-flow"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "order-dev.yml"
    ]
  },
  "repository": {
    "id": 154492402,
    "node_id": "MDEwOlJlcG9zaXRvcnkxNTQ0OTI0MDI=",
    "name": "config",
    "full_name": "Laverrr/config",
    "private": false,
    "owner": {
      "name": "Laverrr",
      "email": "39804660+Laverrr@users.noreply.github.com",
      "login": "Laverrr",
      "id": 39804660,
      "node_id": "MDQ6VXNlcjM5ODA0NjYw",
      "avatar_url": "https://avatars0.githubusercontent.com/u/39804660?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Laverrr",
      "html_url": "https://github.com/Laverrr",
      "followers_url": "https://api.github.com/users/Laverrr/followers",
      "following_url": "https://api.github.com/users/Laverrr/following{/other_user}",
      "gists_url": "https://api.github.com/users/Laverrr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Laverrr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Laverrr/subscriptions",
      "organizations_url": "https://api.github.com/users/Laverrr/orgs",
      "repos_url": "https://api.github.com/users/Laverrr/repos",
      "events_url": "https://api.github.com/users/Laverrr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Laverrr/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Laverrr/config",
    "description": null,
    "fork": false,
    "url": "https://github.com/Laverrr/config",
    "forks_url": "https://api.github.com/repos/Laverrr/config/forks",
    "keys_url": "https://api.github.com/repos/Laverrr/config/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Laverrr/config/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Laverrr/config/teams",
    "hooks_url": "https://api.github.com/repos/Laverrr/config/hooks",
    "issue_events_url": "https://api.github.com/repos/Laverrr/config/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Laverrr/config/events",
    "assignees_url": "https://api.github.com/repos/Laverrr/config/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Laverrr/config/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Laverrr/config/tags",
    "blobs_url": "https://api.github.com/repos/Laverrr/config/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Laverrr/config/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Laverrr/config/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Laverrr/config/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Laverrr/config/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Laverrr/config/languages",
    "stargazers_url": "https://api.github.com/repos/Laverrr/config/stargazers",
    "contributors_url": "https://api.github.com/repos/Laverrr/config/contributors",
    "subscribers_url": "https://api.github.com/repos/Laverrr/config/subscribers",
    "subscription_url": "https://api.github.com/repos/Laverrr/config/subscription",
    "commits_url": "https://api.github.com/repos/Laverrr/config/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Laverrr/config/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Laverrr/config/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Laverrr/config/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Laverrr/config/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Laverrr/config/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Laverrr/config/merges",
    "archive_url": "https://api.github.com/repos/Laverrr/config/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Laverrr/config/downloads",
    "issues_url": "https://api.github.com/repos/Laverrr/config/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Laverrr/config/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Laverrr/config/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Laverrr/config/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Laverrr/config/labels{/name}",
    "releases_url": "https://api.github.com/repos/Laverrr/config/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Laverrr/config/deployments",
    "created_at": 1540381981,
    "updated_at": "2018-10-26T08:33:41Z",
    "pushed_at": 1540543588,
    "git_url": "git://github.com/Laverrr/config.git",
    "ssh_url": "git@github.com:Laverrr/config.git",
    "clone_url": "https://github.com/Laverrr/config.git",
    "svn_url": "https://github.com/Laverrr/config",
    "homepage": null,
    "size": 4,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "stargazers": 0,
    "master_branch": "master"
  },
  "pusher": {
    "name": "Laverrr",
    "email": "39804660+Laverrr@users.noreply.github.com"
  },
  "sender": {
    "login": "Laverrr",
    "id": 39804660,
    "node_id": "MDQ6VXNlcjM5ODA0NjYw",
    "avatar_url": "https://avatars0.githubusercontent.com/u/39804660?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Laverrr",
    "html_url": "https://github.com/Laverrr",
    "followers_url": "https://api.github.com/users/Laverrr/followers",
    "following_url": "https://api.github.com/users/Laverrr/following{/other_user}",
    "gists_url": "https://api.github.com/users/Laverrr/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Laverrr/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Laverrr/subscriptions",
    "organizations_url": "https://api.github.com/users/Laverrr/orgs",
    "repos_url": "https://api.github.com/users/Laverrr/repos",
    "events_url": "https://api.github.com/users/Laverrr/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Laverrr/received_events",
    "type": "User",
    "site_admin": false
  }
}

**Comment by Laverrr** [comment]
@ryanjbaxter May be I should further describe my problem. I use config-server in the eureka and use GitHub as my remote repository and I also use rabbitMQ to connect the config-server and config-client.
In my local env ,I use postman to send a post with the url (localhost:8080/actuator/bus-refresh), it works (config-client did copy the config from GitHub). But when it comes to Webhooks , I expose my port and change the url into natappfree.cc/monitor , then seems nothing happen and I check the post require at GitHub and that was the reason why I raise the issue.

**Comment by ryanjbaxter** [comment]
I tested this with my own web app using Finchley.SR2 and it worked fine

**Comment by spencergibb** [comment]
If it was it is fixed now

**Comment by ryanjbaxter** [comment]
No just pointing out the version I used not that it was bug

**Comment by ryanjbaxter** [comment]
I’m going to close this for now until you can provide a reproducible sample
