### ISSUE TITLE
Property spring.cloud.config.server.native.default-label is being ignored

### ISSUE THREAD

**Issue by sunruh** [spring-cloud/spring-cloud-config#1184]
The value of `spring.cloud.config.server.native.default-label`, which should default to `master` is always overwritten by the value of `spring.cloud.config.server.default-label`.

If `server.default-label` is non-null, this behaviour is correct and consistent with SCM-based repositories, but in case `server.default-label` is null, the native repository's setting should not be overwritten.

The Git and SVN repository factories check `server.default-label` and only set the default label on the created repository if it is non-null.

**Comment by ryanjbaxter** [comment]
Closed via cabc554
