### ISSUE TITLE
Automatically refresh config every N seconds

### ISSUE THREAD

**Issue by adamsiemion** [spring-cloud/spring-cloud-config#1187]
I use Config Server for PCF and spring-cloud-config-client in the services deployed on PCF. The server is configured with a git repository, push notifications from the server are not enabled. The services use actuator so it is possible to manually trigger the config refresh by calling /actuator/refresh. However it would be great if the spring-cloud-config-client provided a way to automatically refresh the configuration fetched from the Config Server every N (configurable) seconds.

**Comment by spencergibb** [comment]
We've closed requests like this in the past. Polling if very inefficient. Using /monitor with webhooks is a better approach.

**Comment by spencergibb** [comment]
You can do this simply on your own with `@Scheduled` and the `ContextRefresher` bean.

**Comment by adamsiemion** [comment]
@spencergibb thanks for the reply, good idea with `@Scheduled`, i'll go with this approach.
