### ISSUE TITLE
Using cloud config to serve certificate and log4j in simple way, such as:

### ISSUE THREAD

**Issue by zhaoshenhao** [spring-cloud/spring-cloud-config#1189]
Can we use cloud config to serve certificate and log4j in simple way, such as:

server.ssl.key-store=cloudconfig:/{app}/{profile}/{label}/{path}?

or

server.ssl.key-store=cloudconfig-server-url-w-cred:/{app}/{profile}/{label}/{path}?

Thanks a lot,

**Comment by spencergibb** [comment]
Not currently

**Comment by zhaoshenhao** [comment]
Then is there any sample code to pull certificate and log.properties and inject into spring boot code. 

Thanks a lot,

**Comment by spencergibb** [comment]
I don't know of any
