### ISSUE TITLE
How to configure spring-cloud-config if we want the encryption/decryption on client 

### ISSUE THREAD

**Issue by seno5979** [spring-cloud/spring-cloud-config#119]
Hi,
Is it possible to use spring cloud-config, but we don't want to use the encryption and decryption using server key ?

The idea is the config-server only stored the property value as it is, and the client will use their own key to encrypt / decrypt the property value.

Thanks.

**Comment by yukatan** [comment]
Is it posible?? I would like to do the same. I want the properties encrypted over http and decrypt then on the client side.

**Comment by 8a8aleo** [comment]
Then just omit the {cipher} prefix off the value

**Comment by spencergibb** [comment]
@dsyer is this possible?

**Comment by dsyer** [comment]
Should work already I think (the config server properties are the same as any others in principle). There might be a property source ordering issue in 1.0 (fixed in 1.1 IIRC).

**Comment by kimec** [comment]
If you want the decryption to happen on the client side only, the config server configuration property ```spring.cloud.config.server.encrypt``` has to be set to ```false```. Otherwise server decrypts the value on its side and sends it to the client in clear text. It seems to work this way in at least ```Brixton.BUILD-SNAPSHOT```.

**Comment by dsyer** [comment]
See also #305 and #349
