### ISSUE TITLE
Config Server Vaulth Healthcheck doesn't attempt to retry the redirected Vault URL for High Availability Vault

### ISSUE THREAD

**Issue by rhall-pivotal** [spring-cloud/spring-cloud-config#1190]
Hi Spring Cloud Team,

A customer reported a problem with SCS config-server when using vault.

According to Vault High Availability, the endpoint could be at either standby or active status: https://www.vaultproject.io/docs/internals/high-availability.html

If by accident config-server vault healthcheck reaches out to the standby endpoint, it seems config-server doesn’t retry the redirected url but reports vault server is down, log entry from the config server:
```
2018-11-08T13:54:16.48-0500 [APP/PROC/WEB/0] OUT 2018-11-08 18:54:16.489  INFO 18 --- [nio-8080-exec-2] i.p.s.c.h.ConfigServerHealthEndpoint     : Health status: DOWN. 
Health details: {vault=DOWN {vault-1=DOWN {server={scheme=https, port=8243, host=gmconfig-vault.gm.com}, initialized=true, sealed=false, standby=true, replication_performance_mode=disabled, 
replication_dr_mode=primary, server_time_utc=1541703256, version=0.10.3+prem, cluster_name=vault-cluster-b1ce0ea0, cluster_id=c1a581aa-98ca-3a27-3b02-cde38b923e53, error=Vault is in standby mode.}},
 git=UP {git-1=UP {repository={uri=https://bitbucket.gm.com/scm/gdo/vdm.git}}}, diskSpace=UP {total=1073741824, free=905228288, threshold=10485760}}
```

According to config-server source code, vault server returns status code `429`: https://github.com/pivotal-cf/spring-cloud-service-broker/blob/master/config-server/src/main/java/io/pivotal/springcloud/config/health/VaultHealthIndicator.java#L126
```
} else if (e.getStatusCode().equals(HttpStatus.TOO_MANY_REQUESTS)) {
                builder.withDetail("error", "Vault is in standby mode.");
}
``` 
Which is `standbycode`: https://www.vaultproject.io/api/system/health.html

Could you please advise? Thanks!

**Comment by rhall-pivotal** [comment]
For Pivotal Team members, the related ticket is 185686 - https://pivotal.lightning.force.com/lightning/r/Case/5000e00001R0HLbAAN/view

**Comment by spencergibb** [comment]
Quoting @mp911de from slack:

> Vault has two deployment options. Either with a load balancer or without. With LB is slightly favorable as you need to configure only a single endpoint. No special config needed in our Vault integrations.
Looking at the ticket above that’s all correct behavior. Pointing to an individual node will report node status (Http status 429 for node in stand-by). Another option could be introducing cluster awareness. This option seems to add too much complexity to just solve a health check issue.

Our suggestion is to put vault behind a load balancer.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
