### ISSUE TITLE
"Serving plain text" - encoding ? consuming as byte[] ?

### ISSUE THREAD

**Issue by Petikoch** [spring-cloud/spring-cloud-config#1191]
Hi,

I'm using `spring-cloud-config-server 2.0.2` together with `spring-boot-starter-web 2.0.6`. 

For a non-spring legacy application, I'd like to use the feature "serving plain text" of the config-server. The idea is to embed Apache HTTP-Client 4.5.x into the legacy application to access the files of the config-server.

I wondered about the behaviour of the RestController of config-server regarding **file-encoding** / **mime-types**. To understand the behaviour, I put some breakpoints in `org.springframework.cloud.config.server.resource.ResourceController` and started the spring-config server in the Debugger.

Observation:
All HTTP GET requests are handled by the `retrieve` method returning a `String`. The implementation reads the file hardcoded using `UTF-8`. Adding a HTTP-Header `Content-Type=application/octet-stream` in my HTTP request does not change the behaviour, altough there is a `retrieve` method returning `byte[]` .  

Questions:

1. Do we have here a bug, since `Content-Type=application/octet-stream` of the HTTP request is not respected?

2. There's no documentation about the file encoding. Should the implicit `UTF-8` encoding be documented in the "serving plain text" feature? 

Best regards,
Peti

**Comment by dsyer** [comment]
> Adding a HTTP-Header Content-Type=application/octet-stream in my HTTP request does not change the behaviour

Don't you need `Accept` (not `Content-Type`)?

The UTF-8 encoding is the default in Spring Boot I think. It is documented there, but we could provide a link.

**Comment by Petikoch** [comment]
Thanks a lot @dsyer , you are absolutely right! Making the HTTP request using `Accept=application/octet-stream` in the HTTP Header is properly dispatched to `retrieve` returning `byte[]`. My fault (blush).

However, extending the excellent documentation with some more details regarding the `UTF-8` default for "text files" and how to get a config file as byte[] would be helpful for others in the future, I think.

Thanks again,
Peti

PS: 1 of 3 of the public methods `retrieve` methods in `ResourceController` are `synchronized`, the other 2 are not.
