### ISSUE TITLE
Support to server binary files

### ISSUE THREAD

**Issue by andresoviedo** [spring-cloud/spring-cloud-config#1195]
**Enhancement**

I would like to be able to
* store **binary files** as part of the application configuration.
* store XML, JSon, Pdf or any other binary file in the config repo.
* call the config server Rest API to get my file:

For instance:

    https://config-server.example.com/my-app/my-profile/my-label/some-binary-file.pdf

I did a test with a binary file. The file is returned with a 200 status, but I don't know why the returned file is corrupted (less bytes than expected)

**Comment by spencergibb** [comment]
Duplicates #926

**Comment by andresoviedo** [comment]
Thanks for the feedback @spencergibb
