### ISSUE TITLE
jdbcUrl doens't work with <spring-cloud.version>Greenwich.M2</spring-cloud.version> or <spring-cloud.version>Greenwich.M2</spring-cloud.version>

### ISSUE THREAD

**Issue by fanghongwei** [spring-cloud/spring-cloud-config#1196]
jdbcUrl doens't work with <spring-cloud.version>Greenwich.M2</spring-cloud.version> or <spring-cloud.version>Greenwich.M2</spring-cloud.version>

<spring-cloud.version>Greenwich.M1</spring-cloud.version> is working fine

**Comment by spencergibb** [comment]
What about it doesn't work? I'm afraid you have not supplied is enough information to help you.

**Comment by fanghongwei** [comment]
sorry, I should mention more details

we are using cloud foundry,  normally we create a db service (or credhub) and our application will bind to the service, we define the service (or credhub) like  {"jdbcUrl": "db connection info"}  if we are using Greenwich.M2 or M3 it will not work. but M1 is working fine. hope it's clear

**Comment by fanghongwei** [comment]
I think this is because of connectors is not configured properly?

<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cloud-connectors</artifactId>
		</dependency>

**Comment by ryanjbaxter** [comment]
Sounds like you should open an issue with spring-cloud-connectors
