### ISSUE TITLE
Spring Cloud Config (Server) Monitor does not send events to clients via RabbitMQ

### ISSUE THREAD

**Issue by dnijssen** [spring-cloud/spring-cloud-config#1197]
Consider the following usecase: https://stackoverflow.com/questions/53426608/spring-cloud-config-server-monitor-does-not-send-events-to-clients-via-rabbitm

So my `configurationserver` fetches the properties for the `configurationclient` via a Git repository (namely https://github.com/dnijssen/configuration), when a change is made I'll trigger the /monitor endpoint on my `configurationserver` manually (just for testing). Which is supposed to send an event via RabbitMQ.

I've noticed this issue does not occur when using Spring Boot 2.0.6.RELEASE and Spring Cloud Dependencies Finchley.SR2. However since the combination of Spring Boot 2.1.0.RELEASE and Finchley.SR2 are not possible, I tried upgrading to Greenwich.M3 which does not throw exceptions anymore, however its not broadcasting the refresh events either... 

Seems like a regression thing to me. Maybe related, maybe not, on startup with 2.1.0 RELEASE / Greenwich.M3 I'll also receive the following warnings:

```
2018-11-22 15:07:19.353  WARN 2980 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'bus-env' contains invalid characters, please migrate to a valid format.
2018-11-22 15:07:20.782  WARN 2980 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'bus-refresh' contains invalid characters, please migrate to a valid format.
```

**Comment by ryanjbaxter** [comment]
Fixed in http://github.com/spring-cloud/spring-cloud-bus/issues/139
