### ISSUE TITLE
Unable to change git branch | config server only reading from master branch

### ISSUE THREAD

**Issue by ahsannaseem** [spring-cloud/spring-cloud-config#1201]
I am trying to configure spring cloud server to read from branch other then master say `foo` but no matter what environment variables i pass it keeps on showing config files from master branch Below are variables I am using: 

config.search.paths = appconfig,awsconfig,awsinfraconfig
git.local.uri = file:///${user.home}/config_repos/${spring.application.name}
git.remote.uri = ssh://careem@vault.phacility.com/diffusion/413/core-configs-qa.git
spring.cloud.config.allowOverride = true
spring.cloud.config.allowOverrideNone = true
spring.cloud.config.server.git.default-label = foo(_)

I tried looking to spring docs and do changes in variables but not sure why its keep pulling from `master` 

```
{
"name": "test-service",
"profiles": [
"qa"
],
"label": "master",
"propertySources": [
{
"name": "file:////root/config_repos/config-service/master/test-service.yml#qa",
```

**Comment by spencergibb** [comment]
Why do you have `foo(_)` and not just `foo`?

**Comment by ahsannaseem** [comment]
@spencergibb thanks for your input I tested with both `foo` and `foo(_)` but result is same

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by ahsannaseem** [comment]
problem is resolved when I used `git.default.branch=master`
