### ISSUE TITLE
Send `/monitor` request occured 400 bad request.

### ISSUE THREAD

**Issue by mstao** [spring-cloud/spring-cloud-config#1202]
I use postman to send `http://localhost:8888/monitor` post request to refresh configuration from gitlab, but there occured 400 error:
```
{
    "timestamp": "2018-11-26T07:00:49.440+0000",
    "status": 400,
    "error": "Bad Request",
    "message": "Required request body is missing: public java.util.Set<java.lang.String> org.springframework.cloud.config.monitor.PropertyPathEndpoint.notifyByPath(org.springframework.http.HttpHeaders,java.util.Map<java.lang.String, java.lang.Object>)",
    "path": "/monitor"
}
```

I use `http://localhost:8888/actuator/bus-refresh` to refresh configuration, all is ok, but I can't use it to set webhooks in gitlab.

spring clould version is `Finchley.RELEASE`, spring boot version is `2.0.3.RELEASE`,  config server dependencies：
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-config-server</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-config-monitor</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-bus-amqp</artifactId>
</dependency>		
```

**Comment by ryanjbaxter** [comment]
did you send a body in the request?  `/monitor` will expect something in the body.

**Comment by mstao** [comment]
No , I don't know what I should send in the request, and I found this doc: http://cloud.spring.io/spring-cloud-config/single/spring-cloud-config.html#_push_notifications_and_spring_cloud_bus,  there is nothing  about `/monitor` which will expect something in the body. If so, what I should send in the body?

I want to use `/monitor` as url in gitlab webhooks , like:

![image](https://github.com/ZZULI-TECH/interview/blob/master/images/gitlab_webhooks.png?raw=true)

**Comment by spencergibb** [comment]
Then you would need to send the gitlab body. For testing you can also send a form url encoded body with a variable named path with the name of the service.
