### ISSUE TITLE
how config client change configuration value

### ISSUE THREAD

**Issue by springAppl** [spring-cloud/spring-cloud-config#1209]
I see spring-cloud-config-client-.1.4.5.RELEASe source code. I think the flow is:
1ConfigClientWatch
2ContextRefresher
3ConfigurationPropertiesRebinder
ConfigurationPropertiesRebinder.rebind(String name) method will recreate  bean  and new configuration value will be inject into bean.  I don't  really know where configuration values are changed in Environment.   I think may be in ContextRefresher.addConfigFilesToEnvironment(). 
`
if (target.contains(name)) {
	target.replace(name, source);
}
`
But it is wired, target and source are from the same context, and no configuration from remote config server.

**Comment by ryanjbaxter** [comment]
I am not sure what the question is, can you elaborate?

**Comment by springAppl** [comment]
Embarrassed. Could you give an architecture guide for configserver.
