### ISSUE TITLE
Label Fallback not working with Composite env

### ISSUE THREAD

**Issue by rs017991** [spring-cloud/spring-cloud-config#1213]
Bug Summary
---
We'd like to take advantage of label fallback(setting **spring.cloud.config.label: myfeature,master**), but this does not work when a composite env is used.
<details><summary>Click to see config JSON that is representative of our typical setup</summary>
<p>

```
{
	"composite":
	[
		{
			"git":
			{
				"pattern": "*service*",
				"uri": "https://github.mycorp.com/my-org/my-repo",
				"label": "master",
				"searchPaths": "services"
			}
		},
		{
			"git":
			{
				"pattern": "*tool*",
				"uri": "https://github.mycorp.com/my-org/my-repo",
				"label": "master",
				"searchPaths": "tools"
			}
		},
		{
			"git":
			{
				"uri": "https://github.mycorp.com/my-org/my-repo",
				"label": "master",
				"searchPaths": "global"
			}
		}
	],
	"encrypt":
	{
		"key": "-----BEGIN PRIVATE KEY-----\nREDACTED\n-----END PRIVATE KEY----- "
	}
}
```

</p>
</details>

Expected Behaviour
---
When the branch **myfeature** doesn't actually exist(in any or all repositories within the composite), the client will retry with **master** (as it does in a non-composite env).

Observed Behaviour
---
When the branch **myfeature** doesn't actually exist, (in any or all repositories within the composite), the server returns an empty response instead of a 404, so the client doesn't bother retrying with **master**.

Notes
---
* We are using the PCF flavour of the config server, if that makes any difference.
* We are not running afoul of the requirement that all repositories within the composite must contain the same labels, though it would be wonderful if support were added for the label fallback to be applied to individual repositories.
  * Perhaps a way to address said enhancement as well as the overall bug would be to send the comma-delimited list to the server(like profiles), and let the server sort it out.
* This may be related to #1008 (in the sense that the response might not give the client enough information to make the right decision).

**Comment by spencergibb** [comment]
spring.cloud.config.label: myfeature,master isn't label fallback, it's look for all of these labels

**Comment by rs017991** [comment]
The way I read this, it would never look for all of the labels, but rather look up one at a time, stopping after it finds one that 'works':
https://github.com/spring-cloud/spring-cloud-config/blob/80fd0fa90441863886ec80486e64de45a3a70f48/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java#L94-L98

**Comment by spencergibb** [comment]
Thanks for that, you're right. I difference in behavior is probably not good :-)

**Comment by ryanjbaxter** [comment]
This is a known limitation

>When using a composite environment, it is important that all repositories contain the same labels. If you have an environment similar to those in the preceding examples and you request configuration data with the master label but the Subversion repository does not contain a branch called master, the entire request fails.

The reason for this limitation is that when one repository does not have that label than an exception is thrown and we stop processing the request and checking the rest of the configured repos.

This actually works as expected then.  For example, if the client sets 
`spring.cloud.config.label: myfeature,master`
And `myfeature` doesnt exist in all `EnvironmentRepository`s than the config server will return a 404 and the `master` will be tried (and so on).

**Comment by ryanjbaxter** [comment]
Yes I think so

**Comment by rs017991** [comment]
@ryanjbaxter as I noted above, I am aware of that limitation, and have tested/observed that this happens even if all repositories have the same branch names.

In fact, the sample JSON I provided has all entries within the composite pointing to the same actual repository (so naturally there could be no discrepancy among their branch lists)

**Comment by spencergibb** [comment]
So the code you pointed to is client code, not server.

There is no support for multiple labels sent to the server at once.

When I do this, config client tries once for each label, it returns a 404 from the `unknown` label but returns for master

bootstrap.yml
```yaml
spring.cloud.config.label=unknown,master
```

```log
2018-12-20 16:15:19.348  INFO 21882 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:8888
2018-12-20 16:15:19.431  INFO 21882 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:8888
2018-12-20 16:15:19.635  INFO 21882 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Located environment: name=foo, profiles=[default], label=master, version=null, state=null
2018-12-20 16:15:19.635  INFO 21882 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: CompositePropertySource {name='configService', propertySources=[MapPropertySource {name='/home/spencer/Desktop/config/foo.properties'}, MapPropertySource {name='/home/spencer/Desktop/config/application.yml'}]}
```

I can't duplicate the behaviour you describe.

**Comment by rs017991** [comment]
Yeah the multiple labels thing was just an idea of one way to address the issue, not an expectation that it would already do it.

It's interesting that you're getting the 404; when I try I get 200 (though the body contains no properties).
I'll go ahead and see if I can put together a simplified reproduction that you can run.

**Comment by rs017991** [comment]
So naturally, in the process of creating my reproduction I discovered that this was a wild goose chase after all.

It turns out that the config servers we have in our PCF environment were all running an older version of the Config Server (except for the one I used when testing the non-composite env, which is what led me down that path).
When I create a new config server with the same JSON I now get the desired 404.

So if anybody stumbles on this page with a similar issue, you may need to update your config servers
* **/actuator/info** reports version **"20"** on the working one, whereas:
*  **/info** reports version **"10"** on the broken one

@spencergibb @ryanjbaxter thanks for looking into this, and sorry for the confusion.

**Comment by spencergibb** [comment]
Those versions don't mean anything to spring cloud. AFAIK, we don't add any versioning to `/info`, maybe something specific to your deployment.
