### ISSUE TITLE
Dynamic configuration not working with @refreshscope

### ISSUE THREAD

**Issue by sathish593** [spring-cloud/spring-cloud-config#1214]
Hello,

i am working on a rest oauth 2.0 application , i have a property, based on that property change, i want to change the configuration. i am able to read the updated property from configuration server and i am able to see the updated value in the rest controller result. but one particular configuration is not build dynamically.

below is my configuration class. the refresh event is printing the updated value, but the configuration is not build dynamically.

@Configuration
@EnableResourceServer
@RefreshScope
public class OAuth2ResourceServerConfigJwt extends ResourceServerConfigurerAdapter {

    @Autowired
    private CustomAccessTokenConverter customAccessTokenConverter;
    
    
  
    
    @Value("${maping:/v1,/v2}")
    private  String maping;
    
    @EventListener(RefreshScopeRefreshedEvent.class)
    public void onRefresh(RefreshScopeRefreshedEvent event) {
        // Your code goes here...
    	System.out.println(maping);
    }

    @Override
    @RefreshScope
    public void configure(final HttpSecurity http) throws Exception {
        // @formatter:off
                /*http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.IF_REQUIRED)
                    .and()
                    .authorizeRequests().anyRequest().permitAll();*/
        // @formatter:on     
    	
               
               /* http.
        		anonymous()
        		.and().authorizeRequests().antMatchers("/v1/**").permitAll()
        		.and().requestMatchers().antMatchers("/v2/user/**")
        		.and().authorizeRequests()
        		.antMatchers("/v2/user/**").access("hasRole('ADMIN')")
        		.and().exceptionHandling().accessDeniedHandler(new OAuth2AccessDeniedHandler());*/
    	//maping="/v1,/v2";
    	
    	System.out.println(maping);
    	
    	if(maping.contains("/v1")) {
    		System.out.println(maping);
                http
                .anonymous().and()
                .authorizeRequests()
                .antMatchers("/v1/**").permitAll()
                .antMatchers("/v2/**").authenticated()
                .antMatchers("/**").permitAll()
               ;
    	}
                
    	else {
    		http
            .anonymous().and()
            .authorizeRequests()
            .antMatchers("/v1/**").denyAll()
            .antMatchers("/v2/**").authenticated()
            .antMatchers("/**").permitAll()
           ;
    	}
                
    }

 i am not getting any error other than 
Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$ce042f36] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

**Comment by spencergibb** [comment]
Refresh scope is documented to not work on configuration classes. Please refactor the class and if it's still an insurance supply a sample project that recreates the issue and I'll reopen
