### ISSUE TITLE
Two environmentWebEndpointExtention beanName

### ISSUE THREAD

**Issue by glmapper** [spring-cloud/spring-cloud-config#1215]
## Enviroment

* JDK -> 8
* SpringCloud -> Finchley.RC1
* SpringBoot -> 2.1.1.RELEASE

## Condition

This exception occurs when I use the following configuration in application.properties.
* config
```json
management.endpoints.web.exposure.include=*
```

* exception
```
Caused by: java.lang.IllegalStateException: Found multiple extensions for the endpoint bean environmentEndpoint (environmentEndpointWebExtension, environmentWebEndpointExtension)
```
## Troubleshooting results

* EndpointDiscoverer#addExtensionBeans(..)
![image](https://user-images.githubusercontent.com/35319286/50430782-0715d780-0901-11e9-8cb3-f6ea230db21f.png)

* DefaultListableBeanFactory#getBeanNamesForAnnotation(..)

There are two identical beanNames here.

first one:
![image](https://user-images.githubusercontent.com/35319286/50430909-bfdc1680-0901-11e9-85f5-1ea2e0fc36b2.png)

another:
![image](https://user-images.githubusercontent.com/35319286/50430919-cff3f600-0901-11e9-8b31-8dc57654b5ca.png)

Can also be seen in beanDefinitionNames.
![image](https://user-images.githubusercontent.com/35319286/50430948-003b9480-0902-11e9-85b8-7956666185c6.png)

**Comment by spencergibb** [comment]
Finchley is not compatible with boot 2.1.x. Upgrade to Greenwich.RC1 or
Downgrade to boot 2.0.x

**Comment by glmapper** [comment]
@spencergibb Where can I get this information about "Finchley is not compatible with boot 2.1.x",
Can you provide a link? thank you.

**Comment by spencergibb** [comment]
http://cloud.spring.io

**Comment by glmapper** [comment]
@spencergibb I tried to Downgrade the SpringBoot version to 2.0.2, but this problem still exists.
