### ISSUE TITLE
Error connecting to git repo with self signed certificate

### ISSUE THREAD

**Issue by marmanan** [spring-cloud/spring-cloud-config#122]
I don´t see any way to configure Spring Cloud Config server to avoid self signed certificate validation when connecting to a git repo. Something like the http.sslVerify property in git client.
Thanks

**Comment by dsyer** [comment]
Self signed certificates are only for testing. Why not ho with HTTP or filesystem access for that?

Anyway Spring is just using JGit and `java.net.*` so anything that applies to those will apply here. There are some static config conveniences for socket factories iirc.

**Comment by dsyer** [comment]
Apparently you can work around self-signed certs in development environments using these steps: 

1. Grab the default truststore, which is the cacerts bundled in the JDK

2. Extract the certs from it, create a new truststore in a temp file

3. Add those certs to the new truststore, add the self-signed cert

4. Set the `javax.net.ssl.trustStore` properties

(Thanks to @willtran for the recipe.)

It's up to you to make sure this doesn't happen in production, and I don't think it's appropriate for Spring to get involved in that (it's too risky).
