### ISSUE TITLE
SSH Key From Mounted Volume

### ISSUE THREAD

**Issue by hanserya** [spring-cloud/spring-cloud-config#1222]
Hello,

I know that this has been brought up multiple times, but I wanted to offer a gist of my implementation to see if the team is amenable to taking a PR that would enable the config server to use an SSH key from a volume that is mounted to a container rather than expect developers to plop private SSH keys into our source code repositories. 

The client that I am currently consulting with utilizes PCF as a cloud platform, Git repos within TFS for VC, and would like to start using config server to manage application configuration rather than continue to rely on their own custom solution. The problem we are facing is that we need to be able to use SSH keys to authenticate with TFS in order to make that happen. However, none of us are keen (at-all) towards placing a private SSH key as plain text in an unsecured location - nor are we willing to place the SSH keys directly within the docker images for obvious security reasons. 

To that end, I have spent a lot of time ripping through the SSH transport layer to figure out what it will take to enable us to deliver the keys to an application via a secured, mounted volume. What I have now appears to be fully functional (even if it is a bit of an ugly duckling from an implementation standpoint.)

https://gist.github.com/hanserya/43b00162741fa3022481301db60e8acd

The gist above sums up what I've been able to discern until now. I'd appreciate it greatly if someone can take a gander and provide some feedback regarding the general willingness of the team to accept a PR that would make this a native feature within the config server. Any time devoted to this is greatly appreciated.

Thanks!
Ryan

**Comment by ryanjbaxter** [comment]
The best thing to do is submit the PR so we can get a better idea of the changes involved.

**Comment by hanserya** [comment]
Understood. I'll set up a dev environment this weekend look at shipping that out. Thanks!

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
