### ISSUE TITLE
Configuration Center, when I modify the configuration file in remote git, and then send a request through webhooks to update the local configuration file, the request succeeds, but the local config configuration center configuration file has not changed. If using command form, it can change the local configuration file ($curl - V - X POST "http://localhost: 8080/actuator/bus-refresh"). Why? Seek help

### ISSUE THREAD

**Issue by Mrliangwenbin** [spring-cloud/spring-cloud-config#1223]
Configuration Center, when I modify the configuration file in remote git, and then send a request through webhooks to update the local configuration file, the request succeeds, but the local config configuration center configuration file has not changed. If using command form, it can change the local configuration file ($curl - V - X POST "http://localhost: 8080/actuator/bus-refresh"). Why? Seek help

**Comment by ryanjbaxter** [comment]
Where is the webhook sending the request?

**Comment by Mrliangwenbin** [comment]
@ryanjbaxter GitHub

**Comment by ryanjbaxter** [comment]
What does the request look like?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
