### ISSUE TITLE
Support lastModified query for file resources?

### ISSUE THREAD

**Issue by PeterTeunissen** [spring-cloud/spring-cloud-config#1228]
We use the Spring Cloud Config Server to serve up some definition files to our application. The round trip from application to config server is quiet large so we want to cache these files inside our application and only refresh the cache if the file on the config server changes. Looking at the code in org.springframework.cloud.config.server.resource.ResourceController it seems it just returns the file content and not much more.  I made a copy of this file and added a query parameter so that we can ask for the lastModified of the resource by adding ?lastModified=true. Is this something that is interesting enough for others ? Does this warrant a PR?

(Attached a crude version of this)
[ResourceController.zip](https://github.com/spring-cloud/spring-cloud-config/files/2769372/ResourceController.zip)

**Comment by spencergibb** [comment]
A PR would be better than an attachment.

**Comment by rgoers** [comment]
I should note that I am modifying Log4j 2 to take advantage of this feature.
