### ISSUE TITLE
Problem with Spring Cloud HeartbeatEvent when Spring Cloud Config Discovery is enabled

### ISSUE THREAD

**Issue by andcuevas** [spring-cloud/spring-cloud-config#1229]
## Versions used:
Spring Boot Starter Parent 2.0.7.RELEASE
Spring Cloud Dependencies Finchley.SR2
Spring Cloud Starter Consul Discovery
Spring Cloud Starter Config

## Description
I have prepared a sample project in order to reproduce the problem:
https://github.com/andcuevas/spring-cloud-config-discovery-noheartbeat-problem

In summary, when the property spring.cloud.config.discovery.enabled=true is present, the Event Listener it's not triggered with the HeartbeatEvent. With the same code but without the property the Event Listener it's triggered as expected.

**Comment by andcuevas** [comment]
But the problem is related with discovering the config server. If there is no config server how the discovery of this service is going to work?

**Comment by spencergibb** [comment]
is a `ParentHeartbeatEvent` triggered?

**Comment by andcuevas** [comment]
There is no ParentHeartbeatEvent.
I added the following to the code:

`
@EventListener
    public void heartbeat(final ParentHeartbeatEvent event) {
        log.info("ParentHeartbeatEvent:" + event.getValue());
    }
`

But it wasn't triggered with the spring.cloud.config.discovery.enabled=true or without the property.

**Comment by TYsewyn** [comment]
This issue may cover other service registries too. We will use this ticket to keep track of all implementations/versions.

- [ ] Consul - Finchley.SR3
- [ ] Consul - Greenwich.SR2
- [ ] Consul - Hoxton.M1
- [ ] Eureka - Finchley.SR3
- [ ] Eureka - Greenwich.SR2
- [ ] Eureka - Hoxton.M1
- [ ] Zookeeper - Finchley.SR3
- [ ] Zookeeper - Greenwich.SR2
- [ ] Zookeeper - Hoxton.M1

**Comment by TYsewyn** [comment]
Will close this issue since both PRs have been merged.
