### ISSUE TITLE
Client side encryption/decryption is not working in bootstrap.yml

### ISSUE THREAD

**Issue by seno5979** [spring-cloud/spring-cloud-config#123]
I currently working on a project that using spring-cloud-config-server, but would like to use client own keys to encrypt/ decrypt the secure property values.

So I did some customization on spring-cloud-config-server to bypass the decryption of property value that has '{cipher}' tag and let the value be decrypted on client side.

As I remember the things is working as expected on 1.0.0.RC1, but after I upgrade to 1.0.0.RELEASE,
the decryption is not working properly.

Then I realize that there were some changes on version 1.0.0.RELEASE that cause the issue I mentioned above.

In 1.0.0.RELEASE, the order of initialization on `EnvironmentDecryptApplicationInitializer` has changed.

`EnvironmentDecryptApplicationInitializer` is being called / initialized before `PropertySourceBootstrapConfiguration`. So the data retrieved from  config server has no change to be decrypted at this scenario.

Just want to make sure why we need to initialized `EnvironmentDecryptApplicationInitializer` earlier than `PropertySourceBootstrapConfiguration` ??

https://github.com/spring-cloud/spring-cloud-config/blob/1.0.0.RELEASE/spring-cloud-config-client/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java#L43

**Comment by dsyer** [comment]
I guess some people might want to decrypt properties that are needed during bootstrap (like the config server password). We could make 2 passes over the environment I suppose?

**Comment by seno5979** [comment]
Hi Dave,

My suggestion is to load EnvironmentDecryptApplicationInitializer after PropertySourceBootstrapConfiguration if this is make sense.

Currently EnvironmentDecryptApplicationInitializer is being loaded before PropertySourceBootstrapConfiguration.

Thanks,
Seno

**Comment by dsyer** [comment]
I know. But your suggestion doesn't work for people that want the order the way it is, does it? Hence I suggested decrypting twice.

**Comment by seno5979** [comment]
Sound make sense to me. Thanks for the explanation.

Is the suggestion you brought up will be the standard of spring-cloud-config or we need to customize it  by our self ?

**Comment by marmanan** [comment]
We are facing the same problem, we want the properties provided by cloud config server decrypted in the client and not in the server and can not manage to do it.

**Comment by marmanan** [comment]
Hi dsyer, getting back to seno5979 question:
"Is the suggestion you brought up will be the standard of spring-cloud-config or we need to customize it by our self ?"
How could we proceed? If we need a customization, can you explain what we will have to do?
Thanks

**Comment by dsyer** [comment]
If you get something working and you want to contribute it as a pull request that's fantastic.

**Comment by ktong** [comment]
It also does not work on customized bootstrap configuration.

**Comment by dsyer** [comment]
@ktong cutomized how? What doesn't work?

**Comment by ktong** [comment]
I add a customized bootstrap configuration according to doc at http://projects.spring.io/spring-cloud/docs/1.0.1/spring-cloud.html#_customizing_the_bootstrap_configuration. I thought the value would be decrypt if it prefix with {cipher}. But it's not.

**Comment by dsyer** [comment]
You mean you added a `PropertySourceLocator` and the properties were not decrypted? Sorry, but we have to be precise about the use case.

**Comment by ktong** [comment]
yes, exactly.

**Comment by marmanan** [comment]
I have tried to encrypt the password to access the config server, but it´s not working either.
Apparently config client creates the ConfigClientProperties bean before doing the decryption process and although the decryption is made before calling the config server, config client uses the encrypted value. So it receives a 401 from the server.

**Comment by marmanan** [comment]
Same thing in config server with git user´s password, decrypted value is not used when calling git.

**Comment by Chumper** [comment]
I have the same use case:

In order to let all other clients know that a value changed the config server triggers the `/bus/refresh` endpoint.
In order for this to work i created an `application.yml` in the git repo:
```yaml
spring:
  rabbitmq:
    host: myHost
    port: 5672
    username: myUser
    password: '{cipher}AQAO8QtUK....'
```

because the config server should also take this as configuration i added into the `bootstrap.yml`:
```yaml
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        bootstrap: true
        git:
         uri: http://git.home... 
```

I expect the config server to initialize itself with the config (which the server does) but also to decrypt all cipher values in the config (which the server does not). 
i have placed the keystore on the classpath and observed, that the server is trying to log into rabbitmq with the `{cipher}...` password.

What can we do in this case?
I just want to provide a minimal config for the config server itself, which will be the url to the git repository and the key for decrypting. everything else should be taken from the repo config.

**Comment by dsyer** [comment]
Fixed in https://github.com/spring-cloud/spring-cloud-commons/issues/32
