### ISSUE TITLE
Spring Cloud Config incorrectly serves same-named plain text file from wrong application

### ISSUE THREAD

**Issue by robinroos** [spring-cloud/spring-cloud-config#1230]
Spring Cloud Config can serve same-named plain text file from wrong application

I am using Spring Cloud Config 2.0.2.RELEASE backed by a Git configuration repo, serving plain-text resources as well as properties.

Given the following configuration folder structure and contents:

$ pwd
/var/folders/z2/fnh72_wn0v315yrsw8kth8gr0000gn/T/config-repo-7805721577126063976
$ find . -name *.xml -or -name *.yml | sort
./ips-data-service/hazelcast-for-hibernate.xml
./ips-data-service/hazelcast.xml
./ips-data-service/ips-data-service-dev.yml
./ips-data-service/ips-data-service-local.yml
./ips-data-service/ips-data-service-prod.yml
./ips-data-service/ips-data-service-test.yml
./ips-data-service/ips-data-service.yml
./ips-rules-engine/hazelcast.xml
./ips-rules-engine/ips-rules-engine-dev.yml
./ips-rules-engine/ips-rules-engine-local.yml
./ips-rules-engine/ips-rules-engine-prod.yml
./ips-rules-engine/ips-rules-engine-test.yml
./ips-rules-engine/ips-rules-engine.yml
./ips-ui/hazelcast.xml
./ips-ui/ips-ui-dev.yml
./ips-ui/ips-ui-local.yml
./ips-ui/ips-ui-prod.yml
./ips-ui/ips-ui-test.yml
./ips-ui/ips-ui.yml
$ 

and noting that hazelcast.xml exists for multiple applications (ips-data-service , ips-rules-engine , ips-ui), the following request:

http://localhost:9000/ips-data-service/dev/master/hazelcast.xml

has been shown to return the hazelcast.xml file for the application ips-rules-engine, instead of the one for ips-data-service.  This appears to happen because

AbstractScmAccessor.getSearchLocations(File dir, String application, String profile, String label)

does not effectively constrain based on application, but happily returns locations from multiple applications.

I will attach a screenshot from a debug session with breakpoint on the return from that method (line #250).  Let me know if you would also require a trimmed-down zip of the files themselves.

**Comment by robinroos** [comment]
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/13133023/51522729-f41ff580-1e21-11e9-9778-7aeee7c77c13.png">

The request was for application ips-data-service, but the returned contents is from application ips-rules-engine.

**Comment by robinroos** [comment]
The <name> elements of the three hazelcast.xml files contain different, application-specific tokens|:

$ cat ./ips-data-service/hazelcast.xml | grep "<name>"
        <name>${cas.env}-ips-data-service-session</name>
$ cat ./ips-rules-engine/hazelcast.xml | grep "<name>"
        <name>${cas.env}-ips-rules-engine-session</name>
$ cat ./ips-ui/hazelcast.xml | grep "<name>"
        <name>${cas.env}-ips-ui-session</name>
$

**Comment by ryanjbaxter** [comment]
Can you provide a sample config repo in github so we can reproduce the problem locally?

**Comment by robinroos** [comment]
[config_repo_1230.zip](https://github.com/spring-cloud/spring-cloud-config/files/2784612/config_repo_1230.zip)

Here are the files.  The archive was created with the zip command on MacOS/X.

**Comment by robinroos** [comment]
We see the same issue after upgrading to spring-cloud-config 2.1.0.RELEASE.

**Comment by robinroos** [comment]
We perceive this as being a pretty serious issue.  Could someone take a look for us?

Using Spring Cloud Config in this way will prevent us from having to find a workable alternative to the concept of resource filtering.  Cloud Config-based management of Plain Text resources looks to be by far the best option, as the application code we can deploy to production the same application package that was deployed to test.  Old-style approaches, such as Maven Resource Filtering (and presumably also approaches based on the gradle Properties plug-in), are sub-optimal in this regard.

Since we already depend on Spring Cloud Config for environment-specific property resolution, we hope to rely on it also for Plain Text.

**Comment by robinroos** [comment]
I finally got to the bottom of this.

We had erroneously enumerated the applications as explicit search-paths:

`spring.cloud.config.server.git.search-paths: ips-ui, ips-ui-or, ips-data-service, ips-rules-engine`

The problem is resolved by setting:

`spring.cloud.config.server.git.search-paths: '{application}'`

Cloud Config Server is now dependably serving plain-text resources to each application.

Many thanks, Robin.
