### ISSUE TITLE
Spring config server getting hit all the time, even though clients are not calling the config server APIs

### ISSUE THREAD

**Issue by Swatikp** [spring-cloud/spring-cloud-config#1231]
Question

Spring config server getting hit all the time, even though clients are not calling the config server APIs, I am seeing bulk of logs.

I have heard that sometimes it can be due to health check, and people are telling to add following property:
health.config.enabled=false

Should it be mentioned in spring config server application or spring config client application (which is a spring boot application) using the config server?

**Comment by ryanjbaxter** [comment]
It is in the client 
http://cloud.spring.io/spring-cloud-static/Greenwich.RC2/single/spring-cloud.html#_health_indicator_3

You can also configure a TTL for the health indication.
