### ISSUE TITLE
Is there an interface to get all the files in the configuration service?

### ISSUE THREAD

**Issue by huangmiao** [spring-cloud/spring-cloud-config#1232]
use configserver get all config location file 
![image](https://user-images.githubusercontent.com/5791417/51604081-a2bd5680-1f46-11e9-9ef8-28ab971c43eb.png)
Use configserver to get all files and folders in all configuration locations.
think it's necessary to encapsulate configserver. 
Provide corresponding action pages on the UI

**Comment by ryanjbaxter** [comment]
No there is not, and I don’t think this is something we want to add
