### ISSUE TITLE
Composite Repository Definition and spring-cloud-config-monitor fails to start

### ISSUE THREAD

**Issue by y24jds** [spring-cloud/spring-cloud-config#1239]
I wish to use the composite repository feature and the spring-cloud-config-monitor feature at the same time but it appears that spring-cloud-config-monitor does not support multiple repositories as they are created as composite repositories.  

The steps are very easy to reproduce if you want to follow the steps below or I have created a demo repository here:

https://github.com/y24jds/test-configserver

# Steps to reproduce issue of using composite repositories and spring-cloud-config-monitor dependency

1. Used spring Initalizr to create new project with Spring Boot 2.1.2, Config Server, and Cloud Bus.
https://start.spring.io/
Using the Greenwich.RELEASE version of spring-cloud
2. Also added the spring-cloud-config-monitor dependency to pom.xml
```xml<dependency>
<groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-config-monitor</artifactId>
</dependency>
```
3. Also added the AMQP dependency to pom.xml
```xml<dependency>
<groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-bus-amqp</artifactId>
</dependency>
```    
4. Make sure that the main application class is annotated with: @SpringBootApplication, @EnableConfigServer, @Configuration

5. Add the following to the application.properties file (note, it doesnt really matter if the git repo's point to a valid repo or not, just the fact of using a composite repository definition and adding at least 2 repo's breaks spring-cloud-config-monitor):

spring.profiles.active=composite
spring.cloud.config.server.composite[0].type=git
spring.cloud.config.server.composite[0].uri=http://github.com/y24jds/common.git
spring.cloud.config.server.composite[1].type=git
spring.cloud.config.server.composite[1].uri=http://github.com/y24jds/{application}.git

6.  Start the application

# Issue:
Observe that the following is logged:
***************************
APPLICATION FAILED TO START
***************************

Description:

Field scmRepository in org.springframework.cloud.config.monitor.FileMonitorConfiguration required a single bean, but 2 were found:
	- git-env-repo0: defined by method 'build' in null
	- git-env-repo1: defined by method 'build' in null

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

# The Problem:
With debug=true on, you can get more detailed info that showed me that the problem is in the FileMonitorConfiguration class in spring-cloud-config-monitor, Spring finds 2 beans as candidates for the AbstractScmEnvironmentRepository scmRepository field.  It doesn't know which to use.

**Comment by spencergibb** [comment]
FileMonitorConfiguration was built before composite repositories. Not sure there is a workaround.
