### ISSUE TITLE
When sending /monitor requests using WebHooks, Config Client cannot refresh automatically

### ISSUE THREAD

**Issue by 405722907** [spring-cloud/spring-cloud-config#1241]

**Comment by spencergibb** [comment]
I'm afraid that, since you've provided no details I can't help. 

From the issue template:
> Please provide details of the problem, including the version of Spring Cloud that you are using. If possible, please provide a test case or sample application that reproduces the problem. This makes it much easier for us to diagnose the problem and to verify that we have fixed it.
