### ISSUE TITLE
spring-cloud-gateway-DiscoveryClient_my-gateway - was unable to send heartbeat!

### ISSUE THREAD

**Issue by rohit756** [spring-cloud/spring-cloud-config#1245]
<!--
Hi
Here Im trying to register my gateway with eureka service
My Eureka service is Up and runnning in PCF
And also my gateway application is running fine in PCF
But when I check Eureka UI, Im not seeing gateway as a registered application

Here are some errros from my logs

ERROR 22 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient : DiscoveryClient_MY-GATEWAY/ - was unable to send heartbeat!
ERROR 22 --- [tbeatExecutor-0] c.n.d.s.t.d.RedirectingEurekaHttpClient : Request execution error
com.netflix.discovery.DiscoveryClient : DiscoveryClient_MY-GATEWAY/ - was unable to refresh its cache! status = Cannot execute request on any known server
Fetching config from server at : http://localhost:8888

Here is my bootstrap.yml look like

spring:
  application:
    name: my-gateway
  cloud:
    config:
      discovery:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: https://localhost:8791/eureka

management:
  endpoint:
    service-registry:
      enabled: true

here is GatewayApplication.java

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.cloud.gateway.route.RouteLocator;
import org.springframework.cloud.gateway.route.builder.RouteLocatorBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.security.config.web.server.ServerHttpSecurity;
import org.springframework.security.web.server.SecurityWebFilterChain;

@SpringBootApplication
@EnableDiscoveryClient
public class GatewayApplication {

    @Bean
    public RouteLocator customRouteLocator(RouteLocatorBuilder builder) {
        return builder.routes()
                .route("rest_service_route",
                        r -> r.path("/my_service/**")
                                .uri("lb://rest-service"))
                .route("rest_service_route2",
                        r -> r.path("/service/**")
                                .filters(f -> f.rewritePath("/service/(?<segment>.*)", "/my_service/${segment}"))
                                .uri("lb://rest-service"))
                .route("rest_service_route2",
                        r -> r.path("/something")
                                .filters(f -> f.rewritePath("/something", "/my_service/hello"))
                                .uri("lb://rest-service"))
                .build();
    }

    @Bean
    public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) throws Exception {
        return http.httpBasic().and()
                .csrf().disable()
                .authorizeExchange().anyExchange().permitAll()
                .and()
                .build();
    }

    public static void main(String[] args) {
        SpringApplication.run(GatewayApplication.class, args);
    }
}

Any help is appreciated
Thanks

**Comment by spencergibb** [comment]
Not sure what you meant to do here. This repo is not spring cloud gateway and you provided no details.

**Comment by rohit756** [comment]
Opened a new issue
https://github.com/spring-cloud/spring-cloud-gateway/issues/819 here with
description
any help is appreciated
