### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by shahid21st** [spring-cloud/spring-cloud-config#125]
In the readme, under the heading 'Spring Cloud Config Client', in the last point it is written "Bootstrap appplication context", it should be "Bootstrap application context".

**Comment by shahid21st** [comment]
The same problem also exists in the project homepage: http://cloud.spring.io/spring-cloud-config/

**Comment by spencergibb** [comment]
@shahid21st yeah, that page is built from the docs, it will eventually go away
