### ISSUE TITLE
Not able to fetch server.jks file from other than classpath

### ISSUE THREAD

**Issue by Swatikp** [spring-cloud/spring-cloud-config#1256]
Question

Hi

For Encryption, I have created Spring cloud config server keystore.jks file and I have stored it at ${user.home}/  location but when I give encrypt.keystore.location=${user.home}/keystore.jks it tells me an error saying :
**class path resource [home/<user-name>/keystore.jks] cannot be opened because it does not exist.**

Can't I store keystore at any location other than classpath, because I have to pass keystore file at runtime instead of packaging it in jar, because my jar will be public.

**Comment by ryanjbaxter** [comment]
This sounds similar to #1176.  I am going to close it as a duplicate.  Please let me know if you think this is a different issue.

**Comment by Swatikp** [comment]
Hi @ryanjbaxter 

My issue is different than the one you mentioned. The problem is that I dont want to package my Java key store with jar file, I want to pick it up from file system location other than classpath. My spring cloud config boot application will be one of my deliverable, but the jks keystore should be generated and used by the end customer.(intended to use the jar to encrypt files). I sthere any way to keep the jks file outside jar and give file system location. I hope I made myself clear. Let me know if you need any clarifications regarding this.
