### ISSUE TITLE
Issue combining Native and JDBC profiles

### ISSUE THREAD

**Issue by kevin-thompson** [spring-cloud/spring-cloud-config#1257]
I've been trying to standup a config server that serves from both local files and the database. I have both profiles working independently of each other, but when I combine them (spring.profiles.active=native,jdbc), I see that only the property sources from the database come through.

In attempting to trace this, I notice that the JdbcEnvironmentRepositoryFactory gets created, then the CompositeEnvironmentRepository constructor is called, then the NativeEnvironmentRepositoryFactory is created. From that standpoint, it makes sense that only the database properties are loaded because CompositeEnvironmentRepository.environmentRepositories only contains the JdbcEnvironmentRepository at this point. However, this is clearly not the desired behavior.

I'm using spring-cloud Greenwich.RELEASE and spring-boot 2.1.3.

Note that it seems to be the same problem revealed in this [stackoverflow question](https://stackoverflow.com/questions/49440558/multiple-composite-repositories-with-jdbc-native), but that was never resolved.

**Comment by spencergibb** [comment]
Can you try with the composite configuration? https://cloud.spring.io/spring-cloud-static/Greenwich.RELEASE/single/spring-cloud.html#composite-environment-repositories

**Comment by kevin-thompson** [comment]
Hmm, that did work; I got both sets of property sources coming through.

I'm certainly happy to continue in this manner as it solves my problem, but it leaves me curious. Was I doing something wrong? I thought I was following the recommended course of action found in the second half of that section to which you linked.

**Comment by spencergibb** [comment]
We're leaning towards recommending the first part because of frequent issues like this.

**Comment by kevin-thompson** [comment]
OK, thanks!

**Comment by zziawan** [comment]
hi, how to write the yaml file for  composite configuration   jdbc and native,  can some one show me . thanks
