### ISSUE TITLE
Config Server to support Hashicorp Vault Namespace

### ISSUE THREAD

**Issue by kamalakarp** [spring-cloud/spring-cloud-config#1259]

**Comment by kamalakarp** [comment]
I have made the changes and i need the process to contribute back to this forum/repo.

**Comment by ryanjbaxter** [comment]
Could you provide a better description of the enhancement?

**Comment by kamalakarp** [comment]
Hashicorp Vault enterprise edition has the concept of the namespace. In a typical enterprise, there will be multiple applications and dev teams, and each application can have it's own namespace created and with in each namespace, they will have their own secret engines. The vault binary available in the internet is a community edition which doesn't have the namespace feature.
All enterprises typically uses the namespace , i have made the code changes to support the namespace.

These are two simple changes in the following classes.

org.springframework.cloud.config.server.environment.VaultEnvironmentProperties

	/** Vault namespace. Defaults to root. */
	private String namespace = "";

org.springframework.cloud.config.server.environment.VaultEnvironmentRepository

		this.namespace = properties.getNamespace();

		headers.add(VAULT_TOKEN, token);
		System.out.println("Namespace : " + this.namespace);
		if(this.namespace!=null && !"".equalsIgnoreCase(this.namespace)) {
			headers.add(VAULT_NAMESPACE, this.namespace);
		}

Today we only add the token to the header and i'm adding namespace to the header and it's working.

Thanks
Kamal.

**Comment by spencergibb** [comment]
PRs welcome

**Comment by kamalakarp** [comment]
I submitted the PR and can you please review the same.
https://github.com/spring-cloud/spring-cloud-config/pull/1266

**Comment by kamalakarp** [comment]
@spencergibb - Thank you for merging to the master. I see the Readme was not updated properly where i have added the vault related configuration.

spring:
  cloud:
    config:
      server:
# Git Repository
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
# Hashicorp Vault
        vault:
          port: 443
          scheme: https
          host: yourvault.com
          namespace: devops/cicd

**Comment by spencergibb** [comment]
I added documentation in the proper location. Where you added is just a quickstart and wasn't ideal.
