### ISSUE TITLE
Missing copyright owner in license file

### ISSUE THREAD

**Issue by lsmithmier** [spring-cloud/spring-cloud-config#1261]
Question

The license doesn't state who the copyright holder of the code is.   Can someone please update the document with the appropriate information?

 **Copyright [yyyy] [name of copyright owner]**

**Comment by ryanjbaxter** [comment]
Are you talking about here? https://github.com/spring-cloud/spring-cloud-config/blob/master/LICENSE.txt

**Comment by spencergibb** [comment]
Each source file has a copyright

**Comment by lsmithmier** [comment]
Right, the main license file just has a placeholder.  If I look in the source then I do find that it lists that: 
 * Copyright 2013-2019 the original author or authors.
and:
 * @author Dave Syer
 * @author Marcos Barbero

https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigClientAutoConfiguration.java

but we are looking at using this project in a corporate environment and we really need a single point that states the rights holders to hand over to legal.  Can the https://github.com/spring-cloud/spring-cloud-config/blob/master/LICENSE.txt file be updated with a list of authors or an is there an appropriate organization name?

**Comment by spencergibb** [comment]
We use a standard across the spring portfolio. It's the same as Spring Framework. So if you're having questions here, you should have the same issues across the entire portfolio.

**Comment by spencergibb** [comment]
Unless I here back from our team, I don't think we will do anything different. I'll reopen if I hear anything different.

**Comment by spencergibb** [comment]
The authors hold the copyright. The list of authors is here https://github.com/spring-cloud/spring-cloud-config/graphs/contributors
