### ISSUE TITLE
Spring Boot creates two beans for MongoDataAutoConfiguration when using @RefreshScope Annotation

### ISSUE THREAD

**Issue by anshumt** [spring-cloud/spring-cloud-config#1262]
I have defined the following configuration class in my Spring boot project:

```
@RefreshScope
@Configuration
@EnableMongoRepositories(basePackages = {"repository-package"})
public class MongoConfig extends AbstractMongoConfiguration {

	@Value("${spring.data.mongodb.database}")
	private String database;

	@Value("${spring.data.mongodb.host}")
	private String host;

	@Value("${spring.data.mongodb.username}")
	private String username;

	@Value("${spring.data.mongodb.password}")
	private String password;

	@Value("${spring.data.mongodb.port}")
	private Integer port;

	@Override
	protected String getDatabaseName() {
		return database;
	}

	@Override
	@Bean
	public Mongo mongo() throws Exception {
		return new MongoClient(Collections.singletonList(new ServerAddress(host, port)),
				Collections.singletonList(MongoCredential.createCredential(username,database, password.toCharArray())));
	}
}
```

When I start my spring boot app, it fails with the following reason:

> Parameter 1 of method mongoMappingContext in org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration required a single bean, but 2 were found:
> 	- customConversions: defined by method 'customConversions' in class path resource [config-package-path/MongoConfig.class]
> 	- mongoCustomConversions: defined by method 'mongoCustomConversions' in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDataAutoConfiguration.class]

The reason I added @RefreshScope annotation is because I have externalized the property file using spring cloud config.

The property file is in a remote github repo and when I over-write that file with some changes, the @refreshScope annotation refreshes the values that are being passed.

Any work-around for this?

**Comment by spencergibb** [comment]
Refresh scope should not be used on `@Configuration` classes

**Comment by anshumt** [comment]
how can I dynamically refresh the values of username or password in case of any change then?

**Comment by spencergibb** [comment]
You need to refactor. Move refresh scope to the Mongo bean and all the values to a configuration properties bean and pass that into the Mongo bean function.

**Comment by anshumt** [comment]
So something like:

      ```
 @RefreshScope
       @Override
	@Bean
	public Mongo mongo() throws Exception {
		return new MongoClient(Collections.singletonList(new ServerAddress(host, port)),
				Collections.singletonList(MongoCredential.createCredential(username,database, password.toCharArray())));
	}
```

but isnt this bean within the configuration class though??

Also the values I can move to a separate Class called MongoProp

```
@Component
@ConfigurationProperties("spring.data.mongodb")
Class MongoProp {

String username;

String password;

//other variables and getter-setters
```

Then auto-wire this inside my @Configuration class and use the getters to get the values.

Is that Ok??

**Comment by spencergibb** [comment]
That's the right direction, but pass MongoProps to Mongo()

**Comment by anshumt** [comment]
so the values inside MongoProp will be refreshed via the @ConfigurationProperties right?? don't have to add @RefreshScope there correct??

**Comment by spencergibb** [comment]
A "refresh" does 2 things, rebinds configuration properties and clears the refresh scope cache so those beans get recreated in next access.

**Comment by anshumt** [comment]
ok...I did exactly as you asked but a very peculiar thing happens:

I changed the username to a garbage value and over-wrote the properties file in the remote git repo.

I sent a /refresh post request to refresh it.

now as expected I'm not able to connect to the cluster.

Now I change the username value to the correct value and over-write the properties file again in the repo.

I send the /refresh POST request.

but now I'm still not able to connect.

Also this time when I sent a refresh request I dont see any mongo related connection logs in the console whereas in the first refresh request, I could see the console say : connection closed.

**Comment by anshumt** [comment]
this is my bootstrap.properties:

spring.application.name=cloud-config
spring.cloud.config.uri=http://localhost:8888
management.security.enabled=false
endpoints.actuator.enabled=true
management.endpoints.web.exposure.include=*

My config server is hosted at 8888.

**Comment by spencergibb** [comment]
I can't really comment on the behavior of what the state of the classes that are using the Mongo bean. They may not be able to recover from a fatal error like that.

**Comment by anshumt** [comment]
but shouldn't @configurationProperties refresh the username to a correct value and then the @RefreshScope in the mongo bean causes it to refresh i.e. retry to make a connection to the cluster?

**Comment by anshumt** [comment]
is it because the MongoProp class which I Autowire is not being refreshed within the Configuration class??

Should I try to create a bean in the configuration class that returns an instance of MongoProp and mark it as @RefreshScope???

**Comment by spencergibb** [comment]
You can certainly try that.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
