### ISSUE TITLE
Support returning data from all environment repositories in a composite

### ISSUE THREAD

**Issue by kevin-thompson** [spring-cloud/spring-cloud-config#1263]
Since Vault allows for multiple secrets engines, it seems reasonable to expect that one might use multiple engines for the same project. For my requirements, we're storing our database secrets in an engine of the database type and the rest of our secrets in a key-value type. It seems that this is not possible using the current code (based on a quick attempt at implementation), and some [Pivotal documentation](https://docs.pivotal.io/spring-cloud-services/2-0/common/config-server/composite-backends.html#overview) seems to indicate as much.

I can see this being implemented one of two ways. Either the Vault configuration should allow for a list of backends, or multiple Vault repositories should be allowed. The second option was mentioned #660, but it does not seem that was addressed.

**Comment by spencergibb** [comment]
The composite environment repository allows multiple repositories if the same type. It only returns data from the first matched though (there's an open issue to return from multiple).

**Comment by ryanjbaxter** [comment]
Here is the info on configuring composite environment repos let us know if this solves the problem
http://cloud.spring.io/spring-cloud-static/Greenwich.RELEASE/single/spring-cloud.html#composite-environment-repositories

**Comment by kevin-thompson** [comment]
The quick implementation I mentioned was just that, and it revealed just what Spencer mentioned: the app started up fine, but it only returned data from the first.

I guess, given the confirmation that what I want isn't really available, my interest is which the correct way forward is. Spencer, you addressed the multiple repositories approach; what's the issue that addresses that? Furthermore, is that the desired solution because implementing a list of secrets engines is too hard to implement?

**Comment by ryanjbaxter** [comment]
Ah OK.  I couldnt find the issue @spencergibb mentions around returning data from multiple repos.  There is an issue around continuing to check multiple repos if one returns an error.

**Comment by spencergibb** [comment]
Maybe that's the one I was thinking of. This could be an operational model, return all of them. Could be configurable. Maybe we use this to track that notion

**Comment by kevin-thompson** [comment]
My apologies, this seems to actually be working. I caught myself with one kvVersion 1 secrets engine and one kvVersion 2 secrets engine while I had them both set as 2 in the app. After correcting my configuration, I'm receiving both sets of configuration.

I think that means that, as the issue is now titled, this is already working (at least for Vault repository in particular). However, I do think it would be nice to enable multiple backends per Vault repository rather than having to declare multiple repositories.

**Comment by ryanjbaxter** [comment]
> However, I do think it would be nice to enable multiple backends per Vault repository rather than having to declare multiple repositories.

Could you open a separate issue for this?
