### ISSUE TITLE
Vault Repository for Embedded Server

### ISSUE THREAD

**Issue by kevin-thompson** [spring-cloud/spring-cloud-config#1267]
I've been trying to get a VaultEnvironmentRepository running in my embedded config server. Attempting to configure it as I would were it not embedded, I get an error stating "No HttpServletRequest available." I got around this by creating a faux implementation of HttpServletRequest and injecting it via BootstrapConfiguration in spring.factories. This worked well (once I forced it to return the spring.cloud.vault.token for the X-Config-Token header), except that this is now always the token used for every request, i.e. there's no way for cloud config clients to use the token configured in their own properties.

My question is, what am I missing when it comes to configuring the VaultEnvironmentRepository in bootstrap.yml? Is this possible, or will workarounds have to do?

**Comment by spencergibb** [comment]
Why not use spring cloud vault at that point?

**Comment by kevin-thompson** [comment]
The goal is to get properties imported from an outside repository, and since that's what the server does best, I was trying to do it through that.

I suppose that I know which properties I need at build time, and, given this, I can just create a BootstrapConfiguration that pulls from Vault the properties that I want. I then either loose the ability to vary based on profile or have to reproduce this in my configuration. Is this what you're suggesting, or am I misunderstanding you?

**Comment by spencergibb** [comment]
There's already a project that does this is what I was trying to say https://github.com/spring-cloud/spring-cloud-vault

**Comment by kevin-thompson** [comment]
I see, I was expecting that project to be merely the implementation of the Vault APIs, not the also forming a property source. That should cover it. Thanks.
