### ISSUE TITLE
how to configure client properties files under consul  in spring config server application

### ISSUE THREAD

**Issue by dilipsingh1306** [spring-cloud/spring-cloud-config#1268]

**Comment by dilipsingh1306** [comment]
I am new to Consul and Cloud concepts in Spring. I am unable to configure properties under consul i.e. From client end whenever it fetching showing as in Logs "Located property source: CompositePropertySource {name='configService', propertySources=[MapPropertySource " but actually I want to get same properties as "Located property source: CompositePropertySource {name='consul', propertySources=[ConsulPropertySource"

**Comment by spencergibb** [comment]
That is from a different project, spring cloud consul

**Comment by dilipsingh1306** [comment]
Do you want me to add another  spring cloud consul dependency in Config Server application level to get it as counsul service ? 

In forums I am seeing as  default location is /config and all. Where should we create this /config folder i.e. inside server application resources folder?

Do weh ave any sample application for reference ?

**Comment by spencergibb** [comment]
There is no support for consul in config server.

**Comment by dilipsingh1306** [comment]
Thank you @spencergibb. 

Precisely my requirement is , I want to load  properties as 
name='consul', propertySources=[ConsulPropertySource" . 

How can I achieve this ?

**Comment by spencergibb** [comment]
You cannot thru config server right now.

**Comment by spencergibb** [comment]
You can do it without config server https://github.com/spring-cloud/spring-cloud-consul/blob/master/docs/src/main/asciidoc/spring-cloud-consul.adoc#distributed-configuration-with-consul

**Comment by dilipsingh1306** [comment]
Thank you @spencergibb for your time and data.
