### ISSUE TITLE
How to configure properties coming from Spring config server as bootstrap properties of client application

### ISSUE THREAD

**Issue by dilipsingh1306** [spring-cloud/spring-cloud-config#1269]

**Comment by ryanjbaxter** [comment]
That is not possible, bootstrap.properties needs to be local

**Comment by dilipsingh1306** [comment]
So That means, as per your response, 
 I can't use properties &values coming from spring config server at client app as bootstrap properties ?
 i.e. using server shared properties for bootstrapping client application (without mentioning again same in client bootstrap file).

**Comment by ryanjbaxter** [comment]
> I can't use properties &values coming from spring config server at client app as bootstrap properties ?

No.  What properties are you trying to use?

**Comment by dilipsingh1306** [comment]
I want to get consul host details "spring.cloud.consul.host=<external-host-name>" from config server and then client should connect to respective consul when we start up.

So here I don't want to configure  "spring.cloud.consul.host=<external-host-name>" in side client bootstrap properties. 

is it possible? then what can I do?

**Comment by dilipsingh1306** [comment]
> > I can't use properties &values coming from spring config server at client app as bootstrap properties ?
> 
> No. What properties are you trying to use?

I want to get consul host details "spring.cloud.consul.host=" from config server and then client should connect to respective consul when we start up.

So here I don't want to configure "spring.cloud.consul.host=" in side client bootstrap properties.

is it possible? then what can I do?

**Comment by spencergibb** [comment]
You can't do that. If you are only using consul for discovery, you can put those values in application.yml. If you are using it for configuration, I'm not sure that makes sense in combination with config server.

**Comment by dilipsingh1306** [comment]
Thank you so much @spencergibb for your time and information.
