### ISSUE TITLE
spring cloud config server does not want to take local cache

### ISSUE THREAD

**Issue by gholly** [spring-cloud/spring-cloud-config#1281]
If the config server does not connect to the git repository, it will read the cache file local to the config server.
But, If I want the config server not to take its own cache file, what should I do?

**Comment by ryanjbaxter** [comment]
I am not sure what you are asking, can you elaborate?

**Comment by gholly** [comment]
The scenario is like this. Due to network reasons, the config server failed to connect to the git repository configuration file. At this time, I modified the configuration file of the git repository, which will cause the config server to fail to connect to spring.cloud.config.server.git.uri:xxx. .git
The config server can't get the newly modified configuration file in real time. In this way, the config client will get the config server's cache file fie:/tmp/Xxxx when it connects to the config server, instead of the newly modified configuration.

This leads to the generation of dirty data.

**Comment by spencergibb** [comment]
That was an intentional design decision

**Comment by gholly** [comment]
First of all, thank you for your answer. If the design of the config server is like this, then I will have no problem, thank you.
