### ISSUE TITLE
Thread contention after migrating to Docker/Kubernetes: Blocked threads at java.util.jar.JarFIle from RequestMappingHandlerAdapter:invokeHandlerMethod

### ISSUE THREAD

**Issue by marcellodesales** [spring-cloud/spring-cloud-config#1284]
# Bug report

* We've been using Config Service in production serving a couple of hundreds of customers 
* We were serving using EC2 hosts and migrating to K8s and we started experiencing a very degraded performance

We hope you guys can shed some light into this problem we have... Everything started with current compatible calls:

* In EC2, serving configs run in less than `200ms` for the cached use cases
  * Those requests where the config-service has already cloned a given customer repos/branches
  * Those are PRF test calls showing `247ms` and `248ms`
 
![Screen Shot 2019-03-14 at 3 04 44 PM](https://user-images.githubusercontent.com/131457/54394595-92824780-466a-11e9-9ac2-088d0505af0f.png)

After we migrated to K8s, we started seeing more of the issue at this specific spot: the same method call taking around `2min` to complete...

![Screen Shot 2019-03-14 at 3 06 18 PM](https://user-images.githubusercontent.com/131457/54394657-c52c4000-466a-11e9-9dda-c685661d554a.png)

Pointing to some specific details of this call, we are investigating the root causes for this... 

![Screen Shot 2019-03-14 at 3 01 46 PM](https://user-images.githubusercontent.com/131457/54394466-2b649300-466a-11e9-9969-8d766853d25a.png)

Drilling down on this, we have the following info:

![Screen Shot 2019-03-14 at 3 03 17 PM](https://user-images.githubusercontent.com/131457/54394531-5c44c800-466a-11e9-9310-c79c19f31d59.png)

Then, looking at the details

![Screen Shot 2019-03-14 at 1 43 42 PM](https://user-images.githubusercontent.com/131457/54391741-fe60b200-4662-11e9-9fc8-5ef9b029e309.png)

The method is blocked at line `org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter:invokeHandlerMethod:827`

The threads blocked mostly at `java.util.jar.JarFIle`... 

```
Web Service - org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter:invokeHandlerMethod
Type	Web Service
Class	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter
Method	invokeHandlerMethod
Line Number	827
```

I found a thread at https://stackoverflow.com/questions/39956409/zipfile-getentry-causing-java-aplication-to-hang/43053570 which might be a similar thread around this problem... 

Looking at the source-code (we are using `spring-webmvc-4.3.18`) at https://github.com/spring-projects/spring-framework/blob/4.3.x/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/RequestMappingHandlerAdapter.java#L827, the call might be on the following line: 

```
modelFactory.initModel(webRequest, mavContainer, invocableMethod);
```

I hope that's pointing to the right direction... Could you guys help us find a solution to this? I have a couple of questions:

## Questions

* Is this filter trying to look at the Jar files for what purpose? 
* Is this Spring scanning for resources?
* Is there anything we need to do to skip this from happening?

As we can't just migrate to a newer version of Spring Cloud Config at this moment, we are looking to migrate to `K8S` without code changes... That's the reason why we dockerized our Config Service to run using Tomcat... 

# Information

* We are using a relatively old version https://github.com/spring-cloud/spring-cloud-config/releases/tag/v1.2.1.RELEASE
  * `SpringBoot`: spring-boot-1.5.15
  * `SpringMVC`: spring-webmvc-4.3.18.RELEASE.jar 
  * `Apache Tomcat`: apache-tomcat-8.0.36
  * `Spring Cloud Commons` 1.2.5
  * `Spring Cloud Context` `4.3.18`

We also ran our Config Service as a Runnar Jar as well... 

In regards to our infra:

* EC2 hosts `RHEL 6.10 `, where our baseline is currently running in Production env
  * Apache Tomcat Version `8.0.24` 
  * Oracle `JDK8-181 `
  * 4 EC2 hosts running on `c4.xlarge - 4cpu 7.5GiB`
  * JVM `JAVA_OPTS` with `-Xms2048m -Xmx2048m`

* K8s hosts `RHEL 7.4` where this experience is
  * Kubernetes `v1.10.11`
  * Docker Engine `17.3.2` 
  * Config Service Docker on `Oracle JDK8-181` on base Docker image `RHEL 7.5`
  * Deployed with 4 CPUs and 2GiB, but with similar `JAVA_OPTS` of `-Xms2048m -Xmx2048m`

After reading the thread at https://stackoverflow.com/questions/39956409/zipfile-getentry-causing-java-aplication-to-hang/43053570, we rebuilt the base Docker image with the following:

* Config Service Docker on `Oracle JDK8-181` on base Docker image `RHEL 6.10`

Thank you and hope someone has gone through this experience and can help out...

**Comment by ryanjbaxter** [comment]
Wow that is old.  We no longer support that version of Spring Cloud.  Also from your investigation I dont see anything that points to a problem in the Spring Cloud code it looks like you narrowed it down to Spring MVC.

**Comment by marcellodesales** [comment]
@ryanjbaxter That's really true, a very old version... We have plans to change our strategy in the coming months...

So, after matching the Tomcat version in the Docker container from `Apache Tomcat Version 8.0.36 to 8.0.24`, we were able to match the same performance numbers we have in our current environment!!!

Now, the question is: How can I take all the parameters used by the application in the Tomcat version 8.0.24 and apply those in a Runnable Jar with the embedded tomcat running in the Config Service? We started using the JAVA_OPTS `-showversion -XshowSettings:vm -XX:+PrintFlagsFinal` to show all details of the VM options resolved after its bootstrap in the section `Global flags`... 

```[Global flags]
    uintx AdaptiveSizeDecrementScaleFactor          = 4                                   {product}
    uintx AdaptiveSizeMajorGCDecayTimeScale         = 10                                  {product}
    uintx AdaptiveSizePausePolicy                   = 0                                   {product}
    uintx AdaptiveSizePolicyCollectionCostMargin    = 50                                  {product}
    uintx AdaptiveSizePolicyInitializingSteps       = 20                                  {product}
...
...
...
```

However, there are TOO MANY settings and most of them are decided by the VM itself... 

Are there any suggestions in how to migrate SpringBoot applications from Tomcat to the Runnable Jar and eliminate the need for Tomcat when running in Docker?

**Comment by marcellodesales** [comment]
Closing this, but we still need to answer what JVM options we need to use for Config Service to be ported from Tomcat to a Runnable Jar...

**Comment by marcellodesales** [comment]
@ryanjbaxter So, I changed the build to make a WAR file and wrapped it with `Tomcat 8.5.38`... Results were similar to our Production env in EC2 and now I'm trying to nail down the catalina properties used by the embedded jar...

According to https://stackoverflow.com/questions/44379278/spring-boot-tomcat-embedded-how-define-catalina-properties, we can use any property from https://tomcat.apache.org/tomcat-8.5-doc/config/systemprops.html to be applied to the embedded Tomcat server... However, It doesn't seem to work... 

# Question

* Do we need to prepend those properties with anything like the ones described at  `server.tomcat`? from the docs https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html?

**Comment by marcellodesales** [comment]
@dsyer @philwebb Any suggestions on this issue above? How to make the embedded tomcat take the system properties just like the regular Tomcat deployment passes (`conf/catalina.properties`)? 

Our Dockerized Config Service still can't perform using the embedded runnable Jar when compared with the WAR deployed in Tomcat (Also dockerized)

**Comment by dsyer** [comment]
Probably something to do with the file system - a vanilla EC2 VM and a k8s pod likely have very different attached file systems. Your mileage may vary, but I've never had an issue with either, so it must be something to do with the way you are running the apps.

**Comment by marcellodesales** [comment]
@dsyer thank you for your suggestion... We did try to use a `PVC` and eliminated the `fs/disk problem` when we dockerized a Full Tomcat version and deployed the Config Service as WAR instead of a runnable Jar... We can successfully deploy different versions of Tomcat such as `8.5.37` and `8.5.38` and still perform well in `K8S`... That's why I narrowed it down to the system properties used by the full Tomcat version without any file-system changes when deploying in K8S... 

This is the only SpringBoot app that we migrated to K8S that shows this symptom... :( Still looking...

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by marcellodesales** [comment]
Closing this as we won't be looking into this any further for the time being... If anyone has any suggestion, I would be appreciated...
