### ISSUE TITLE
Settings to disable ConfigServer HealthIndicator failed

### ISSUE THREAD

**Issue by deeravi** [spring-cloud/spring-cloud-config#1294]
I am using spring cloud config server with git backup. Version Finchley.RC2 for spring cloud dependency. Git server is polled repeatedly and I tried using health.config.enabled=false on bootstrap.properties on config server and it doesn't seem to have any effect. I have referred to the other issues reported for the same but with no avail. Please help !

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by deeravi** [comment]
Attaching a snapshot of what's happening in the production environment -  
![image](https://user-images.githubusercontent.com/38168882/54563058-7f7eb880-4985-11e9-911b-73da46728ff8.png)

**Comment by spencergibb** [comment]
The value is `spring.cloud.config.server.health.enabled`. Finchley.RC2 is not a supported version. The actual text is much preferred to screenshots.

**Comment by deeravi** [comment]
Thanks @spencergibb. What would be a better version ?

**Comment by spencergibb** [comment]
Finchley.SR3. This is config server only.

**Comment by deeravi** [comment]
I tried with Finchley.SR3 with the mentioned changes `spring.cloud.config.server.health.enabled` on config server. Tough luck. 
![image](https://user-images.githubusercontent.com/38168882/54628023-de017080-4a31-11e9-94cd-29f9702cff74.png)

**Comment by spencergibb** [comment]
> The actual text is much preferred to screenshots.

Those logs are from the config client, the mentioned property is for the server, not the client.

The value is indeed `health.config.enabled`.

> Can you provide a complete, minimal, verifiable sample that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by deeravi** [comment]
Hi @spencergibb, I have tried including `health.config.enabled` in config client as well to no avail.

**Comment by spencergibb** [comment]
> Can you provide a complete, minimal, verifiable sample that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by deeravi** [comment]
Hi all, Thanks all for your help. The changes that you suggested worked when placed within `application.yml`.
