### ISSUE TITLE
spring cloud config server overrides not working when bootsrap enabled

### ISSUE THREAD

**Issue by mehdikhelif** [spring-cloud/spring-cloud-config#1295]
Hello,

We are trying to update our cloud config server to Greenwhich.SR1 and boot 2.1.3.RELEASE but the spring.cloud.config.server.overrides is broken. It is quite easy to reproduce. This happens when spring.cloud.config.server.bootstrap is set to true and overrides are put on git. 
After some investigations, it seems that the problem is in `org.springframework.cloud.config.server.config.ConfigServerMvcConfiguration` 

```java
private EnvironmentRepository encrypted(EnvironmentRepository envRepository,
			ConfigServerProperties server) {
   EnvironmentEncryptorEnvironmentRepository encrypted = new 
   EnvironmentEncryptorEnvironmentRepository(
				envRepository, this.environmentEncryptor);
   encrypted.setOverrides(server.getOverrides());
   return encrypted;
}
```
That `EnvironmentEncryptorEnvironmentRepository` is initialized with the content of ConfigurationProperties `ConfigServerProperties` before it is rebound when the context is refreshed so it does not contain the values coming from Git. I think the solution would be to inject the `ConfigServerProperties` inside `EnvironmentEncryptorEnvironmentRepository` instead of passing the values.

This was tested with Finchley.SR3 and boot 2.0.8.RELEASE with same results.

**Comment by ryanjbaxter** [comment]
What are you upgrading from?

**Comment by mehdikhelif** [comment]
Hello @ryanjbaxter, thx for your quick reply. I am upgrading from Edgware.SR4/boot 1.5.14.RELEASE. But it does not really matter. I get exactly the same when creating a new config-server from scratch.

**Comment by ryanjbaxter** [comment]
Are you using a composite environment as well?
http://cloud.spring.io/spring-cloud-static/Greenwich.RELEASE/single/spring-cloud.html#_embedding_the_config_server

**Comment by mehdikhelif** [comment]
By default we dont but I already tried without success. However, I do not think it is related. The config is loaded correctly, just too late or the bean is created too early, depends how you see it

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by mehdikhelif** [comment]
Hello, you can find example here : https://github.com/mehdikhelif/config-server . I have created a small test verifying what I explained

**Comment by mehdikhelif** [comment]
Hey @ryanjbaxter any chance you had the time to have a look ?
