### ISSUE TITLE
spring-cloud-config-client cannot locate spring profiles active

### ISSUE THREAD

**Issue by i-tim-tang** [spring-cloud/spring-cloud-config#1296]
application.properties:
```
spring.application.name=hello
spring.profiles.active=prod
```

bootsrap.properties 
doesn't override name and profile with spring.cloud.config.name and profile

from the startup log info, spring-cloud-config-client had located the spring.application.name Environment, but NOT the spring.profiles.active Environment, it used the "default" profile.

later on the log, the Spring Boot application was using the right configed active profile, "prod"

Give me some tips?
thx in advance.

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Is the application.properties coming from the config server?

**Comment by i-tim-tang** [comment]
> Is the application.properties coming from the config server?

No.

before connecting to config server,  config client will first locate the application name and profile local, right ?

If i override profile setting in boostrap.properties
```
spring.cloud.config.profile=prod
```
config client will use this profile to get back configuration for config server.

i expect config client will use spring.profiles.active property in application.properties

**Comment by spencergibb** [comment]
Config client cannot read anything from application.properties only bootstrap. properties

**Comment by i-tim-tang** [comment]
> Config client cannot read anything from application.properties only bootstrap. properties

but config client had read **spring.application.name** from application.properties
i think it should read **spring.profiles.active** too.
defining name and profile property  in application.properties is more natural for me anyway...

**Comment by ryanjbaxter** [comment]
From our documentation

> If your application needs any application-specific configuration from the server, it is a good idea to set the spring.application.name (in bootstrap.yml or application.yml).

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
