### ISSUE TITLE
logging.config in remote server doesn't work in config client

### ISSUE THREAD

**Issue by G-Cat** [spring-cloud/spring-cloud-config#132]
Hi!

I'm trying to set which logback.xml file to use in application.yml file, which stores at spring-cloud-config repository, for example:

```
...

---
spring:
  profiles: production
logging:
  config: classpath:production.xml

...
```

Accordingly, I expect to get production.xml logback configurations at runtime if I set:

```
--spring.profiles.active=production
```

Unfortunately, it doesn't work! When I set production profile, my app starts to use its configuration...but only for one log message, for example: "Started Main in 40.865 seconds (JVM running for 44.9)" and that is all, after all it uses default Spring Boot logback configuration.

If I set this setting in app's application.yml - it works perfectly, but I need to store this setting at spring-cloud-config side.

I use the following Spring Boot and Spring Cloud dependencies:

```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>1.3.0.BUILD-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starters</artifactId>
                <version>1.0.0.BUILD-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

and this is my logback configuration:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <appender name="AMQP" class="org.springframework.amqp.rabbit.logback.AmqpAppender">
        <layout>
            <pattern>
                {
                "time": "%date{ISO8601}",
                "thread": "%thread",
                "level": "%level",
                "class": "%logger{36}",
                "message": "%message"
                }
            </pattern>
        </layout>

        <!-- RabbitMQ connection -->
        <host>...</host>
        <port>...</port>
        <username>...</username>
        <password>...</password>

        <routingKeyPattern>logs</routingKeyPattern>
        <declareExchange>true</declareExchange>
        <exchangeType>topic</exchangeType>
        <exchangeName>service.logs</exchangeName>

        <generateId>true</generateId>
        <charset>UTF-8</charset>
        <durable>true</durable>
        <deliveryMode>NON_PERSISTENT</deliveryMode>
    </appender>

    <root level="INFO">
        <appender-ref ref="AMQP"/>
    </root>
</configuration>
```

**Comment by dsyer** [comment]
The loggers are configured really early (for obvious reasons), so they aren't seeing your remote configuration properties. It's a bit chicken and egg (how do you log without the configuration, and how to you report the progress of loading the configuration without logging), but we can probably do something to bump the loggers once the remote configuration is available.

You will see what I mean if you POST to /refresh after startup (the logger will switch to the new configuration).

**Comment by G-Cat** [comment]
Great thanks! 

/${management.context-path}/refresh works perfectly, but I can't call it on all services every time after I start it.

As I understand, your commit fix it and re-initialize log configuration after communication with Config Server. How can I use spring-cloud with your fix? What I should to add in my pom.xml dependencies?

**Comment by dsyer** [comment]
You need a snapshot I guess. They are deployed automatically, but might be more reliable to build it yourself this week (I think the build is broken and I'm travelling).

**Comment by spencergibb** [comment]
@dsyer @G-Cat I fixed the builds this morning with the exception of spring-cloud-cli.  Snapshots should work because [this build](https://travis-ci.org/spring-cloud/spring-cloud-commons/builds/60244611) completed.

**Comment by ccit-spence** [comment]
Are there any problems with only using the snapshot for the config clients and the config server?  Basically not using the snapshot for everything else.

**Comment by dsyer** [comment]
It's a risk obviously. At the minute it's a minimal risk because there are no other changes in master and nothing big is planned for 1.0.x (but some people are asking us to make changes, e.g. see #124).

**Comment by ccit-spence** [comment]
I will try it for a little while.  We are implementing aggregated logging and need this bit of code for it to work correctly.  And you are right that change would be fun!  Any idea when this will go into the release build?

**Comment by ccit-spence** [comment]
Just an FYI, everything with new build snapshot works perfectly.  Will reload the logback config with new settings based on `logging.config` properties.  Thanks for adding this!
