### ISSUE TITLE
Error loading config files in config server on Windows

### ISSUE THREAD

**Issue by marmanan** [spring-cloud/spring-cloud-config#133]
I have upgraded config-server from 1.0.0 to 1.0.1 and I have found that when running in windows config server is not able to find any config file. 
The problem seems to be in method clean in class NativeEnvironmentRepository, it doen not take into account the "\" in windows environments.

**Comment by dsyer** [comment]
Are you using the "native" profile, or just hitting `NativeEnvironmentRepository` somewhere in the call stack? I don't remember that method changing, but it's protected, so you can override it to provide a workaround. When you have some clean code that works, please post it back here (or send a PR).

**Comment by marmanan** [comment]
I was using JGitEnvironmentRepository that call NativeEnvironmentRepository.findOne. 
I guess the clean method was changed in this commit: https://github.com/spring-cloud/spring-cloud-config/commit/b1ba8df0660f9f2853ce9a075a5122206f25b71a#diff-b99e10d657a99285c8ffad46c3ad2052

I think I can´t override NativeEnvironmentRepository because JGitEnvironmentRepository  is calling the constructor of this class.

**Comment by abrochard63** [comment]
I sent a PR for fixing this bug (https://github.com/spring-cloud/spring-cloud-config/pull/135)
