### ISSUE TITLE
Types in Json endpoints in Config Server

### ISSUE THREAD

**Issue by marmanan** [spring-cloud/spring-cloud-config#134]
The new json endpoints are not keeping types integer and boolean in the output json file, it surrounds the values with quotes.  This is a problem for javascript clients consuming these endpoints.
The types are correct when the number or boolean values are located in nested object but not if the properties are placed in root level in the json object. 

Example.
source:

```
prop1Bool: true
prop2Int: 1
prop3Str: hello
prop4List:
  - "item1"
  - "item2"
  - "item3"
```

`/foo-dev.json` returns:

```
{"prop4List":["item1","item2","item3"],"prop1Bool":"true","prop2Int":"1","prop3Str":"hello"}
```
expected:

```
{"prop4List":["item1","item2","item3"],"prop1Bool":true,"prop2Int":1,"prop3Str":"hello"}
```

**Comment by dsyer** [comment]
It doesn't even work as well as that for me. I don't think I would have expected it to either. How did you set up that source?

**Comment by dsyer** [comment]
This actually requires a fix in Spring Boot: https://github.com/spring-projects/spring-boot/issues/2891
