### ISSUE TITLE
[Question] The way to access private git repo.

### ISSUE THREAD

**Issue by Incarnation-p-lee** [spring-cloud/spring-cloud-config#1342]
As I know, when we use private git backend, there are two ways to get the credentials:

* User/password from application.yml
* Ssh config from local or application.yml.

My question may contains 2 part:
* is the all authN/Z way to access private git repo of spring cloud config for now, right ?
* If so is there any plan to support some authN/Z way to access private git repo, for example, github Oauth2 application ?

Thanks in advance! Please correct me if something misunderstanding.

**Comment by ryanjbaxter** [comment]
We have no plans to support other ways of authentication/authorization other than the ones that are currently supported.
