### ISSUE TITLE
Config Client Can Not Refresh Automatically

### ISSUE THREAD

**Issue by PeichengLiu** [spring-cloud/spring-cloud-config#1347]
Question

Here is my [sample application](https://github.com/PeichengLiu/spring-cloud-config-sample-project).

Step to reproduce my issue:
1. Start the `discovery-service` with default profile, the `config-service` with default profile, and the `client-service` with `zone1` profile.
2. Change value of `sample.string.prop` property in `client-service-zone1.yml` file of `config-repo` repository, stage changed, commit, push.

You can see from the console logs that `config-service` is refreshing its context , while `client-service` remains unchanged.

**Comment by PeichengLiu** [comment]
Can anyone give me a hand, please?

**Comment by leogoing** [comment]
I have the same problem, Have you solved your problem? @PeichengLiu

**Comment by PeichengLiu** [comment]
@leogoing According to the [document](https://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.1.3.RELEASE/single/spring-cloud-config.html#_push_notifications_and_spring_cloud_bus),

> you can trigger a change notification by POSTing to `/monitor` with form-encoded body parameters in the pattern of `path={name}`. Doing so broadcasts to applications matching the `{name}` pattern (which can contain wildcards).

I have verified this using Postman.

[![TIM截图20190710212908.png](https://i.loli.net/2019/07/10/5d25e8321a55e30921.png)](https://i.loli.net/2019/07/10/5d25e8321a55e30921.png)

However, I don't know how to send the custom payload with GitLab Webhooks. And I can't find the solution neither from the [document](https://docs.gitlab.com/ce/user/project/integrations/webhooks.html) nor Google.

What's more, with this approach, we have to specify the APP name. This limitation may be unacceptable under certain circumstances. While we can surely write some additional script to verify the delta and then specify the APP name accordingly.

**Comment by PeichengLiu** [comment]
@leogoing According to the [document](https://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.1.3.RELEASE/single/spring-cloud-config.html#_push_notifications_and_spring_cloud_bus),

> you can trigger a change notification by POSTing to `/monitor` with form-encoded body parameters in the pattern of `path={name}`. Doing so broadcasts to applications matching the `{name}` pattern (which can contain wildcards).

I have verified this using Postman.

[![TIM截图20190710212908.png](https://i.loli.net/2019/07/10/5d25e8321a55e30921.png)](https://i.loli.net/2019/07/10/5d25e8321a55e30921.png)

However, I don't know how to send the custom payload with GitLab Webhooks. And I can't find the solution from neither the [document](https://docs.gitlab.com/ce/user/project/integrations/webhooks.html) nor Google.

What's more, with this approach, we have to specify the APP name. This limitation may be unacceptable under certain circumstances. While we can surely write some additional script to verify the delta and then specify the APP name accordingly.

**Comment by spencergibb** [comment]
I'm afraid that's a limitation of gitlab, there's not anything we can do.
