### ISSUE TITLE
Spring Config Server - Error when specifying conf files

### ISSUE THREAD

**Issue by jyacine** [spring-cloud/spring-cloud-config#1351]
Hi,

I'm using the versions above : 

<spring.cloud.version>Greenwich.SR1</spring.cloud.version>
<spring.cloud.config>2.1.1.RELEASE</spring.cloud.config>

While investifgation the source code, I found that an issue in the class : `org.springframework.cloud.config.server.environment.NativeEnvironmentRepository`. The method 

`public Locations getLocations(String application, String profile, String label)`

At line 188, a  check is made to identify if the path is a directory or not =>
```
if (isDirectory(value)) {
       output.add(value);
}
```
The isDirectory method check the conditions above :
```
private boolean isDirectory(String location) {
		return !location.contains("{") && !location.endsWith(".properties")
				&& !location.endsWith(".yml") && !location.endsWith(".yaml");
}
```

But juste before the call if isDirectory, the path is changed like that (line 185):
```
if (!value.endsWith("/")) {
	value = value + "/";
}
```
So we will always have true returned from isDirectory (even if the file is specified)

Best regards,
Yacine

**Comment by spencergibb** [comment]
Can we take a step back? Before telling us what you think is a specific flaw in a class, tell us what you are trying to do and what isn't working?

**Comment by jyacine** [comment]
Maybe the title is confusing.
It's just a remark(when I read the source code). Btw, my code works fine :-).

**Comment by spencergibb** [comment]
I'll go ahead and close this then if there are no errors occurring. If you'd like to try and fix it, PRs welcome, just make sure all the tests pass.
