### ISSUE TITLE
eureka.instance.appname and spring.application.name

### ISSUE THREAD

**Issue by geemu** [spring-cloud/spring-cloud-config#1358]
The eureka.instance.name of the configuration center cannot be used by the microservice client to obtain the configured spring.cloud.config.discovery.service-id. The spring.application.name of the breeding must be set. Is this a bug? Or say that appname is just a name and cannot be used for configuration fetching.

If I only set the appname, then my client can't find the corresponding configuration center. I have to set spring.application.name. What is the role of appname? I see the comment saying this: Get the name of the application to be registered with eureka. Is this a bug?

version:
  2.1.4.RELEASE
  Greenwich.RELEASE

**Comment by spencergibb** [comment]
It is not a bug. spring.application.name is used as the default for various fields in Spring Cloud. Including the config name and eureka application name.

**Comment by geemu** [comment]
If I set eureka.instance.appname then the name in eureka will be replaced with eureka.instance.appname, but I still need to use the configuration in spring.application.name to get the configuration, but the configuration center shows eureka. The configuration of instance.appname, the annotation of appname is: Get the name of the application to be registered with eureka, then what is the role of appname? Just to display a name?

**Comment by ryanjbaxter** [comment]
Maybe you can explain why you want to two to be different?
