### ISSUE TITLE
an issues about zookeeper 3.4.14 and spring cloud config

### ISSUE THREAD

**Issue by hongdaliu** [spring-cloud/spring-cloud-config#1359]
Thanks for raising a Spring Cloud issue. 

Question

I set some config in bootstrap.yml 
`cloud:
    config:
      enabled: true
      name: zookeeper-client
      uri: http://..........`

Bug report

generally, spring cloud config will load remote config files first.
but, zookeeper discovery running at first and connect localhost/127.0.0.1:2181 address

**Comment by spencergibb** [comment]
Can you please describe the problem in more detail. What you're doing, what is happening and what you think should happen. Please include versions.

**Comment by hongdaliu** [comment]
> Can you please describe the problem in more detail. What you're doing, what is happening and what you think should happen. Please include versions.


of course. I want put my config files in github repo, and i create a zookeeper config file in it.
i make a config client project and make a spring.cloud.config.name property ,put zookeeper config file name . I click running project button, the log shows zookeeper connect localhost/127.0.0.1:2181 not the address i set on github

**Comment by hongdaliu** [comment]
> Can you please describe the problem in more detail. What you're doing, what is happening and what you think should happen. Please include versions.

can you help me to solve this problem?

**Comment by ryanjbaxter** [comment]
What is the name of the property file in your git repo?  Why are you setting `spring.cloud.config.name` instead of using `spring.application.name`?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
