### ISSUE TITLE
spring cloud config bus-refresh not working

### ISSUE THREAD

**Issue by thapld** [spring-cloud/spring-cloud-config#1361]
I play with spring cloud config 2.1.0 and I dont see endpoint bus-refresh when start application.
I only see endpoint bus-env, so I can't refresh my service.

`2019-04-24 10:26:53.633  WARN [haft-config,,,] 30356 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'bus-env' contains invalid characters, please migrate to a valid format.
2019-04-24 10:26:53.824  WARN [haft-config,,,] 30356 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.`

Here my config

`server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://haft:haft123@haft-eureka:8761/eureka/

spring:
  application:
    name: @artifactId@
  cloud:
    stream:
      bindings:
        springCloudBusInput:
          destination: config-bus
          group: haft-config
        springCloudBusOutput:
          destination: config-bus
    config:
      retry:
        initial-interval: 3000
        multiplier: 1.5
        max-interval: 20000
        max-attempts: 6
      server:
        native:
          search-locations: file:///E:/scanner_center/SVN/config-repos/development

management:
  endpoint:
    health:
      show-details: always
    bus-refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        exclude: bus-refresh
`

Here my pom:

`<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
		</dependency>
		<dependency>
			<groupId>vn.com.hafintech</groupId>
			<artifactId>haft-common-slf4j</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-monitor</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-stream-rabbit</artifactId>
		</dependency>
		<dependency>
			<groupId>vn.com.hafintech</groupId>
			<artifactId>haft-common-web</artifactId>
		</dependency>`

Can you help me? Thank you so much.

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Why are you excluding the endpoint?

```
management:
    endpoint:
       health:
          show-details: always
        bus-refresh:
           enabled: true
     endpoints:
           web:
                 exposure:
                     exclude: bus-refresh
```

**Comment by zhousiyi25420** [comment]
explode interface /actuator/bus-refresh?

**Comment by spencergibb** [comment]
That is a warning, what is actually not working?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
