### ISSUE TITLE
logback-spring.xml spring.application.name setting not work with spring cloud config

### ISSUE THREAD

**Issue by abccbaandy** [spring-cloud/spring-cloud-config#1362]
I'm using `spring.application.name` in my `logback-spring.xml`
````xml
<springProperty scope="context" name="spring.application.name" source="spring.application.name" defaultValue="default-app"/>
````

It work well when I put `spring.application.name` in `bootstrap.yml`.

But when I put it in my remote config(spring cloud config git repo), it seems read the `spring.application.name` too late. Because the service name in eureka list changed but not logback setting.

**Comment by ryanjbaxter** [comment]
You should not be putting `spring.application.name` in remote config files, it should always be in either `bootstrap.yml` or `application.yml`.  It plays a key role in many pieces of functionality very early on in application startup.

**Comment by abccbaandy** [comment]
So there is no way to do that?

I can't put it in `bootstrap.yml` or `application.yml`, because I have multiple `spring.application.name`.

Currently workaround is `-Dspring.application.name` to override the name, but it doesn't seems like a good way.

**Comment by spencergibb** [comment]
It's a problem of what is needed first. We need to send spring.application.name to config server therefore it can not come from config server. Any local configuration will work. There's really no other way.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
