### ISSUE TITLE
the system environment variable of Linux system does not work

### ISSUE THREAD

**Issue by cheninitial** [spring-cloud/spring-cloud-config#1366]
I use the "spring-cloud-starter-config : 2.1.2.RELEASE" 
in the git project ".yml" file, I set "spring: datasource: url: 
jdbc:mysql://www.exampleA.com"
<img width="368" alt="图片" src="https://user-images.githubusercontent.com/26613683/56845231-af0fd180-68f0-11e9-8d39-0ffbf3375179.png">

in the k8s.yaml file I put a new system environment variable "SPRING_DATASOURCE_URL" and "SPRING_PROFILES_ACTIVE" But "SPRING_DATASOURCE_URL"  does not work.
![图片](https://user-images.githubusercontent.com/26613683/56845294-83411b80-68f1-11e9-878f-41ba378011c4.png)

this is bootstrap.yml of my client application 
![图片](https://user-images.githubusercontent.com/26613683/56845277-49701500-68f1-11e9-8e92-03ad452721d4.png)

**Comment by spencergibb** [comment]
I'm sorry, I'm unsure what this has to do with spring cloud config. Also, screenshots are difficult to read

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
