### ISSUE TITLE
Sharing configuration between applications and profiles

### ISSUE THREAD

**Issue by gitmykeul** [spring-cloud/spring-cloud-config#1368]
Hi,

I would like each microservice to read properties from 4 property files, meaning for a service called "myService" with profile "dev", I want to be able to read from the following **Git folders**:

- config/myService/application-dev.yml (specific config for this service and this profile)
- config/myService/application.yml (specific config for this service no matter which profile)
- config/application-dev.yml (specific config for dev profile no matter which service)
- config/application.yml (shared config no matter which service, no matter which profile)

I tried several patterns in **search-paths** but when I start myService, it reads everything except the last one: application.yml from the root folder (config/application.yml)

Here is my config:
```spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ssh://git@xxx:7999/qi/athena.git
          clone-on-start: true
          search-paths: '*,{application},config/{application}, config/, config/*'
          #search-paths: '{application}'
          #search-paths: 'config/{application}'
```

It seems the **_Sharing Configuration With All Applications_** does not work as expected:
[https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html#_sharing_configuration_with_all_applications](url)

Am I missing something?

For info I am using Finchley.SR2 version.

Thank you.

**Comment by ryanjbaxter** [comment]
Can you try with Finchley.SR3?  Is you can still reproduce it can you provide a sample that demonstrates the problem?

**Comment by gitmykeul** [comment]
I tried with Finchley.SR3 but still have the same issue.

Config service - application.yml:

```
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ssh://git@xxx:7999/qi/config.git
          clone-on-start: true
          search-paths: '*,{application},config/{application}, config/, config/*'
```

myService - bootstrap.yml:
```
spring:
  application:
    name: myService
  cloud:
      config:
        uri: http://localhost:8888
```

Remote Git repository:
config/application-dev.yml (specific config for dev profile no matter which service)
config/application.yml (shared config no matter which service, no matter which profile)

		
When I start myService, I am getting:
```
14:02:10.589 [main] INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at : http://localhost:8888
14:02:14.150 [main] INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Located environment: name=myService, profiles=[dev], label=null, version=5cb49c7b47d918db4e1e37d627cfe1c7673d2199, state=null
14:02:14.151 [main] INFO  o.s.c.b.c.PropertySourceBootstrapConfiguration - Located property source: CompositePropertySource {name='configService', propertySources=[MapPropertySource {name='configClient'}, MapPropertySource {name='ssh://git@xxx:7999/qi/config.git/config/application-dev.yml'}]}
```

When I issue a Rest request to the environment endpoint controller, I get:

GET localhost:8888/myService/dev/

```

{
    "name": "myService",
    "profiles": [
        "dev"
    ],
    "label": null,
    "version": "5cb49c7b47d918db4e1e37d627cfe1c7673d2199",
    "state": null,
    "propertySources": [
        {
            "name": "ssh://git@xxx:7999/qi/config.git/config/application-dev.yml",
            "source": {
                "spring.profiles": "dev",
                "spring.profiles.include[0]": "enable_mongo_ssl",
                "spring.profiles.include[1]": "greenzone",
                "environment": "dev",
                "mongo.environment": "dev",
                "eems.environment": "dev",
                "server.ssl.enabled": false
            }
        }
    ]
}
```

Only application-dev.yml is read. I can't make application.yml to be read/retrieved.

Thank you.

**Comment by gitmykeul** [comment]
application.yml  and application-dev.yml are in the same repository and in the same directory called "config".

**Comment by gitmykeul** [comment]
I would like to debug this. What class/method should I look at?
I checked AbstractScmEnvironmentRepository class, findOne method: 
```
Locations locations = getLocations(application, profile, label);
```
I can see that the locations are correct: config-repo-123 and config-repo-123/config
But then I am loosing the thread when debugging:
```
Environment result = delegate.findOne(application, profile, "");
```

**Comment by gitmykeul** [comment]
The problem was the content of the files that were not read. If by mistake there is a property:
```
spring.profiles: some_profile
```
then application.yml file is not read.

Same if you have for example:
```
spring.profiles: prod
```
in an application-uat.yml file.

I guess this is the right behavior to ignore such files since this is an inconsistency or conflict. However an error or warning message should have helped in this case instead of ignoring silently the file.
