### ISSUE TITLE
CloudConfig client doesn't get config from ConfigServer after upgrading spring-cloud from 1.0.0.RELEASE to 1.0.1.RELEASE

### ISSUE THREAD

**Issue by DirkLachowski** [spring-cloud/spring-cloud-config#137]
I have a working microservice build against 1.0.0.RELEASE and are getting my properties from a remote cloud config server. After upgrading the microservice to 1.0.1.RELEASE the service doesn't start anymore because of not resolvable property placeholders:

    Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'cassandra.seeds' in string value "${cassandra.seeds}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174) 

When reverting back to 1.0.0.RELEASE the service again starts.

Maybe related:

     ConfigClientAutoConfiguration.ConfigServerHealthIndicatorConfiguration
          - @ConditionalOnClass classes found: org.springframework.boot.actuate.health.HealthIndicator (OnClassCondition)
          - matched (OnPropertyCondition)
          - @ConditionalOnBean (types:     org.springframework.cloud.config.client.ConfigServicePropertySourceLocator; SearchStrategy: all) found no beans (OnBeanCondition) 

Is any additional action necessary when upgrading to 1.0.1?

**Comment by spencergibb** [comment]
@DirkLachowski We separated the starters, so config is not auto-included anymore.  Do you have `spring-cloud-starter-config` included?

**Comment by DirkLachowski** [comment]
@spencergibb Much better, that fixed it. Thanks for your help.
