### ISSUE TITLE
In want config server to read k8s config map

### ISSUE THREAD

**Issue by avikjis27** [spring-cloud/spring-cloud-config#1371]
Is it possible to make config server to read properties from kubernetes config map just like git or vault?

In our environment, micro service wants to access secret from the vault and some configurations from the config map. The values of the config maps are injected by some infrastructure layer code. We want to provide micro service applications a unified interface to interact with vault as well as with the config map so that applications helm chart become clean and organized. We want to use spring-cloud-config as the standard layer between our applications and different source of configurations. We know, spring-cloud-config can integrate with vault but not sure if it can talk to k8s it this point?

Thanks in advance.

**Comment by spencergibb** [comment]
See https://cloud.spring.io/spring-cloud-kubernetes/spring-cloud-kubernetes.html#_kubernetes_propertysource_implementations. It's not something we're currently looking at providing for config server specifically.
