### ISSUE TITLE
QUESTION: Potential performance issue with JGit

### ISSUE THREAD

**Issue by habuma** [spring-cloud/spring-cloud-config#1372]
It seems that the `readAdvertisedRefs()` method (https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/transport/BasePackConnection.java#L180) is called from pretty much all of JGit's connection types as soon as a connection is established. 

This is fine under normal circumstances. But what if the backing Git repo has an enormous number of refs (where "enormous" is unknown at this point, but there is one SCS customer that apparently knows what enormous means)? It could result in delays in creating a connection and potential timeouts.

My concern is that if config server is backed by JGit and if JGit fetches all refs on every connection, then performance will degrade in config-server as the number of refs increases. The issue is in JGit, but wondering what can be done to avoid this or if there's opportunity for improvement in JGit.

**Comment by spencergibb** [comment]
ping @habuma. IIRC, there wasn't much we could do here.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
