### ISSUE TITLE
Filemonitor does not work for git repositories with file:// url

### ISSUE THREAD

**Issue by dl1ely** [spring-cloud/spring-cloud-config#1374]
I configured `spring.cloud.config.server.git.uri: file://c:/test/`, with C:/test/ being a local git repo.
I expected the file monitor to watch this git repo for changes.

In https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-monitor/src/main/java/org/springframework/cloud/config/monitor/FileMonitorConfiguration.java#L197 the repository URL gets loaded as a `Resource`. File watching will only be enabled when `resource instanceof FileSystemResource`, but the Default ResourceLoader will never return a FileSystemResource, only a FileUrlResource, so file monitoring does not work for a file:// url. As long as the default ResourceLoader is used, the instanceof check can never be true. In case of the native Repositories, the searchlocations URL(s) are loaded as resources but only checked if they exist (https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-monitor/src/main/java/org/springframework/cloud/config/monitor/FileMonitorConfiguration.java#L211).

I could only fix that by providing a ProtocolResolver that uses a FileSystemResourceLoader for URLs starting with file://, thus returning a FileSystemResource for such URLs as described here: https://stackoverflow.com/a/51420272/727373

I think, either the check on the SCM repository URLs should be made less restrictive (why is this check more strict as the check for the native repository URL?), or at least documentation should be improved to help providing the necessary ProtocolResolver.

**Comment by spencergibb** [comment]
Yeah, I'm sure it's original intent was NativeEnvironmentRepository not git.

Not sure I'm comfortable with a custom `ProtocolResolver`, but maybe there's something else that could be done.

**Comment by dl1ely** [comment]
I am also not happy with the custom ProtocolResolver because it is global and might have unintended side-effects, but i found no other way to fix the behaviour. IMHO relaxing the `instanceof` check to `resource instanceof FileSystemResource || resource instanceof FileUrlResource` would fix it. The check for `FileSystemResource` could even be removed, because a SCM repo URL can never be a `FileSystemResource`, only a `FileUrlResource` at best.  But for the purpose of the file monitoring, both resource types should work, shouldn't they? The monitoring for the native repositories also works with file:// URLs.

**Comment by dl1ely** [comment]
Should i take a shot and allow an instance of FileUrlResource in addition to FileSystemResource to activate the file monitor on at https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-monitor/src/main/java/org/springframework/cloud/config/monitor/FileMonitorConfiguration.java#L197 ? I see no obvious downside.

**Comment by spencergibb** [comment]
PRs welcome
