### ISSUE TITLE
Auto refreshing the properties on client through configuration

### ISSUE THREAD

**Issue by thefalconfeat** [spring-cloud/spring-cloud-config#138]
its not very clear for me going through the documentation, but we have a need to configure certain set of application to get refreshed(properties) every 10 min and its becomes hazy to trigger /refresh every 10 min manually. Is it something that we can configure on the client application, if so how do we do it..?

**Comment by dsyer** [comment]
You can easily `@EnableScheduled` and add a bean that calls the `RefreshEndpoint.refresh()` method every 10min (or whatever schedule you like of course). `@EnableScheduled` is a Spring core feature.

**Comment by thefalconfeat** [comment]
we are using cloudfoundry to deploy our applications, and it would be hard to get the exact endpoint of all the instances, especially when the application is running with multiple instances.

**Comment by spencergibb** [comment]
@thefalconfeat he's not suggesting you make a rest, call, but use `@EnableScheduled` IN your application to call `RefreshEndpoint.refresh()` directly in java code.

**Comment by thefalconfeat** [comment]
thanks, this is helpful

**Comment by jmnarloch** [comment]
Hi, I was wondering if you could consider at least implementing a kind of event publishing within the config server something similar to: https://github.com/jmnarloch/spring-cloud-config/commit/c1a003525d40ce3897a53ab02bbce5c01766867d#diff-14f7a9bbd398562fdfd12ce9f6619d7cR179

With at least such API it would be trivial for anyone to implement on top of that selective push notifications/refreshes to Eureka/Ribbon configured nodes in it's application.

**Comment by spencergibb** [comment]
@jmnarloch you should open a new issue rather than commenting on one that is closed.

**Comment by spencergibb** [comment]
@jmnarloch please disregard my comment, I see you opened a new issue :-)

**Comment by jmnarloch** [comment]
Done
