### ISSUE TITLE
Document linux keytool warning or update command

### ISSUE THREAD

**Issue by jbprek** [spring-cloud/spring-cloud-config#1380]
According to the documentation for [Creating a Key Store for Testing](https://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_creating_a_key_store_for_testing) the command to create a test keystrore is:
```
keytool -genkeypair -alias mytestkey -keyalg RSA \
  -dname "CN=Web Server,OU=Unit,O=Organization,L=City,S=State,C=US" \
  -keypass changeme -keystore server.jks -storepass letmein
```

However, the specific command for keytool with JDK 11 on Linux gives the following error:

Warning:  Different store and key passwords not supported for PKCS12 KeyStores. Ignoring user-specified -keypass value.

**Comment by ryanjbaxter** [comment]
It is just a warning, but yes we could add a note or change the documentation so they match
