### ISSUE TITLE
Property overrides feature of spring cloud config server not working as expected

### ISSUE THREAD

**Issue by Swatikp** [spring-cloud/spring-cloud-config#1384]
Question

I recently came accross property overrides feature of spring cloud config server from the documentation below:
[property overrides](https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html#_property_overrides
)

So what I did was I inserted common DB url in spring config server bootstrap.properties file as follows:
```
spring.cloud.config.server.overrides.db.url=http://localhost:5050
```
In my spring clients property file I have :
```
db.url=http://localhost:8080
```

but when i run my client application, database url thatmy client picks up is **http://localhost:8080**

What I understood from the documentation was :
<br/>
_The preceding examples causes all applications that are config clients to read db.url=http://localhost:5050, independent of their own configuration._

But why my client is still overriding the property provided.

Any help regarding this issue will be appriciated.

Thanks.

**Comment by ryanjbaxter** [comment]
Did you set `spring.cloud.config.overrideNone=true` on the client?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Swatikp** [comment]
Hi @ryanjbaxter I have not specified spring.cloud.config.overrideNone=true on the client side.

But the documentation [here](https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html#_property_overrides) does not mention any such thing.

**Comment by ryanjbaxter** [comment]
Sorry I mispoke, `spring.cloud.config.overrideNone` should be set to `true` in the configuration file for the client in the remote repository.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
