### ISSUE TITLE
connecting spring config server with client by username and password. How can we achieve this requirement.? 

### ISSUE THREAD

**Issue by dilipsingh1306** [spring-cloud/spring-cloud-config#1388]
I have multiple config clients and all are connected to config server and it's working as expected . 
ahead of that we are trying to provide authentication to access config server from clients i.e.  to access config server in future by any client then authentication is required. 

I tried to find out  solution for this but failed to get it . 

Please help me which are properties are required for this.

**Comment by ryanjbaxter** [comment]
Have you read the documentation?
http://cloud.spring.io/spring-cloud-static/Greenwich.SR1/single/spring-cloud.html#_security

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
