### ISSUE TITLE
Dynamic refresh and bootstrap mode for multiple repo configuration

### ISSUE THREAD

**Issue by Binary00** [spring-cloud/spring-cloud-config#139]
Currently a `spring-cloud-config-server` has configuration for multiple repositories . It would be nice if that configuration could be loaded from a git repo and possibly reloaded automatically on a configurable scheduled amount of time. 

I know currently spring boot apps have the ability to point at configuration files anywhere and then call `/refresh` to reload the properties. Which is a way we've been able to reload repos "conveniently" w/o redeploying the whole app. 

I know when you're in development you want a fast turnaround, that was the reasoning for the automatic refresh. This could be used with a properties server in development mode. In production, maybe only load the properties from a git repo on startup and on a `/refresh` hit. Obviously this could be configured as needed per environment.

**Comment by dsyer** [comment]
> reloaded automatically on a configurable scheduled amount of time

You can do that yourself. Just add `@EnableScheduled` and a `@Bean` that has a `@Scheduled` method that calls the `RefreshEndpoint.refresh()` method.

**Comment by Binary00** [comment]
I'll take note of the `RefreshEndpoint.refresh()` method. 

How would that work with a git remote repo configuration, instead of a file system based approach?

**Comment by dsyer** [comment]
It's the same. The remote config is reloaded on refresh.

**Comment by Binary00** [comment]
Maybe I'm missing something. 

I'm running a standalone `spring-cloud-config-server` with multiple repositories it serves up for configuration. 

```
spring: 
   cloud:
    config:
      server:
        git:
          repos:
            service_name1: https://git-url/service-name1-config.git
            service_name2: https://git-url/service-name2-config.git
            service_name3: https://git-url/service-name3-config.git
```

That configuration lives in a `bootstrap.yml` file and has to be manually updated on the filesystem where the `spring-cloud-config-server` is running. Whenever a new repo is added the `/refresh` needs to be called, or as you mentioned above it could be scheduled. 

I was thinking it would be possible to have the config above get those configuration repos from a git endpoint. 

```
spring: 
   cloud:
    config:
      server:
        git:
          configrepos: https://git-url/config-repos.git
```

That config repo (https://git-url/config-repos.git) would contain:

```
repos:
  service_name1: https://git-url/service-name1-config.git
  service_name2: https://git-url/service-name2-config.git
  service_name3: https://git-url/service-name3-config.git
```

Maybe this can be done already through other means that I haven't figured out yet, or I wasn't explaining myself correctly. Or this could just be overkill for a feature, just makes it easy to add a new config repo w/o even having to touch the property server's configuration.

**Comment by dsyer** [comment]
Maybe you are trying something and it doesn't work, and I admit I haven't, but I don't see why it wouldn't if you tried it the way I think you should. I think you only need a git repo URL in `bootstrap.yml` if you set the flag `spring.config.server.bootstrap=true` (the ones for the apps themselves are not needed until the server has started). If you never set that flag I guess you are stuck with local configuration for the config server. If you do set the flag then I expect the remote repository can contain additional repository configuration (as long as it refers back to itself, so it can locate itself when you want to refresh).

**Comment by Binary00** [comment]
I've tried the following in the `spring-cloud-config-server':

```
boostrap.yml {

spring:
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://git-url/config-repos.git

}
```

That will serve up configuration for multiple services/apps, but that seems to require every service/app configuration to exist in that one repo. 

For example:

```
https://git-url/config-repos.git
  /service_name1-dev.yml
  /service_name2-dev.yml
```

We were hoping to have one config repo for each service/app instead of one monster configuration repo. 

```
https://git-url/service_name1-config.git
  /service_name1-dev.yml
  /service_name1-prod.yml

https://git-url/service_name2-config.git
  /service_name2-dev.yml
  /service_name2-prod.yml
```

Maybe I'm still doing something wrong? Should that `spring.config.server.bootstrap=true` be able to reference `spring-cloud-config-server` configuration in the git repo? I wasn't able to get the following to work.

For example:

```
https://git-url/config-repos.git
  application.yml

application.yml {

spring:
  cloud:
    config:
      server:
        git:
          repos:
            service_name1: https://git-url/service_name1-config.git
            service_name2: https://git-url/service_name2-config.git

}
```

Thanks again for walking me through this.

**Comment by Binary00** [comment]
Ok well I was able to get the `spring-cloud-config-server` to startup using a git repo using the `spring.config.server.bootstrap=true` flag. I didn't have the application name set. I now see on startup that its refrencing `https://git-url/config-repos/configserver.yml` as a property source. 

It still doesn't seem to be using the data in that file to serve up properties.  

```
configserver.yml {

spring:
  cloud:
    config:
      server:
        git:
          repos:
            service_name1: https://git-url/service_name1-config.git
            service_name2: https://git-url/service_name2-config.git

}
```

If I request `/server_name1/default` I don't get any properties. I've tested the git urls on a normal startup using `bootstrap.yml` explicitly, they work fine. 

I'm not sure how `MultipleJGitEnvironmentRepository` would populate its repos, would it populate with the remote config mentioned above? The after properties set on `MultipleJGitEnvironmentRepository` seems to be getting called before `PropertySourceBootstrapConfiguration`, which would lead me to believe that those properties wouldn't be available to `MultipleJGitEnvironmentRepository`. I'm not exactly sure the order of operations going on there.

**Comment by dsyer** [comment]
The `afterProperties()` should be called on refresh, but maybe not the first time (which would be odd). I can't really guess any more so I'll have to try it myself.

**Comment by Binary00** [comment]
Yeah doesn't look like `MultipleJGitEnvironmentRepository` is being initialized with the remote repos. If I call a `/refresh` I can see `MultipleJGitEnvironmentRepository.afterPropertiesSet()` being called with the updated remote repos like you mentioned, but I don't think its re-wired up to the controller. The app will not reference the newly populated repos. 

This is assuming I have everything configured right.  Again, thanks for taking the time.

**Comment by mroowa000** [comment]
We have the same requirement as Binary00. Wondering if you got a chance to look at this.

**Comment by dsyer** [comment]
I have half a solution, or at least an explanation and a workaround. You have to rebind the "environmentRepository" to the `Environment` *after* the application starts up because the first time it binds (in bootstrap mode) is in the bootstrap phase before any remote configuration is yet available. That is to say, after the server starts your repos configuration will be in the `Environment` (you will see them in `/admin/env`) but a `/refresh` doesn't rebind them because the target bean is in the parent context. To get at the parent context you can use the existing `ConfigurationPropertiesBindingPostProcessor` from the main context and ask it to rebind a bean by name (which will then be resolved in the parent). E.g. this code will work:

```
	@ManagedOperation
	public void rebind(String name) {
		if (!this.applicationContext.containsBean(name)) {
			return;
		}
		Object bean = this.applicationContext.getBean(name);
		this.binder.postProcessBeforeInitialization(bean, name);
		if (this.applicationContext != null) {
			this.applicationContext.getAutowireCapableBeanFactory().initializeBean(
					bean, name);
		}
	}
```

where `binder` is the `ConfigurationPropertiesBindingPostProcessor` and `applicationContext` is the main context. A bean with that method which is `@ManagedResource` will expose a generic bean rebinder JMX endpoint, and if you call it with the argument "environmentRepository" it will rebind and change the repository configuration.

I'll add that code to the existing `ConfigurationPropertiesRebinder` MBean, and have a think about how to  make it work without the additional manual refresh.

**Comment by Binary00** [comment]
I got a solution working. Not really fond of it, but it works until a more formal solution is available :). 

All of the code is below. I do want to say that I had to find out the hard way I couldn't just add repos to the repo hash map in `RemoteMultipleJGitEnvironmentRepository`, I had to diff them manually otherwise every time a repo is instantiated it creates a hash of that on the file system. I ended up filling up the file system, just adding all of the repos fresh each time since I was refreshing on a pretty rapid rate. 

Theres a config repo just for the properties server `<configserver-giturl>` that contains `configserver.yml` and `repos.yml`. The properties server is bootstrapped using the remote repo. 

```java
@Configuration
@EnableConfigurationProperties(ConfigServerProperties.class)
public class Config {

  @Bean
  public EnvironmentRepository environmentRepository(ConfigurableEnvironment environment) {
    return new RemoteMultipleJGitEnvironmentRepository(environment);
  }
}

@ConfigurationProperties("configrepos")
public class RemoteMultipleJGitEnvironmentRepository extends MultipleJGitEnvironmentRepository {

  private CountDownLatch latch;
  private JGitEnvironmentRepository remoteRepo;

  public RemoteMultipleJGitEnvironmentRepository(ConfigurableEnvironment environment) {
    super(environment);
    remoteRepo = new JGitEnvironmentRepository(environment);
  }

  @Override
  public void afterPropertiesSet() throws Exception {
    remoteRepo.setUri(getUri());

    Environment environment = remoteRepo.findOne("repos", null, remoteRepo.getDefaultLabel());

    Map<String, PatternMatchingJGitEnvironmentRepository> repos = super.getRepos();

    List<String> repoNames = new ArrayList<>();
    environment.getPropertySources().get(0).getSource()
      .forEach((key, value) -> {
        String repoName = key.toString().replace("repos.", "").trim();
        repoNames.add(repoName);

        if(value != null && value instanceof String) {
          String uri = value.toString().trim();

          PatternMatchingJGitEnvironmentRepository existingRepo = repos.get(repoName);
          if(existingRepo != null) {
            String existingURI = existingRepo.getUri();

            if(!uri.equals(existingURI)) {
              repos.put(repoName, new PatternMatchingJGitEnvironmentRepository(uri));
            }
          } else {
            repos.put(repoName, new PatternMatchingJGitEnvironmentRepository(uri));
          }
        }
      });

    Iterator<String> currentRepoIter = repos.keySet().iterator();
    while(currentRepoIter.hasNext()) {
      String currentRepoName = currentRepoIter.next();

      if(!repoNames.contains(currentRepoName)) {
        currentRepoIter.remove();
      }
    }

    super.setRepos(repos);
    super.afterPropertiesSet();

    if(latch != null) latch.countDown();
  }

  public JGitEnvironmentRepository getRemoteRepo() {
    return remoteRepo;
  }

  public CountDownLatch getLatch() {
    return latch;
  }

  public void setLatch(CountDownLatch latch) {
    this.latch = latch;
  }
}

@Component
@ConditionalOnBean(value = EnvironmentRepository.class, type = "RemoteMultipleJGitEnvironmentRepository")
@ConditionalOnProperty("configrepos.refresh")
public class RepoRefresh {

  @Autowired private EnvironmentRepository repository;

  @Scheduled(fixedDelayString = "${configrepos.delay}")
  public void refreshRepos() throws Exception {
    ((RemoteMultipleJGitEnvironmentRepository) repository).afterPropertiesSet();
  }

}

@SpringBootApplication
@EnableConfigServer
@EnableScheduling
public class PropertiesServiceApplication {

  public static void main(String[] args) {
    SpringApplication.run(PropertiesServiceApplication.class, args);
  }

}

```

boostrap.yml
```yml
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: <configserver-giturl>
```

configserver.yml
```yml
configrepos:
  uri: <configserver-giturl>
  refresh: true
  delay: 5000
```

repos.yml
```yml
repos:
  app1: <app1-config-giturl>
  app2: <app2-config-giturl>
  app3: <app3-config-giturl>
```

**Comment by dsyer** [comment]
That's useful to know thanks. I would prefer a more generic solution which addresses the deeper problem that beans in the parent context are not bound to the full runtime `Environment`. It wouldn't have to know anything about git or repositories.

**Comment by sprgn** [comment]
Property name correction so search would find this `spring.cloud.config.server.bootstrap`

**Comment by Roronoa-Zoro** [comment]
if I get two projects, payment-app and account-app, and we have a git uri: https://xxxx.git, we leave master branch alone, we create another two branches, payment-app and account-app, in each branch we create our yml files. it looks like below
-- branch
master(empty)
payment-app
-payment-app.yml
account-app
-account-app.yml
we maintain different project config file in separate branch, is this ok ?

**Comment by ryanjbaxter** [comment]
@Roronoa-Zoro please open a separate issue

**Comment by remo408** [comment]
Hi Just was curious if the support for this kind of setup is now included in the configserver project?

**Comment by dsyer** [comment]
What is "this kind of setup"? This issue was closed 2 years ago. If you are looking for a feature try the user guide, or stackoverflow.

**Comment by remo408** [comment]
Hi dsyer i tried to implement the solution mentioned above and i am getting following error:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'environmentRepository' defined in class path resource [com/test/services/DynamicConfig.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: You need to configure a uri for the git repository
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1275)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1180)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1096)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:659)
	... 42 common frames omitted
Caused by: java.lang.IllegalStateException: You need to configure a uri for the git repository
	at org.springframework.util.Assert.state(Assert.java:70)
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.afterPropertiesSet(JGitEnvironmentRepository.java:169)
	at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.afterPropertiesSet(MultipleJGitEnvironmentRepository.java:68)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 55 common frames omitted
```

My bootstrap.yml:

```
spring:
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https:<url>
          searchPaths: '{application}'
          force-pull: true
```

**Comment by dsyer** [comment]
The code above is redundant (that's why this issue was closed).

**Comment by remo408** [comment]
hi dsyer, so how can we configure the case where i can dynamically update the repo configuration? 
I went through the documentation and couldn't find any feature that supports it other than 

```
spring:
  cloud:
    config:
      server:
        git:
          uri: file:/C:/Users/pu580r/dev/local/demo/{application}
```
but not something where i could dynamically update the entire URI. Pleasea advice

**Comment by dsyer** [comment]
If you have a usage question please put it on Stckoverflow. If it's a new feature, please create a new issue.

**Comment by remo408** [comment]
Hi dsyer i opened an new issue :https://github.com/spring-cloud/spring-cloud-config/issues/788 where i was pointed to this issue.
