### ISSUE TITLE
config can not refresh

### ISSUE THREAD

**Issue by mufool** [spring-cloud/spring-cloud-config#1391]
config can not refresh like this!
```
public class ElasticsearchConfiguration implements FactoryBean<TransportClient>, InitializingBean, DisposableBean {

    private MyServerProperties myServerProperties;

    private TransportClient transportClient;

    @Autowired
    public ElasticsearchConfiguration(MyServerProperties myServerProperties) {
        this.myServerProperties = myServerProperties;
    }
...
}
```
and i can received remote refresh request.

**Comment by spencergibb** [comment]
I'm afraid you've not provided enough information. Can you explain what you want to happen and what is actually happening?

**Comment by scottfrederick** [comment]
@mufool Assuming what you are saying is that

* `MyServerProperties` is a bean annotated with `@ConfigurationProperties` that gets populated from Spring Cloud Config
* You want the values in `MyServerProperties` to be refreshed when a Spring Cloud Config refresh event happens

then the first thing I'd do is make sure the `MyServerProperties` bean is also annotated with `@Component` or a similar Spring stereotype annotation to make sure it is included in the `RefreshScope` context.

**Comment by spencergibb** [comment]
Actually, we don't recommend `@Component` on configuration properties. 

If it is marked as `@ConfigurationProperties` the `MyServerProperties` will automatically be rebound. What won't though is `ElasticsearchConfiguration`. It needs to be marked as `@RefreshScope`.

**Comment by scottfrederick** [comment]
Interesting - the `@Component` trick fixed a similar problem for me recently. What's the downside to using that on config properties? 

I'll try `@RefreshScope` on the container bean and see if that solves the problem I was having too.

**Comment by spencergibb** [comment]
AFAICR it was a boot recommendation.

**Comment by mufool** [comment]
```
@Data
@ConfigurationProperties("myserver")
public class MyServerProperties {
    private String test;
    ...
}
```
MyServerProperties like this！

When i use  implements `FactoryBean<TransportClient>`  and autowired `MyServerProperties` this way
``` 
   @Autowired
    public ElasticsearchConfiguration(MyServerProperties myServerProperties) {
        this.myServerProperties = myServerProperties;
    }
```
Then Spring Cloud Config refresh not working.

**Comment by spencergibb** [comment]
What does "not working" mean?

**Comment by mufool** [comment]
> What does "not working" mean?

Client configuration files cannot be automatically refreshed via rabbitmq messages

**Comment by spencergibb** [comment]
Which ones?

**Comment by mufool** [comment]
Solved in another way. Thanks!
