### ISSUE TITLE
Use of spring.profiles.include in Config Server

### ISSUE THREAD

**Issue by gitmykeul** [spring-cloud/spring-cloud-config#1395]
I have a spring boot application. I am using **spring.profiles.include** in application.yml to add some active profiles according to a given profile, then I am using those active profiles for bean creation as below:

application.yml:
```
spring:
  profiles: prod
  profiles.include:
    - enable_tls
    - enable_mongo_ssl
```

Configuration class - bean creation according active profiles:
```
@Configuration
@PropertySource("classpath:/mongo-${mongo.environment}.properties")
public class MongoConfiguration {
    @Bean
    @Profile("enable_mongo_ssl")
    public MongoClientOptions.Builder mongoClientOptionsBuilder() {
        return getMongoClientOptionsBuilder();
    }
```

This works fine.
However when I remove application.yml from the classpath and use external config through Spring Cloud Config - with Git repository, this does not work. The active profiles is only prod and does not include "enable_tls" and "enable_mongo_ssl", thus at bean creation, the statement:
```
@Profile("enable_mongo_ssl")
```
 is no longer true.

When I query the environment controller, I can see the profiles enable_tls and enable_mongo_ssl:
```
 "profiles": [
        "prod"
    ],
    "label": null,
    "version": "2ddd208fff7caa48b2ae41d69020325ce61f241e",
    "state": null,
    "propertySources": [
        {
            "name": "file:///C://dev/config-repo/config/application-prod.yml",
            "source": {
                "spring.profiles.include[0]": "enable_tls",
                "spring.profiles.include[1]": "enable_mongo_ssl",
                "server.ssl.key-store-password": "ENC(xxx)",
            }
        }
```

Is there a limitation? Can we use spring.profiles.include in an external configuration and not in the classpath application.yml file?

For info I am using Finchley.SR3 version.

My current workaround solution is to have all properties externalized in Config Server except spring.profiles.include remaining in the application.yml classpath file.

**Comment by gitmykeul** [comment]
I will follow your recommendation and keep the spring.profiles.include within classpath application.yml.
Other properties will be in config server. Thank you.

**Comment by ryanjbaxter** [comment]
It can be but at that point we are not going to make another request to the config server to fetch the configuration, we need the information upfront.

**Comment by gavenkoa** [comment]
We are using `logback-spring.xml` with `<springProfile name=...>` extension.

It allows us selectively enable logging to file/console/ES/mongo/db.

We'd like to `spring.profiles.include: log-to-es` for PROD and `spring.profiles.include: log-to-file` for STAGE.

Currently we need to embed prod/stage names into `logback-spring.xml` instead of externalizing env configs and just keep feature-flags like `log-to-file` or `log-to-db`.

I understand that making recursive calls to server from client isn't implemented though it breaks pure Spring Boot experience.

**Comment by gavenkoa** [comment]
https://stackoverflow.com/questions/56163411/spring-profiles-include-property-from-spring-cloud-config
