### ISSUE TITLE
Specify Custom file names at Spring Cloud Client

### ISSUE THREAD

**Issue by iamTheL** [spring-cloud/spring-cloud-config#1399]
My Config Server has the following files: 

- `application.properties`
- `order-dev.properties`
Everything works file with the `order` service with the db and message properties in the same file. 

Now I wish to split the `.properties` file as follows:
`orderdb-dev.properties` and `order-dev.properties`.

How can I specify the `order` client to pick properties from `order-dev` and `orderdb-dev` only ? There are other clients too which I want to configure in similar fashion. 

Can it be done ?

Versions:
Spring Boot: 2.1.5.Release
Spring Cloud Version: Greenwich.SR1

**Comment by ryanjbaxter** [comment]
`orderdb` and `order` represent application names, maybe a better approach would be to use `order-db-dev` and `order-dev` so `db` is just another profile you enable.

**Comment by iamTheL** [comment]
@ryanjbaxter . Thanks will check it out.
