### ISSUE TITLE
Scheduler is not working with RefreshScope

### ISSUE THREAD

**Issue by thefalconfeat** [spring-cloud/spring-cloud-config#140]
When a class is annotated with,@Configuration, @EnableScheduling, @RefreshScope the scheduler is not working.
Once I removed the @RefreshScope, scheduler started working.

**Comment by spencergibb** [comment]
I don't think `@RefreshScope` works on configuration classes, you should put it on a bean definition.

**Comment by dsyer** [comment]
It's mentioned here: http://projects.spring.io/spring-cloud/spring-cloud.html#_refresh_scope
