### ISSUE TITLE
how to serving pure plain-text with special word?

### ISSUE THREAD

**Issue by githubyong** [spring-cloud/spring-cloud-config#1401]
version Finchley.RELEASE,when serving plain-text file like this:
```
${mt:WAIT,0275}   name:${psi:WAIT,0181}
```
it result that:
```
WAIT,0275  name:WAIT,0181
```

the words "${mt:" lost,is there have some config to prevent springcloudconfig transfering file ?

**Comment by spencergibb** [comment]
Config server resolves placeholders. You'll need to escape them.
