### ISSUE TITLE
Use local working copy when git host isn't available for config server

### ISSUE THREAD

**Issue by Binary00** [spring-cloud/spring-cloud-config#141]
The issue of HA was brought up here #4. Does that mean when a git host goes down the property server will continue to serve up files if a particular repo has already been referenced? 

I've tested this out locally and haven't had luck with that. 

Steps Used:
1.  Pointed a configuration server at a git repo. Using a short dns timeout. `java.security.Security.setProperty("networkaddress.cache.ttl" , "10")`
2.  Hit a property endpoint to get that repo pulled down locally.
3.  Update my local hosts file to point to 127.0.0.2 for the git host used in step 1. 
4.  Hit the same property endpoint in step 2. The connection proceeded to timeout. 

It'd be nice to have a configuration timeout for a git host, if that timeout is exceeded the local file system is used in the event those properties have been requested before. 

I know there is the ability to use the `file:/` option for a git uri to point locally, I didn't know if there was any redundancy with remote git repos. 

Thanks!

**Comment by dsyer** [comment]
I'm not sure about the DNS trick you did, but simply switching off the network forces the repository to fallback on the local working copy, so I'm surprised it didn't work the same way (possibly after a timeout). You should see this kind of thing in logs:

```
2015-05-06 07:24:11.384  WARN 22528 --- [nio-8888-exec-5] o.s.c.c.s.JGitEnvironmentRepository      : Remote repository not available
2015-05-06 07:24:11.397  WARN 22528 --- [nio-8888-exec-5] o.s.c.c.s.JGitEnvironmentRepository      : Could not pull remote for master (current ref=Ref[refs/heads/master=90a65e05a4883622b82613b45c30f23de4ae1675]), remote: https://github.com/spring-cloud-samples/config-repo
```

but you still get a response from the server and it uses the local working copy.

**Comment by Binary00** [comment]
I was able to test switching off the network as you did and I got a quick timeout and was served up the local working copy. 

Further testing done using the DNS trick above with different hosts that weren't 127.0.0.2:
* Host that was up, but wasn't listening on port 80/443. 
  * Got a quick timeout. 
  * Was served up local copy. 
* Host that wasn't up at all. 
  * Took ~15 seconds to timeout.
  * Was served up local copy.   
* Host with a listener that would allow tcp connections, but would never respond to an http request.  
  * Never seemed to timeout, waited ~15mins, still waiting.
  * Super extreme edge case. 

So different situations have different timeouts. I think for the most part quick timeouts are what we'd be experiencing (Self hosted git upgrades, server down, etc). I think there is still the edge case that a server would accept a connection and not respond (application server under high load).  

After the testing above, not sure if an enhancement is needed/warranted. 

Thanks again.

**Comment by bprakash** [comment]
hi @dsyer 
I need this fix. Is this released to maven? I am using -'org.springframework.cloud:spring-cloud-config-server:1.0.2.RELEASE' but I dont think it has this fix/enhancement.

**Comment by dsyer** [comment]
1.0.3 is the latest GA release. Why didn't you use that? What makes you think it isn't working?
