### ISSUE TITLE
/refresh not working if management.security.enabled=true

### ISSUE THREAD

**Issue by MVinayK** [spring-cloud/spring-cloud-config#1411]
If i do not give management.security.enabled=true or even do not give it then refresh url is not working it gives 401 -- Full authentication is required to access this resource. I am testing it from soap ui and do not understand what authentication it needs , I even skipped it from our inhouse authentication. can anyone tell how i can expose it without any authentication and with management.security.enabled=true otherwise sonar complaines about it.

**Comment by ryanjbaxter** [comment]
You must have spring security on the classpath.  You can either disable spring security or configure it so the `/refresh` endpoint is not protected.

**Comment by MVinayK** [comment]
I will try that and other thing is i exposed a custom url (eg : "/custom-refresh")  which calls the refresh method of spring class which i will autowire in my custom controller and provide authentication to it. Wouldn't that be a good solution.

**Comment by Nyamkhuub** [comment]
Perhaps, You couldn't config your authorization configure, in just my opinion. If you enable security, you should be using basic-auth or password.  and if you will try to change management URL, you just change management port.
[https://docs.spring.io/spring-boot/docs/1.4.1.RELEASE/reference/html/production-ready-monitoring.html](Official documentation)

**Comment by MVinayK** [comment]
That was helpful, I was able to find it . Thanks @ryanjbaxter  and @Nyamkhuub
