### ISSUE TITLE
IntelliJ Checkstyle config is missing

### ISSUE THREAD

**Issue by claymccoy** [spring-cloud/spring-cloud-config#1414]
The readme contains instructions for setting Checkstyle up in IntellliJ. Those instructions reference `spring-cloud-build-tools/src/main/resources/intellij/Intellij_Spring_Boot_Java_Conventions.xml`. I don't see this file (or the related ones under main) anywhere in the repo. Maybe the files have been removed?
I'd be happy to test the config and update the readme if I knew what the current config was.

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-build/tree/master/spring-cloud-build-tools/src/main/resources/intellij

**Comment by spencergibb** [comment]
The source for that portion of the readme is from https://github.com/spring-cloud/spring-cloud-build/blob/master/docs/src/main/asciidoc/contributing.adoc

**Comment by spencergibb** [comment]
It does mention spring-cloud-build but doesn't link out.

**Comment by claymccoy** [comment]
Thanks! It makes sense now. I have everything set up, and I'll add a link specifying that most of that is in the spring-cloud-build repo (except for the additional suppressions).
