### ISSUE TITLE
When refresh, TimerTask is scheduled again

### ISSUE THREAD

**Issue by dlsrb6342** [spring-cloud/spring-cloud-config#1415]
I'm using spring-cloud-config with custom logback appender and logback xml files are got from spring-cloud-config-server.

And custom appender has list of ILoggingEvent. And with TimerTask check if size is not 0 every interval, and if not, send it to remote log collect server. 
```
// Simple CustomAppender
public class CustomAppender extends UnsynchronizedAppenderBase<ILoggingEvent> {

    private final List<ILoggingEvent> loggingEvents = Lists.newArrayList();
 
    @Override
    public void start() {
        Timer timer = new Timer(true);
        TimerTask timerTask = new TimerTask() {
            @Override
            public void run() {
                if (false == loggingEvents.isEmpty()) {
                    // send ILoggingEvent to remote log collect server
                }
            }
        };

        timer.schedule(timerTask, 1000, 1000);
    }

    @Override
    protected void append(ILoggingEvent eventObject) {
        loggingEvents.add(eventObject);
    }
}
```

If call /actuator/refresh, new context make another custom appender. At this time, new TimerTask is scheduled. **After new context closed, new custom appender is stopped but TimerTask is not destroyed. There are two appenders when refresh finished.**

Although it seems more appropriate to handle with CustomAppender, I think it would be nice that spring-cloud-config check about scheduled job if possible.

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by dlsrb6342** [comment]
https://github.com/dlsrb6342/timer-task-sample

Here is my example code. 
**master** branch is source code for config-client and config-server.
**config** branch is resource files for config-client.

There are two modules (server and client). The Server is watching `config` branch in same repo.
client module has `CustomAppender` which is extended `ConsoleAppender` and print some message.
`CustomAppender` is just simple example that uses `TimerTask`.


First, run `ServerApplication`. After then, run `ClientApplication`.   you can see `application.yml` in `config` branch. ClientApplication get `logback-spring.xml` from config-server.
```yml
# application.yml
logging:
  config: http://localhost:8888/**/local/config/logback-spring.xml
```

And then, request /actuator/refresh to `ClientApplication`. it will refresh context. After finishing refresh, you can see CustomAppender's message is printed twice. 
Refresh Context makes one more TimerTask.

I think it is problem about CustomAppender, but it would be good to warn to spring-cloud-config's users who use TimerTask..

**Comment by TYsewyn** [comment]
Hi @dlsrb63421! You see this issue because you didn't dispose of the allocated resources.
To solve this you would need to create the timer outside the start method only once.
Next you'll need to override the `stop` method so you can cancel the scheduled tasks.

Based on the example you provided it would look like this:

```
public class CustomAppender extends ConsoleAppender<ILoggingEvent> {
    
    private static final int BULK_SIZE = 100;

    private final List<ILoggingEvent> loggingEvents = new ArrayList<>();
    private final Timer timer = new Timer(true);

    @Override
    public void start() {
        TimerTask timerTask = new TimerTask() {
            @Override
            public void run() {
                System.out.println("Pending logging events : " + loggingEvents.size());
                if (loggingEvents.size() > BULK_SIZE) {
                    // send ILoggingEvent to remote log collect server
                    loggingEvents.clear();
                }
            }
        };

        this.timer.schedule(timerTask, 1000, 1000);
        super.start();
    }

    @Override
    protected void append(ILoggingEvent eventObject) {
        this.loggingEvents.add(eventObject);
        super.append(eventObject);
    }

    @Override
    public void stop() {
        super.stop();
        this.timer.cancel();
    }
}
```

Hope that helps! :)

**Comment by dlsrb6342** [comment]
Hi @TYsewyn ! Thanks for kindly comment.
But I know how to prevent duplicated timerTask. 
As I mentioned in first comment, `CustomAppender` must be fixed to solve problem. 

spring-cloud-config run new Context for refreshing. Because of this, scheduled job with `Timer` can be registered duplicately. So this issue is the question about whether spring-cloud-config can check scheduled job or not.

**Comment by TYsewyn** [comment]
Oh, my bad! :)
AFAIK, if you create the timer and schedule tasks yourself within a bean then there is no way for us to handle that, unless you implement the `InitializingBean` and `DisposableBean` interfaces where you create/destroy the needed resources in the required methods.

**Comment by dlsrb6342** [comment]
I thought so too. I think there is no way to handle registered TimerTask in bean. 
For users, It would be great to warn about TimerTask or scheduled job.

**Comment by TYsewyn** [comment]
We have [Spring Batch](https://spring.io/projects/spring-batch) or [Spring Cloud Task](https://spring.io/projects/spring-cloud-task) for scheduled jobs.
