### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [spring-cloud/spring-cloud-config#1416]
Hi
The following lines have cryptographic API misuses. <br> File name => spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/AwsCodeCommitCredentialProvider.java: Line number => 256: API name => SecretKeySpec:<BR> File name => spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/AwsCodeCommitCredentialProvider.java: Line number => 256: API name => SecretKeySpec:<BR>

**Comment by spencergibb** [comment]
What about them is a misuse?

**Comment by TYsewyn** [comment]
Hi @mhp0rtal! Thanks for the clarification.
However I still don't see why this is a misuse of the cryptographic API.
That function is using the HMAC SHA256 algorithm to generate the signature of the message, and doesn't do any encryption.

If this is still a misuse, would you be able to provide us a proper solution or a pull request?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
