### ISSUE TITLE
need to call two branches with in one git repository. 

### ISSUE THREAD

**Issue by nischayreddy** [spring-cloud/spring-cloud-config#1422]
I have a spring client application which is using a cloud server, I have a branch for each environment, for example, client STAG points to STAG branch in http://@giturl.So, what I'm trying to do is creating another branch called common which consists of common properties across the environment. I want to point STAG branch from client application to cloud server and as well as to common branch which retrieves all the common properties used across all the environments, Tried to use the composite type in a cloud server in application.yml by defining the same URL and different labels no luck on that any thoughts?

**Comment by spencergibb** [comment]
This is not currently supported

**Comment by nischayreddy** [comment]
This feature is not supported or someone here cannot support?
