### ISSUE TITLE
Unwanted document key from empty YAML file

### ISSUE THREAD

**Issue by slavashvets** [spring-cloud/spring-cloud-config#1428]
Spring Cloud Version: Finchley.SR2

### Steps to reproduce

* Create a file with the following content (empty yaml):

application-staging.yml
```
---
```

* Query GET on cloud-config server like `/(name)/(profiles)/(label)`

### Expected result

Don't see "staging" file in the output list

### Actual result

There is unwanted `document` key

```json
...
    {
      "name": "git@mshop-git-config:repo.git/application-staging.yml",
      "source": {
        "document": ""
      }
    },
...
```

### Workaround

Remove `---` from application-staging.yml

**Comment by spencergibb** [comment]
You created an empty document and it gave you an empty document. I'm not sure we'd want to change that behavior.

**Comment by ryanjbaxter** [comment]
Is it causing any kind of error?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
