### ISSUE TITLE
RefreshScope not works on kotlin class

### ISSUE THREAD

**Issue by YegorBabarykin** [spring-cloud/spring-cloud-config#1432]
I have this test service:
```kotlin
@Component
class TestService (val env: Environment) {
    fun get(property: String): String? {
        return env.getProperty(property)
    }
}
```
It works as good as should. But when i am trying to add `@RefreshScope` i get this error: `Caused by: java.lang.IllegalArgumentException: Cannot subclass final class org.test.service.TestService`
This exception can be solved by add `open` to class TestService definition:
```kotlin
...
@RefreshScope
open class TestService(val env: Environment) {
...
``` 

But in this example env property is not initialized (`env = null`)

**Comment by TYsewyn** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by YegorBabarykin** [comment]
I solved this problem by addiing configuration to kotlin-maven-plugin
```xml
<configuration>
    <compilerPlugins>
        <plugin>spring</plugin>
    </compilerPlugins>
</configuration>
```
