### ISSUE TITLE
github webhook has JSON parse error

### ISSUE THREAD

**Issue by linux5396** [spring-cloud/spring-cloud-config#1438]
# Question

When i used the github webhook to post a notification to spring-config-bus ,i met a error occurred,"github webhook has JSON parse error". How to solve it? I solve it on another way.

# Bug report

EX :JSON parse error

# Solutions

Use the spring-config-monitor to replace it. it means endpoints will be fixed "/monitor". In my opinion , I think we should solve by myself.So i tried.

# Result
` 
@Component
@Slf4j
public class WebHookWrapper extends HttpServletRequestWrapper implements Filter {
    private final RefreshBusEndpoint refreshEndpoint;

    @Autowired
    public WebHookWrapper(@Qualifier("httpServletRequest") HttpServletRequest request, RefreshBusEndpoint refreshEndpoint) {
        super(request);
        this.refreshEndpoint = refreshEndpoint;
    }

    @Override
    public ServletInputStream getInputStream() throws IOException {
        byte[] bytes = new byte[0];
        ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(bytes);
        return new ServletInputStream() {
            @Override
            public boolean isFinished() {
                return byteArrayInputStream.read() == -1;
            }
            @Override
            public boolean isReady() {
                return false;
            }
            @Override
            public void setReadListener(ReadListener readListener) {
            }
            @Override
            public int read() throws IOException {
                return byteArrayInputStream.read();
            }
        };
    }

    @Override
    public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain) throws IOException, ServletException {
        HttpServletRequest httpServletRequest = (HttpServletRequest) servletRequest;
        HttpServletResponse httpServletResponse = (HttpServletResponse) servletResponse;

        String url = new String(httpServletRequest.getRequestURI());

        //rest request pass here.
        if (!url.endsWith("/bus-refresh")) {
            filterChain.doFilter(servletRequest, servletResponse);
            return;
        }
        log.info("Receive {} request bus-refresh and use webHookWrapper.", httpServletRequest.getRemoteAddr());
        //sprcify the destination. can support specified service notified.
      refreshEndpoint.busRefreshWithDestination(httpServletRequest.getParameter("destination"));
        log.warn("PUBLISH ENDING.");
    }}
 `

By doing this, we don't need to use monitor dependency.

**Comment by spencergibb** [comment]
/bus/refresh was not meant to be used from a webhook. `/monitor` was built for that purpose.
