### ISSUE TITLE
Issue connecting to data base as Backend from Cloud Config Server

### ISSUE THREAD

**Issue by santhoshgs** [spring-cloud/spring-cloud-config#1442]
I have configured - cloud-config-server for connecting to DB backend (postgreSQL ) , when i start my Config server i'm getting below error:

--------------------- Error On Startup-------

APPLICATION FAILED TO START
Description:
Invalid config server configuration.
Action:
If you are using the git profile, you need to set a Git URI in your configuration. If you are using a native profile and have spring.cloud.config.server.bootstrap=true, you need to use a composite configuration.

---------------------- End Of Error -------------------------

i have set "spring.profiles.active=jdbc" in server - application.properties file.

Config-Server Code:
[config-db-server.zip](https://github.com/spring-cloud/spring-cloud-config/files/3495111/config-db-server.zip)

Config-Server-Client Code:
[config-db-client.zip](https://github.com/spring-cloud/spring-cloud-config/files/3495112/config-db-client.zip)

DDL:

CREATE TABLE PROPERTIES (
   application VARCHAR (10),
   profile VARCHAR (10),
  label VARCHAR (10),
	key VARCHAR (10),
	value VARCHAR (10)
);

**Comment by ryanjbaxter** [comment]
Please try using `spring-boot-starter-jdbc`

**Comment by santhoshgs** [comment]
> Please try using `spring-boot-starter-jdbc`

Thank you very much @ryanjbaxter  , it works!! 
Curios to know , will @RefreshScope restart Spring Application context as well ? when we do actuator/refresh.
will any of the inflight transactions gets affected when we Refresh any bean marked @RefreshScope

**Comment by ryanjbaxter** [comment]
> Curios to know , will @RefreshScope restart Spring Application context as well ? when we do actuator/refresh.

Yes 

>will any of the inflight transactions gets affected when we Refresh any bean marked @RefreshScope

yes
