### ISSUE TITLE
/env on client does not refresh from config server

### ISSUE THREAD

**Issue by rubesMN** [spring-cloud/spring-cloud-config#145]
With spring-cloud-config code as of 3 weeks ago, I am not able to get clients to get updated config server values (via updates to the backing git repo) using the actuator endpoint /env.  This applies to @ConfigurationProperties annotated classes and @Value annotated properties.   This seems in contradiction to the documentation which has the following:

POST to /env to update the Environment and rebind @ConfigurationProperties and log levels

**Comment by spencergibb** [comment]
have you tried `/refresh`?

**Comment by rubesMN** [comment]
Yes, /refresh works if the `@RefreshScope` annotation is used.

**Comment by spencergibb** [comment]
I think that there is a misunderstanding of what `POST /env` does then.  You should be using `/refresh`.

**Comment by rubesMN** [comment]
Thanks Spencer.  Perhaps the documentation needs to be clarified.  Seems `POST /env` only re-reads from local property sources.
