### ISSUE TITLE
Error with : You need to configure a uri for the git repository 

### ISSUE THREAD

**Issue by kaka89** [spring-cloud/spring-cloud-config#1457]
I got :
```
Caused by: java.lang.IllegalStateException: You need to configure a uri for the git repository
```
when I use "spring.cloud.config.server.native"

and it alway checkout to `master` branch when I use git repository.

**Comment by spencergibb** [comment]
Please provide what version you are using and your configuration.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
