### ISSUE TITLE
Add a way to access raw text / binary resources from config-server to config-client

### ISSUE THREAD

**Issue by SpiReCZ** [spring-cloud/spring-cloud-config#1459]
As for now the dependency: 

~~~~~xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-config</artifactId>
</dependency>
~~~~~

provides a simple way to access Config server properties.

But it is missing a feature to natively download RAW text / binary based Resources.

This was already implemented in project: https://github.com/pivotal-cf/spring-cloud-services-connector/blob/master/spring-cloud-services-spring-connector/src/main/java/io/pivotal/spring/cloud/service/config/OAuth2ConfigResourceClient.java

I think the feature should be available in this project with some autoconfiguration and also with Impl without OAuth2 requirement.

I proposed the `pivotal-cf` project to `giveaway` the feature to this project (https://github.com/pivotal-cf/spring-cloud-services-connector/issues/129).

As i stated in the `pivotal-cf` issue:

> I have managed to isolate the the fuctionality and created BasicConfigResourceClient which is OAuth2ConfigResourceClient without Oauth feature.

Why don't i just use the `pivotal-cf` library or my own? 
* I need `basic` implementation without OAuth2 and it is a much more cleaner to not add things you don't really need to the classpath. Also the implementation is package-private.
* Developers would get unified solution if it was implemented in here.

**Comment by spencergibb** [comment]
Please close one of the issues, no need to cross-post. We can AT mention proper folks here.

**Comment by SpiReCZ** [comment]
> Please close one of the issues, no need to cross-post. We can AT mention proper folks here.

Sure, no problem. Done.

**Comment by spencergibb** [comment]
Duplicates #789
