### ISSUE TITLE
Enable config server to reach repository via proxy server

### ISSUE THREAD

**Issue by mstine** [spring-cloud/spring-cloud-config#146]
Ran into this while teaching a Spring Cloud class on-site with a customer that required a proxy to access the web. JGit does not support the "standard" mechanisms for this. 

Reference http://stackoverflow.com/questions/16921374/jgit-proxy-configuration-in-code/17071687#17071687 for an example of how this is done. I figure we can wrap this in some nice configuration that would allow snippets in bootstrap.yml like the following:

```
spring.cloud.config.server.git.http.proxy.host=blah
spring.cloud.config.server.git.http.proxy.port=1234
spring.cloud.config.server.git.https.proxy.host=blah
spring.cloud.config.server.git.https.proxy.port=5678
```

**Comment by dsyer** [comment]
That SO link just shows someone making a special case for github. The normal JVM convention for System properties should work unless we need special cases like this (e.g. "-DproxyHost=myproxy.com" etc.). What was the use case exactly at the customer site?

**Comment by dsyer** [comment]
For the record I tried the config server with a proxy and it worked fine with `-Dhttps.proxyHost` and `-Dhttps.proxyPort` set (I was using squid so localhost:3128). It also works with `~/.git/config` with `http.proxy=localhost:3128`.

I have seen people on SO having issues with NTLM but I don't really know if we can do anything about that (maybe look at Spring Kerberos for the config server somewhere). This might be helpful (a proxy proxy with NTLM): http://stackoverflow.com/questions/7734518/how-to-set-up-git-to-get-through-a-proxy

**Comment by royclarkson** [comment]
I'm considering a PR for this. Cc: @spencergibb

**Comment by dsyer** [comment]
What does your PR do (go ahead and submit it)? Is it to do with the NTLM case?

**Comment by royclarkson** [comment]
No, it's not the NTLM case. We need to set proxy host to access a Git repository.

**Comment by dsyer** [comment]
Can you do that with a patch to Spring Cloud? You need to set a System property?

**Comment by royclarkson** [comment]
I don't know if we can do this with a patch. I just starting thinking about it and saw this open story. But yes, it appears we'll have to set System properties.

**Comment by dsyer** [comment]
For PCF would it be better to set the system property when you push the app? I suppose we could set a System property based on a config file (Spring environment entry), but it seems upside down.

**Comment by royclarkson** [comment]
I agree that having Spring Cloud set system properties feels awkward, if that's the only requirement for going through a proxy. My initial impression was there was something else needed, but I guess not. Your notes above said the system properties worked as desired in your tests.

**Comment by dsyer** [comment]
Yeah. I guess it's an important enough use case that we might be able to support it via `System.setProperty()`, but I'm not 100% convinced yet.

**Comment by royclarkson** [comment]
I'll explore a solution in the context of pushing a PCF app. If anything obvious reveals itself as a candidate for spring cloud, then I'll follow up here. Thanks for the feedback!

**Comment by stefanocke** [comment]
This seems to be resolved meanwhile. 
See http://cloud.spring.io/spring-cloud-static/Finchley.RELEASE/single/spring-cloud.html#_accessing_backends_through_a_proxy
