### ISSUE TITLE
Spring Cloud Config Server - Support Vault AppRole Auth method

### ISSUE THREAD

**Issue by kamalakarp** [spring-cloud/spring-cloud-config#1464]
Enhancement

Currently Config Server only supports token based Auth for Vault backend and often tokens expire regularly. Also, tokens doesn't work when Vault clusters are in performance replication (Enterprise Licensed version feature).  All enterprise Vault clusters uses performance replication for HA and tokens and leases doesn't replicate. Only Auth methods , secret backends gets replicated across clusters.

The enhancement request is to make Config Server support the most prominent auth method which is AppRole used by the Machines and applications.

**Comment by scottfrederick** [comment]
This requirement should be met with https://github.com/spring-cloud/spring-cloud-config/pull/1526
