### ISSUE TITLE
Question : in Serving Plain text: what is the meaning of "regular environment endpoint"

### ISSUE THREAD

**Issue by JakesIV** [spring-cloud/spring-cloud-config#1467]
Question

In Serving Plain text: (e.g. additonal config for logging)
What is the meaning of "regular environment endpoint"
I do not understand what url I need to use in serving logback-spring.xml file which is stored in a configuration server  the same way I store application.properties file. The samples use http://localhost:8087/main-application/default/master/log.xml
I do not uderstand where this information is coming from. What does main-application mean?
what does "default" mean ? and what does "master" mean?

As soon as I add "logging.config=http://localhost:8080/main-application/default/master/logback-spring.xml to my application it now longer resolves my Spring cloud application config.

thanks

**Comment by ryanjbaxter** [comment]
This is explained in the documentation https://cloud.spring.io/spring-cloud-static/Greenwich.SR3/single/spring-cloud.html#_quick_start

**Comment by JakesIV** [comment]
thanks for the info.
