### ISSUE TITLE
Inconsistent behavior of jdbc backend with default profile

### ISSUE THREAD

**Issue by svpace** [spring-cloud/spring-cloud-config#1473]
On a regular spring boot application the "default" profile is used only when no other profile is explicitly defined. Therefore with no profile selected the application will use the properties on the files application.properties and application-default.properties.

When using the jdbc backend with config server "default" is always added to the set of profiles and is used for the commons properties that would otherwise go on the application.properties.

This leaves no way to separate the commons properties, that should always be included, and properties, that should be used only when no other profile is specified.

**Comment by ryanjbaxter** [comment]
Have you tried other backends?  Is it only a problem with the JDBC backend?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
