### ISSUE TITLE
Property 'spring.cloud.config.server.git.privateKey' is not a valid private key

### ISSUE THREAD

**Issue by laur21** [spring-cloud/spring-cloud-config#1479]
Hello, 

I am unable to authenticate to the git repository due to the fact that I receive "Reason: Property 'spring.cloud.config.server.git.privateKey' is not a valid private key."

> server.port=8883
> spring.profiles.active=native
> spring.cloud.config.server.git.uri=ssh://git@blablabla.properties.git
> spring.cloud.config.server.git.clone-on-start=true
> spring.security.user.name=*******//user for client auth ( not git)
> logging.level.=DEBUG
> spring.security.user.password=******* //password for client auth ( not git)
> spring.cloud.config.server.git.strict-host-key-checking=false
> spring.cloud.config.server.git.preferred-authentications=publickey
> 

The ssh connections is fine when I clone the project manually (using ssh).

My private key has the following and it seems fine since I already searched this issue.
-----BEGIN RSA PRIVATE KEY-----
*******************************
-----END RSA PRIVATE KEY-----

I've tried to add values to the config file from ~/ssh/config, but still the same error message.

When using http and credentials it is fine, but not an option.

Any thoughts? Suggestions?

**Comment by spencergibb** [comment]
Can you provide the whole exception?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
