### ISSUE TITLE
spring-cloud-config-monitor 

### ISSUE THREAD

**Issue by prince129** [spring-cloud/spring-cloud-config#1487]
I am trying to update the config server by enabling the monitor endpoint in the spring-cloud-config server as I am using the bitbucket as my repo. It genrates the pull-request as webhook object in the post call. When I went to the class BitbucketPropertyPathNotificationExtractor

```
if (("repo:push".equals(headers.getFirst("X-Event-Key"))
|| "pullrequest:fulfilled".equals(headers.getFirst("X-Event-Key")))
&& StringUtils.hasText(headers.getFirst("X-Hook-UUID"))) {
// Bitbucket cloud
Object push = request.get("push");
if (push instanceof Map
&& ((Map) push).get("changes") instanceof Collection) {
// Bitbucket doesn't tell us the files that changed so this is a
// broadcast to all apps
return new PropertyPathNotification("application.yml");
}
}

```

It looks for push object in the post request genrated by the webhook. But bitbucket genrates the object as pull-request.

Can you help me to resolve the issue.

**Comment by ryanjbaxter** [comment]
Not sure what you mean by "pull-request".

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
