### ISSUE TITLE
Automatic decryption not working for 2.2.0.M3

### ISSUE THREAD

**Issue by seanlruff** [spring-cloud/spring-cloud-config#1490]
Hello All,

I'm using both the cloud config server and client and recently updated to the Hoxton (M3) release to find that the encrypted properties were no longer being automatically decrypted before being returned to the client.  The actual exception on the client side is at the bottom of this description.  However, what I noticed is that when accessing the data directly from a browser it was being decrypted correctly.  Upon investigation, I realized that the browser was hitting `EnvironmentController.defaultLabel(String, String)`, where as the config client was hitting `EnvironmentController.defaultLabelIncludeOrigin(String, String)`, with the difference being the "includeOrigin" flag.    More investigation revealed that the datatype stored in the `Environment` when includeOrigin = false is a String, but when includeOrigin = true, the datatype is a `PropertyValueDescriptor`.  Due to this when the `CipherEnvironmentEncryptor` attempts to decrypt the value it's looking for a String value which starts with {cipher} which will not be the case for `PropertyValueDescriptor` types and therefore the values will be delivered to the client encrypted.

===Client Error===
```
IllegalStateException: Cannot decrypt: key=datasource.providers[2].password
...
UnsupportedOperationException: No decryption for FailsafeTextEncryptor. Did you configure the keystore correctly?
```

**Comment by maslano** [comment]
I have no idea from which version did you upgrade, but if for a very old one it turns out the config property was changed to encrypt.key-store in comparison to the documentation

**Comment by seanlruff** [comment]
The previous version we were using was Greenwich.RELEASE.  However the issue isn't with this property since, as mentioned above, when accessing the config server via the browser the values are decrypted correctly, but when accessing the config server via a config client (which accepts - application/vnd.spring-cloud.config-server.v2+json) it does not decrypt the values.   I will try to get a example put together to reproduce but it may take me a few days to find the time.
