### ISSUE TITLE
Can I replace  spring.profiles.active="native" with "dev" when using the local file system?

### ISSUE THREAD

**Issue by andyzhaozhao** [spring-cloud/spring-cloud-config#1503]
Hello, there are 4 profiles (dev,test,stage,prod) in my Micro service projects. In dev profile ,all the config is configed as the local environment.But in config server the local enviroment is named "native",not "dev",How can I replace  spring.profiles.active="native" with "dev" when using the local file system?

**Comment by KOSSOKO** [comment]
@andyzhaozhao  did you find a solution ?

**Comment by andyzhaozhao** [comment]
> @andyzhaozhao did you find a solution ?

No

**Comment by hammadirshad** [comment]
@Configuration
	@ConditionalOnMissingBean(EnvironmentRepository.class)
	@Profile("dev") // profile name
	class NativeRepositoryConfiguration {
	@Bean
	public NativeEnvironmentRepository nativeEnvironmentRepository(NativeEnvironmentRepositoryFactory factory,
			NativeEnvironmentProperties environmentProperties) {
        	return factory.build(environmentProperties);
		}
	}

**Comment by TYsewyn** [comment]
Have you tried using `spring.profiles.include` to solve this issue?

**Comment by hammadirshad** [comment]
server:
      port: 8080
      ---
      spring:
        profiles: dev
          include:
            - native
      ---
      spring:
        profiles: test
          include:
            - git

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by andyzhaozhao** [comment]
I have used @hammadirshad  's  solution. Thanks every one very much.
```
@Configuration
@ConditionalOnMissingBean(EnvironmentRepository.class)
@Profile("dev") // profile name
class NativeRepositoryConfiguration {
@Bean
public NativeEnvironmentRepository nativeEnvironmentRepository(NativeEnvironmentRepositoryFactory factory,
		NativeEnvironmentProperties environmentProperties) {
    	return factory.build(environmentProperties);
	}
}
```
