### ISSUE TITLE
Spring cloud config server and client

### ISSUE THREAD

**Issue by deepsharma951** [spring-cloud/spring-cloud-config#1508]
Hi,
If we have same properties under different folder
like 
ms-one
|--- application.properties
|--- application-prod.properties
|--- application-dev.properties
ms-two
|--- application.properties
|--- application-prod.properties
|--- application-dev.properties

we have define search path in spring cloud config bootstrap file
spring.cloud.config.server.git.search-paths=ms-one,ms-two

Now we have to load profile in client application then how we can load the profile?
I have define in properties file like this
spring.application.name=application
spring.profiles.active=dev
but how to define which folder??
Thanks in advance

**Comment by spencergibb** [comment]
It will look in the folders according to the order in search paths

**Comment by deepsharma951** [comment]
spencergibb

> It will look in the folders according to the order in search paths

yes it will but how to use those properties into application i.e. how to use config server folder properties into multiple micro services

**Comment by spencergibb** [comment]
I still don't understand what you're asking. The properties from config server get added to the spring environment.

**Comment by scottfrederick** [comment]
@deepsharma951 You should use the application name to distinguish between the separate services. 

```
ms-one
|--- ms-one-application.properties
|--- ms-one-application-prod.properties
|--- ms-one-application-dev.properties
ms-two
|--- ms-two-application.properties
|--- ms-two-application-prod.properties
|--- ms-two-application-dev.properties
```

Then set `spring.application.name` to either `ms-one-application` or `ms-two-application` in each application's `bootstrap.yml`.
