### ISSUE TITLE
@RefreshScope on bean annotated  with @Bean and bean final function get null value

### ISSUE THREAD

**Issue by pizhaojun** [spring-cloud/spring-cloud-config#1509]
hi, when i set annotaion _@RefreshScope_  on bean annotated with @Bean，then i used this bean and get final funciton return value, it's get _null_,  why? 

**Sample**
```
@Bean
@RefreshScope
public StudentQueryService studentQueryService(){
      return new StudentQueryService("studentName");
}

public StudentQueryService {
 private String name;
  public  StudentQueryService (String name){
     this.name  = name;
   }
  public final getName(){
   return name;
 }
}

@RestController
public StudentQueryController {
   @Resouce 
   private StudentQueryService  service;
   
  @GetMapping("/getStuName")
   public String getStuName(){
    return service.getName();
  }
}
```
 when request _/getStuName_ ,  it's return null . But when i remove _@RefreshScope_ , it's normal.

**Comment by OLPMO** [comment]
Could you provide a complete, minimal, verifiable sample that reproduces the problem?@pizhaojun

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
