### ISSUE TITLE
EnvironmentController mapping of properties to Yaml is bad

### ISSUE THREAD

**Issue by iskradelta** [spring-cloud/spring-cloud-config#1510]
All versions available of spring cloud config, from 2.0.x onwards (Ive tested with, possibly earlier) contain the bug.

A given yaml file, is parsed OK and processed as wished when not using spring-cloud, when just starting the application directly with java jar spring config location and so on. 

Given a yaml file such as below, will throw a ClassCast exception, this is disrepancy between what spring-cloud-config allows/considers-a-valid configuration, and what spring-boot considers a valid configuration file.

The full log is like this,

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
at org.springframework.cloud.config.server.environment.EnvironmentController$PropertyNavigator.setMapValue(EnvironmentController.java:374) ~[spring-cloud-config-server-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
```

**Sample**

Put in your configuration yaml file this

```
logging.level:
    org.springframework: WARN
    org.springframework.cloud: ERROR
```

This leads to correctly, being converted to properties as expected by spring-boots yaml to properties loader. 

However, the bug is triggered when converting the "from yaml to properties" back to a Map, which happens when requesting the cloud-config application-conf as yaml, in the convertToMap method, the conversion from properties causes the above ClassCastException, 

Perhaps, the solution is to use a real Properties-To-Yaml library, or even skip that step altogether when yaml is requested and just validate it and send it back, hm?

**Comment by spencergibb** [comment]
Related to #1113
