### ISSUE TITLE
Please let TestPropertySource override properties coming from cloud config

### ISSUE THREAD

**Issue by tobias-neubert** [spring-cloud/spring-cloud-config#1513]
I have been used to work with spring boot and the way it resolves property sources. Especially the high priority of @TestPropertySource is very handy. After I have switched to spring cloud config I now have the problem that some of my integration tests do not work anymore, because they rely on exactly that behavior. I bet most of the developers familiar with spring boot expect that behavior. 
Is it possible to implement that? @TestPropertySources should have higher priority than cloud config properties.

**Comment by spencergibb** [comment]
duplicates #505
