### ISSUE TITLE
Reopened: The wrong http settings may be used if there are two git repo configs for the same url

### ISSUE THREAD

**Issue by marnee01** [spring-cloud/spring-cloud-config#1514]
Please see the issue documented in https://github.com/spring-cloud/spring-cloud-config/issues/1482. It is marked as fixed, but I don't see how it could be. I don't see a way to re-open it.

Ryan Baxter had said:

> When I apply the fix from #1480 that does not seem to address this issue, there is still only 2 entries in the map. I don't see how that would address the uniqueness of the key.

I replied to that, but I actually made a mistake and thought I was replying on the issue documented in #1480. (So, my response starting with "If there are two connections that would..." from Nov 15th is not applicable.) Ryan was in fact correct in saying that the fix from 1480 won't fix this. I am very sorry for that confusion.

In fact, it appears to me that there is an underlying design flaw in this area (which is why I kept insisting the workaround for 1480 was nothing but a workaround). The code in question does not take into account that you can have the same URL but with different properties provided in the `spring.cloud.config.server.git` properties. The code knows nothing about the `spring.cloud.config.server.git` configuration.

**Comment by spencergibb** [comment]
please comment on #1482, we can reopen if needed
