### ISSUE TITLE
Not able to read from vault via spring cloud using profiles

### ISSUE THREAD

**Issue by joshisimt** [spring-cloud/spring-cloud-config#1516]
Hi Team,

I have one microservice which get the config from vault via spring cloud.
It works fine without any profile. I need to fetch the details from vault on based of profile.
So I created folder structure in vault like `/secret/application/dev` and also `/secret/microservicename/dev` inside this I have all configurations.

So problem is I am unable to find it on profile basis from vault.
Can you please help?

Basic configuration for spring cloud server is as below-

`spring.profiles.active=vault,git
spring.cloud.config.server.vault.host=localhost
spring.cloud.config.server.vault.port=8900
spring.cloud.config.server.vault.order=1
spring.cloud.config.server.git.order=2
spring.cloud.config.server.git.uri=https://giturl
spring.cloud.config.server.git.username=username
spring.cloud.config.server.git.password=password
spring.cloud.config.server.git.searchPaths=configuration,iam
server.port=6565`

I have started the microservice in dev profile.

Thanks

**Comment by joshisimt** [comment]
Welcome @mp911de 
Yes please.

**Comment by scottfrederick** [comment]
The profile should be part of the secret name as [shown in the docs](https://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.2.0.RELEASE/reference/html/#_multiple_properties_sources), not in a folder structure. Instead of: 

```
/secret/application/dev
/secret/microservicename/dev
```

use:

```
/secret/application,dev
/secret/microservicename,dev
```

**Comment by joshisimt** [comment]
Hi @scottfrederick 

Thanks for your help.
It worked.
