### ISSUE TITLE
Memory Leak related to ConfigurableApplicationContext#registerShutdownHook ?

### ISSUE THREAD

**Issue by piotrzk** [spring-cloud/spring-cloud-config#152]
I've noticed that after each config refresh new `ConfigurableApplicationContext` is created and is registered in `Runtime.getRuntime().addShutdownHook()` - AFAIK shutdown hooks will be called only while shutting down JVM.
If config reload is scheduled every couple minutes it seems causing application running out of memory.
While monitoring my JVM I can see many `org.springframework.context.annotation.AnnotationConfigApplicationContext` instances which are not removed by GC.
Anybody has an issue with it?
Any idea how can I solve this problem?

**Comment by dsyer** [comment]
If this is an issue it should be in Commons: https://github.com/spring-cloud/spring-cloud-commons

**Comment by dsyer** [comment]
If this is a problem I believe it must be in Commons: https://github.com/spring-cloud/spring-cloud-commons
