### ISSUE TITLE
Placeholders don't resolve when placed in different files

### ISSUE THREAD

**Issue by punit-kulal** [spring-cloud/spring-cloud-config#1528]
**Placeholders on config server end**
I have an application.yml which contains key a.b.c
<pre>a:  
  b: 
    c: value </pre>

in my app.yml, I try to use this value by using a placeholder
x: ${a.b.c}

The configuration for app gives back the string literal
x: "${a.b.c}"

**Comment by OLPMO** [comment]
Could you provide a complete, minimal, verifiable sample that reproduces the problem?

**Comment by punit-kulal** [comment]
I don't know whether there's a problem or is it not implemented.
My question is whether a config value from 1 file is available in another config file. Like how we can use placeholders provided from command line in the config file.

**Comment by spencergibb** [comment]
files don't matter once they are in the the spring environment, so it should work.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
