### ISSUE TITLE
Bit Bucket Web hook refreshed all config server consumers

### ISSUE THREAD

**Issue by srinivasmeenavalli** [spring-cloud/spring-cloud-config#1532]
I have enabled config server /monitor in bitbucket web hook, observed that config server refreshed all services on property file commits. "destinationService": "*:**", 
Is it a bug or expected behavior because bit bucket web hook payload doesn't  provide what are exact files changes? 

Web hook url :  **/configserver/monitor**
**kafka message for Bit Bucket web hook :** 
"type": "RefreshRemoteApplicationEvent",
    "timestamp": 1577949004944,
    "originService": "configserver:80:ca8e305dc3afed64ed5aaa4ab2e722d6",
    "destinationService": "*:**",

Kafka Event for GIT changes : 
{
timestamp: 1471498671136,
info: {
signal: "spring.cloud.bus.sent",
type: "RefreshRemoteApplicationEvent",
id: "9009a8ba-ed29-4d0c-adea-637a7ef6f7cc",
origin: "config-server:native:8100",
destination: "service-a:**"
}

BitBucket Webhook Generated Payload  - Push 
  X-Event-Key: repo:refs_changed

Git Webhook Generated Payload- Push 
    X-GitHub-Event: push

**Comment by spencergibb** [comment]
There's a note that says
```
// Bitbucket doesn't tell us the files that changed so this is a
				// broadcast to all apps
```

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by srinivasmeenavalli** [comment]
It's limitation in Bit bucket . Thank for update. Can you close this issue?
