### ISSUE TITLE
Spring cloud decryption issue

### ISSUE THREAD

**Issue by jacksonjoseph** [spring-cloud/spring-cloud-config#1549]
I set spring.cloud.config.server.encrypt.enabled=true in bootstrap.properties. But the decryption working. It can able to decrypt the encrypted value.
I'm using Springboot 2.2.1.RELEASE and Spring cloud Hoxton.RELEASE.

**Comment by spencergibb** [comment]
Duplicates #1548. Please don't open multiple issues
