### ISSUE TITLE
Send 404 if application not found

### ISSUE THREAD

**Issue by hmichopoulos** [spring-cloud/spring-cloud-config#155]
Hi,
I would like to configure Config Client to accept only non empty configuration sources.

Currently, if the configuration of my `FooApplication` has not reached the Config Server yet, the Config Client will receive empty configuration sources and will go on. 
I suggest it to be configurable. If `acceptEmpty` is false, it would fail and probably retry.

Thanks

**Comment by hmichopoulos** [comment]
Actually, Config Server should send 404 if the application is not found

**Comment by dsyer** [comment]
This is marked as fixed in #156

**Comment by Sangdol** [comment]
Is this actually fixed? #156 has been closed without being merged and `acceptEmpty` option doesn't work. I cannot find the `acceptEmpty` in the code as well.

**Comment by spencergibb** [comment]
No, it was closed since the PR didn't actually issue a 404

**Comment by spencergibb** [comment]
@hmichopoulos never submitted another PR
