### ISSUE TITLE
Config server failed to locate PropertySource

### ISSUE THREAD

**Issue by PraveenkumarJ** [spring-cloud/spring-cloud-config#1550]
Config server failing to locate PropertySource.

ConfigServicePropertySourceLocator : Could not locate PropertySource {status:500, error:Internal Server Error, Message:Failed to load property source from location}

Config Server is up and running and showing the status as "Config Server is online" when checking the manage Spring Cloud Services.

and config server is bounded to the application and I can see in the logs Fetching config from server.

It was working and locating the property sources correctly, but recently getting this issue, any idea why we are getting this issue?

Spring Cloud version: Finchley:RELEASE
Spring Boot 2.0.3.RELEASE

**Comment by PraveenkumarJ** [comment]
Please ignore, simple issue in the yml file, caused the above issue. Resolved now.

**Comment by nagomirachel** [comment]
Hi Praveen,

I am facing the same issue. Can you let me know what is that issue in yaml.

**Comment by ambika2204** [comment]
I am facing the same issue, can you please what was the issue in yaml.
