### ISSUE TITLE
How to point Config-server to a deep nested subfolder of a git repository without reading the whole tree?

### ISSUE THREAD

**Issue by raulgv1980** [spring-cloud/spring-cloud-config#1554]
Hi,

I have a working Config Server pointed to a small git repository and everything works fine. I am using searchPaths to look for files in subfolders working fine. My problem is that I need to use an existing git repository with huge content where the files I need are placed in a subfolder. If I try to point my config-server to this new git, it tries to read the whole tree folder (including brothers and cousins from the actual folder I need) and produces a timeout.
Is there any way to tell Config Server to work only with a determined subfolder and ignore the rest of the git tree?

Thanks in advance!

**Comment by spencergibb** [comment]
That's not really how git works is it? Are these huge files configuration?

**Comment by raulgv1980** [comment]
No, there is all kind of stuff in the repository, which was created for a legacy application that does not use config-server. We would like to avoid changing the structure of the repository since it is remotely synchronizedwith a CMS. That is also the reason why we did not simply copy the property files to another repository.

**Comment by spencergibb** [comment]
That's really a limitation of git. Not sure what else to say.

**Comment by raulgv1980** [comment]
I guess we will have to go with a uri:file configuration and some how clone/mount the content remote subfolder, just checking if someone had previously faced this problem.
Thanks anyway!
