### ISSUE TITLE
Enhancement: Monitor Endpoint Refresh Configuration

### ISSUE THREAD

**Issue by joshfleck** [spring-cloud/spring-cloud-config#1568]
Scenario:
Remote repository (Bitbucket) is configured with /monitor webhook on commit. SCC server listens to events and fires off AMQP messages. Application receives message and tries to reload properties.

Problem:
When the above occurs multiple times within the configured refresh rate, the AMQP messages are still sent off to the application which then try to reload the properties. Since refresh-rate is configured, SCC server does not refresh the git backend, causing the application to receive old property values.

Not sure if there is an existing solution to this that doesn't involve removing refresh-rate from the server configuration. It would be nice if the AMQP messages were not sent until the repository configuration is updated, or add the ability for the monitor endpoint to trigger a refresh of the configuration.

**Comment by spencergibb** [comment]
I'm sure how that would work. Can you clarify what "add the ability for the monitor endpoint to trigger a refresh of the configuration." means? To me, that is what the monitor endpoint does.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
