### ISSUE TITLE
Support integration with AWS Secrets Manager

### ISSUE THREAD

**Issue by Walliee** [spring-cloud/spring-cloud-config#1574]
[AWS Secrets Manager](https://docs.aws.amazon.com/secretsmanager/latest/apireference/Welcome.html) is an AWS service that enables you to store, manage, and retrieve, secrets.

Similar to #850, which talks about support for AWS Parameter Store; supporting AWS Secrets Manager behind the Config Server abstraction would be a useful feature.

**Comment by Walliee** [comment]
Happy to take a stab at it if the team agrees.

**Comment by spencergibb** [comment]
Not sure we'd want one without the other

**Comment by tejas-pandilwar** [comment]
@spencergibb I am going to start working on this [feature](https://github.com/tejas-pandilwar/spring-cloud-config).
