### ISSUE TITLE
Can't construct a java object for org.redisson.codec.JsonJacksonCodec; exception=Invalid tag: org.redisson.codec.JsonJacksonCodec

### ISSUE THREAD

**Issue by noseparte** [spring-cloud/spring-cloud-config#1579]
**Describe the bug**
Hey! There was an error getting redisson's yaml configuration file from a different environment through the springcloud config component @claymccoy @ogrodnek @rmorgan 

**Sample**

![image](https://user-images.githubusercontent.com/30165939/76737945-acd29200-67a4-11ea-96b0-a0633bd71a57.png)

**Comment by spencergibb** [comment]
Screenshots aren't very helpful. I can't see how this is a problem with config server without instructions on how to recreate the problem

**Comment by noseparte** [comment]
ok. Here's the whole problem. @spencergibb 
I upgraded my company's project from boot to cloud, so I added the springcloud eureka, config component
Before the new, The program is normal and redisson.yaml can be loaded into.
![image](https://user-images.githubusercontent.com/30165939/76826315-20cd7280-6857-11ea-9d42-f60716a4014d.png)
------------------------------------
After upgrading to cloud
![image](https://user-images.githubusercontent.com/30165939/76826523-9fc2ab00-6857-11ea-9dcb-27ec40ef5ef0.png)
Now get redisson.yaml from the config repository through the bootstrap.yml file
![image](https://user-images.githubusercontent.com/30165939/76826583-d7c9ee00-6857-11ea-897f-d335e82b9790.png)
![image](https://user-images.githubusercontent.com/30165939/76826626-ef08db80-6857-11ea-9aac-56f669d720fb.png)
![image](https://user-images.githubusercontent.com/30165939/76827634-41e39280-685a-11ea-8da9-51e7a37277af.png)

-------------------------------------------------
Here are the results
![image](https://user-images.githubusercontent.com/30165939/76826711-25def180-6858-11ea-88d4-baef65cf07f5.png)
![image](https://user-images.githubusercontent.com/30165939/76826707-237c9780-6858-11ea-9653-510165599a60.png)

**Comment by spencergibb** [comment]
Again screenshots are not very helpful. Please provide a sample project that recreates the problem. It should be attached as a zip file or as a GitHub repo

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
