### ISSUE TITLE
IDE run application is different from mvn clean package the application and then java -jar xxx.jar

### ISSUE THREAD

**Issue by huskyui** [spring-cloud/spring-cloud-config#1587]
**Describe the bug**
i add `spring-boot-starter-actuator` in this application,and exposure `bus-refresh`.
when RUN with IDEA,the terminal log 
`2020-03-25 16:06:00.675  INFO 18308 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'`
```
curl -X GET http://localhost:13000/actuator
{"_links":{"self":{"href":"http://localhost:13000/actuator","templated":false},"bus-refresh":{"href":"http://localhost:13000/actuator/bus-refresh","templated":false},"bus-ref
resh-destination":{"href":"http://localhost:13000/actuator/bus-refresh/{destination}","templated":true}}}

```

when `mvn clean package`and java -jar xx.jar,the teminal log
`2020-03-25 15:41:45.576  INFO 9380 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 0 endpoint(s) beneath base path '/actuator'`
```
curl -X GET http://localhost:13000/actuator
{"_links":{"self":{"href":"http://localhost:13000/actuator","templated":false}}}
```

**Comment by spencergibb** [comment]
I'm not sure how this is a big or issue here. It's likely a problem with your environment

**Comment by huskyui** [comment]
> I'm not sure how this is a big or issue here. It's likely a problem with your environment

i got it.

**Comment by thjaeckle** [comment]
@huskyui do you remember what the problem was and how you solved it? I have the same issue and am quite puzzled ..
