### ISSUE TITLE
Feature Switch - Inclusion of ConfigServer health check

### ISSUE THREAD

**Issue by fritzrichter** [spring-cloud/spring-cloud-config#159]
Based on this discussion https://stackoverflow.com/questions/30232850/spring-cloud-config-client-slows-down-metric-health it makes sense to add a feature switch (boolean property) which allows the auto-registration of ConfigServerHealthIndicator.

Currently the entire roundtrip to the ConfigServer --> GIT --> and back, slows dramatically down our health checks. I monitor the config server separately, don't want every application to check the connection to the config server all the time.

**Comment by Sanket0510** [comment]
if we are using making dependency of spring-cloud-config-client of 1.0.1.RELEASE, we will not be able to get health.config.enabled property. The correct property is health.config.enabled and we can use it with version 1.0.4 RELEASE
