### ISSUE TITLE
Spring Cloud Config Server for Spring Batch Application

### ISSUE THREAD

**Issue by Gayathri-91** [spring-cloud/spring-cloud-config#1600]
Question:

How to use Spring Cloud config server for spring batch applications. I would like my spring batch application to behave as a client and consume the properties defined in server config. I cant find any examples for this. All the examples have rest controller based approach. I dont have any controller here and I tried adding bootstrap.yml and tried to consume the values defined in server config. But it didnt work out.

**Comment by ryanjbaxter** [comment]
> But it didnt work out.

Is not very helpful.  What didn't work?  Can you provide a sample?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
