### ISSUE TITLE
The same as Issue 1530:  https://github.com/spring-cloud/spring-cloud-config/issues/1530

### ISSUE THREAD

**Issue by andyzhaozhao** [spring-cloud/spring-cloud-config#1601]
**Spring Boot Admin or Spring Cloud Gateway could not fetch the dynamic Eureka clients when using Spring Cloud Config**
https://github.com/spring-cloud/spring-cloud-config/issues/1530

I have writen a sample : https://github.com/andyzhaozhao/spring-cloud-config-issues-1530-sample  .

Every thing described in https://github.com/andyzhaozhao/spring-cloud-config-issues-1530-sample/blob/master/Readme.md

**Comment by spencergibb** [comment]
No need to open a new issue
