### ISSUE TITLE
how can i read the properties which has the same name in different files at the same time？

### ISSUE THREAD

**Issue by solachan** [spring-cloud/spring-cloud-config#1606]
how can i read the properties which has the same names in different files at the same time？
for example,i have two files to read , a.properties and b.properties.they both have a key named "switch" and these two keys has different values，how can i get these two "time"？

**Comment by spencergibb** [comment]
why would you want to do that?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
