### ISSUE TITLE
Cloneonstart flag doesn't checkout the branch mentioned in label

### ISSUE THREAD

**Issue by gauravhanda** [spring-cloud/spring-cloud-config#1609]
In the cloud config server application.yml, if cloneOnStart is set to true, then default label is ignored and most active branch is checked out.

Spring cloud dependency version: Hoxton.SR4
Spring clould config server version: 2.2.2RELEASE

Sample application.yml

 uri: ${CENTRALIZED_GIT_URI}
 username: ${SERVICE_USERNAME}
 password: ${SERVICE_PASSWORD}
 **cloneOnStart: true
    defaultLabel: qa // This is not read and most active branch is checked out **

Expected Behavior:
The cloneOnStart should consider the defaultLabel so that the expected label is not checked out during first request.

**Comment by gauravhanda** [comment]
This seems to be easy fix. In JGitEnvironmentRepository.java :: initClonedRepository method, we need to checkout to defaultLabel
// checkout the default label
			if (null != getDefaultLabel()) {
				checkout(git, getDefaultLabel());
			}
I can submit a pull request, if someone can share the process. Sorry for trivial question, new to Spring :)

**Comment by spencergibb** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by gauravhanda** [comment]
Thanks @spencergibb , created PR for the same.

**Comment by spencergibb** [comment]
Closing in favor of #1610
