### ISSUE TITLE
user.dir vs user.home

### ISSUE THREAD

**Issue by Drezir** [spring-cloud/spring-cloud-config#1616]
Hello, 

I am experiencing strange behaviour using system properties in configuration file.

While this example with `user.home` works
`spring.cloud.config.server.git.uri=file://${user.home}/configs`

the other does not work:
`spring.cloud.config.server.git.uri=file://${user.dir}/configs`

I am running on Linux Mint 19.3.

**Comment by spencergibb** [comment]
I don't think this has anything to do with config server. Those values come from either system properties or environment variables. So one of them isn't set with a combination of your os and jdk.
