### ISSUE TITLE
Empty array maps to empty string

### ISSUE THREAD

**Issue by snowe2010** [spring-cloud/spring-cloud-config#1620]
**Describe the bug**
versions:

spring-boot-starter-parent: 2.2.4.RELEASE
spring-cloud-version: Greenwich.SR3

an empty array maps to an empty string rather than an empty array:

**Sample**
fully reproducible example [here](https://github.com/snowe2010/spring-cloud/tree/e633f6cb3d128c0af2f6d8e66550a397cc04ac76/config-server) (you will need to provide a config, example below)

The above sample code is about as simple as you can get. The config 

```yaml
test: []
```

maps to 
```json
{
    "name": "roomservices",
    "profiles": [
        "default"
    ],
    "label": null,
    "version": "b74cfaa653c789de331a25f8b9a2113303b1fecd",
    "state": null,
    "propertySources": [
        {
            "name": "${homehere}/IdeaProjects/config/roomservices.yml",
            "source": {
                "test": ""
            }
        }
    ]
}
```

It should instead map to `"test": []`

edit: my example code includes an objectmapper bean, but that is not required to reproduce the bug.

**Comment by spencergibb** [comment]
Does this still happen in Hoxton.SR6?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by snowe2010** [comment]
I'm still seeing this with Hoxton.SR6. Test branch: https://github.com/snowe2010/spring-cloud/tree/hoxton.sr6

**Comment by spencergibb** [comment]
I'm unable to replicate on Hoxton.SR10 or 2020.0.2, so looks like this got fixed in the meantime.
