### ISSUE TITLE
Cloud Gateway routes and normal properties

### ISSUE THREAD

**Issue by gituserjava** [spring-cloud/spring-cloud-config#1624]
We would like to have cloud Gateway routes in one yaml and other properties like DB Urls, file locations etc in another yaml file. Both the above files are environment specific.

How can we selectively refresh one vs other yaml file using cloud config and actuator endpoint?

**Comment by spencergibb** [comment]
The only way to approach having different settings in different files is with profiles.

> How can we selectively refresh one vs other yaml file using cloud config and actuator endpoint?

You can not.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
