### ISSUE TITLE
Secure cloud config

### ISSUE THREAD

**Issue by gituserjava** [spring-cloud/spring-cloud-config#1625]
Can we secure cloud config server deployed on AWS ECS with ECS task role so that only spring cloud gateway (deployed on ECS) can access it? If not what are the other mechanisms to protect cloud config server without use of username/password?

**Comment by spencergibb** [comment]
I have no experience with aws eks

**Comment by gituserjava** [comment]
@spencergibb , are there any mechanisms to protect cloud config server without use of username/password?

**Comment by spencergibb** [comment]
Anything you can do with spring security

**Comment by gituserjava** [comment]
@spencergibb , we are using Spring Cloud Config with Spring Boot 2.0 and I configured spring security as below. This is not validating the username/password. If I don't password it does say 401, but with incorrect password also it is working.

Do we need to do anything specific for cloud config?

```
spring:
   security:
   user: 
       name: test
       password abc
       roles: USER
```
```
@Override
        protected void configure(HttpSecurity http) throws Exception {
                http.csrf().disable().authorizeRequests().antMatchers("/**").hasRole("USER").and().httpBasic();
        }
```

**Comment by spencergibb** [comment]
No that is all spring security
