### ISSUE TITLE
Add Webhook and option to disable polling support, auto pull after only CI/CD builds

### ISSUE THREAD

**Issue by buraksarac** [spring-cloud/spring-cloud-config#1626]
**Is your feature request related to a problem? Please describe.**
Prevent scheduled polls between server<->property source as well as server<->client, only reach property source if needed

**Describe the solution you'd like**
When CI/CD build is complete, it calls server rest api to trigger an local update
After trigger Server pulls new resources
If there is update (by file pattern?) Server updates its state to changed
Server notify related client and triggers client context refresh
Otherwise (no versioning update) server in quite/silent mode
Client also doesnt need to check server, since its triggered by server
This option could be stacked as well (client has server dependency)

**Describe alternatives you've considered**
I couldnt find an existing rest endpoint to force pulling except using scheduling on server

Thank you
Burak

**Comment by buraksarac** [comment]
Hi if you are interested and think this could be useful, I will be happy to work on it, but since I didnt have any pull req. before for any spring project framework, I might be a bit of head ache and would need some additional time than usual to code review/fixes/updates.

Thank you
Burak

**Comment by spencergibb** [comment]
I'm a bit confused about polling. There isn't a polling feature. Can you explain more in depth what is happening?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
