### ISSUE TITLE
No documentation for ResourceController endpoints?

### ISSUE THREAD

**Issue by marnee01** [spring-cloud/spring-cloud-config#1627]
This isn't actually a bug, but is a question and perhaps may result in a request for updated documentation. (I wasn't sure how else or where else to pose this question.)

I noticed in spring cloud config server logs that there are endpoints mapped in the org.springframework.cloud.config.server.resource.ResourceController class. From the javadoc on the class, I have no idea how someone might make use of these endpoints (e.g. `/{name}/{profile}/{label}/**`). I'd like to understand all the features available in the service. 

I tried searching for online documentation related to this, but did not find any. Could you point me to the documentation related to the functionality in this class?

**Comment by spencergibb** [comment]
https://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.2.2.RELEASE/reference/html/#_quick_start

**Comment by marnee01** [comment]
Is it this section? 

https://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.2.2.RELEASE/reference/html/#_serving_plain_text

**Comment by spencergibb** [comment]
Yes

**Comment by marnee01** [comment]
Thanks!
