### ISSUE TITLE
Spring Cloud Config Server Native Profile In Docker Container

### ISSUE THREAD

**Issue by sau3078** [spring-cloud/spring-cloud-config#1629]
Question
How to give spring cloud config server url using native profile  to Eureka client which is also a spring cloud config client.

Eureka Client need to fetch the config server url as all the configurations are stored in config server folder say config-repo. 
Also config server is not looked up by eureka server as config server itself acting like server.
l 

Bug report

Spring Cloud Version : Finchley.SR2
Spring BOOT Version : 2.0.4.RELEASE

**Comment by spencergibb** [comment]
Can you please provide more detail? I'm afraid I don't understand. Are you trying to lookup config server from eureka? If so that is well documented https://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.2.0.RELEASE/reference/html/#discovery-first-bootstrap

**Comment by spencergibb** [comment]
also, Finchley and boot 2.0.x are no longer supported, please upgrade to Hoxton.SR6 and the latest boot release.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
