### ISSUE TITLE
Config server returns "Cannot clone or checkout repository" only when deployed

### ISSUE THREAD

**Issue by tudorgrig** [spring-cloud/spring-cloud-config#1630]
I have a basic Hoxton.RELEASE Config server that when deployed to GKE it fails to connect to Eureka and any request returns:

````
Cannot clone or checkout repository
````

You can view any details needed here: https://github.com/tudorgrig/comand/tree/master/comand-API/config-server

**Comment by spencergibb** [comment]
Can you update to the latest Hoxton.SR4 and boot 2.2.7.RELEASE? Does it work outside of GKE?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
