### ISSUE TITLE
Spring Cloud Config | Git Based | Not working on windows machine

### ISSUE THREAD

**Issue by ksambhav** [spring-cloud/spring-cloud-config#164]
Hitting the URL on my browser http://localhost:{configServerPort}/{appName}/default gives expected result on a linux machine buts fails on windows machine.

Inside`NativeEnvironmentRepository#clean()` method, around line 153, `normal.startsWith(pattern)` condition fails because of '/' (forward slash) and '\' (backward slash) mismatch on a Windows machine. Same thing seems to be working fine on a linux machine.

Spring Cloud version 1.0.1.RELEASE

SOF:- http://stackoverflow.com/questions/30524202/spring-cloud-config-git-based-not-working-on-windows-machine

**Comment by dsyer** [comment]
Looks like it was fixed here: https://github.com/spring-cloud/spring-cloud-config/commit/641d5b40e861e5750393a6f57c26d8124c214083

**Comment by james-appfoundry** [comment]
I'm still hitting this problem even on 1.0.3.BUILD-SNAPSHOT. The string compare fails because the 'normal' var has backslashes. I'm running on Windows (through cygwin to be simplify the ssh access to our git repo) and experience the same issue. It seems as though the same change to normalise the string may need to be applied to NativeEnvironmentRepository at line 136?

From:
					normal = new File(normal.substring("file:".length()))
							.getAbsolutePath();
To:
					normal = StringUtils.cleanPath(new File(normal.substring("file:".length()))
							.getAbsolutePath());

**Comment by spencergibb** [comment]
@james-appfoundry I'm looking at `NativeEnvironmentRepository` line 136 from 641d5b40e861e5750393a6f57c26d8124c214083 and it has the `StringUtils.cleanPath` call.  Can you make sure you are using the latest code?  If you still have issues, please open a new issue.

**Comment by james-appfoundry** [comment]
Apologies, yes, in my rush to leave the office last night I'd missed the fact that 1.0.3.BUILD-SNAPSHOT of the cloud starter was using 1.0.2.BUILD-SNAPSHOT of the config server. Cleaned my cache and pulled down the latest 1.0.2.BUILD-SNAPSHOT build and I've picked up the change. Thanks.
