### ISSUE TITLE
Is it safe to store passwords with String?

### ISSUE THREAD

**Issue by jliuold** [spring-cloud/spring-cloud-config#1640]
https://github.com/spring-cloud/spring-cloud-config/blob/72ec91814ee1b1dbd6d914899205144122cedbca/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/encryption/EncryptionController.java#L133

Is it safe to store passwords with String? There seems to be no way to proactively clean up strings of passwords stored in memory.

**Comment by spencergibb** [comment]
`TextEncryptor.decrypt()` returns a string. Not sure there's anything I can do there.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
