### ISSUE TITLE
may I load a privatekey.pem file from spring cloud config?

### ISSUE THREAD

**Issue by EkeSu** [spring-cloud/spring-cloud-config#1641]
may I load a privatekey.pem file from spring cloud config?

**Comment by spencergibb** [comment]
yes. Can you provide more context please.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
