### ISSUE TITLE
Remove ResourceController mappigs with param useDefaultLabel

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-config#1643]
ResourceController has multiple `@RequestMapping`s that would conflict, currently to avoid passing the label we use the `useDefaultLabel` request parameter to select. Starting with spring 5.3 this is no longer happening.

Given
```
	@RequestMapping("/{name}/{profile}/{label}/**")
// and 
	@RequestMapping(value = "/{name}/{profile}/**", params = "useDefaultLabel")
```
Calling `/foo/default/file.txt?useDefaultLabel` used to route to the later, now it routes to the former and produces an error because the file is treated as a label.

**Comment by spencergibb** [comment]
After writing some [samples](https://github.com/bclozel/mapping), it appears that using the `useDefaultLabel` request parameter to select a different `@RequestMapping` hasn't worked for some time. It appears that no one is using this as no one is reporting problems. This method will get removed instead.

**Comment by dinhani** [comment]
I was starting to use the the ResourceController for serving plain-text files, but it did not work.
Is the support for plain-text files being removed or just migrated to something else?

**Comment by spencergibb** [comment]
@dinhani no, this is to remove specific use of a query parameter named `useDefaultLabel` that doesn't work anyway.

**Comment by ThomasVitale** [comment]
@spencergibb can I help with this task?

**Comment by spencergibb** [comment]
@ThomasVitale sure

**Comment by ThomasVitale** [comment]
I've just created a PR: https://github.com/spring-cloud/spring-cloud-config/pull/1728
I've removed both mappings in `ResourceController` using the `useDefaultLabel`. Is it ok?
