### ISSUE TITLE
spring-cloud-config-server should not refresh itself environment

### ISSUE THREAD

**Issue by peacetrue** [spring-cloud/spring-cloud-config#1654]
**Describe the bug**
First of all, I need to make sure that the `spring-cloud-config-server` will not read the configuration from the `EnvironmentRepository`(like spring-cloud-config-client). In my test, it will not read.

Then I found that when the configuration from `EnvironmentRepository` is changed, `spring-cloud-config-server` will refresh its environment properties. As mentioned above, since it will not read the configuration from `EnvironmentRepository`, the configuration change has nothing to do with it, and it should not refresh itself.

**Sample**
Dependency description:

* spring-cloud-config-server:2.2.2
* spring-cloud-config-monitor:2.2.2
* spring-cloud-starter-bus-amqp:2.2.2

Invoke stack(for `NativeEnvironmentRepository`):

* FileMonitorConfiguration.poll()
* PropertyPathEndpoint.notifyByPath(HttpHeaders,Map<String, Object>)
* ApplicationEventPublisher.publishEvent(RefreshRemoteApplicationEvent)
* RefreshListener.onApplicationEvent(RefreshRemoteApplicationEvent)
* ContextRefresher.refresh()
* ConfigurableApplicationContext.publishEvent(EnvironmentChangeEvent)
* ConfigurationPropertiesRebinder.onApplicationEvent(EnvironmentChangeEvent)

**Comment by spencergibb** [comment]
Refresh is part of spring cloud commons, I'm not sure there's much we can do here.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
