### ISSUE TITLE
provide usage documentation without spring boot

### ISSUE THREAD

**Issue by imod** [spring-cloud/spring-cloud-config#166]
The documentation claims the following:

`...so they fit very well with Spring applications, but can be used with any application running in any language.`

But there is no documentation how this would even work without `spring-boot`. Could you please add documentation on these topics?
- how to use the `config-client` in a Spring MVC app (no spring-boot)
- how to embed the `config-server` in a Spring MVC app (no spring-boot)

**Comment by dsyer** [comment]
The config server is an API (HTTP resource) server. To use it from a non Spring Cloud client, you consume the endpoints using your HTTP client of choice. I would have thought that was obvious.

As far as embedding the server goes, I don't know how you would do that without Spring Boot on the classpath. Why would you want to anyway?

**Comment by imod** [comment]
If I have a single application (and only one instance of that application), then I don't wanna run a separate application just to be able to use `spring-cloud-config` - that just doubles my costs and brings unnecessary complexity. In such a case I would wanna have the client and server be running in the same instance - but maybe the client is already able to work without the server and use use e.g. git directly, but the documentation is just missing.

**Comment by dsyer** [comment]
If someone has some suggestions about what might change in the documentation then we can mark it as a "documentation" issue. The idea of embedding the git repository clone features in an application is sort of interesting, but I would call that an "enhancement" really, since you would be using the config server code but not exposing a server. How easy it would be to use without Spring Boot is yet another question, but without the feature there's not much point documenting anything.

**Comment by imod** [comment]
I agree with the "enhancement" type for the config-server. 
But what I was referring to for documentation is about the usage of config-client outside of spring-boot.

**Comment by dsyer** [comment]
Fine, but your use case didn't require documentation as much as a new feature. The existing documentation doesn't (as far as I know) even suggest that the config-client might be useful outside a Spring Cloud application. It *does* say that the server could be useful to a wide range of applications, but that wasn't your requirement in the end anyway, and the documentation we have is adequate for that anyway I think (it describes all the HTTP resources in detail).

**Comment by imod** [comment]
ok, thanks - I agree there with your outcome (although its a disappointment)

**Comment by cerebrotecnologico** [comment]
To use the spring config client on a non-boot Spring app, we don't want to use the REST API with the HTTP client of our choice, we want to be able to reuse parts of the Spring Config Client, perhaps  an implementation of PropertySource that already knows how to call the endpoints in the server

**Comment by AshishShivrajPoste** [comment]
Do we have a solution for this problem

**Comment by dsyer** [comment]
http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_serving_alternative_formats
http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_serving_plain_text

An HTTP client can consume those endpoints. It's up to you to work out what to do with them but if you are using Spring Boot it works as a normal Boot config file.

**Comment by hth** [comment]
Is there an example without SpringBoot that shows configuring Sleuth?
