### ISSUE TITLE
Links to Spring Cloud Config docs on spring.io are broken

### ISSUE THREAD

**Issue by xtreme-jon-ji** [spring-cloud/spring-cloud-config#1672]
Links to Reference Doc and API Doc on https://spring.io/projects/spring-cloud-config#learn are broken for:

3.0 0-M3
3.0.0 M1
2.2.4
2.1.9
2.1.8

I apologize if this isn't the place to report documentation issues - if that's the case, could you help direct me to which repo to create an issue on?

**Comment by spencergibb** [comment]
This has been fixed.
