### ISSUE TITLE
Not honoring Vault configurations "spring.cloud.config.server.vault" at start-up

### ISSUE THREAD

**Issue by bkoragan** [spring-cloud/spring-cloud-config#1681]
Question:
Issue with honoring "spring.cloud.config.server.vault" property values while boot-up and hence its connecting to default Vault endpoint values like localhost:8200 ?  Is there a know issue when integrating with both GIT+Vault sources ? or please correct me if I'm missing anything? Reference to any sample configuration with my scenario would be of great help!

More Description:
I'm using "spring-cloud-config" to integrate with two back end sources(GIT + Vault) to get configurations from both sources.

here are version details in my pom:
<artifactId>**spring-boot-starter-parent**</artifactId>
<version>**2.3.2.RELEASE**</version>
<spring-cloud.version>**Hoxton.SR6**</spring-cloud.version>
<artifactId>**spring-cloud-dependencies**</artifactId>
<version>${spring-cloud.version}</version>

Here is my bootstrap.yml file:
![image](https://user-images.githubusercontent.com/34816445/89616929-3b7ca400-d857-11ea-9118-95209d2ad77d.png)

Thanks and Appreciate any help!

**Comment by bkoragan** [comment]
@ryanjbaxter @spencergibb any help/inputs are much appreciated !

**Comment by spencergibb** [comment]
If you are using multple profiles in bootstrap, please use composite repositories https://docs.spring.io/spring-cloud-config/docs/3.0.2/reference/html/#composite-environment-repositories

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
