### ISSUE TITLE
How to determine path of git working copy?

### ISSUE THREAD

**Issue by satar** [spring-cloud/spring-cloud-config#169]
Like iceycake discusses in issue #147 I also need to push an XML file, in my case for a third-party service. I need to push this file, and potentially others in the future, as part of the solution. I want to leverage off all the hard work the config server already does for me with for property management. The idea is to place these files in the same github repo where the property configs live and then add a couple additional endpoints to a controller in the spring boot config server app that can look up what should be pulled and another to pull them down to client. 

I may be missing something, but I don't see how from the context of the spring boot app that embeds my cloud config server I can determine the root path of the locally cloned repo (or repositories but I would likely stick to one for cm simplicity). Is this possible or is it possible that I can tell the config server to use local path x/y/z when cloning? I think this would be a useful mechanism regardless of my probably not so great current reason for the need of it.

**Comment by dsyer** [comment]
There's a `@Bean` of type `MultipleJGitEnvironmentRepository` with a property called "basedir". That's the location of the working copy (if there is only one, otherwise the individual repos each have their own). You can set it with `spring.cloud.config.server.git.basedir`.
