### ISSUE TITLE
Composite profile not serving label in case there are multiple git repos

### ISSUE THREAD

**Issue by psharmaithaka** [spring-cloud/spring-cloud-config#1691]
**Describe the bug**
Spring Cloud Config Server - spring-cloud-config-server-2.1.0.RELEASE.jar

I am using composite profile to connect to two git repositories at the same time. I pull configurations from two git repos based on the pattern. But if I try to get the label(git branch) that is only in one repository the config service does not render anything from that git branch into browser

I try to check config using the URL : http://localhost:8888/{application-name}/{profile}/{label or git branch}

**Sample**
Sample of my application.yml attached to the ticket

[application.txt](https://github.com/spring-cloud/spring-cloud-config/files/5136858/application.txt)

**Comment by spencergibb** [comment]
can you be more specific about which git repo in your sample has a particular label and which one does not?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
