### ISSUE TITLE
Support for serverless operation of config client

### ISSUE THREAD

**Issue by imod** [spring-cloud/spring-cloud-config#170]
If I have a single application (and only one instance of that application), then I don't wanna run a separate application just to be able to use spring-cloud-config - that just doubles my costs and brings unnecessary complexity. 
In such a case I would wanna have the client and server (or better just the server API) be available in the same instance.

extracted issue out of the conversation in #166

**Comment by spencergibb** [comment]
This is how spring-cloud-consul-config and spring-cloud-zookeeper-config work.

**Comment by dsyer** [comment]
I expect this would work up to a point already if you add the spring-cloud-config-server as a dependency and *dont'* `@EnableConfigServer`  but *do* set `spring.cloud.config.server.bootstrap=true`. That would add the environment repository property source to your `Environment` at least. Might need some tweaks.

**Comment by AshishShivrajPoste** [comment]
Do we have a solution for the problem discussed

**Comment by dsyer** [comment]
Did you read my last comment? Did you try it?
