### ISSUE TITLE
Custom extension of spring cloud config server

### ISSUE THREAD

**Issue by kalous78** [spring-cloud/spring-cloud-config#1700]
Hello,

I have a question regarding spring cloud config server. I'd like to create custom wrapper in cloud config server.
I have application configuration data stored in git repository in yaml file:
app1.yml
dev:
  config:
    db.user: test
    db.password: ${dev.db.password}

My wrapper should replace the placeholder "${dev.db.password}" with real password from our vault system.
So app1 should get config data like this:
dev:
  config:
    db.user: test
    db.password: password

My qestion is, how to create the wrapper?
Would be possible to send me a basic example.
 
Thank you.

Regards
Frantisek Kalousek

**Comment by spencergibb** [comment]
Config server supports vault directly
