### ISSUE TITLE
JDBC property versioning

### ISSUE THREAD

**Issue by aidanpd** [spring-cloud/spring-cloud-config#1710]
I cannot see how to control changes to key-value pairs when backed by a JDBC repository as there is no property versioning or history table. This makes auditing of changes to property values impossible as far as I can see.

A solution would be for the JDBC repository to have some kind of history table.

Ideal would be similar functionality to Git backed repository where we can use Git to review changes etc.

**Comment by spencergibb** [comment]
The reason we went with git to begin with is so we wouldn't have to build any of that. The `JdbcEnvironmentRepository` only reads data from a table (the SQL is customizable). Any entry of data into a table is outside the preview of config server and would be up to your organization to implement versioning and auditing.
