### ISSUE TITLE
Server doesn't reflect on branch renaming

### ISSUE THREAD

**Issue by GordPavel** [spring-cloud/spring-cloud-config#1711]
If you rename the branch in git, cloud server doesn't see new label, but old one still works

Steps to reproduce: 
create branch in git source and ask server this config by label. Then rename branch and ask server the new label.

**Comment by spencergibb** [comment]
Have you tried setting `spring.cloud.config.server.git.force-pull=true` or ``spring.cloud.config.server.git.deleteUntrackedBranches=true`?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
