### ISSUE TITLE
JGitEnvironmentRepository make private methods protected

### ISSUE THREAD

**Issue by llambda** [spring-cloud/spring-cloud-config#172]
Would it be possible to make private methods protected for JGitEnvironmentRepository? I'd like to extend and right now am using reflection to access createGitClient, initialize, and getWorkingDirectory. (I am using that to create commits in the git repo.) Thanks!

**Comment by spencergibb** [comment]
Your use case sounds scary to me.  I'm pretty sure we don't wan't config server to be in the business to create commits.

**Comment by llambda** [comment]
I understand, it's a valid concern about config server creating commit, and I'm open to any suggestions For our case we wanted to have a web interface that allows changing values for convenience. Link to  the code for how I extended the class... https://gist.github.com/llambda/1d4f404fbb58f48ab6d0

**Comment by dsyer** [comment]
Agree. It would be better to just copy the code.
