### ISSUE TITLE
[Bug or Expected Behavior] Health indicator for config server git repository after reset credenitals

### ISSUE THREAD

**Issue by Incarnation-p-lee** [spring-cloud/spring-cloud-config#1727]
**Describe the bug**
Config server always return `UP` after reset remote github uri credentials.

**Sample**
Reproduce step
* Create one config server with github public uri https://fake-uri.git
* Curl /actuator/health, should be `UP` here.
* Make the https://fake-uri.git repo privated.
* Curl /actuator/health, should be `DOWN` then but still get `UP` as usual.

**Potential Fix**
Throw exception when fetch() invoked by refresh(). Thus when fetch failure, refresh should be aware of this.
https://github.com/spring-cloud/spring-cloud-config/blob/baa1bd4282c753a39c5a019cef6efba7a9f06f66/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepository.java#L451-L475

**Comment by spencergibb** [comment]
actuator health calls are [cached for a while](https://docs.spring.io/spring-boot/docs/1.2.1.RELEASE/reference/html/production-ready-monitoring.html#production-ready-health-access-restrictions). Have you tried waiting?

**Comment by Incarnation-p-lee** [comment]
Yes, I didn't config `endpoints.health.time-to-live` thus it should be 1 seonds.
I setup one simple config server locally with curl to verify many times and reproduce stablely. So it may not related to cache from my side.

**Comment by Incarnation-p-lee** [comment]
any update about this issue ?

**Comment by spencergibb** [comment]
I think this is expected behavior. In my test, the local checkout of the git repository is still there, so that it what it uses.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
