### ISSUE TITLE
Please provide a way to connect Spring Cloud Config Server as a ConfigMap for my Kubernetes infrastructure and services

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-config#1737]
**Is your feature request related to a problem? Please describe.**
No problem: quite the contrary: Spring Cloud Config Server is so useful I'm trying to extend its reach

**Describe the solution you'd like**

I would love to somehow be able to mount a Spring Cloud Config Server instance as a Kubernetes ConfigMap so that my Kubernetes applications could draw their configuration directly from the config server instead of me having to ferry the values into ConfigMaps manually during build time 

**Describe alternatives you've considered**
See above

**Additional context**

**Comment by spencergibb** [comment]
I just moved this to s-c-k8s where it would be implemented

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-kubernetes/issues/668
