### ISSUE TITLE
ConfigServerConfigDataLocation extends final class ConfigDataLocation from Spring Boot

### ISSUE THREAD

**Issue by fedortche** [spring-cloud/spring-cloud-config#1738]
Trying spring-cloud-config-client from 2020.0.0-M4 with Spring Boot 2.4.0-RC1 I'm getting java VerifyError.
The reason is ConfigServerConfigDataLocation extends ConfigDataLocation which is a final class in Spring Boot

**Comment by spencergibb** [comment]
This is already fixed and will be in the next release early next week

**Comment by fedortche** [comment]
ok thanks sorry couldn't find the duplicate one
