### ISSUE TITLE
Spring Config Server not able to connect to Github using only the main branch 

### ISSUE THREAD

**Issue by Astha0710** [spring-cloud/spring-cloud-config#1744]
As the default branch in Github is changed from master to main. Without having a master branch in place for the git repository the Spring Config Server when tries to access the Git repository gives an error. Is it mandatory to have a master branch for a Git repository to work with spring config server or is there a way we can work without having the master branch ?

**Comment by spencergibb** [comment]
Duplicates #1722.

For now you can set `spring.cloud.config.label` on the client.
