### ISSUE TITLE
If a bean has @RefreshScope annotation and implements SmartLifecycle, SmartLifecycle failure

### ISSUE THREAD

**Issue by flangely** [spring-cloud/spring-cloud-config#1745]
**Describe the bug**
with 
<spring-cloud-alibaba.version>2.2.1.RELEASE</spring-cloud-alibaba.version>
<spring-cloud.version>Hoxton.SR6</spring-cloud.version>

If a Bean has the @RereshScope annotation and implements the SmartLife interface, the SmartLife interface lifecycle method will not be invoked after the Spring container is started

**Sample**

Bean:
@Slf4j
@Component
@RefreshScope
public class NectorInvoker implements SmartLifecycle

start method:
@Override
    public void start() {
        if (this.running.compareAndSet(false, true)) {
            nectorClient.start();
        }
   }

As mentioned above, the start method will not be called

**Comment by spencergibb** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-commons/issues/848
