### ISSUE TITLE
When use BootstrapApplicationListener(Because need used the remote configuration center) ,SpringApplication.addListeners Method does not work（sping boot 2.3.5.RELEASE，spring cloud Hoxton.SR8）

### ISSUE THREAD

**Issue by np7sky** [spring-cloud/spring-cloud-config#1746]
main class
```java
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class GiantApplication {
    public static void main(String[] args) {
        SpringApplication application = new SpringApplication(GiantApplication.class);
        application.addListeners(new Log4J2SpringEnvListener());
        application.run(args);
    }
}
```
The configuration file is bootstrap.yml，

The debugging results of idea found that when use nacos or spring cloud config 

, the SpringApplication.run method was executed twice as shown in the figure:

the first：

SpringApplication.java

![image-20201113115903351](https://user-images.githubusercontent.com/13186540/99034911-457e1380-25b9-11eb-95f6-e4d87a7e7e49.png)

Second : Log4J2SpringEnvListener is gone.

BootstrapApplicationListener.java

![image-20201113135049598](https://user-images.githubusercontent.com/13186540/99034951-66466900-25b9-11eb-9c1b-4a72dfedd4c2.png)

SpringApplication.java

![image-20201113115955251](https://user-images.githubusercontent.com/13186540/99034982-8118dd80-25b9-11eb-9653-92f0dffad3bc.png)

##### What i need to Do something so that custom listener is called before LoggingApplicationListener. But custom  defined Listener needs to be able to use the environment.

I used Google Translate and it may be difficult to understand,

Thank you for reading all this question!

**Comment by np7sky** [comment]
it work for me;
in src\main\resources\META-INF\spring.factories
```properties
org.springframework.context.ApplicationListener=\
com.xxx.xxx.common.spring.log4j2.Log4J2SpringEnvListener
```
But I don’t want to configure more locally， Is there any other way?

**Comment by spencergibb** [comment]
This is an artifact of the legacy bootstrap system. https://github.com/spring-cloud/spring-cloud-commons/issues/737  There is no easy fix. Using the new `spring.config.import` in 2020.0 (aka ilford) is the way to avoid this problem.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by np7sky** [comment]
Hope we all have a bright future! Come on!

**Comment by spencergibb** [comment]
As I said before, this is an artifact of bootstrap. There's no way to fix it. The new spring.config.import avoids this.

**Comment by np7sky** [comment]
If it is not easy to fix, it can be added to the future plan. As for whether to close the problem, it depends on the long-term consideration of the spring cloud team.  I have no other opinions
