### ISSUE TITLE
Unable to override properties locally during development

### ISSUE THREAD

**Issue by 7--** [spring-cloud/spring-cloud-config#1748]
**Describe the bug**
https://cloud.spring.io/spring-cloud-static/spring-cloud.html#overriding-bootstrap-properties
According to this there's no way to change properties locally when developing. This is a common use case. Often developers don't have access to the config server or don't wish to push changes and redeploy which could effect the whole team. It says they can be overriden on the command line but I was only able to override `--server.port=8080`

**Sample**
`--my.app.prop.abc=2` This won't get overriden when put on the command line. Since `spring.cloud.config.allowOverride=true` is not set there's no way to try locally when developing.

**Comment by 7--** [comment]
Still a big issue. There's no way to set config values for local development.

**Comment by spencergibb** [comment]
what about disabling config client? If the shared config server isn't mutable by a dev, disable it.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
