### ISSUE TITLE
Cache with Git Backend

### ISSUE THREAD

**Issue by fritzrichter** [spring-cloud/spring-cloud-config#175]
We are using BitBucket as Git Backend for our Config-Server. If a spring-boot clients wants to retrieve updates from the ConfigServer, this one is always going to the external remote GIT-Repository and loads the newest data.

This feature always takes ~ 3-5 seconds, depending on the connection speed between ConfigServer and BitBucket. It would be nice to add a optional feature, which either
a) caches the git-results for a certain fixed time
b) caches the git-results and continuously updates the cache in the background (even if no client is asking for new updates).

It's good to have always the newest configuration, but in practice everything slows down, especially for the developers, who are starting apps quite often during development.

**Comment by spencergibb** [comment]
@fritzrichter I'd say that if your devs want speed, manually clone the git repo and use a [file system backend](https://github.com/spring-cloud/spring-cloud-config/blob/master/docs/src/main/asciidoc/spring-cloud-config.adoc#file-system-backend) for config server.  Then it will only update if they run `git pull`.

**Comment by fritzrichter** [comment]
That's actually not the right solution for another problem. Of course that's something we can do locally, on the other hand going to GIT everytime for every single request, is somehow bad. As well for remote-services I would like a fast start-up and response times of 3-5s for a HTTP Rest Call is something which is good to avoid in general I would say. 

What's wrong with a simple Cache?

**Comment by spencergibb** [comment]
Nothing's wrong with the cache, just a way to approximate it without having the feature.

**Comment by dsyer** [comment]
You could add a cache in your server quite easily anyway using Spring Framework core features. I would prefer not to do it here because the data in the backend can of course change, so you don't really want the cache in production if I understand correctly.

**Comment by gondor** [comment]
+1  We are in the process of moving all of our services to the cloud.  Our Git server is still on premise so the connect between our config server in the cloud to pull from on premise is higher in latency.  That being said it would be nice to configure when it updates the local repo (by request or by interval).  I'm curious on how to leverage a cache as mentioned above if it would help in my scenario.

**Comment by fritzrichter** [comment]
Today it happened again, the BitBucket Server was not reachable, so in the end I was not able to start up my servers, as the config server did not respond. A fallback to the old folder cache would be really nice.

I "jstacked" the config-server, when it was hanging, here the results, maybe this is another issue?

```
"qtp144085203-93" #93 prio=5 os_prio=0 tid=0x00007f72a8012800 nid=0x1b6f waiting for monitor entry [0x00007f73013b6000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:93)
	- waiting to lock <0x00000000c3383a68> (a org.eclipse.jgit.transport.DefaultSshSessionFactory)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1115)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	at org.springframework.cloud.config.server.JGitEnvironmentRepository.tryFetch(JGitEnvironmentRepository.java:213)
	at org.springframework.cloud.config.server.JGitEnvironmentRepository.openGitRepository(JGitEnvironmentRepository.java:184)
	at org.springframework.cloud.config.server.JGitEnvironmentRepository.createGitClient(JGitEnvironmentRepository.java:164)
	at org.springframework.cloud.config.server.JGitEnvironmentRepository.findOne(JGitEnvironmentRepository.java:80)
	at org.springframework.cloud.config.server.MultipleJGitEnvironmentRepository.findOne(MultipleJGitEnvironmentRepository.java:84)
```

**Comment by dsyer** [comment]
A cache any actually help then. Your server actually already has a cache copy of the repo (if it has been running for a while already). Your git provider went south but still has a socket open that you are blocking on. It's really a downstream problem, but I guess we might have to think of something to work around it here. I believe the socket will eventually time out and the config server will make progress again, but by then the client has probably given up. I suppose a retry with a long eventual timeout on the client would fix it at the cost of very slow start up. Did you try that (given that it's intermittent it might be tolerable)?

The only other thing we could do, that I can think of, is try and process the git connection in a background thread and put in another layer of timeouts in there.

**Comment by dsyer** [comment]
I was going to say "did you try just setting `spring.config.server.git.timeout`?" but then I noticed it's not exposed as a config property (I'll fix that separately #225).

**Comment by fritzrichter** [comment]
Personally, I like that approach:

1. try to load from git (say with a configureable timeout)
2. in case of timeout do it resilient and deliver the local cache

**Comment by dsyer** [comment]
That's what you get already if you set the timeout in the `JGitEnvironmentRepository`. Unfortunately you couldn't do that until today using configuration properties.

**Comment by fritzrichter** [comment]
I tried to set the timeout, but it seams, that there is no such a property in the current version (1.0.2.RELEASE), must wait for 1.1.0 then. Any idea, when this will be released?

**Comment by dsyer** [comment]
#225 is marked as fixed in 1.0.3. We could release that at any time I guess (I don't think there's anything else outstanding). In the meantime all you need to do is create your own `@Bean` of type `EnvironmentRepository` and set the timeout.

**Comment by fritzrichter** [comment]
As said, in version 1.0.2 (which is the only one currently available at the mvn repository) I can not set the timeout. I downloaded the 1.1.0.M1 sources now and uploaded the artifacts manually to our artifactory.

Here I tested the property and it worked pretty fine actually. One think I noticed, just to make this conversion complete: the right property which you have to set is "spring.cloud.config.server.git.timeout".

Looking forward to the next release then.

**Comment by dsyer** [comment]
You can set the timeout in 1.0.2 by doing as I suggested above I believe. Good to hear it works as expected in 1.1
