### ISSUE TITLE
Update this repository's spring-cloud-config-sample to 2.4.x as 2.4.x contains breaking change please :)

### ISSUE THREAD

**Issue by patpatpat123** [spring-cloud/spring-cloud-config#1750]
Hello, is it possible to update this repository's spring-cloud-config-sample to 2.4.x + Illford as 2.4.x + Illford contains breaking change please :)

**Comment by spencergibb** [comment]
I don't understand. Version 3.0.x is ilford and is built using bit 2.4.x

**Comment by patpatpat123** [comment]
Hello @spencergibb,

My bad, I should have been more clear. Definitely my bad.

Currently in the spring-cloud-config/spring-cloud-config-sample/src/main/java/sample/  project, there is a main file:

```
@RestController
@SpringBootApplication
public class Application {

	@Autowired
	private Environment environment;

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

	@RequestMapping("/")
	public String query(@RequestParam("q") String q) {
		return this.environment.getProperty(q);
	}

```

And some application and bootstrap .yml under resources.

Would it be possible to have instead a @EnableConfigServer main file, with the new bootstrap start up behavior, and another client with also the new bootstrap startup format that will talk to the @EnableConfigServer, both with the newest way of configuration please?

(Please let me know if I am not clear, I will be glad to provide further explanation).

It is just this repo might be one of the first place people look at in order to understand and have hands on experience with this cool project.

Just wanted to ask if it is possible to have a config server and a config client, all respecting the latest configuration format in this sample repo.

I hope it is not an irrelevant ask. I was thinking that contrary, it could help people get started.

Thank you

**Comment by patpatpat123** [comment]
And also @spencergibb,

Your post here https://spring.io/blog/2020/11/18/spring-cloud-2020-0-0-m5-aka-ilford-is-available#disqus_thread mentions Illford M5.

However, bottom of the post, in the maven and Gradle dependency, I think there is a typo, we can see M4 mentioned.

Thank you

<img width="910" alt="Screen Shot 2020-11-19 at 4 10 50 PM" src="https://user-images.githubusercontent.com/43899031/99638964-fbe26c80-2a81-11eb-87a1-9ad7f4ce793e.png">

**Comment by patpatpat123** [comment]
I think this is not relevant anymore, as people are moving towards newer versions.

Thanks!
