### ISSUE TITLE
Pushing config to GitHub with typo causes config server to hold onto current config file version until restart

### ISSUE THREAD

**Issue by jaytylerwilliams** [spring-cloud/spring-cloud-config#176]
Hi,

We have seen an issue where if a .yml config file that contains a typo is pushed to Github it will cause config server to go into a state where it will hold on to that config file version, and subsequent changes and pushes to the repository will not be reflected either by apps pointing to config server, or by accessing the config values via the REST endpoint of config server.  It is not until a config server restart that the issue gets resolved.  Is there another way around restarting the server?

An example of a typo that caused the behavior was adding a list of values, and forgetting the space between the dash and the value.  Ex.

```
users:
  admins: 
    -admin1
    -admin2
```

After I made this change I checked it via the REST api: http://prodconfigserver:8888/appname/profile/branchname which caused the config server to become locked up.  It seems to continue to serve this version of the config until restart.  I verified that by pointing my localhost version of config server to the same repo, hitting the REST endpoint, then trying to push the fix to the repository would force me to restart config server for the change to be picked up.  Normally adding new values is immediately reflected when accessing the REST endpoint.

Our workflow has been to have one config server running that serves configs for ALL environments dev, test, prod.  We push config changes to remote Github branches for dev/test and reference the branch name in the `spring.cloud.config.label` property.  When we go to production we merge the config changes to master, tag a release, and then update the label in the client app to match the new tag/release name.  

Is this an ideal workflow?  Should we utilize a completely separate repository for clean, tested config files?  Thanks for any help.

**Comment by dsyer** [comment]
The sample you posted above isn't even invalid YAML so I don't know why it would be a problem. Even if it was the result would be a 500 from the Config Server and it would recover when the change was applied (pushed to the remote). Maybe if you could check again and see if there isn't something else going on there. Also probably worth updating to the latest code (i.e. a snapshot) in case something is different there.

**Comment by davidmorley** [comment]
We're seeing the same thing, actually. If we commit invalid YAML into the repository, the config server (not unexpectedly) can't parse it, and throws an exception:
```
2015-10-08 15:34:49.671 ERROR 36894 --- [nio-8888-exec-7] o.s.boot.SpringApplication               : Application startup failed

org.yaml.snakeyaml.parser.ParserException: while parsing MappingNode
 in 'reader', line 190, column 1:
    spring:
    ^
duplicate key: pg.server.port
 in 'reader', line 228, column 1:
    ---
    ^

	at org.springframework.beans.factory.config.YamlProcessor$StrictMapAppenderConstructor.constructMapping(YamlProcessor.java:405)
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:485)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:108)
	at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:502)
```

After that, despite pushes to the repo with corrected syntax, the config server doesn't seem to pick it up until we restart the config server.

**Comment by marcingrzejszczak** [comment]
Is it still a problem with Finchley?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
