### ISSUE TITLE
Config Client is not running

### ISSUE THREAD

**Issue by liranfar** [spring-cloud/spring-cloud-config#1762]
Hi, 

I see that under spring-boot-starter-parent 2.4.0 and spring-cloud-dependencies 2020.0.0-M5 the config client is not running nor showing any log message ( _fetching config..._).

I used spring-boot-initializer (in intellij) and chose spring-web and config-client dependencies as maven project.
After that I tried using spring-boot-starter-parent 2.3.6.RELEASE and spring-cloud-dependencies Hoxton.SR9 and it worked as expected.

Thanks guys!

**Comment by spencergibb** [comment]
See the release notes https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#breaking-changes
