### ISSUE TITLE
Config Server fails if refresh scope not available

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-config#1763]
E.g. `EnvironmentController` is declared as `@RefreshScope` unconditionally. I think this is out of step with the usage of `@RefreshScope` in other parts of Spring Cloud. Also, it seems kinder to make it optional.

**Comment by spencergibb** [comment]
Spring Cloud commons isn't really optional any more

**Comment by dsyer** [comment]
Yes, but it's spring-cloud-context, and anyway `@RefreshScope` is optional even with that.

**Comment by spencergibb** [comment]
Yeah, I meant the project not the module. And IIRC s-c-context is not optional in the other Spring Cloud projects anymore

**Comment by spencergibb** [comment]
Anyway, this change is fairly benign so it doesn't really matter much
