### ISSUE TITLE
Overriding ConfigServicePropertySourceLocator

### ISSUE THREAD

**Issue by arsenaid** [spring-cloud/spring-cloud-config#177]
I have a use case where I need to pass Authorization header to the Config Server. How can I override RestTemplate in ConfigServicePropertySourceLocator class? I am not able to disable ConfigServiceBootstrapConfiguration auto configuration.

**Comment by dsyer** [comment]
You can set `spring.cloud.config.enabled=false` to disable the existing config server property source. Then you'd have to add your own with the custom `RestTemplate`.

**Comment by arsenaid** [comment]
Custom source worked fine. Thank you.

**Comment by cubfan20** [comment]
Can you give examples of what you did to fix this?  I am running into the exact same issue and can't find the right way to do this.

**Comment by arsenaid** [comment]
There are few things you'd need to do to make this work:

1) Set spring.cloud.config.enabled=false to disable the existing config server property source
2) Create a new @Configuration annotated class CustomConfigServiceBootstrapConfiguration with your implementation of PropertySourceLocator

 @Bean
    public ConfigClientProperties configClientProperties() {
        ConfigClientProperties client = new ConfigClientProperties(this.environment);
        client.setEnabled(false);
        return client;
    }

    @Bean
    public ConfigServicePropertySourceLocator configServicePropertySourceLocator() {
        ConfigClientProperties clientProperties = configClientProperties();
       ConfigServicePropertySourceLocator configServicePropertySourceLocator =  new ConfigServicePropertySourceLocator(clientProperties);
        configServicePropertySourceLocator.setRestTemplate(customRestTemplate(clientProperties));
        return configServicePropertySourceLocator;
    }

3) In resource/META_INF create a file spring.factories and specify bootstrap components. This is important, otherwise, it won't load the custom bootstrap class you created. Specify the name of your Bootstrap class, e.g.

# Bootstrap components
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
com.my.config.client.CustomConfigServiceBootstrapConfiguration

**Comment by spencergibb** [comment]
If you're going to set `spring.cloud.config.enabled=false`, don't include `spring-cloud-config-client` in the first place.  `BootstrapConfiguration` comes from `spring-cloud-context`.  [Spring Cloud Consul](https://github.com/spring-cloud/spring-cloud-consul/tree/master/spring-cloud-consul-config) and [Spring Cloud Zookeeper](https://github.com/spring-cloud/spring-cloud-zookeeper/tree/master/spring-cloud-starter-zookeeper-config) both have similar implementations of this.

**Comment by arsenaid** [comment]
In my case I needed the config client since without it remote config source
wouldn't get  loaded.

**Comment by bitsofinfo** [comment]
This should be in the official documentation under http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_client_side_usage in the `Security` section as it is non-intuitive

**Comment by andysworkshop** [comment]
The workaround is such an ugly (but necessary) hack that it shouldn't appear in any documentation.  BTW the code snippet above needs `@Primary` on the `configServicePropertySourceLocator()` method and `this.environment` is a spring core `Environment` class that can be injected as a member with `@Inject`. I also had to keep `spring.cloud.config.enabled=true`. Finally I can secure calls to my cloud config server but I don't feel good about it!

An official way to customise the `RestTemplate` used by this property source locator would be much appreciated in a future version.

**Comment by dsyer** [comment]
I think you are doing something wrong if it's as ugly as you say. The spring cloud services team do it in a few lines of code with no drama as far as I am aware (probably using the trick I suggested with autowiring the locator).

**Comment by andysworkshop** [comment]
Do you have a link to the clean implementation that I can look at? The `RestTemplate` is created during the `locate()` call which happens during the execution of an application context initializer which is too early in the bootstrap to do much other than @arsenaid's override. Happy to proven wrong here...

**Comment by marcellodesales** [comment]
It would be great to have a documented sample for this scenario... We have additional Headers required by our Config Servers to accept calls.

**Comment by marcellodesales** [comment]
Looking at the source-code, https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java#L193-L196, couldn't we expose an HTTP Interceptor Bean for the client's implementation?

That way, users would just implement their own bean similar to the basic one as https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java#L201-L221

**Comment by spencergibb** [comment]
If we could do that we'd do it for the rest template

**Comment by marcellodesales** [comment]
@spencergibb True... Looking into it... Would need to change the `restTemplate` instantiation at https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java#L76-L77 with a bean... correct?

**Comment by marcellodesales** [comment]
@spencergibb @andysworkshop @arsenaid 

CustomBean bean overridden by default Spring Cloud version
=====

I'm following the suggestion on this... I'm getting the following bean replaced with the original and I'm not sure why it has higher precedence than mind, even though I defined mined as `@Primary`.

```java
INFO [  restartedMain] o.s.b.f.s.DefaultListableBeanFactory Overriding bean definition for bean
 'configClientProperties' with a different definition: replacing [Root bean: class [null]; scope=;
abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true;
 primary=false;  factoryBeanName=configSourceLocator;
factoryMethodName=configClientProperties; initMethodName=null; destroyMethodName=(inferred); 
defined in class path resource
[com/company/platform/config/publisher/ConfigSourceLocator.class]] 
with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3;
 dependencyCheck=0; autowireCandidate=true; primary=false; 
factoryBeanName=org.springframework.cloud.config.client.ConfigClientAutoConfiguration;
 factoryMethodName=configClientProperties; initMethodName=null; 
destroyMethodName=(inferred); defined in class path resource
 [org/springframework/cloud/config/client/ConfigClientAutoConfiguration.class]]
```

Class Design
====

* Followed the suggestions above;
* Rest template copied from [the original code](https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java#L188-L221);
* Retrieving the required authentication token from the `password` property for now, as shown in the class below.

Questions and Class
===

I have tried disabling the config client, and removed the flag. Still no luck... Any suggestions?

```java
package com.company.platform.config.publisher;

import java.io.IOException;
import java.util.Arrays;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.config.client.ConfigClientProperties;
import org.springframework.cloud.config.client.ConfigServicePropertySourceLocator;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.core.annotation.Order;
import org.springframework.core.env.Environment;
import org.springframework.http.HttpRequest;
import org.springframework.http.client.ClientHttpRequestExecution;
import org.springframework.http.client.ClientHttpRequestInterceptor;
import org.springframework.http.client.ClientHttpResponse;
import org.springframework.http.client.SimpleClientHttpRequestFactory;
import org.springframework.web.client.RestTemplate;

@Order(0)
@Configuration
public class ConfigSourceLocator extends ConfigServicePropertySourceLocator {

  @Autowired
  private Environment environment;

  public ConfigSourceLocator(ConfigClientProperties defaults) {
    super(defaults);
  }

  @Bean
  public ConfigClientProperties configClientProperties() {
    ConfigClientProperties client = new ConfigClientProperties(this.environment);
    client.setEnabled(false);
    return client;
  }

  @Primary
  @Bean
  public ConfigServicePropertySourceLocator configServicePropertySourceLocator() {
    ConfigClientProperties clientProperties = configClientProperties();
    ConfigServicePropertySourceLocator sourceLocator = new ConfigServicePropertySourceLocator(clientProperties);
    sourceLocator.setRestTemplate(getSecureRestTemplate(clientProperties));
    return sourceLocator;
  }

  private RestTemplate getSecureRestTemplate(ConfigClientProperties client) {
    SimpleClientHttpRequestFactory requestFactory = new SimpleClientHttpRequestFactory();
    requestFactory.setReadTimeout((60 * 1000 * 3) + 5000); // TODO 3m5s, make configurable?
    RestTemplate template = new RestTemplate(requestFactory);
    String password = client.getPassword();
    if (password != null) {
      template.setInterceptors(Arrays
          .<ClientHttpRequestInterceptor>asList(new AuthorizationToken(password)));
    }
    return template;
  }

  private static class AuthorizationToken implements ClientHttpRequestInterceptor {

    private final String authenticationToken;

    public AuthorizationToken(String authenticationToken) {
      this.authenticationToken = (authenticationToken == null ? "" : authenticationToken);
    }

    @Override
    public ClientHttpResponse intercept(HttpRequest request, byte[] body, ClientHttpRequestExecution execution)
        throws IOException {
      request.getHeaders().add("Authorization", authenticationToken);
      return execution.execute(request, body);
    }

  }
}
```

**Comment by marcellodesales** [comment]
@spencergibb @dsyer

My attempts to implement the Authorization header support as described were not successful... So, I'm sending a suggestion to extend the current implementation with the support with `authorization`. That might be a simpler path. Please let me know if that would be the direction to go, and if so, I'm interested in contributing with more...

**Comment by dsyer** [comment]
Close din favour of #474
