### ISSUE TITLE
Command line --server.port is ignored when server.port is provided from remote config

### ISSUE THREAD

**Issue by arikanorh** [spring-cloud/spring-cloud-config#1800]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

1. Setup a config server with a service specific property and define a port
2. Configure client service to use config service (in my case config service is discovered over eureka)
3. Compile and start from jar from commandline with --server.port

The application starts up with the port defined on config server and ignores the commandline port

**Comment by spencergibb** [comment]
See https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#overriding-bootstrap-properties

Set `spring.cloud.config.allowOverride=true` in the remote file.
