### ISSUE TITLE
2.4.2 how to work with profiles?

### ISSUE THREAD

**Issue by Miles-Ahead-Digital** [spring-cloud/spring-cloud-config#1802]
Hi,

how can I structure my yml-files with profiles in the new 2.4.2 spring boot version?

The syntax:
**spring.config.activate.on-profile: xyz**
does not work with files served by the config server.

The Error is:
"Property 'spring.config.activate.on-profile' imported from location ...is invalid in a profile specific resource"

I tried to use a second -xyz.yml file, but this is not recognized if the xyz profile is active

Please advise
Stefan

**Comment by ankurbhakta** [comment]
This has been fixed with spring boot version 2.4.3

**Comment by Miles-Ahead-Digital** [comment]
With spring boot 2.4.3 the Stactrace is gone, but the config server does not serve profiles as expected.
Please check the demo rep https://github.com/Miles-Ahead-Digital/milesahead 
It is not possible to select the message value base on a spring profile.

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-config/issues/1807#issuecomment-810579138

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
