### ISSUE TITLE
configserver fails silently when yaml is invalid

### ISSUE THREAD

**Issue by pcornelissen** [spring-cloud/spring-cloud-config#1808]
Due to a copy paste error (actually, I don't know how these blanks went into the file) I broke a yaml file that is exposed via configserver.
The effect is:

```
curl http://localhost:55677/lunchdeals/kubernetes
{"timestamp":"2021-02-26T12:06:25.591+00:00","status":500,"error":"Internal Server Error","message":"","path":"/lunchdeals/kubernetes"}
```

There is no log output at all for the failing request in configserver whoch logs on INFO level!

The yaml contained a snipped like this:

```yaml
spring:
                          flyway:
    url: jdbc:mariadb://${db.host}/${db.name}
```

as you can see the "flyway:" part was indented wrong.
After I fixed the indentation, configserver was able to serve requests again without silent 500 errors.

So it is crucial to get some kind of notice that the configserver cannot parse the yaml file. We only found that by accident after hours of searching for other reasons of why the depending services didn't start.

**Comment by ryanjbaxter** [comment]
What version of Spring Cloud are you using?

**Comment by pcornelissen** [comment]
Sorry forgot to mention, it happened with Spring boot 2.4.2 and Spring cloud 2020.0.1
