### ISSUE TITLE
Vault related tutorials on Spring.io not working 

### ISSUE THREAD

**Issue by robinbajaj123** [spring-cloud/spring-cloud-config#1812]
**Describe the bug**
Spring.io blog website has both the links not working 
https://spring.io/guides/gs/accessing-vault/
https://spring.io/guides/gs/vault-config/

**Sample**
Documentation issue, please fix it

**Comment by ryanjbaxter** [comment]
These samples are not related to spring cloud config, they are part of Spring Vault
https://github.com/spring-projects/spring-vault

I think there might be some kind of issue with Spring.io, but I would open the issue with the spring-vault project

**Comment by robinbajaj123** [comment]
ok sure @ryanjbaxter
