### ISSUE TITLE
Documentation bug for "/{application}/{profile}[/{label}]"

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-config#1816]
The documentation says:

```
The HTTP service has resources in the following form:

/{application}/{profile}[/{label}]
....
```

which is incorrect. 

The correct form would be `/{application}/[{profile}]/{label}` as `profile`s can be many. It would also not hurt to have a minor example of this.

**Comment by spencergibb** [comment]
It's not incorrect. Label is optional, profile is not

**Comment by spencergibb** [comment]
Profile can be a comma separated list, but it isn't optional which is what brackets denote

**Comment by wind57** [comment]
thank you @spencergibb, got my answer, closing.
