### ISSUE TITLE
trying to understand : "curl localhost:8888/master/foo-db.properties"

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-config#1818]
If I execute `curl localhost:8888/master/foo-db.properties`, running the samples; I get:

```
info.description: Spring Cloud Samples
info.url: https://github.com/spring-cloud-samples
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
foo: from foo props
democonfigclient.message: hello spring io
foo.db: mycooldb
```

which seems like a lot more than I asked for. I was really expecting to see only `foo.db: mycooldb`. Did I miss-understood something, or this is the intended behavior? If this is intended, then the documentation somehow should explain about this, no? 

thank you.

**Comment by ryanjbaxter** [comment]
Just to be clear, are you trying to get the raw file content of foo-db.properties?

**Comment by wind57** [comment]
right. I was just following the documentation examples a bit and I thought that if I do:

```
curl localhost:8888/master/foo-db.properties
```

I would get _only_ those; but instead I get a lot more. which is sort of weird?

**Comment by ryanjbaxter** [comment]
See this documentation, the right URL is localhost:8888/foo/db/master/foo-db.properties

**Comment by wind57** [comment]
ah! that makes sense now, sorry for taking your time.
