### ISSUE TITLE
ConfigServerHealthIndicator uses wrong application name to construct a URL to config server

### ISSUE THREAD

**Issue by lujimmy** [spring-cloud/spring-cloud-config#182]
Hi spring could team,

I've encountered a problem about health check to config server. The **ConfigServerHealthIndicator** uses default application name, which is **application** to construct the URL to config server.

I used a debugger to track the problem and found that the application name is not correctly resolved by **ConfigClientProperties.override()**

```
	public ConfigClientProperties override(
			org.springframework.core.env.Environment environment) {
		ConfigClientProperties override = new ConfigClientProperties();
		BeanUtils.copyProperties(this, override);
		override.setName(environment.resolvePlaceholders("${"
				+ ConfigClientProperties.PREFIX
				+ ".name:${spring.application.name:application}}"));
		if (environment.containsProperty(ConfigClientProperties.PREFIX + ".profile")) {
			override.setProfile(environment.getProperty(ConfigClientProperties.PREFIX
					+ ".profile"));
		}
		if (environment.containsProperty(ConfigClientProperties.PREFIX + ".label")) {
			override.setLabel(environment.getProperty(ConfigClientProperties.PREFIX
					+ ".label"));
		}
		return override;
	}
```

However, the value of **name** field of ConfigClientProperties is correctly injected.

The result is, the application can connect to config server successfully when startup, but failed for health check.

Is there any way I can turn off the health check for config server? It seems that there is no property I can set to disable the health check.

The version of config client I use are 1.0.0 and 1.0.2. 1.2.2 for spring boot and 4.1.5 for spring.

**Comment by dsyer** [comment]
In the user guide is says "You can disable the Health Indicator by setting `spring.cloud.config.server.health.enabled=false`." It also says that it's not using the application name to check the health, but you can set the values. I'm not sure why. I also don't know why the health check would fail if it had the wrong app name. What is it that happens in your case?

**Comment by lujimmy** [comment]
Hi Dave, It's my bad. I didn't check the latest version of the user guide. I'll close the issue. Thank you so much for the help!

**Comment by heymysweetheart** [comment]
@songyunlu Hi, how did you get this issue resolved? Now I have the same problem when check the health status of ConfigServer, because of the default application name "application". Thanks.

**Comment by songyunlu** [comment]
Hi @heymysweetheart, we end up adding a `ConfigServerPostProcessor` which implements `BeanPostProcessor` to manipulate the name like this. Hope this helps.

```java
@Component
public class ConfigServerPostProcessor implements BeanPostProcessor {

    @Autowired
    private Environment environment;

    @Override
    public Object postProcessBeforeInitialization(final Object bean, final String beanName) throws BeansException {
        return bean;
    }

    @Override
    public Object postProcessAfterInitialization(final Object bean, final String beanName) throws BeansException {

        if (bean.getClass().isAssignableFrom(ConfigServerHealthIndicator.class)) {
            final Field envField = ReflectionUtils.findField(ConfigServerHealthIndicator.class, "env");
            envField.setAccessible(true);
            ReflectionUtils.setField(envField, bean, this.environment);

        }

        return bean;
    }
}
```

**Comment by dsyer** [comment]
@songyunlu I'm not sure how that solves any problems since the environment is already injected into the health indicator when it is created. If you think there's something that needs fixing, please open a new issue.

**Comment by heymysweetheart** [comment]
@dsyer With songyunlu's help, the Environment was injected successfully. But before that, the PropertitySources was empty from the Environment. Bellow is the debug pics.

**Before:**
![image](https://cloud.githubusercontent.com/assets/9413173/20387689/4b917fd0-acfc-11e6-9963-4efb0cbb4402.png)
![image](https://cloud.githubusercontent.com/assets/9413173/20387696/549cac9e-acfc-11e6-9687-69ac670ad08f.png)


**After:**
![image](https://cloud.githubusercontent.com/assets/9413173/20387591/caae247c-acfb-11e6-8f4d-2771d2358952.png)
