### ISSUE TITLE
restore useDefaultLabel parameter in ResourceController

### ISSUE THREAD

**Issue by alftheo** [spring-cloud/spring-cloud-config#1823]
**Is your feature request related to a problem? Please describe.**
The ability to fetch text files using /foo/default/file.txt?useDefaultLabel was removed as per https://github.com/spring-cloud/spring-cloud-config/issues/1643. This was a useful feature and in use in our environment

**Describe the solution you'd like**
Adding the same method with a more specific RequestMapping would make this work with new spring

**Describe alternatives you've considered**
At the moment I have a separate class with the above RequestMapping in my config server

**Additional context**
I have created pull request https://github.com/spring-cloud/spring-cloud-config/pull/1822 with the changes

**Comment by spencergibb** [comment]
Duplicates #1643
