### ISSUE TITLE
Spring Cloud Vault Client can't support login with version prefix.

### ISSUE THREAD

**Issue by iamjackhu** [spring-cloud/spring-cloud-config#1824]
When using spring cloud vault client to authenticate by AppRole, it will send request 'auth/approle/login' to Vault Service. But some service requires version, such as 'v1/auth/approle/login'.
And the class AppRoleAuthentication can't not inherited to overwrite the login path.

It's better to:
1. support v1 to login 
2. have the capability to overwrite the login path

**Comment by ryanjbaxter** [comment]
I just want to clarify, is this problem with Spring Cloud Config or Spring Cloud Vault?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
