### ISSUE TITLE
Map variables not deleting on remote refresh event

### ISSUE THREAD

**Issue by Munoon** [spring-cloud/spring-cloud-config#1825]
**Describe the bug**
When you want to remove some keys from key-value map in configuration, it not deleting on config clients.

**Sample**
[Sample Project (used in video bellow)](https://github.com/spring-cloud/spring-cloud-config/files/6097990/spring-cloud-config-map-refresh-bug.zip)

https://user-images.githubusercontent.com/43534008/110255420-4be72f80-7f9c-11eb-9a9b-faf2b515c8ce.mov

As you can see in the demo video, to reproduce bug I simple delete `a` variable and also add `c` variable (to make sure that we have the newest configuration version). Then, when I make request to see available variables, it returned all variables: `a`, `b` and `c`.

Interesting fact is that, if you use configuration file with name equals of spring application name this issue disappear.

**Comment by spencergibb** [comment]
We've had this discussion before. Please see the latest comment here https://github.com/spring-cloud/spring-cloud-commons/issues/818#issuecomment-696213968

Closing as duplicate.
