### ISSUE TITLE
Spring Cloud framework support for ARM architecture discussion

### ISSUE THREAD

**Issue by wbazmy** [spring-cloud/spring-cloud-config#1826]
In recent years, ARM architecture server has been more and more widely used in microservice development, some microservice frameworks have also provided support for ARM architecture, so now does Spring Cloud framework provide support for ARM architecture, if not, will there be any future migration plan?

**Comment by dantheperson** [comment]
Um... spring is a Java framework, and Java runs on ARM for a long time. Are you a ARM social media bot?

**Comment by spencergibb** [comment]
indeed we don't do anything jvm arch specific
