### ISSUE TITLE
Multiple application's secrets being loaded from Vault

### ISSUE THREAD

**Issue by mfmarlow** [spring-cloud/spring-cloud-config#1855]
**Describe the bug**
I have a Spring Cloud Config server backed by a HashiCorp Vault and a Git repo and two Spring Boot applications: **reservation-services** and **reservation-batch-services**. When I start **reservation-services** with the dev profile active, it correctly identifies and pulls in 
- reservation-services-dev.properties from the Git repo 
- reservation-services/dev secrets in Vault. 

and the application starts successfully.

However, when I start **reservation-batch-services**, it identifies and tries to use
- reservation-batch-services-dev.properties in Git
- reservation-batch-services/dev in Vault
- reservation-services/dev in Vault

and since they share similar properties, I'm assuming some are getting overwritten, which causes the app to not start successfully.

The reason this is my hypothesis is that I can see in the logs of **reservation-batch-services**:
`Converting PropertySource bootstrapProperties-vault:reservation-batch-services/dev [org.springframework.cloud.bootstrap.config.BootstrapPropertySource] to EncryptableEnumerablePropertySourceWrapper`
followed by
`Converting PropertySource bootstrapProperties-vault:reservation-services/dev [org.springframework.cloud.bootstrap.config.BootstrapPropertySource] to EncryptableEnumerablePropertySourceWrapper`

Am I breaking a naming convention by having the names of the apps so similar?

Spring Boot v2.3.9, SCS v3.1.6

**Comment by ryanjbaxter** [comment]
Yes I think using `-` in application names is going to be problematic since we use that as a profile separator.  I would remove the `-` from the name, I think that would solve the problem.

**Comment by mfmarlow** [comment]
> Yes I think using `-` in application names is going to be problematic since we use that as a profile separator. I would remove the `-` from the name, I think that would solve the problem.

I'm using `/` as the profile separator for the Vault configuration though. It seems to identify the Git repo correctly which does use `-` as a profile separator. I'll try renaming them with `_` instead of `-` and see if that helps.

**Comment by mfmarlow** [comment]
Looks like that fixed it. Thanks @ryanjbaxter!
