### ISSUE TITLE
Spring cloud config Server not able to clone to Persistent volume which is attached to Azure File Share. 

### ISSUE THREAD

**Issue by ramkrisz** [spring-cloud/spring-cloud-config#1869]
Hello Spring Cloud team,

We tried to config spring cloud config server with bit bucket as backend to server files. However , when trying to clone the git repository files to Persistent volume which is attached to Azure file share it is failing with error as mentioned below.
**Config Server not able to clone to Persistent volume which is attached to Azure File Share. 
Whereas manually cloning through Git CLI the repository is cloned, but when Spring Config Server pod gets deployed it is unable to clone the repository.**
We suspect that spring java code is not internally able to clone the repository.

**Please find the underlying infra details where the Config Serve pod is running.**

Platform: AKS cluster.
OS: ubuntu 18.04 SMB / CIFS  
kernel: 5.4.0-1043-azure

**Log:**
2021-04-22 13:28:37.678 ERROR 7 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[.[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [/v1/eapiconfigserver] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Cannot load environment] with root cause
java.nio.file.FileSystemException: /mnt/configrepo/.git/HEAD.lock.86526dbd7fde432bad43b4f38cfe7f12 -> /mnt/configrepo/.git/HEAD.lock: Operation not supported
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[na:1.8.0_181]
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_181]
at sun.nio.fs.UnixFileSystemProvider.createLink(UnixFileSystemProvider.java:476) ~[na:1.8.0_181]
at java.nio.file.Files.createLink(Files.java:1086) ~[na:1.8.0_181]

**Comment by Thiruvengadam** [comment]
I am also facing this issue in our project. can you please prioritize?

**Comment by aservera** [comment]
We are also facing this issue. It seems that SPring is taking the File System configuration where it¡s been executed, not from the drive the configuration is going to be stored locally, in our case we are using SMB 3.0 which is not fully compliant with Unix FS.

**Comment by FMartull** [comment]
Hi, this is very annoying and it would be very helpful if you guys can priorice this. Thanks!

**Comment by spencergibb** [comment]
I fail to see how this is a bug in spring cloud. Cloning is a function of jgit. The full stack trace would be helpful.

**Comment by FMartull** [comment]
Hi, Spencer is right. I don't request actions by your side. Thank you

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
