### ISSUE TITLE
Unable to read properties from local/remote git repo

### ISSUE THREAD

**Issue by agaikwad07-alt** [spring-cloud/spring-cloud-config#1883]
I am trying to setup a spring cloud config server to read from local or remote git repository. Followed all necessary steps but the URL, http://localhost:8888/bank-account-service/default to read from remote repository(https://github.com/briansjavablog/micro-services-spring-cloud-config
) and the URL, http://localhost:8888/limits-service/default to read from local git repo are returning 404 as below,

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Sun May 23 12:36:26 IST 2021
There was an unexpected error (type=Not Found, status=404).
No message available

Source code: https://github.com/agaikwad07-alt/spring-cloud-config.git
this code is for reading from local repository dir, D:\Learning\Microservices\git-localconfig-repo, where all changes are committed. Same result when tried to read from remote and changed application properties and added/changed below properties,

spring.cloud.config.server.git.uri=https://github.com/briansjavablog/micro-services-spring-cloud-config
spring.cloud.config.server.git.searchPaths=configuration

**Comment by agaikwad07-alt** [comment]
Facing this issue for different versions of spring boot and respective compatible version of spring cloud.

**Comment by agaikwad07-alt** [comment]
Same code is working on different system

**Comment by spencergibb** [comment]
If the same code is working on a different system, then it is something in the environment.
