### ISSUE TITLE
S3 bucket bug make it useless to use it as backend ! 

### ISSUE THREAD

**Issue by avnerstr** [spring-cloud/spring-cloud-config#1886]
I also see this problem. Is someone working to solve this bug ?! it's totally wrong behaviour and it's different than the git behaviour. Is there a workaround to this issue?

_Originally posted by @avnerstr in https://github.com/spring-cloud/spring-cloud-config/issues/1611#issuecomment-846594458_

**Comment by avnerstr** [comment]
This is not enhancement. Due to this bug, we can't work with the S3 bucket.

there is also stackoverflow issue about it:

[](https://stackoverflow.com/questions/61251423/cant-get-hierarchic-properties-by-s3-backend-spring-config-server)

**Comment by avnerstr** [comment]
https://stackoverflow.com/questions/61251423/cant-get-hierarchic-properties-by-s3-backend-spring-config-server

**Comment by jaganm2018** [comment]
Can you share sample code at least to read {application}-{profile}.properties/yml?. Thanks in advance. 

No proper documentation from spring team.

**Comment by ryanjbaxter** [comment]
Duplicate of  #1611
