### ISSUE TITLE
Still error when using Config Server Git Backend but OK with composite local file

### ISSUE THREAD

**Issue by hendisantika** [spring-cloud/spring-cloud-config#1893]
**Describe the bug**
I am trying to use Config Server Git Backend. But Still error when using Config Server Git Backend but OK with composite local file.

**Sample**
Here is the sample to reproduce --> https://gitlab.com/microservice-samples/micro-services-spring-cloud-config/configuration

**Comment by ryanjbaxter** [comment]
That is not a sample but a collection of yaml files

**Comment by hendisantika** [comment]
Oh Sorry. Here's the Config Server repo sample https://gitlab.com/microservice-samples/micro-services-spring-cloud-config/config-server

**Comment by ryanjbaxter** [comment]
That app starts fine (after adding the correct repositories to the pom)

**Comment by hendisantika** [comment]
I can't run that app with Git Backend. But If with Local file it is working well.

**Comment by ryanjbaxter** [comment]
Can you please provide a sample that reproduces the problem then?

**Comment by hendisantika** [comment]
I already put the sample above. But, OK I put it again here. Here's the Config Server repo sample https://gitlab.com/microservice-samples/micro-services-spring-cloud-config/config-server

**Comment by ryanjbaxter** [comment]
Again if I run that sample it does not show any kind of error.  Please provide a sample that does reproduce the error you are seeing.

**Comment by hendisantika** [comment]
Ooo sorry. 
Please uncomment line 4:
```
spring.application.name=config-server
server.port=8888
# URI of GIT repo containing properties
#spring.cloud.config.server.git.uri=https://gitlab.com/microservice-samples/micro-services-spring-cloud-config/configuration
```

For me error will occur like reported.

**Comment by ryanjbaxter** [comment]
I am not understanding what this has to do with a composite?  Can you provide the error you are seeing?

**Comment by hendisantika** [comment]
Oh sorry. I forgot to add the error logs:
```
Error occured cloning to base directory.

org.eclipse.jgit.api.errors.TransportException: https://gitlab.com/microservice-samples/micro-services-spring-cloud-config/configuration: 422 Unprocessable Entity
```

**Comment by ryanjbaxter** [comment]
Try setting the URL to `https://gitlab.com/microservice-samples/micro-services-spring-cloud-config/configuration.git`

**Comment by hendisantika** [comment]
It's working now. But previously I already add .git in the end of the git url but still failed. 

Thanks @ryanjbaxter
