### ISSUE TITLE
Explain the changes in the Bootstrap configuration in the docs

### ISSUE THREAD

**Issue by asaikali** [spring-cloud/spring-cloud-config#1894]
Given the change to how bootstrap processing works in 2020.x and Spring Boot 2.4 the docs should explain the change in a callout so that readers know that something important has changed that will break code. Maybe adding a callout in the [Client Side Usage](https://docs.spring.io/spring-cloud-config/docs/3.0.0/reference/html/#_client_side_usage) section explaining the changes from boot 2.3 to 2.4 will help a lot of users. For users migrating from 2.3 to 2.4 this is a common issue that trips up folks.

**Comment by spencergibb** [comment]
typically release notes are where upgrade instructions go.
