### ISSUE TITLE
Vault - An app by changing its app name can get secrets of another app

### ISSUE THREAD

**Issue by avnerstr** [spring-cloud/spring-cloud-config#1899]
**Describe the bug**
If I change in a client the application name I can get the secrets of another app. Seems like a major security bug.
Due to the nature of the current design, an app that is properly authenticated to Config Server, can by changing the app name, get the configuration of another another app.

**Comment by ryanjbaxter** [comment]
Duplicate of https://github.com/spring-cloud/spring-cloud-config/issues/1796
