### ISSUE TITLE
Add support for Apache MINA

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-config#1901]
see https://github.com/spring-cloud/spring-cloud-config/issues/1881#issuecomment-843231353

**Comment by SivaTharun** [comment]
@spencergibb can i work on this issue, i see that the above mentioned issues refer to replacing jsch library for apache MINA.

i see that jsch is being used for ssh session/file operations in the below files and their corresponding unit test classes.

- PropertyBasedSshSessionFactory.java
- PrivateKeyValidator.java
- PropertiesBasedSshTransportConfigCallback.java
- FileBasedSshTransportConfigCallback.java
- JGitEnvironmentRepository.java
