### ISSUE TITLE
always could not resolve placeholder 'testName' in value "${testName}"

### ISSUE THREAD

**Issue by krmao** [spring-cloud/spring-cloud-config#1905]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

I spent two days to use the library but always get the error, very hard to use felling.

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

code is here
[https://github.com/krmao/template/tree/master/service/springcloud](https://github.com/krmao/template/tree/master/service/springcloud)

config server is ok , and set testName in source bootstrap.yml is ok ,but set in github [https://github.com/krmao/springcloud-config-repo/tree/master/files](https://github.com/krmao/springcloud-config-repo/tree/master/files) always get the error,

- some one said shouldn't use *.yml, and should use *.properties [https://www.cnblogs.com/linliquan/p/13033238.html#4887396](https://www.cnblogs.com/linliquan/p/13033238.html#4887396)

I almost give up now! very sad!

![image](https://user-images.githubusercontent.com/7344437/121508534-4a545a00-ca18-11eb-8f40-5f8114350181.png)

![image](https://user-images.githubusercontent.com/7344437/121508562-4fb1a480-ca18-11eb-87df-800056a26169.png)

![image](https://user-images.githubusercontent.com/7344437/121508578-53ddc200-ca18-11eb-9c08-68f6a7c90709.png)

**Comment by ryanjbaxter** [comment]
This is not a minimal sample, please provide the simplest sample possible to reproduce the problem along with instructions on how to reproduce the problem with the sample.

**Comment by krmao** [comment]
After a restudy, it was found to be a problem with IntelliJ IDEA 2019.3,
Everything is OK while execute the command bellow by gradle:
```
./gradlew :app-b:clean :app-b:bootRun --info --stacktrace
```
