### ISSUE TITLE
Can spring.cloud.import in Environment or VM Option overwrite value in application.properties?

### ISSUE THREAD

**Issue by zhoufenqin** [spring-cloud/spring-cloud-config#1908]
**Is your feature request related to a problem? Please describe.**
When using `spring.cloud.config.uri`, if I rewrite the property in JVM Option or Environment Properties, then the value will overwrite the properties in `bootstrap.yml`.
After upgrading spring-boot to 2.5.0, I will use `spring.config.import` to replace `spring.cloud.config.uri`, but I find that if I add `spring.config.import` both in Environment or `application.properties`, the values will both be load and solved by `ConfigServerConfigDataLocationResolver`.  So is it by design?

**Describe the solution you'd like**
I hope that if I write the value in Environment, then the value can replace the value in `application.properties`

**Describe alternatives you've considered**

**Additional context**

**Comment by ryanjbaxter** [comment]
Can you try Spring Cloud 2021.0.6 or 2022.0.1?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
