### ISSUE TITLE
Could Not locate Property Source, 401 Unauthorized,  error encountered in spring config client app

### ISSUE THREAD

**Issue by SwapneelA** [spring-cloud/spring-cloud-config#1914]
I am getting could not locate property source, 401 UnAuthorized in ConfigServerConfigDataResource class of spring cloud config client.
I am getting this error when starting up config client application.

This was working for me earlier.
After changing Spring Boot version of my client config app from 2.2.7 to 2.4.5, this has stopped working.

I have also added below property in my application property file of config client app after changing to spring boot version 2.4.5

`spring.config.import=optional:configserver:https://myconfigserverurl`

Note: I have done no changes in Cloud Config Server. 
I am using cloud foundry's Config Server

**Comment by ryanjbaxter** [comment]
What do you mean by 
> I am using cloud foundry's Config Server

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by SwapneelA** [comment]
I am using Pivotal Cloud foundry config server.

I am creating config client spring boot app. After upgrading spring boot from 2.2.7 to 2.4.5 I am getting 401 Unauthorized when connecting to pivotal cloud foundry config server

**Comment by ryanjbaxter** [comment]
You should open a support ticket for your problem, this repo is only for the open source code.
