### ISSUE TITLE
Clarify Documentation On Composite Failures

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-config#1929]
https://github.com/spring-cloud/spring-cloud-config/issues/661 Fixed the issue with the entire composite failing, however there is still a note in the documentation stating if one repo fails the whole composite fails.  We need to document that if you don't want that behavior you need to set `spring.cloud.config.server.failOnCompositeError` to `false`.

**Comment by halcyon22** [comment]
Hi @ryanjbaxter - this looks like the last issue going into 3.0.5; is that true? I'm waiting for #1895 to be released before upgrading Spring Boot and moving to Java 16. We can switch to the milestone repo, but I'd like to avoid it if 3.0.5 will be out soon. Thanks for all your work!

**Comment by ryanjbaxter** [comment]
Tentative release dates can be found here https://github.com/spring-cloud/spring-cloud-release/milestones
