### ISSUE TITLE
Decide on the right central configuration solution

### ISSUE THREAD

**Issue by avnerstr** [spring-cloud/spring-cloud-config#1941]
I'm trying to understand what is the best solution and pros and cons for central configuration

1. Spring cloud config
2. Spring Cloud Kubernetes ConfigMaps

If we are running on k8s what is the best solution between the two?

Please advice. 

Thanks,
Avner

**Comment by ryanjbaxter** [comment]
It is hard to say, it depends on your application.  From a Spring Cloud perspective we don't have a preference, both will work.

**Comment by avnerstr** [comment]
I think I found a clear Pros in favour of Spring Cloud Config.
In case I want to have a shared configuration between different microservices running on different accounts
I think you can't do it with Config Maps 

For example, we have a scenario when we have configurations like core services urls that all the services needs.

One more question, there is no plan to deprecate the Cloud Config Service, although there are couple of other solutions, right?

**Comment by ryanjbaxter** [comment]
There are no plans to deprecate this project, no.
