### ISSUE TITLE
I'm wondering why git default branch doesn't change "master" to "main"

### ISSUE THREAD

**Issue by BryceYangS** [spring-cloud/spring-cloud-config#1942]
Hi. I'm studying spring cloud. and I've used spring-cloud-config-server. I knew git deafult branch of spring-cloud-config-server is a "master".
I heard many git platforms(Github, GitLab) are changing default branch to "main" .
so, how about changing default branch setting to "main"?
If I miss some reasons, I'm sorry about it. and If you notice that reasons, It will help my studying.
Thanks for reading this report!

**Comment by ryanjbaxter** [comment]
See https://github.com/spring-cloud/spring-cloud-config/issues/1722
