### ISSUE TITLE
How to push to this spring-cloud-config repo?

### ISSUE THREAD

**Issue by marnee01** [spring-cloud/spring-cloud-config#1945]
This is probably not the right place for this question. Please let me know if there is a different approach I should take.

I want to push changes to this repo for Issue #1845. I have a github account (obviously). When I try to push, git pops up a github login screen. I enter my username and password, but authentication fails, as per the message at the commandline:

```
Logon failed, use ctrl+c to cancel basic credential prompt.
```

Git then prompts for username at the commandline. After I enter, it logs another error. 

I have logged out and back in to verify username and password are correct. (I also tried email address for the username.)

This would be my first time pushing to an open source project in github. **Is there some special step I need to take?** (I thought it was open to anyone to submit a pull request.) I did try to follow the steps in the readme. I didn't see anything regarding requiring special permission.

This is the entire commandline output:

```
UPINCMA@BGTMNWL-JY7ZNC2 MINGW64 ~/git/3rdParty/spring-cloud-config (feature/marnee01/gh-1845/AddMultipleUriStrategy)
$ git push --set-upstream origin feature/marnee01/gh-1845/AddMultipleUriStrategy
Logon failed, use ctrl+c to cancel basic credential prompt.
Username for 'https://github.com': marneederider40@gmail.com
remote: Permission to spring-cloud/spring-cloud-config.git denied to marnee01.
fatal: unable to access 'https://github.com/spring-cloud/spring-cloud-config.git/': The requested URL returned error: 403

```
**Additional Notes**
* I cloned this repo yesterday.
* I created my branch from branch `main`

**Edit**
I also tried logging in via IntelliJ using a github-generated token. I saw 

```
remote: Permission to spring-cloud/spring-cloud-config.git denied to marnee01.
fatal: unable to access 'https://github.com/spring-cloud/spring-cloud-config.git/': The requested URL returned error: 403
```

**Comment by hpoettker** [comment]
@marnee01 You need to fork the repository. The corresponding button is in the top right corner. Afterwards you can push your branch to `https://github.com/marnee01/spring-cloud-config.git`. Then, you can open a pull request against the main branch of this repository.

**Comment by marnee01** [comment]
Thank you! I will try this tomorrow.
