### ISSUE TITLE
Add Company Image In Email Template

### ISSUE THREAD

**Issue by nishantpandya** [spring-cloud/spring-cloud-config#195]
There is a nice facility in IOMAD that as per company we can update the email templates from IOMAD -> Course Management -> Email Templates. 

If we want to send the email from one company manager of one company so they can change content as per there requirement.

Now I want to add the Image on the email template. So when admin / company manager create there employee then they will get there company logo on email.

How can I do this. Please help.
Thanks
Nishant

**Comment by dsyer** [comment]
I don't think this is a Spring Cloud question, is it?

**Comment by nishantpandya** [comment]
So sorry @dsyer . Actually I have post IOMAD query on spring-cloud. 
Please remove this query from here.
