### ISSUE TITLE
spring-cloud-config-server-3.0.4.jar || could not pull private github repo with valid github credential

### ISSUE THREAD

**Issue by mrinalsunny** [spring-cloud/spring-cloud-config#1954]
> Spring Boot 2.5.4 and Spring Cloud 2020.0.3

> Boot Project: https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.5.4&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=actuator,cloud-config-server

> **org.eclipse.jgit.api.errors.TransportException: https://github.com/***/***: not authorized**
> Is this a known bug in v3.0.4? Or am I missing any configuration?

> **application.properties**
> server.port=8888
>  
> spring.application.name=configserver
> spring.cloud.config.server.git.basedir=config
> spring.cloud.config.server.git.uri=https://github.com/***/***
> spring.cloud.config.server.git.default-label=main
> spring.cloud.config.server.git.username=*********
> spring.cloud.config.server.git.password=*********
> spring.cloud.config.server.git.skip-ssl-validation=TRUE
> spring.cloud.config.server.git.ignore-local-ssh-settings=TRUE
> spring.cloud.config.server.git.force-pull=TRUE
> spring.cloud.config.server.git.strict-host-key-checking=FALSE
> 
> management.endpoints.web.exposure.include=*

> **Error**
>   .   ____          _            __ _ _
>  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
> ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
>  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
>   '  |____| .__|_| |_|_| |_\__, | / / / /
>  =========|_|==============|___/=/_/_/_/
> [32m :: Spring Boot :: [39m              [2m (v2.5.4)[0;39m
> 
> [2m2021-08-23 01:52:50.495[0;39m [32m INFO[0;39m [35m440[0;39m [2m---[0;39m [2m[           main][0;39m [36mc.example.demo.ConfigServer2Application [0;39m [2m:[0;39m Starting ConfigServer2Application using Java 16.0.1 on ****-PC with PID 440 (D:\***\***\***\*** started by ***in D:\***\***)
> [2m2021-08-23 01:52:50.497[0;39m [32m INFO[0;39m [35m440[0;39m [2m---[0;39m [2m[           main][0;39m [36mc.example.demo.ConfigServer2Application [0;39m [2m:[0;39m No active profile set, falling back to default profiles: default
> [2m2021-08-23 01:52:51.374[0;39m [32m INFO[0;39m [35m440[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.cloud.context.scope.GenericScope    [0;39m [2m:[0;39m BeanFactory id=e5c663b3-86a7-3f7d-9537-4734f8658f1a
> [2m2021-08-23 01:52:51.615[0;39m [32m INFO[0;39m [35m440[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.b.w.embedded.tomcat.TomcatWebServer [0;39m [2m:[0;39m Tomcat initialized with port(s): 8888 (http)
> [2m2021-08-23 01:52:51.624[0;39m [32m INFO[0;39m [35m440[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.apache.catalina.core.StandardService  [0;39m [2m:[0;39m Starting service [Tomcat]
> [2m2021-08-23 01:52:51.624[0;39m [32m INFO[0;39m [35m440[0;39m [2m---[0;39m [2m[           main][0;39m [36morg.apache.catalina.core.StandardEngine [0;39m [2m:[0;39m Starting Servlet engine: [Apache Tomcat/9.0.52]
> [2m2021-08-23 01:52:51.722[0;39m [32m INFO[0;39m [35m440[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.a.c.c.C.[Tomcat].[localhost].[/]      [0;39m [2m:[0;39m Initializing Spring embedded WebApplicationContext
> [2m2021-08-23 01:52:51.722[0;39m [32m INFO[0;39m [35m440[0;39m [2m---[0;39m [2m[           main][0;39m [36mw.s.c.ServletWebServerApplicationContext[0;39m [2m:[0;39m Root WebApplicationContext: initialization completed in 1184 ms
> [2m2021-08-23 01:52:52.681[0;39m [32m INFO[0;39m [35m440[0;39m [2m---[0;39m [2m[on(1)-127.0.0.1][0;39m [36mo.a.c.c.C.[Tomcat].[localhost].[/]      [0;39m [2m:[0;39m Initializing Spring DispatcherServlet 'dispatcherServlet'
> [2m2021-08-23 01:52:52.681[0;39m [32m INFO[0;39m [35m440[0;39m [2m---[0;39m [2m[on(1)-127.0.0.1][0;39m [36mo.s.web.servlet.DispatcherServlet       [0;39m [2m:[0;39m Initializing Servlet 'dispatcherServlet'
> [2m2021-08-23 01:52:52.938[0;39m [32m INFO[0;39m [35m440[0;39m [2m---[0;39m [2m[on(1)-127.0.0.1][0;39m [36mo.s.b.a.e.web.EndpointLinksResolver     [0;39m [2m:[0;39m Exposing 15 endpoint(s) beneath base path '/actuator'
> [2m2021-08-23 01:52:52.947[0;39m [32m INFO[0;39m [35m440[0;39m [2m---[0;39m [2m[on(1)-127.0.0.1][0;39m [36mo.s.web.servlet.DispatcherServlet       [0;39m [2m:[0;39m Completed initialization in 266 ms
> [2m2021-08-23 01:52:53.049[0;39m [32m INFO[0;39m [35m440[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.b.w.embedded.tomcat.TomcatWebServer [0;39m [2m:[0;39m Tomcat started on port(s): 8888 (http) with context path ''
> [2m2021-08-23 01:52:53.446[0;39m [32m INFO[0;39m [35m440[0;39m [2m---[0;39m [2m[           main][0;39m [36mc.example.demo.ConfigServer2Application [0;39m [2m:[0;39m Started ConfigServer2Application in 3.75 seconds (JVM running for 4.448)
> [2m2021-08-23 01:52:59.700[0;39m [33m WARN[0;39m [35m440[0;39m [2m---[0;39m [2m[nio-8888-exec-2][0;39m [36m.c.s.e.MultipleJGitEnvironmentRepository[0;39m [2m:[0;39m Error occured cloning to base directory.
> 
> org.eclipse.jgit.api.errors.TransportException: https://github.com/***/***: not authorized
> 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:254) ~[org.eclipse.jgit-5.1.3.201810200350-r.jar:5.1.3.201810200350-r]
> 	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:306) ~[org.eclipse.jgit-5.1.3.201810200350-r.jar:5.1.3.201810200350-r]
> 	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:200) ~[org.eclipse.jgit-5.1.3.201810200350-r.jar:5.1.3.201810200350-r]
> 	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.cloneToBasedir(JGitEnvironmentRepository.java:612) ~[spring-cloud-config-server-3.0.4.jar:3.0.4]
> 	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.copyRepository(JGitEnvironmentRepository.java:587) ~[spring-cloud-config-server-3.0.4.jar:3.0.4]
> 	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.createGitClient(JGitEnvironmentRepository.java:570) ~[spring-cloud-config-server-3.0.4.jar:3.0.4]
> 	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.refresh(JGitEnvironmentRepository.java:267) ~[spring-cloud-config-server-3.0.4.jar:3.0.4]
> 	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.getLocations(JGitEnvironmentRepository.java:245) ~[spring-cloud-config-server-3.0.4.jar:3.0.4]
>

**Comment by ryanjbaxter** [comment]
Its not a known issue.  And without a way to reproduce it I am not sure how we can help.

**Comment by mrinalsunny** [comment]
> Its not a known issue. And without a way to reproduce it I am not sure how we can help.

Thanks @ryanjbaxter I will provide the replication steps. As of now I have added the Spring Initializr link which has the required dependencies. Basically I am trying a bare minimum configuration to pull private github repo where exists a properties file.

**Comment by mrinalsunny** [comment]
I have resolved this problem, its a github side issue. GitHub login password didn't provide me any authorization to access private repo, I had to create a **Personal access tokens** at **GitHub/Settings/Developer settings** and updated **spring.cloud.config.server.git.password** with the **access token**. Now I can fetch data from github repo.

**Comment by mrinalsunny** [comment]
Closing this reported bug as there is no issue to spring-cloud-config-server-3.0.4.jar
