### ISSUE TITLE
Connection refused (Connection refused)

### ISSUE THREAD

**Issue by govardhanaraoganji** [spring-cloud/spring-cloud-config#1959]
**Bug Description**
Hello Guys, I am using config service to get configs from Github for my service on cloud foundry but I am getting the below error and It is working with same configuration on my machine.

HTTP Basic authentication is working on both cloud & local machines with the configuration like, https://cloud.spring.io/spring-cloud-config/reference/html/#_authentication
 
Could you guys please help me where I am doing wrong?

I am using the below configuration like https://cloud.spring.io/spring-cloud-config/reference/html/#_git_ssh_configuration_using_properties

**ERROR**
11:36:48.983: [APP/PROC/WEB.0] 2021-09-02 09:36:48.973  WARN 7:3e7e10f3-bcef-4b52-655c-414c:c30bef509fd3a980327f468b0f968002:::: --- [nio-8080-exec-6] .c.s.e.MultipleJGitEnvironmentRepository : Error occured cloning to base directory.
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
11:36:48.983: [APP/PROC/WEB.0] org.eclipse.jgit.api.errors.TransportException: git@github.com:*configuration.git: Connection refused (Connection refused)
11:36:48.983: [APP/PROC/WEB.0] 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:254)
11:36:48.983: [APP/PROC/WEB.0] 	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:306)
11:36:48.983: [APP/PROC/WEB.0] 	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:200)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.cloneToBasedir(JGitEnvironmentRepository.java:616)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.copyRepository(JGitEnvironmentRepository.java:591)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.createGitClient(JGitEnvironmentRepository.java:574)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.refresh(JGitEnvironmentRepository.java:270)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.getLocations(JGitEnvironmentRepository.java:248)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.getLocations(MultipleJGitEnvironmentRepository.java:146)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.cloud.config.server.environment.AbstractScmEnvironmentRepository.findOne(AbstractScmEnvironmentRepository.java:57)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.findOne(MultipleJGitEnvironmentRepository.java:187)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.cloud.config.server.environment.CompositeEnvironmentRepository.findOne(CompositeEnvironmentRepository.java:67)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.cloud.config.server.config.ConfigServerHealthIndicator.doHealthCheck(ConfigServerHealthIndicator.java:73)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.boot.actuate.health.HealthIndicator.getHealth(HealthIndicator.java:37)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.getHealth(HealthEndpointWebExtension.java:85)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.getHealth(HealthEndpointWebExtension.java:44)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:99)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateHealth(HealthEndpointSupport.java:110)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:96)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:74)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:61)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.health(HealthEndpointWebExtension.java:71)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.health(HealthEndpointWebExtension.java:60)
11:36:48.983: [APP/PROC/WEB.0] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:36:48.983: [APP/PROC/WEB.0] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
11:36:48.983: [APP/PROC/WEB.0] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
11:36:48.983: [APP/PROC/WEB.0] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:77)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$ServletWebOperationAdapter.handle(AbstractWebMvcEndpointHandlerMapping.java:305)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(AbstractWebMvcEndpointHandlerMapping.java:388)
11:36:48.983: [APP/PROC/WEB.0] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:36:48.983: [APP/PROC/WEB.0] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
11:36:48.983: [APP/PROC/WEB.0] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
11:36:48.983: [APP/PROC/WEB.0] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
11:36:48.983: [APP/PROC/WEB.0] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
11:36:48.983: [APP/PROC/WEB.0] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
11:36:48.983: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
11:36:48.983: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
11:36:48.983: [APP/PROC/WEB.0] 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
11:36:48.983: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
11:36:48.983: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
11:36:48.983: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
11:36:48.983: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
11:36:48.983: [APP/PROC/WEB.0] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
11:36:48.983: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
11:36:48.984: [APP/PROC/WEB.0] 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
11:36:48.984: [APP/PROC/WEB.0] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
11:36:48.984: [APP/PROC/WEB.0] 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
11:36:48.984: [APP/PROC/WEB.0] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
11:36:48.984: [APP/PROC/WEB.0] 	at com.vw.odp.cte.multitenancy.ce_project.CeProjectContextServletFilter.doFilter(CeProjectContextServletFilter.java:44)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
11:36:48.984: [APP/PROC/WEB.0] 	at com.vw.odp.cte.multitenancy.ce_tenant.MdcTenancyServletFilter.doFilter(MdcTenancyServletFilter.java:27)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
11:36:48.984: [APP/PROC/WEB.0] 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
11:36:48.984: [APP/PROC/WEB.0] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
11:36:48.984: [APP/PROC/WEB.0] 	at org.cloudfoundry.router.ClientCertificateMapper.doFilter(ClientCertificateMapper.java:79)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
11:36:48.984: [APP/PROC/WEB.0] 	at com.vw.odp.cte.logging.instrumentation.servlet.NewRelicHttpCorrelationServletFilter.doFilter(NewRelicHttpCorrelationServletFilter.java:33)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
11:36:48.984: [APP/PROC/WEB.0] 	at com.vw.odp.cte.multitenancy.running_context.RunningContextServletFilter.doFilter(RunningContextServletFilter.java:27)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
11:36:48.984: [APP/PROC/WEB.0] 	at com.vw.odp.cte.multitenancy.ce_tenant.CeTenantContextServletFilter.doFilter(CeTenantContextServletFilter.java:28)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
11:36:48.984: [APP/PROC/WEB.0] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
11:36:48.984: [APP/PROC/WEB.0] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
11:36:48.984: [APP/PROC/WEB.0] 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
11:36:48.984: [APP/PROC/WEB.0] 	at java.base/java.lang.Thread.run(Unknown Source)
11:36:48.984: [APP/PROC/WEB.0] Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:*configuration.git: Connection refused (Connection refused)
11:36:48.984: [APP/PROC/WEB.0] 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:190)
11:36:48.984: [APP/PROC/WEB.0] 	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:140)
11:36:48.984: [APP/PROC/WEB.0] 	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:280)
11:36:48.984: [APP/PROC/WEB.0] 	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:170)
11:36:48.984: [APP/PROC/WEB.0] 	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:137)
11:36:48.984: [APP/PROC/WEB.0] 	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:123)
11:36:48.984: [APP/PROC/WEB.0] 	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1271)
11:36:48.984: [APP/PROC/WEB.0] 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:243)
11:36:48.984: [APP/PROC/WEB.0] 	... 133 common frames omitted
11:36:48.984: [APP/PROC/WEB.0] Caused by: com.jcraft.jsch.JSchException: java.net.ConnectException: Connection refused (Connection refused)
11:36:48.984: [APP/PROC/WEB.0] 	at com.jcraft.jsch.Util.createSocket(Util.java:394)
11:36:48.984: [APP/PROC/WEB.0] 	at com.jcraft.jsch.Session.connect(Session.java:215)
11:36:48.984: [APP/PROC/WEB.0] 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:146)
11:36:48.984: [APP/PROC/WEB.0] 	... 140 common frames omitted
11:36:48.984: [APP/PROC/WEB.0] Caused by: java.net.ConnectException: Connection refused (Connection refused)
11:36:48.984: [APP/PROC/WEB.0] 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
11:36:48.984: [APP/PROC/WEB.0] 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
11:36:48.984: [APP/PROC/WEB.0] 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
11:36:48.984: [APP/PROC/WEB.0] 	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
11:36:48.984: [APP/PROC/WEB.0] 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
11:36:48.984: [APP/PROC/WEB.0] 	at java.base/java.net.Socket.connect(Unknown Source)
11:36:48.984: [APP/PROC/WEB.0] 	at java.base/java.net.Socket.connect(Unknown Source)
11:36:48.984: [APP/PROC/WEB.0] 	at java.base/java.net.Socket.<init>(Unknown Source)
11:36:48.984: [APP/PROC/WEB.0] 	at java.base/java.net.Socket.<init>(Unknown Source)
11:36:48.984: [APP/PROC/WEB.0] 	at com.jcraft.jsch.Util$1.run(Util.java:362)
11:36:48.984: [APP/PROC/WEB.0] 	... 1 common frames omitted

**Comment by ryanjbaxter** [comment]
There is not really much to go off of in that stacktrace.  The one thing I would try is to try to clone a public repo from CloudFoundry.

**Comment by govardhanaraoganji** [comment]
Thank you for the update.

We have firewall for outgoing calls on our cloud foundry which is blocking the connection. We have achieved it by enabling the TCP proxy for the service and used the proxy URL for connecting the `github.com`.
