### ISSUE TITLE
Spring cloud bus refresh doesnt work with local repository

### ISSUE THREAD

**Issue by samarth274** [spring-cloud/spring-cloud-config#196]
Hello,

I am working on microservices using spring-cloud and I find it interesting. I am exploring cloud-bus feature of spring-cloud. I have added this dependency at both the client and the config-server:

compile("org.springframework.cloud:spring-cloud-starter-bus-amqp:1.0.0.RC1")

I have included @RefreshScope at the client end.

I configured my local repository by using spring.platform.config.server.uri: file:/Users/samarth1/git/cloud-config-repo. And now, I modify a property in my config-server and do a refresh by using:

curl -X POST http://localhost:8080/bus/refresh

I want property changes to be reflected in my client. But, it throws an error in config-server.

Here is the client and config-server log:

Client:

2015-07-20 11:26:41.832  INFO 76569 --- [qtp697240075-21] o.s.cloud.bus.event.RefreshListener      : Received remote refresh request. Keys refreshed []

Config-server:

2015-07-20 11:27:11.050  WARN 76549 --- [qtp100393301-19] o.s.c.c.s.JGitEnvironmentRepository      : Remote repository not available
2015-07-20 11:27:11.088  INFO 76549 --- [qtp100393301-19] o.s.boot.SpringApplication               : Starting application on Samarths-MacBook-Pro.local with PID 76549 (/Users/samarth1/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot/1.3.0.BUILD-SNAPSHOT/6a96a86171a7b349e4788a3f65ea1af548f902d8/spring-boot-1.3.0.BUILD-SNAPSHOT.jar started by samarth1 in /Users/samarth1/git/configuration/server)

Now I am wondering whether spring-cloud-bus-refresh works well with local repositories?

@dsyer : please help?

**Comment by dsyer** [comment]
I suggest you update to a more recent version than a release candidate from several months ago. You are also using Spring Boot 1.3 snapshots, which means you probably want the 1.1.0 snapshots for Spring Cloud bits, but beware as they are quite unstable currently. Stick to Spring Cloud Angel.SR3 and you should be fine. Also read the user guide again because there are no config properties called `spring.platform.*` any more (not since before the 1.0 milestones).

**Comment by samarth274** [comment]
@dsyer : Thanks for the quick response. I followed your suggestion and updated snapshots of my spring cloud libraries to Angel.SR3. Now I am facing a new issue on the client side. Looks like the basic functionity of autowiring dependecnies is not working:

Below is the attached snapshot on the config-server side. The same has been copied on the client side
<img width="1440" alt="screen shot 2015-07-20 at 2 55 38 pm" src="https://cloud.githubusercontent.com/assets/12155086/8784372/b8e07a8c-2eef-11e5-8e30-12d55fca053c.png">

However, after this modification, I am unable to wire dependencies on the client side. Can u please figure the solution for this?

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.Config': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.lang.String com.securityscorecard.client.Config.SAMPLE; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'SAMPLE' in string value "${SAMPLE}"

**Comment by dsyer** [comment]
I'm sorry, but there isn't enough information here. I think it would help if you go and do some studying on your own - look at the sample apps and the user guide - and try again, a bit more methodically.

**Comment by samarth274** [comment]
@dsyer . Thanks for your help. I carefully followed the steps and the sample apps available. It turned out that I had included an additional jar in my Gradle file. Removing that library made my application work.

**Comment by dsyer** [comment]
Cool. Glad to hear it.
