### ISSUE TITLE
Property files are skipped during the bootstrap process

### ISSUE THREAD

**Issue by thundur** [spring-cloud/spring-cloud-config#1974]
**Describe the bug**
I have a project that uses bootstrapping. Since spring-cloud-config 3.0.5, property files defined outside of the deliverable (jar or war) are no longer added as a property source. In spring-cloud-config 3.0.4, this was still working.

**Sample**
See next comment

It was introduced by #1904.

I debugged the differences, and the problem occurs in the `clean()` method in `NativeEnvironmentRepository`. This method calls a new private method called `matchesLocations`. This method loops over some configuration patterns, but in the final if in this loop, there is always a return statement, which means that if the property source could not be found in the first pattern (`classpath:/` in my case), false is returned, instead of the loop continuing to the next pattern, where a match still could be found.

Instead of always returning here, we should only return if the result of the pipeline is `true`.

**Comment by nickcaballero** [comment]
Running into the same issue. We use `spring.config.import` to incorporate shared property files. However, the imported files fail the `matchesLocation` test and are ignored. As @thundur pointed out, it's because `matchesLocations` exits early instead of testing all possible location patterns.

**Comment by thundur** [comment]
@ryanjbaxter, @spencergibb, @philwebb this issue is ignored since I created it. What is required for me to do so you would take a look?

**Comment by ryanjbaxter** [comment]
Sorry for the delay here.  I am still on vacation but I believe the code causing the problem was changed (fixed?) here
https://github.com/spring-cloud/spring-cloud-config/commit/4636ddb3b5aaf15a843581844bd6bf709c7fa3ee#diff-6e42942d6c70c5ad5dbf7bf796155f22e6dd24a953694cf090fcf087051add1e

Have you tried 3.0.6?

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
