### ISSUE TITLE
spring.cloud.config.label doesn't work

### ISSUE THREAD

**Issue by Surrin1999** [spring-cloud/spring-cloud-config#1976]
**Describe the bug**
My version is **3.0.5.** when i set spring.cloud.config.label=dev，the default value of **{label}** in uri has not changed
![image](https://user-images.githubusercontent.com/37960540/136664875-0f092e5c-46ce-4bbc-8188-f75fb985c8ba.png)

I have posted the problem to stackoverflow,see more detai:https://stackoverflow.com/questions/69508069/what-does-the-property-spring-cloud-config-label-in-spring-cloud-config-do,  and i will be tomorrow Submit the code to https://gitee.com/surrin1999/spring-cloud---learning.git

**Comment by ryanjbaxter** [comment]
Seems like you got your answer on SO.
