### ISSUE TITLE
Order not followed for AWSSecretsManager With Other Repositories in Spring Config Server

### ISSUE THREAD

**Issue by knvs97** [spring-cloud/spring-cloud-config#1980]
Currently when trying to configure multiple repositories in spring config server along with AWSSecretsManager, the order specified for the AWSSecretsManager is not followed.

Version : v3.1.0-M2 
Module :  Spring-Cloud-Config-Server

Config : 
`
spring:
  application:
    name: Config-Server
  profiles:
    active:  native,awssecretsmanager
  cloud:
    config:
      server:
        aws-secretsmanager:
          region: ap-south-1
          prefix: secrets/app
          order: 2
        native:
          order: 1
          searchLocations: file://${user.home}/Workspace/Config
`

SecretManagerRepository:
<img width="773" alt="SecretsManager" src="https://user-images.githubusercontent.com/9269084/137288040-154f8235-2c8e-496e-91cf-1e79400f801e.png">

NativeRepository:
<img width="903" alt="Screenshot 2021-10-14 at 2 42 56 PM" src="https://user-images.githubusercontent.com/9269084/137288082-7fc83ffb-24ff-4881-b881-fadf64cff11c.png">

This is causing the order defined for the awssecretmanager to be ignored, and not work as expected.
Is there any reason for not extending Ordered for 'AwsSecretsManagerEnvironmentRepository'?

**Comment by knvs97** [comment]
Also wanted to point it out, there were some other profiles where order was not supported in like AwsParameterStoreEnvironmentRepository, CompositeEnvironmentRepository, CredhubEnvironmentRepository, GoogleSecretManagerEnvironmentRepository, JGitEnvironmentRepository, RedisEnvironmentRepository. 
It appears like a bug. Can you confirm @ryanjbaxter

**Comment by ryanjbaxter** [comment]
Not sure if all of them makes sense.  Particularly `JGitEnvironmentRepository` extends `AbstractScmEnvironmentRepository` so it implements `Ordered`.  I am unsure if it makes sense for `CompositeEnvironmentRepository` to implement `Ordered` because it is the one leveraging the `Ordered` interface.  Sounds like maybe the others should.

**Comment by knvs97** [comment]
Yeah JGitEnvironmentRepository, CompositeEnvironmentRepository need not extend Ordered. Others do. Do you want me to make the changes for the above discussed in the same PR?

**Comment by ryanjbaxter** [comment]
Sure.
