### ISSUE TITLE
Spring cloud config server on refresh -> logback config also refresh automatically

### ISSUE THREAD

**Issue by fuzzy28** [spring-cloud/spring-cloud-config#1993]
I can't find any existing article/documentation related to this. The spring cloud config server and logback XML configuration are working in harmony, whenever I change something in my git repo config and trigger refresh of my application, somehow the logback automatically gets updated even though the logback is not in the config server but in the jar file itself.

Basically, my configuration is something like this:

I have an SMTP appender in my logback XML, at startup I'm checking if the enableSMTP is enabled, then I only set the recipient.

    <if condition='property("smtpEnabled").equals("true")'>
        <then>
            <to>to@to.com</to>
        </then>
    </if>
This is to prevent email sending if the property is disabled, then I'm setting it back programmatically, ideally in EnvironmentChangeEvent. However, changing the property in the config server and calling the /monitor endpoint from the spring cloud config server automatically sets this value in logback without programmatically setting it through the event handler.

Is this behavior of environment change and auto reconfigure of logback expected? (note that logback scan is disabled)

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
