### ISSUE TITLE
Configuration on types of files to look at for the storage backend

### ISSUE THREAD

**Issue by cmdub** [spring-cloud/spring-cloud-config#2002]
Hi,

Is there a specific configuration that can be utilized to make the config server more efficient in finding the associated configuration files in the storage backend? Currently, when a call comes in to: http://configServer:/serviceName/default the configServer will look for all different types of files in different extensions and naming formats before arriving at the file schema I'm currently using. Currently, I have all of the settings files stored in this format: serviceName.yml

This means that configService will look for serviceName-default.json / serviceName-default.properties / serviceName.json / serviceName.properties before finally arriving at serviceName.yml

This is pretty inefficient, and it also causes a litany of exceptions to be logged within our APM tool (AppDynamics)

Can we specify a setting to only look for a certain file extension and only in a specific naming schema?

**Comment by ryanjbaxter** [comment]
No not currently

**Comment by ryanjbaxter** [comment]
I could see maybe making things more specific, but this has been the way the config server has functioned for a while now (although I have not verified it) and this is the first time I am hearing about this.  Lets see if the community things it is a worth while enhancement.

**Comment by spring-cloud-issues** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
