### ISSUE TITLE
BindableProxyFactory not inject in FunctionConfiguration#afterPropertiesSet  after adding spring-boot-starter-web-services

### ISSUE THREAD

**Issue by amiraziz** [spring-cloud/spring-cloud-config#2008]
Hi, I'm using spring cloud version 2020.0.4 and spring-boot-starter-parent 2.5.7.

in my sample located in [github ](https://github.com/amiraziz/spring-stream-rabbitMq), i'm trying to use `spring-boot-starter-web-services` after adding basic spring cloud dependencies. but after adding that, no queue was created.

i try to debug and only thing that i found is when program reach to `FunctionConfiguration#afterPropertiesSet` , `BindableProxyFactory`  beans of type array is empty after i add `spring-boot-starter-web-services`.

Where is the mistake?

and my stackoverflow [post](https://stackoverflow.com/questions/70083799) about this issue

**Comment by amiraziz** [comment]
I found this `spring.cloud.function.definition` property for define a function for creating queue. but i need know 
 how can automatically create queues in modules more than one function with this type of definition?

**Comment by ryanjbaxter** [comment]
This does not seem related to spring cloud config

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
