### ISSUE TITLE
MinIO as s3 implementation - how do you do it?

### ISSUE THREAD

**Issue by avogt-sundn** [spring-cloud/spring-cloud-config#2019]
**Describe the bug**
I had 'aws3' profile activated, and als implemented the hook that. allows me to address localhost minio:

```

    @Primary
    @Bean
    public AmazonS3 amazonS3Client() {
        return AmazonS3ClientBuilder
                .standard()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(endpoint, region))
                .withCredentials(new AWSStaticCredentialsProvider(
                        new BasicAWSCredentials(awsAccessKey, awsSecretKey)))
                .build();
    }
```

when spring is booting, i get this error 
```
java.lang.IllegalStateException: Failed to load ApplicationContext
...
Caused by: java.lang.IllegalStateException: There is no EC2 meta data available, because the application is not running in the EC2 environment. Region detection is only possible if the application is running on a EC2 instance
```

**Sample**
use this project, branch minio and run tests to reproduce 
https://gitlab.com/avogt-sundn/spring-cloud-config-example/-/commits/minio

**Comment by ryanjbaxter** [comment]
Can you please try with Spring Cloud 2020.0.4 or 2021.0.0?

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
