### ISSUE TITLE
Decrypt fail when the encrypted text is 32 chars long

### ISSUE THREAD

**Issue by kwongpan** [spring-cloud/spring-cloud-config#202]
Example:

curl http://localhost:8888/encrypt -d abcdefghijklmnopqrstuvwxyz123456 -u user:password
AQCJdqQkxDIaJvWXrPMk9oHdFN7TTXaXpBWe7kuMBIjYXVJ5tCAxvWbdyAzjfAybdPwFa9AstoRWx2MNfqXAEIX0798cWbmPh7zKPwlAj+SeMGogm795CYBsNt+e2oiZ7PqLFUoIs1RV7+0uem/PAPgmbJvaNrOvZ85HZp+NRLcl7+JlkkVFESoYV/4mzSIWxjBs0cfiZw7tp+aJWQR6XKSVkPLdyqvlTpGaA4pY694+Y/y6c+FEM4V/kLI61RsQ46p9e+kpOevM04Hk4tWeK7ksXPUccQ+jbhXd6svARJTWfuG77FT6I2bWDkWt5hLMPxtMCquurnD9X8szadn/eIzdAqtCLf+2GtLvrbPBRzu/6vBt6o8wloNJkCFOulip7LfRseT1IiF7JisK3sGvyZ1JdCFuBg+jvbT7+ZYti+d35w==

curl http://localhost:8888/decrypt -d AQCJdqQkxDIaJvWXrPMk9oHdFN7TTXaXpBWe7kuMBIjYXVJ5tCAxvWbdyAzjfAybdPwFa9AstoRWx2MNfqXAEIX0798cWbmPh7zKPwlAj+SeMGogm795CYBsNt+e2oiZ7PqLFUoIs1RV7+0uem/PAPgmbJvaNrOvZ85HZp+NRLcl7+JlkkVFESoYV/4mzSIWxjBs0cfiZw7tp+aJWQR6XKSVkPLdyqvlTpGaA4pY694+Y/y6c+FEM4V/kLI61RsQ46p9e+kpOevM04Hk4tWeK7ksXPUccQ+jbhXd6svARJTWfuG77FT6I2bWDkWt5hLMPxtMCquurnD9X8szadn/eIzdAqtCLf+2GtLvrbPBRzu/6vBt6o8wloNJkCFOulip7LfRseT1IiF7JisK3sGvyZ1JdCFuBg+jvbT7+ZYti+d35w== -u user:password
{"description":"Text not encrypted with this key","status":"INVALID"}

**Comment by spencergibb** [comment]
You need to url encode the encrypted text first

```
$ export ENCRYPTED=`curl http://localhost:8888/encrypt -d abcdefghijklmnopqrstuvwxyz123456 -u user:password| python -c 'import sys,urllib;print urllib.quote(sys.stdin.read().strip())'`
$ echo $ENCRYPTED AQBcV3SLjjFW8tjlI/OEVniVePTM5D%2BOn3w0aAsR/h2ICg9A7Sm6fjudpAgGko%2B73PVSX0X%2BRYBoq5Ia7bwRg5MQTghUGvnv/CQqD6NDas1h493BcfDyqFtMCbnqOMrnp1r0fOHkFyEtGlUuHjy6b5eBN%2BBCpKdtNdIv7WCxL8WcWwRRtjw%2BCFftS2OyD5Jgtk9vTtnkLSDQR5eR/JiJwx3vbu7%2BDsUdLX6vVd9ng9BUjIgdX722Kq4DIHm7KMxr1LZL4bYO/EA6bJ9niqUt2nCM90YlAjLlod1%2BDJpcFxOwM8zR7ZJSsBdnt8gss%2BX2VrNZ5WpExTUsnP12EX4qYNUIrb3OxhSRnQDotpwJ5mpEyQuvu9ruIrF6PZrn64fYhV5IqU2GNZdgcwEjS7GFwyvqCeO/uAaEgbPNaS9%2B7/uj5g%3D%3D
$ curl http://localhost:8888/decrypt -d $ENCRYPTED -u user:password
abcdefghijklmnopqrstuvwxyz123456
```

**Comment by checketts** [comment]
@spencergibb Thanks for including the python snippet. Is there a spring cli equivalent?

**Comment by spencergibb** [comment]
@checketts it's a bit different because it all happens locally, not sure it needs to be url encoded.

**Comment by checketts** [comment]
@spencergibb Sorry for not being clear. I meant to ask if there was some way to use the Spring CLI to handle the URL encoding aspect and not use python as in `python -c 'import sys,urllib;print urllib.quote(sys.stdin.read().strip())'`

````
spring urlEncode "ab+c+d"
````
Then take the return urlEncode from that command and pass it to a curl:
````
curl http://localhost:8888/encrypt -d $encodedPassword -u user:password
````

I like the idea of using the Config server to do the encryption as username/password to access the server are much easier to individualize and revoke than the actual encryption key.

**Comment by spencergibb** [comment]
Absolutely! @checketts create an [issue](https://github.com/spring-cloud/spring-cloud-cli/issues), pull requests welcome :-)

**Comment by checketts** [comment]
Thanks! Opened: https://github.com/spring-cloud/spring-cloud-cli/issues/11

**Comment by atoregozh** [comment]
@spencergibb could you please explain why do you have `AQBcV3SLjjFW8tjlI/OEVniVePTM5D%2BOn3w0aAsR/h2ICg9A7Sm6fjudpAgGko%2B73PVSX0X%2BRYBoq5Ia7bwRg5MQTghUGvnv/CQqD6NDas1h493BcfDyqFtMCbnqOMrnp1r0fOHkFyEtGlUuHjy6b5eBN%2BBCpKdtNdIv7WCxL8WcWwRRtjw%2BCFftS2OyD5Jgtk9vTtnkLSDQR5eR/JiJwx3vbu7%2BDsUdLX6vVd9ng9BUjIgdX722Kq4DIHm7KMxr1LZL4bYO/EA6bJ9niqUt2nCM90YlAjLlod1%2BDJpcFxOwM8zR7ZJSsBdnt8gss%2BX2VrNZ5WpExTUsnP12EX4qYNUIrb3OxhSRnQDotpwJ5mpEyQuvu9ruIrF6PZrn64fYhV5IqU2GNZdgcwEjS7GFwyvqCeO/uAaEgbPNaS9%2B7/uj5g%3D%3D` after `echo $ENCRYPTED`? What purpose does it serve if you are not reusing it as part of decrypt?

**Comment by spencergibb** [comment]
@atoregozh should have been on its own line, the output of the echo

**Comment by atoregozh** [comment]
@spencergibb ahhh. now this makes so much more sense!

**Comment by dsyer** [comment]
Probably you can use `curl --data-urlencode ...` instead of the python.

**Comment by spencergibb** [comment]
Nice, didn't know about `--data-urlencode`.
