### ISSUE TITLE
url /{label}/{application}-{profile}.properties stopped working in spring boot 2.6.1 and config 3.1.0

### ISSUE THREAD

**Issue by aizerin** [spring-cloud/spring-cloud-config#2020]
I upgraded spring cloud to 2021.0.0 and spring boot to 2.6.1 and it stopped working for URL in format `/{label}/{application}-{profile}.properties`. 

It ends with this response:

```
{"name":"master","profiles":["app-devt.properties"],"label":null,"version":null,"state":null,"propertySources":[]}
```

I tried to debug it and it goes to this method in the controller instead of the correct one.

https://github.com/spring-cloud/spring-cloud-config/blob/v3.1.0/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentController.java#L109

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by hpoettker** [comment]
I think the old behavior should return if the property `spring.mvc.pathmatch.matching-strategy: ant_path_matcher` is set.

**Comment by SamuelTissot** [comment]
I can confirm that `spring.mvc.pathmatch.matching-strategy=ant_path_matcher` fixed the issue

however, 

```
/{application}-{profile}.properties
/{application}-{profile}.yml
```

always have a `null` label when using `jdbc`

**Comment by ryanjbaxter** [comment]
Change in boot https://github.com/spring-projects/spring-boot/issues/24805
