### ISSUE TITLE
server locked when refreshing the config in nacos

### ISSUE THREAD

**Issue by baiydavid** [spring-cloud/spring-cloud-config#2029]
spring cloud hoxton
spring boot 2.2.6
nacos 1.3.1
when we refresh the config in nacos,   the server locked , follow-up requests are all have no response.  we must restart the server
we found in log , the log in the figure below is not printed 
![image](https://user-images.githubusercontent.com/13481447/148348558-3c0973d7-4ec3-4856-bd2b-83f4163fd891.png)
up to now， we have encountered this problem twice

by the way , we found the related function marked as "for testing", even in the later version of spring cloud. why?
![image](https://user-images.githubusercontent.com/13481447/148348835-edcf265f-2a7e-4f27-96c3-fb39f75e6194.png)

**Comment by baiydavid** [comment]
the final log of the thread that refreshing config:
2022-01-03 11:57:40,619 CST [d.internal_8848] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver 115 logKeyFound - Found key 'propertyName' in PropertySource 'bootstrapProperties-config.yaml,DEFAULT_GROUP' with value of type Boolean

**Comment by ryanjbaxter** [comment]
Please try spring cloud 2021.0.6 or 2022.0.1

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
