### ISSUE TITLE
ConfigServerConfigDataLoader provided property sources can degrade performance

### ISSUE THREAD

**Issue by philwebb** [spring-cloud/spring-cloud-config#2032]
[This line](https://github.com/spring-cloud/spring-cloud-config/blob/181a44c6d6226861c7eb67c9bb27307abadcdef7/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataLoader.java#L129) or `ConfigServerConfigDataLoader` adds a new `OriginTrackedMapPropertySource` with items loaded from the config server.

If there are a large number of properties then binding operations in Spring Boot can become very slow. This is due to `SpringIterableConfigurationPropertySource` constantly remapping entries.

Performance improves significantly if the alternate `OriginTrackedMapPropertySource` constructor is used and the `immutable` argument is set to `true`.

**Comment by pintomau** [comment]
Hi. Let me know if this should go into a different issue, but we've also faced an added issue, I think specific to Redis and possibly other sources. Please take a look at my comment: https://github.com/spring-projects/spring-boot/issues/28723#issuecomment-1014502593
