### ISSUE TITLE
Config server /encrypt endpoint ignores "+" in keys during encryption

### ISSUE THREAD

**Issue by atoregozh** [spring-cloud/spring-cloud-config#204]
When trying to encrypt keys by POSTing to the `/encrypt` endpoint of config server I noticed that it ignores "+"s in keys and substitutes them with spaces. 
Example:
![image](https://cloud.githubusercontent.com/assets/7033854/8971570/d602cb12-360e-11e5-990b-67265a653a5e.png)
* Leaving off the double quotes in encryption string doesn't change the output.
* When I use `spring` command line client, it encrypts and decrypts the values correctly.

**Comment by spencergibb** [comment]
You need to url encode the values.  See #202
