### ISSUE TITLE
Documentation update for Spring Cloud Config Server using the Vault Backend (Add spring-vault-core lib)

### ISSUE THREAD

**Issue by kamalakarp** [spring-cloud/spring-cloud-config#2041]
HashiCorp Vault is heavily used as backend for Spring Cloud Config Server  and lot of teams use Authentication methods like AppRole, CF Auth, LDAP while connecting and Config Server requires a vault library to perform the authentication. Current documentation needs to be updated to include the step.
https://github.com/spring-cloud/spring-cloud-config/issues/1589#issuecomment-1021439252 

In order to use any authentication method other than TOKEN or the X-Config-Token header, you need to have Spring Vault on the classpath so that Config Server can delegate authentication to that library. If you don't have that library in your Config Server app, you can add it with

```
<dependencies>
	<dependency>
		<groupId>org.springframework.vault</groupId>
		<artifactId>spring-vault-core</artifactId>
	</dependency>
</dependencies>
```
in a Maven pom.xml or

```
dependencies {
    implementation "org.springframework.vault:spring-vault-core"
}
```
in a Gradle build.gradle file.

I thought we had added this info to the docs when the feature was added, but I didn't see it in a quick read of the current docs. If it's not there, it should definitely be added.

**Comment by ryanjbaxter** [comment]
Would you like to create a PR?

**Comment by kamalakarp** [comment]
There are no code changes required. Just documentation update. I have not done documentation update through PR. 
If you can guide me, I can do it through PR.

**Comment by ryanjbaxter** [comment]
Sure!

Are you familiar with making a GitHub PR in general?

The documentation lives in this file
https://github.com/spring-cloud/spring-cloud-config/blob/main/docs/src/main/asciidoc/spring-cloud-config.adoc

Make the PR against the 3.0.x branch.

**Comment by kamalakarp** [comment]
I have done PR's before and can create a PR

**Comment by ryanjbaxter** [comment]
YES!!!! Thank you!

**Comment by kamalakarp** [comment]
@ryanjbaxter - How can i get the documentation updated in this page
https://docs.spring.io/spring-cloud-config/docs/3.0.5/reference/html/#vault-backend

**Comment by kamalakarp** [comment]
does it go there automatically ?

**Comment by kamalakarp** [comment]
@ryanjbaxter - I just finished the PR.
https://github.com/spring-cloud/spring-cloud-config/pull/2042 

Can you please check this ?

**Comment by ryanjbaxter** [comment]
Thanks!
