### ISSUE TITLE
Default git branch (master) no longer served after upgrade

### ISSUE THREAD

**Issue by tspoeri** [spring-cloud/spring-cloud-config#2055]
With Spring Boot 2.6.2 and Spring Cloud 2021.0.0 the config on the default git branch 'master' could be retrieved from the config server with the URL
`/<spring.application.name>/<profile-name>`

With Spring Boot 2.6.4 and Spring Cloud 2021.0.1 the result of the same request to the config server is 404 Not Found.
When the branch name 'master' is appended like this
`/<spring.application.name>/<profile-name>/master`
the request works

I suspected a relation to the new git default branch name main instead of master and added 
~~~
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
~~~
to the config but it still does not work without appending master

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by Stexxen** [comment]
@tspoeri Good find! We've been struggling with this one as well. Downgraded back to 3.1.0, but hadn't identified what was causing it.
Just checked the profiles and yes we use dashes in them.....

Also looks like it might have been fixed, https://github.com/spring-cloud/spring-cloud-config/issues/2058

**Comment by ryanjbaxter** [comment]
Yes I fixed this problem here https://github.com/spring-cloud/spring-cloud-config/commit/5fe66908775d50c51feab96fd26278415dee10a3

You can try our snapshot releases to confirm it was addressed.
