### ISSUE TITLE
Watch files and send refresh events

### ISSUE THREAD

**Issue by ctatineni** [spring-cloud/spring-cloud-config#206]
Is there a way that we can add file watcher to native file system , so that properties can be loaded automatically, rather than loading them via refresh endpoint?

we can not use amqp bus due to various reasons, any other ideas apart from filewatcher to automatically refresh the properties based on the file system would be appreciated.

**Comment by dsyer** [comment]
I'm not sure I follow the use case completely. Kind of a duplicate of #86?

**Comment by dsyer** [comment]
Commit 8d8e07a adds watches to local file system resources (in the case that the SCM repository has a local URI, or if the repository is native).
