### ISSUE TITLE
How to request ability to set both timeouts for SSH JGit connections?

### ISSUE THREAD

**Issue by marnee01** [spring-cloud/spring-cloud-config#2062]
In https://github.com/spring-cloud/spring-cloud-config/issues/1253, I asked about setting connect and read/response timeouts for Jgit connections using **SSH**. Spencer Gibb said that there wasn't anyplace in JGit to set an SSH timeout, so nothing could be done in this project.

This isn't really a feature request. Do you know where I could submit a request to have JGit updated to allow for configuring this? (If that is ever resolved, I'd then submit a feature request here to be able to configure that for spring-cloud-config-server.) I tried searching github, but did not find a Jgit repo here (except one which was just someone's personal repo).

**Comment by ryanjbaxter** [comment]
You can file a bug here 
https://www.eclipse.org/jgit/support/
