### ISSUE TITLE
Concurrency Limitations?

### ISSUE THREAD

**Issue by darylrobbins** [spring-cloud/spring-cloud-config#2069]
https://github.com/spring-cloud/spring-cloud-config/blob/3e1322be369187c7a92cd5c1b200295676c48e4d/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/resource/ResourceController.java#L130

Aren't we effectively limited to processing one request at a time by marking the retrieve helper methods as synchronized?

**Comment by ryanjbaxter** [comment]
I talked to original developer who wrote this code and the reason this is `synchronized` is because the underlying git operations are not threadsafe and since calling this method could cause changes to the cloned repo it is synchronized.

**Comment by ryanjbaxter** [comment]
Done, thanks!
