### ISSUE TITLE
spring cloud config webhook don't work in PropertyPathEndpoint file.

### ISSUE THREAD

**Issue by yoonjk** [spring-cloud/spring-cloud-config#2070]
**Describe the bug**
When push property to git after modified property values, I found a bug that git config property don't be published during testing spring cloud features using spring cloud config webhook.

I think the codes of line no 115,118 is  bugs in the PropertyPathEndpoint file, and then i solved the problems. line no 115 remove ':' charactor and line no 118 code replace ':' to '-' charactor .

- https://github.com/spring-cloud/spring-cloud-config/blob/main/spring-cloud-config-monitor/src/main/java/org/springframework/cloud/config/monitor/PropertyPathEndpoint.java

**Sample**
[PropertyPathEndpoint.java]
	private Set<String> guessServiceName(String path) {
                  :
			while (index >= 0) {
				String name = stem.substring(0, index);
				String profile = stem.substring(index + 1);
				if ("application".equals(name)) {
					services.add("*" + profile);
				}
				else if (!name.startsWith("application")) {
					services.add(name + "-" + profile);
				}
				index = stem.indexOf("-", index + 1);
			}
			:
		}
		return services;
	}

**test**
branch name is base-git-webhook.

[config-server] 
https://gitlab.com/msa2021/config-server.git

[config-client] 
https://gitlab.com/msa2021/config-client.git

**Comment by ryanjbaxter** [comment]
Can you try 2021.0.2-SNAPSHOT?

**Comment by yoonjk** [comment]
I solved trying to 2021.0.2-SNAPSHOT,  So, has the problem been resolved since this version?

**Comment by yoonjk** [comment]
@ryanjbaxter
I solved trying to 2021.0.2-SNAPSHOT, So, has the problem been resolved since this version?

**Comment by ryanjbaxter** [comment]
Yes it has.  It will be on our next release.
