### ISSUE TITLE
value starts with {cipher} in customized PropertySourceLocator not get decrypted

### ISSUE THREAD

**Issue by ktong** [spring-cloud/spring-cloud-config#209]
we implemented a customized PropertySourceLocator which reads configuration from somewhere. There are values which start with {cipher} which we expect getting decrypted in bootstrap context. However, it does not.

**Comment by spencergibb** [comment]
@ktong You need to provide much more information than you have provided for us to begin to understand your problem.  What version? What does your configuration look like?  How did you insert the property source?  What does the `/env` actuator show?

**Comment by ktong** [comment]
<code>
@Configuration
@ConditionalOnOffSpring
public class Cfg2PropertySourceLocator implements PropertySourceLocator {

  @Override
  public PropertySource<?> locate(Environment environment) {
    @SuppressWarnings("unchecked")
    Map<String, Object> properties = OffSpringFactory.getInstance().get(Map.class);
    Map<String, Object> result = properties.entrySet().stream()
            .filter(e -> !e.getKey().startsWith("__"))
            .collect(Collectors.toMap(Map.Entry::getKey, this::getValue));
    return new MapPropertySource("cfg2Property", result);
  }

    private String getValue(Map.Entry<String, Object> e) {
        return (e.getValue() == null) ? "" : e.getValue().toString();
    }
}
</code>

<code>
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
com.linkedin.microservices.li.cfg2.Cfg2PropertySourceLocator
</code>

**Comment by ktong** [comment]
my spring cloud version is Angel.SR3

**Comment by ktong** [comment]
/env cannot show the value because it's password. But when I debug the code , the value does not been decrypted, so it still likes {cipher}xxxx in runtime

**Comment by szpak** [comment]
Maybe this is a similar issue to https://github.com/spring-cloud/spring-cloud-config/issues/30?

**Comment by spencergibb** [comment]
@ktong is your locator ordered before [`EnvironmentDecryptApplicationInitializer`](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java)?

**Comment by spencergibb** [comment]
Actually, this is in the wrong repository.  Encryption happens in spring-cloud-context.  Can you make an issue [there](https://github.com/spring-cloud/spring-cloud-commons/issues) and reference this one?
