### ISSUE TITLE
Cloud config returns 404 not found if the label is empty

### ISSUE THREAD

**Issue by ahmadsab95** [spring-cloud/spring-cloud-config#2091]
Spring Cloud Config support empty label  when using 2.1.6.RELEASE , in case it empty the cloud config server use the default label 

once upgraded to 3.1.1 , it does not accept empty label from client and return 404 not found  instead of use the default label

**Comment by ahmadsab95** [comment]
i just noticed that the request deleted ,  but i don't understands why ? and if its not supported what the purpose of the default label that set by the config server 

`	@RequestMapping("/{name}/{profiles:.*[^-].*}")
	public Environment defaultLabel(@PathVariable String name,
			@PathVariable String profiles) {
		return labelled(name, profiles, null);
	}`

**Comment by dkar3** [comment]
Facing the same issue with Spring Cloud 3.1.3, was in the process of migrating all my services from older (yet compatible Boot and Cloud versions) and unless I specifically declat=re the label name, my services do not seem to pick up configuration from the Config server at all (trying to migrate to Spring Boot 2.7.2 and Spring Cloud 2021.0.3)

**Comment by ryanjbaxter** [comment]
This method is still present in the latest release
https://github.com/spring-cloud/spring-cloud-config/blob/v3.1.4/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentController.java#L109

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
