### ISSUE TITLE
VaultEnvironmentProperties pathToKey prepended with double 'data' in HTTP requests to Vault

### ISSUE THREAD

**Issue by gostevning** [spring-cloud/spring-cloud-config#2092]
Spring Cloud version 3.1.2

I'm trying to use path-to-key for my application, but it seems to me like the resolved path is prefixed with two 'data' strings. In my case I have the **spring.cloud.config.server.vault.path-to-key** set to _some/special/path_, and GET request to vault for a given application/profile is generated as: "https://vault.example.com:443/v1/secret/data/data/some/special/path/my-dummy-app/dev"

To me it looks like the [VaultKeyValue2Accessor](https://github.com/spring-projects/spring-vault/blob/2.3.2/spring-vault-core/src/main/java/org/springframework/vault/core/VaultKeyValue2Accessor.java#L79-L85) prepends 'data' as well.

**Comment by piercer** [comment]
Yes, this is an issue for us too. Both the SpringVaultEnvironmentRepository and V2VaultKvAccessStrategy prepend "data/" to the pathToKey property (ay different times). 

Unfortunately if the spring-vault-core is on the classpath (this is apparently required for approle authentication) then the VaultKeyValue2Accessor in that library appends "/data" to the backend property.

This means that "data" is added twice and the path used to access a secret in the vault ends up looking like this

${backend}/data/data/${pathToKey}

**Comment by ryanjbaxter** [comment]
Fixed in bc8227cc4d9ede583642489584ad320171d60019
