### ISSUE TITLE
Config client doesn't try next label if first one doesn't exist

### ISSUE THREAD

**Issue by checketts** [spring-cloud/spring-cloud-config#210]
If I set `spring.cloud.config.label=nonexistant,master` then the RestClient receives a 404 on the 'nonexistant' label which is converted to an HttpClientResponseException. The code is checking for a 200 but should also catch the client exception.

See:
https://github.com/spring-cloud/spring-cloud-config/blob/5f05eadbd4c0352515ede0d08427e14bd297d737/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java#L120

**Comment by spencergibb** [comment]
Closed via 4aaf8cd1881fbcb61d67f59a4cd1080a8a513358

**Comment by ryanjbaxter** [comment]
Have you tried fail fast?
https://docs.spring.io/spring-cloud-config/docs/3.1.1/reference/html/#config-client-fail-fast

**Comment by ddesna** [comment]
> Have you tried fail fast? https://docs.spring.io/spring-cloud-config/docs/3.1.1/reference/html/#config-client-fail-fast

Yep, but it is just in case your client app is not able to connect with config server.

**Comment by ryanjbaxter** [comment]
Ah I see.  You can open an issue and we can see what the community thinks about it
