### ISSUE TITLE
Documentation mentions password but should be personal access token

### ISSUE THREAD

**Issue by henrylangenhoven** [spring-cloud/spring-cloud-config#2121]
The documentation for spring-cloud-config [authentication section](https://cloud.spring.io/spring-cloud-config/reference/html/#_authentication) specifies a password field, but makes no mention that this password should be a personal access token instead of the password.

**Comment by ryanjbaxter** [comment]
This is the correct documentation link
https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_authentication

If you are using basic authentication it should be a password.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
