### ISSUE TITLE
Documentation: Add a hint about immutable @ConfigurationProperties / @ConstructorBinding

### ISSUE THREAD

**Issue by rowi1de** [spring-cloud/spring-cloud-config#2126]
Hey Spring Cloud Devs, I only came here after while googeling and finding: https://github.com/spring-cloud/spring-cloud-config/issues/1851
- Would be nice if you could extend the Documentation regarding non-refreshable immutable @ConfigurationProperties
- https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#configmap-propertysource

**Comment by ryanjbaxter** [comment]
Im confused as to why you are pointing to the spring cloud kubernetes documentation above

**Comment by rowi1de** [comment]
I’m using spring-cloud-config-kubernetes which is just one config backend server for spring cloud config or?

**Comment by ryanjbaxter** [comment]
Do you have a specific place in mind where this documentation should reside?  Perhaps here: https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#refresh-scope

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
