### ISSUE TITLE
Consider Testcontainers (Localstack) to replace Mockito for AWS integrations

### ISSUE THREAD

**Issue by MatejNedic** [spring-cloud/spring-cloud-config#2127]
**Is your feature request related to a problem? Please describe.**
Not a problem but rather making tests run against real integration.

**Describe the solution you'd like**
Currently, all of AWS Repository tests are being mocked with Mockito, [Localstack](https://www.testcontainers.org/modules/localstack/) can be used to provide real integration tests. This would help when new features or integrations are introduced.

**Additional context**
If this is something that is worth doing, I am willing to take this issue.

**Comment by ryanjbaxter** [comment]
Sound interesting!  If you want to take a go at implementing it we can take a look!

**Comment by hpoettker** [comment]
The PR #2099 contained three integration tests with Localstack for AWS SSM, S3, and Secrets Manager, respectively. They should work as is. In any case, they could be used as a starting point.

**Comment by ryanjbaxter** [comment]
Can you separate out the tests from that PR into a new PR?

**Comment by MatejNedic** [comment]
Hey @hpoettker, 
I already have PR mostly done but since you spent time on this in past I think you should finish it.

Just something to note I would recommend moving all unit tests to integration ones completely and refactor all `Aws*EnvironmentRepositoryTests` to use Localstack. 

@ryanjbaxter what are your thoughts about refactoring unit tests to Integration ones instead?

**Comment by hpoettker** [comment]
@MatejNedic Thanks for the kind offer. But please feel free to go ahead.

The tests in #2099 had a much more limited scope compared to your suggestion. As a broader scope definitely has its merits, I don't see a good reason to stick with the old PR unless a limited scope is strongly preferred.

**Comment by ryanjbaxter** [comment]
@MatejNedic thats fine

**Comment by MatejNedic** [comment]
Hey, sorry for the delay I was on vacation and some other things took priority.
I am currently in process of polishing tests and will have PR soon.
