### ISSUE TITLE
Clarify documentation of pattern formatting when finding single/multiple git config repositories

### ISSUE THREAD

**Issue by atoregozh** [spring-cloud/spring-cloud-config#213]
The part of the [documentation](http://projects.spring.io/spring-cloud/spring-cloud.html) about 'Git backend' gives example of single and multiple git repos:
![image](https://cloud.githubusercontent.com/assets/7033854/9237926/9255f30a-410b-11e5-9c29-e539abb15325.png)
`In the above example, if {application} does not match to any of the patterns, it will use the default uri defined under "spring.cloud.config.server.git.uri". For the "simple" repository, the pattern is "simple" (i.e. it only matches one application). The pattern format is a comma-separated list of application names with wildcards.`
The paragraph above created some confusion and I'd like to see a bit more clarification would help future users:
1. `For the "simple" repository, the pattern is "simple" (i.e. it only matches one application).` is very confusing. My gotcha was that "simple" isn't a repository as the doc says, but an application (as specified in spring.application.name of config client). 
2. The second thing that threw me off was `/pattern1` in the uri. I thought there is supposed to be some patterning involved, when it was none. The right hand side is just an address of git repo where config for "simple" application live. Maybe you could rephrase it as: `To define config repo for exactly one application use one-liner specification "{application}: https://github.com/anyname-repo". To define config repo for one or more applications use multi-line specification involving wildcards "pattern: pattern*,*pattern1*"`.
3. Third gotcha is that you cannot list anything below simple one-liner specification. E.g.
![image](https://cloud.githubusercontent.com/assets/7033854/9238489/e00960a6-410f-11e5-9f5c-50cd723f4207.png)
But then the question is - how should I provide github credentials and where? The doc doesn't talk about that.
4. Last is specification of wildcard locations within patterns. it wasn't clear to me that setting a `pattern` as `pattern: *data or pattern:*` wouldn't work unless i wrap it in double quotes. E.g. this doesn't work:
![image](https://cloud.githubusercontent.com/assets/7033854/9238561/960f40b4-4110-11e5-917e-194ee21d6864.png)
But this does work:
![image](https://cloud.githubusercontent.com/assets/7033854/9238567/a652ce96-4110-11e5-8341-de8860c934bc.png)

**Comment by dsyer** [comment]
What is it about the unquoted "*pattern*" that doesn't work? I'd expect those last two samples are identical.

**Comment by atoregozh** [comment]
@dsyer It doesn't like the first star (*) if not provided inside of the quotes. Below is the error I get if I don't wrap it in double quotes:
![image](https://cloud.githubusercontent.com/assets/7033854/9254782/995e183e-41a2-11e5-8ea1-feeec5b3de48.png)

**Comment by dsyer** [comment]
Fine, so it's just invalid YAML. I consider the error message documentation enough but I added a line in the user guide FWIW anyway.

**Comment by atoregozh** [comment]
Thanks for doing that!
