### ISSUE TITLE
Profile-specific spring.cloud.config.label disregarded. 

### ISSUE THREAD

**Issue by Srinivasan95-RB** [spring-cloud/spring-cloud-config#2135]
Hi. I found that in Cloud Dependencies 2021.0.2, I am unable to specify a spring.cloud.config.label in the profile-specific application.yml. Any value that is specified simply gets ignored. Shouldn't we be able to override the label based on certain profiles?

**Comment by ryanjbaxter** [comment]
Did it work in a previous release?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
