### ISSUE TITLE
Support application and group specific configurations

### ISSUE THREAD

**Issue by hicnar** [spring-cloud/spring-cloud-config#2143]
In our scenario we have a bunch of properties that are common for a group of applications as well as properties that are application specific.

Is it possible to use spring cloud config in a way that for an app that is requesting config on startup it would supply both: props that are common for the whole group of applications as well as the app specific ones without workarounds like for example replicating the common properties by creating an exact copy for each app where the only difference is the name?

If not, then that would be the subject of this feature request.

**Comment by ryanjbaxter** [comment]
`application.yaml | properties` is shared between all clients so common properties can be placed in that file.

**Comment by hicnar** [comment]
Guess I should have been a bit more specific, but here it is...
Yes, you can do that, but they will be static and you won't be able to modify their values without redeploying the server  that on startup will read the application.yaml where they are defined and start serving new values. If we were interested in such scenario I guess we would not have to use spring cloud config. In our use case we must be able to modify them at any time so that the apps that depend on them get their most up-to-date values when they start up and join the cluster.

**Comment by hicnar** [comment]
Yep, makes sense. Thanks for your response. Closing the ticket.
