### ISSUE TITLE
BUG: @PropertySource with custom factory overwrites another @ProperySource with the same loader

### ISSUE THREAD

**Issue by KirillKurdyukov** [spring-cloud/spring-cloud-config#2145]
```
@PropertySource(
    SERVICE_YAML_LOCATION_PATTERN,
    factory = YamlPropertyLoaderFactory::class,
)
class ServiceYamlPropertiesLoader

and

@PropertySource(
    "classpath:config-service-local-settings.yaml",
    factory = YamlPropertyLoaderFactory::class,
)
object ConfigurationPropertySourceLocal : ConfigurationPropertySource
```

org.springframework.cloud.bootstrap.BootstrapConfiguration=\
config.service.configuration.ServiceYamlPropertiesLoader,\
config.service.configuration.ConfigServiceBootstrapConfiguration

Use two classes with the same loader in @Propertysource. But the settings of one disappear. The question is why? I fixed it by starting to load some settings as .properties

I can't use @PropertySources in may case

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
