### ISSUE TITLE
How does the Spring Cloud Config Client & Spring Cloud Bus work with Project Reactor?

### ISSUE THREAD

**Issue by code-magician323** [spring-cloud/spring-cloud-config#2153]
I'd like to understand how Spring Cloud Config Client & Spring Cloud Bus work with Project Reactor?
Are they reactive, or synchronous even for reactive applications? If so, I'd like to request reactive support as a feature request.

**Comment by ryanjbaxter** [comment]
Config clients may use WebFlux.

Bus does not use Project Reactor at all and is using Spring Cloud Stream, I dont see why it would need to use Project Reactor.
