### ISSUE TITLE
Documentation on cloud.spring.io references 3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by maff** [spring-cloud/spring-cloud-config#2159]
We recently adopted Spring Cloud Config and ran into confusions as there are multiple "current" documentation URLs which contain different versions of the documentation.

Googling "spring cloud config" lists https://cloud.spring.io/spring-cloud-config/reference/html/ as first result, however that documentation is for `3.0.0-SNAPSHOT` and does not include the new `spring.config.import` way of configuring a client (also see #1695). Navigating to the documentation via https://spring.io/projects/spring-cloud brings me to the current documentation on https://docs.spring.io/spring-cloud/docs/current/reference/html/ which is currently linking to [Spring Cloud Config `3.1.4`](https://docs.spring.io/spring-cloud-config/docs/current/reference/html/). 

Would it be possible to provide the updated documentation on cloud.spring.io or to redirect from the cloud.spring.io documentation to docs.spring.io?

**Comment by ryanjbaxter** [comment]
We reworked some of the redirects and now https://cloud.spring.io/spring-cloud-config/reference/html/ should redirect to https://docs.spring.io/spring-cloud/docs/current/reference/html/

**Comment by maff** [comment]
Thank you!
