### ISSUE TITLE
suggestion on Exception Handling in MultipleJGitEnvironmentRepository

### ISSUE THREAD

**Issue by ndy2** [spring-cloud/spring-cloud-config#2161]
**Is your feature request related to a problem? Please describe.**
Hi! I'm newbie on spring config and frustrated by the 404 error on my config server
![image](https://user-images.githubusercontent.com/67302707/192106854-15ad1a42-4dd3-4bdd-bce3-b6b86a14e738.png)

the error log is like no such label master

I google the error and the answer is like add default-label @ application.properties
```properties
spring.cloud.config.server.git.default-label= main
```

but it did not solve the problem. 
Now I Found That default label is now main @ defulat 
and the tryMaster feature was added due to maintain compatibility
 [related commit](https://github.com/spring-cloud/spring-cloud-config/commit/38a09020e56940942680f48f34a0d2a7c94eb5b3)

---
above was my story of how i get to this suggestion.

I hope the method `MultipleJGitEnvironmentRepository.findOne` provide a little more kind log or exception handling
in blow lines

line 175
```java
catch (Exception e) {
	if (MultipleJGitEnvironmentProperties.MAIN_LABEL.equals(label) && isTryMasterBranch()) {
		candidate = getRepository(this, application, profile, MultipleJGitEnvironmentProperties.MASTER_LABEL);
		return findOneFromCandidate(candidate, application, profile,
				MultipleJGitEnvironmentProperties.MASTER_LABEL, includeOrigin);
	}
	throw e;
}
```

if the error is catched and then it try again on master branch

if another error is throw while try on master branch.
it just eat the original exception which is thrown by first try (main branch)  !!!

**Describe the solution you'd like**
I want to add simple log for original exception.

**Additional context**
the log i expected 
![image](https://user-images.githubusercontent.com/67302707/192107916-eb256d82-4682-48d3-a9bf-42f6d0d6a1ef.png)

i solve my problem and got to know actual exception by set
```properties
spring.cloud.config.server.git.try-master-branch: false
```

the log i got
![image](https://user-images.githubusercontent.com/67302707/192107850-53eb7ee0-4aed-4ba2-9953-534660b84d8b.png)

**Comment by woshikid** [comment]
What about a suppressed exception?
```java
catch (Exception e) {
    if (MultipleJGitEnvironmentProperties.MAIN_LABEL.equals(label) && isTryMasterBranch()) {
        candidate = getRepository(this, application, profile, MultipleJGitEnvironmentProperties.MASTER_LABEL);
        try {
            return findOneFromCandidate(candidate, application, profile, MultipleJGitEnvironmentProperties.MASTER_LABEL, includeOrigin);
        } catch (Exception e1) {
            e1.addSuppressed(e); // add the original exception as suppressed
            throw e1;
        }
    }
    throw e;
}
```

**Comment by woshikid** [comment]
or we can just throw the original exception, ignore the exception caused by Try Master Branch feature.

**Comment by ndy2** [comment]
Both ideas look good!!
I hope we can notice the original Exception when it is thrown

**Comment by woshikid** [comment]
I will make a PR with Suppressed Exception solution.

**Comment by ndy2** [comment]
Can i make a PR with your idea? T.T

I will be really appreciate and honor to contribute this project

**Comment by woshikid** [comment]
OK, you can take it.

**Comment by ndy2** [comment]
Thanks a lot!
