### ISSUE TITLE
Custom exception handling for NoSuchResourceException is not working

### ISSUE THREAD

**Issue by isvyry** [spring-cloud/spring-cloud-config#2192]
**Describe the bug**
Spring cloud version: **2021.0.5**
I use custom exception handling in my spring-cloud-config-server application.
And the problem is that I could not overwrite exception handling for `NoSuchResourceException` that is defined in `org.springframework.cloud.config.server.resource.ResourceController` (lines 218-221), because it is being handled inside of the controller, which takes higher priority.
The question is how could I handle this exception in my controller advice.

**Sample**
The sample project could be found [here](https://github.com/isvyry/spring-cloud-config-exception-issue)

**Comment by ryanjbaxter** [comment]
I am not sure I see a good was around this.  We need to define how to handle the exception by default.

Maybe we can add a property to turn it off if you want to supply your own?

**Comment by isvyry** [comment]
Yes, it could be an option. That'll work
