### ISSUE TITLE
Common properties not supported anymore

### ISSUE THREAD

**Issue by andreasevers** [spring-cloud/spring-cloud-config#220]
We just migrated from Spring Cloud 1.0.0 to 1.0.3 which upgraded Spring Cloud Config from 1.0.0 to 1.0.2

The resources returned by the config server are now different while we didn't change any of the configuration files.

1.0.0:
```json
{
  "profiles": [
    "itt"
  ],
  "configService:applicationConfig: [classpath:/awards-itt.yml]": {
    "server.port": 22281,
    [...]
  },
  "configService:applicationConfig: [classpath:/awards.yml]": {
    "server.port": 8082,
    [...]
  },
  "configService:applicationConfig: [classpath:/application.yml]": {
    "server.servletPath": "/*",
    "spring.cloud.config.server.native.searchLocations": "classpath:/",
    "spring.boot.admin.client.serviceUrl": "http://${server.hostname:localhost}:${server.port}${server.contextPath}",
    "eureka.instance.statusPageUrlPath": "${server.contextPath}/info",
    "eureka.instance.healthCheckUrlPath": "${server.contextPath}/health",
    [...]
  },
  "servletContextInitParams": {
    "contextConfigLocation": "<NONE>"
  },
  "systemProperties": {
    "os.name": "Linux",
    [...]
  },
  "systemEnvironment": {
    "SHELL": "/bin/bash",
    [...]
  },
  "applicationConfig: [classpath:/bootstrap-itt.yml]": {
    "spring.cloud.config.uri": "http://deds12i:22121/configuration",
    "spring.cloud.config.failFast": true
  },
  "applicationConfig: [classpath:/bootstrap.yml]": {
    "spring.application.name": "awards",
    "spring.cloud.config.uri": "http://localhost:8888/",
    "spring.cloud.config.failFast": false,
    "info.app.version": "1.8.0",
    "info.git-commit": "214fdd7668cd29979e5431f5a7faaface34373f8",
    "info.jenkins-build.number": "Local",
    "info.jenkins-build.id": "Local"
  },
  "defaultProperties": {
    "spring.application.name": "bootstrap"
  }
}
```

1.0.2:
```json
{
  "profiles": [
    "itt"
  ],
  "configService:applicationConfig: [classpath:/awards-itt.yml]": {
    "server.port": 22281,
    [...]
  },
  "configService:applicationConfig: [classpath:/awards.yml]": {
    "server.port": 8082,
    [...]
  },
  "servletContextInitParams": {
    "contextConfigLocation": "<NONE>"
  },
  "systemProperties": {
    "os.name": "Linux",
    [...]
  },
  "systemEnvironment": {
    "SHELL": "/bin/bash",
    [...]
  },
  "applicationConfig: [classpath:/bootstrap-itt.yml]": {
    "spring.cloud.config.uri": "http://deds12i:22121/configuration",
    "spring.cloud.config.failFast": true
  },
  "applicationConfig: [classpath:/bootstrap.yml]": {
    "spring.application.name": "awards",
    "spring.cloud.config.uri": "http://localhost:8888/",
    "spring.cloud.config.failFast": false,
    "info.app.version": "1.8.0",
    "info.git-commit": "214fdd7668cd29979e5431f5a7faaface34373f8",
    "info.jenkins-build.number": "Local",
    "info.jenkins-build.id": "Local"
  },
  "defaultProperties": {
    "spring.application.name": "bootstrap"
  }
}
```

The difference is that the ```application.yml``` of the config server is no longer passed from the config server to the microservices that fetch their configuration.

While this seems like a bug and is not what the documentation describes, this was a very useful feature for us. We used this to our advantage in the following way:

The config server needs configuration hard-coded so we put all its configuration in its ```bootstrap.yml``` file. Since its ```application.yml``` file is shared to all microservices, we had the ability to put common properties in there that are valid for all microservices. This is a very useful feature in case mandatory properties need to be added to all microservices. We wouldn't want to change all our microservices, release and deploy them just to add the same property in all of them.

Seeing this probably was never intended as a feature, could perhaps a file called ```common.yml``` or something similar be scanned and passed as well to all microservices fetching their configuration? That way we can still have this feature without it being an accident.

**Comment by spencergibb** [comment]
I assume you are using the native profile?

**Comment by andreasevers** [comment]
Ah yes sorry, forgot to mention that.

**Comment by spencergibb** [comment]
Change `spring.cloud.config.server.native.searchLocations` (an array of strings).  The default is `{ "classpath:/", "classpath:/config/", "file:./", "file:./config/" }` (which is the same as spring-boot's).  You should be able to add an `application.yml` that _isn't_ used as the config servers properties, but that _is_ sent to clients. The native profile was mostly for testing. If you put `server.port` in it, it screwed up every application.

**Comment by andreasevers** [comment]
Okay I'll try that out tomorrow.
We will be migrating towards a git server for configuration soon. For now we deployed spring cloud on jboss eap 6.3 and for our configuration we are using a jboss module on the config server deployed on such a jboss server. So for our migration path to jar deploys having this native feature is really great!
I'll update this issue tomorrow with the result of our test.
