### ISSUE TITLE
Github OAuth Support for Backing Git repository.

### ISSUE THREAD

**Issue by MissingHandle** [spring-cloud/spring-cloud-config#2214]
**Is your feature request related to a problem? Please describe.**

My Company's SRE team is attempting to eliminate reliance on individual Github Accounts for auth by applications.  As such, it wants to exclusively use machine-to-machine OAuth for access to our Github repositories.

Per our investigations, it seems that when using Git as the backing store for Spring Cloud Config, we would be limited to authenticating to our Github repository using the Personal Access Token or SSH key of a Github User Account, and that there is no ability to use a rotating M2M OAuth flow.

**Describe the solution you'd like**

SRE has requested that I open this issue regarding use of M2M Oauth Flows with regards to accessing the backing Git store.  What does the Spring Team think about the utility and feasibility of this as an option?

**Describe alternatives you've considered**

- Standing up a git repository within our infrastructure and syncing it to our Github Repository.

**Comment by ryanjbaxter** [comment]
How do you authenticate via oauth using git on the command line?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
