### ISSUE TITLE
Property logging.file on configserver repository

### ISSUE THREAD

**Issue by marcosbarbero** [spring-cloud/spring-cloud-config#224]
I'm trying to store the logging.file property in the configserver repository but it is not taking effect.
Is there any issue on doing it?

If I store this config on classpath application.yml it works fine, but not working on remote repo.
My config looks like this:
```
logging.file: /var/log/spring-app/application.log
```

**Comment by dsyer** [comment]
Did you try that with a snapshot of Spring Cloud (Commons - it's not a config client feature actually)?

**Comment by marcosbarbero** [comment]
@dsyer I did with the following dependency:
```
<dependency>
   <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-config</artifactId>
</dependency>
```
I just added spring-cloud-commons dependency but nothing different happened. I've Angel.SR3 spring-cloud-starter-parent.

All properties stored on configserver is working fine, just logging.file does not take effect.

**Comment by dsyer** [comment]
Angel.SR3 is not a snapshot. Try Brixton.BUILD-SNAPSHOT if you can. I think this problem night go away there.

**Comment by marcosbarbero** [comment]
Just tried with Brixton.BUILD-SNAPSHOT and the behavior persists.

**Comment by dsyer** [comment]
Fixed in master. You can work around it by adding a (valid) `logging.config` to your remote property source (or adding another one with that property value).
