### ISSUE TITLE
Typo in dependency configurations for Spring Cloud

### ISSUE THREAD

**Issue by eno-lc** [spring-cloud/spring-cloud-config#2255]
**Describe the bug**
It is not a bug, just a typo when it comes to configuring Spring Cloud. Thought you guys would want to take a look.
<version>${spring.cloud-version}</version> - version uses property spring.cloud-version
<spring-cloud.version>2022.0.1</spring-cloud.version> - here it is defined as spring-cloud.version.
So it is just a typo in the documentation here: https://spring.io/projects/spring-cloud

**Sample**
![image](https://user-images.githubusercontent.com/93098680/234260638-d01ee1dc-4833-4b79-b870-46bc8dda4ae7.png)

**Comment by ryanjbaxter** [comment]
Should be fixed now, thanks!
