### ISSUE TITLE
Is Fetch command necessary?

### ISSUE THREAD

**Issue by arsenaid** [spring-cloud/spring-cloud-config#227]
Hi,
I am running into performance issues with the Config Server because of FetchCommand usage. Fetch command lasts a whopping 600 ms in spite of no changes in remote branches. In the loadEnvironment method afterwards Checkout and Pull commands are used after Fetch command is executed. I was wondering about the reasons of using the Fetch in the following snippet. 

```
private Git openGitRepository() throws IOException {
		Git git = this.gitFactory.getGitByOpen(getWorkingDirectory());
		tryFetch(git);
		return git;
	}

private void tryFetch(Git git) {
		try {
			FetchCommand fetch = git.fetch();
			if (hasText(getUsername())) {
				setCredentialsProvider(fetch);
			}
			fetch.call();
		}
		catch (Exception e) {
			logger.warn("Remote repository not available");
		}
	} 
```

**Comment by dsyer** [comment]
I can take that out and see if anything breaks. It's probably there as a failfast, but if it costs a lot maybe not worth it.

**Comment by arsenaid** [comment]
Thank you.
