### ISSUE TITLE
Reload values on git commit?

### ISSUE THREAD

**Issue by dharshanrg** [spring-cloud/spring-cloud-config#2270]
Hi,

Is there an option for the config server to reload values from the git repo when there is a commit? The default behavior appears to check with Git for every request. This always provides the correct value, but results in high latency. If there was an option to reload the values on commit, it would be useful to reduce the latency.

**Comment by ryanjbaxter** [comment]
See https://docs.spring.io/spring-cloud-config/docs/4.0.2/reference/html/#_push_notifications_and_spring_cloud_bus

**Comment by dharshanrg** [comment]
Thanks Ryan - that is a good idea. What is the mechanism to get Spring cloud config to reload a particular environment when I detect a commit?

**Comment by ryanjbaxter** [comment]
That is what that documentation explains.  If you have specific questions I would be happy to help.

**Comment by dharshanrg** [comment]
Thanks. I will work through the details. Thanks again for your timely help. Will close the issue.
