### ISSUE TITLE
Overriding default java system properties like line.separator, path.separator via config server

### ISSUE THREAD

**Issue by rmotapar** [spring-cloud/spring-cloud-config#228]
Hi,
Is there a way to override the JVM properties like "path.separartor", "user.timezone", etc, via config server instead of supplying them via command line when starting the spring boot app? I attempted this and environment.getProperty gives me the right overridden value from config server but System.getProperty still returns the default value.

Thanks,
Ramesh

**Comment by spencergibb** [comment]
I don't believe there is.

**Comment by rmotapar** [comment]
Thank you for confirming! We are thinking of setting these JVM properties in config server and then loading them into the JVM via a custom ApplicationContextInitializer which executes right after PropertySourceBootstrapConfiguration initializer.
