### ISSUE TITLE
java.lang.AssertionError when using HTTP/HTTPS url for the `git.uri` with `-enableassertions` flag enabled.

### ISSUE THREAD

**Issue by kvmw** [spring-cloud/spring-cloud-config#2284]
Both [FileBasedSshSessionFactory](https://github.com/spring-cloud/spring-cloud-config/blob/8ca88f30e5f9b2ae6af7e0a7947c9ebef639d2a6/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/ssh/FileBasedSshSessionFactory.java#L36) and [PropertyBasedSshSessionFactory](https://github.com/spring-cloud/spring-cloud-config/blob/8ca88f30e5f9b2ae6af7e0a7947c9ebef639d2a6/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/ssh/PropertyBasedSshSessionFactory.java#L70) are expecting at least one `ssh` URL in the git configuration. So a  HTTP/HTTPS URL for `git.uri`  can cause `java.lang.AssertionError`, if `-enableassertions` flag is true. 

The issue in often not visible because above flag is `false` by default. But in development or test environment, which the flag might be enabled, one can see the issue. 

**Sample**
Running any sample config-server application with above flag enabled can show the issue.
```
java -ea -jar ./build/libs/config-server-sample-0.0.1-SNAPSHOT.jar
```

**Possible Solution**
`FileBasedSshTransportConfigCallback` and `PropertyBasedSshTransportConfigCallback` should configure the `SshTransport` only if there is at least one SSH URL in the configuration.

current code:
```java
@Override
public void configure(Transport transport) {
  if (transport instanceof SshTransport) {
    ((SshTransport) transport).setSshSessionFactory(new FileBasedSshSessionFactory(
		new SshUriPropertyProcessor(this.sshUriProperties).getSshKeysByHostname()));
  }
}
```
proposed change:
```java
@Override
public void configure(Transport transport) {
  if (transport instanceof SshTransport) {
        var sshKeysByHostname = new SshUriPropertyProcessor(this.sshUriProperties).getSshKeysByHostname();
        if (!sshKeysByHostname.isEmpty()) {  // Only if the map is not empty
	  ((SshTransport) transport).setSshSessionFactory(new FileBasedSshSessionFactory(sshKeysByHostname));
	}
  }
}
```

**Comment by ryanjbaxter** [comment]
Would you want to submit a PR with this change?

**Comment by kvmw** [comment]
> Would you want to submit a PR with this change?

PR is ready: #2287
