### ISSUE TITLE
Disable clients continuously polling for configuration

### ISSUE THREAD

**Issue by fritzrichter** [spring-cloud/spring-cloud-config#229]
Currently the spring-cloud-config clients are asking for configurations approx. every 2 seconds. In our case, we do not want to "re-configure" our services at runtime, therefore we would like to disable that polling feature. Only ask for configs at boot-time. 

Is that possible?

**Comment by spencergibb** [comment]
There is a [retry mechanism](https://github.com/spring-cloud/spring-cloud-config/blob/b191b91322548feb2e2bf63cb8c18fed7ec9e79e/docs/src/main/asciidoc/spring-cloud-config.adoc#config-client-retry) that has to be specifically enabled. I'm not aware of a polling mechanism. Do you have some scheduled task that is refreshing or something?

**Comment by fritzrichter** [comment]
Ahhh, I found out what it is. It's the embedded "Health Check" of Spring Boot, which is called by an external deamon (Consul) which is connecting to the config server.
