### ISSUE TITLE
When spring.config.import: optional, still failing

### ISSUE THREAD

**Issue by zdendis** [spring-cloud/spring-cloud-config#2294]
https://github.com/spring-cloud/spring-cloud-config/blob/1f18b7076cbe487e7013ea3bbc754ae0286e41b7/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataLoader.java#L191

This if should be && not ||.

if (properties.isFailFast() || !resource.isOptional()) {
			String reason;
			if (properties.isFailFast()) {
				reason = "the fail fast property is set";
			}
			else {
				reason = "the resource is not optional";
			}
			throw new ConfigClientFailFastException("Could not locate PropertySource and " + reason + ", failing"
					+ (errorBody == null ? "" : ": " + errorBody), error);
		}

**Comment by ryanjbaxter** [comment]
I dont think so.

Setting fail fast to true and having the import be optional seems to contradict itself.  By saying fail fast you are saying you want the application not to start up if there is an error.  But by saying its optional you are saying you don't care that the import doesnt exist and we are getting and error you want to ignore.

**Comment by ryanjbaxter** [comment]
I think one of the problem here with this setup is that `spring.config.import` behaves differently than other properties.

You would expect when you set it via a system property it would override whats in the application.yaml, however that is not the case with `spring.config.import`, each statement is independent of each other.

Could you disable `fail-fast` in the test environment?

**Comment by zdendis** [comment]
Yes. I did it by fail-fast=false. :)  Why is it done like this? (each setting is independent of each other)

**Comment by ryanjbaxter** [comment]
That’s a question for the spring boot team, I don’t have the best answer for that

**Comment by zdendis** [comment]
Ok. I keep it on you, if you want that communicate with spring boot team or not.
