### ISSUE TITLE
Discovery first lookup does not work anymore with spring cloud 2022

### ISSUE THREAD

**Issue by snussbaumer** [spring-cloud/spring-cloud-config#2303]
I've spent quite a few hours scratching my head on this one, digging through [the documentation](https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#discovery-first-bootstrap), migration guides, release notes, but can not get an application to get it's config from a configserver found through eureka : it works perfectly with boot 2.7.13/Cloud 2021.0.8, but fails with boot 3.1.1/Cloud 2022.0.3. 

I put a really simple project here : https://github.com/snussbaumer/spring-cloud-config-discovery-first-sample. 

The main branch is spring boot 3, there is also a [main-spring-boot-2 branch](https://github.com/snussbaumer/spring-cloud-config-discovery-first-sample/tree/main-spring-boot-2) with the spring boot 2 version that works. The diff is really only versions in poms : https://github.com/snussbaumer/spring-cloud-config-discovery-first-sample/compare/main...main-spring-boot-2

I've successfully migrated through every Spring Cloud version since Angel (!!!), this is the first time I can not sort it out ... that's why I think there might be an issue here.

**Comment by guerricm** [comment]
hello @snussbaumer , 

i had the same pb and opened an issue : https://github.com/spring-cloud/spring-cloud-config/issues/2295
There is a workaround that you could find in this comment : https://github.com/spring-cloud/spring-cloud-config/issues/2295#issuecomment-1600847647 

we must wait for a better fix ;-)

**Comment by snussbaumer** [comment]
Thanks for your input @guerricm  !!! 

I close this issue => it is a duplicate of #2295 and it's now working with spring cloud 2022.0.4
