### ISSUE TITLE
Docker/Maven/Java/IntelliK

### ISSUE THREAD

**Issue by stoiandelev** [spring-cloud/spring-cloud-config#2306]
Hi,
My application properties

spring.profiles.active=@spring.profiles.active@
server.port=8000

My pom.xml file

4.0.0

org.springframework.boot
spring-boot-starter-parent
3.1.1

com.example
Demo_Docker
0.0.1-SNAPSHOT
Demo_Docker
Demo_Docker

<java.version>17</java.version>
<spring.profiles.active>development</spring.profiles.active>

org.springframework.boot
spring-boot-starter-web
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-devtools</artifactId>
        <scope>runtime</scope>
        <optional>true</optional>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-test</artifactId>
        <scope>test</scope>
    </dependency>
</dependencies>

<build>
    <testResources>
        <testResource>
            <directory>src/test/resources</directory>
            <filtering>true</filtering>
        </testResource>
    </testResources>
    <plugins>
        <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
        </plugin>
    </plugins>

</build>
My Dockerfile

FROM openjdk:17-jdk-alpine
ARG JAR_FILE=out/*.jar
COPY ./out/artifacts/Demo_Docker_jar/Demo_Docker.jar app.jar
EXPOSE 8000
ENTRYPOINT ["java", "-jar", "/app.jar"]

RestController

@RestController
public class hello {

@GetMapping("/")
public String greeting() {
    return "Greeting Sto";
}
INFO FRON INTELLIJ
17:38:36.217 [main] INFO com.example.demo_docker.DemoDockerApplication -- No active profile set, falling back to 1 default profile: "default"

CAN HELP PLS

APP NOT RUNNING ON DOCKER!

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by stoiandelev** [comment]
When I start the project with docker and open the localhost method greeting() it doesn't execute. When I run the app normally with Spring Boot the method works. If you have any additional questions, I'm on a date. My console says -
No active profile set, falling back to 1 default profile: "default" 

And the App does work.

I tried everything I could find on the net but to no avail
Thanks for support


[Demo_Docker.zip](https://github.com/spring-cloud/spring-cloud-config/files/12065032/Demo_Docker.zip)

**Comment by ryanjbaxter** [comment]
This project doesn't using Spring Cloud from what I see so I am not sure why you have opened the issue in Spring Cloud Config...
