### ISSUE TITLE
Why do I still report an error when the program runs when I configure the label in the yml file no such lable: master

### ISSUE THREAD

**Issue by striveBin** [spring-cloud/spring-cloud-config#2313]
My springcloud version is Hoxton.SR12.
I have configured the label as main in yml, but still reported an error of no such master
![10da2678d14f917847f23e3607b066ba](https://github.com/spring-cloud/spring-cloud-config/assets/100272418/dc835226-d1e4-48d5-9335-df7abe28736c)
![42ff557117c224a3e6f33fe64f48a826](https://github.com/spring-cloud/spring-cloud-config/assets/100272418/1233c5db-6f30-4126-99f4-c9ab8a30bde4)

**Comment by striveBin** [comment]
When I change the branch name of Git to master and submit it to the warehouse, this error will not occur

**Comment by ryanjbaxter** [comment]
We no longer support Hoxton, please try with the latest 2021.0.x or 2022.0.x release

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
