### ISSUE TITLE
Spring Cloud Dependencies 2021.0.8: active profiles on command-line are appended to those in bootstrap.yml

### ISSUE THREAD

**Issue by robsmorenburg** [spring-cloud/spring-cloud-config#2319]
**Describe the bug**
After upgrading from spring-cloud-dependencies 2021.0.7 to 2021.0.8 we notice that the active profiles are no longer as expected. These services are on Spring Boot 2.17.4 btw.

The bootstrap.yml specifies: dev,local-vault
The command-line specifies: production

In the past our pod would be started with just the production profile.
Since release 2021.0.8 it is started with all 3 profiles.

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by robsmorenburg** [comment]
I tried, but was not able to have a failing minimal service.

**Comment by ryanjbaxter** [comment]
If you can't provide a sample it will be hard for us to help

**Comment by robsmorenburg** [comment]
I understand

**Comment by leovx** [comment]
> **Describe the bug** After upgrading from spring-cloud-dependencies 2021.0.7 to 2021.0.8 we notice that the active profiles are no longer as expected. These services are on Spring Boot 2.17.4 btw.
> 
> The bootstrap.yml specifies: dev,local-vault The command-line specifies: production
> 
> In the past our pod would be started with just the production profile. Since release 2021.0.8 it is started with all 3 profiles.

Hi @robsmorenburg, I think you are talking about this issue https://github.com/spring-cloud/spring-cloud-commons/issues/1285, no worries, we have fixed it in the next version (2021.0.9).
