### ISSUE TITLE
config-client - log the requested URL on failure

### ISSUE THREAD

**Issue by dwelch2344** [spring-cloud/spring-cloud-config#232]
In the event of a failure, it's really difficult to track down what the final URL a config client requested was. It'd be nice to have a warning in the logs, especially if fail fast is enabled.

**Comment by dwelch2344** [comment]
Also, the ability to customize the RestTemplate via a @Bean or @Configuration would be ideal. I've seen this [StackOverflow answer](http://stackoverflow.com/questions/30239163/how-to-configure-a-custom-resttemplate-when-using-spring-cloud-config-client) by @spencergibb but couldn't get any customizations to take effect since bootstrapping happens immediately (and doing it via a `@PostConstruct` method felt pretty hacky)

**Comment by dsyer** [comment]
AFAIK you get the URL logged at INFO level whether it is successful or not. That always works for me. Maybe you are looking at something else, or you don't use INFO?

Please don't overload issues with more than one thread. IMO `@PostConstruct` is a legitimate call back and if you treat the things you inject into it with respect (mind the contract) it's fair game. If you don't like it you can always set `spring.cloud.config.enabled=false` and add your own `ConfigServicePropertySourceLocator` (or equivalent).

**Comment by dsyer** [comment]
Actually when I looked I realized that you only see a URL if a property source is successfully fetched, and even then it's the wrong one (the git URL not the config server).
