### ISSUE TITLE
cache edit

### ISSUE THREAD

**Issue by f-a-zarand** [spring-cloud/spring-cloud-config#2329]
hi every one, i want to know can i change cache that create with all yml file(concurent map that create under the hood for save cache for yml file) directly with java code,  without change yml file? or no? thanks for advance :)

**Comment by ryanjbaxter** [comment]
I am not sure I am following your question, can you please provide more details?

**Comment by f-a-zarand** [comment]
Thanks for your response, when spring cloud config server is run, create cache with all yml file, if i understand correctlly, after that when a client request property , server don't read actually file and use from cache, is it correct? if yes can i change this cache without change actually yml file? (for some test, this is a very specific situation)

**Comment by ryanjbaxter** [comment]
What environment repository are you using on the config server?

**Comment by f-a-zarand** [comment]
Hi again, thanks for your response
I use the default environment
if I can't do this by default, can I do it with Redis?

thanks for your time and your energy :)

**Comment by ryanjbaxter** [comment]
There is no default environment, you must configure the config server with an environment repository (git, svn, vault, filesystem, etc.)

**Comment by f-a-zarand** [comment]
oh excuse me, I was mistaken, yes I used from filesystem

**Comment by ryanjbaxter** [comment]
There is no caching done on the config server.  In the case where a source control environment repository is used we clone the repo to the file system initially and there is a refresh interval within which we won’t pull changes but other than that there is no caching.  If you make a change to the configuration on the file system you should be seeing that change reflected in requests made to the config serve.

**Comment by f-a-zarand** [comment]
my problem will be solved or not, it's not significant, you're spending time for me, this is significant :)
if this topic bothers you please don't answer and close it, I'm glad and understand something until here :)

your answer attacked my mind map that I created about the spring config server:)))))
excuse me for these base questions (or incorrect questions)
based on your answers, the spring config server doesn't create any caching, so when a client-server for example restarted, the config server reads the related configuration file again and sends the property to the client, is this correct?
if yes, this isn't very expensive? for again read a file?

**Comment by ryanjbaxter** [comment]
> the config server reads the related configuration file again and sends the property to the client, is this correct?
Correct

> if yes, this isn't very expensive? for again read a file?
As [the docs suggest](https://docs.spring.io/spring-cloud-config/docs/4.0.4/reference/html/#_file_system_backend), using the file system with the config server is not recommended for production.  One of the reasons is that the configuration is not shared across config servers.  Ultimately the performance problem you are describing would only become an issue if the apps are restarting frequently or there are ALOT of apps that restarting occasionally.  You can scale the config server horizontally to deal with this, but when using the file system its hard to share configuration between all the config server instances.

**Comment by f-a-zarand** [comment]
Hi again
Thanks for your time and the energy spent on developers
I wish you all the success, happiness, and joy in life :))
