### ISSUE TITLE
Storing configuration in JSON

### ISSUE THREAD

**Issue by marcellodesales** [spring-cloud/spring-cloud-config#233]
Hi there,

Question
---- 
Is there support for storing the configuration files in JSON???

Motivation
----

We are deploying the config server to serve not only `Java`, but also `Node.js` services... Although we can support YAML files for that community, we already have multiple Node.js teams distributed across the company storying properties in JSON... 

thanks
Marcello

**Comment by spencergibb** [comment]
According to [the spec](http://www.yaml.org/spec/1.2/spec.html) json is a subset of yaml. Config server also returns the properties as json via the rest api (`/<appname>/<profile>`).

**Comment by marcellodesales** [comment]
@spencergibb The question here is about storage... As mentioned, we have dozens of teams today working in Node.js services that already use JSON files. Some teams are NOT willing to replace JSON with YAML due to the native support of JSON objects in Node.js without requiring external YAML module. Also, we are targeting teams writing UI services such as Angular-based clients that already deals with JSON objects.

**Comment by spencergibb** [comment]
Config server supports the formats that [spring-boot does](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config). You'll need to open an issue there.
