### ISSUE TITLE
2022.0.4 : No decryption for FailsafeTextEncryptor. Did you configure the keystore correctly?

### ISSUE THREAD

**Issue by mpalourdio** [spring-cloud/spring-cloud-config#2330]
Hello,

**Describe the bug**
Spring Boot `3.1.4`, Spring Cloud `2022.0.4`
 
Run this Config Server : https://github.com/mpalourdio/ConfigServer
Run this Spring Cloud Gateway : https://github.com/mpalourdio/ProxyServer

This fails with
```log
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.cloud.config.password' to java.lang.String:

    Property: spring.cloud.config.password
    Value: "{cipher}12c545c7e569d579c0b205bfebeef99dcbf07c0d079b4035ce2980ef6ef2301e"
    Origin: class path resource [application.properties] - 22:30
    Reason: java.lang.UnsupportedOperationException: No decryption for FailsafeTextEncryptor. Did you configure the keystore correctly?

Action:

Update your application's configuration
```

**Sample**
See above, clone both and `mvn spring-boot:run`

**Observations**

Going back to `2022.0.2` as version in https://github.com/mpalourdio/ProxyServer works. Fails with `2022.0.3` too.

**Comment by mpalourdio** [comment]
Hi, 

Just updated to 2023.0.1 but the error still remains. What works to have symmetric OK, is exporting the env var, ie,

`export ENCRYPT_KEY=mykey`
The property `encrypt.key=mykey` still has no effect and leads to the exception.

Whereas the doc seems to indicate that the property should be ok : https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_key_management

I have updated the repositories from OP to latest versions.

Please see : https://github.com/mpalourdio/ProxyServer/blob/6d85ca9469848bf44d1893fecc8ac6cb6f0fe5b2/src/main/resources/application.properties

**Comment by ryanjbaxter** [comment]
Try adding
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
```
and set encrypt.key in bootstrap.properties.  It is needed during bootstrap and that is why the environment variable works.

**Comment by mpalourdio** [comment]
Sure, this use to work (and will work) like this prior to the introduction to `spring.config.import`.But all our apps had been refactored to remove the need of the bootstrap in Spring Cloud, and it has worked until `2022.0.2`. All versions after `2022.0.2` have failed with this configuration, and I didn't see any deprecation/removal warning.

Also the documentation still states this point

> The Config Server can use a symmetric (shared) key or an asymmetric one (RSA key pair). The asymmetric choice is superior in terms of security, but it is often more convenient to use a symmetric key since it is **a single property value to configure in the application.properties.**
> 
> To configure a symmetric key, you need to set encrypt.key to a secret String (or use the ENCRYPT_KEY environment variable to keep it out of plain-text configuration files).

This notice is in the documentation too : 

> **If** you include spring-cloud-starter-bootstrap on the classpath or set spring.cloud.bootstrap.enabled=true as a system property, you will need to set encrypt.key in bootstrap.properties


Something has changed, but i don't know why. Thanks for your feedback

**Comment by mpalourdio** [comment]
So i have tested with reintroducing `spring-cloud-starter-bootstrap` and moving the `encrypt.key` to `bootstrap.properties`. As stated, it did not work until I change `spring.config.import` to the good ol' `spring.cloud.config.uri`
