### ISSUE TITLE
Upgrade to Spring boot 3 fail on org.eclipse.jgit.errors.TransportException

### ISSUE THREAD

**Issue by avnerstr** [spring-cloud/spring-cloud-config#2332]
**Describe the bug**
After upgrade to Spring boot 3.1.4
plugin: id 'io.spring.dependency-management' version '1.1.3'
and 
dependencyManagement {
	imports {
		mavenBom 'org.springframework.cloud:spring-cloud-dependencies:2022.0.4'
	}
}
I started to get errors connecting to AWS code commit:

Caused by: org.eclipse.jgit.errors.TransportException: https://git-codecommit.eu-west-2.amazonaws.com/v1/repos/fallback-repo: git-upload-pack not permitted on 'https://git-codecommit.eu-west-2.amazonaws.com/v1/repos/fallback-repo/'
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:692)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:465)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:151)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:103)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1462)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:235)
	... 178 common frames omitted

important issue:
I created this class:

public class AwsCodeCommitCredentialsProviderFactory extends GitCredentialsProviderFactory {

    private SecretHandler secretHandler;

    public AwsCodeCommitCredentialsProviderFactory(SecretHandler secretHandler) {
        this.secretHandler = secretHandler;
    }

    @Override
    public CredentialsProvider createFor(String uri, String username, String password, String passphrase, boolean skipSslValidation) {
        String accessKeyId = secretHandler.getSecret("aws.access.key.id");
        String secretAccessKey = secretHandler.getSecret("aws.secret.access.key");
        log.info("in createFor, user: {}, password: {}", accessKeyId, secretAccessKey);
        return super.createFor(uri, accessKeyId, secretAccessKey, passphrase, skipSslValidation);
    }
}

and bean:
@Configuration
public class CodeCommitConfiguration {

    @Bean
    public GitCredentialsProviderFactory gitCredentialsProviderFactory(SecretHandler secretHandler) {
       return new AwsCodeCommitCredentialsProviderFactory(secretHandler);
    }

this is working prefect on Spring boot 2 and break in Springboot 3 - any idea?

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by artiom-bozieac** [comment]
Did you manage to solve the issue?
