### ISSUE TITLE
Version 4.0.4, unable to connect to Cloud Config if we have cloud config profile and spring environment profile.

### ISSUE THREAD

**Issue by adityakiranpendyala** [spring-cloud/spring-cloud-config#2349]
Description:

We have a profile property to connect to appconfig.(spring.cloud.config.profile)
with spring-cloud-config-client-4.0.4.jar, in class ConfigServicePropertySourceLocator, there is  a new method which combines profile from property and environment with comma separated.
So, finally profile value while connecting to appconfig will be like below and failing app-config call.

HTTP GET https://XXXXXXXXXX/appconfig/properties/<ModuleID>/<PROFILE-XYX,ABC>/<LABEL>
This is failing.

Even though profile properties are overrider at line 122 ConfigClientProperties properties = this.defaultProperties.override(environment);

in the next line, profile value is getting updated by appending with all the profiles
properties.setProfile(String.join(",", combineProfiles(properties, environment)));

So in method getRemoteEnvironment, while preparing the URL, profile path param is goign as comma separated and there by causing issue.

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by adityakiranpendyala** [comment]
Hi @ryanjbaxter ,

I am preparing a sample with out exposing client specific details.
But issue gist ism

At line 116, properties.setProfile(String.join(",", combineProfiles(properties, environment)));
profile can be comma separated. And we are sending this profile as a path parameter to a GET call at line 291
response = restTemplate.exchange(uri + path, HttpMethod.GET, entity, Environment.class, args);

where args  is either  = new String[] { name, profile }; or  new String[] { name, profile, label };

So, we are ending up having a comma separated in a Http GET call

**Comment by adityakiranpendyala** [comment]
Hi @ryanjbaxter ,

Here is an example. You can run below project as a Spring Boot application.

1. I have on profile defiled for logging.
2. I have properties to connect to spring cloud to download properties on startup.
So, I have two profiles, one at environment level and one for cloud profile.

Now when I am starting application, I am getting URL as profiles with comma separated and failing.
[demo.zip](https://github.com/spring-cloud/spring-cloud-config/files/13309632/demo.zip)

GET request for "http://localhost:8888/CONFIG_NAME/CONFIG_PROFILE,logging-profile/CONFIG_LABEL

**Comment by ryanjbaxter** [comment]
I think I understand what you are saying now...

If you set `spring.cloud.config.profile` it should override any profile(s) set in any other manor.  So in your example if you set `spring.cloud.config.profile=CONFIG_LABEL` and set `spring.profiles.active=logging-profile` the request made to the config server should only have the `CONFIG_LABEL` profile, ie `http://localhost:8888/CONFIG_NAME/CONFIG_PROFILE/CONFIG_LABEL`.  Is that correct?

**Comment by adityakiranpendyala** [comment]
yes @ryanjbaxter , your understanding is correct.
Config Service URL should be http://localhost:8888/CONFIG_NAME/CONFIG_PROFILE/CONFIG_LABEL
but now it is preparing as http://localhost:8888/CONFIG_NAME/CONFIG_PROFILE,logging-profile/CONFIG_LABEL
