### ISSUE TITLE
Spring does not override properties values when we use yaml files in config server repository

### ISSUE THREAD

**Issue by michalmielko-newsuk** [spring-cloud/spring-cloud-config#2356]
Affected versions
Spring Boo version: 2.7.13 (same behaviour for 2.7.17)
Spring cloud version: 2021.0.8

We have decided to replace our properties files with yaml files in config server. Properties are loaded in correct order

Local properties
Fetch properties from config server
Fetch properties (secrets) from AWS Parameter Store
The problem is that if the property exists in yaml files in config server repository and in SSM. The property value is not override based on values from AWS Parameter Store. The AWS Parameter Store has the highest precedence so it should always override the value. It has stopped working since we started using yaml files instead of *.properties files.

Apologise if I have chosen wrong place to report it

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.
