### ISSUE TITLE
spring-cloud-config-monitor Gitee webhook not work

### ISSUE THREAD

**Issue by ws1922667298** [spring-cloud/spring-cloud-config#2371]
hi,
This is Gitee webhook request header (use /config because my gateway config)
``` text
Request URL: http://xxx.xxx.xxx.xxx/config/monitor?path=*
Request Method: POST
X-Gitee-Token: 
X-Gitee-Event: push_hooks
User-Agent: git-oschina-hook
X-Gitee-Timestamp: 1704445639493
X-Gitee-Ping: true
Content-Type: application/json
X-Git-Oschina-Event: push_hooks
```
This is `GiteePropertyPathNotificationExtractor.java`
latest version
``` java
private static final String HEADERS_KEY = "x-git-oschina-event";

private static final String HEADERS_VALUE = "Push Hook";

@Override
protected boolean requestBelongsToGitRepoManager(MultiValueMap<String, String> headers) {
return HEADERS_VALUE.equals(headers.getFirst(HEADERS_KEY));
}
```
my version (2.2.2.RELEASE)
``` java
protected boolean requestBelongsToGitRepoManager(MultiValueMap<String, String> headers) {
    return "Push Hook".equals(headers.getFirst("x-git-oschina-event"));
}
```
maybe here's the problem
I think the `Push Hook` maybe should change to `push_hooks`
sorry, my english is low.
thanks

**Comment by ryanjbaxter** [comment]
It is hard for me to tell since the documentation is in Chinese, can you point me to any Gitee documentation that shows the headers in the request.

Also if you are using versions 2.2.2.RELEASE you need to upgrade, its no longer supported

**Comment by ws1922667298** [comment]
I can't find the detail document for gitee webhook,  only this

https://help.gitee.com/webhook/gitee-webhook-push-data-format

**Comment by ryanjbaxter** [comment]
I assume you opened this issue?
https://gitee.com/oschina/git-osc/issues/I8U3K7?from=project-issue

It would be great if they respond to that an clarify what the header value should be.

**Comment by ws1922667298** [comment]
Yep

**Comment by ryanjbaxter** [comment]
Please let me know if you hear back from them

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
