### ISSUE TITLE
Enhance Spring ConfigServer: Introduce {secret} Prefix for Efficient Management of Shared Secrets

### ISSUE THREAD

**Issue by sergioasantiago** [spring-cloud/spring-cloud-config#2377]
**Is your feature request related to a problem? Please describe.**

Currently, when externalizing secrets from the git backend to a secret manager (such as [Vault](https://docs.spring.io/spring-cloud-config/reference/server/environment-repository/vault-backend.html) or [AWS Secret Manager](https://docs.spring.io/spring-cloud-config/reference/server/environment-repository/aws-secrets-manager-backend.html)) in a Spring ConfigServer setup, the need to duplicate secrets across multiple microservices can be cumbersome. Each microservice requests its configuration from ConfigServer using the microservice name as the application, leading to redundancy when a secret is shared among several microservices.

**Describe the solution you'd like**

I would like to propose an enhancement that allows for more efficient management of shared secrets. Specifically, the ability to extend the `{cipher}` prefix to introduce a new prefix, let's call it `{secret}`, and include the path to the secret in the secret manager. For example: `{secret}/secret/myservice/live:apipassword=test`. This modification would enable the reuse of the same secret across multiple microservices, improving efficiency and easing the process of updating shared secrets during refactoring.

**Describe alternatives you've considered**

One alternative could be to continue with the current approach of duplicating secrets for each microservice, but this leads to redundancy, increased maintenance efforts, and potential issues during updates. The proposed `{secret}` prefix offers a more streamlined and scalable solution for managing shared secrets.

**Additional context**

Our infrastructure consists of approximately 500 microservices, and there are scenarios where a secret, such as an API password, needs to be shared among many microservices. The introduction of the `{secret}` prefix would not only enhance the flexibility of managing shared secrets but also contribute to a more efficient and scalable configuration setup for large microservices architectures.

**Contributions**

I am available and willing to create a pull request to implement this feature once the proposal is reviewed and accepted by the Spring ConfigServer project maintainers.

**Comment by ryanjbaxter** [comment]
The config server looks for something in the backend named `application` all properties within this store is served to all microservices.  For example with Vault you could do

```
vault kv put secret/application foo=bar baz=bam
```

Every microservice that request configuration from the config server would then receive the `foo` and `baz` properties.

And with AWS Secret Manager

> When using AWS Secrets Manager as a backend, you can share configuration with all applications by placing configuration in /application/ or by placing it in the default profile for the application. 

Is this not what you are requesting?

**Comment by sergioasantiago** [comment]
Hi @ryanjbaxter, thank you for your prompt response.

While the solution you provided is appreciated, it doesn't precisely align with our requirements.

Our objective is to maintain a dual backend approach, utilizing `git` for non-sensitive data and `vault` for managing secrets. We employ a `composite` configuration to merge the outcomes seamlessly. The configuration snippet is as follows:

```yaml
spring:
  cloud:
    config:
      server:
        encrypt:
          plainTextEncrypt: true
        composite:
          - type: git
            uri: git@mygithub.com:configuration/{application}.git
            default-label: master
            ignoreLocalSshSettings: true
          - type: git
            uri: git@mygithub.com:configuration/global.git
            default-label: master
            refreshRate: 86400
          - type: vault
            host: vault.myhost
            backend: configserver
            kvVersion: 2
            authentication: TOKEN
```

During startup, services request configurations using their service names (e.g., `myservice`). This retrieves keys from:

- `mygithub.com:configuration/myservice.git`
- `mygithub.com:configuration/global.git`
- `vault: /configserver/myservice`

This setup works seamlessly when secrets for `myservice` are located under `/configserver/myservice`. Our secret schema looks like this:

```
/configserver/rds/myservice/password
/configserver/apipassword/anotherservice
```

To enhance maintenance, we propose the ability to reference secrets in the git configuration, such as:

```yaml
{vault}/configserver/apipassword/anotherservice
```

or a more generic form:

```yaml
{secret}/configserver/apipassword/anotherservice
```

This would prompt the configserver to fetch the secret by path from the configured secret backend (in this example, Vault). This approach streamlines management, especially when identical secrets are used across multiple services, like `/configserver/apipassword/anotherservice`. Additionally, we can create namespaces like `/configserver/rds` to organize secrets efficiently.

I trust this clarifies our request. Feel free to reach out if you require additional details. Thanks.

**Comment by ryanjbaxter** [comment]
I am not sure I am understanding the problem....

It seems like if you structured your secrets like this:

```
/configserver/application/
```

And placed all common secrets under there all applications would get these properties.

However since you have chosen to structure your secrets differently you cannot do this?

I also don't understand why your git configuration would reference these common configurations.

Why wouldn't you set

```
configserver/apipassword apipasswordproperty=mypassword
```

in Vault?

Why would you set the property in Git and then reference the value in Vault?

**Comment by sergioasantiago** [comment]
Consider a scenario with three services: ServiceA, ServiceB, and ServiceC.

ServiceA needs to make requests to ServiceC, and ServiceB also needs to make requests to ServiceC. Both ServiceA and ServiceB require the `apiPassword` for ServiceC.

With the current configserver implementation, two separate secrets are needed in Vault:

```plaintext
/configserver/ServiceA serviceCApiPassword=mypassword
```

```plaintext
/configserver/ServiceB serviceCApiPassword=mypassword
```

Consequently, when ServiceA requests its configurations, it retrieves the `apiPassword` to connect to ServiceC, and the same process occurs for ServiceB.

The desired outcome is to streamline this process by having a single secret:

```plaintext
configserver/ServiceC apiPassword=mypassword
```

In the configurations for both ServiceA and ServiceB, we aim to reference the Vault path:

```yaml
{vault}configserver/ServiceC
```

This approach eliminates the need for duplicated secrets. While this example highlights only two instances of duplicated secrets, envision scaling it up to a scenario involving 500 microservices that share common secrets. The goal is to enhance efficiency and simplify secret management across a large-scale microservices architecture.

**Comment by ryanjbaxter** [comment]
This can be accomplished with 
```
/configserver/application serviceCApiPassword=mypassword
```

Both ServiceA and ServiceB will get `serviceCApiPassword` when fetching their configuration from the config server

**Comment by sergioasantiago** [comment]
Yes, indeed it can, but also a ServiceX would get this secret even though it is not needed, so that would be a security issue leaking secrets to all services.

**Comment by ryanjbaxter** [comment]
Ok so what you really want is a list of applications allowed or a list of applications not allowed?

that seems like a much simpler way to accomplish what you are looking for

**Comment by sergioasantiago** [comment]
I guess I know what you are about to suggest. The service sends the token and we link the secrets to the token sent by the service. Yes, that would definitely work. But we can't use client authentication in our use case (for many other reasons), we need to use server authentication (configserver authenticate to vault)

**Comment by ryanjbaxter** [comment]
Got it.  I could imagine something on the config server that specify which application names will get the common configuration properties from `application`.  We could also offer a property the does the opposite and instead is an exclusion list.

**Comment by sergioasantiago** [comment]
I'm not sure if I fully understand that. How that would look like?

**Comment by sergioasantiago** [comment]
I stumbled [here](https://github.com/spring-cloud/spring-cloud-config/blob/3e423e5d3123f28f11f295f33a505439a2669343/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/encryption/vault/VaultEnvironmentEncryptor.java) by accident. 

This looks like exactly what I planned to have.
So I need to enable the `vault` profile and set the value starting with `{vault}`.

**Comment by sergioasantiago** [comment]
I just did some tests and it does exactly what is needed for this use case.

- I needed to set the configuration for Vault under spring, not under composite.
```
spring:
  cloud:
    config:
      server:
        vault:
          backend: configserver
          skipSslValidation: true
          kvVersion: 2
          authentication: TOKEN
          token: "mytoken"
```
- I need to enable the vault profile
- I need to use the following pattern to set the key: `one: "{vault}:rds/testdatabase#password"`
- My secret is stored in vault like this:
<img width="496" alt="image" src="https://github.com/spring-cloud/spring-cloud-config/assets/875058/b385617b-18dd-478f-bda3-86f764680765">

So in the end, it is a matter of lack of documentation since I could not find any mention about this feature in spring cloud docs.

**Comment by ryanjbaxter** [comment]
Huh I didnt even know about that.  Would you be interested in adding some docs on this?

**Comment by sergioasantiago** [comment]
Sure, I can take a look. Which section do you suggest to put this?

**Comment by ryanjbaxter** [comment]
I would say here
https://github.com/spring-cloud/spring-cloud-config/blob/4.0.x/docs/src/main/asciidoc/spring-cloud-config.adoc#vault-backend

**Comment by pukkaone** [comment]
I implemented something similar for AWS Secrets Manager.  The [AWS Secrets Manager repository](https://docs.spring.io/spring-cloud-config/reference/server/environment-repository/aws-secrets-manager.html) imposes a secret naming convention, but I wanted more flexibility in naming secrets.  A custom configuration overrides the `{cipher}` prefix resolver to [read secrets from AWS Secrets Manager](https://gist.github.com/pukkaone/280da23000030d5bc0c729fbcca1c014).  An application property can specify a secret ARN or secret name:
```yaml
spring:
  datasource:
    password: '{cipher}spring-cloud-config/payment-service/spring.datasource.password'
```

**Comment by pukkaone** [comment]
There is already issue #1785 to document the `{vault}` decryptor.

**Comment by kk1726** [comment]
can we use secrets in github . Could some one help on this. We are planning to store our application secrets in github secrets. Our spring cloud config server fetches the secrets  like db passwords ...etc from github secrets. Pls share some links if any for setup.

**Comment by ryanjbaxter** [comment]
Please open a separate issue for this
