### ISSUE TITLE
spring.cloud.config.retry.useRandomPolicy not being applied

### ISSUE THREAD

**Issue by marnee01** [spring-cloud/spring-cloud-config#2379]
I see in https://github.com/spring-cloud/spring-cloud-config/pull/2353, that support was added for the `spring.cloud.config.retry.useRandomPolicy` property. However, it's not actually being applied when I run one of our ConfigServer clients.   (I observed this by adding a break point in `RetryProperties,isUseRandomPolicy()`. It's never being called. Note that we have `spring.config.use-legacy-processing=true`.

**Analysis:** The retry appears to be configured in ConfigServiceBootstrapConfiguration.configServerRetryInterceptor. In spring-cloud-config-client-4.0.5.jar, I see that the RetryInterceptorBuilder is not calling the retryPolicy builder method. Was that a miss in the above-mentioned PR?

**Comment by ryanjbaxter** [comment]
Yeah I think you are right.  You are using bootstrap configuration then and not leveraging `spring.config.import`?

**Comment by marnee01** [comment]
> Yeah I think you are right. You are using bootstrap configuration then and not leveraging `spring.config.import`?

Yes, that's correct.
