### ISSUE TITLE
misconfigured spring.cloud.config.server.git fails only on first usage, not on app start

### ISSUE THREAD

**Issue by sanderkerel** [spring-cloud/spring-cloud-config#238]
I am using spring cloud config server 1.1.0.M1 in my spring boot application (1.3.0.M5).

When I misconfigure application.properties with a wrong git-url, I would like that to fail early, I want to get the error on starting up.
my application.properties: 
`spring.cloud.config.server.git.uri=https://lalala.woopsie`

Instead, the application starts without complaining. I only get to see an error-stacktrace on the first attempt to access a property by a client.

Please fix it by making it fail early, when the config server starts.

**Comment by edethoor** [comment]
I think you could use the cloneOnStart option.

**Comment by sanderkerel** [comment]
`spring.cloud.config.server.git.cloneOnStart=true` in the properties does do the trick, thanks!
