### ISSUE TITLE
Case sensitive headers in web hooks

### ISSUE THREAD

**Issue by sergiorc** [spring-cloud/spring-cloud-config#240]
Two issues about github monitoring:

To retrieve github hook call, I have had to define a GithubPropertyPathNotificationExtractor:

```
@Bean
	public PropertyPathNotificationExtractor githubPathExtractor() {
		return new GithubPropertyPathNotificationExtractor();
```
If this is the desired way to configure git provider, It should be included in documentation.
Perhaps, extractor implementation could be retrieved parsing git uri path.

Second issue is related with headers case.
My config server is using Brixton.M1 parent and default configuration

```
@Configuration
@EnableAutoConfiguration
@EnableConfigServer
```
I have no idea why every request done against config server is received with http headers in lowercase.
This is causing GithubPropertyPathNotificationExtractor doesn't work, because X-Github-Event header is not found, but the behaviour is general.

Request against EnvironmentController are also coming with lowercase headers.
I'm using a RequestDumperFilter to show requests headers.

Request againts my application service (Spring Boot + Spring Cloud config client) are coming with correct headers.

**Comment by dsyer** [comment]
`Brixton.M1` is probably not a great way to test this since the monitor jar is only available in snapshots. Can you try again with a snapshot please? Headers should be case insensitive, but maybe that was fixed in master.

Pull requests for documentation are always more than welcome. On the other hand I see no reason why the github and gitlab extractors shouldn't be included as defaults. Do you want to do that?

**Comment by sergiorc** [comment]
You are right about Brixton.M1, I should be using snapshot for everything. Not only for monitor.
It's perfect for me both github and gitlab extractors are included by default. The problem, currently (at least in my tests), is that no one is included.

I'll test using cloud-config snapshots.

**Comment by sergiorc** [comment]
Testing with Brixton.BUILD-SNAPSHOT I got the same behaviour

```headers.getFirst("X-Github-Event")``` returns null because header is lowercase

**Comment by spencergibb** [comment]
I got the same problem while writing [this blog post](http://spencer.gibb.us/blog/2015/09/24/spring-cloud-config-push-notifications/). I thought I had pushed my fixes, hadn't. See #242.

**Comment by dsyer** [comment]
I think I fixed the case sensitive issue. If there is something else please open another issue.
