### ISSUE TITLE
Enable force refresh by forceRefresh query parameter regardless of refreshRate

### ISSUE THREAD

**Issue by opeco17** [spring-cloud/spring-cloud-config#2401]
**Is your feature request related to a problem? Please describe.**
[refreshRate](https://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.0.2.RELEASE/single/spring-cloud-config.html#_git_refresh_rate) is useful to scale Cloud Config clients.
However, we want to make sure that some important clients can get the latest configurations regardless of refreshRate.

**Describe the solution you'd like**
Allow force refresh regardless of refreshRate by using forceRefresh query parameter.

**Describe alternatives you've considered**
We can temporarily update refreshRate to 0 while some important clients access Cloud Config
But the new refreshRate is effective for all Cloud Config clients and Config Server might receive huge traffic during that period.
Also updating refreshRate manually every time is tough for operators.

**Additional context**
PR: https://github.com/spring-cloud/spring-cloud-config/pull/2402

**Comment by spencergibb** [comment]
Closing in favor of #2402
