### ISSUE TITLE
Provide a non-Git enabled option tightly integrated with CF

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-config#241]
This issue may be more of a CF issue than a Spring Cloud Config issue but I want to start here:

Having gone through the process of deploying an app to PWS, I believe we should provide a much better configuration experience for CF users. While using Spring Cloud Config + Git is technically the best solution, it is odd to basically require Git to have decent configuration experience. Plus you would need a paid-GitHub account in order to create private repos.

When deploying Spring Boot applications to PWS, you have basically the following options in regards to configuration management without using external services:

* Encode properties into your Jar/War
  - Seems like an anti-pattern
* Use Environment Variables
  - Will be tedious if you have lots of properties to customize
  - Only option that provides UI support  
* Use CF User Defined Services
  - Will pollute your `application.yml`
  - Tricky to set up - [See Article](https://www.ibm.com/developerworks/community/blogs/binhn/entry/creating_user_provided_service_with_complex_values?lang=en)
  - User Defined Services seem to be more geared towards credentials, so feels awkward for non-credential properties
  - Cannot change properties via UI

Would it maybe make sense to populate configuration properties using JSON in a single environment variable and have Boot to pick that up automatically? I guess one could implement my their `PropertySourceLocator`...

Ideally, it would be VERY nice if Spring Cloud Config provided an integrated Spring Cloud Config experience (I should not even have to know wether it is Git underneath or something else):

* Provide UI to add/edit/remove properties
* Upload a Yaml file with my custom properties
* Provide command-line support to setup properties in bulk, e.g. read from a yml or json file

**Comment by spencergibb** [comment]
Both [bitbucket](https://bitbucket.org/product/pricing) and [gitlab](https://about.gitlab.com/gitlab-com/) both host free private repos, so payment isn't an issue. There is [talk](https://twitter.com/wattersjames/status/644634786850566144) of a gitlab tile for CF.

So far config-server has maintained a read-only stance. A ui for editing would likely come from the spring-cloud-services team. 

There is also #203 which would back config server via a db. A ui for editing would be dependent on the back end, edit whole files with git, individual properties with a db.

/cc @mstine @dsyer

**Comment by dsyer** [comment]
Personally, I never want to see code for editing files in git (or other SCM repository) in this code base. I guess it's fair game if the Cloud Foundry folk want to go down that route for the platform.

I guess I don't really understand the problem. You don't want to put stuff in your YAML (why?), and you don't want to create user-provided services (why?), and you don't want to set environment variables. Those seem like perfect solutions for standalone apps. Is it only where there is an existing config server that you feel you need an additional feature?

**Comment by spencergibb** [comment]
This is a [gitlab tile](https://about.gitlab.com/2015/11/03/pivotal-cloud-foundry-tile-for-gitlab-ee/) for pcf now. @ghillert @dsyer any reason to keep this open?
