### ISSUE TITLE
Config file same key overriding order/precedence

### ISSUE THREAD

**Issue by krshna-dtdl** [spring-cloud/spring-cloud-config#2414]
We are facing [this issue](https://github.com/spring-cloud/spring-cloud-config/issues/2205) again with upgraded dependencies.

We are using org.springframework.cloud:spring-cloud-config-server:jar:4.1.1:compile

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
