### ISSUE TITLE
Support for Spring Boot 3.3.0

### ISSUE THREAD

**Issue by DavidHaasz** [spring-cloud/spring-cloud-config#2429]
The latest version of the spring-cloud-starter-config dependency does not currently support Spring Boot 3.3.x and attempting to upgrade Spring Boot results in the following upon starting the application

```
***************************
APPLICATION FAILED TO START
***************************
Description:
Your project setup is incompatible with our requirements due to following reasons:
- Spring Boot [3.3.0] is not compatible with this Spring Cloud release train
Action:
Consider applying the following actions:
- Change Spring Boot version to one of the following versions [3.2.x] .
You can find the latest Spring Boot versions here [https://spring.io/projects/spring-boot#learn]. 
If you want to learn more about the Spring Cloud Release train compatibility, you can visit this page [https://spring.io/projects/spring-cloud#overview] and check the [Release Trains] section.
If you want to disable this check, just set the property [spring.cloud.compatibility-verifier.enabled=false]
============================
CONDITIONS EVALUATION REPORT
============================
Positive matches:
-----------------
    None
Negative matches:
-----------------
    None
Exclusions:
-----------
    None
Unconditional classes:
----------------------
```

know we could disable the verifier but that might uncover other incompatibilities or problems that might be outside of powers to self-fix.

Would it be possible to have a new version which supports the latest Spring Boot 3.3.x version

**Comment by ryanjbaxter** [comment]
Which version of Spring Cloud are you using with Spring Boot 3.3.0?

**Comment by DavidHaasz** [comment]
```
<dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-config</artifactId>
      <version>4.1.2</version>
</dependency>
```
is the version we are using

**Comment by ryanjbaxter** [comment]
I am not able to reproduce this using Spring Boot 3.3.0 and Spring Cloud 2023.0.2.  Can you please try using dependency management instead of managing the version explicitly

```
<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>2023.0.3</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

If you are still having a problem please provide a sample to reproduce the issue.

**Comment by deryoman** [comment]
@DavidHaasz Do you use other dependencies that rely on spring boot? I had the same issue, but the issue was that I was using `io.awspring.cloud:spring-cloud-aws-dependencies` which is currently incompatible with spring boot > 3.2.x.

**Comment by ryanjbaxter** [comment]
Glad you got it figured out!
