### ISSUE TITLE
Upgrade AWS SDK packages to 2.18.41

### ISSUE THREAD

**Issue by cmxconsulting** [spring-cloud/spring-cloud-config#2435]
Currently, the AWS Sdk version used is the Spring Cloud config is 2.17.195.
Unfortunately, we are using on our side some features available from 2.18 and more. 
As the 2.17.195 was released in may 2022, it should be good to update it to a latest version. Currently the latest version is 2.26.8
https://mvnrepository.com/artifact/software.amazon.awssdk/aws-core

Can you upgrade your project to use the 2.26.8 in your pom.xml ?
Currently : `<aws-java-sdk.version>2.17.195</aws-java-sdk.version>`
New value : `<aws-java-sdk.version>2.26.8</aws-java-sdk.version>`

This is causing Class exception in our application due to version mismatches between the aws SDK dependencies.

Thank you.

**Comment by ryanjbaxter** [comment]
We would potentially upgrade to 2.18 in a point release but not to 2.26.  If we upgraded to 2.18 would that address the issue?  We would need to wait until our 2024 release to upgrade to 2.26

**Comment by cmxconsulting** [comment]
Hello, It should be ok with 2.18, so I can suggest the latest 2.18 which is 2.18.41.
When do you plan to release your 2024 release ?
Thank you.

**Comment by cmxconsulting** [comment]
Pull request created : https://github.com/spring-cloud/spring-cloud-config/pull/2436
Thank you.

**Comment by ryanjbaxter** [comment]
We dont have a planned date yet for 2024, but I have merged the PR and it will be in our next 2023 release
