### ISSUE TITLE
Sprin cloud config server- I am trying to clone data in linux machine user defined directory instead of linux default system directory /tmp/config-repo-

### ISSUE THREAD

**Issue by arc872014** [spring-cloud/spring-cloud-config#2442]
As per Spring cloud documentation-

With VCS-based backends (git, svn), files are checked out or cloned to the local filesystem. By default, they are put in the system **temporary directory with a prefix of config-repo-**. On linux, for example, it could be /tmp/config-repo-<randomid>. Some operating systems routinely clean out temporary directories. This can lead to unexpected behavior, such as missing properties. To avoid this problem, change the directory that Config Server uses by setting **spring.cloud.config.server.git.basedir or spring.cloud.config.server.svn.basedir to a directory that does not reside in the system temp structure.**

We are trying to clone the data to user defined location /var/**/configserver/data using below configuration for the same **but it doesn't create.** Please suggest. To be informed , we are using **Java 17, Spring boot 2.7.0 , Spring cloud 2021.0.3 which loads config server and config client dependencies with version 3.1.3**

spring:
  cloud:
    config:
      server:
        prefix: /config
        composite:
        -
          type : git
          uri: git@github.com:xyz/eai-123-{application}_${levelname}.git
          ignoreLocalSshSettings: true
          passphrase: ${PASSPHRASE}
          privateKey: ${DEPLOY_KEY}
          **basedir: /var/abc/configserver/data**
          clone-on-start: true
        -
          type: git  
          uri: git@github.com:xyz/eai-123-common_${levelname}.git
          bootstrap: true
          ignoreLocalSshSettings: true
          passphrase: ${PASSPHRASE}
          privateKey: ${DEPLOY_KEY}
          **basedir: /var/abc/configserver/data**
          clone-on-start: true

Please ignore if pasted configuration here, has any space issues, it may be because of copy paste. My original yml does not have any space issues so is a valid yml.

**Comment by ryanjbaxter** [comment]
We no longer support this version of Spring Cloud plus update to Spring Cloud 2023.0.x and try and reproduce the error.  If you can still reproduce the error please provide details on the error you are seeing.

**Comment by arc872014** [comment]
Thanks for your response. I am closing the issue for now as i can't upgrade the spring cloud version for now.
