### ISSUE TITLE
Support for Targeted Property Refresh in /actuator/refresh Endpoint

### ISSUE THREAD

**Issue by samuelj90** [spring-cloud/spring-cloud-config#2453]
Question : 

Hello @spring-cloud-issues, @spring-cloud Team,

I'm currently using the Spring Boot Actuator's `/actuator/refresh` endpoint to refresh my application's properties. However, I've noticed that the endpoint triggers a full refresh of all property sources. The issue with this approach is that some encrypted properties always cause Spring beans to reinitialize.

I wanted to confirm if there's any support for a more granular refresh mechanism, where specific properties or beans can be targeted for refresh instead of reloading the entire property source. If this isn't supported, are there any plans to introduce this feature in future releases?

**Comment by ryanjbaxter** [comment]
Please don't open the same issue across multiple projects.  Closing in favor of
https://github.com/spring-cloud/spring-cloud-commons/issues/1370
