### ISSUE TITLE
Health indicator configuration property is documented incorrectly

### ISSUE THREAD

**Issue by blackr1234** [spring-cloud/spring-cloud-config#2457]
## The issue

According to the [Health Indicator](https://docs.spring.io/spring-cloud-config/reference/server/health-indicator.html) document page,

> You can disable the Health Indicator by setting `management.health.config.enabled=false`.

In reality, the actual configuration property is `spring.cloud.config.server.health.enabled=false`. As per my testing, only this configuration property will skip the `configServer` health component, meaning that it will not call `EnvironmentRepository#findOne`.

Please help update the documentation accordingly, thanks.

**Comment by ryanjbaxter** [comment]
Using `management.health.config.enabled=false` worked for me.  Can you provide a sample?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by mircea-lemnaru-aera** [comment]
Hi All, 

I have encountered the same issue @blackr1234 has. According to the documentation for the config server , the property: `management.health.config.enabled` should disable the config server health endpoint. But in reality it doesn't. 

This property will disable the `org.springframework.cloud.config.client.ConfigServerHealthIndicator` ( from client ) ... the server side class: `org.springframework.cloud.config.server.config.ConfigServerHealthIndicator` is controlled by the property `spring.cloud.config.server.health.enabled`. 

I am using spring cloud config server version 4.3.0

@ryanjbaxter I propose we reopen this and update the documentation. Thank you

**Comment by ryanjbaxter** [comment]
@mircea-lemnaru-aera this was addressed here https://github.com/spring-cloud/spring-cloud-config/commit/2587c80b4107b36c51580222e362ca896c7132fd
