### ISSUE TITLE
wrong decryption of password/cipher

### ISSUE THREAD

**Issue by imod** [spring-cloud/spring-cloud-config#246]
Following the description at http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_encryption_and_decryption I tried to encrypt and decrypt my passwords. This works all fine, unless the password contains a "+" (plus) sign. If I decrypt the cipher of a encrypted password with a "+" then the resulting string does not contain the "+" anymore.

e.g. 
```
$> curl localhost:8080/encrypt -d myp+ass
$> 3bd5c274f5d5bdcb9c93069a370a17ca4b8abc8174e8178a2f36134758d946f9
$> curl localhost:8080/decrypt -d 3bd5c274f5d5bdcb9c93069a370a17ca4b8abc8174e8178a2f36134758d946f9
$> myp ass   # -> missing "+"
```
I also tried with with escaping "myp\+ass", but it does not help either.
This seem not like such a big deal when you have the chance to define your passwords by yourself, but when the passwords are generated then this is a blocker (like on AWS).

**Comment by dsyer** [comment]
See also https://github.com/spring-cloud/spring-cloud-cli/issues/11

**Comment by dsyer** [comment]
It works if you encode the input: 

```
$ CIPHER=`curl localhost:8888/encrypt -d my%2Bpass`
$ curl localhost:8888/decrypt -d $CIPHER
my+pass
```

**Comment by spencergibb** [comment]
yes, I've seen the same thing, the data needs to be urlencoded.

**Comment by dsyer** [comment]
We should include that in the docs I guess. But I don't think there's anything to change in the config server.

**Comment by spencergibb** [comment]
I agree.

**Comment by imod** [comment]
:+1: yes, encoded works - thanks!
