### ISSUE TITLE
Profile precedence issue

### ISSUE THREAD

**Issue by sergiorc** [spring-cloud/spring-cloud-config#249]
I'm not sure what component is causing this issue, but it's impacting in configuration retrieval.
I'm using Brixton.M1 in both client and config server and trying to recover configuration for "ci" profile.

I have make tests using .properties and .yaml configuration. 

Case A

Using .properties, I have a default configuration file and the "ci" extension:
 - appname-ci.properties
 - appname.properties

Enabling "ci" profile in client and retrieving configuration from client brings all PropertySources (both files), but appname.properties is recovered in second order, and its content is having precedence.
Default profile has precedence over active profile.
A good way to trace the problem is debugging RefreshEndpoint in refresh method.
It always returns no changes in "ci" profile configuration, and changes does not apply.

Case B

Using .yaml file
In this case, it works ok, configuration of active profile is having precedence, and changes are applied after RefreshEndpoint invocation.
However, although refresh applies configuration changes, the method returns no content.

**Comment by dsyer** [comment]
I'm not clear if you think there is a problem with the YAML case or not (if so it seems like it would be a different issue, so can you open a new ticket if there is something to report, please?).

Is this a regression from Angel, or are you just now looking and finding the problem only in Brixton?

**Comment by dsyer** [comment]
The scenario you described with the properties files works as expected for me (with Brixton snapshots, but I don't know if anything changed). Maybe if you have a sample project that would help us to understand the issue better?

**Comment by sergiorc** [comment]
I've created 3 small sample projects (client, server and config) and now it's more clear for me what's happening.
Sorry, forget distinctions between YAML and .properties. They have the same behaviour.

Profile precedence is always applying successfully, the Case A was produced for an unrelated problem.

The precedence problem is only happening in RefreshEndpoint returned body (both Brixton.M1 and Brixton snapshots). The returned array is always empty.

https://github.com/sergiorc/client
https://github.com/sergiorc/config-repo
https://github.com/sergiorc/configserver

Steps to reproduce:
-start client (with "ci" profile enabled) and configserver.
-Change property in foo-ci.properties and push (using another repo)
-Make POST to http://localhost:8080/refresh
-body is empty

Thanks a lot

**Comment by dsyer** [comment]
This is an issue in spring-cloud-commons: https://github.com/spring-cloud/spring-cloud-commons/issues/73. Please follow up there if you need to track progress, thanks.
