### ISSUE TITLE
Support non-Boot client Spring applications

### ISSUE THREAD

**Issue by spencerwi** [spring-cloud/spring-cloud-config#25]
In its current form, Spring Cloud Config is only good for software projects starting now using Spring Boot that anticipate scaling up in the future. Existing Spring webapps that do not use Spring Boot (even those on Spring 4...) can't make use of Spring Cloud Config at all -- at least, not according to existing documentation.

Spring Boot and Spring Cloud Config seem aimed at two totally-disjoint user bases: Spring Boot is aimed at getting a small app up and running quickly, and allowing developers to build out enterprise-grade control later as they move further out and away from Boot's "automagic"; Spring Cloud Config is aimed at managing multiple large multi-environment enterprise-grade applications.

For anecdotal evidence: I work at a company looking to scale up our existing Spring 4 webapp (assembled _without_ Boot), and would like to be able to use Spring Cloud Config for managing per-environment configuration of our app. But since Spring Boot is a prerequisite for Spring Cloud Config, the benefits of Cloud Config are unavailable to us unless we tear out all of our existing Spring context setup and hoping Boot "automagically" picks the right results in every case.

**Comment by piefel** [comment]
A pity. Really. Not being able to integrate this into existing projects is a major hindrance.

**Comment by dsyer** [comment]
So did you try something that didn't work?

**Comment by piefel** [comment]
Actually, no. Without guidance, I don’t know how to start. The documentation mentions only Spring Boot annotations, and I have no clue how to do it without Spring Boot.

Alternatively, I could convert the projects to Spring Boot, but don’t know how to do that either. Our projects all use a different bootstrapping process (some use Dropwizard, some are legacy) and only later start up the Spring context.

**Comment by K-RAD** [comment]
Guess there's no update on this issue. I'm in the exact same situation.
