### ISSUE TITLE
Make spring cloud config server jar fully executable for linux

### ISSUE THREAD

**Issue by ursuad** [spring-cloud/spring-cloud-config#250]
In the new version of spring boot, you have the capability to make spring boot jars as **fully executable Linux applications**, as explained [here](http://docs.spring.io/spring-boot/docs/1.3.x-SNAPSHOT/reference/html/deployment-install.html#deployment-install).  To have this for the **spring cloud config server executable jar**, the following should be added in the pom file:
```xml
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <executable>true</executable>
    </configuration>
</plugin>
```

If a jar with this features would be available [here](http://repo.spring.io/libs-milestone/org/springframework/cloud/spring-cloud-config-server/1.1.0.M1/), for example, ready to download and run , it would facilitate automating spring cloud config server installation and deployments.

**Comment by dsyer** [comment]
I'm not sure we should do that because the jar is not readable by all ZIP implementations. It happens to work as an executable on Linux, but there are lots of other uses for the jar that would be ruled out if we did this.

**Comment by spencergibb** [comment]
Closing as the executable jar is no longer built and distributed via 15b5ca804e643b2733bb11b795ba9e16b2d83ace
