### ISSUE TITLE
"KeyStoreException: Keystore not specified" when only truststore is configured in config client configuration.

### ISSUE THREAD

**Issue by KrishnaST** [spring-cloud/spring-cloud-config#2514]
I have TLS enabled eureka server. Microservice is trying to fetch configuration from config server throws "KeyStoreException: Keystore not specified" when only truststore is configured. should be able to trust server certificate by truststore configuration. There is no mutual authentication.

Following is micro-service configuration
![image](https://github.com/user-attachments/assets/95276864-e632-4be7-a003-5a6fc955324f)

It seems that there is no way to configure truststore without configuring the keystore even when mutual authentication is not required.

org.springframework.cloud.configuration.SSLContextFactory  
![image](https://github.com/user-attachments/assets/c9e16005-c687-4dcc-9409-3f8b09c3edda)

Spring Config Client Version : 4.1.3

**Comment by ryanjbaxter** [comment]
Is that because `builder.loadKeyMaterial` throws an exception and we never call `builder.loadTrustMaterial`?  Can you provide a sample to reproduce the error?

**Comment by KrishnaST** [comment]
Here is a minimal sample to reproduce the error.

https://github.com/KrishnaST/Config-Client-TLS-Issue

**Comment by KrishnaST** [comment]
I am still facing the issue even with Spring Boot 4.0.1 & Cloud config 5.0.0

**Comment by ryanjbaxter** [comment]
Does the sample above still reproduce the issue?
