### ISSUE TITLE
Question: HealthCheck ignoring spring.cloud.consul.config.enabled

### ISSUE THREAD

**Issue by tehjakey** [spring-cloud/spring-cloud-config#253]
I have a springboot app using spring-cloud-consul-config:1.0.0.M2 to read config from an external consul server. If my spring.could.consul.host is misconfigured the /health check endpoint reports "DOWN" even though the spring.cloud.consul.config.enabled=false. I was expecting spring.cloud.consul.config.enabled to remove consul considerations from the /health check.

With a properly configured and reachable spring.could.consul.host the /health check then passes even when the spring.cloud.consul.config.enabled=false

Can you confirm this is the desired behavior?

**Comment by spencergibb** [comment]
This is the wrong issue tracker. Please open the issue here: https://github.com/spring-cloud/spring-cloud-consul/issues
