### ISSUE TITLE
Slow response times

### ISSUE THREAD

**Issue by marek-obuchowicz** [spring-cloud/spring-cloud-config#255]
We are running ~50 EC2 instances. They run behind an ELB, which is calling spring boot actuator health URI each 10seconds. On each request like that, services connect to ProxyServer and fetch new configuration. Strange is that response time on ConfigServer is >400ms. We're running it with activated profile "native" and our configuration is server from YAML files embeeded into jarfile - no external connections to git etc are required, so it should be superfast - at the moment it delivers >400 ms response time for each request and causes 3 machines with 2CPUs to have load ~50%, which is stranegly much for such an easy service.

**Comment by dsyer** [comment]
I guess maybe switching off the config server health indicator would be the first obvious step. As for the latency, it is of course impossible to say why you have such an issue without a lot more detailed analysis.  If you can help to uncover what is going on in more detail we can certainly see whether it makes sense to address your issue here or not. A guess: are you doing a lot of crypto in the shared `application.yml`?

**Comment by marek-obuchowicz** [comment]
We're using really basic ConfigServer setup:
https://gist.github.com/marek-obuchowicz/3a1c9b524bb7fac28c7a
 + `inMemoryAuthentication` with one possible username/password

In `src/main/resources/consigs/application.yml` all the values are in clear text, no crypto at all.

The strange thing in log output of ConfigServer is that each time a new applicationContext is created, not sure if it's correct? (https://gist.github.com/marek-obuchowicz/d56c786f70e751ece5ae).

How can I disable refreshing configuration for healthChecks?
I've tried setting in `configs/application.yml`:

```
spring:
  cloud:
    config:
      health:
        enabled: false
```
but apparently that's wrong way, as this doesn't change the behavior.

**Comment by dsyer** [comment]
> How can I disable refreshing configuration for healthChecks?

It's just `health.config.enabled` I think. That should work.

> The strange thing in log output of ConfigServer is that each time a new applicationContext is created, not sure if it's correct?

It's correct (that's how it loads the config files). You will notice that it is very fast (a few milliseconds it looks like). So your latency isn't coming from there. Can you get a more detailed log, or do some profiling locally?

**Comment by marek-obuchowicz** [comment]
I will try tomorrow `health.config.enabled=false` and will let you know.
About starting applicationContext: according to log I pasted into gist, it took 200 miliseconds actually: `Started application in 0.207 seconds (JVM running for 331894.715)`.
I'd be happy to provide more detailed logs, any particular classpaths I should switch to debug in logger configs?

**Comment by dsyer** [comment]
It's all pretty fast for me locally (double digit millisecs). Can you verify that? It probably just means the disk is really slow in your EC2 instance. There are definitely ways to fix that, but my guess is it's better just to disable the health indicator. Your choice.

**Comment by spencergibb** [comment]
@marek-obuchowicz did dave's suggestion help?

**Comment by spencergibb** [comment]
Closing for lack of feedback.
