### ISSUE TITLE
Support for `Spring Boot 3.3.4` in `Spring Cloud 2023.0.x`?

### ISSUE THREAD

**Issue by JooHyukKim** [spring-cloud/spring-cloud-config#2559]
**Is your feature request related to a problem? Please describe.**

Now Spring Boot 3.3.4 is out, I was wondering if 2023.0 version would support it, and hopefully when?

**Describe the solution you'd like**

support? 

**Describe alternatives you've considered**

Alternative may be I can work on the supporting part? 

**Additional context**

**Comment by ryanjbaxter** [comment]
Spring Cloud 2023.0.3 should work with Spring Boot 3.3.4.
