### ISSUE TITLE
Optional synchronized server cache for mobile/front apps

### ISSUE THREAD

**Issue by alfonso-presa** [spring-cloud/spring-cloud-config#256]
We are planning to use the spring cloud config server in production but with some peculiarities:
* There are Spring applications using the spring cloud config client.
* We also want to expose the spring cloud config server to the internet for it to be consumed by Mobile applications.

We plan to run two instances of the server for each use case for security reasons, but for the mobile we are also facing a throughput problem.

If I understand correctly, the behavior of the spring cloud config server is to clone the git repo every time a configuration is requested. This is fair for server side clients, but it's not for mobile devices as there can be a huge amount of them.

My proposal to solve this is to add cache to the endpoints. The cache should:
- Be totally optional. It should be possible to disable it without affecting the server functionality.
- Be possible to be configured using CRON expressions, so you can for example set it to expire every odd number of minutes. This way if server's clocks are synchronized the response of the cloud config server cluster will be consistent.
- refresh asynchronously, so that while the git repo is being cloned in the background, the cached version is being served. This way the latency of the repository doesn't affect the clients.

I know it's possible to build this by embedding the cloud config server inside an spring boot application and adding a caché filter on top, but I think it's a useful functionality for the core project. If you think so I can try to build it for you and PR.

Thanks!

**Comment by dsyer** [comment]
The clone only happens once. Can you cache in a layer above the config server? If you can (and I don't see why not) then I don't really see the need for an additional cache native to the config server itself. It wouldn't be hard to add headers to hint at a load balancer, so if you need to make changes maybe that would be a useful first step.

**Comment by alfonso-presa** [comment]
@dsyer, thank you for your quick answer. 

Sorry, I didn't meant clone but `fetchs` from the git repo :-). This are done with every configuration request right?

A cache can be added on top easily if you're working in an on-premise scenario, but be are moving towards PaaS+micro-services, and I think that adding another tier on top will break the model. An API gateway will be a good place to cache, but be don't have any right now.

A possible scenario for this, for example, can be the CF 1.5 tile for spring cloud config server.... I don't think adding a reverse proxy on top of it will be a good practice (though I know you can achieve it with the static-buildpack), and also there's no possibility there to customize the tile implementation itself.

I know that there are workarounds for this, but I think that being scalable in amount of clients/requests is a must for this kind of services, and as a "user" I would like the service to be as much as self contained as possible so that my infrastructure doesn't get impacted by the software implementation details.

**Comment by spencergibb** [comment]
This scares me a bit
> We also want to expose the spring cloud config server to the internet for it to be consumed by Mobile applications.

**Comment by alfonso-presa** [comment]
@spencergibb Me too... But I don't see any good reason other than security and throughput. The first one is resolved by using two different instances of the config server. The second one is the one I'm trying to solve here :-). I know is a little bit off topic but, what are your objections?

**Comment by spencergibb** [comment]
@alfonso-presa my objection is putting config-server to the public. We built it so you can enhance it anyway you seem fit. I agree with dave, that you can implement a cache above config server.

**Comment by testark** [comment]
@spencergibb @dsyer why do you consider that exposing the config server to the public is a bad idea? We are facing the same need as @alfonso-presa (we need to expose configs to mobile apps).

**Comment by spencergibb** [comment]
> I don't see any good reason against it other than security and throughput

Config server was designed to serve as part of a microservices infrastructure, not as a user-facing API. You're free to build that as you see fit and use config server as a component, but we don't plan on supporting that directly.
