### ISSUE TITLE
Spring config monitor

### ISSUE THREAD

**Issue by hacbq** [spring-cloud/spring-cloud-config#258]
I'm using spring cloud config version 1.1 snapshop with spring config monitor + spring cloud bus amqp.
I'm have 2 cloud config client : service 1, service 2, config server.
When I post to config server: localhost:8888/monitor, only config server refresh my application.yml.
I post to localhost:8888/monitor again, service 1 refresh application.yml
And post to localhost:8888/monitor again, service 2 refresh its config.
In rabbit, I only see 1 queue binder.springCloudBus with 3 consumers

How do I config to both 3 service refresh their config. Sorry for my English :)

**Comment by spencergibb** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-bus/issues/21
