### ISSUE TITLE
Windows environment with git config server not returning propertySources

### ISSUE THREAD

**Issue by vandiedakaf** [spring-cloud/spring-cloud-config#259]
I think this is similar to issue #164 (actually, I think I'm having the exact same problem).

I'm trying to run a tutorial https://github.com/kennyk65/Microservices-With-Spring-Student-Files/blob/master/LabInstructions/Lab%203.md (which works in Linux) but when I attempt it in Windows it fails.

The propertySources are returned correctly when using
`<artifactId>spring-cloud-starter-parent</artifactId>` with version `<version>1.0.0.RELEASE</version>`
, however, as soon as I change it to a newer version (1.0.1.RELEASE or 1.0.2.RELEASE) then the response has an empty propertySources set.

**Summary:**
A Windows-based config server with a Git config repository works in version 1.0.0.RELEASE but not in the latest release 1.0.2.RELEASE.

**Comment by RobMaskell** [comment]
I'm running the `Brixton.M3` spring cloud config server, works fine on OSX reading from a private bitbucket repo, but won't work on windows. The local `file:` way works but not the direct connection to the repo. However I can connect just fine to the repo from SourceTree on the same windows machine so I don't think there is any enterprise gunk getting in the way.

**Comment by dsyer** [comment]
#164 is closed, so it this is the same (per the original post) then it is fixed. @RobMaskell if you have a new problem in Brixton, please open a new issue.
