### ISSUE TITLE
Codacy Badge URL Invalid in README.adoc

### ISSUE THREAD

**Issue by wickdynex** [spring-cloud/spring-cloud-config#2616]
## Describe the bug
I have found that the Codacy badge in the [README.adoc](https://github.com/spring-cloud/spring-cloud-config/blob/main/docs/src/main/asciidoc/README.adoc?plain=1) is invalid. This [image link](https://api.codacy.com/project/badge/Grade/f064024a072c477e97dca6ed5a70fccd?branch=master) and [related link](https://www.codacy.com/app/Spring-Cloud/spring-cloud-config?branch=master&utm_source=github.com&utm_medium=referral&utm_content=spring-cloud/spring-cloud-config&utm_campaign=Badge_Grade) currently inaccessible, resulting in the badge not displaying.

## Outcome
In the Home page, it looks like this:
<img width="996" alt="image" src="https://github.com/user-attachments/assets/25f797c8-545a-433f-91de-9c3c61549501">

## Expect
Please check the status on Codacy whether is valid, or generate a new badge. Looking forward to your reply.

**Comment by ryanjbaxter** [comment]
We actually dont even use Coday anymore so I removed that badge
https://github.com/spring-cloud/spring-cloud-config/commit/78c693b77c81125f7c549413dd312685f2aa4917

**Comment by wickdynex** [comment]
> We actually dont even use Coday anymore so I removed that badge
> https://github.com/spring-cloud/spring-cloud-config/commit/78c693b77c81125f7c549413dd312685f2aa4917

Thanks for your reply also your PR to fix this issue😊.
