### ISSUE TITLE
svnkit license is not as permissive as we would like

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-config#262]
Either rip it out or use the jni javaHL

https://subversion.apache.org/docs/javahl/1.8/org/tigris/subversion/javahl/package-summary.html

javahl
`brew install --java subversion`
http://subclipse.tigris.org/wiki/JavaHL#head-bb1dd50f9ec2f0d8c32246430c00e237d27a04fe

**Comment by dsyer** [comment]
I don't think this license is any worse than MySql or Neo4j or various other vendor jars that we integrate with. We should make sure we don't ship binaries that contain the svnkit jars, but depending on them for a build seems fine unless I missed something.

**Comment by spencergibb** [comment]
The commercial guys are ripping out svn support.

**Comment by dsyer** [comment]
They have to ship binaries though, right?

**Comment by spencergibb** [comment]
Yes, and they want to support SVN. @mstine care to comment?

**Comment by spencergibb** [comment]
So @mstine I'll let you and vinicius (what's his github handle?) decide if you want us to swap impl so you guys can add this back.
