### ISSUE TITLE
Restricting network interface being used

### ISSUE THREAD

**Issue by NickMk** [spring-cloud/spring-cloud-config#263]
Is there a way to constrict the config server to only run on a specific interface? Right now it looks like it's listening on all interfaces, but I'd like it to only run on localhost.

I saw the documentation on setting the port being used (the property being "server.port"). However, I didn't see anything for the interface.

**Comment by spencergibb** [comment]
Config server doesn't really have an opinion here, it just uses [spring-boot](https://github.com/spring-projects/spring-boot). [Looks like](http://docs.spring.io/spring-boot/docs/1.3.0.RC1/reference/htmlsingle/#boot-features-customizing-embedded-containers) you can set `server.address`.
