### ISSUE TITLE
Config server's ResourceController cannot handle labels with slashes

### ISSUE THREAD

**Issue by shakuzen** [spring-cloud/spring-cloud-config#264]
The [EnvironmentController](https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentController.java#L92) handles labels with slashes ("/") in them. However, the [ResourceController](https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/resource/ResourceController.java) does not have this same logic in it, and therefore fails to find labels when they have slashes in them (using "(_)" in place of the slash).

**Comment by dsyer** [comment]
It's a Spring MVC limitation. You need to use an escape ("/" -> "(_)"). See docs here: http://projects.spring.io/spring-cloud/spring-cloud.html#_environment_repository
