### ISSUE TITLE
Config Server - Dynamic property refresh is taking 30 seconds 

### ISSUE THREAD

**Issue by pradeepkusingh** [spring-cloud/spring-cloud-config#266]
Perf Test
Configuration = Cloud Foundry+ Spring Cloud
We have configured Config Server and put or property files in GITHUB, all controllers are coded with `@RefreshScope` annotations . while load test with 75 users , we have updated property files in git and try to refresh from browser to dynamically update all beans with new property. It is taking 30-50 seconds and sometimes timeout with bad gateway error. less user less time , more users more time.

can you please explain us the behavior?

**Comment by dsyer** [comment]
How many threads do you have on the client apps (i.e. is it possible for 75 concurrent requests to be executing concurrently)? I imagine that, in the worst case scenario, your load could lead to 75 concurrent requests to the config server for the updated properties, and you won't have 75 threads able to process them on the server, so they will have to wait for each other.

This change will probably reduce the load on the config server: https://github.com/spring-cloud/spring-cloud-commons/commit/aaa7288.

**Comment by dsyer** [comment]
No feedback. Assume not a problem any more.
