### ISSUE TITLE
Spring Boot 1.3.0 upgrade causes Spring Cloud Config 1.0.2.RELEASE Spring Core Conflict

### ISSUE THREAD

**Issue by willschipp** [spring-cloud/spring-cloud-config#270]
when upgrading Spring Boot dependencies to 1.3.0.RELEASE independently of Spring Cloud Config (1.0.2.RELEASE) there's a  java.lang.ClassNotFoundException: org.springframework.context.event.GenericApplicationListener due to a conflict in dependencies of core spring framework packages (spring-core is 4.2.3.RELEASE from spring-boot, spring-test is 4.1.6.RELEASE based on Spring Cloud Config)

Appears to come from conflict in package from "spring-cloud-config-client" package and direct reference to spring-web which pulls in 4.1.6.RELEASE and spring-cloud-starter which pulls in spring-boot-starter

**Comment by spencergibb** [comment]
@willschipp spring-cloud 1.0.x (Angel.x) is not compatible with spring-boot 1.3.x. That work is being done in Brixton. Brixton.M2 is compatible with spring-boot 1.3.0.RC1 and M3 will work with 1.3.0.RELEASE.
