### ISSUE TITLE
Encrypt fails to strip name/value prefixes

### ISSUE THREAD

**Issue by westse** [spring-cloud/spring-cloud-config#273]
See [pull request 272](https://github.com/spring-cloud/spring-cloud-config/pull/272) containing a unit test demonstrating the problem. Note that `decrypt()` masks the problem because it strips the prefix *after* decrypting the value.

**Comment by spencergibb** [comment]
From #272 

> Note that EncryptionController.decrypt() masks the problem by stripping prefixes twice, once prior to decrypting and once after decrypting the value.

**Comment by spencergibb** [comment]
Hey @westse how goes? So you're looking for parity between `EncryptionController.encrypt()` and  `EncryptionController.decrypt()`, is that correct?

**Comment by westse** [comment]
Going well @spencergibb! Not really parity. I update the PR with the proposed fix. Hopefully that clarifies things.

We discovered this because we used `EncryptionController.encrypt()` to encrypt values stored in Spring Cloud Config server, but use Spring Cloud Config client tor retrieve decrypted values and do *not* use `EncryptionController.decrypt()` (which would mask the issue).

**Comment by spencergibb** [comment]
Nice, thanks for the clarification.

**Comment by dsyer** [comment]
Merged PR
