### ISSUE TITLE
Config Server bootstrapping itself from its own Environment Repository

### ISSUE THREAD

**Issue by cah-oster** [spring-cloud/spring-cloud-config#276]
I'm planning to use the config server for a deployment that involves multi-application/teams, with a git backend where each team/application has its own git repository for their configuration.  The config server supports this concept well, but I'd like to avoid hard coding all the repositories, and especially their authentication information, in the application properties for the config server.  Ideally I would like to have the config server bootstrap itself by pulling the team repositories (spring.cloud.config.server.git.repos) from its own configuration git repository.  I would envision I would set the spring.cloud.config.server.git.uri value in the config server's bootstrap properties, which would be used to fetch its configuration from the default git repo (matching on spring.application.name just like its clients do).  In the configuration of this repository I would then maintain the other team specific repo settings (encrypting their authentication information using the config server's encryption key).  This would allow me to dynamically add and remove teams/applications, and keep all the sensitive information out of the config server's own properties file (which is the main reason I want to use it for other services).  Is this possible today? If not is it a reasonable enhancement request?

**Comment by dsyer** [comment]
Did you try it? I believe it is supported (but I don't recall if it's in 1.0 or not).

**Comment by dsyer** [comment]
This definitely is supported and documented (there's a `bootstrap` flag) and has sample apps (e.g. https://github.com/spring-cloud-samples/tests/tree/master/configserver-bootstrap).

**Comment by cah-oster** [comment]
Ok I will test it. I assumed that was for when embedding the config server and bootstrapping the "normal" components.
