### ISSUE TITLE
Creating a custom bootstrap context similar to Spring Cloud Config

### ISSUE THREAD

**Issue by efenderbosch** [spring-cloud/spring-cloud-config#281]
I'm looking to do something similar to what the Spring Cloud project does in creating a bootstrap context. We can't simply use spring-cloud-config because it (and/or the Netflix libraries) uses Jersey under the hood due to licensing restrictions. So I'm rolling my own ``PropertySource`` to read from a Curator ``TreeCache``.

In my bootstrap.yaml I'll need a property to specify the hosts in a Zookeeper cluster. I'm using that to configure a ``CuratorFramework`` and then a Curator ``TreeCache``. I've created a Spring ``PropertySource`` backed by the ``TreeCache``.

Example usage is currently like this:

```java
server = new TestingServer();
client = CuratorFrameworkFactory.newClient(server.getConnectString(), new ExponentialBackoffRetry(1000, 3));
client.start();
cache = new TreeCache(client, "/");
cache.start();

ConfigurableApplicationContext context = new SpringApplicationBuilder(). //
		sources(Test.class). //
		environment(CuratorEnvironment.using(cache)). //
		run(args);
```

I'd like to be able to push the Zookeeper connection string to a config, like bootstramp.yaml, which will stand up the ``CuratorFramework``, Curator ``TreeCache`` and my custom Spring ``PropertySource`` and, if possible auto-register the ``PropertySource`` in the ``ConfigurableEnvironment``.

I can't figure out how Spring Cloud knows how to read ``org.springframework.cloud.bootstrap.BootstrapConfiguration`` from ``META-INF/spring.factories`` to create the parent context. That string doesn't appear to be anywhere in the source tree. Where does that happen so I can do something similar?

Or is there a different approach that might work better?

Thanks.

**Comment by spencergibb** [comment]
Three things:

 1. spring-cloud-config does NOT use jersey. spring-cloud-netflix uses jersey. 
 1. `BootstrapConfiguration` comes from [spring-cloud-commons](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapConfiguration.java)
 1. Have you seen [spring-cloud-zookeeper](https://github.com/spring-cloud/spring-cloud-zookeeper)? We already have integration. ([Consul too](https://github.com/spring-cloud/spring-cloud-consul)).
