### ISSUE TITLE
Refresh mechanism

### ISSUE THREAD

**Issue by toolkit** [spring-cloud/spring-cloud-config#282]
Hi there,
I am researching if spring config server fits my requirements.
I have a cluster of nodes that make up a service.
I want a local cache of config in every node, and I don't want to rely on a config server, so I am looking to use the embedded one.
This presents a challenge in notifying the nodes when someone changes my git repo.
Is my best option to use a regular pull from my repo, and if so what is the config property for tuning the refresh rate?

**Comment by spencergibb** [comment]
If you're using a git server that supports webhooks you can use http://spencer.gibb.us/blog/2015/09/24/spring-cloud-config-push-notifications/, otherwise you're left to polling. You could use `@Scheduled` from spring-framework to implement polling.

**Comment by toolkit** [comment]
Not sure exactly where I would stick my Scheduled annotation. Shame there isn't a refresh property within the config server that I can use?

**Comment by spencergibb** [comment]
There is retry, but it's only available on [startup](https://github.com/spring-cloud/spring-cloud-config/blob/5ceca182924244edb4ca26a7618baeb5384aa33b/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServiceBootstrapConfiguration.java#L60).
