### ISSUE TITLE
Endpoints .properties return ": " as separator 

### ISSUE THREAD

**Issue by pwielgolaski** [spring-cloud/spring-cloud-config#285]
Shouldn't we use .properties format as here 
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html
It seems to be trivial change, but I wonder if there is typo or some bigger idea behind

https://github.com/spring-cloud/spring-cloud-config/blob/5ceca182924244edb4ca26a7618baeb5384aa33b/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentController.java#L138

**Comment by spencergibb** [comment]
According to [the oracle docs](https://docs.oracle.com/cd/E23095_01/Platform.93/ATGProgGuide/html/s0204propertiesfileformat01.html) colon ':' is a valid separator in properties files.  Maybe an option to use equals '='?

**Comment by pwielgolaski** [comment]
I was sure that "=" was the only one, but it seems that you are right. 
I dont mind to leave it as it is.

**Comment by otrosien** [comment]
@spencergibb is this a general move away from equals to colons / any reasonable rationale behind it? I noticed this in a different context as well - https://github.com/spring-guides/tut-spring-security-and-angular-js/pull/7 - and I still find it a bit strange, as the equals sign is the predominant character used in properties files. STS for example auto-inserts equals in code-completion...
