### ISSUE TITLE
If @RefreshScope is added, @Scheduled does not work any more

### ISSUE THREAD

**Issue by adrianciuc** [spring-cloud/spring-cloud-config#294]
The code works fine if `@RefreshScope` is not added on top of class, but when I add it under `@Component` annotation the method is not called any more.
I use spring boot 1.2.6.RELEASE
```java
@Component
public class SomeClass {

 @Scheduled(cron="some cron")
 public void someMethod() {
     System.out.println("\n\nyeeei !!\n\n")
 }

}
```

**Comment by dsyer** [comment]
Did you set `spring.aop.proxyTargetClass=true` (or equivalent)?

**Comment by spencergibb** [comment]
Shouldn't this go in spring-cloud-commons?

**Comment by adrianciuc** [comment]
@spencergibb  Sorry, I've just rushed a little bit.
@dsyer No I don't use `sping.aop.proxyTargetClass=true`. Is this a property that should be specified in application.properties ?

**Comment by adrianciuc** [comment]
I added `spring.aop.proxyTargetClass=true` in application.properties, ran the application, nothing changed. Also I set that property to `false` and the same result. Also I tried with `spring.aop.proxy-target-class` property  and didn't worked.

**Comment by dsyer** [comment]
Yes, this should go in spring-cloud-commons (if it turns out to be a problem that we can fix). I think it's just pilot error - the default proxy mode does not expose methods not in an interface, so you need to switch on target class proxies. I don't know why it's not working though, so we are going to need a sample app.

**Comment by RaviH** [comment]
I have the same exact issue and I tried with: 

```
spring.aop.proxyTargetClass=true
spring.aop.proxy-target-class=true
```

But no change. The scheduled method is not called anymore. The moment I remove `@RefreshScope, same method starts working again. I can provide a sample app, but creating one shouldn't be that difficult either. Please let me know if you would like me to provide a sample app?

**Comment by dsyer** [comment]
Please open an issue in spring-cloud-commons and include a link to a sample project.

**Comment by RaviH** [comment]
Created https://github.com/spring-cloud/spring-cloud-commons/issues/74 as requested.
