### ISSUE TITLE
@RefreshScope beans are always refreshed, even if there were no changes in the repository

### ISSUE THREAD

**Issue by erecarte** [spring-cloud/spring-cloud-config#296]
Hi,

I'm using Spring Cloud Config and I update my apps with remote changes by adding a `@Scheduled` operation every couple of minutes.

I was looking at the 'RefreshEndpoint` code:

```java
public synchronized String[] refresh() {
		Map<String, Object> before = extract(this.context.getEnvironment()
				.getPropertySources());
		addConfigFilesToEnvironment();
		Set<String> keys = changes(before,
				extract(this.context.getEnvironment().getPropertySources())).keySet();
		this.context.publishEvent(new EnvironmentChangeEvent(keys));
		this.scope.refreshAll();
		return keys.toArray(new String[keys.size()]);
}

```

Since this endpoint already does the calculation to see what properties have actually changed, wouldn't it make sense to only do the publishing of the event and the refreshing only if there were any changes? Something like this:

```java
public synchronized String[] refresh() {
        Map<String, Object> before = extract(this.context.getEnvironment()
           .getPropertySources());
        addConfigFilesToEnvironment();
        Set<String> keys = changes(before,
				extract(this.context.getEnvironment().getPropertySources())).keySet();
        if (keys.size() > 0) {
            this.context.publishEvent(new EnvironmentChangeEvent(keys));
            this.scope.refreshAll();
        }

        return keys.toArray(new String[keys.size()]);
}

```

My main concern is that for applications that can't have a Spring Cloud Bus and need to rely on something like `@Scheduled`, might have a performance impact if every couple of minutes all the `@RefreshScope` beans get reloaded.

Thanks!

**Comment by dsyer** [comment]
Tough, I think. That's the way it works (as designed). If you put a lot of logic in your refresh scope beans it will be slow, but I wouldn't really expect that to be necessary.
