### ISSUE TITLE
Spring Config client not receiving decrypted config properties from config server.

### ISSUE THREAD

**Issue by jgawli** [spring-cloud/spring-cloud-config#297]
I created a server.jks file and put it in resources directory in config server and added following properties in application.properties

```
encrypt.keyStore.location=classpath:/server.jks
encrypt.keyStore.password=${KEYSTORE_PASSWORD:mystore123}
#encrypt.keyStore.password=mystore123
encrypt.keyStore.alias=server
encrypt.keyStore.secret=mykey123
```

I have client specific myclient-application.properties which has security properties

```
security.user.name=admin
security.user.password={cipher}blahblahblah..
```

I created this password by calling encrypt endpoint.

And on Config client, I have common properties in application.properties and have bootstrap.properties. When I run config client I get following error.

```
java.lang.IllegalArgumentException: Could not resolve placeholder 'security.user.name' in string value "${security.user.name}"
```

Do I need to add any encrypt.key on config client and what will be that key. Please let me know what am I missing.

**Comment by dsyer** [comment]
Is there an error on the config server? Can you decrypt that value using the `/decrypt` endpoint? Does it show up decrypted in the `/myclient-application/default` resource?

**Comment by jgawli** [comment]
Sorry my bad, I didn't copy encrypted value properly. So now I just have server.jks file in config server, do I need to add anything on config client. According to documentation, encryption and decryption will be done on config server itself.

**Comment by jgawli** [comment]
When I put encrypted values of these properties, Config Server gives error when I try to start it
encrypt.keyStore.password={cipher}AQB/AXaJqWsnIuYNtla/j5IpJbLDir2aJrmvdv7E8WlPs9GoV5TOxSHPzNlE3sxbCHfFgM10Zq47AcggJ0OjE4V4XwUO46Z7DdF7LHzXyNMPhZgR2Ek4LOz1h8xXTMsS5Ai9GFPA08aAfGvVd1eGypAFouMfDjbk/8eA6jQraXfAaIEdqlHaikm1940CRp8gn3xIyg0N6dveiU7yf+To3RgqUkvEBBcy9vI5/VNdZS5HtivD7bKq60ZL0d9+/p4SA1jOv/aCdkqdJZ2S49EJ5zWHC0hAPpxk0pM9raUDBB6Fk9yx1nAY8Yf8J6q489eJb4ldByG7qib+1dgfb1qIVYuuIYvUI45fxyN34TcAin5gfbd+ZU9L2yVROdxYji2LqIo=
encrypt.keyStore.alias=server
encrypt.keyStore.secret={cipher}AQAsAaSKSZwmsVetCuxkX5NmSx4I2o2vqMlD6ORRt9odMw5uAYOMBPjLtRC5NMC6QOYPVHEc70SAuvp2gzZFAGa07Nbq8jVV5nGfEuwIYwBJ8IduvtD7JHVCGly5GMrzINADMxgIHpVeg6nMbl+y2pXqBPnJsvxc/5ueyzIoUUIu5W8GfJeWHEl2IaUstkFKQwR8TaJTlArP7/iSI/Po6Z4qBnNwtcPH/2aAQzZ9ylci6U0eqSROeFCUI2ir+KeEGZwaqqVhACtdGSQiSE/HkmUibN9YnSN87DEDVPuJJjHFvo3SOmSlG9N5Blv2OKQN1g4kgSoFh33yi6t+C35623h/TkDBfYfx7+3RLbAwOnHgQpqcSQS/H4PQX9OD/iAmPO0=

I get following error, am I not suppose to encrypt these values
java.lang.IllegalStateException: Cannot decrypt: key=encrypt.keyStore.password

**Comment by dsyer** [comment]
Indeed (it's turtles all the way down from there).

**Comment by jgawli** [comment]
Yes when I give plain text values, then it works. Thank you very much..
