### ISSUE TITLE
Using config client OUTSIDE a Spring Boot application...

### ISSUE THREAD

**Issue by redboy1972** [spring-cloud/spring-cloud-config#299]
Is it possible to use the client without it starting from a Spring Boot context?

I would like remote configuration available to me however my code exists within the context of a ActiveMQ plugin and another within a Vert.x server.  I do not control the start classes in either.

My code doesn't have to be automatically refreshed.  A simple on start loading of properties is sufficient.  If the setting change I would be willing to restart the app to get the new properties.  

Is this possible?

**Comment by dsyer** [comment]
How would your app consume the properties if it isn't a Spring application? If there is no link to the Spring `Environment` I don't think it's worth using the client at all - just pull the configuration from the config server and do whatever you need to do with it.

**Comment by redboy1972** [comment]
It is a Spring application.  Well more specifically we are a plugin to ActiveMQ which is a Spring app but not a Spring Boot one and would like settings pertaining to our configuration to come from the config server.

I have been able to get @Value annotations to work from a local properties file but would like them if there is an available config server to come from it and fallback otherwise.

My settings seem to come from property files, System properties, etc but after spending a lot of effort I can't seem to figure out how to get them from a config server from a non-Spring Boot context.

I have a server which I can get settings from both a "curl http://www.mysite.com/dev" command and from several other actual Spring Boot apps but this one eludes me.  Having the jars on the command path is NOT sufficient.  

Do you have some instructions or at least an idea that would push me in the right direction?

I am writing a class that does this the hard way revolving around 
new ObjectMapper().readValue( newURL(url), MyConfigProperty.class);
and was going to manually merge them with system properties and so on.

It would be 1000% more preferable to do this the normal way.

Any assistance would be appreciated.

**Comment by dsyer** [comment]
Well the "normal" way is to use Spring Cloud Config as part of a Spring Boot app. You really should consider doing that at some point.

If you want to try and cobble it together yourself you need a `ConfigServicePropertySourceLocator` and you need to apply it to the `Environment` before the application context is started. How you do that will depend a lot on how you are creating the `ApplicationContext` (`SpringApplication` from Spring Boot would be much easier than whatever you are doing probably).

**Comment by redboy1972** [comment]
One of the things I tried before I started this thread was this:

	<bean id="ConfigClientProperties" class="org.springframework.cloud.config.client.ConfigClientProperties">
		<property name="uri" value="http://labconfig.wcmad.com:8888/ott-dev.properties" />
	</bean>

	<bean id="ConfigServicePropertySourceLocator" class="org.springframework.cloud.config.client.ConfigServicePropertySourceLocator">
		 <constructor-arg ref="ConfigClientProperties"/>
	</bean>

However I wasn't sure how exactly to configure this.  Does the above seem right?  It didn't work but there is so many new technologies being stitched together I don't know where things are going wrong.

Should this be used in conjunction with or as a replacement for PropertySourcesPlaceholderConfigurer?

**Comment by redboy1972** [comment]
Thanks.

I attempted to try to convert ActiveMQ to a Spring Boot and it seems too much work.  I have written a custom wrapper that gets/parses the Config server settings.

**Comment by Mike520** [comment]
a chinese guy had see this and made a solution.
[https://wenku.baidu.com/view/493cf9eba300a6c30d229f49.html](https://wenku.baidu.com/view/493cf9eba300a6c30d229f49.html)
extend StandardServletEnvironment to CloudEnvironment, override customizePropertySources() method, add a new PropertySource from configServicePropertySourceLocator.locate(environment).

**Comment by marcellodesales** [comment]
@Mike520 I tried following the steps... There are a couple of problems:

* All the properties defined in `configClientProperties` got overridden by the default properties right after the our properties are provided.
 * https://github.com/spring-cloud/spring-cloud-config/blob/1.2.x/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigClientProperties.java#L283
 * In order to by-pass that, I had to create an environment variable `spring.application.name`
 * https://github.com/spring-cloud/spring-cloud-config/blob/1.2.x/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigClientProperties.java#L284-L286 

Autowire problems
----

It loads the properties... I'm having a hard time:

* to get the `@Value(${myproperty})` and
* to load a class with `@ConfigurationProperties(prefix = "myprefix")` to load all the properties for a POJO... 

Did you get that to work?

**Comment by mehmetsalgar** [comment]
Well, I saw this issue a while ago and actually have the exact same motivation, to use @RefreshScope and Spring Boot Configuration Server for core Spring, I finally have a working implementation and wrote blog about it.

If anybody needs it here is the link to the blog.

https://mehmetsalgar.wordpress.com/2017/05/29/configuration-client-and-refreshscope-for-plain-spring-and-spring-boot-configuration-server/

**Comment by kamranullah-se** [comment]
I have clone the project and built it on maven. But it giving me the error: Could not resolve placeholder 'github.token' in string value "${github.token}"

**Comment by mzubairahmed** [comment]
Hello @mehmetsalgar,
I have restrictions on accessing wordpress site. Is it possible for you to send the blog as a document to my email?
