### ISSUE TITLE
Values in configService don't bind to @Value annotated attributes (nor to ConfigurationProperties)

### ISSUE THREAD

**Issue by raphsoft** [spring-cloud/spring-cloud-config#301]
I have management.context-path set to /admin, so when I go to http://localhost:8080/admin/env I can see the configService pointing to my .yml file served by my config-server application.

However, even if I can see all the properties returned by the config-server, when I annotate an attribute with @value("${app.test.property}") I always get NULL instead of the value returned by the config client. 

My application has OAth2 and Elastic dependencies, not sure if those have conflicts. However, the only thing I'm sure is that the properties are being correctly retrieved but are not being set to their corresponding attributes.

**Comment by spencergibb** [comment]
Your annotation is wrong. It should be `@Value("${app.test.property}")`. If that doesn't help you'll need to provide a sample project that reproduces the problem.

**Comment by raphsoft** [comment]
Sorry, I mistyped the annotation, I actually have the issue with the correct annotation usage.

**Comment by spencergibb** [comment]
@raphsoft we still need a project that recreates the issue as this is basic functionality that gets tested.

**Comment by raphsoft** [comment]
I realized it's a problem with the @MapperScan annotation of MyBatis, nothing to do here I think. All my  configuration resources work well when the MapperScan thing is not present.
