### ISSUE TITLE
{cipher} is stripped from property values when crypto isn't enabled

### ISSUE THREAD

**Issue by mstine** [spring-cloud/spring-cloud-config#305]
I may want to store ciphertext in Git and have a Config Server without crypto enabled (i.e. no `encrypt.key` or `encrypt.keyStore` properties set) pass on the ciphertext as is so that I can use client-side decryption in the application.

e.g.

```
---
secretProperty: '{cipher}AQBKoRBQKU9C6+DWUx4T3NHFWfGMezYBd8VC+F6gzBVOfmAJad1CMnFOF2tGDHTyVYy3f7N7MiydQl1NkArUAEA2GmZbk8gkkmISrfGcvioFnfYtugVsn8SLtWfnlu/sKU6SIioaQC57biyQM4l1fEU4qBxaw+aRMkE7ab4QnCy4984VH38bATOV3AdI0or/V4UbdfqVz1hNIkz7Pgb8CYsktyqk78CEXkv/Fr0erDP6c34V3vM4oDQQ5/gldw9ARs6kuSy7ijPGqRNkhnS63Ube8//L+eTrIK6wERs8USFx14WteVKUyXiozzbe2+JJzbvXiPWw4tp+aFsa4l3fKe97Tu25kUUO5cjbaTFFF06ZPnjNV0zSrOrwbcz0J2ONj0s='
```

In all versions from Angel to Brixton.BUILD-SNAPSHOT, the `{cipher}` prefix is being stripped when the propertySource is delivered to the client, so the client doesn't know it needs to decrypt the value.

e.g.

```
propertySources: [
{
name: "https://github.com/mstine/config-repo.git/crypto.yml",
source: {
secretProperty: "AQBKoRBQKU9C6+DWUx4T3NHFWfGMezYBd8VC+F6gzBVOfmAJad1CMnFOF2tGDHTyVYy3f7N7MiydQl1NkArUAEA2GmZbk8gkkmISrfGcvioFnfYtugVsn8SLtWfnlu/sKU6SIioaQC57biyQM4l1fEU4qBxaw+aRMkE7ab4QnCy4984VH38bATOV3AdI0or/V4UbdfqVz1hNIkz7Pgb8CYsktyqk78CEXkv/Fr0erDP6c34V3vM4oDQQ5/gldw9ARs6kuSy7ijPGqRNkhnS63Ube8//L+eTrIK6wERs8USFx14WteVKUyXiozzbe2+JJzbvXiPWw4tp+aFsa4l3fKe97Tu25kUUO5cjbaTFFF06ZPnjNV0zSrOrwbcz0J2ONj0s="
}
},
```

**Comment by dsyer** [comment]
I actually can't reproduce this with Angel.SR4 or Brixton snapshots, with or without the key. (I.e. I see the `{cipher}` prefix on properties from the config repo.)  I've only tried so far with symmetric keys (when set), so I'll have another look with RSA tomorrow.

I did find a couple of related minor issues: 1) the key needs  to be in `bootstrap.yml` in the config server (even if not needed there to actually decrypt anything), 2) you can't put anything to be client-side decrypted in "overrides" in the config server when a key is provided (it is decrypted before the client sees it). I can fix those in Brixton (shout if you want support for those features in Angel).

**Comment by dsyer** [comment]
Still can't reproduce this issue (even with RSA, Angel or Brixton). I added some samples to the "tests" repo. If you have something similar that doesn't work, can you share a project please, and we'll see if we can cover it in documentation or something.

**Comment by mstine** [comment]
I missed your comments while I was out. I will take a look at this again this week.

**Comment by dsyer** [comment]
I saw this happen today. If you don't set `spring.cloud.config.server.encrypt.enabled` *or* `encrypt.*` then the configserver will send back cipher strings without the prefix (I don't know why yet). If you do set either of those properties it seems to work as expected for me.

**Comment by mstine** [comment]
Here are the repos that I'm using to create the issue: 

* https://github.com/mstine/config-server-encrypt
* https://github.com/mstine/config-client-encrypt

I tried setting `spring.cloud.config.server.encrypt.enabled` to `true`, but I still get the prefix stripped. If I set it to `false`, I get the expected value including `{cipher}` (verified back to Angel.SR4). I assume this is the expected behavior? 

FWIW, the client is successfully decrypting the value using Brixton.BUILD-SNAPSHOT, but not Angel.SR4.

**Comment by dsyer** [comment]
That sounds about right (`spring.cloud.config.server.encrypt.enabled=false` is needed if you want to retain the prefix). We could try and change that, but I assume this is good enough, so not super urgent.

The client side decryption is a separate issue. If you can easily reproduce it, please open another ticket for Angel.

**Comment by mstine** [comment]
I think that's fine. I'll close this one. And I'm fairly certain we'll be on Brixton across the board by the time the client decryption is needed, so no need for a backport IMO. Thanks!
