### ISSUE TITLE
Combined Eureka and Configuration Server Returns XML

### ISSUE THREAD

**Issue by tkvangorder** [spring-cloud/spring-cloud-config#306]
I am migrating our Spring Cloud application from Angel.SR3 to Brixton.M3. Currently, we have combined the config server and the eureka server into a single app: 

```java
@SpringBootApplication
@EnableConfigServer
@EnableEurekaServer
public class DepbugApplication {

    public static void main(String[] args) {
        SpringApplication.run(DepbugApplication.class, args);
    }
}
```

I have set "spring.cloud.config.server.prefix" to "configuration"

In the Angel.SR3 release: 

http://host:port/eureka/apps is returned as XML.
http://host:port/configuration/appname/profile is returned as JSON

In the Brixton.M3 release: 

http://host:port/eureka/apps is returned as XML.
http://host:port/configuration/appname/profile is returned as XML

I believe this is because the eureka maven artifact has a runtime dependency on jackson-dataformat-xml which is then picked up by Spring Boot.

I am able to get the JSON version of the configuration by suffixing the URL with .json but JSON really should be the default/only format for the configuration end points.

In looking at the content negotiation in Spring MVC, it looks like this could be fixed by adding 

produces={"application/json"} to the @RequestMapping for the various config server end points.

**Comment by tkvangorder** [comment]
Additional Information: 

Chrome is sending the following in its Http Request Header: 

```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
```

I was able to work around this issue by extending the WebMvcConfigurerAdapter and telling the content negotiation to ignore the accept header and default to JSON: 

```java
@SpringBootApplication
@EnableConfigServer
@EnableEurekaServer
public class DepbugApplication extends WebMvcConfigurerAdapter {

    public static void main(String[] args) {
        SpringApplication.run(DepbugApplication.class, args);
    }

    /**
     * Setup a simple strategy: use all the defaults and return XML by default when not sure. 
     */
   @Override
   public void configureContentNegotiation(ContentNegotiationConfigurer configurer) {
     configurer.ignoreAcceptHeader(true).defaultContentType(MediaType.APPLICATION_JSON);
   }

}
```

**Comment by dsyer** [comment]
#337 identified an issue with this blunt force approach. We might have to say we don't support default JSON content (without a header) in a config server embedded in eureka - it's a corner case for sure.

**Comment by pcornelissen** [comment]
I have separate services for eureka and the config server, but today all services refused to start with

```
2016-02-23 07:33:17.013  WARN 3218 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: Could not read document: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '[' (code 91) excepted space, or '>' or "/>"
 at [row,col {unknown-source}]: [1,2992] (through reference chain: org.springframework.cloud.config.environment.Environment["propertySources"]->java.util.ArrayList[0]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '[' (code 91) excepted space, or '>' or "/>"
 at [row,col {unknown-source}]: [1,2992] (through reference chain: org.springframework.cloud.config.environment.Environment["propertySources"]->java.util.ArrayList[0])

```
This worked yesterday. The configserver is pretty simple, just spring boot with the necessary application.yml/bootstrap.yml that registers the configserver in eureka.

Due to the other bugs that I commented on in the last weeks I have to use the brixton snapshot. :-/

FYI I have a strange effect that I can start the configserver-clients from inside intellij, but when I try to start them via the spring boot maven plugin or java -jar I get the exception above and the service refuses to start due to broken property values.

**Comment by dsyer** [comment]
Can you capture the headers from your clients to the config server (eg using the /trace endpoint)?

**Comment by dsyer** [comment]
It works fine for me, so you must have something other than a "vanilla" config server (e.g. you added jackson XML to the classpath, or whatever it is that causes  issues in the eureka case).

**Comment by pcornelissen** [comment]
Found the culprit by accident :-)
It's the cloud starter for eureka!

To fix the issue just use this:
```
      <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.dataformat</groupId>
                    <artifactId>jackson-dataformat-xml</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by dsyer** [comment]
OK, that makes a small amount of sense. I hate that Jackson XML does that to a Spring Boot app, but I still get JSON by default if I don't ask for anything special. So your clients are not the regular monday to friday clients. Did you get those headers?

**Comment by pcornelissen** [comment]
OK, So I had to remove the jackson exclusion from the confighub and the client (Which leads me to believe that it would be sufficient to remove jackson from the config server only, but I don't want xml anyway anywhere)

```
  {
    "timestamp": 1456303509075,
    "info": {
      "method": "GET",
      "path": "/admin/default",
      "headers": {
        "request": {
          "accept": "application/xml, text/xml, application/json, application/*+xml, application/*+json",
          "authorization": "Basic YWRtaW46czNjcjN0IVM=",
          "user-agent": "Java/1.8.0_66",
          "host": "dockermachine:8888",
          "connection": "keep-alive"
        },
        "response": {
          "X-Content-Type-Options": "nosniff",
          "X-XSS-Protection": "1; mode=block",
          "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",
          "Pragma": "no-cache",
          "Expires": "0",
          "X-Frame-Options": "DENY",
          "Strict-Transport-Security": "max-age=31536000 ; includeSubDomains",
          "X-Application-Context": "confighub:native,docker:8888",
          "Content-Type": "application/xml;charset=UTF-8",
          "Transfer-Encoding": "chunked",
          "Date": "Wed, 24 Feb 2016 08:45:09 GMT",
          "status": "200"
        }
      }
    }
  }
``` 

This behaviour is congruent with problems that I have encountered in other spring services as well.
As soon as you have jackson xml (or other xml marshallers as well) in your classpath they are picked up by spring. The problem is that they usually end up first in the accept header list and json comes last. When such a client performs a request to another spring boot service with the same "problem" both agree on xml, which leads to all kinds of weird behaviours like un-/marshalling problems of date/time fields etc.


In my other project I just removed the message converters in the config by: (I needed the classes in the classpath, so maven exclusion was not an option there)

```
  @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        super.configureMessageConverters(converters);
        /*JaxB causes trouble, so remove it, we are using jackson! */
        for (Iterator<HttpMessageConverter<?>> iterator = converters.iterator(); iterator
                .hasNext(); ) {
            HttpMessageConverter<?> converter = iterator.next();
            if (converter instanceof Jaxb2RootElementHttpMessageConverter) {
                iterator.remove();
            }
        }
    }
```
In my WebMvcAutoConfigurationAdapter based WebConfig class.

**Comment by dsyer** [comment]
AFAIK the Jackson XML dependency should be optional for the eureka client (but not the server), so we can exclude it by default in the Spring Cloud dependencies. That should help. But I still don't understand why your clients are sending accept headers (mine don't, so they get JSON).

**Comment by pcornelissen** [comment]
I have no special configuration that should lead to this. (As far as I know, I have a 5h train ride later, I can try to find out where this might come from)

**Comment by dsyer** [comment]
The XML dependency is excluded in bc0eef9
