### ISSUE TITLE
Wrong doc -> Unknown property 'spring.cloud.config.server.health.enabled'

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-config#307]
Unknown property 'spring.cloud.config.server.health.enabled'

...bot documented in http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html

**Comment by spencergibb** [comment]
It is certainly a [valid property](https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration.java#L41). Are you getting an error?

**Comment by cforce** [comment]
I think its only a missing entry in /META-INF/spring-configuration-metadata.json ?

**Comment by spencergibb** [comment]
Are you seeing an error? That property isn't in an `@ConfigurationProperties` object, so it won't automatically end up in `/META-INF/spring-configuration-metadata.json`.

**Comment by cforce** [comment]
it only "unknown to the STS IDE in yml editor.
