### ISSUE TITLE
Don't listen to events in a bootstrap context

### ISSUE THREAD

**Issue by pawelszymczyk** [spring-cloud/spring-cloud-config#314]
Hi

I have a application based on Spring-boot. This application have a listener that listens on ApplicationEnvironmentPreparedEvent events. When action occurs listener reads and modifies ConfigurableEnvironment fetched from event. Everything works perfect until I added spring-cloud-config into classpath.  After few hours debbuging session I noticed that my listener was called twice - first (correctly) while starting application container and second while starting spring-cloud-config container. Undesirable behavior is that second invocation overrides my changes on ConfigurableEnvironment. Finally I have to copy some code from spring-cloud-config sources to don't listen on events from bootstrap phase

```java
// don't listen to events in a bootstrap context
		if (environment.getPropertySources().contains("bootstrapInProgress")) {
			return;
		}
```

https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java#L74

And here is src code that fixes it in my application:

https://github.com/allegro/hermes/pull/275/files

In my opinion it's very poor solution when something like "bootstrapInProgress" leaks out of framework sources.

**Comment by dsyer** [comment]
Can you explain why you don't want your listener to run in the Bootstrap context? The intention is that the Bootstrap is in every way the same as a "regular" Spring Boot application, so it would want to pick up changes to the `Environment` that you are implementing as well.

I don't like the leak either, but I'm not sure you have to implement your listener in that way anyway - maybe you could have checked for a property source with your own unique name to ensure that it only runs once? I think you probably should be defensive if you care about when and how your listener is executed anyway (Spring Cloud isn't the only thing that might screw you up).

P.S. the code you copied is from spring-cloud-context, so maybe you should have opened an issue there?

**Comment by pawelszymczyk** [comment]
Ok, I close this issue and open another in spring-cloud-context.
