### ISSUE TITLE
Behavior of webhooks on CF (PWS)

### ISSUE THREAD

**Issue by mstine** [spring-cloud/spring-cloud-config#316]
I'm not sure I'll be able to get all of the details right in the issue, so we may need to discuss this in chat.

Reference applications for this issue:

* Config Server - https://github.com/mstine/config-server-encrypt
* Config Client - https://github.com/mstine/config-client-encrypt
* Config Repo - https://github.com/mstine/config-repo

(Note that no encryption is in play here, I'm just reusing those applications)

*LOCALLY - EVERYTHING WORKS*

1. I added the `spring-cloud-config-monitor` dependency to `config-server-encrypt`, and ran it on port `8888`.
2. I set up Ngrok to point to my locally running Config Server.
3. I set up a webhook on `config-repo` to point to the Ngrok link.
4. I ran 2 instances of `config-client-encrypt` on ports `8080` and `8081`.
5. I committed changes to the `foo` property in `crypto.yml` and pushed to GitHub.
6. The webhook `POST` to `/monitor` was received, and the applications received the update.

*PWS - BROKEN FOR MOST UPDATES*

1. Push the same applications to PWS. `config-server-encrypt` becomes `http://ms-cs-enc.cfapps.io` and `config-client-encrypt` becomes `http://ms-cc.cfapps.io`.
2. Scale out `ms-cc` to 5 instances.
3. I committed changes to the `foo` property in `crypto.yml` and pushed to GitHub.
4. The webhook `POST` to `/monitor` was received, but no applications received the update.

When you look at trace, you see the following:

```
{
timestamp: 1452037045656,
info: {
signal: "spring.cloud.bus.sent",
type: "RefreshRemoteApplicationEvent",
id: "f1f4c0a5-9844-4615-b0a1-624765aa82a9",
origin: "ms-cs-enc:cloud:0",
destination: "crypto:**"
}
},
```

So the destination for the message is "all applications named `crypto` regardless of profile." Note that `spring.application.name` is set to `crypto` in both `application.yml` and `bootstrap.yml` for `ms-cc`.

Next experiment:

1. I committed changes to a property in `application.yml` and pushed to GitHub.
2. The webhook `POST` to `/monitor` was received, and the applications received the update.

Now when you look at trace, you see the following:

```
{
timestamp: 1452037279185,
info: {
signal: "spring.cloud.bus.sent",
type: "RefreshRemoteApplicationEvent",
id: "30a17615-150c-47ad-92a5-344b6f2fefcd",
origin: "ms-cs-enc:cloud:0",
destination: "*:**"
}
}
```

So the destination for the message is "all applications regardless of name and profile." Now we can see acks from the client apps:

```
{
timestamp: 1452037280765,
info: {
signal: "spring.cloud.bus.ack",
type: "RefreshRemoteApplicationEvent",
id: "30a17615-150c-47ad-92a5-344b6f2fefcd",
origin: "ms-cc:cloud:1",
destination: "*:**"
}
},
```

Note that the origin of the ack is an application named `ms-cc`, not `crypto`. 

If you look at `/env` for `ms-cc`, you'll see that `spring.application.name` is consistently still set to `crypto`. However, `cloud.application.name` is `ms-cc`, which seems to be sourced from `VCAP_APPLICATION`.

Another experiment:

1. Add a file called `crypto-cloud.properties` to `config-repo` and push it. The value of `foo` in this file should override all others, as it specifies both application name (`crypto`) and profile name (`cloud`). 
2. Restart `ms-cc`. Looking at `http://ms-cc.cfapps.io/foo` endpoint, this is in fact true.
3. Now, push an update to `crypto-cloud.properties`.
4. The webhook `POST` to `/monitor` was received, but no applications received the update.

Now when you look at trace, you see the following:

```
{
timestamp: 1452037732498,
info: {
signal: "spring.cloud.bus.sent",
type: "RefreshRemoteApplicationEvent",
id: "8476219d-ba94-47e5-a400-66615eebb071",
origin: "ms-cs-enc:cloud:0",
destination: "crypto-cloud:**"
}
}
```

So, instead of the destination being `crypto:cloud` as I expected, it is `crypto-cloud:**`. This seems like a bug.

**Comment by dsyer** [comment]
Looks like 2 issues to me, so we can deal with one of them here, and create a new issue for the other (#318).

Summary: `destination: "crypto:**"` looks good to me, i.e. the message generated by the monitor is correct, which makes it a Bus problem if it doesn't get delivered.

I don't like the looks of `origin: "ms-cs-enc:cloud:0"` though, and that comes from Spring Boot. I'll raise an issue there because I think that's actually the problem (in `ContextIdApplicationContextInitializer`).

The workaround is to use a `vcap.application.name` that is the same as your `spring.application.name`.
