### ISSUE TITLE
Backport client-side decryption of Config Server properties to Angel

### ISSUE THREAD

**Issue by mstine** [spring-cloud/spring-cloud-config#325]
Creating this ticket per request here: https://github.com/spring-cloud/spring-cloud-config/issues/305#issuecomment-169028032

We are releasing support for this in SCS next week, and most customer apps will not have moved to Brixton yet, so a backported fix would be great. Thanks!

**Comment by dsyer** [comment]
Shame that Angel.SR5 was just released yesterday. Oh well.

**Comment by dsyer** [comment]
Fixed in https://github.com/spring-cloud/spring-cloud-config/commit/7f897d5. Please try 1.0.5.BUILD-SNAPSHOT of spring-cloud-context to check this works for you.
