### ISSUE TITLE
In Eureka First Bootstrap mode I can't use custom EurekaInstanceConfigBean 

### ISSUE THREAD

**Issue by svenrienstra** [spring-cloud/spring-cloud-config#329]
I want to override the default EurekaInstanceConfigBean so it uses AmazonInfo:

```java
@Bean
@Profile("!dev")
public EurekaInstanceConfigBean eurekaInstanceConfig() {
   EurekaInstanceConfigBean b = new EurekaInstanceConfigBean();
   AmazonInfo info = AmazonInfo.Builder.newBuilder().autoBuild("eureka");
   b.setDataCenterInfo(info);
   return b;
}
```
 When I enable spring.cloud.config.discovery.enabled the EurekaInstanceConfigBean isn't picked up anymore but throws a ` No qualifying bean of type [org.springframework.cloud.netflix.eureka.EurekaInstanceConfigBean] is defined: expected single matching bean but found 2: eurekaInstanceConfig,eurekaInstanceConfigBean`

The problem is DiscoveryClientConfigServiceBootstrapConfiguration causes a EurekaInstanceConfigBean to be created before any other bean is created.

**Comment by spencergibb** [comment]
@svenrienstra can you change the name of your bean to `eurekaInstanceConfigBean`?

**Comment by svenrienstra** [comment]
That does indeed fix the error. Maybe ask your colleagues over at Spring cloud netflix to change this documentation: http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html (Using Eureka on AWS)?
