### ISSUE TITLE
Refreshing the properties on client

### ISSUE THREAD

**Issue by cornelcreanga** [spring-cloud/spring-cloud-config#330]
Hello,

Besides using [Push notifications](http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_push_notifications_and_spring_cloud_bus) is there any way for a client to refresh the properties already loaded from a Spring Config Server? I thought that calling RefreshEndpoint.refresh (on the client) would force the client to reload the properties from the server but I have the impression it does not work (I can provide a very simple example if it helps). Thanks.

**Comment by dsyer** [comment]
It does work for me (but make sure you get the latest snapshots if you are on Brixton because of https://github.com/spring-cloud/spring-cloud-commons/issues/83).

**Comment by cornelcreanga** [comment]
The last artefact from http://repo.spring.io/libs-snapshot-local/org/springframework/cloud/spring-cloud-commons/1.1.0.BUILD-SNAPSHOT/ seems to not have your modification (the last one was built on 29-JAN) - maybe because the build is failing?

Hoewever I've pulled the last GIT sources and I've installed the artifact into my local repo - it works. Thanks for your help.
