### ISSUE TITLE
Versioning of documentation

### ISSUE THREAD

**Issue by sylvainlaurent** [spring-cloud/spring-cloud-config#331]
On the page http://cloud.spring.io/spring-cloud-config/ all the links for the reference documentation point to the same url : http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html
It seems that this is always the latest snapshot version (the version is not indicated in the html).
Please provide the correct doc for each version.

**Comment by dsyer** [comment]
Old versions of the documentation are always available in the compendium version, e.g. http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html. Currently they stop at 1.0.3 but I'd rather fix that than archive the same stuff twice.

**Comment by dsyer** [comment]
I updated the links to point to a fragment in the old compendium. I'll leave this open while we get the 1.0.x leading edge sorted out.

**Comment by dsyer** [comment]
Links for Angel projects now point to 1.0.x. Fingers crossed and the docs may even be updated by CI when there is a change.
