### ISSUE TITLE
cannot disable PauseEndpoint because it is created twice

### ISSUE THREAD

**Issue by sylvainlaurent** [spring-cloud/spring-cloud-config#332]
Hello,

I tried to set `endpoints.pause.enabled: false` in my config to prevent calls to `/pause`.
Unfortunately it seems that there are 2 instance of PauseEndpoint : one is configurable, the other not 

The one created by `org.springframework.cloud.autoconfigure.RefreshAutoConfiguration.RefreshEndpointsConfiguration.pauseEndpoint(RestartEndpoint)` is configurable
But the one created by `org.springframework.cloud.context.restart.RestartMvcEndpoint.getPauseEndpoint()` is not configurable and not "disableable"

**Comment by spencergibb** [comment]
Closing in favor of https://github.com/spring-cloud/spring-cloud-commons/issues/86 in the right repo.
