### ISSUE TITLE
Service dynamically determines the profile to use

### ISSUE THREAD

**Issue by leb1** [spring-cloud/spring-cloud-config#333]
I have a use case where a service has to dynamically determine the profile to use without having to initiate a new request to the Config Server. 

For example, Service A handles requests from both mobile and desktop users. For each http request, if the request is originated from a mobile device, certain configurations will be used (e.g. Mobile profile, serviceA-mobile.yml, key1=abc). For desktop requests,  a different set of values will be used for the same configurations (e.g. Desktop profile, serviceA-desktop.yml, key1=xyz). 

How can serviceA dynamically determines the value for "key1" without having to reload any data from the Config. Server? 
If I activate both profiles (mobile and desktop) as show below, configurations (e.g. key1) will be consumed from the desktop profile during application startup.
`spring.profiles.active=mobile,desktop`
 
Does the Config Server support such functionality?  Is it possible to load both profiles and use expressions to determine which profile to consume?

Thanks!

**Comment by spencergibb** [comment]
Config server doesn't have that functionality. Why not have `mobile.key1` and `desktop.key1`?

**Comment by dsyer** [comment]
It doesn't really sound like a config server feature anyway since you are describing features in an application, not the server itself. It's basically a feature switch.  I think you probably have to  either deploy 2 separate apps, or else look at dispatching the requests using content negotiation (or maybe a custom `RequestMapping`).

**Comment by dsyer** [comment]
I'm going to close this one because it's not really config related. If you are still interested, put a new feature request in Spring Cloud Commons.

**Comment by leb1** [comment]
@spencergibb It is not just mobile and desktop, there could be more hierarchies to address. Could be something like, level 1 -> level 2 -> level 3 -> level 4
If a property can be found in level 4, return it. If not, check level 3 and return if there is a value and so on which is the way the config client works if multiple profiles are enabled (spring.profiles.active=level1,level2,level3,level4). However, in my case, the order of the hierarchy (active profiles) is dynamically determined and the number of levels involved in the hierarchy is also dynamically determined (based on the http request). 

@dsyer I don’t think it is a feature switch as I am not switching between features. I am executing the same feature (same code) but with different configurations. 

After looking at the config client code, I can achieve what I described above with some custom coding on top of the config client library. 
The Config client builds a collection of MapPropertySource where each MapPropertySource represents an active profile. When calling environment.getProperty(key), the code loops through the collection of MapPropertySource and returns the first value found. I just have to write some code to control the order in which these MapPropertySource are checked. I will try that soon.

Thank you for looking into the question.
