### ISSUE TITLE
No handler method found when requesting plain text xml resource

### ISSUE THREAD

**Issue by mikee** [spring-cloud/spring-cloud-config#337]
Using .conf for a file name works fine - but the same file with a .xml extension returns an http 406

Logs show
2016-02-16 01:44:03.140 DEBUG 523 --- [nio-8888-exec-7] s.w.s.m.m.a.RequestMappingHandlerMapping : Looking up handler method for path /myapp/development/master/context.xml
2016-02-16 01:44:03.145 DEBUG 523 --- [nio-8888-exec-7] .m.m.a.ExceptionHandlerExceptionResolver : Resolving exception from handler [null]: org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation

**Comment by shakuzen** [comment]
I can confirm this seems to have broken in Brixton M5 but works with Brixton M4.

**Comment by copa2** [comment]
This was introduced with 05dc6f9aceda4b7180041e2100201c2770b0f7d7.
ResourceController has introducted "produces = MediaType.APPLICATION_JSON_VALUE" on type level.

The file extensions(.xml, .json, .yml) when we search for a file "/app/proflie/label/myFile.xml" are intepreted as content type. But there is no longer a mapping on the ResourceController.

Previously it mapped to "all content types" so it was no problem. With the above commit it only knows "application/json" for ResourceController.resolve().

You can fix this with providing your own configuration of the ContentNegotiationConfigurer.
Simply ignore the contentResolution for file extensions the following way:
`
@Configuration
protected static class WebConfigurer extends WebMvcConfigurerAdapter {
	@Override
	public void configureContentNegotiation(ContentNegotiationConfigurer configurer) {
		configurer.favorPathExtension(false);
	}
}
`
At least a note the documentation would help.

**Comment by dsyer** [comment]
I'm going to revert 05dc6f9 and add a test for the resource controller.
