### ISSUE TITLE
Client side failover reading configuration from cloud config servers

### ISSUE THREAD

**Issue by uweschaefer** [spring-cloud/spring-cloud-config#342]
[suggestion for enhancement/discussion]

We're using a cloud config server. In order to be resilient to failure of the server, we have multiple instance behind a load balancer. However, in case the load-balancer fails, we'd need some IP-Level failover setup to guarantee access to the config servers.

We were wondering, if it would be easier to allow multiple endpoints for configuration via
spring.cloud.config.uri or a similar property, so that the client can try to configure itself with a secondary uri if the first fails.

Is this something considered of value? if so, we'd like to work on it with a little help.

**Comment by dsyer** [comment]
I think resilient load balancers are free or cheap in pretty much any cloud environment, so I wouldn't make this a high priority. But if you have some code you want to contribute we can definitely take a look. It would be most likely to be successful if it stayed orthogonal to the existing code, so we don't risk making what is now quite simple into something complicated. Maybe the `LoadBalancer` abstraction from spring cloud would be useful?

**Comment by spencergibb** [comment]
I've had others ask for this functionality as well. It's similar to how eureka works too.

**Comment by uweschaefer** [comment]
Just wondering: If we would implement this, how exactly would one USE this?

Provide a comma separated List to "spring.cloud.config.uri" or have a secondary "spring.cloud.config.uris" that has a list?

**Comment by spencergibb** [comment]
I'd start with a comma separated list. Would be simple to change if needed.

**Comment by fkissel** [comment]
Thanks for your feedback!

After talking to my colleague @uweschaefer we would start working on this.

**Comment by fkissel** [comment]
I signed the Individual Contributor Agreement, my confirmation number is 167520160316100217.
