### ISSUE TITLE
Embedded config server injects properties only after refresh

### ISSUE THREAD

**Issue by kurtinaitis** [spring-cloud/spring-cloud-config#351]
I setup an embedded config server using spring.cloud.config.server.bootstrap=true
My controller does not get injected values until I hit the /refresh endpoint. After that the values are injected and can be used.

I use the version Angel.SR6.

[cloud-server.zip](https://github.com/spring-cloud/spring-cloud-config/files/171979/cloud-server.zip)

**Comment by kurtinaitis** [comment]
I get the following exception: 
There was an unexpected error (type=Internal Server Error, status=500).
Error creating bean with name 'scopedTarget.projectNameRestController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: java.lang.String cloud.server.ProjectNameRestController.projectName; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'configuration.projectName' in string value "${configuration.projectName}"

**Comment by dsyer** [comment]
Your code works for me if I put those `configuration.*` properties in the config repo. Maybe the config repo you are using (which is a local file that you didn't provide) doesn't contain the right properties?

**Comment by kurtinaitis** [comment]
I attach the repo files.
The scenario to reproduce is the following:
- start the server: 
```
export ENCRYPT_KEY=secret
java -jar target/server-0.0.1-SNAPSHOT.jar | tee server.log
```
- hit the endpoint: 
```
curl http://localhost:8888/value
{"timestamp":1458042443604,"status":500,"error":"Internal Server Error","exception":"org.springframework.beans.factory.BeanCreationException","message":"Error creating bean with name 'scopedTarget.projectNameRestController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: java.lang.String cloud.server.ProjectNameRestController.projectName; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'configuration.projectName' in string value \"${configuration.projectName}\"","path":"/value"}
```
- hit the refresh endpoint: 
```
curl -X POST http://localhost:8888/refresh
["configuration.projectName","configuration.key"]
```
- hit the endpoint again. Now it works...
```
curl http://localhost:8888/value
value
```
I also attach the server log of this scenario.

[server.log.zip](https://github.com/spring-cloud/spring-cloud-config/files/173826/server.log.zip)

[config-repo.zip](https://github.com/spring-cloud/spring-cloud-config/files/173769/config-repo.zip)

**Comment by dsyer** [comment]
OK, so the problem is just that to bootstrap the server from it's own repo it needs to have that bit configured in the bootstrap phase (you had all the `spring.cloud.config.*` stuff in `application.yml`). Just move it all into `bootstrap.yml`.
