### ISSUE TITLE
Configuration refreshing depends on actuator

### ISSUE THREAD

**Issue by kurtinaitis** [spring-cloud/spring-cloud-config#352]
Currently, all configuration refreshing code resides in the RefreshEndpoint which depends on the actuator.
I would like to have a possibility to do a programmatic refresh and do not expose multiple endpoints which come with the actuator.
Please move the refreshing code into separate class, not depending on actuator machinery.

**Comment by dsyer** [comment]
`RefreshScope` does not depend on the actuator, and there is a `EnvironmentChangeEvent` that you can fire (and listen to) if you want to as well. I don't think there's a lot else in the actuator endpoint, so I don't think there's anything to do here. Do you agree?

**Comment by kurtinaitis** [comment]
I do not agree. RefreshEndpoint.refresh() refreshes all my bean injected properties, but RefreshScope.refreshAll() does not. Maybe I do something wrong here?
This works as expected:

```
@RestController
class RefreshController {

    @Autowired
    RefreshEndpoint refreshEndpoint;

    @RequestMapping(value = "/rfr", method = RequestMethod.POST)
    String[] refresh() {
        return refreshEndpoint.refresh();
    }
}
```

But this one doesn't:
```
@RestController
class RefreshController {

    @Autowired
    RefreshScope refreshscope;

    @RequestMapping(value = "/rfr", method = RequestMethod.POST)
    void refresh() {
        refreshScope.refreshAll();
    }
}
```

**Comment by spencergibb** [comment]
This issue is in the wrong repo, should be in spring-cloud-commons.

Closing in favor of https://github.com/spring-cloud/spring-cloud-commons/issues/101
