### ISSUE TITLE
Release spring-cloud-monitor

### ISSUE THREAD

**Issue by mmoayyed** [spring-cloud/spring-cloud-config#357]
spring-cloud-config-monitor is not yet properly released. I only see it in milestone mode, and using the milestone with the official releases of other cloud config modules is not possible since there are API/package changes. Task at hand would be to cut an official release for spring-cloud-config-monitor.

**Comment by spencergibb** [comment]
We are in the process of cutting RC1

**Comment by mmoayyed** [comment]
Do you have an estimate of when RC1 may become available? and for the matter, the GA? 

Would have been nice to keep this issue open, so others could track the process.

**Comment by spencergibb** [comment]
RC1 happened a few weeks ago. RC2 likely next week. Then GA after that.

**Comment by mmoayyed** [comment]
Thanks! I'll keep watch.
