### ISSUE TITLE
List in YAML lead to "error parsing attribute name" in Brixton.RC1

### ISSUE THREAD

**Issue by rainerfriesen** [spring-cloud/spring-cloud-config#368]
Hi together,
when using Brixton.RC1 a list in a yml file stored in the configuration repository leads to an error "error parsing attribute name". While with Angel.SR6 everything is working fine.

Example (everything ok):
```
dummy:
  property: 123dummy
```

Example (Error in Brixton):
```
dummy:
  property: 
    - 123dummy
```

This is a blocking issue for our project.

Regards,
Rainer

**Comment by spencergibb** [comment]
I'm unsure if this is a problem with spring cloud config or if it is a change in boot (1.2.x->1.3.x). When are you getting this error? Are you binding to an object?

**Comment by rainerfriesen** [comment]
I'm binding the list to an Object annotated with `@ConfigurationProperties` as an List of Strings. The error is thrown when I try to access the depending configuration on the config-server, e.g. `localhost:8888/eureka-server/default`

**Comment by spencergibb** [comment]
@rainerfriesen putting that file exactly as you have it yielded the following from config server:
```
{
    "name": "baz",
    "profiles": [
        "default"
    ],
    "label": null,
    "version": "8b498746541b6b0fb7663c3025fd80a4e1712f43",
    "propertySources": [
        {
            "name": "/Users/sgibb/workspace/spring/spring-cloud-samples/config-repo/baz.yml",
            "source": {
                "dummy.property[0]": "123dummy"
            }
        },
        {
            "name": "/Users/sgibb/workspace/spring/spring-cloud-samples/config-repo/application.yml",
            "source": {
                "info.description": "Spring Cloud Samples",
                "info.url": "https://github.com/spring-cloud-samples",
                "eureka.client.serviceUrl.defaultZone": "http://localhost:8761/eureka/"
            }
        }
    ]
}
```
You'll have to provide a sample that recreates the problem.

**Comment by rainerfriesen** [comment]
Hi,
I tested again with the attached file (just renamed to txt). I recognized, that the config-server responds correct. But in Brixton it returns the following XML instead of JSON like in Angel:

<Environment><name>foo</name><profiles><profiles>default</profiles></profiles><label/><version/><propertySources><propertySources><name>file:/tmp/config-repository/foo.yml</name><source><dummy.property[0]>123dummy</dummy.property[0]></source></propertySources></propertySources></Environment>

The XML parser seems to have a Problem with the "[" in the property name of `dummy.property[0]`. In Angel it responded with a JSON representation.

Here's my dependecies section from the maven pom:
`<parent>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-parent</artifactId>
        <version>Angel.SR6</version>
        <relativePath/>
        
    </parent>`

`<dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jolokia</groupId>
            <artifactId>jolokia-core</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>`

Thank you very much for your help.

Regards,
Rainer
[foo_yml.txt](https://github.com/spring-cloud/spring-cloud-config/files/236162/foo_yml.txt)

**Comment by rainerfriesen** [comment]
Hi together,
as the issue still persists, I found this Bountysource thread describing the very same issue. The exclusion of jackson-dataformat-xml from the config-server resolved my issue.

Regards,
Rainer

**Comment by spencergibb** [comment]
Closing as a vanilla config server doesn't have a jackson-dataformat-xml dependency.
[pom.xml.txt](https://github.com/spring-cloud/spring-cloud-config/files/298427/pom.xml.txt)
[tree.txt](https://github.com/spring-cloud/spring-cloud-config/files/298431/tree.txt)
