### ISSUE TITLE
Spring Cloud Config Server doc is inaccurate regarding application name and config

### ISSUE THREAD

**Issue by mbenson** [spring-cloud/spring-cloud-config#370]
Documentation discusses the possibilities of "launching it with `spring.config.name=configserver`" and using "your own `application.properties`", while `ConfigServerApplication` explicitly sets `spring.config.name=configserver`. Due to this the documentation's assertion that the app defaults to run on port 8080 is also incorrect.

**Comment by dsyer** [comment]
I don't think that's right. The documentation is referring to a sample app that is defined inline as 

```
@SpringBootApplication
@EnableConfigServer
public class ConfigServer {
  public static void main(String[] args) {
    SpringApplication.run(ConfigServer.class, args);
  }
}
```

This will run on port 8080 by default.

The `ConfigServerApplication` in the jar is not mentioned and hardly used I would guess (possibly we should just remove it).

**Comment by mbenson** [comment]
Point taken, @dsyer. TBH however I don't really understand the decision for removing the repackage mojo from the cloud-server project, nor for contemplating removing the `ConfigServerApplication` class. It seems to me that by providing an external configserver.properties file it's ready to go. That's how I'm currently running it after having run spring-boot:repackage against the project.
