### ISSUE TITLE
GIT connection problem breaks configuration server

### ISSUE THREAD

**Issue by matbhe** [spring-cloud/spring-cloud-config#373]
Temporary **GIT connection problems** while the execution of the method JGitEnvironmentRepository#copyRepository can **break the configuration server**.
After the occurance of a GitAPIException there exists a an invalid and empty **.git** folder.
Due to this empty folder the method JGitEnvironmentRepository#createGitClient always tries to open the invalid repository. This leads to permanent **"No such label" - exceptions**.---

Fix: The **.git** folder should be **removed** after any exception in in the copyRepository - method.
     This will change the behavoir in the JGitEnvironmentRepository#createGitClient - method and fix it.

**Comment by prademak** [comment]
+1
We sometimes see exactly the samen situation occurring after a restart of our config server.

**Comment by ryanjbaxter** [comment]
Looking at the code, we delete the base directory if it exists before we copy it, shouldn't that also delete the `.git` directory?
https://github.com/spring-cloud/spring-cloud-config/blob/62195b4e5d77b65826350bc3958e59e55b500b1d/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepository.java#L346

**Comment by spencergibb** [comment]
it should

**Comment by copa2** [comment]
Well it deletes it at start of copyRepository, but when it fails in the clone process (init,fetch,checkout) it might be that the init worked but fetch/checkout failed due network problems. Then you have a .git folder from init and you get a GitAPIException from fetch. 
At the next call of refresh it will not call copyRepository from createGitClient, as it already has a .git folder:
https://github.com/spring-cloud/spring-cloud-config/blob/62195b4e5d77b65826350bc3958e59e55b500b1d/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepository.java#L334
refresh will now fail in checkout, as it has not the needed fetched data of the clone. It throws  RefNotFoundException, which then will be translated to NoSuchLabelException.

In my opinion we should, as suggested by mathbe, delete .git directory when clone fails, to keep it in a proper state.

**Comment by ryanjbaxter** [comment]
OK I think that makes sense, @spencergibb do you agree?
