### ISSUE TITLE
Running Spring Cloud Config Server on Windows gets no properties for my services

### ISSUE THREAD

**Issue by mihaita-tinta** [spring-cloud/spring-cloud-config#374]
When I run a Spring Cloud Config Server on windows using:

spring.cloud.config.server.git.uri=https://github.com/mihaita-tinta/boot-config-repo

It searches into the temporary git folders:

`[file:/C:/Users/MIHAIT~1.TIN/AppData/Local/Temp/config-repo-1323458472291671575/]`

but when the NativeEnvironmentRepository.clean method is called to filter locations, it removes all the configurations properties files because every property source name has the \ separator from File.getAbsolutePath:

`C:\Users\MIHAIT~1.TIN\AppData\Local\Temp\config-repo-1323458472291671575\template-builder.properties`

while every search location has the path from: File.toURI.toString

Therefore the result I get for:
http://localhost:9999/template-builder/default
is
{"name":"my-service","profiles":["default"],"label":"master","propertySources":[]}

Running the same jar on linux returns the output as expected:

`{"name":"template-builder","profiles":["default"],"label":"master","propertySources":[{"name":"https://github.com/mihaita-tinta/boot-config-repo/template-builder.properties","source":{"server.port":"8000","message":"Some message from config"}},{"name":"https://github.com/mihaita-tinta/boot-config-repo/application.properties","source":{"server.port":"0"}}]}`

Is this something that can be fixed? Or is another configuration available to get this working on windows?

**Comment by dsyer** [comment]
I am having a hard time making a test case that fails. What version are you using?

**Comment by mihaita-tinta** [comment]
I used the spring-cloud-config-server 1.0.1.RELEASE version with java 1.8.0_25 on Windows 8.1.
Hope it helps. Thanks.

**Comment by dsyer** [comment]
OK, that's pretty old. Please try the latest stable release.

**Comment by mihaita-tinta** [comment]
Sorry for the delay. I had some trouble running the latest version with Spring Boot. It works fine, both filepaths are normalized with: StringUtils.cleanPath

https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/NativeEnvironmentRepository.java#L188

Thank you for your help.
