### ISSUE TITLE
Iterate over an array

### ISSUE THREAD

**Issue by ghughal** [spring-cloud/spring-cloud-config#378]
Is there any way to iterate over an array and generate configs dynamically.

Example: With application.yml like this:

```
nginx:
    backend:
        - backend1.example.com
        - backend2.example.com
        - backend3.example.com
        - backend4.example.com
```

I need to generate something like this in nginx.conf

```
upstream backend {
    server backend1.example.com;
    server backend2.example.com;
    server backend3.example.com;
    server backend4.example.com;
}
```

**Comment by spencergibb** [comment]
Not currently. Do you want config server to generate this file? It should be simple enough to add a controller to your config server that did this using freemarker or something similar.

**Comment by ghughal** [comment]
@spencergibb - yes, we are thinking of using config server to general config file for all non java components and use it as central config server for all sprint boot apps.

Can you provide an example of how to add controller to config server? I was not able to find it.

**Comment by spencergibb** [comment]
There's no example I can think of. Just write a controller as you normally would in a normal boot app.
