### ISSUE TITLE
Question: config server applicationcontext started/refreshed/stoppend on each request to the config service

### ISSUE THREAD

**Issue by pfournea** [spring-cloud/spring-cloud-config#381]
Hi,

We have some batches running every 5 minutes using the config server for retrieving the configuration. In the log files of the config server we see on each request from the batch that the applicationcontext is refreshed for each call.

sequence:
* start application
* refresh context
* close context

   - 09:24:33.449 [http-nio-6499-exec-1] INFO  - **Starting application on s40jasstst01** with PID 5060 (started by susr_java_config_ser in D:\sxData\configservice) [o.s.b.StartupInfoLogger:logStarting:48]
   - 09:24:33.449 [http-nio-6499-exec-1] INFO  - The following profiles are active: tst [o.s.b.SpringApplication:logStartupProfileInfo:670]
   - 09:24:33.465 [http-nio-6499-exec-1] INFO  - **Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext**@48b5fc66: startup date [Fri Apr 22 09:24:33 CEST 2016]; root of context hierarchy [o.s.c.s.AbstractApplicationContext:prepareRefresh:578]
   - 09:24:33.465 [http-nio-6499-exec-1] INFO  - Started application in 0.11 seconds (JVM running for 3327.168) [o.s.b.StartupInfoLogger:logStarted:57]
   - 09:24:33.465 [http-nio-6499-exec-1] INFO  - Adding property source: file:/D:/sxData/java_io_tmpdir/configservice/config-repo-8950990226508586530/crmbatch.yml [o.s.c.c.s.e.NativeEnvironmentRepository:clean:224]
   - 09:24:33.465 [http-nio-6499-exec-1] INFO  - Adding property source: file:/D:/sxData/java_io_tmpdir/configservice/config-repo-8950990226508586530/application.yml [o.s.c.c.s.e.NativeEnvironmentRepository:clean:224]
   - 09:24:33.480 [http-nio-6499-exec-1] INFO  - **Closing org.springframework.context.annotation.AnnotationConfigApplicationContext**@48b5fc66: startup date [Fri Apr 22 09:24:33 CEST 2016]; root of context hierarchy [o.s.c.s.AbstractApplicationContext:doClose:960]
   - 09:30:34.513 [http-nio-6499-exec-9] INFO  - **Starting application** on s40jasstst01 with PID 5060 (started by susr_java_config_ser in D:\sxData\configservice) [o.s.b.StartupInfoLogger:logStarting:48]
   - 09:30:34.513 [http-nio-6499-exec-9] INFO  - The following profiles are active: tst [o.s.b.SpringApplication:logStartupProfileInfo:670]
   - 09:30:34.513 [http-nio-6499-exec-9] INFO  - **Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext**@3cace960: startup date [Fri Apr 22 09:30:34 CEST 2016]; root of context hierarchy [o.s.c.s.AbstractApplicationContext:prepareRefresh:578]
   - 09:30:34.529 [http-nio-6499-exec-9] INFO  - Started application in 0.125 seconds (JVM running for 3688.23) [o.s.b.StartupInfoLogger:logStarted:57]
   - 09:30:34.529 [http-nio-6499-exec-9] INFO  - Adding property source: file:/D:/sxData/java_io_tmpdir/configservice/config-repo-8950990226508586530/crmbatch.yml [o.s.c.c.s.e.NativeEnvironmentRepository:clean:224]
   - 09:30:34.529 [http-nio-6499-exec-9] INFO  - Adding property source: file:/D:/sxData/java_io_tmpdir/configservice/config-repo-8950990226508586530/application.yml [o.s.c.c.s.e.NativeEnvironmentRepository:clean:224]
   - 09:30:34.529 [http-nio-6499-exec-9] INFO  - **Closing org.springframework.context.annotation.AnnotationConfigApplicationContext**@3cace960: startup date [Fri Apr 22 09:30:34 CEST 2016]; root of context hierarchy [o.s.c.s.AbstractApplicationContext:doClose:960]

Questions:
* Why is the application context is started/stopped on each call? Why not just fetching the git repo for changes?
* Is this behaviour not problematic in case of stoppen/starting a lot of applications at once?

Thanks in advance!

Regards

Peter

**Comment by dsyer** [comment]
That's not the main context for the whole config server, it's just an implementation detail of how the properties are loaded for the `EnvironmentController` .
