### ISSUE TITLE
Allow config server to coalesce property sources

### ISSUE THREAD

**Issue by kpschuck** [spring-cloud/spring-cloud-config#387]
I wanted to see about the possibly of allowing the config server to coalesce property sources with the proper overrides. Say, for example, I wanted to configure global defaults and have them overridden by application-specific properties. 

I make a request to `/sample-app/local` and get the following json payload:
```json
{
    "name": "sample-app",
    "profiles": [
        "local"
    ],
    "label": "master",
    "propertySources": [
        {
            "name": "sample-app-local.yml",
            "source": {
                "port": "443"
            }
        }, {
            "name": "application.yml",
            "source": {
                "host": "imap.gmail.com",
                "port": "993"
            }
        }
    ]
}
```

On the client-side, I now have to build a properties map from the above resulting in the following properties:
```properties
host=imap.gmail.com
port=443
```

Instead of the client having to handle coalescing properties, can we have the config server serve them up with the proper overrides?

For example, something like this would be ideal, especially for clients that are not Spring applications and therefore do not implement spring-cloud-config-client:

```json
{
    "name": "sample-app",
    "profiles": [
        "local"
    ],
    "label": "master",
    "propertySources": [
        {
            "name": "sample-app-local.yml",
            "source": {
                "port": "443"
            }
        }, {
            "name": "application.yml",
            "source": {
                "host": "imap.gmail.com",
                "port": "993"
            }
        }
    ],
    "coalesced": {
        "host": "imap.gmail.com",
        "port": "443"
    }
}
```

I'm operating under the assumption that when a key exists in both `application.yml` and `sample-app-local.yml` (port in the above example), that only those keys will be overridden and the global `host` key will still be part of the final "coalesced" configuration.

**Comment by spencergibb** [comment]
Two things, the config-client plugs those properties into the Spring `Environment` which gives you that exact thing. Also the config server has other api's that also coalesce and format.  From https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentController.java#L111-L178

They aren't documented really well and don't allow `-` in name or profile.
```
/{name}-{profiles}.properties
/{label}/{name}-{profiles}.properties
{name}-{profiles}.json
/{label}/{name}-{profiles}.json
/{name}-{profiles}.yml
/{name}-{profiles}.yaml
/{label}/{name}-{profiles}.yml
/{label}/{name}-{profiles}.yaml
```

**Comment by kpschuck** [comment]
Excellent, thanks for the prompt response @spencergibb
