### ISSUE TITLE
Git availability - config server fallback

### ISSUE THREAD

**Issue by jeffnelson** [spring-cloud/spring-cloud-config#390]
My project is having issues with git availability. Our config server points to an internal github enterprise server. For the most part this works fine, but we have issues when our enterprise git is down for maintenance. Our Production environment cannot be this tied to our enterprise git.

We have been brainstorming and have a few ideas on how to handle it, but so far everything we've come up with requires some custom code.

Do you have any suggestions, tips, pointers, etc regarding this situation?

**Comment by dsyer** [comment]
Can you describe the issues in a bit more detail? There are plenty of other issues in github that might be relevant I think as well, so you might be able to contribute to the discussion (e.g. #342 #157 #87 #6).

**Comment by jeffnelson** [comment]
Closing this. The newer version (1.0.4) of config server resolved the issues I was having.

Thanks.

**Comment by KramKroc** [comment]
@jeffnelson what did you make use of in 1.0.4 that solved your issues?
