### ISSUE TITLE
How config server supports a keystore with multiple private keys for encrypt (or decrypt) feature?

### ISSUE THREAD

**Issue by lipinggm** [spring-cloud/spring-cloud-config#394]
Our config server will be accessed by multiple client applications, due to the security reason, for config server encrypt/decrypt feature, we has to create a keystore (.jks file) with multiple private keys, each key will dedicate to the specific client application. So we don't have to share the same keystore/password among the clients as well as config server. Here are my questions:
1. How to properly configure Config Server's encryption properties, for a single private key, it's much easier because there is only one alias needs to be set, but in our case, we have multiple aliases for the same .jks store

> encrypt.keyStore.location=classpath:/xxx.jks
> encrypt.keyStore.password=xxx
> encrypt.keyStore.alias=xxxx (there are multiple keys, how can we config this property ?)
> encrypt.keyStore.secret=xxxx(there are multiple keys, how can we config this property ?)

2. If we use Config Server's /encrypt (or /decrypt) endpoint, how to pass 'alias' (private key) information to the config server so the service will pick the right key to do the encryption/decryption? Any available sample url to share with us?

Any help is highly appreciated!

**Comment by dsyer** [comment]
Did you read this section in the user guide: http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_using_multiple_keys_and_key_rotation?

**Comment by lipinggm** [comment]
Thank you Dave. Yes, I read it for couple times, that means to locate a key, we have to put {key:value}{secret:value} in front of each encrypted properties, do you have any sample of using custom SecretLocator for this case?

Regarding to question on how to use Config Server's encrypt/decrypt endpoint with multiple keys, there is a statement under the doc:
![image](https://cloud.githubusercontent.com/assets/13051111/15118189/1b234bd6-15d9-11e6-9d33-e15b6ad51990.png)

What above statement means? I tried to use http request header or url query string to locate key but neither approach worked.

Thank you so much for any help.

**Comment by lipinggm** [comment]
I am able to use /encrypt (or /decrypt) to do the encryption (or decryption) when the keystore has multiple keys, we only need to put the following information inside http request body like this:
{"key":xxx,
"secret":xxx}

For encrypted configurations, we will put {key:xxx}{secret:xxx} prefix by following the instruction indicated in the spring cloud document.

Thanks

**Comment by Jayanta0123** [comment]
Hey team,

I am reopening this thread, I also need to do a similar exercise using spring-cloud config. Giving you a short description below, please suggest if that's doable in spring config-server or not.

I have multiple teams (team-A, team-B, team-C) using the same config-server. All of them should add their own secrets in the bootstrap file, yml code might look similar to this

 ```
encrypt: 
     teamA-key:    56ABCD##$%
     teamB-key:    ABDC@3451
     teamC-key:    BGHdf12341
```
If I use only one-key, my purpose is served - but I have to share the key across teams. I'm looking for a way to let config-server
reads and understands multiple secret keys in run-time and use them for encryption and decryption.

Please note, I want to stick to **symmetric encryption only**, don't want to take the asymmetric path now.

**Comment by dsyer** [comment]
The relevant section of the User Guide is here: https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_using_multiple_keys_and_key_rotation

**Comment by Jayanta0123** [comment]
I tried, no luck yet. Can I use multiple secret keys like above without generating the key-store file?

**Comment by dsyer** [comment]
I guess if you're not using a key store then you need your own `TextEncryptorLocator`. There isn't much demand, so one hasn't been added to the project that works with symmetric encryption.

**Comment by dsyer** [comment]
Not sure. Probably. It would have to have config settings for the secrets and salts, so something like the above. When you have something that works for you, why not send a pull request?

**Comment by Jayanta0123** [comment]
@dsyer - my application is actually failing to launch with the ConfigurationProperties and Component annotation. 

I have added SymmetricTextEncryptorLocator class, annotating it like above, have declared the encrypt.key and secret.keys in yml file. But getting an error like below.


![image](https://user-images.githubusercontent.com/13516046/181711702-231da402-25d3-46a1-ba4e-44a27037ee9e.png)

**Comment by dsyer** [comment]
The exception says it doesn't like a "non-hex character" (probably in the text you obscured). You probably need to fix your YAML.

**Comment by Jayanta0123** [comment]
```
encrypt:
  key: market-intelligence-and-rating

secrets:
  keys:
    rx-api-key: D057C5D8E4
  salt: headHoldHigh

```
This is what I used @dsyer. There's no company-proprietary data - hence I added the plain-texts above. 

Configuration properties annotation is causing an issue for me to launch the application

**Comment by dsyer** [comment]
That looks OK to me, but you haven't shared all your code. Did you copy my code precisely, or did you modify it? The version I wrote would have bound to a string.

**Comment by Jayanta0123** [comment]
Hello @dsyer ,

I'm able to make the config-server work now - the salt need to be hex-encoded (0...9,a...f), and it need to be of even lengths. These are the two conditions to satisfy.

However, looking at all other aspects, it seems multiple key encryption using a keystore would be more correct approach for me. Thanks for all your help.
