### ISSUE TITLE
ConfigurationPropertiesRebinder exists in 2 jars in spring cloud

### ISSUE THREAD

**Issue by yairogen** [spring-cloud/spring-cloud-config#395]
Trying out latest spring cloud starter milestone: 'Brixton.RC2', and correlating jars: 'spring-cloud-config-client:1.0.0.RC2' and 'spring-cloud-context:1.1.0.RC3'. I picked latest from milestone for each.

I get problems as the class 'ConfigurationPropertiesRebinder' exists in both above jars and the 2 classes are not identical.

My app fails on NoClassDefFound.

**Comment by igreenfield** [comment]
I have the same problem!

**Comment by spencergibb** [comment]
Config client 1.0.0.RC2 is not the latest, 1.1.0.RC2 is.

**Comment by yairogen** [comment]
Thanks.
