### ISSUE TITLE
Seeking advice: to be able to start Config server client with and without config server 

### ISSUE THREAD

**Issue by lipinggm** [spring-cloud/spring-cloud-config#397]
Dear all,

Our config server client application's availability is very critical for our customer. That means that our application should able to be kicked off with or without config server. 

Here is our design:
Config server gets the configuration (includes encrypted properties) from a git repo and do the decryption whenever needed. Before starting config server client, the configuration file(s) will be directly copied from git repo to config server client box, if config server is not available, the client then reads the configuration from the local copy and do the description whenever needed. That means that the client side has to have keystore installed, this is the least we would like to do to deploy keystores cross different config server client(s) (or per environments). (Note: on the config server side, we might have to use the keystore with multiple private keys)

I really would like to seek your expert advice on the solution, is there any better way to solve the issue?

**Comment by spencergibb** [comment]
Are you trying to do this for production? or to support other environments? At that point, what is the point of a config server?

**Comment by lipinggm** [comment]
This is for both production and non-production environments. Actually there are two issues:
1. Multiple applications share the same config server (behind the load balancer). Because some config server client has very sensitive configuration data and the users/customers of the client don't want to expose their sensitive information to the other applications, that leads to the consideration of using a keystore with multiple private keys for each specific client on config server side. Do you recommend any solution that could hide private credential used for one client from other's?
2. How to ensure that the client application is able to start even when config server is down for some reason? Or the client should fail if config server is not available during the starting ? What's your recommendation on this matter?

**Comment by lipinggm** [comment]
Here is our solution related to above questions
#1)Config server will use a keystore which has multiple private keys dedicated to the specific client. Each private keys' credentials could be passed through environment variables without being exposed to the unauthorized users.
#2)We decided (or normal case) to allow client fail if config server is down. We also provide a script to the support team so they still can kick off client without config server whenever needed.
