### ISSUE TITLE
Local encrypted properties can't be decrypted within logback-spring.xml

### ISSUE THREAD

**Issue by soiff** [spring-cloud/spring-cloud-config#398]
I tried to use spring boot logback extensions and spring cloud config feature. What I want to do is use `DBAppender` and set data source's password from encrypted properties. But I've found it cannot be decrypted in `logback-spring.xml`.

Is it too early? If I try to retrieve the encrypted value by `@Value` in `CommandLineRunner#run()`, it's fine.

Could I use encrypted properties in `logback-spring.xml`? And how?

**Comment by spencergibb** [comment]
logging is configured very early in spring boot. My guess is that it's too early.

**Comment by 3792274** [comment]
try this 
https://github.com/ulisesbocchio/jasypt-spring-boot

**Comment by soiff** [comment]
Thanks! It seems like a great work!
