### ISSUE TITLE
logging.file property not getting used from cloud config

### ISSUE THREAD

**Issue by jmandawg** [spring-cloud/spring-cloud-config#399]
We have the following in our application.properties in our cloud-config-server:

logging.file: /logs/${spring.application.name}.log

The application picks up the properties file, but the logger is not using it.  Instead it writes to /temp/spring.log

Any ideas?

**Comment by spencergibb** [comment]
Logging gets initialized very early in boot. I wonder if it is too early to do something like this.

**Comment by shakuzen** [comment]
@jmandawg What versions of Spring Boot and Spring Cloud are you using? I'm doing something similar and it works for me with the latest release versions (Boot 1.3.5 and Brixton.RELEASE).

**Comment by jmandawg** [comment]
spring boot 1.3.3.RELEASE and Srping cloud 1.1.0.M4.  
It actually used to work on spring-boot 1.3.1.RELEASE.  Maybe i need to upgrade to 1.3.5.

**Comment by shakuzen** [comment]
Yes. There was a regression that was fixed in Spring Boot 1.3.4 (see spring-projects/spring-boot#5491) Please try again after upgrading to Brixton.RELEASE and Spring Boot 1.3.5.RELEASE.

**Comment by jmandawg** [comment]
Yeah, it works fine in 1.3.5.RELEASE.  Thanks

**Comment by miller79** [comment]
I just tried this with Spring Boot 1.4.1.RELEASE and Spring Cloud Brixton.RELEASE and it looks like this bug may have returned.  It definitely works fine with Spring Boot 1.3.5.RELEASE and Spring Cloud Brixton.RELEASE however.  Can this issue be rechecked with that version?

**Comment by spencergibb** [comment]
Brixton.SR6 is the latest Brixton release, please try with that first.

**Comment by miller79** [comment]
Just tried it and that seemed to have cleared up the issue.  Thanks!

**Comment by ezraroi** [comment]
Hi, in spring boot 1.4.5 and Camden.SR6 looks like this returned...

**Comment by spencergibb** [comment]
Please open a new issue
