### ISSUE TITLE
ConfigurationClassPostProcessor cannot enhance bean "refreshScope"

### ISSUE THREAD

**Issue by mmoayyed** [spring-cloud/spring-cloud-config#401]
```bash
WARN [org.springframework.context.annotation.ConfigurationClassPostProcessor] - 
<Cannot enhance @Configuration bean definition 'refreshScope' since its singleton instance has been
created too early. The typical cause is a non-static @Bean method with a 
BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.>

```

Seeing this with Spring 2.4.6. Recently upgraded from 1.0.4.RELEASE where this warning was non-apparent. Is this something to be concerned about?

**Comment by shakuzen** [comment]
Are you using `@RefreshScope` on a `@Configuration ` class? There is a corresponding note in the documentation regarding that. See the [RefreshScope section](http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_refresh_scope). Generally speaking, configuration classes themselves are not what you want to make refresh scope.

**Comment by mmoayyed** [comment]
Thanks. It appears that there a quite a few Configuration classes that do carry that annotation. I'll get them removed.

**Comment by mmoayyed** [comment]
Turns out this isnt quite solved: I removed all traces of @RefreshScope from all @Configuration classes, and ran a global search to ensure. I still see the log warning message.

**Comment by mmoayyed** [comment]
If it helps, I am using Boot 1.3.5.RELEASE

**Comment by dsyer** [comment]
I think it's fine. It's just telling you about a bean that is configured in the framework now.

**Comment by mmoayyed** [comment]
Thanks for the confirmation.

Of course, would have been more reassuring if it wasnt logged as WARN, but I understand that is core to Spring and not the cloud config.

**Comment by janlisse** [comment]
Hallo @dsyer ,

i don't think it's fine having a WARN logged on every application startup. Won't you agree?

**Comment by dsyer** [comment]
I don't think this is the only WARN log when an app starts up, once it gets to something sufficiently complex. Besides I don't think there is a way to stop this one, since it comes from Spring (not from Spring Cloud). If you see a way to stop it please open a new issue, since it is not really relevant to the oroginal question here.

**Comment by janlisse** [comment]
In our App which i would subsume under "sufficiently complex", this is the ONLY warning that is logged during startup. Besides that you are right, the original question was a little bit different. Nevertheless i think it is a bad practice having WARN's logged out that ought to be ignored.
And finally there might be a reason why the Spring people introduced it and it might indicate improper usage.

**Comment by dsyer** [comment]
I suggest you take it up with the Spring team then (https://jira.spring.io/browse/SPR) and/or open a new issue here.

**Comment by BastianVoigt** [comment]
Getting an App completely WARN-free is common practice in our organisation because we have a WARNINGS histogram chart on our DevOps monitor. We want this chart to be free of "noise" so that we can see when anything really goes wrong. Therefore regular warnings or errors that get logged every so often are very annoying for us. I think this bug should be reopened.

**Comment by dsyer** [comment]
Maybe you didn't read the comment above? In my opinion this warning is completely benign, and we don't control it in Spring Cloud anyway, so calling it a "bug" is a tad incendiary, and unlikely to win you any friends. Please open an issue in the Spring JIRA if you want to dig into the technical reasons for the log.

**Comment by dsyer** [comment]
Also, RefreshScope is in Spring Cloud Commons, so this is the wrong place to discuss changes.

**Comment by kyounger** [comment]
@BastianVoigt, you can configure the log level for that specific class to turn off logging.
