### ISSUE TITLE
Couldn't load ecrypt keystore jks file if the jks is not pre-packed with config server (or client)

### ISSUE THREAD

**Issue by lipinggm** [spring-cloud/spring-cloud-config#402]
Here is our use case

I am trying to make spring cloud config server (or client) to load runtime supplied keystore jks based on jvm option encrypt.keyStore.location( as we did for javax.net.ssl.trustStore), but the service doesn’t work as expected. Based on my debug observation, spring cloud encyption related class only loads encrypt jks file from its package, if jks is not build with the application, the application couldn't locate it.

The key failure point is at Spring Cloud function RsaEncryptionConfiguration.textEncryptor() ( at the statement :  if (keyStore.getLocation() != null && keyStore.getLocation().exists()) ...)

```
@Bean
		@ConditionalOnMissingBean(TextEncryptor.class)
		public TextEncryptor textEncryptor() {
			KeyStore keyStore = this.key.getKeyStore();
			if (keyStore.getLocation() != null && keyStore.getLocation().exists()) {
				return new RsaSecretEncryptor(
						new KeyStoreKeyFactory(keyStore.getLocation(), keyStore
								.getPassword().toCharArray()).getKeyPair(
										keyStore.getAlias(), keyStore.getSecret().toCharArray()),
										this.key.getRsa().getAlgorithm(), this.key.getRsa().getSalt(), this.key.getRsa()
										.isStrong());
			}
			return new EncryptorFactory().create(this.key.getKey());
		}

	}
```

Above function then calls spring function ClassPathResource.resolveURL() which calls classLoader.getResource(..) and failed because the jks is not stored in package hierarchy during build time.

```
                protected URL resolveURL() {
		if (this.clazz != null) {
			return this.clazz.getResource(this.path);
		}
		else if (this.classLoader != null) {
			return this.classLoader.getResource(this.path);
		}
		else {
			return ClassLoader.getSystemResource(this.path);
		}
	}
```
What I did wrong? Or it's a spring cloud encryption bug or limitation? Have anyone out there had tried to supply dynamic jks file at runtime before?

Any help is highly appreciated.

**Comment by lipinggm** [comment]
To simplify my question: can we dynamically specify encrypt jks file & its location (like other property such as javax.net.ssl.trustStore) instead of pre-packed the keystore with the spring boot application?

By the way, I am using spring cloud: Angel.SR4

**Comment by dsyer** [comment]
The keystore location is ` Resource`. It will resolve to an external location if you provide a prefix (e./g. `file:` or `http:`). This is a core Spring feature (nothing to do with Spring Cloud).

**Comment by lipinggm** [comment]
Thank you @dsyer for your valuable information. I am able to solve the issue by just putting 'file:' prefix in front of the keystore file path.
