### ISSUE TITLE
can config server set password to prevent any client?

### ISSUE THREAD

**Issue by dragontree101** [spring-cloud/spring-cloud-config#406]
can i start up a config server and set a password?
and client can get config properties if this client has password? 
if client doesn't have password, it can not get config properties from config server?

i means only client has password, it can get properties from server.

spring cloud config can support this feature?
thanks!

**Comment by shakuzen** [comment]
Yes, please check the [Security section of the documentation](http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_security). You can secure the config server in many ways. The simplest, which sounds like what you described, can be done with basic auth by simply adding `spring-boot-starter-security` as a dependency (as mentioned in the linked documentation).
You can also ask these kind of usage questions on the [Gitter channel for Spring Cloud](https://gitter.im/spring-cloud/spring-cloud).

**Comment by dragontree101** [comment]
thanks
i need add dependency `spring-boot-starter-security` in client and server?  
do you have some examples?
