### ISSUE TITLE
Spring Cloud Config Server Save API

### ISSUE THREAD

**Issue by magaton** [spring-cloud/spring-cloud-config#408]
Hi, is there a reason for not implementing push or general save in EnvironmentRepository?
We have an app implemented that lists the files from the specified dir (native) or git repository.
When we change the property, we'd like to save it, but there is no API available. Pushing file externally is not an option for us, since this config app is client facing. 
Now, we can do that using JGit, but beforehand, I'd like to see what you think.

**Comment by spencergibb** [comment]
It's been a non goal since the beginning. Writing brings in lots of security and stateful questions that we didn't want to deal with. Help me understand your use case a bit better. Specifically

> When we change the property, we'd like to save it, but there is no API available. Pushing file externally is not an option for us, since this config app is client facing.

**Comment by magaton** [comment]
The way how it is supposed to work currently, (as far as I understand) is to change property externally, push it to git and then either explicitly call /refresh or implement a webhook and call /monitor within a webhook. There is also a project on github that does poll every N seconds and do refresh automatically. We'd like to enable config change directly from web ui (admin part of client facing app). In order to do that, we'd need to initiate git push from the UI. Does this make sense?

**Comment by spencergibb** [comment]
Yes. That's not something we're currently interested in doing.

**Comment by magaton** [comment]
Is there a way to plug our own custom implementation of EnvironmentRepository where we can implement save api?

**Comment by dsyer** [comment]
Naturally. You just need to implement the interface and declare a `@Bean`.
