### ISSUE TITLE
How to encrypt 'secret' value by customizing SecretLocator

### ISSUE THREAD

**Issue by lipinggm** [spring-cloud/spring-cloud-config#412]
Our Config Server supports a keystore with multiple private keys for encryption/decryption. So we have to prefix encrypted application configuration values with {cipher}{key:keyvalue}{secret:secretvalue}, but leaving plain secret value without encryption is not secure, we would like to encrypt the value based on the recommendation of [Config Server Doc](http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_using_multiple_keys_and_key_rotation):

> If you do supply a secret it is recommended that you also encrypt the secrets using a custom SecretLocator.

But so far we couldn't find any online sample or information regarding to encrypting 'secret' value, so I am seeking help from this forum, any help is highly appreciated.

**Comment by dsyer** [comment]
Why do you need a secret in the cipher text? You should be able to build that into your `TextEncryptorLocator` logic. If you can't then `SecretLocator` is a last resort (it's just a strategy - implement it and declare a bean).

**Comment by lipinggm** [comment]
Thank you @dsyer 
Maybe it's a dumb question: assume I created a CustomizedTextEncryptorLocator, how to inject this customizedTextEncryptorLocator into existing Config Server without introducing too many code changes?

**Comment by lipinggm** [comment]
I am able to use Spring Auto-configuration to do the trick. Thanks.

**Comment by ryanjbaxter** [comment]
@arthurarts please dont comment on old issues that are closed.  If you have an issue please open a separate issue containing a project that reproduces the problem.  For questions you can reach out to us on StackOverflow or Gitter.
