### ISSUE TITLE
Properties versioning solution

### ISSUE THREAD

**Issue by ergomes** [spring-cloud/spring-cloud-config#413]
Hi All,

I am probably missing something here, but what is a good solution for properties versioning?

For example, in a blue-green deployment scenario with property value changes (old app version consumes the old value, new version requires the new value), how do you ensure both versions of your app can successfully co-exist (considering potential restarts and rollbacks)?

One option would be to create new property names for the properties that need new values applied. This, of course, is not a good option as we need to track all the usages of that property in the code base and update its reference accordingly. It is also not nice from a conceptual perspective.

Another option is to have a branch for each release. While this could work very well for this scenario, I envisage a branch/tag hell as we scale to the config repo to multiple apps and their respective branches evolve into different directions. 

A solution to the branch hell would be to have a separated config repo for each app. But, I believe this in some sense defeats the purpose of the config server as it adds overhead.

While this is more of a question rather than an issue, I decided to post it here as it may as well become a feature request.

**Comment by qinnnyul** [comment]
We are having the same concern when we try to adopt spring config server into our project, hopefully there is a good solution to bule-green deployment.

**Comment by spencergibb** [comment]
Many people have a repo per app or team.

**Comment by dsyer** [comment]
You can use commit ids and tags as well as branches, even in a single repo that gives you a lot of options.

**Comment by hellojukay** [comment]
I have the same question!
