### ISSUE TITLE
DefaultLabel property doesn't work with Brixton

### ISSUE THREAD

**Issue by airanluis** [spring-cloud/spring-cloud-config#414]
DefaultLabel property server configuration works with Angel, but not with Brixton.

Example:

Config server configuration:
-----------------------------------------------------------------------------------------------------------------
<pre><code>
spring:
  application:
      name: configsrv
  cloud:
      config:
        server:
          git:
            # Default URI
            uri: file://home/airan/git/default

            # Pattern matching for microservice's name for every project
            repos:
              local:
                pattern: local*
                uri: file://home/airan/git/local

          defaultLabel: develop
server:
  port: 8585
</code></pre>
-----------------------------------------------------------------------------------------------------------------------------
/home/airan/git/local/application.yml (develop branch)

branch.name: develop
---------------------------------------------------------------------------------------------------------------------------
/home/airan/git/local/application.yml (master branch)

branch.name: master
--------------------------------------------------------------------------------------------------------------------

Curl with Angel:

curl http://localhost:8585/local/env

Response:
<pre><code>
{"name":"local","profiles":["env"],"label":"develop","propertySources":[{"name":"file://home/airan/git/local/application.yml","source":{"branch.name":"develop"}}]}
</code></pre>

-----------------------------------------------------------------------------------------------------------------------------
Curl with Brixton:

curl http://localhost:8585/local/env

Response:
<pre><code>
{"name":"local","profiles":["env"],"label":null,"version":"73357433750abfea45bc93d7792897174db07bd3","propertySources":[{"name":"file://home/airan/git/local/application.yml","source":{"branch.name":"master"}}]}
</code></pre>

**Comment by spencergibb** [comment]
I am unable to reproduce your problem. Setting the `defaultLabel` works for me. Can you provide a project and git repo that reproduces the problem?

**Comment by airanluis** [comment]
Spring config server: https://github.com/airanluis/brixton-config-server.git
        master-> brixton release
        angel-> angel release

-----------------------------------------------------------------------------------------------------------------------
Curl with brixton

curl http://localhost:8585/labeltest/default

Response
<pre><code>
{"name":"labeltest","profiles":["default"],"label":null,"version":"5978ebcafedaf3afc3ac5f1961531c07aa8ce194","propertySources":[{"name":"https://github.com/airanluis/defaultLabelTestRepo.git/labeltest.yml","source":{"label.name":"master"}}]}
</code></pre>

Curl with angel

curl http://localhost:8585/labeltest/default

Response
<pre><code>
{"name":"labeltest","profiles":["default"],"label":"develop","propertySources":[{"name":"https://github.com/airanluis/defaultLabelTestRepo.git/labeltest.yml","source":{"label.name":"develop"}}]}
</code></pre>

**Comment by spencergibb** [comment]
I can confirm the behavior. The global default is not used in anything defined under `repo`.

Workaround:
```
spring:
  cloud:
    config:
      server:
        defaultLabel: develop
        git:
          uri: https://github.com/airanluis/defaultTestRepo.git
          repos:
            label:
              pattern: label*
              uri: https://github.com/airanluis/defaultLabelTestRepo.git
              defaultLabel: ${spring.cloud.config.server.defaultLabel}
```

@dsyer why in d4ce149f2d613b74a59a7d95e2d7dbf46eaa1bed did you 
> Also removes getDefaultLabel() from EnvironmentRepository.

**Comment by dsyer** [comment]
That was to push the control of the label up to the controller. It should be passed down from there.

**Comment by spencergibb** [comment]
How would we even know to use `server.defaultLabel` vs. `repos.<myrepo>.defaultLabel`? Or do we say the behavior has changed and `server.defaultLabel` only applies to `server.git.uri`?

**Comment by dsyer** [comment]
We only removed the default label from the interface. It is still there in the concrete implementation, so I think it can be used in the multi git case. If it isn't being used I guess it's a bug (as described).
