### ISSUE TITLE
classpath prefix not supported as uri

### ISSUE THREAD

**Issue by openwms** [spring-cloud/spring-cloud-config#418]
the `spring.cloud.config.uri` should ideally point to a git repo. Local (file://) or remote (http://). But could it although point to jar packaged classpath resources? This is useful for development purpose only. The property setting is then be overridden in production - as environment property.

**Comment by dsyer** [comment]
That might work in the "native" profile. Clearly it is a bad idea for the git repository (the classpath should not contain git metadata).

**Comment by spencergibb** [comment]
I agree with @dsyer it could work with `native`, but not `git`.

**Comment by openwms** [comment]
I completely agree that the classpath should not contain any git metadata. I think about having a simple config folder on the classpath that is taken as configuration base. Currently I reference such a folder absolutely with the `file:/`prefix. When the app is deployed in a cloud environment the `spring.cloud.config.uri` parameter is set to a git repo. I don't see why a git repo _must_ always be referenced

**Comment by spencergibb** [comment]
`spring.cloud.config.uri` is the setting used by config client as the uri of the actual config server. Are you talking about `spring.cloud.config.server.git.uri`?

**Comment by openwms** [comment]
On configuration client side I set in bootstrap.properties `spring.cloud.config.uri=file://data/.../src/main/resources/config` and it works - currently with absolute path. This property is different in production.

**Comment by spencergibb** [comment]
@openwms this makes no sense to me `spring.cloud.config.uri` is a client side uri to config server. Pointing to a fail should fail. You'll have to share a project that shows what you are doing.

**Comment by openwms** [comment]
Request closed. I don't want to build an re-producer so we can close this here because it works for me. Thanks for your support!
