### ISSUE TITLE
afterPropertiesSet failure when using encryption on password property in bootstrap/embedded mode

### ISSUE THREAD

**Issue by rlynch** [spring-cloud/spring-cloud-config#419]
FYI, using Spring Cloud Config 1.1.0-RELEASE

I have a scenario where I am unable to start due to a failed assertion inside the JGitEnviromentRepository method afterPropertiesSet on line 133.  First, let me describe my setup.
1) I am running a bootstrapped version of spring cloud config so I can retrieve the configuration of spring config server itself from git as described in http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_embedding_the_config_server
2) I am encrypting the password of the additional repos I am configuring in my external git repo using the {cipher} annotation as described in http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_encryption_and_decryption

During startup the afterPropertiesSet call is occurring multiple times as each round of property setting/injection on the bean occurs.  On the first round on onPropertySet() in MultipleJGitEnvironmentRepository is for the decryption of any encrypted fields. As a result, only the password field is being set and importantly the username/uri fields are still null.  This causes the following assertion to fail from JGitEnvironmentRepository on line 133.

	@Override
	public void afterPropertiesSet() throws Exception {
		Assert.state(getUri() != null,
				"You need to configure a uri for the git repository");
		if (this.cloneOnStart) {
			initClonedRepository();
		}
	}

It seems that the afterPropertiesSet() is the wrong event handler to use to see if we should clone the repo.  Is there another way to work around this?

**Comment by dsyer** [comment]
Why can't you just set the URI property as well?

**Comment by rlynch** [comment]
The URI is set in the configuration file but during initialization it appears that spring puts the bean through at least two rounds of applying the properties with each round causing a call to afterPropertiesSet().  The first round only sets the encrypted properties (the password in my case) so as a result the rest of the non password properties are null thus causing the assertion to fail.

**Comment by dsyer** [comment]
I think if you look closely you will find that there are 2 beans (and probably 2 application contexts). If one of them is invalid all you have to do to make it valid is set the URI. Maybe a sample app would help, if you could throw one together and paste a link?
