### ISSUE TITLE
Endpoints /pause, /resume and /restart not disable

### ISSUE THREAD

**Issue by hocklo** [spring-cloud/spring-cloud-config#420]
I'll try to disable /pause, /resume and /restart endpoint but doesn't work.

`endpoints.pause.enabled=false`
`endpoints.restart.enabled=false`
`endpoints.resume.enabled=false`

![screenshot at 2016-06-18 21 50 35](https://cloud.githubusercontent.com/assets/575408/16173341/da83faa4-359e-11e6-8eff-c7671cf2d9fa.png)

![screenshot at 2016-06-18 21 53 07](https://cloud.githubusercontent.com/assets/575408/16173349/164606ae-359f-11e6-85d9-e512d33e665c.png)

pom.xml:

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.5.RELEASE</version>
	</parent>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Brixton.SR1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-consul-discovery</artifactId>
		</dependency>
	</dependencies>

</project>

**Comment by spencergibb** [comment]
The endpoints still show in the mapping, but this is the response I get.

```
$ http POST :8080/pause
HTTP/1.1 404 Not Found
Content-Type: application/json;charset=UTF-8
Date: Mon, 20 Jun 2016 16:38:46 GMT
Server: Apache-Coyote/1.1
Transfer-Encoding: chunked
X-Application-Context: testeurekabrixtonclient

{
    "message": "This endpoint is disabled"
}
```

What happens if you try and post to `/pause`?

**Comment by hocklo** [comment]
Hi @spencergibb,

Im thinking that im not explain really well.

If you disable this endpoints, is necessary load this endpoints(Objects) at memory?

It's only for improve the performance at startup.

Thank you for your time.

**Comment by spencergibb** [comment]
Right, not they could not be created. Will you open a new issue here https://github.com/spring-cloud/spring-cloud-commons/issues since that is where the code lives.
