### ISSUE TITLE
Support for Java Security JKS config files

### ISSUE THREAD

**Issue by tjuchniewicz** [spring-cloud/spring-cloud-config#427]
We need to configure Java Security using JKS files and we want to use spring-cloud-config to override this configuration. There is no direct support for such case but my idea is to put Base64 encoded JKS file into configuration and force to override Java Security settings in some callback/listener method on the application side. 

The question is: Any other ideas to better support our case?

**Comment by spencergibb** [comment]
There is a spring event that is published that has the keys that have changed. I want to sat `EnvironmentChangedEvent` (not in front of code).

**Comment by spencergibb** [comment]
@tjuchniewicz the vent is `EnvironmentChangeEvent`. Config Server also supports [serving files](https://github.com/spring-cloud/spring-cloud-config/blob/master/docs/src/main/asciidoc/spring-cloud-config.adoc#serving-plain-text).

**Comment by tjuchniewicz** [comment]
Serving files. This is what I need. Thanks!
