### ISSUE TITLE
Override of properties seems not to work

### ISSUE THREAD

**Issue by HagarJNode** [spring-cloud/spring-cloud-config#428]
It seams like there are a bug with the git version when using override in the files in the repository.

Like 
application.yml and application-*.yml

Where one property from an application-*.yml file should override the values from the root file. But it doesn't... When I test the same thing in a svn repository it works.

**Comment by spencergibb** [comment]
Not enough information. Please expound. We use this regularly, so please provide steps to reproduce or better yet a project that reproduces the problem.

**Comment by HagarJNode** [comment]
I'll post a example first thing tomorrow morning when  I get back to the office. Basicly I had to move properties away from the base file and into env files to make the configuration work with the git repository.

**Comment by HagarJNode** [comment]
Ok... been testing and still not finished, but... so fare it doesn't looks as a git bug, but a property key issue:
So fare I noticed this in the application.yml and application-env.yml

Having application.yml

a:
  b: B
c : C

And application-env.yml
a:
  b: D
  
Will make the call  http://xxx/master/a-env.properties return the content of application.yml;
a.b=B
c=C

Changing the application.yml to
a:
  b: B
  c : C

Will return 
a.b=D
a.c=C


I'm not sure if this is a nested key level problem, yet, but I'm still testing

**Comment by HagarJNode** [comment]
Follow up... I think there is yet an issue... having a structure like:

```
folder/aa.yml
folder/aa-env.yml
application.yml
application-env.yml
```

It looks like changing some properties in the three, one have to remember the sub elements even tho they ain't changed:

folder/aa.yml:
```
a:
  b: B
  c: C
d: d
```
folder/aa-env.yml:
```
a:
  b: BB
  c: C
```
 In this case the **a.c** should be added in the env file too - if it's not present the aa-env content is not used.

**Comment by HagarJNode** [comment]
Sorry, one should have added the d as well - I think, as it's a 'root' key. I believe that the only content needed in the file should the following, as it's the only changes:

folder/aa-env.yml:
```
a:
  b: BB
```

**Comment by taa-autorola-com** [comment]
I ran into this problem as well, I'm totally upvoting this issue, it breaks my configurations!

**Comment by HagarJNode** [comment]
Looking at my issue, again, made me write a small example that illustrate the problem once again

Note that the a.test value changes when the test property is uncommeted. Both properties are in the app-env.yml file.

[bug.zip](https://github.com/spring-cloud/spring-cloud-config/files/413121/bug.zip)
[work_around.zip](https://github.com/spring-cloud/spring-cloud-config/files/413127/work_around.zip)

**Comment by dsyer** [comment]
Duplicates #441
