### ISSUE TITLE
Support for SSH git access with passphrase protected key

### ISSUE THREAD

**Issue by bitsofinfo** [spring-cloud/spring-cloud-config#431]
Is there any configuration option to provide the passphrase for the SSH key that accesses an SSH based git endpoint? The only way i could get it to work with `git@my.repo` was to strip the passphrase from the key. This should be added as it appears possible w/ jgit via a CredentialsProvider

http://stackoverflow.com/questions/12502452/how-do-you-set-the-configuration-for-jschconfigsessionfactory-for-jgit-so-that-p

**Comment by zxkane** [comment]
It would be a really nicer feature for git backend support.
