### ISSUE TITLE
Encryption about server and client of spring cloud config.

### ISSUE THREAD

**Issue by MingningShao** [spring-cloud/spring-cloud-config#438]
Well,whether can server client both encrypt and decrypt.
I noticed that only encrypted and decrypted on server side.How can i put encrypted and decrypted both on server and client,so i can encrypted and decrypted at ease.What's imporant,it will be much safer.
What's more,i want encrypted on client and sent encrypted data to server,then server decrypted and operate data,finally store encrypted data to DB.Also it has an reversed procedures.

**Comment by HagarJNode** [comment]
If you set the spring.cloud.config.server.encrypt.enabled=false in the server configuration it will send your {cipher} values without touching them, leaving it up to the clients to decrypt the content.

**Comment by MingningShao** [comment]
@HagarJNode I noticed that,but you still need to dev an interface to decrypt the cipher.If there any good ideas to encrypt/decrypt both server and client side?

**Comment by HagarJNode** [comment]
Yea, I implemented a TextEncryptor, it will do the encrypting and decrypting in some parts of our setup... On the matter regarding the server/client side encrypt/decrypt... well, we send all data over https, so we are basically using server side... the only client decrypting is to ensure encrypted the password to the server as we use basic auth.

**Comment by MingningShao** [comment]
@HagarJNode  Haha  ~~ yeah,that's great!Thanks~~~
