### ISSUE TITLE
@TestPropertySource does not override bootstrap properties

### ISSUE THREAD

**Issue by colin-shine** [spring-cloud/spring-cloud-config#440]
I am aware that [the documentation](http://projects.spring.io/spring-cloud/spring-cloud.html#_the_bootstrap_application_context) states that:
> Bootstrap properties are added with high precedence, so they cannot be overridden by local configuration

but it would be great if the `@TestPropertySource` annotation was able to override bootstrap properties for integration tests. Is this planned for the upcoming release?

**Comment by dsyer** [comment]
This issue is in the wrong repo (bootstrap context is a commons feature). You can use `@SpringBootTest` (or `@IntegrationTest` in older versions of Spring Boot) to override bootstrap properties. `@TestPropertySource` is (and always has been) broken IMO.

**Comment by marbon87** [comment]
I am running into the same problem. As far as i can see properties from spring cloud config cannot be overridden in a SpringBootTest with Spring Boot 2.1.8 and spring cloud config client 2.1.3.RELEASE
