### ISSUE TITLE
PropertySources are merged with wrong priority

### ISSUE THREAD

**Issue by elek** [spring-cloud/spring-cloud-config#441]
It seems that the property override mechanism is not working with the right priorities.

The problem is the implementation of the `EnvironmentController.convertToProperties` method.

## Scenario

Given three config files:

```
application.properties
A: X
S: 1
```

```
myapp.properties
A: Y
S: 2
```

```
myapp-myenv.properties
A: Z
S: 3
```

Getting the configuration myapp-myenv.properties from the configserver:

```
curl http://localhost:8888/myapp-myenv.properties 
```

The result is:

```
A: Z
S: 3
```

Which is ok.

But when I add a new key (from the end of the ABC ) to the myapp.properties:

```
application.properties
A: X
S: 1
```

```
myapp.properties
A: Y
S: 2
Y: 0
```

```
myapp-myenv.properties
A: Z
S: 3
```

The expected result is:

```
A: Z
S: 3
Y: 0
```

But I got the result:

```
A: Y
S: 2
Y: 0
```

The problem is the magic implementation of the `EnvironmentController.convertToProperties`. The `map` contains configuration property keys as keys but all of the sources as values which are note merged properly. (combined.putAll will use all of the properties from the latest source)

## To reproduce the problem (method 1)

Start a vanilla config server with `spring.cloud.config.server.git.uri=https://github.com/elek/spring-configserver-bug`

``curl http://localhost:8888/master/myapp-myenv.properties``

Result:

```
A: Z
S: 3
```

``curl http://localhost:8888/problem/myapp-myenv.properties``

Result:

```
A: Y
S: 2
Y: 0
```

Note: value of A and S has not been changed in any file I just added a new `Y` key to one of the files.

## To reproduce the problem (method 2)

Clone the fork: `https://github.com/elek/spring-cloud-config`

And run the `convertToPropertiesWithOverride` and `convertToPropertiesWithOverrideOrderProblem` new unit tests in `EnvironmentControllerTests`

**Comment by HagarJNode** [comment]
I guess this is somehow related to https://github.com/spring-cloud/spring-cloud-config/issues/428

**Comment by elek** [comment]
Could be. As I wrote the implementation of EnvironmentController.convertToProperties (as I think) totally wrong. And it could be the root cause...

**Comment by HagarJNode** [comment]
I think you're right... it looks a bit odd. I tried to make a checkout of the code, so that I could do something about it. But I ends up with a build error on windows telling me that it can't find egrep... even tho I have it with cygwin.

**Comment by dsyer** [comment]
`EnvironmentController.convertToProperties()` is utterly bizarre, I agree (@dmfrey is the culprit). We need some more tests...

**Comment by HagarJNode** [comment]
@dsyer I included some test files in the #428, they might be helpful.

**Comment by dsyer** [comment]
I used the sample here to test. If you can try with your sample too that would be helpful.

**Comment by HagarJNode** [comment]
Thumbs up! I just builded the 1.1.3.BUILD-SNAPSHOT and it's working just fine. Thankyou Dave. 
Any idea about when the release is coming up?

**Comment by dsyer** [comment]
https://github.com/spring-cloud/spring-cloud-release/milestone/21

**Comment by HagarJNode** [comment]
Great, thankyou!
