### ISSUE TITLE
RefreshScope

### ISSUE THREAD

**Issue by iboppana** [spring-cloud/spring-cloud-config#444]
Say we have a simple Application which talks to config server.
It has a Application class and a simple Class annotated as @RestController
In the RestController class we are using the property from configServer
@Value("${example-property}")
	String luckyWord;

We annotated the main ApplicationClass with @RefreshScope.
so when we post to /refresh endpoint does it gaurantee all the other beans in this application are refreshed too

Or each has to be separately annotated ?

**Comment by spencergibb** [comment]
Only refresh scope beans. But if you're just using `@Value`, move it to a `@ConfigurationProperties` and you don't need refresh scope beans.

**Comment by spencergibb** [comment]
Oh, and refresh scope doesn't work on `@Configuration` classes.
