### ISSUE TITLE
health indicator is DOWN if Config server git repository URL is defined with placeholders for the {application} and {profile}

### ISSUE THREAD

**Issue by lipinggm** [spring-cloud/spring-cloud-config#446]
According to [Config Server Document](http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html),  Spring Cloud Config Server supports a git repository URL with placeholders for the {application} and {profile}. So we define our config server git uri with the following value:
spring.cloud.config.server.git.uri=http://company.com/xxx/{application}/{application}-{profile}.git

Unfortunately this approach causes config server's health indicator issue: the health status of the server (shown below) is always 'DOWN'. Actually it doesn't surprise me because we don't provide default repo:  xxx/app/app-default.git used when config server is initialized.

```
{
    "status": "DOWN",
    "configServer": {
        "status": "DOWN",
        "repository": {
            "application": "app",
            "profiles": "default"
        },
        "error": "java.lang.IllegalStateException: Cannot clone or checkout repository"
    },
    "diskSpace": {
        "status": "UP",
        "total": 180043640832,
        "free": 56121884672,
        "threshold": 10485760
    },
    "refreshScope": {
        "status": "UP"
    }
}
```

It looks like defining config git.uri with {application} and {profile} placeholders makes it impossible for us to rely on the health indicator to monitor config server's health status. Does anyone have solution to the issue?

**Comment by spencergibb** [comment]
@lipinggm you can work around the problem by setting a specific repository to test or disabling the health check. See the docs http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_health_indicator

**Comment by sunnyWangXin** [comment]
Met similar problem. If I want to check health for specific client A, and I used {application} placeholder in server side, it always try to connect to application.git(seems the default repo name). Do we have any other way to pass application name A to server so the health indicator could check A.git? Thanks~

**Comment by spencergibb** [comment]
@sunnyWangXin no, did you try a workaround mentioned above?
