### ISSUE TITLE
Maven 3.2.1 compiled failed.

### ISSUE THREAD

**Issue by MingningShao** [spring-cloud/spring-cloud-config#463]
Maven version: 3.2.1
spring-cloud-config version: 1.1.0 Release
mvn compile -DskipTests=true

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (imports) on project spring-cloud-config: Command execution failed. Cannot run program "C:\Program Files\Git\usr\bin\egrep" (in directory "D:\Work\Cloud3.0\spring-cloud-config-1.1.0.RELEASE"): CreateProcess error=193.

if i used maven 3.3.9 it worked well,i want to whether do i need to use maven 3.3.*+?
Or,must 3.3.*+?

**Comment by spencergibb** [comment]
Yes, you must use 3.3.x which is why we document to use the maven wrapper `./mvnw` so you don't need to have maven installed and you always have the right version.

**Comment by gabrielruiu** [comment]
Weird, spring-boot-dependencies-1.4.0.RELEASE.pom defines Maven 3.2.1 as a minimum prerequisite:
```
<prerequisites>
	<maven>3.2.1</maven>
</prerequisites>
```

**Comment by spencergibb** [comment]
This isn't Spring Boot.

**Comment by MingningShao** [comment]
@spencergibb 3Q !
