### ISSUE TITLE
Improve interop with spring-security and auto configuration for multiple service accounts

### ISSUE THREAD

**Issue by btiernay** [spring-cloud/spring-cloud-config#464]
Currently, it is very difficult to implement a, presumably, very common use case: allow multiple service accounts to authenticate against a `spring-cloud-config-server` within a microservice architecture. Having [only one account](http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_security) (as is the case when using `spring-boot-starter-security` with `spring-cloud-config-server`) is not appropriate for production environments.

The difficulty of implementing multiple service accounts stems from the interplay between auto configuration, Spring Cloud endpoints and Spring Security. Right now one must disable `SecurityAutoConfiguration` and install a custom `WebSecurityConfigurerAdapter`. 

At the very least be better documented, but ideally should be possible out of the box. For example, it is unclear whether to use `SecurityProperties.ACCESS_OVERRIDE_ORDER` or `SecurityProperties.BASIC_AUTH_ORDER` when creating a `WebSecurityConfigurerAdapter` for this purpose. Much trial and error is needed to get this to work properly.

**Comment by spencergibb** [comment]
So securing config server is like securing any boot app. This might be a good idea for a blog post or guide. Beyond documentation, what were you hoping that we could do in spring cloud config?

**Comment by btiernay** [comment]
@spencergibb I think you are right. This might not be the best forum for such a request. But it is something that I know folks struggle with. It took me a while to get a working configuration going and I'm sure there must be a better way. Do you have any suggestions on how this would be best improved? Because it does involve various Spring modules, I'm not sure where to best direct the effort.

**Comment by btiernay** [comment]
I was able to get something going with names and labels:

```java
@Configuration
@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

  @Override
  protected void configure(HttpSecurity http) throws Exception {
    // TODO: Externalize
    val names = ImmutableList.of("dcc-portal");
    val profiles = ImmutableList.of("production");

    http
        .authorizeRequests()
        .antMatchers("/").permitAll();

    for (val name : names)
      for (val profile : profiles)
        authorize(http, "/" + name + "/" + profile + "/**", name, profile);

    for (val name : names)
      authorize(http, "/" + name + "/**/**", name, "*");

    for (val profile : profiles)
      authorize(http, "/**/" + profile + "/**", "*", profile);

    http
        .authorizeRequests()
        .anyRequest().authenticated()
        .and()
        .httpBasic();
  }

  @SneakyThrows
  private void authorize(HttpSecurity http, String pattern, String name, String profile) {
    http
        .authorizeRequests()
        .antMatchers(pattern)
        .access(or(hasAuthorities("name:*", "profile:*"), hasAuthorities("name:" + name, "profile:" + profile)));
  }

  private static String or(String... expressions) {
    return Stream.of(expressions).map(e -> "(" + e + ")").collect(joining(" || "));
  }

  private static String hasAuthorities(String... authorities) {
    return Stream.of(authorities).map(a -> "hasAuthority('" + a + "')").collect(joining(" && "));
  }

}
```

**Comment by ryanjbaxter** [comment]
Have you found anything in particular that you need to do because you are securing a config server?  To me this mostly seems like general configuration for any Boot app.

**Comment by btiernay** [comment]
@ryanjbaxter you are probably right here as this stuff may tend to be very environment specific.
