### ISSUE TITLE
Documentation is sometimes inconsistent

### ISSUE THREAD

**Issue by kelassar-zodis** [spring-cloud/spring-cloud-config#465]
Hi,

Trying to setup configuration client via consul discovery. Found out the service id tag should be spring.cloud.config.discovery.service-id and not spring.cloud.config.discovery.serviceId as written under: http://cloud.spring.io/spring-cloud-static/spring-cloud.html#discovery-first-bootstrap.

That ruined me some precious time. 
Would be nice to get a correction!

**Comment by spencergibb** [comment]
They both should work
