### ISSUE TITLE
Increase config server polling frequency on client

### ISSUE THREAD

**Issue by rbkumar88** [spring-cloud/spring-cloud-config#467]
Hi,

Is there any property available to control the frequency in which config server is polled from/on client side.

Thanks
Bharath

**Comment by spencergibb** [comment]
The client side does not poll the server, so not sure it makes sense.

**Comment by rbkumar88** [comment]
This keeps happening every 10 seconds on the microservice which looks up to the config uri/server for fetching properties.

2016-08-08 11:11:04.003  INFO 1612 --- [nio-8981-exec-5] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://XXX
2016-08-08 11:11:07.022  INFO 1612 --- [nio-8981-exec-5] c.c.c.ConfigServicePropertySourceLocator : Located environment: name=application, profiles=[local], label=null, version=b56a3d906ddfce27900693891400c1bf3f166611

**Comment by spencergibb** [comment]
There is no polling. Do you have a monitoring system that hits the health endpoint every 10 seconds?

**Comment by rbkumar88** [comment]
Yes we have Consul for Service discovery. So are you saying these logs are because of the spring.cloud.consul.discovery.health-check-interval and if that is the case,what is this ConfigServiceProperty has to do with Consul health check?

**Comment by spencergibb** [comment]
it has a health indicator. So it would need to be disabled by setting `health.config.enabled=false`. See #260 for more information.
