### ISSUE TITLE
Client cache after getting properties from sever

### ISSUE THREAD

**Issue by tezball** [spring-cloud/spring-cloud-config#471]
Question:
I'm trying to understand what happens to the properties after they load into the client. When the client gets the values, loads the properties does it ever flush the cache and contact the server for a fresh copy or does that only happen when the refresh endpoint is used?

If there is a cache timeout, can it be configured, turned off?

Many thanks!

Terry

**Comment by spencergibb** [comment]
They are loaded into the spring environment. There is no polling. There really is no cache either. Only when `/refresh` is called is when they will refresh.

**Comment by tezball** [comment]
Thanks @spencergibb for the quick response :+1:
