### ISSUE TITLE
The reference documentation links on cloud.spring.io are broken.

### ISSUE THREAD

**Issue by neildcruz19** [spring-cloud/spring-cloud-config#478]
Not sure if this is the right repo to raise this issue, but, the reference links on  https://cloud.spring.io/spring-cloud-config/ are broken.

**Comment by ryanjbaxter** [comment]
@marcingrzejszczak is this an issue with the new ghpages changes?

**Comment by dsyer** [comment]
Yes. I think @marcingrzejszczak changed them all and got it wrong somewhow.

**Comment by marcingrzejszczak** [comment]
Ehh `http` was missing at the beginning.

**Comment by ryanjbaxter** [comment]
Thanks!

**Comment by neildcruz19** [comment]
Thanks guys!
