### ISSUE TITLE
Git Environment Repository does not handle remotes updated from a forced push.

### ISSUE THREAD

**Issue by daniellavoie** [spring-cloud/spring-cloud-config#481]
If you ever force push on a branch served by the config server using an ssh git backend, the config server local repository will be left in a conflicting state. Accessing the HTTP endpoint will even serve you the json ENV properties with git conflict markers `>>>>>>>>>>` and `==========`.

I suggest that the `JGitEnvironmentRepository` operates a `git fetch` then `git reset --hard` operation rather than a simple `git pull`.

**Comment by daniellavoie** [comment]
I can come up with a PR but I'll need some inspiration to mock and reproduce the git operations on a remote. I am curious to figure out which approach was taken to unit test the `JGitEnvironmentRepository`. I doubt I'll be able to simulate a remote who diverged with a `git push --force`. Guess I'll have to stick with actual manual testing and make sure the current tests does not encounter any regression.

**Comment by daniellavoie** [comment]
Hello @ryanjbaxter. Any chances this will be part of Candem M2 ? Ciao !

**Comment by spencergibb** [comment]
I was just starting to look at this again

**Comment by ryanjbaxter** [comment]
@daniellavoie once @spencergibb finished taking a look at it I am sure we can get it merged
