### ISSUE TITLE
Encryption and Decryption of a symmetric key.What does it mean?

### ISSUE THREAD

**Issue by MingningShao** [spring-cloud/spring-cloud-config#482]
According to official doc:

> The Config Server can use a symmetric (shared) key or an asymmetric one (RSA key pair). The asymmetric choice is superior in terms of security, but it is often more convenient to use a symmetric key since **it is just a single property value to configure**.
> To configure a symmetric key you just need to set encrypt.key to a _**secret String**_ (or use an enviroment variable ENCRYPT_KEY to keep it out of plain text configuration files).

Well,what does secret String mean?And,what does the secret String used for?
What's more,do i need to encrypt it to be more security by a security component?
Why there only a string cloud encrypt and decrypt,not a private key?
Thanks!

**Comment by ryanjbaxter** [comment]
"Secret string" means a string that no one else knows.  Think of it as a key that is going to be used to encrypt the values.  If the string is compromised others could then use it to decrypt your encrypted values

**Comment by MingningShao** [comment]
@ryanjbaxter Does the secret string generate a key or just a value to used for encrypt/decrypt?Well,the secret String was of great importance for our system,how could us protect the secret String?

**Comment by spencergibb** [comment]
It is a key. It is inherently less secure than using a keystore. The best option is to pass it in as an environment variable.

**Comment by MingningShao** [comment]
@spencergibb But i can still get the secret String buy using method of get environment variable,such as System.getproperties("ENCRYPT_KEY").

**Comment by spencergibb** [comment]
Hence:
> It is inherently less secure than using a keystore.

**Comment by MingningShao** [comment]
@spencergibb If i used a keystore,how to protect keyStore.password?

**Comment by ryanjbaxter** [comment]
That is kind of outside the scope of the project.  You need to secure the server running the application to only those that should have access to it.
