### ISSUE TITLE
Unable to update the server.port property at runtime passing it as a command line argument if it is set in the config-repo

### ISSUE THREAD

**Issue by neildcruz19** [spring-cloud/spring-cloud-config#484]
I have a project where I have the server.port property set to 8083 in the config-repo.

I am not able to override this property from the command line args at run-time. Is this functionality as intended?

java -jar project.jar --server.port=8080

I am able to override it if i specify it in the bootstrap.yml.

**Comment by spencergibb** [comment]
Yes, we want the config server to be the ultimate source of truth. Often times we will do something like this in configserver:
```
server:
  port: ${PORT:8083}
```

Then running with `--port=8080` will override.

**Comment by neildcruz19** [comment]
Thanks, that helps!
