### ISSUE TITLE
Unresolved directive in spring-cloud.adoc

### ISSUE THREAD

**Issue by php-coder** [spring-cloud/spring-cloud-config#489]
At the end of the page http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html I see the error: `Unresolved directive in spring-cloud.adoc - include::../../../security/src/main/asciidoc/spring-cloud-security.adoc[]`

**Comment by spencergibb** [comment]
Closing in favor of https://github.com/spring-cloud-samples/scripts/issues/16
