### ISSUE TITLE
Client application try to fetch wrong config file

### ISSUE THREAD

**Issue by vpetit35** [spring-cloud/spring-cloud-config#494]
Hello, I observed that on startup, my application successfully fetch the remote config file with the following log message : 
`c.c.c.ConfigServicePropertySourceLocator : Located environment: name=app1, profiles=[dev], label=master, version=a238786e2ccd7a5ae69813b1f7d380b681617e09`

But then, when application is running, every 20sec I have this message : 
`c.c.c.ConfigServicePropertySourceLocator : Located environment: name=application, profiles=[dev], label=master, version=a238786e2ccd7a5ae69813b1f7d380b681617e09`

It seems that it try to fetch the config file for an application named 'application' instead of 'app1'.

**Comment by ryanjbaxter** [comment]
If your config server contains a file named `application.yml` or `application.properties` those properties will be applied to all applications with the more specific properties file taking precedence.  

From the [documentation](http://cloud.spring.io/spring-cloud-static/Brixton.SR5/#_environment_repository):

> If the repository is file-based, the server will create an Environment from application.yml (shared between all clients), and foo.yml (with foo.yml taking precedence).

**Comment by vpetit35** [comment]
Ok, I understand that hierarchical behavior on startup when configs are fetch. 
But what I do not understand why that message every 20 sec, and why just for application.yml/properties and not for the others one.
I used to think that config client was pooling for checking for variables updates, but based on my experience, it does not seems to take into account any changes in git config files.

**Comment by spencergibb** [comment]
Sounds like the config server health check.

**Comment by ryanjbaxter** [comment]
Thats exactly what I was just thinking as well.

**Comment by vpetit35** [comment]
Why does config server have an health check ? Past application startup, config server is never needed anymore no ?

**Comment by ryanjbaxter** [comment]
I believe we use it to make sure we can get configuration for the application.

The config server may be contacted again when asked to refresh configuration.

**Comment by spencergibb** [comment]
@vpetit35 see #260

**Comment by vpetit35** [comment]
I think it is a bit weird, because Spring I thought Cloud Bus was supposed to eliminate the need for client to do pooling. 
I mean, while the client does that health check, why could it not also ask if the config server received a webhook from the git server and then ask for a refresh ?

**Comment by spencergibb** [comment]
@vpetit35 commenting on a closed isn't helpful. If you think there is a bug or want to propose an enhancement open another issue. 

The config server doesn't know that a webhook was received. It keeps no state. It HAS to use the bus to tell the clients to perform a refresh.
