### ISSUE TITLE
Support a composite EnvironmentRepository

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-config#495]
Then, for example, you could have normal config data in git, with secrets in vault.

**Comment by mstine** [comment]
I would like us to prioritize this work.

**Comment by csterwa** [comment]
Some example use cases to help with guiding implementation of this story:

**Composed of multiple types of environment repos**

Composibility of multiple and varied environment repositories as backends for Config Server is the basic use case. There are situations where multiple divisions or teams manage their own environment repository but a Config Server could be serving from multiple divisions or teams repos.

```
Given Vault repo A
And Github repo B
And Github repo C
When Config Server is configured to with repos ordered [A, B, C]
Then configuration values from repos A, B and C should be available to clients
```

**Composed environment repos with ordered precedence**

We've discussed somewhat about ordered precendence of configured environment repos, let me know if this is consistent with the result of these discussions:

```
Given Github repo A
And Github repo B
When Config Server is configured to with repos ordered [A, B]
Then configuration values from repos A and B should be available to clients
And configurations from A should take precedence over configurations from B
```

**Refresh of single environment repo**

As multiple environment repos are composed together, it is important to still have the ability to refresh a single environment repo without the overhead of refreshing all of those that are configured.

```
Given Vault repo A
And Github repo B
And Config Server is configured to with repos ordered [A, B]
When refresh of repo A is requested
Then configuration values for repo A are refreshed
And configuration values for repo B are not refreshed
```

**Comment by marbon87** [comment]
If i unterstand the documentation at http://cloud.spring.io/spring-cloud-static/spring-cloud-config/1.3.0.M1/ correctly, then it is only possible to use different types of repos (git, svn, vault) together in a composed environment?

In contrast to that the examples from @csterwa describe the usage of multiple git repos. How do i configure spring-cloud-config-server to use two git-repos with a specified order? 
Background: I want to configure own repo for global properties, that are used for all clients, and one repo that contains one folder per application, each containing the app-specific properties

**Comment by ryanjbaxter** [comment]
@marbon87 

> is only possible to use different types of repos (git, svn, vault) together in a composed environment?

No you can create a composite environment from one or more of the same type of repos

> How do i configure spring-cloud-config-server to use two git-repos with a specified order?
I believe that is discussed in this [section](http://cloud.spring.io/spring-cloud-static/spring-cloud-config/1.3.0.M1/#_custom_composite_environment_repositories) .  If you have further questions please open a separate issue.
