### ISSUE TITLE
Brixton.SR5 brings in spring-cloud-config 1.1.2.RELEASE, should be 1.1.3.RELEASE

### ISSUE THREAD

**Issue by andyshinn** [spring-cloud/spring-cloud-config#496]
I am having a similar issue to #249. But that one appeared already fixed as of Brixton.RELEASE. I am currently running on Brixton.RELEASE and utilize `application.yml` (contains only defaults, no profiles set) and `app.yml` (which contains multiple profiles and a default section).

In Brixton.RELEASE the `app.yml#profile` is winning precedence. But in Brixton.SR1 (and SR5 as well) the `application.yml` properties are winning precedence. Is there a behavior or configuration change for this?

I am testing by just pulling down http://localhost:6010/app-profile.properties. The behavior changes as I switch out Brixton.RELEASE and Brixton.SR1 in my `pom.xml`. I am running with `mvn spring-boot:run` and `configserver.yml` points to my private git repository. I can try to build a public test repository if that would be helpful for debugging.

**Comment by andyshinn** [comment]
I created a git repository at https://gist.github.com/andyshinn/18796e0b6b3342a2a1ff6b51ad174917 for testing. I am specifying `spring.cloud.config.server.git.uri` as `https://gist.github.com/18796e0b6b3342a2a1ff6b51ad174917.git`. When I request any `app` profile (such as `app-test.properties`) it always gives me `security.user.password` as `default`.

**Comment by spencergibb** [comment]
Yeah, I'm having trouble reproducing. Your git repo would be most helpful. Also, `SR5` is the latest. Please try with that.

From https://github.com/spring-cloud-samples/config-repo I can hit http://localhost:8888/foo-development.properties which gives me the right value for the property `foo`.

**Comment by spencergibb** [comment]
With the latest I see the correct values. Please try with the latest.

**Comment by andyshinn** [comment]
Strange, I have the same behavior from https://github.com/spring-cloud-samples/config-repo when using Brixton.SR5 as well. When I request http://localhost:6010/foo-development.properties I get:

```
bar: spam
democonfigclient.message: hello spring io
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
foo: from-default
info.description: Spring Cloud Samples
info.url: https://github.com/spring-cloud-samples
```

I'm going through and trimming parts out of the config server app to see if I can pinpoint something.

**Comment by spencergibb** [comment]
It's then not the repo, but your project. A sample would be helpful.

**Comment by andyshinn** [comment]
I am able to reproduce it with this basic `pom.xml` (dependency tree also included): https://gist.github.com/andyshinn/3260ba5629d813fd8325416892f07acf.

Maven and Java version:

```
$ mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T10:41:47-06:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```

I am running using:
```
SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/spring-cloud-samples/config-repo.git mvn spring-boot:run
```

I then hit http://localhost:8888/foo-development.properties and observe the output is:

```
bar: spam
democonfigclient.message: hello spring io
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
foo: from-default
info.description: Spring Cloud Samples
info.url: https://github.com/spring-cloud-samples
```

I expect `foo` to be `from foo development`.

**Comment by spencergibb** [comment]
Your project has `org.springframework.cloud:spring-cloud-config-server:jar:1.1.2.RELEASE:compile`

https://github.com/spring-cloud/spring-cloud-release/blob/vBrixton.SR5/spring-cloud-dependencies/pom.xml has `<spring-cloud-config.version>1.1.3.RELEASE</spring-cloud-config.version>`.

Your problem is solved in 1.1.3.RELEASE. I don't understand why your project has 1.1.2.

/cc @dsyer

**Comment by spencergibb** [comment]
You should use `spring-cloud-dependencies` instead of `spring-cloud-starter-parent` BTW.

**Comment by spencergibb** [comment]
Adding `<version>1.1.3.RELEASE</version>` is a valid workaround.

**Comment by spencergibb** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-release/commit/2e0bf49d75d03adb2645e1b5942172391af119be. This will be available with Brixton.SR6

**Comment by andyshinn** [comment]
Great. Indeed, pinning the correct version for now is fixing it. I didn't dig enough earlier to pin the exact `spring-cloud-config` version at fault. Thank you!

**Comment by spencergibb** [comment]
Took me a while to figure it out myself.
