### ISSUE TITLE
@TestPropertySource vs spring-cloud-config

### ISSUE THREAD

**Issue by hengyunabc** [spring-cloud/spring-cloud-config#505]
This doc don not have information about spring-cloud-config...
http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html 

I know that spring-cloud-config will add itself first by default.
https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java#L155

But I thank that spring-cloud-config default order should be the same as `JNDI`.

Default spring-cloud-config order > `@TestPropertySource`, This will make people very confused.

I think `overrideSystemProperties` is not a good way.

**Comment by spencergibb** [comment]
If config server is running during an integration test, you can disable the client with `spring.cloud.config.enabled=false`.

**Comment by OldIMP** [comment]
@spencergibb We would like to also use cloud config for integration tests, but in some tests we need to override a couple of properties. Is that possible? Thx!

**Comment by spencergibb** [comment]
@OldIMP please use gitter for questions, not old closed issues. 

Set `spring.cloud.config.overrideSystemProperties=false` and then add `-Dyourprop=val`

**Comment by tobias-neubert** [comment]
If it is of any value for anybody: I have the same problem and use override properties from cloud config via an initializer like this:

```java
@SpringBootTest
@ExtendWith(SpringExtension.class)
@ContextConfiguration(initializers = {TestBase.Initializer.class})
public abstract class TestBase {
  // This is ugly but it seems that you cannot simply override spring properties
  // that were set via spring cloud config by using the usual @SpringBootTest(properties=...) or
  // @TestPropertySource(properties=...) annotation.
  static class Initializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {
    public void initialize(ConfigurableApplicationContext configurableApplicationContext) {
      TestPropertyValues.of("tobias.db.schema=db_test")
        .applyTo(configurableApplicationContext.getEnvironment());
    }
  }
}
```

**Comment by spencergibb** [comment]
IMO config should be disabled for tests.

**Comment by tobias-neubert** [comment]
For unit tests: Agreed. But for integration tests I am not so sure.
