### ISSUE TITLE
Can you use local configuration to override cloud configuration?

### ISSUE THREAD

**Issue by jashatton** [spring-cloud/spring-cloud-config#509]
I am trying to setup our development environment to allow local development configurations to override parts of the configuration that are coming from Cloud Config.  This is to avoid making changes to configuration files that are under source control. 

The location setting I am trying to use is
```
 --spring.config.location=file:./application-local.yml
```

The file sits in my working directory and I want to use it to override Cloud Configuration settings. This doesn't appear to work with Cloud configuration but it will work with an app that only uses classpath, i.e. files under the resource directory.  

Is this intentionally not possible to do or is there a better way to do this?

Thanks,

Jas

**Comment by ryanjbaxter** [comment]
I think this section in the documentation has the info you want http://cloud.spring.io/spring-cloud-static/spring-cloud.html#overriding-bootstrap-properties

**Comment by jashatton** [comment]
Not sure why I didn't think to look there.  Thanks for the reply.  

I believe I am reading this correctly that the cloud configuration server has to allow the clients to override with local settings.  Is that correct?  The client will be unable to do what I need until the remote server is set up to do so?

**Comment by ryanjbaxter** [comment]
Right that is the way I am interpreting it as well
