### ISSUE TITLE
java.util.concurrent.RejectedExecutionException after update from 1.0.4 to 1.1.3

### ISSUE THREAD

**Issue by timerons** [spring-cloud/spring-cloud-config#516]
Hi, 

we use successful spring config server 1.0.4-RELEASE with spring boot 1.2.5-RELEASE. Now i update to spring boot 1.4.1.RELEASE and config 1.2.0.RELEASE. Now get randomly RejectedExecutionException.

At the first glance, it looks like a concurrency issue in the InetUtils.

[ConfigServerLogV1.1.3_SpringBoot1.3.7.txt](https://github.com/spring-cloud/spring-cloud-config/files/497119/ConfigServerLogV1.1.3_SpringBoot1.3.7.txt)

**Comment by ryanjbaxter** [comment]
Can you provide the POM/Gradle file that reproduces the problem?

**Comment by rlynch** [comment]
Is this related to gh-132?

**Comment by rlynch** [comment]
Is this fixed in https://github.com/spring-cloud/spring-cloud-commons/issues/132

**Comment by ryanjbaxter** [comment]
Thanks @rlynch!
