### ISSUE TITLE
Plain test and binary endpoints not working

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-config#517]
This change 51c53e301 hides the concrete type of the `EnvironmentRepository` so it doesn't expose the fact that it is a `SearchPathLocator` and consequently a `ResourceRepository` is never created, and so the "raw resources" endpoints are not created either. We'll have to ask @spencergibb why he made that change because it is clearly deliberate.

**Comment by Dreampie** [comment]
raw resources  can be  refresh?

**Comment by dsyer** [comment]
Fixed in b827877 (1.1 didn't appear to be tested so that's fixed in 512e58).
