### ISSUE TITLE
how to use cloud-config with the project which is not a web project?

### ISSUE THREAD

**Issue by kaybinwong** [spring-cloud/spring-cloud-config#525]
how to use cloud-config with project which is not a web project?
any idea?

**Comment by ryanjbaxter** [comment]
Are you referring to the client or the server?  What specifically do you mean by "web project"?  Do you mean a project that depends on `spring-web`?  Why is it an issue for you?

**Comment by kaybinwong** [comment]
yeah, i run a scheduled job which not depend on spring-web, but i did not found ways to read the config from my-cloud-config-server.
i finally find the project [disconf,](https://github.com/knightliao/disconf) it may be helpful for me!

**Comment by kaybinwong** [comment]
any plan to support notify(like disconf) when config changed, instead of manual operate with refreshscope?

**Comment by ryanjbaxter** [comment]
Take a look at http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_push_notifications_and_spring_cloud_bus
