### ISSUE TITLE
Config Server text and binary file mapping lost

### ISSUE THREAD

**Issue by hubba1987** [spring-cloud/spring-cloud-config#530]
In server, in versions starting from 1.2.1 next mapping is lost:   [/{name}/{profile}/{label}/**], so /{name}/{profile}/{label}/{path}  doesn't resolve to files.

**Comment by spencergibb** [comment]
I can config the fix in 1.2.1 didn't work

**Comment by cforce** [comment]
Still can't see an update of dep to spring cloud config 1.2.2 in Brixton Release branch
Why is that not fixed in Brixton?

**Comment by ryanjbaxter** [comment]
@cforce it was fixed in Camden and Dalston.  I don't believe we have any plans to do another Brixton release.
