### ISSUE TITLE
Windows + File based paths + Monitoring(+Push)

### ISSUE THREAD

**Issue by matanshukry** [spring-cloud/spring-cloud-config#531]
So when all of the above conditions meet:
1. `FileMonitorConfiguration::poll()` is emitting local file changed. paths are made by calling `file.getAbsolutePath()`
2. `PropertyPathEndpoint::guessServiceName()` is calling `StringUtils.getFilename(path)` to get only the file name
3. `StringUtils.getFilename(path)` is assuming the path has non-windows separators ("/"), and hence return the entir epath rather than just the file name.

The result is the guessed service name is made from the path, it is incorrect, and hence the correct services aren't being notified.

IMO the simplest solution would be to clean the paths to non-windows separators when emitting, in `FileMonitoringConfiguration::poll`; But those are just my 2 cents.

Anyway, I know this is not the most urgent bug since this is a very specific case and probably not too common, but the solution isn't very difficlult as well (as far as I can tell, anyway).

**Comment by ryanjbaxter** [comment]
PRs are welcome
