### ISSUE TITLE
Enhance EnvironmentController extensibility

### ISSUE THREAD

**Issue by mlueders** [spring-cloud/spring-cloud-config#533]
First, I’d like to explain the scenaio I’m trying to solve for.  Being able to serve alternative formats (properties/json/yaml) is very useful for visualizing a particular application’s configuration (for example, printing the configuration in the jenkins logs at the end of a successful deployment).  Unfortunately, we can’t use this feature in the stock configuration server due to the limitation of ‘-‘es in the application and profile names (we have dashes in both, along with mutliple profiles per environment).  To solve this, we’ve added a couple custom endpoints with the signature of the form

```
@RequestMapping("/format/{name}/{profiles}/{label}")
public ResponseEntity<String> properties(@PathVariable String name, 
                          @PathVariable String profiles, 
                          @RequestParam(defaultValue = "true") boolean resolvePlaceholders,
                          @RequestParam(defaultValue = "false") boolean decrypt, 
                          @RequestParam(defaultValue = "properties") String format)
```

While this is obviously not an option for the stock config server being a breaking change and all, it would be very nice to be able to implement this in a more palatable way - the current solution involves injecting the standard EnvironmentController and invoking various private methods.  For example...

```
public ResponseEntity<String> getEnvironmentAsProperties(String name, String profiles, String label,boolean resolvePlaceholders, boolean decryptValues) {
        Environment environment = getEnvironment(name, profiles, label, decryptValues);
        Map<String, Object> properties = controller.convertToProperties(environment);
        String propertiesString = controller.getPropertiesString(properties);
        return createResponse(environment, propertiesString, resolvePlaceholders)
    }
```

The reason this is necessary is b/c org.springframework.cloud.config.server.environment.EnvironmentController#validateProfiles prevents methods like org.springframework.cloud.config.server.environment.EnvironmentController#labelledProperties from being invoked if the profiles or application names have ‘-‘es.

As far as I can tell, there’s no fundamental reason why this would be disallowed, other than the specific format of the EnvironmentController endpoints.  It would be really nice if the code in EnvironmentController could be used for the case described here.  The easiest way to do this would be to have a flag on EnvironmentController (defaulting to false) which can be programmatically set.  A better way would be to extract the primary functionality of EnvironmentController into a separate class which can then be injected and invoked as needed.

If someone can provide guidance as to whether a change like this would be accepted, I’d be happy to raise a PR.

**Comment by spencergibb** [comment]
So in my test `http://localhost:8888/foo-development-a.properties` with `	@RequestMapping("/{name}-{profiles}.properties")` selects name as `foo-development` and profiles as `a` so the validation doesn't really matter. The options are to add mappings like you suggest rather or make the controller more extensible. The controller wasn't meant to be an API class so I would err on adding mappings.

**Comment by Blackbaud-MikeLueders** [comment]
@spencergibb You're right, it did in previous versions of the library where i was getting exceptions - I just tried it with the latest and I am not getting exceptions, I'm just getting incorrect behavior.  

Here is an example app name + profile we would need to match against. 

app name: auth-losaml
profiles: cloud,long-dev,pivotal-dev.dev-apps,dev-apps

The url with the current strategy would look like `curl some-host://auth-losaml-cloud,long-dev,long-dev.dev-apps,dev-apps.yaml`  It's not clear to me what the mappings would look like in order to ensure no breakage to existing clients - if you're not worried about breaking existing clients, that opens up possibilities.  I'm open to suggestions here.

Also, while I realize the controller wasn't meant to be an API class, the functionality could easily be extracted to something the controller (and others) could use.

**Comment by marcingrzejszczak** [comment]
Is it still a problem with Finchley.RELEASE?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
