### ISSUE TITLE
Serving plain text from classpath.

### ISSUE THREAD

**Issue by cmitchell** [spring-cloud/spring-cloud-config#544]
I am trying to serve plain text resources for non-spring applications, and I can't figure out what the {application-name} part of the url would be.  I have the following in my configserver application.yml
```
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/
          failFast: true
server:
  port: 8888
```

And in my bootstrap.yml
```
ring:
  application:
    name: configserver
  profiles:
    active: native
```

Under the src/main/resources/config directory I have
```
ls configserver/src/main/resources/config/
go-services  search-test.txt  search.yml  test.json
```

Now, there is a spring application called search, and it is able to find search.yml just fine. I can also get search.yml just fine via curl.
```
curl -v http://localhost:8888/search/default/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET /search/default/ HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 
< X-Application-Context: configserver:native:8888
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Thu, 03 Nov 2016 19:40:22 GMT
< 
* Connection #0 to host localhost left intact
{"name":"search","profiles":["default"],"label":null,"version":null,"state":null,"propertySources":[{"name":"classpath:config/search.yml","source":{"info.build.version":"0.0.1-SNAPSHOT","server.port":6500,"eureka.instance.hostname":"search","eureka.instance.preferIpAddress":true,"eureka.client.serviceUrl.defaultZone":"http://discovery:8761/eureka/"}}]}
```

My problem is when I try to get ANY other file via the curl interface.  I have consulted the docs, as well as other bugs here, but none seemed to address how to determine the applicaiton name - at least, that's what i hope I'm doing wrong.  However, I can't even pull the search.yml file back as plain text.  Doing this
```
curl -v http://localhost:8888/search/default/master/search.yml
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET /search/default/master/search.yml HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 404 
< X-Application-Context: configserver:native:8888
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Thu, 03 Nov 2016 19:42:06 GMT
< 
* Connection #0 to host localhost left intact
{"timestamp":1478202126792,"status":404,"error":"Not Found","message":"No message available","path":"/search/default/master/search.yml"
```

 I get the same response for 
ttp://localhost:8888/search/default/master/config/search.yml

I have tried making a separate folder (go-services in my case) and using that as the application name, but no luck.  Is there a concept of a default path?  Or even just a way to list all resources?  I've hit the /info, /health, and /env endoints, but they aren't helpful.

**Comment by ryanjbaxter** [comment]
What version of Spring Cloud are you using?  Have you seen #530?

**Comment by cmitchell** [comment]
I am using 
BOM_VERSION=Camden.RELEASE
CLOUD_DEPENDENCIES_VERSION=1.0.1.RELEASE


I had not seen #530 - I will look at it now.

**Comment by ryanjbaxter** [comment]
Looks to be the same issue, try the camden snapshot releases to see if it fixes the problem

**Comment by cmitchell** [comment]
That doesn't seem to have made a difference.  I changed the version to 
BOM_VERSION=Camden.SR2

I saw
Download https://jcenter.bintray.com/org/springframework/cloud/spring-cloud-config-server/1.2.1.RELEASE/spring-cloud-config-server-1.2.1.RELEASE.pom
Download https://jcenter.bintray.com/org/springframework/cloud/spring-cloud-config/1.2.1.RELEASE/spring-cloud-config-1.2.1.RELEASE.pom

But I still see the same behavior.

**Comment by spencergibb** [comment]
he did say to try `Camden.BUILD-SNAPSHOT`.

**Comment by cmitchell** [comment]
Sorry - I missed that. That version works. Thanks! Any idea when it will make it to a more stable (non build) version?

Using Camden.BUILD-SNAPSHOT, I got (among other things)
Download http://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-config-server/1.2.2.BUILD-SNAPSHOT/spring-cloud-config-server-1.2.2.BUILD-20161103.180231-135.pom

And it does work now.

**Comment by ryanjbaxter** [comment]
Probably in Camden.SR3

**Comment by cmitchell** [comment]
Thanks!
