### ISSUE TITLE
Serving plain text files broken after 1.1.2 => 1.2.1 migration

### ISSUE THREAD

**Issue by horalstvo** [spring-cloud/spring-cloud-config#546]
I use Spring Cloud Config Server to serve as well logback.xml and certificate binary files. I can serve these fine with 1.1.2 version. I upgraded to 1.2.1 and now the previously working call returns:

```
HTTP/1.1 404 
Content-Type: application/json;charset=UTF-8
Date: Tue, 08 Nov 2016 09:42:19 GMT
Transfer-Encoding: chunked
X-Application-Context: application:8888

{
    "error": "Not Found", 
    "message": "No message available", 
    "path": "/app/dev/label/app.properties", 
    "status": 404, 
    "timestamp": 1478598139782
}
```

The failing call looks like `http localhost:8888/app/profile/master/app-logback.xml`.

If I look at the call for properties file - `http localhost:8888/app/profile/master/app.properties` then that call also gives me the error above but calling `http localhost:8888/app/profile/master` will return the properties as a property source.

Since I need to serve plain text files this bug is a showstopper for me and I cannot upgrade.

Also I missed release notes which would tell me what is new in 1.2 but maybe I did not look thoroughly enough.

**Comment by ryanjbaxter** [comment]
Sounds similar to #530.  Can you try the latest SNAPSHOT release?

**Comment by ryanjbaxter** [comment]
Please re-open if that was not the issue.

**Comment by cforce** [comment]
This is still not fixed in Brixton Release Train is it?

**Comment by ryanjbaxter** [comment]
@cforce please don't comment on related issues like that
