### ISSUE TITLE
Settings to disable ConfigServer HealthIndicator failed.

### ISSUE THREAD

**Issue by heymysweetheart** [spring-cloud/spring-cloud-config#552]
Hi spring cloud team,

When I enable spring.cloud.config.server.health.enabled, the /health will always return "DOWN"([Same Issue](https://github.com/spring-cloud/spring-cloud-config/issues/182)), So I want to disable the ConfigServer HealthIndicatior by setting the `spring.cloud.config.server.health.enabled=false`. But it turned out to be no use and the application still check the status of ConfigServer. 
I am using eureka, config server with git backend. Spring boot 1.4.1, spring-cloud-starter-config:1.1.3.RELEASE.

Regards,
Yuliang

**Comment by spencergibb** [comment]
those config values are for config server, not for config client. You should use `health.config.enabled=false`

**Comment by heymysweetheart** [comment]
With configuration `health.config.enabled=false`, it really worked. Thanks. 
In spring boot, to turn off one of the default HealthIndicator, like db, hystrix, the settings is like: 
```
management:
  health:
    db:
      enabled: false
    refresh:
      enabled: false
```.

So could you please to modify this config `health.config.enabled` to the way like setting the default HealthIndicator? I think that would be better. @spencergibb

**Comment by maxxyme** [comment]
Despite setting `health.config.enabled=false` in my `application.properties`, `org.springframework.cloud.health.RefreshScopeHealthIndicator` was still getting called...

Alas, I finally discovered in spring-cloud-context-2.1.3.RELEASE.jar the existence of these 2 files:

spring-configuration-metadata.json

    {
      "name": "management.health.refresh.enabled",
      "type": "java.lang.Boolean",
      "description": "Enable the health endpoint for the refresh scope.",
      "defaultValue": true
    },

additional-spring-configuration-metadata.json

		{
			"name": "management.health.refresh.enabled",
			"type": "java.lang.Boolean",
			"description": "Enable the health endpoint for the refresh scope.",
			"defaultValue": true
		}

So basically the prop name we can see everywhere is erroneous, it's actually **`management.health.refresh.enabled`** NOT `health.config.enabled`.

e.g. official doc @ https://cloud.spring.io/spring-cloud-config/reference/html/#_health_indicator_2

Also found an answer from 2017 telling the correct properties: https://stackoverflow.com/a/46775306
So probably this has been "fixed" by the time...
