### ISSUE TITLE
Are there plans for adopting Eureka 2 into Spring Cloud?

### ISSUE THREAD

**Issue by russBDigitalGlobe** [spring-cloud/spring-cloud-config#553]
We are currently evaluating Eureka 2 as a replacement for our current Eureka implementation and was wondering if there are any plans to have this folded into Spring Cloud if it goes GA?

Thanks in advance,

Russ Baker

**Comment by spencergibb** [comment]
There are no plans for eureka 2 at netflix. We'll evaluate if there are any changes on their side.

**Comment by Tires** [comment]
Can somebody describe in short term what is the goal to adopting Eureka 2?

**Comment by spencergibb** [comment]
There is no eureka 2, therefore no plans

**Comment by Tires** [comment]
What is with artifact com.netflix.eureka2:* and https://github.com/Netflix/eureka/wiki/Eureka-2.0-Architecture-Overview? Sorry when I don't understand your question about "No Eureka 2". I read about about the concept of read cluster and write cluster and even saw the code

**Comment by spencergibb** [comment]
They abandoned it

**Comment by Tires** [comment]
Netflix at all? Crazy, why?

**Comment by spencergibb** [comment]
You'll have to ask them

**Comment by Tires** [comment]
I will. So we stay with version 1 in Spring
