### ISSUE TITLE
Merge configuration from multiple EnvironmentRepository 

### ISSUE THREAD

**Issue by shalom938** [spring-cloud/spring-cloud-config#555]
We are still in the process of evaluating spring cloud config and we wonder if its possible to merge configuration from two or more EnvironmentRepository.
for example we want most of the configuration to come from a git repo and the secrets from vault. is that possible in anyway? will spring cloud config support that in the future?

**Comment by dsyer** [comment]
Probably duplicates #495 and #286?

**Comment by shalom938** [comment]
Yes, duplicate of https://github.com/spring-cloud/spring-cloud-config/issues/495
