### ISSUE TITLE
ResourceController pulling twice from the git repo

### ISSUE THREAD

**Issue by dallanmc** [spring-cloud/spring-cloud-config#557]
We exclusively use spring cloud config for serving plain text files via the resource controller. 
I was debugging into the cloud server code and notice that for every single call to the `resolve` endpoint (`@RequestMapping("/{name}/{profile}/{label}/**")`) two calls are made to the JGitEnvironmentRepository class resulting in two calls to pull the repo. Ours is a remote repo (and quite slow at that), so this mechanism seems to double the amount of time it takes to serve a single resource file. 
The code that seems to be doing the calls is this in the `ResourceController`:
```
prepareEnvironment(this.environmentRepository.findOne(name, profile, label));//RESULTS IN A GIT PULL

// ensure InputStream will be closed to prevent file locks on Windows
try (InputStream is = this.resourceRepository.findOne(name, profile, label, path) {...  //RESULTS IN A GIT PULL
```

Each call above to `findOne`, ends up calling the JGitEnvironmentRepository (and invoking git pull). Is there a good reason for this or could it be optimised? Am I doing something wrong?

**Comment by dallanmc** [comment]
Can anyone else confirm this behaviour?

**Comment by ryanjbaxter** [comment]
I haven't confirmed it, but can you tell us what version you are using?

**Comment by dallanmc** [comment]
1.2.2

**Comment by ryanjbaxter** [comment]
@dallanmc I wonder if #566 would help address this concern.  If so maybe we can close this as a duplicate?
