### ISSUE TITLE
Can't change bootstrap properties location

### ISSUE THREAD

**Issue by crusi** [spring-cloud/spring-cloud-config#56]
I can't change the location of the bootstrap.properties file during startup with --spring.cloud.bootstrap.location=...

It looks like a copy/past error in line 95 of [BootstrapApplicationListener](https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-client/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java#L95)?

**Comment by dsyer** [comment]
Why did you think that was a copy/paste error? What did you do exactly and what did you observe? (I believe there are tests for changing the bootstrap location that work just fine.)

**Comment by crusi** [comment]
Hi,

we want to change the location of the config server by defining a bootstrap.yml/properties on certain environments. There was no test until now. I addd one in the pull-request with an external bootstrap.properties

Let's assume i have a spring boot application configured with spring cloud config client here:

*/opt/portal/portal.jar*

which has in the classpath a bootstrap.yml like this:

```
....
spring:
  cloud:
    config:
      uri: http://localhost:8686/config
....
```

And i have a bootstrap.properties under */etc/conf/portal* with 

```

spring.cloud.config.uri=http://localhost:1234/config
```
When i change to the directory /opt/ and start from there 

```
java -jar portal/portal.jar --spring.cloud.bootstrap.location=/etc/conf/portal/bootstrap.properties 
```
it will not be used. I still get the properties from the bootstrap.properties included into the jar.

I fixed line 95 from
```
		if (StringUtils.hasText(configLocation)) {
			bootstrapMap.put("spring.config.location", configName);
		}
```
to 
```
		if (StringUtils.hasText(configLocation)) {
			bootstrapMap.put("spring.config.location", configLocation);
		}
```

Hope this clarifies the problem a little bit.

Cheers
Stefan
