### ISSUE TITLE
Register with Eureka and Trust invalid Cert

### ISSUE THREAD

**Issue by 1123** [spring-cloud/spring-cloud-config#560]
Not sure if this is the right place to ask this question. Feel free to redirect me to a different place.

We have a config service deployed in Cloud Foundry and would like to register with Eureka, which is only reachable via https. Unfortunately the certificate shown by Eureka is issued for the wrong domain. Thus registration fails. Until this is fixed, we would like to trust the certificate even though its wrong. 

Importing the certificate won't help, since it is still issued for the wrong domain. 

Is there some spring boot property I could set -- like trust all certificates, or disable certificate checking?

Thanks.

**Comment by spencergibb** [comment]
It's a function of the client. You'd need to configure a `RestTemplate` and the underlying http client. See https://github.com/spring-cloud/spring-cloud-config/blob/master/docs/src/main/asciidoc/spring-cloud-config.adoc#providing-a-custom-resttemplate
