### ISSUE TITLE
Encrypt/Decrypt Endpoints not working for Symmetric Key

### ISSUE THREAD

**Issue by kmb385** [spring-cloud/spring-cloud-config#561]
I have setup a simple project using Spring Cloud Config Server and I'm trying to simply encrypt and decrypt some values. I create the project as a Spring Starter Project using the following pom.xml with Spring Boot.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.oreilly.cloud</groupId>
    <artifactId>spring-microservices-config-server6</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>spring-microservices-config-server6</name>
    <description>Demo project for Spring Boot</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.4.2.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-server</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Camden.SR2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
```
From there I modify the main Spring Boot Application class to add the @EnableConfigServer annotation as follows:

```
@SpringBootApplication
@EnableConfigServer
public class SpringMicroservicesConfigServer6Application {

    public static void main(String[] args) {
        SpringApplication.run(SpringMicroservicesConfigServer6Application.class, args);
    }
}
```

Within my application.properties file, I point to a git repository, setup the server port and enable symmetric key encryption using encrypt.key as follows:
```

server.port=8888
spring.cloud.config.server.git.uri=C:/Users/training/Desktop/sts-workspace/configuration
encrypt.key=secret
```

Next I open a bash shell and encrypt some data:

`$ curl http://localhost:8888/encrypt -d Kevin`

Which produces the value:

`315ca5592635e4f65e0a0278cd08f74b5cef27e8379bd0e0d81d08c9ed8fbac161d`

If I attempt to decrypt the value using:

`curl localhost:8888/decrypt --data-urlencode 315ca5592635e4f65e0a0278cd08f74b5cef27e8379bd0e0d81d08c9ed8fbac161d`

I receive the following error:

`276{"description":"Text not encrypted with this key","status":"INVALID"}`

I do not understand why this simple example does not work.  I have confirmed my JCE extension is in place using some simple code to test the .jar files are in place.  Is this an issue or am I missing something?

**Comment by spencergibb** [comment]
I'm unable to replicate with the provided files. Can you share your project?

**Comment by kmb385** [comment]
Sure, want me to push it to a repo?

**Comment by spencergibb** [comment]
sure, whereever you want to share it.

**Comment by kmb385** [comment]
Here is the repo:  https://github.com/kmb385/spring-cloud-server-encryption  .  I appreciate the help so much, I've been debugging this for 3 days.  Focusing a lot on the EncryptionController and EnvironmentPrefixHelper, it doesn't seem to be parsing out the input as I would expect.

**Comment by spencergibb** [comment]
Even your project works fine for me, maybe your JCE installation isn't right?

**Comment by kmb385** [comment]
Attempting to reinstall using: http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Comment by kmb385** [comment]
Still no luck, I installed JCE in both a JRE and JDK.  Testing JCE now with: http://stackoverflow.com/questions/11538746/check-for-jce-unlimited-strength-jurisdiction-policy-files

**Comment by kmb385** [comment]
Test confirms JCE is in place, console output reads:  2147483647

**Comment by spencergibb** [comment]
Unfortunately, I don't know what else to do to help you.

**Comment by kmb385** [comment]
OMG.... If I tell you what I did wrong, promise you won't shame me?

**Comment by kmb385** [comment]
![console](https://cloud.githubusercontent.com/assets/1264457/20578982/13ec58ac-b198-11e6-9db0-b7d7e5a2a394.png)

I was including the current speed in the enrypted value I provided for decrypt.  The output was adjacent to each other with no spaces between them.

**Comment by kmb385** [comment]
Thank you for your help.  Sorry for taking up your time, but your efforts were very appreciated.

**Comment by spencergibb** [comment]
I won't shame you, happens all the time. How about a good LOL 😆 and we call it good.

**Comment by repos-jmp** [comment]
I spent 20 minutes on this issue too. Redirecting the output to a file helped me get the correct value. 
May be add this as a tip in the documentation to help future newcomers ?

**Comment by ryanjbaxter** [comment]
@repos-jmp want to submit a PR?

**Comment by repos-jmp** [comment]
Apologies if I sounded rude. Have submitted the PR.
