### ISSUE TITLE
Updating a key using Config Server in non JVM environment

### ISSUE THREAD

**Issue by janakiraman-ramani** [spring-cloud/spring-cloud-config#562]
We are generating API keys through a service and want to store the details in config server. The underlying data store may be either Vault or git hub. The API keys can be retrieved at a later stage.

How to dynamically save and update the configuration details to github/ vault in Config Server in non JVM environment through nodeJS? I didn't see any API endpoint to do the same. In other words, does Config Server provide an option to update the details dynamically during runtime.

**Comment by spencergibb** [comment]
Config server is read-only by design. You would need to handle any updates on your own.
