### ISSUE TITLE
Configurable PropertySource priority (for property sources from config server)

### ISSUE THREAD

**Issue by warmuuh** [spring-cloud/spring-cloud-config#57]
I was wondering, if there is a possibility to configure the priority of the added "bootstrap"-proprtySource on client side. currently, it has highest priority, even higher than system-environment or startup-parameters. I would have thought that it should be after jvm parameters, just like normal application.properties. I actually reorder this propertySource via applicationInitializer. Is there a way to make this more easily configurable or even default?

**Comment by dsyer** [comment]
I don't think that's a great default. the point of a centralized config server is that it is the authoritative source of external properties. What is the use case exactly where you need to re-order?

**Comment by warmuuh** [comment]
i grasped cloud-config as a way to externalize and centralize all configuration normally done via application-xx.properties. that means, it will act as a replacement. looking at [spring-boot reference](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-external-config), the system-properties have higher priority. honestly, i am used to the "override-by-jvm-parameters" behavior in all java applications.

we actually use this to have e.g. 5 instances of a service and on one or two servers, the instances are slightly different configured (using system-properties), so we wanted to use spring-cloud to configure all services and use system-properties to "specialize" the instances (instances should do the same, i know, but it is like it is...). 

i actually cannot see a usecase where you want the "pre-defined" properties from config-server override the system-properties, but maybe its because of our use of them... anyhow, it would be great to make this configurable

**Comment by dsyer** [comment]
I guess it depends on how much of a control freak you are. One of the points of a central config server might be to disallow local overrides of some properties, which explains the current implementation. But making it configurable seems sensible. Maybe even per application via its own external properties.
