### ISSUE TITLE
When MultipleJGitEnvironmentRepository.cloneOnStart==true initClonedRepository is called twice

### ISSUE THREAD

**Issue by shalom938** [spring-cloud/spring-cloud-config#570]
The method JGitEnvironmentRepository#initClonedRepository is called twice if cloneOnStart is true. i understand its not such a big issue but if the repository gets bigger it might be..

**Comment by spencergibb** [comment]
Duplicates #557?

**Comment by shalom938** [comment]
Its not exactly a duplicate, i don't see the issue described in #557 , my issue is only on startup.

**Comment by spencergibb** [comment]
ok, thanks

**Comment by marcingrzejszczak** [comment]
Is it still a problem with Finchley.RELEASE?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
