### ISSUE TITLE
Can local config override remote props when running embedded?

### ISSUE THREAD

**Issue by Sangdol** [spring-cloud/spring-cloud-config#573]
Can we make local configuration override remote properties when running embedded server?

I know it's possible when running a Config server and a Config client separately. If I set `spring.cloud.config.allowOverride=true` on the server and set `spring.cloud.config.overrideNone=true` on the client, the local configuration overrides the remote. 

Some related links regarding this
* http://cloud.spring.io/spring-cloud-static/spring-cloud.html#overriding-bootstrap-properties
* https://github.com/spring-cloud/spring-cloud-config/issues/509

Is it possible when [running embedded server](http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_embedding_the_config_server) with `spring.cloud.config.server.bootstrap=true`? I've tried set the properties in the project like below but it didn't work.

```
spring:
  profiles: default
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      server:
        bootstrap: true
        git:
          uri: file://${user.home}/config
```

**Comment by Sangdol** [comment]
I am sorry I misunderstood. The properties should be in the remote source and it's working fine.

**Comment by Jeckyli** [comment]
@Sangdol Can you clarify which properties should be in the remote source? My understanding is your original message is correct, that 

`spring.cloud.config.allowOverride=true` in config server
`spring.cloud.config.overrideNone=true` in config client

and any local property in client can override remote source from server. But seems that this doesn't work for me.

**Comment by Sangdol** [comment]
@Jeckyli no, I was wrong and you are making the same mistake as I was.

The both properties (`allowOverride`, `overrideNone`) should reside in server config. `overrideNone=true` makes the server not override clients' properties with the server's properties.

It had been quite confusing for me, and was still not easy to remind correctly; I had to check the note that I've made before.

**Comment by Jeckyli** [comment]
Thanks @Sangdol for confirming. Now I'm clear that both should reside on config server side, and if I understand correctly, `spring.cloud.config.allow-override=true` allows system properties from client side to override config server values right?

The problem I'm facing now is I'm trying to have a local prop on config client side to override the same prop from config server, let's say

config server:
```
key=valueA
```

In which file (like bootstrap.properties, application.properties or else) should I put on client side 

```
key=valueB
```

so that client will use valueB for this key?

**Comment by Sangdol** [comment]
@Jeckyli 

> Thanks @Sangdol for confirming. Now I'm clear that both should reside on config server side, and if I understand correctly, spring.cloud.config.allow-override=true allows system properties from client side to override config server values right?

Right.

> so that client will use valueB for this key?

Correct.

**Comment by Jeckyli** [comment]
@Sangdol Thanks, but you've probably misunderstood the last question. I'm wondering where should I put the overriding property on client side. How do you provide the local properties that override default remote ones?

**Comment by Sangdol** [comment]
@Jeckyli Sorry, I didn't read your question carefully. Actually it doesn't matter, so it'd be good for you to just put it in `application.properties`. 

Refer to this http://stackoverflow.com/questions/32997352/what-is-the-diference-between-putting-a-property-on-application-yml-or-bootstrap to check the difference between the two files.

**Comment by Cs4r** [comment]
This ticket saved my day.

Thank you guys

**Comment by Sangdol** [comment]
I am very happy that it helped you. Thanks for the comment.

**Comment by Subhashre** [comment]
I am using remote repo as file based system. So where i can place the below property to override the remote property by client property.
 spring:
     cloud:
         config:
                allowOverride: true
                overrideNone: false
                overrideSystemProperties: false

I tried placing the above properties in config-server as well but it didnt work for me.
Please Help.

**Comment by Subhashre** [comment]
The solution is not working for me.

Could you please explain which properties will be placed where.
I mean config-server or client.

**Comment by miqi770** [comment]
I have the same question that: How can I specify a  property on client side which it can not be overrided  by config server side ?

**Comment by Cs4r** [comment]
I don't think that's possible @miqi770.  AFAIK, there is no such a level of granularity. 

`spring.cloud.config.allow-override=true` allows **_ALL_** application properties defined in the server side be overriden by client-side system properties.

If you want to avoid that a client side property is overriden by a server side one, just use different names in each side (e.g: by using prefixes).

**Comment by gcaracuel** [comment]
Solved by comments on: https://github.com/spring-cloud/spring-cloud-config/issues/907 
```
spring:
  cloud:
    config:
      allow-override: true
      override-none: true
```
Must be added to all desired files at my git repository.

**Comment by eago** [comment]
@gcaracuel 
hello, what do you mean by all desired files? all those application-{profile}.yml files ?

**Comment by gcaracuel** [comment]
Exactly + application.yml too if you also need to override values here. I.E.:

At application.yml:
keyA=value1

At application-profile.yml
keyA=value2

And finally at your local application configuration:
keyA=value3

You will need to allow overrides to both 'remote' files if you need keyA to be value3.
