### ISSUE TITLE
config server - multiple git repository lookup

### ISSUE THREAD

**Issue by srialapati** [spring-cloud/spring-cloud-config#574]
Hi,
I read a lot of posts regarding this but never really got the impression that the config server can read from multiple git repositories effectively. Could someone clarify this for me and may be provide an update on when that functionality will be available?

Here's my use case:
Need to read from repo1 for non-secure properties for different profiles
Need to read from repo2 for secure properties that not every user can have access to. Usually passwords etc. 
Need to club property sources from both repos and return. 

Here's my bootstrap.yml for the config server.
spring:
  profiles:
    active: dev, qa, prod
  cloud:
    config:
      label: master
      server:
        git:
          uri: git_url/environment-configuration-repo.git
          repos:
            secure: 
              pattern: secure*
              uri: git_url/secure-environment-configuration-repo.git
          searchPaths: '{profile}/{application}'
server:
  port: 8888

http://localhost:8888/myapp/dev/master only reads the properties from git_url/environment-configuration-repo.git but not from git_url/secure-environment-configuration-repo.git

The folder structure is same for both repos so that the search path matches. It's just that the secure repo is not being read.

Appreciate your help if you can suggest how I can read the properties from second repo simultaneously.

Thanks.

**Comment by spencergibb** [comment]
It doesn't support reading from more than one repo at a time.

**Comment by spencergibb** [comment]
Duplicates #383

**Comment by srialapati** [comment]
Thanks @spencergibb for the update. Do you know if there's any plan to add that feature?

**Comment by spencergibb** [comment]
Not currently

**Comment by shakuzen** [comment]
@srialapati Note that for your use case: you can use the encryption features of the config server to handle secure properties in the same repository as unsecure properties without compromising the unencrypted value.
http://cloud.spring.io/spring-cloud-static/spring-cloud-config/1.2.2.RELEASE/#_encryption_and_decryption

**Comment by srialapati** [comment]
Thanks @shakuzen. We are exploring this option as well.
