### ISSUE TITLE
add an spring cloud config monitor test for integration with gitblit 

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-config#575]
http://gitblit.com/setup_hooks.html desvribes hotw it may work. An example as test would be great.

**Comment by spencergibb** [comment]
I've never heard of gitblit before. You can add your own custom code. Follow the examples [here](https://github.com/spring-cloud/spring-cloud-config/tree/master/spring-cloud-config-monitor/src/main/java/org/springframework/cloud/config/monitor) for bitbucket, github and gitlab.
