### ISSUE TITLE
@RefreshScope on  a class that uses TaskScheduler

### ISSUE THREAD

**Issue by ezraroi** [spring-cloud/spring-cloud-config#577]
I have a class that all it is doing is to register a task on the TaskScheduler. This task is using some confiugration and also the interval of the task is based on configuration. I try to use the  @RefreshScope here but the problem is no one really is calling any method if this class... so it is being destroyed when i call /refresh but never gets created again.

Any solution or a way to solve such case?

Thanks

**Comment by spencergibb** [comment]
Put the refresh scope on a different class and consume that in the schedule one?

**Comment by ezraroi** [comment]
Tried this.. still the class with the TaskScheduler will not be created again as no real class using it..

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
