### ISSUE TITLE
No qualifying bean of type 'org.springframework.cloud.config.server.environment.JGitEnvironmentRepository' available

### ISSUE THREAD

**Issue by magaton** [spring-cloud/spring-cloud-config#580]
Hello,
we are constantly hit by the problem which I think is related to https://github.com/spring-projects/spring-boot/issues/4619

There it turned out to be the problem with spring-integration, not with the spring-boot itself.
I am wondering whether there is a problem with spring cloud config server in the similar manner.

Symptoms:
We have a spring boot app that acts as the spring cloud config server and we build it with spring maven plugin (create an executable). Depending on the FS path where the war file is originally produced (CI, local) we have a different behaviour. Sometimes the app cannot be started due to 
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gitPersistingGenericResourceRepository' defined in URL [jar:file:/data/registry.war!/WEB-INF/classes!/com/acme/registry/GitPersistingGenericResourceRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.config.server.environment.JGitEnvironmentRepository'
```

and GitPersistingGenericResourceRepository is

```
import org.springframework.cloud.config.server.environment.JGitEnvironmentRepository;
@Component
public class GitPersistingGenericResourceRepository extends PersistingGenericResourceRepository {
	@Autowired
	public GitPersistingGenericResourceRepository(
			JGitEnvironmentRepository jGitEnvironmentRepository) {
		super(jGitEnvironmentRepository);
		this.jGitEnvironmentRepository = jGitEnvironmentRepository;
	}
```
and PersistingGenericResourceRepository is:
```
import org.springframework.cloud.config.server.environment.SearchPathLocator;
import org.springframework.cloud.config.server.resource.GenericResourceRepository;
public abstract class PersistingGenericResourceRepository extends GenericResourceRepository {
    public PersistingGenericResourceRepository(SearchPathLocator service) {
        super(service);
    }
```

According to our observations, shorter paths work, the longer don't.
The issue is seen to happen with Brixton.RELEASE, Brixton SR5, Camden.RELEASE with Spring Boot 1.3.7 and 1.4.2. It doesn't make any difference if executable is true or false in spring-boot-maven plugin configuration.

I was inspecting logs in both cases and compared them line by line:
in both logs EnvironmentRepositoryConfiguration is properly matched:

```
org.springframework.cloud.config.server.config.EnvironmentRepositoryConfiguration$GitRepositoryConfiguration matched due to @ConditionalOnMissingBean (types: org.springframework.cloud.config.server.environment.EnvironmentRepository
```

but it is created by DefaultListableBeanFactory only in one case:
 ```
[main] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Finished creating instance of bean org.springframework.cloud.config.server.config.EnvironmentRepositoryConfiguration$GitRepositoryConfiguration
```

in the other one, there is no such log message and app blows when our class tries to autowire @Bean from EnvironmentRepositoryConfiguration and that bean is not in context.

Now the question is why EnvironmentRepositoryConfiguration is created in one case and not in the other, or in other words: why our class which has spring cloud server bean as dependency in @Autowired annotation constructor is initialised before spring cloud config bean in one case and not in the other?

The things I also tried, but without success: 
- explicit @ComponentScan for org.springframework.cloud.config.server
- @DependsOn next to @Component annotation of our bean that has JGitEnvironmentRepository as dependency.

Thanks

**Comment by spencergibb** [comment]
Can you create a sample project that reproduces the problem?
