### ISSUE TITLE
Support for SSH private keys outside ~/.ssh

### ISSUE THREAD

**Issue by dvtoever** [spring-cloud/spring-cloud-config#589]
At our company we deploy springboot applications in a cloud environment that all run as the 'springboot' user. Multiple applications run on the same machine, hence sharing the home dir of the springboot user (and its ~/.ssh).

The concern of the spring-cloud-config service (and only this application) is to connect via SSH to an external git repository. Therefore it makes sense to package the private key information just with the spring-cloud-config application and programmatically setup the git connection. 

However I see no possibility to extend/configure JGitEnvironmentRepository to use SSH authentication. The only option would be to make an entire custom EnvironmentRepository.

At the moment I clone the repository myself using JGit right before spring-cloud-config starts and then I point the git repo to the local repository I just cloned myself.

Is there a better way to solve this issue? Or could the JGitEnvironmentRepository be made more flexible to I can tell it where it should look for a private key?

**Comment by spencergibb** [comment]
Our use of jgit would need to be changed to support ssh locations outside of the standard.

**Comment by spencergibb** [comment]
Related #101

**Comment by sunnyWangXin** [comment]
Hi, will spring cloud config support multiple ssh location for different git repo? @spencergibb

**Comment by spencergibb** [comment]
@sunnyWangXin watch this issue.

**Comment by mbdebian** [comment]
I'm facing the same problem, I would like to specify a deploy key, instead of it using my default key, which, in addition, is encrypted, thus it doesn't work.

**Comment by ojhughes** [comment]
See https://github.com/spring-cloud/spring-cloud-config/pull/741

**Comment by ryanjbaxter** [comment]
Can we close this not that #741 is merged?

**Comment by dvtoever** [comment]
Yes

Verstuurd vanaf mijn iPhone
