### ISSUE TITLE
Config Server changing address on AWS

### ISSUE THREAD

**Issue by paolo-rendano** [spring-cloud/spring-cloud-config#590]
Hi,
I noticed a problem on my AWS (Elastic beanstalk) hosted microservice solution.

I'm using eureka (1.4.2) + 2 nodes config server (1.2.1) along with multiple spring boot apps that get the address of cloud config server at bootstrap phase via eureka lookup in order to retrieve configurations.

The issue is that once the EB that hosts config server changes the address (maybe an autoscale, a termination or a redeploy) after a while the spring boot apps are still using the old address of cloud config server and I get:

```
23:29:19.850 [DiscoveryClient-CacheRefreshExecutor-0] WARN  o.s.c.c.c.DiscoveryClientConfigServiceBootstrapConfiguration - No instances found of configserver (xxxx)
```

this make the spring boot app stop refreshing properties and could potentially also bring down the health of the app. 

Example of a log while it regularly works and finds the config server:

```
23:30:48.128 [qtp911501858-33] INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at: http://ip-10-0-0-149.eu-west-1.compute.internal:80/
```

I've also tried to set spring.cloud.config.failFast=true but not solved the problem even if in this case I get (I think this is using the retrier):

```
00:02:58.210 [qtp464649704-34] INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at: http://ip-10-0-0-149.eu-west-1.compute.internal:80/
00:02:58.555 [AsyncResolver-bootstrap-executor-0] INFO  c.n.d.s.r.a.ConfigClusterResolver - Resolving eureka endpoints via DNS
00:02:59.253 [qtp464649704-34] INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at: http://ip-10-0-0-149.eu-west-1.compute.internal:80/
00:03:00.395 [qtp464649704-34] INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at: http://ip-10-0-0-149.eu-west-1.compute.internal:80/
00:03:01.638 [qtp464649704-34] INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at: http://ip-10-0-0-149.eu-west-1.compute.internal:80/
00:03:03.018 [qtp464649704-34] INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at: http://ip-10-0-0-149.eu-west-1.compute.internal:80/
00:03:04.521 [qtp464649704-34] INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at: http://ip-10-0-0-149.eu-west-1.compute.internal:80/

```

Any idea? I would expect my spring boot app to move to the second config server looking up it into eureka (they are both registered there), or in the case I have only one node that changes its address, to retrieve the updated address registered in eureka.

Thanks
Paolo

**Comment by paolo-rendano** [comment]
UPDATE:
I reproduced it locally without AWS. The problem seems related to the health endpoint. The log
23:30:48.128 [qtp911501858-33] INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at: http://ip-10-0-0-149.eu-west-1.compute.internal:80/

happens when I call the health endpoint of the spring application. In the case I set failFast=true, then the health endpoint return DOWN. If not set, it returns UP.

Debugging it I see that the code line:
ConfigClientProperties properties = this.defaultProperties.override(environment);
in the class ConfigServicePropertySourceLocator 

returns in properties the address of the cloud config server that has been terminated, instead of getting the new old.

During debugging I tried to find where these properties are supposed to be updated. I've seen that the class DiscoveryClientConfigServiceBootstrapConfiguration run periodically the refresh method that should (not very clear to me) update that configuration with:
this.config.setUri(url); 
I see it contains the new address (this function contains the logic to discover the address by eureka).

After that I noticed that refresh method was called twice with different instances of DiscoveryClientConfigServiceBootstrapConfiguration. Each time it returns alternatively the first and the second address. This seems a weird thing.

I double checked all the code and I found that I have declared @EnableEurekaClient but @EnableDiscoveryClient is declared by DiscoveryClientConfigServiceBootstrapConfiguration. I tried to remove @EnableEurekaClient from my spring app, and now it seems that it calls refresh method once.

I'm not completely sure this situation is stable. I'll update you soon after some more other tests (also on AWS).

**Comment by spencergibb** [comment]
duplicates #514?

**Comment by paolo-rendano** [comment]
yes, I guess.
What I definitely see is the DiscoveryClientConfigServiceBootstrapConfiguration is loaded twice: during bootstrap and also later leaving two different leaving instance of beans DiscoveryClientConfigServiceBootstrapConfiguration and ConfigClientProperties.
```
	private ConfigClientProperties defaultProperties;

	public ConfigServicePropertySourceLocator(ConfigClientProperties defaultProperties) {
		this.defaultProperties = defaultProperties;
	}
```
The bootstrap one is no more refreshed after a while, so any beans that refers to that instance will never get updated. In my case this is the case ConfigServicePropertySourceLocator used by the HealthCheck.

So, for me the best would to lookup from discovery server the real config server address in the ConfigServicePropertySourceLocator and not getting it from defaultProperties.

example:
now locate is:
```
ConfigClientProperties properties = this.defaultProperties.override(environment);
		CompositePropertySource composite = new CompositePropertySource("configService");
		RestTemplate restTemplate = this.restTemplate == null ? getSecureRestTemplate(properties)
				: this.restTemplate;
		Exception error = null;
		String errorBody = null;
		logger.info("Fetching config from server at: " + properties.getRawUri());
```

should be something as (cut and past from the refresh method):
```
			String serviceId = this.config.getDiscovery().getServiceId();
			List<ServiceInstance> instances = this.client.getInstances(serviceId);
			if (instances.isEmpty()) {
				logger.warn("No instances found of configserver (" + serviceId + ")");
				return;
			}
			ServiceInstance server = instances.get(0);
			String url = getHomePage(server);
			if (server.getMetadata().containsKey("password")) {
				String user = server.getMetadata().get("user");
				user = user == null ? "user" : user;
				this.config.setUsername(user);
				String password = server.getMetadata().get("password");
				this.config.setPassword(password);
			}
			if (server.getMetadata().containsKey("configPath")) {
				String path = server.getMetadata().get("configPath");
				if (url.endsWith("/") && path.startsWith("/")) {
					url = url.substring(0, url.length() - 1);
				}
				url = url + path;
			}

```
and would avoid to set statically the uri in the ConfigClientProperties object with: this.config.setUri(url); 
preferring a lazy binding to that uri.

@spencergibb What do you think about this?

**Comment by sumitsarkar** [comment]
@paolo-rendano Any success with the way you proposed?

**Comment by spencergibb** [comment]
Closing in favor of #514

**Comment by izeye** [comment]
@spencergibb Not closed yet? 😅
