### ISSUE TITLE
Config server is not available with several Eureka server instances

### ISSUE THREAD

**Issue by aleskurlovich** [spring-cloud/spring-cloud-config#593]
Hello! I have a problem with spring cloud config. I use it with Eureka and when I test it localy (1 Eureka instance, 1 Config server instance and one instance of each microservice), it works perfectly. But when I deploy it on Docker host with several instances of Eureka (only one difference comparing with local tests), sometimes different microservices can't get right config server uri, use default and fail. I developed script which waits until GET http://registry1:8761/eureka/apps/config-service returns 200 (which means to me that config server is up and available through Eureka) and only after it I start microservices but it didn't help.

I attached log files of microservice, config server and Eureka registry. If it is not enough, I can create test project and commit it.
[client-service.txt](https://github.com/spring-cloud/spring-cloud-config/files/661061/client-service.txt)
[config-service.txt](https://github.com/spring-cloud/spring-cloud-config/files/661060/config-service.txt)
[registry1.txt](https://github.com/spring-cloud/spring-cloud-config/files/661062/registry1.txt)

It is configuration of config server (application.yml):
```
debug: true

server:
  port: 8070

spring:
  application:
    name: config-service
  rabbitmq:
    addresses: rabbitmq1:5672
  cloud:
    config:
      server:
        native:
          searchLocations: ${configLocation}
  profiles:
     active: native

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry1:8761/eureka,http://registry2:8761/eureka
  instance:
    preferIpAddress: true
```

It is configuration of Eureka server (application.yml):
```
debug: true

server:
  port: 8761

spring:
  application:
    name: registry

---
spring:
  profiles: registry1
eureka:
  instance:
    hostname: registry1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
        defaultZone: http://registry2:8761/eureka

---
spring:
  profiles: registry2
eureka:
  instance:
    hostname: registry2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
        defaultZone: http://registry1:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
```

It is configuration of microservice which has a problem (bootstrap.yml):
```
debug: true

server:
    port: 8082

spring:
  application:
    name: client-service
  cloud:
    config:
      discovery:
        serviceId: config-service
        enabled: true
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 20
        multiplier: 3

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry1:8761/eureka,http://registry2:8761/eureka
  instance:
    preferIpAddress: true
```

**Comment by ryanjbaxter** [comment]
The timestamps between when the config-service is registered and when the config-client makes a request to Eureka seems to line up.  However no where in the logs does it say which Eureka instance the config-client is using.  I would suspect that it would be using registry1 but it could be that it is using registry2 and the two Eureka servers have not replicated the registry data between them yet.  It would help to confirm which Eureka server is being used.

**Comment by aleskurlovich** [comment]
Thank you Ryan. I guess you are right. I tested it again with "logging.level.root=DEBUG" (sorry, I don't know how to check exactly what you asked). I attached two log files - when client is worked and failed:

[client-failed.txt](https://github.com/spring-cloud/spring-cloud-config/files/663654/client-failed.txt)
[client-ok.txt](https://github.com/spring-cloud/spring-cloud-config/files/663655/client-ok.txt)

I found in log files next lines.
For client-ok:
```
Line 15386: 2016-12-20 11:08:00.506 DEBUG 95 --- [           main] c.n.d.s.r.aws.ConfigClusterResolver      : Config resolved to [AwsEndpoint{ serviceUrl='http://registry1:8761/eureka/', region='us-east-1', zone='defaultZone'}, AwsEndpoint{ serviceUrl='http://registry2:8761/eureka/', region='us-east-1', zone='defaultZone'}]
	Line 15386: 2016-12-20 11:08:00.506 DEBUG 95 --- [           main] c.n.d.s.r.aws.ConfigClusterResolver      : Config resolved to [AwsEndpoint{ serviceUrl='http://registry1:8761/eureka/', region='us-east-1', zone='defaultZone'}, AwsEndpoint{ serviceUrl='http://registry2:8761/eureka/', region='us-east-1', zone='defaultZone'}]
	Line 15399: 2016-12-20 11:08:00.517 DEBUG 95 --- [           main] c.n.d.s.r.a.ZoneAffinityClusterResolver  : Local zone=defaultZone; resolved to: [AwsEndpoint{ serviceUrl='http://registry1:8761/eureka/', region='us-east-1', zone='defaultZone'}, AwsEndpoint{ serviceUrl='http://registry2:8761/eureka/', region='us-east-1', zone='defaultZone'}]
	Line 15399: 2016-12-20 11:08:00.517 DEBUG 95 --- [           main] c.n.d.s.r.a.ZoneAffinityClusterResolver  : Local zone=defaultZone; resolved to: [AwsEndpoint{ serviceUrl='http://registry1:8761/eureka/', region='us-east-1', zone='defaultZone'}, AwsEndpoint{ serviceUrl='http://registry2:8761/eureka/', region='us-east-1', zone='defaultZone'}]
```

For client-failed:
```
Line 13721: 2016-12-20 11:07:58.156 DEBUG 95 --- [           main] c.n.d.s.r.aws.ConfigClusterResolver      : Config resolved to [AwsEndpoint{ serviceUrl='http://registry1:8761/eureka/', region='us-east-1', zone='defaultZone'}, AwsEndpoint{ serviceUrl='http://registry2:8761/eureka/', region='us-east-1', zone='defaultZone'}]
	Line 13721: 2016-12-20 11:07:58.156 DEBUG 95 --- [           main] c.n.d.s.r.aws.ConfigClusterResolver      : Config resolved to [AwsEndpoint{ serviceUrl='http://registry1:8761/eureka/', region='us-east-1', zone='defaultZone'}, AwsEndpoint{ serviceUrl='http://registry2:8761/eureka/', region='us-east-1', zone='defaultZone'}]
	Line 13737: 2016-12-20 11:07:58.169 DEBUG 95 --- [           main] c.n.d.s.r.a.ZoneAffinityClusterResolver  : Local zone=defaultZone; resolved to: [AwsEndpoint{ serviceUrl='http://registry2:8761/eureka/', region='us-east-1', zone='defaultZone'}, AwsEndpoint{ serviceUrl='http://registry1:8761/eureka/', region='us-east-1', zone='defaultZone'}]
	Line 13737: 2016-12-20 11:07:58.169 DEBUG 95 --- [           main] c.n.d.s.r.a.ZoneAffinityClusterResolver  : Local zone=defaultZone; resolved to: [AwsEndpoint{ serviceUrl='http://registry2:8761/eureka/', region='us-east-1', zone='defaultZone'}, AwsEndpoint{ serviceUrl='http://registry1:8761/eureka/', region='us-east-1', zone='defaultZone'}]
```
c.n.d.s.r.a.ZoneAffinityClusterResolver logs different order of endpoints...

May be I should specify several zones which is described [here](https://github.com/spring-cloud/spring-cloud-netflix/issues/203#issuecomment-212586039)...

**Comment by ryanjbaxter** [comment]
Yes forcing it to use an Eureka server in a given zone (initially at least) would probably be the best bet.

**Comment by aleskurlovich** [comment]
It works. I added several zones. There is only one Eureka server instance per zone. All microservices are in one zone. Thank you for your help!

Could you please mention zone importance in "Peer Awareness" part of Eureka documentation?

**Comment by ryanjbaxter** [comment]
What exactly do you think is missing?

**Comment by aleskurlovich** [comment]
As I understand issue was that several Eureka server instances were in one zone. May be it is obviously for people how are familiar with Eureka but not for new developers. From my point of view, it will be useful if you add note like "Keep in mind that usually there is only one Eureka instance per zone ([see](https://github.com/Netflix/eureka/wiki/Eureka-at-a-glance#high-level-architecture) Eureka documentation). Several Eureka instances in one zone are possible but you should know what you do".

**Comment by ryanjbaxter** [comment]
As you point out, Netflix already documents this, I would rather not duplicate that in Spring Cloud.

**Comment by asarkar** [comment]
@aleskurlovich @ryanjbaxter I'm researching Eureka clustering and came across this ticket. I'm not clear what's the issue with zone here. The logs show all using `defaultZone`, which is the default set by Spring. Eureka config shows that they are **NOT** replicated (`registerWithEureka: false`) for profiles `registry1` and `registry2`. The order of endpoints shouldn't matter as the client will try the 2nd one if the first fails. Where does zone come in this picture?

**Comment by aleskurlovich** [comment]
@asarkar I tested again with "registerWithEureka: false" and two registries. First one was primary node and all services were registered there. After killing of it all services became available in another node. How did you test it?

My problem was that sometimes even when registry1 is available some services could register itself to registry2. When I added registry1 and registry2 at different zones, it helped.

I removed "registerWithEureka: false" and "fetchRegistry: false" and I didn't reproduce my problem (I used one default zone). It looks like you are right and "Peer Awareness" part of documentation ([link](http://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/1.2.4.RELEASE/)) doesn't include such settings... So, thank you for your response! But it will be better if somebody approve it...

**Comment by ryanjbaxter** [comment]
The problem was that the peer hadnt receive the instance information yet, and the client was querying the peer.  I am going to close this issue because it belongs in spring-cloud-netflix, not config.  We can continue the discussion over there if need be.
