### ISSUE TITLE
How to enable force-pulling of a dirty repository?

### ISSUE THREAD

**Issue by andyshinn** [spring-cloud/spring-cloud-config#596]
It sounds like https://github.com/spring-cloud/spring-cloud-config/pull/473 has a way for us to pull a dirty repository (for example, one that had branches force-pushed). Can we get an example / documentation on how to use it? It is unclear from the pull request how to actually enable it.

**Comment by marcosbarbero** [comment]
I'm working on it

**Comment by marcosbarbero** [comment]
While it's not merged you can check it out right here https://github.com/marcosbarbero/spring-cloud-config/blob/master/docs/src/main/asciidoc/spring-cloud-config.adoc#force-pull-in-git-repositories

**Comment by andyshinn** [comment]
Makes sense. Thanks!
