### ISSUE TITLE
Config server fails to start when attempting to serve encrypted keys without decrypting them

### ISSUE THREAD

**Issue by Fitzoh** [spring-cloud/spring-cloud-config#597]
According to the documentation, setting spring.cloud.config.server.encrypt.enabled=false should prevent spring cloud config from decrypting secrets, and instead pass them to the client. However, if that property is set to false and a value in the remote application.properties is encrypted, the application will fail on startup.

The workaround I have found is to set encrypt.fail-on-error=false in bootstrap.properties.

Minimal example located here: https://github.com/Fitzoh/spring-cloud-config-encryption-issue

**Comment by ryanjbaxter** [comment]
I think the problem actually has to do with the fact that you have the `config` directory in the app as well as in the remote repo (the repo for the server and the repo for the configuration are the same).  If you separate the two you should be all set.

**Comment by Fitzoh** [comment]
Yeah, guess you're right @ryanjbaxter . I didn't realize that spring checked ${projectDir}/config.
I renamed the directory from `config` to `configuration` and that resolved the issue.
Closing, thanks!

**Comment by eacdy** [comment]
@Fitzoh I‘ve found the same problem.
Could share the correct code of both server and client side?

**Comment by ryanjbaxter** [comment]
There was no code change, it just involved changing a directory name.
