### ISSUE TITLE
Multiple ConfigServicePropertySourceLocator bean after restart.

### ISSUE THREAD

**Issue by olayinkasf** [spring-cloud/spring-cloud-config#599]
After calling restart, a new ConfigServicePropertySourceLocator is created and the old one is kept. The problem is they are all invoked after restart so if I POST to restart 10 times, I get 11 beans and eleven invocations which is very weird.

**Comment by olayinkasf** [comment]
Breakpoint at `SpringApplication#addInitializers(ApplicationContextInitializer<?>... initializers)`

```
this = {SpringApplication@2244} 
initializers = {ApplicationContextInitializer[2]@6093} 
 0 = {PropertySourceBootstrapConfiguration$$EnhancerBySpringCGLIB$$56dce074@6097} 
 1 = {EnvironmentDecryptApplicationInitializer@6098} 
this.initializers = {ArrayList@3671}  size = 10
 0 = {DelegatingApplicationContextInitializer@3784} 
 1 = {ContextIdApplicationContextInitializer@3785} 
 2 = {ConfigurationWarningsApplicationContextInitializer@3786} 
 3 = {ServerPortInfoApplicationContextInitializer@3787} 
 4 = {SharedMetadataReaderFactoryContextInitializer@3788} 
 5 = {AutoConfigurationReportLoggingInitializer@3789} 
 6 = {BootstrapApplicationListener$AncestorInitializer@3678} 
 7 = {PropertySourceBootstrapConfiguration$$EnhancerBySpringCGLIB$$56dce074@3705} 
 8 = {EnvironmentDecryptApplicationInitializer@3706} 
 9 = {BootstrapApplicationListener$DelegatingEnvironmentDecryptApplicationInitializer@3715} 
```

As you can see, it is about to add another instance of `PropertySourceBootstrapConfiguration` to the initializer list.

**Comment by spencergibb** [comment]
Thanks for the report

**Comment by marcingrzejszczak** [comment]
Is it still a problem with Finchley.RELEASE?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
