### ISSUE TITLE
Question on Environment Changes

### ISSUE THREAD

**Issue by NickPadilla** [spring-cloud/spring-cloud-config#60]
Hello,

When a change is pulled from the remote git repository do all services with the changed configuration get the changes automatically?  Or do we need to call the /refresh or /restart endpoints on those services?  

I made a change to the repository and the changes didn't get pulled until the next call for a configuration was made.  That is fine, but when that happens do all other services get their configuration updated automatically?  If not that is fine as well, we need to call the endpoints to have configuration updated - which works really well for rolling updates.  If it does update services automatically, how can we disable that so that we can do rolling updates?   Please let me know if you have any questions for me, thanks for the great work!

**Comment by NickPadilla** [comment]
OK, after doing a bit of testing I have found that updates to configurations do not automatically propagate to the services.  The new configurations are pulled when a request for a configuration resource comes in, only the resource that triggered the pull gets the updated configuration.  So this setup should work well for rolling updates.  

Now having said that, is there a way to trigger an update for all services of a given type all at once - or maybe have it work automatically?

**Comment by spencergibb** [comment]
[See here](https://github.com/spring-cloud/spring-cloud-bus/#quick-start).  In short you can post to `/bus/refresh?destination=<serviceId>`.  If you leave off the `destination` parameter, it will go to all services bound to the bus.
