### ISSUE TITLE
Spring Cloud Config Server version change

### ISSUE THREAD

**Issue by SaltOfTheFlame** [spring-cloud/spring-cloud-config#600]
Hello, dear spring cloud commiters

I have a project, running on spring boot 1.3.8 and Brixton.SR7
Question is, will it be right and, if not, is it safe and what can I expect if I am going to use Spring Cloud Config Server from Camden freshest releases ?
Does that worse the troubles, that could appear?

**Comment by ryanjbaxter** [comment]
You best bet might be look through the [release notes for Camden](https://github.com/spring-projects/spring-cloud/wiki/Spring-Cloud-Camden-Release-Notes) to see what changed.
