### ISSUE TITLE
Way to refresh properties in config client when update de properties in git?

### ISSUE THREAD

**Issue by LucasHCruz** [spring-cloud/spring-cloud-config#601]
I'm using local repository in the same machine of config server.

I need to update the local git and the config client refresh the properties.

Is there anyway to do this?

**Comment by ryanjbaxter** [comment]
Have you tried using the '/refresh' endpoint?

**Comment by LucasHCruz** [comment]
How can I enable `/refresh`? I don't have any `/refresh` endpoint

**Comment by LucasHCruz** [comment]
Oh jesus!!! Was just send a POST not a GET.... My mistake guys :D

**Comment by ryanjbaxter** [comment]
Yup :)
