### ISSUE TITLE
how to localy change the environment after the cloud property source in prepared ?

### ISSUE THREAD

**Issue by shalom938** [spring-cloud/spring-cloud-config#603]
I want to be able to manipulate the environment locally after the bootstrap property source is initialized. but ConfigServicePropertySourceLocator is invoked in a context initializer and therefor ApplicationEnvironmentPreparedEvent is too early.  i think ApplicationPreparedEvent is too late because the bean definitions are already created. only way i see is a context initializer with lower precedence then PropertySourceBootstrapConfiguration but it doesn't look like very reliable if things change in future versions.
I'll be happy for ideas.

Thank you

**Comment by spencergibb** [comment]
you could use a `org.springframework.cloud.bootstrap.BootstrapConfiguration` instead of a context initializer.

**Comment by shalom938** [comment]
@spencergibb , Thanks for the response. Maybe i was not clear enough. i want to manipulate the real environment, not the bootstrap context environment. BootstrapConfiguration is used to build the bootstrap context. but the PropertySourceLocator is invoked as a ApplicationContextInitializer (PropertySourceBootstrapConfiguration) of the main application context. and i don't see a way to change the environment after ConfigServicePropertySourceLocator.locate is invoked. 
I think the real problem is that with cloud config client you can not rely on ApplicationEnvironmentPreparedEvent because it will be invoked before the environment is fully prepared by ConfigServicePropertySourceLocator.

**Comment by marcingrzejszczak** [comment]
Is it still a problem with Finchley.RELEASE?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
