### ISSUE TITLE
Support Defining Property For Multiple Apps in Single File

### ISSUE THREAD

**Issue by tgolden-andplus** [spring-cloud/spring-cloud-config#605]
The cloud config server does a great job letting me define common properties to all apps in `application.(yml|properties)` and specific properties in each `<application>` file. However, if I'm using the config server to manage something like the `server.port` property for each app (as an example) that property has to live in the specific application file. When I add a new app and config file I have to read all the other application files to see what port is available.

What would be a nice enhancement would be some way of defining a list of properties for each app in one file, in sort of the inverse approach, e.g. in some file `ports.properties`:
```
serviceA.server.port=8080
serviceB.server.port=8081
serviceC.server.port=8082
//etc...
```

The idea is that the property key is prefixed with the application name, which would be stripped before being sent to that client app, so that it receives the normal `server.port` property. It'd be nice if this config file could have an arbitrary name, which probably means it couldn't live at the root level where the other config files live (what would happen when you added an app named 'ports'?). 

Some complications I could see this introducing would be what happens when the same property is defined both in one of these "shared" files as well as in the client-specific file. However there are already rules for overriding properties from `application.properties` so this might not be too bad.

I'm also open to feedback telling me there's a simpler way to do what I'm looking for already. :)

**Comment by ryanjbaxter** [comment]
One solution that would come to mind would be to put these properties in `application.properties` for example and use Spring Profiles to separate them out.

**Comment by tgolden-andplus** [comment]
@ryanjbaxter can you give a short example snippet of how you might do that? Is there a way to separate config sections by profile right in the properties file?

**Comment by ryanjbaxter** [comment]
Here is an example `application.yml` you can put in your config repo.  Each app would have to have the specific profile active in order to get the properties.

```
---
spring:
  profiles: serviceA
server:
  port: 8080

---
spring:
  profiles: serviceB
server:
  port: 8081

---
spring:
  profiles:  serviceC
server:
  port: 8082
```

**Comment by tgolden-andplus** [comment]
Ah, I didn't realize that the YAML files had that [multi-profile capability](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-yaml) built in already. This seems like a good-enough workaround for the sort of thing I described, then.

**Comment by JamesXiao** [comment]
Sorry to dig up this old and closed issue, but I have a problem related.

The question is, what if my serviceA also want to know the port number of serviceB, in order to do some communication between the two?

The proposed solution of using separate profiles will hide port number of serviceB, when running serviceA with profile "serviceA"

**Comment by ryanjbaxter** [comment]
@JamesXiao sounds like a good use case for service discovery.
