### ISSUE TITLE
Silent Fail When user Field is incorrect or Empty in bootstrap.yml

### ISSUE THREAD

**Issue by rayfagan** [spring-cloud/spring-cloud-config#606]
I am receiving no error or notice of failure when deploying an application running spring cloud config and spring boot when the username field is incorrect (including if it is empty) in the application's configuration. The application appears to deploy properly, but the application's functionality fails when it's endpoints are called.

I've also noticed that if the url or password fields are incorrect then I receive an error and the app fails to deploy, which is the expected behavior.

**Comment by ryanjbaxter** [comment]
I am not sure I understand the problem.  Can you provide a sample the demonstrates the issue?

**Comment by rayfagan** [comment]
Sure, here is a sample of the bootstrap.yml
`spring:
  application:
    name: <name of app in cloud config>
  cloud:
    config:
      uri:  ${<correct_host>}
      user: ${<incorrect user>}
      password: ${<config server password>}
  profiles:
    active: ${<active profile environment variable>}

server:
  context-path: <Name of application>`

Even with the incorrect username the application deploys in jboss with no errors as seen below.

`11:44:38,778 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 9.0.1.Final (WildFly Core 1.0.1.Final) started in 23117ms - Started 926 of 1093 services (246 services are lazy, passive`

I was expecting the application to either fail to deploy or for spring to throw an exception when the user is incorrect. It currently fails properly when the url and password are incorrect (as seen below)

`11:51:24,692 ERROR [org.springframework.boot.SpringApplication] (ServerService Thread Pool -- 24) Application startup failed: org.springframework.beans.FatalBeanException: Could not copy property 'password' from source to target; nested exception is java.lang.reflect.InvocationTargetException`

**Comment by ryanjbaxter** [comment]
The complete working application would be more useful in reproducing the problem.

**Comment by rayfagan** [comment]
I will provide a sample application which replicates the issue tomorrow Afternoon.
For now I will provide the spring cloud client information before including the app. 

The cloud client is authenticating against LDAP

**Comment by rayfagan** [comment]
I will provide a sample application which replicates this issue tomorrow afternoon. With that I will include the information to replicate the cloud config server settings as well.

**Comment by rayfagan** [comment]
I have compiled a sample application and will send it over to you on Monday, along with an example configuration.

**Comment by rayfagan** [comment]
[CloudConfigSampleApp.zip](https://github.com/spring-cloud/spring-cloud-config/files/694806/CloudConfigSampleApp.zip)

**Comment by rayfagan** [comment]
Hi Ryan, attached below is a very basic sample app that I used to recreate the issue. When boot run is called against a config setup for properly configured application "config-name" with environment variables (HOST for uri, USER for user, PASSWORD for password, and ENV for active profile this app will work properly. However when the uri field is empty or the password field is empty the app will fail (as expected). Interestingly when the user field is left blank the app will still launch successfully as if the configuration is proper (the silent fail).

**Comment by rayfagan** [comment]
[CloudConfigSampleApp.zip](https://github.com/spring-cloud/spring-cloud-config/files/694812/CloudConfigSampleApp.zip)

**Comment by rayfagan** [comment]
The sample configuration is using a jtds driver for the sql datasource and an encrypted password which is working for this app. I am unable to send the configuration.

**Comment by rayfagan** [comment]
Correctly failing bootstrap.yml

[bootstrap.yml.zip](https://github.com/spring-cloud/spring-cloud-config/files/694819/bootstrap.yml.zip)

**Comment by rayfagan** [comment]
Incorrectly passing bootstrap.yml

[bootstrap.yml.zip](https://github.com/spring-cloud/spring-cloud-config/files/694820/bootstrap.yml.zip)

**Comment by spencergibb** [comment]
@rayfagan by default, config client doesn't fail fast. If the user is missing, the client will log a warning `Could not locate PropertySource: ...`.

If you want it to fail when it can't reach, set `spring.cloud.config.fail-fast=true`.

**Comment by rayfagan** [comment]
Wonderful, thank you very much @spencergibb.

**Comment by spencergibb** [comment]
can we close this then?

**Comment by rayfagan** [comment]
Yes, all set on my end, thank you.
