### ISSUE TITLE
Config client cannot parse propertySource from config server using snake case

### ISSUE THREAD

**Issue by zhengl7** [spring-cloud/spring-cloud-config#608]
Help needed. 

Started a config server by embedding it into an existing Spring Boot app. The original Spring app has a REST API and has snake case for JSON, by specifying `spring.jackson.property-naming-strategy=CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES`.

Problem is the new config properties from the embedded config server also follows this naming and I think it causes the client not be able to parse it correctly. Here is an example of the config endpoint response,

```JSON
{
 "name": "my-app",
 "profiles": [
    "test"
  ],
  "label": "null",
  "version": "942d818e31449d972547b8a1d94deae6ca95ebd4",
  "property_sources": [
   {
      "name": "...",
      "source":{
            "server.port": "8877"
       }
   }
   ]
}
```

I stepped into the config client code, and found that on parsing the [Environment](https://github.com/spring-cloud/spring-cloud-config/blob/v1.1.0.RELEASE/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/environment/Environment.java) object, all other keys are parsed except the propertySource, which is empty. So suspecting it is due to the naming convention. Tried a few things like adding `spring.jackson.property-naming-strategy=CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES` to `bootstrap.properties` in config client but it doesn't help. So wondering if I'm doing it wrong or the config client just cannot work with a snake case config server.

**Comment by spencergibb** [comment]
@Jeckyli very likely the client can't understand it. There was a similar issue where the config server output was changed to xml and the client had similar errors.

**Comment by Jeckyli** [comment]
@spencergibb thanks for the quick response. But I'm not quite sure why there is such limitation. Looks to me config client also uses Jackson for parsing JSON, so to me it should be configurable in anyway Jackson can be.

Usually if I'd parse an entity from JSON in snake, I'd annotate the entity specifically. But this is Spring Cloud Config code so I cannot do this. 

Also I thought the boot config with `spring.jackson.property-naming-strategy=CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES` would instruct all Jackson deserialization to recognize snake case, thus including config client. But not sure why this is not working.

**Comment by spencergibb** [comment]
Yeah, not sure why it doesn't, but it seems like it should be possible.

**Comment by Jeckyli** [comment]
I might be wrong, but could this be due to the client will only read configuration properties from the config server and thus ignore `spring.jackson.property-naming-strategy=CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES` from the local file? If this is the case, then it's a chicken-and-egg problem, meaning I cannot have any local properties to configure the config client (other than the recognized properties in bootstrap about config server)? 

Or in other words, is there anyway to let the Spring Boot app honor local properties before the ones from config client?

**Comment by spencergibb** [comment]
@Jeckyli the client reads from local configuration files, but the property would need to be in `bootstrap.{properties|yml}` or an Env Var or System Property.

**Comment by jhonatasobrinho** [comment]
@zhengl7 have you solved this? I'm facing the same issue. And tried to apply @spencergibb 's suggestion but nothing worked.

**Comment by zhengl7** [comment]
@jhonatasobrinho No I haven't. And I didn't work on this for a while so not sure if there has been any updates. Sorry.

**Comment by jhonatasobrinho** [comment]
I've figured out one thing. It is serializing using snake_case when the setup is made by bootstrap.yml and camel case when it is configured through application.properties. I don't know why that happens.
