### ISSUE TITLE
propagate profile info to spring-config clients

### ISSUE THREAD

**Issue by Vad1mo** [spring-cloud/spring-cloud-config#61]
Hello
this might be a bit off topic as it is only directed to a cloud config client. 

We have a zone where all microservices have one and the same profile (prod/te/dev) currently we start each microservice with spring.profiles.active and the url to the config server. 
IMHO providing the spring.profiles.active for each microservice is redundant as it can be also retrieved from the config-server. So I would like to start only the config-server in the zone with an active profile such as (prod/te/dev) and this should be propagated to the config clients.

Regarding an implementation.
1. Can a profile be changed at runtime in spring?
2. Is there a way a calling client can pull the correct spring.profiles.active?
3. Can a context refresh be performed automatically after the fetching from-config server.   eg. config client starts with default profile gets the active profile from config server and activates this profile.

**Comment by dsyer** [comment]
If the config server sets a profile it should apply in all the clients. Did you try it and it didn't work?

**Comment by dsyer** [comment]
If you want to change the profile in a running server though, you need to restart the application context (or the whole application). There is a /restart endpoint (and support in the bus), but your environment might provide a clean way to automate it using some other mechanism.
