### ISSUE TITLE
Does config server have a cache and a polling mechanism?

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-config#615]
We're currently using config server with `native` profile and file system property files. 

1. I've noticed that changes in property files seem to be picked up by config server without restart or refresh, so I'm assuming it has a polling mechanism. If so, what's the interval and how can I modify that if I want to? 
2. Does config server cache the properties before or after merging from various property sources? If yes, what's the interval and how can I modify that if I want to?

**Comment by spencergibb** [comment]
No cache and no polling. It reads from the filesystem each time. If you are using the `-monitor` starter, it will use facilities to "watch" for filesystem changes.

**Comment by asarkar** [comment]
>  It reads from the filesystem each time

@spencergibb "Each time" being each HTTP request from a client? That'd explain why the local changes are immediately seen.

**Comment by spencergibb** [comment]
Yes
