### ISSUE TITLE
Running ApplicationTests from IDEA results in an IllegalArgumentException

### ISSUE THREAD

**Issue by roykachouh** [spring-cloud/spring-cloud-config#62]
When running `ApplicationTests` individually from your IDE, the test fails because `JGitEnvironmentRepository#copyFromLocalRepository` does not recognize the path 'file:./target/test-classes/config-repo' as a file.  This is primarily due to the IDE working directory when running tests defaults to the parent project.  We can easily change the working directory in our Run configuration, but I thought if there was a better way to initialize the `spring.cloud.config.server.git.uri` property in the test it might make for smoother testing.

```
java.lang.IllegalArgumentException: Source File must denote a directory or file
	at org.springframework.util.Assert.isTrue(Assert.java:65)
	at org.springframework.util.FileSystemUtils.copyRecursively(FileSystemUtils.java:61)
	at org.springframework.cloud.config.server.JGitEnvironmentRepository.copyFromLocalRepository(JGitEnvironmentRepository.java:264)
	at org.springframework.cloud.config.server.JGitEnvironmentRepository.copyRepository(JGitEnvironmentRepository.java:249)
	at org.springframework.cloud.config.server.JGitEnvironmentRepository.createGitClient(JGitEnvironmentRepository.java:241)
```

![image](https://cloud.githubusercontent.com/assets/2084958/5760541/74604ec0-9ca3-11e4-927d-c583373c1204.png)

**Comment by dsyer** [comment]
Since it works in Eclipse (and on the command line), I guess I need a suggestion of what might work for everyone. Maybe a tmp dir?

**Comment by roykachouh** [comment]
Yeah, I think a tmp dir might make sense.  It's not a huge deal, I can take a look at implementing this if you would like.

**Comment by dsyer** [comment]
Sure that would be good. Just be careful in case there is no tmpdir (not uncommon in CI servers).

**Comment by dsyer** [comment]
There's already some code to deal with this situation in a different test case I noticed: https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-client/src/test/java/org/springframework/cloud/bootstrap/config/BootstrapConfigurationTests.java#L86. Maybe you could extract that and re-use it?
