### ISSUE TITLE
/encrypt, /decrypt documentation

### ISSUE THREAD

**Issue by andysworkshop** [spring-cloud/spring-cloud-config#620]
The docs refer to example usage like this:
````
$ curl localhost:8888/encrypt -d mysecret
````
We've found that this silently produces the wrong result if the password contains characters that need to be url-encoded, e.g. the `+` sign that can occur in a strong password. A better usage of curl for this purpose is:
````
$ curl localhost:8888/encrypt --data-urlencode mysecret
````

**Comment by ryanjbaxter** [comment]
I think just adding a `NOTE` about this in the documentation would be good.  Thoughts?

**Comment by spencergibb** [comment]
@ryanjbaxter yes

**Comment by andysworkshop** [comment]
agreed.

**Comment by ryanjbaxter** [comment]
Fixed via commit https://github.com/spring-cloud/spring-cloud-config/commit/937027b9a44e99f10874241749d2b6e4cad0ae62
