### ISSUE TITLE
Config server HA and Git webhook

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-config#624]
We want to run multiple instances of config and set up Git webhooks but the issue is each config instance is independent. So either we've to set up a webhook for each instance or perhaps use a shared directory to clone the repo locally. Are there better options?

**Comment by spencergibb** [comment]
Our recommended config server HA setup is behind a load balancer.

**Comment by asarkar** [comment]
@spencergibb If we do that and give the LB URL to Git, the webhook notifications will be sent to only one of the config server instances. How will it notify the peers to update their locally cloned copy?

**Comment by spencergibb** [comment]
the monitor works by sending out `/bus/refresh` messages to clients. They then make requests to config server.

**Comment by asarkar** [comment]
I know that. What I'm asking is say, you've 3 config servers behind a LB. You set up a Git webhook for `http://lb/monitor`. LB picks config1 and forwards the POST request. config1 refreshes itself and puts a message in the bus for the clients to refresh themselves.
In all this, config2 and config3 still have a stale copy of the repo in local. Unless of course, they're using a shared volume (you didn't mention that so I'm assuming not).

**Comment by spencergibb** [comment]
The servers that host `/monitor` don't refresh themselves.

**Comment by asarkar** [comment]
OK, so in the use case I described above, the only way to keep the config instances in sync would be to use a shared volume. Or write additional code to sync them. Correct?

**Comment by spencergibb** [comment]
Config servers don't have state. Each request clones the git repo. There is nothing to sync.

**Comment by asarkar** [comment]
ok, thank you. Give me a few days to wrap my head around this and I'll either close the ticket or ask a clarifying question.
