### ISSUE TITLE
Dalston.M1: spring-cloud-config-client doesn't work with spring-cloud-config-monitor

### ISSUE THREAD

**Issue by aalsup** [spring-cloud/spring-cloud-config#633]
I'm using release `spring-cloud-dependencies:Dalston.M1` and `spring-boot-dependencies:1.5.1.RELEASE`

My application is using `spring-cloud-config-client`, but I cannot seem to get both `spring-cloud-config-client` and `spring-cloud-config-monitor` working together.

This pom.xml snippet **works** _(without `spring-cloud-config-monitor`)_:

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-config-client</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-bus-amqp</artifactId>
</dependency>
```

Resulting in the logs below, just after the Spring banner.  It 

```
c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:9999
c.c.c.ConfigServicePropertySourceLocator : Located environment: name=snippitz-rest, profiles=[default], label=null, version=null, state=null
b.c.PropertySourceBootstrapConfiguration : Located property source: CompositePropertySource [name='configService', propertySources=[MapPropertySource [name='classpath:/config/snippitz-rest/application.properties']]]
c.a.snippitz.app.SnippitzApplication     : No active profile set, falling back to default profiles: default
```

However, when I include `spring-cloud-config-monitor` the spring-cloud-config-server is NOT consulted for properties.  
This pom.xml snippet **does not work**.  The only thing changed is the inclusion of the the `spring-cloud-config-monitor` artifact.

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-config-client</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-config-monitor</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-bus-amqp</artifactId>
</dependency>
```

Resulting in the following log, just after the Spring banner.  Notice there's no mention of ConfigServicePropertySourceLocator nor PropertySourceBootstrapConfiguration:

```
c.a.snippitz.app.SnippitzApplication     : No active profile set, falling back to default profiles: default
```

**Comment by spencergibb** [comment]
So config-monitor doesn't make a lot of sense on a config-client. We've used it with config-server.

**Comment by spencergibb** [comment]
config-monitor brings in config-server which disabled config-client by default. Is there a reason you're using monitor with client? You mention Dalston.M1 like this used to work. Can you provide a sample that used to work?

**Comment by spencergibb** [comment]
You can set `spring.cloud.config.server.bootstrap=true` in `bootstrap.yml`, but then you are configuring a config-server.

**Comment by aalsup** [comment]
Using config-monitor on the config-client is (I guess) a misunderstanding on my part.  My understanding was that hitting any of the client nodes' `/refresh` endpoints would result in a "cascade" via the bus, starting with the config-server (reloading the config settings), then pushing a `/refresh` to config-clients.

Is it correct that **only** the `config-server` requires `config-monitor`?
If so, is the `/refresh` POSTed to the `config-server` rather than the `config-clients`?

Thanks so much for the clarification on this.

**Comment by spencergibb** [comment]
It makes more sense to use config-monitor on the server. The webhook hits monitor, monitor sends bus message, clients receive bus message, clients make a request to config server.

**Comment by aalsup** [comment]
Thank you so much for the clarification.
