### ISSUE TITLE
ConfigWatch ignores first value for a "context"

### ISSUE THREAD

**Issue by ShalomDeitch1** [spring-cloud/spring-cloud-config#635]
version: spring-cloud-consul-config-1.2.0.M1
package: org.springframework.cloud.consul.config
class: ConfigWatch

lines 104-105
// don't publish the same index again, **don't publish the first time (-1) so index can be primed**
if (!this.consulIndexes.containsValue(newIndex) **&& !currentIndex.equals(-1L)**) {

issue: it is true that the "index" has to be primed, but there is also a need to publish the event, otherwise the first addition to some "context" is ignored. There can be a need to get updates, e.g. when there is a property in more then one PropertySource and the value from "Consul" has precedence.

thanks for your help
Shalom Deitch

**Comment by beeva-pablovaliente** [comment]
Hello all!

I am having the same issue with Spring Cloud Consul Config, but in my case I am using the 1.1.2-RELEASE version.

My scenario is as follows:
- My application starts when consul is still empty
- After application is started, a key is written in consul (manually)
- The application cannot detect this first change until a new change is made again in consul. When the second change happens, the event that arise, contains both updated keys.

Is there any way to fix this? I was previously using the 1.0.2-RELEASE version of Spring Cloud Consul Config and this didn't happen.

Thanks!

**Comment by spencergibb** [comment]
Please move to spring-cloud-consul

**Comment by beeva-pablovaliente** [comment]
Thanks @spencergibb.

I have open the next issue in Spring Cloud Consul: https://github.com/spring-cloud/spring-cloud-consul/issues/288

Regards!
