### ISSUE TITLE
Simpler Spring Cloud Config approach

### ISSUE THREAD

**Issue by Vad1mo** [spring-cloud/spring-cloud-config#64]
I am trying to integrate spring cloud config into our docker micro-service architecture. 

Currently spring-cloud-config propagates a client service architecture.
[GitRepp] <---accessedBy--- [Config Server]  <---accessedBy--- [Config Client 1..N] 
                                              
In our case the Config Server is just a main method with all the overhead of (git, gradle, jenkins, docker, versioning, jira, testcases and many more) This is quite a lot for an Application having "only" an empty main method.

While rethinking all this, the only USP that counts for us is the ability to pull the config from a git repository. So suddenly the question popped up, why do we need a Client Server setup at all?

Why don't the clients get their configuration directly from git?. This setup would have many advantages compared to the config server. (always running, failsafe, known address)

Could you explain why this is a good or bad idea, what features could the config server offer more then just to get the config from a repository?

**Comment by szpak** [comment]
I'm not the author of spring-cloud-config, but for me the primary reason could be a situation when you would like to separate the infrastructure (Git repository) using another (micro)service to provide configuration. That facade just could be possibly replaced when (for some reasons) Git is not welcome anymore. Probably Dave will have more interesting arguments for that architecture.

Nevertheless for our projects we had similar concerns and in the end we created [micro-infra-spring-config](https://github.com/4finance/micro-infra-spring/wiki/Centralized-configuration-management) solution which under the hood uses spring-cloud-config, but simplifies it to keep configuration stored in the local directory - usually Git repository which is updated/pulled with cron (or any other external tool) - what seems to be something what you described in your question.
If you interested @Vad1mo, it is a part of [micro-infra-spring](https://github.com/4finance/micro-infra-spring) stack which provides many common things needed to write custom microservice(s) (but can be used separately).

**Comment by Vad1mo** [comment]
I am trying to challenge if having a dedicated config server has any benefit over declaring Git as the config server and merging spring-config-server and sprint-config-client together. 
Having an config-server with no added custom code is very suspicious to me for its existence.

**Comment by spencergibb** [comment]
Encryption is one thing that comes to mind.  Right now only config server needs to know about the keys, otherwise, every service would need to know about the keys.

**Comment by dsyer** [comment]
The server separates concerns of application and configuration. You could do that with your build and deploy toolchain for sure (by storing the configuration in a different repository and checking it out during deployment), but that's not the only choice, and it's not available to everyone. I would say, though, to keep the separation clean, it needs to be done at deployment time, not at build time.
