### ISSUE TITLE
Can I maintain configuration for multiple applications through spring-cloud-config?

### ISSUE THREAD

**Issue by sunnyWangXin** [spring-cloud/spring-cloud-config#646]
I want to maintain configuration for multiple applications (one server and multiple clients), will spring-cloud-config support below requests？Thanks~
1. Support multiple git url in application.yml (Only query one repo one time)
2. Support multiple ssh location for different git repo

**Comment by spencergibb** [comment]
See http://cloud.spring.io/spring-cloud-static/Camden.SR5/#_pattern_matching_and_multiple_repositories

**Comment by sunnyWangXin** [comment]
Thanks, is there any API to add a new git repo(url, key) during runtime, without define in application.properties? @spencergibb

**Comment by ryanjbaxter** [comment]
You might want to consider creating your own `MultipleJGitEnvironmentRepository` bean.  https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/MultipleJGitEnvironmentRepository.java

**Comment by spencergibb** [comment]
@sunnyWangXin no

**Comment by sunnyWangXin** [comment]
Thanks for your advise @ryanjbaxter
