### ISSUE TITLE
Will cloud support slash in {application} placeholder?

### ISSUE THREAD

**Issue by sunnyWangXin** [spring-cloud/spring-cloud-config#648]
I use {application} placeholder in git url like below. 
And the actual directory in git is A/test1.git, A/test2.git, B/test3.git.
Is any method to pass A/test1 to {application}? I found that (_) only support for {label}.
Or do I need overwrite the method that analyze {application}? Or add another placeholder myself?
Thanks very much!
`spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://git@cedt-icg/{application}.git`

**Comment by ryanjbaxter** [comment]
Are `A` and `B` applications names?  Are `test1`, `test2`, `test3` profiles?

**Comment by sunnyWangXin** [comment]
Hmm, I take A/test1 as the application name. We have many sub-directories in git like below. 
I can access repo under directory A when I set url as `spring: cloud: config: server: git: uri: ssh://git@cedt-icg/A/{application}.git`. 
But if I want to access all repo under different sub-directory by set url as `spring: cloud: config: server: git: uri: ssh://git@cedt-icg/{application}.git`. I can't find the repo by http://localhost:8080/A/test1/dev/master, where I take A/test1 as the application name. @ryanjbaxter 

Git Repo: (ssh://git@cedt-icg)
-A 
    -test1.git
    -test2.git
-B
    -test3.git
-C
   -C1
     -test4.git

**Comment by ryanjbaxter** [comment]
I dont think that was the intention of replacing the application name in the git URL.  While I guess it is valid to have an application name with a slash in it, we don't interpret that slash as a path separator.

**Comment by spencergibb** [comment]
See http://cloud.spring.io/spring-cloud-static/Camden.SR5/#_pattern_matching_and_multiple_repositories

**Comment by sunnyWangXin** [comment]
Year, I saw this part. But in this implement, if a new sub-directory created, we must modify our application.yml right? Can't support existed and new repo automatically. @spencergibb

**Comment by ryanjbaxter** [comment]
Yes looks like that is the case

**Comment by sunnyWangXin** [comment]
Is there any better way to deal with new sub-directory and new repos? Instead of updating and building server every time @ryanjbaxter

**Comment by spencergibb** [comment]
Config Server can load it's configuration from git, so then it could be refreshed instead of restarted.

**Comment by sunnyWangXin** [comment]
Got it, thanks very much @spencergibb @ryanjbaxter
