### ISSUE TITLE
config client read more prop files than expected

### ISSUE THREAD

**Issue by jxplus** [spring-cloud/spring-cloud-config#649]
In my spring cloud config client project, the bootstrap.properties config like that: spring.application.name=demo
spring.cloud.config.profile=test

but when I run, the propertySources loaded two files with "demo-test.properties" and "application.properties". 
This one file "demo-test.properties" is just I want to load yet.

Want to know why load "application.properties"?

**Comment by ryanjbaxter** [comment]
`application.[properties | yml]` is shared between all clients.  Your profiles specific properties file (`demo-test.properties`) will take precedence over the `application.properties`.

**Comment by jxplus** [comment]
ok, thanks a lot.
