### ISSUE TITLE
spring.cloud.bootstrap.enabled=false causing NoSuchBeanDefinitionException

### ISSUE THREAD

**Issue by Vad1mo** [spring-cloud/spring-cloud-config#65]
The config-server is not ment to bootstrap itself by fetching the configuration from localhost:8888. This makes sense because the server in question is being started. So for this reason I wanted to disable the bootstrap process for the config-server. 

```
    public static void main(String[] args) throws IOException {
        System.setProperty("spring.cloud.bootstrap.enabled","false")
        run(Application.class, args)
    }
```

The error I get is this:
```
Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.cloud.config.client.RefreshEndpoint] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
		at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 16 common frames omitted
```

**Comment by dsyer** [comment]
It works for me (and "false" is the default anyway). Can you be a bit more specific about what you did (sample project maybe)?

**Comment by Vad1mo** [comment]
Basically I had a config server and client in one microserver. I was trying to get rid of the config server being an own instance. Maybe this was a not so good idea

```
spring:
  application:
    name: myservice
  groovy:
    template:
      check-template-location: false
  cloud:
    config:
      uri: http://localhost:8884
      enabled: true
      server:
        git:
          uri: ${gitRepoUrl}
          username: ${git.username}
          password: ${git.password}
          basedir: ${git.basedir}

```

**Comment by dsyer** [comment]
Sounds like you mean to use `spring.cloud.config.server.bootstrap=true` then? (It needs to go in the `bootstrap.yml` and you probably need `spring.cloud.config.enabled=false` in `application.yml`.)

**Comment by Vad1mo** [comment]
I forgot to add  `spring.cloud.config.server.bootstrap=true` in my last post But I had that entry. 
The only thing I did different was `System.setProperty("spring.cloud.bootstrap.enabled","false")` because it did had any effect if it was in application.yml because it is loaded after bootstrap.yml and then it is already to late.

**Comment by dsyer** [comment]
If you set `spring.cloud.bootstrap.enabled` then you don't get any config client features, so I don't know what you were trying to do (there's still possibly a bug if you get that exception, but I think it doesn't happen with a normal client that isn't also trying to be a server). Can you explain your use case a bit more?

**Comment by Vad1mo** [comment]
When the client is also the server then the client also tries to bootstrap itself from itself during startup. Thats why there is always a error message (I/O Exeception) during service start saying the the client could not connect to itself. I was looking for a way to get rid of this error message and thought `spring.cloud.bootstrap.enabled=false` would disable the bootstrapping process and not the whole config-client.

**Comment by dsyer** [comment]
Try `spring.cloud.config.enabled=false` (you don't want to disable the whole bootstrap). Example here: https://github.com/spring-cloud-samples/configserver/blob/master/src/main/resources/bootstrap.yml.

**Comment by brenuart** [comment]
@dsyer you said:
> It works for me (and "false" is the default anyway)

Did you meant "spring.cloud.bootstrap.enabled" is FALSE by default? If so, I don't think it is the case - check the following piece of code:
```
public class BootstrapApplicationListener ... {
	@Override
	public void onApplicationEvent(ApplicationEnvironmentPreparedEvent event) {
		ConfigurableEnvironment environment = event.getEnvironment();
		if (!environment.getProperty("spring.cloud.bootstrap.enabled", Boolean.class,
				true)) {
			return;
		}
       ...
}
```

BTW: having the bootstrap feature DISABLED by default would be very nice (!)

**Comment by otrosien** [comment]
.. also already ran into problems with having bootstrap auto-enabled. For example integration tests were reading from the config-server and thus connecting to production databases - not a good thing.

**Comment by dsyer** [comment]
This issue has been closed for months. If you have a new issue please open a new ticket.
