### ISSUE TITLE
How to escape "/" in git branch

### ISSUE THREAD

**Issue by emoshaya-cognito** [spring-cloud/spring-cloud-config#652]
I'm using 

- 1.3.3.RELEASE - spring-boot-starter-parent 
- 1.1.0.M2 - spring-cloud-config-server-1.1.0.M2-exec

Based on documentation http://projects.spring.io/spring-cloud/spring-cloud.html 

 If the git branch or tag name contains a slash ("/") then the label in the HTTP URL should be specified with the special string "(_)" instead (to avoid ambiguity with other URL paths). Be careful with the brackets in the URL if you are using a command line client like curl (e.g. escape them from the shell with quotes '').

Does that mean if my git branch is feature/JIRA-33

I need to start the service with?
```
--spring.cloud.config.label="\"(feature/JIRA-33)\""
```
I get the following warning:
```
WARN 24960 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: {"timestamp":1487944786369,"status":500,"error":"Internal Server Error","exception":"org.springframework.cloud.config.server.environment.NoSuchLabelException","message":"No such label: \"(feature","path":"/inventory-delete-service/%22(feature/JIRA-22)%22"}
```
any idea's?

**Comment by spencergibb** [comment]
You should litteraly replace `/` with `(_)`. So `feature(_)JIRA-33`.

**Comment by emoshaya-cognito** [comment]
@spencergibb Unfortunately, that didn't work 

I started the spring-boot application with --spring.cloud.config.label=feature_JIRA-33

I just replaced the forward slash with underscore. I got the following warning:

WARN 6283 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: label not found

**Comment by emoshaya-cognito** [comment]
@spencergibb ignore my above comment. I forgot to include brackets. It's working now. Thank you!!

**Comment by ryanjbaxter** [comment]
Reopening to clarify documentation

**Comment by emoshaya-cognito** [comment]
providing an example in the documentation would be fantastic
