### ISSUE TITLE
What is the difference between spring cloud config server exec.jar and .jar suffix

### ISSUE THREAD

**Issue by emoshaya-cognito** [spring-cloud/spring-cloud-config#653]
We are currently using spring cloud config server spring-cloud-config-server-1.1.0.M2-exec.jar and would like to upgrade to the latest version. However, i've noticed that beyond 1.1.0.M2 version there's only standard jars and no exec.jar in Maven repo http://maven.springframework.org/milestone/org/springframework/cloud/spring-cloud-config-server/

Could someone please explain what the difference is? Will I be able to just substitute the exec one with the standard non exec one?

Thanks

**Comment by ryanjbaxter** [comment]
Instead of depending on versions directly, we suggest you use the Spring Cloud BOM.  
http://projects.spring.io/spring-cloud/#release-trains

**Comment by spencergibb** [comment]
We decided to no longer ship an executable jar after 1.0.x. `spring-cloud-config-server-X.jar` is a plain library jar. Please create your own executable jar.

**Comment by emoshaya-cognito** [comment]
Thank you for your answers!! I will create my own executable!
