### ISSUE TITLE
S3 backend for config storage

### ISSUE THREAD

**Issue by shahid21st** [spring-cloud/spring-cloud-config#655]
Can you support S3 as a backend for Spring Cloud Config server? Due to some unique corporate restrictions, git can't be used. It would be just like the native profile except the config properties files would be stored in S3. I am thinking what is the best way to do this? One path could be to use an extension of PropertyPlaceholderConfigurer to load configuration from S3 bucket, but want to know your opinion if another approach is better.

**Comment by spencergibb** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-config/issues/654
