### ISSUE TITLE
'spring-cloud-starter-config' causes 'afterPropertiesSet()' to be called twice

### ISSUE THREAD

**Issue by imod** [spring-cloud/spring-cloud-config#663]
As soon as we add `spring-cloud-starter-config`, configuration objects seem to be loaded twice (are at least `afterPropertiesSet()` is called twice.

Here is a small demo project showing the issue: https://github.com/imod/spring-config-load-issue

**Comment by dsyer** [comment]
This is working as designed, although I guess we might be able to change the design if necessary. The second initialization is there in case the Environment changed during context refresh (as happens for instance if things are being decrypted or what not). You can disable it by commenting out the `afterSingletonsInstantiated()` callback here: https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/ConfigurationPropertiesRebinderAutoConfiguration.java#L75.

**Comment by imod** [comment]
sounds reasonable, but very confusing too...
