### ISSUE TITLE
Error rendering YAML configuration files with lists in them

### ISSUE THREAD

**Issue by victor-ferrer** [spring-cloud/spring-cloud-config#665]
Hi, I´m trying to display a YAML file in the server HTML interface and got this error whenever I use a list.

For instance, this YAML:

```
info:
   description: ESPA Microwave Collector

collector:
   batch:
      jobs:
         - name: my_batch_job
           clazz: com.example.myclazz
           query: select  sql here
           parameters:
             - from
             - to

```

Generates this error in the web interface:

```
This page contains the following errors:

error on line 1 at column 425: error parsing attribute name
Below is a rendering of the page up to the first error.
```

However, one important point here, **is that these properties are properly passed to the clients subscribed to this config server**.
Also, if I remove the list part, the rest of the file is rendered just fine (the usual XML format is shown).

I´m using Brixton.SR7

See this StackOverflow question:
http://stackoverflow.com/questions/42362262/can%C2%B4t-use-sequences-lists-in-yaml-with-spring-cloud-config

Cheers,
Victor

**Comment by ryanjbaxter** [comment]
Please try an avoid cross posting issues.

If config clients are receiving the properties properly I am not use why you think this is a problem with the config server.2

**Comment by victor-ferrer** [comment]
Hi @ryanjbaxter,

What do you mean by "cross posting issues"? 

OK, clients are receiving the configuration but the rendering provided by the config server does not work (hence the title of the issue). I agree this is not a critical functionality of the server, but in any case is a part of the server nonetheless (a part that I think is quite useful). Don´t you think?

Thanks!

**Comment by victor-ferrer** [comment]
Mm, I posted it a couple of weeks ago and it has not received much attention, but don´t worry, I will close it if  I get this one closed too :)

Sure, these are two examples of request made on my browser:
- This one works without any issue, as the YAML file called "cem-skpi-consumer.yml" in the Git repo does not contain lists:

http://[...]:8090/admin/config/cem-skpi-consumer/master/master

The resulting XML shown in the browser:
```
<Environment>
<name>cem-skpi-consumer</name>
<profiles>
<profiles>master</profiles>
</profiles>
<label>master</label>
<version>691383a955222aab13a70581404a6f75730a8cb4</version>
<propertySources>
<propertySources>
<name>
https://bitbucket.platform.dev.sdt.ericsson.se/scm/ea/edos-dp-configuration.git/cem-skpi-consumer.yml
```

Then, this one, with the YAML displayed above:
http://[...]:8090/admin/config/cem-skpi-collector/master/master

Shows this error:

```
This page contains the following errors:

error on line 1 at column 406: error parsing attribute name
Below is a rendering of the page up to the first error.
```

I don´t get anything in the process output, though-

**Comment by spencergibb** [comment]
I'm confused about which config server url you are calling. There is no "server HTML interface".

From your comment above it looks like the normal interface the config client calls (though it should return json, not xml).

If I plug the snippet of yaml from your first comment into a repo and run config server I get the following:
```
{
  "name": "haslists",
  "profiles": [
    "default"
  ],
  "label": "master",
  "version": "88ff901bae6830724186dd8a4f7cdaf67443cd8b",
  "state": null,
  "propertySources": [
    {
      "name": "https://github.com/spring-cloud-samples/config-repo/haslists.yml",
      "source": {
        "info.description": "ESPA Microwave Collector",
        "collector.batch.jobs[0].name": "my_batch_job",
        "collector.batch.jobs[0].clazz": "com.example.myclazz",
        "collector.batch.jobs[0].query": "select  sql here",
        "collector.batch.jobs[0].parameters[0]": "from",
        "collector.batch.jobs[0].parameters[1]": "to"
      }
    }
  ]
}
```

So either it's already fixed in a newer version, or it's specific to your application and dependencies.

**Comment by victor-ferrer** [comment]
I pulled the last version and indeed works, It´s weird because now JSON is displayed instead of XML.
Anyway, thanks for looking into this.
