### ISSUE TITLE
NativeEnvironmentRepository doesn't support soft link "property files"

### ISSUE THREAD

**Issue by ddwolf** [spring-cloud/spring-cloud-config#666]
https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/NativeEnvironmentRepository.java#L216

if the property source is a file that soft-linked to the `searchLocation`, then `getCanonicalPath` will return the real location, so at line 216, the if statement will not pass.

Is this the original intention? I suggest using `getAbsolutePath` rather than `getCanonicalPath`.

**Comment by spencergibb** [comment]
I don't see where `getCanonicalPath()` is used. I do see `getAbsolutePath`

**Comment by ddwolf** [comment]
@spencergibb Sorry for the wrong message. now I close this issue:-)
