### ISSUE TITLE
In STS, sleuth causes the compile error: Build path is incomplete. Cannot find class file for org/tmatesoft/svn/core/wc2/SvnOperationFactory

### ISSUE THREAD

**Issue by cesargomezvela** [spring-cloud/spring-cloud-config#667]
Hi,

I have a config server application and all were fine until I added spring-cloud-starter-sleuth which is causing a compilation error:

```
Build path is incomplete. Cannot find class file for org/tmatesoft/svn/core/wc2/SvnOperationFactory
```

the important part of my pom:
```XML
      <dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-amqp</artifactId>
		</dependency>
   		<dependency>
       		        <groupId>org.springframework.cloud</groupId>
        	        <artifactId>spring-cloud-starter-sleuth</artifactId>
   		 </dependency>
	</dependencies>

      <dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Camden.SR5</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

My spring boot version is: 1.5.1.RELEASE

Any help?

**Comment by ryanjbaxter** [comment]
I added those same dependencies to my config server app and did not see a problem, can you provide a sample that reproduces the issue?

**Comment by spencergibb** [comment]
As a GitHub project or a zip file, not as comments

**Comment by cesargithub5** [comment]
Hi,
Thank you for your answers, I created the next git project as an example (a very simple project) 

https://github.com/cesargithub5/ConfigServer

Also, I ask you to see the attached image.

<img width="2048" alt="screen shot 2017-03-14 at 11 16 28 am" src="https://cloud.githubusercontent.com/assets/26411679/23907738/6a7545fa-08a8-11e7-96cd-2b4fe1c1339b.png">

**Comment by spencergibb** [comment]
It builds fine from the command line and intellij, so some problem with eclipse? I'm not an eclipse user, so someone else will need to try it out.

**Comment by ryanjbaxter** [comment]
I tried it in STS and I can reproduce it.  IDK why Sleuth would be effecting this though.  @marcingrzejszczak any ideas?

**Comment by spencergibb** [comment]
Maybe someone from the STS team would have an idea? @kdvolder @martinlippert @BoykoAlex

**Comment by marcingrzejszczak** [comment]
I have absolutely no idea

**Comment by kdvolder** [comment]
I imported the sample project into STS as 'existing maven project' and it has no errors. @ryanjbaxter You said you could reproduce, so could you please elaborate what exactly you did to reproduce it.

**Comment by ryanjbaxter** [comment]
@kdvolder I did the same thing and didnt see any issues, then I cleaned the project and after the rebuild I saw the issue

**Comment by kdvolder** [comment]
Aha, yes. Getting it too now. Interesting, in the problems view in the 'type' column it says its a 'Spring AOP problem' so seems to have something to do with STS AOP support. I'm not that familiar with that part of STS, but it seems the error is coming from that component.

**Comment by kdvolder** [comment]
Here's a workaround. Right click the project and go to

"Properties >> Spring"

Select the "Enable Project Specific settings" checkbox. 

Go to "Project Builders" tab and disable "AOP Reference Model Builder".

My guess is that the AOP reference model builder is running into references to types that a regular compile would not visit, and these types are not on the project classpath, causing that error.

**Comment by ryanjbaxter** [comment]
Thanks @kdvolder.  Is this something we should open an issue for in STS?

**Comment by kdvolder** [comment]
Sure, please do. I'm not yet sure what is the right course of action to address it. But as the error clearly coming from an STS component, we should at least look into it a bit more to diagnose more precisely what causes it.

**Comment by ryanjbaxter** [comment]
@cesargithub5 @cesargomezvela please open an issue for STS [here](https://issuetracker.springsource.com/browse/STS).

**Comment by cesargithub5** [comment]
Thank you for your answers.
I opened the issue. 
You can follow it here:
https://issuetracker.springsource.com/browse/STS-4437

**Comment by martinlippert** [comment]
Thanks for submitting that to the STS issue tracker, we will take a look.

**Comment by kdvolder** [comment]
I could very easily make this error 'disapear' from STS. I.e hide it somehow. However, I'm still trying to figure out if that's really the right thing to do or not (mostly worried about other similar, possibly real errors thereby going missing too).

I've managed to get a longer version of the error message with more infos in it providing a hint to the true cause (indeed something in SC Sleuth). It doesn't tell me much really, but maybe someone here ( @marcingrzejszczak ?)who is more familiar with Sleuth support might make some sense of it:

> Class dependency error 'org/tmatesoft/svn/core/SVNException' occurred on aspect definition 'Aspect definition [/ConfigServer/src/main/java/com/test/conf/Application.java:-1] advise type [after] advise [org.springframework.cloud.sleuth.instrument.scheduling.TraceSchedulingAspect.traceBackgroundThread(org.aspectj.lang.ProceedingJoinPoint)]' while processing bean 'environmentRepository (-1) [org.springframework.cloud.config.server.environment.SvnKitEnvironmentRepository]'. Check if builder classpath is complete
