### ISSUE TITLE
Question-- support for Decryption of password in the url rather than its own property

### ISSUE THREAD

**Issue by nandhusriram** [spring-cloud/spring-cloud-config#670]
I have a url  like this mongodb://user:{cipher}encryptedvalue@hostname:port/, encrypted password is  part of the url and I am running into issue where config server is not sending the decrypted password to client.I do understand defining  password as separate property works instead of embedded url , does spring cloud config supports decryption of password if its defined in the url ?

Thanks

**Comment by spencergibb** [comment]
AFAIK, it's all or nothing. You could put it in it's own property and then reference that property in the url, that is fine.

**Comment by nandhusriram** [comment]
Thanks @spencergibb  you are saying I could do this in my application.properties of the config server
mongodb.password={cipher}encryptedvalue
mongodb.url=mongodb://user:${mongodb.passwordl}@hostname:port/

**Comment by spencergibb** [comment]
That is what I'm saying

**Comment by nandhusriram** [comment]
Thanks
