### ISSUE TITLE
Server does not load application.yml for services beginning with the name application

### ISSUE THREAD

**Issue by mayaswrath** [spring-cloud/spring-cloud-config#673]
I was having problems getting application.yml to load for a my new service which had the name, application-config-server. I was able to track this down to the following line,

In NativeEnvironmentRepository, line 239 in current master

> if (!config.startsWith("application")) {
			config = "application," + config;
		}

This causes any application name beginning with 'application' to not append 'application,' to the value. Consider changing the check to `startsWith("application,") `?

**Comment by spencergibb** [comment]
You mean `application.`? That would rule out `application-<profile>.{yml|properties}` which I don't think we can do. That's an unfortunate name. `config-server` or `config-server-application` might make better sense.

**Comment by mayaswrath** [comment]
Oh yea did't think about the profile suffix. I did change the name, I was more concerned with the many hours of trying to figure out why it wasn't working and how to prevent others from running into it. Maybe just some documentation about not naming something beginning with application would be sufficient.

**Comment by mayaswrath** [comment]
Actually after thinking about some more, my understanding was that, `application` was passed there then that was expanded to `application-<profile>.{yml|properties}` farther down. `config` is populated with the application name.
