### ISSUE TITLE
Placeholders with default values in configuration files

### ISSUE THREAD

**Issue by aleskurlovich** [spring-cloud/spring-cloud-config#675]
Let's imagine next simple configuration file which microservice will use (one line is enough):
test: ${variable:defaultValue}

Expected:
Microservice gets configuration and if variable is not set, it takes 'defaultValue'.

Real behaviour:
Microservice gets configuration and it always gets defaultValue.

When I request manully configuration using REST service, I see 'test: defaultValue'.

Version is org.springframework.cloud:spring-cloud-netflix:1.2.3.RELEASE.

**Comment by spencergibb** [comment]
We do this all over, so you'll need to provide steps to reproduce or a project that reproduces the problem.

**Comment by aleskurlovich** [comment]
Sorry for delay.

Please do next steps:
1. download prototype: [link](https://github.com/aleskurlovich/spring-cloud-issue-test)
2. go to root directory
3. build it: mvn clean install
4. go to target: cd target
5. run it: java -jar config-server.jar --configLocation="file://(or file:/// in Windows)ROOT directory"
6. do HTTP GET request http://localhost:8080/client-service.yml

Expected:
test: ${variable:defaultValue}

Actual:
test: defaultValue

I expect ${variable:defaultValue} because client can be deployed to separate host or container.

**Comment by ryanjbaxter** [comment]
You want the variable to be resolved on the config client?  If so you need to escape the `$` with a `\`.  See the `TIP` in this section http://cloud.spring.io/spring-cloud-static/Camden.SR6/#_spring_cloud_config#_property_overrides

**Comment by aleskurlovich** [comment]
Exactly. Thank you!
