### ISSUE TITLE
Spring Cloud Config client does not match RefreshRemoteApplicationEvent that contains multiple profiles

### ISSUE THREAD

**Issue by kelapure** [spring-cloud/spring-cloud-config#678]
Current Github Repository structure is like so ...

`test-config-server-repo/customerportal/`
-  application.yml	  _WORKS_
-   customerportal.yml _WORKS_
-   application-dev.yml	**NOT WORK**
-   customerportal-cloud.yml	**NOT WORK**
-   customerportal-dev.yml	**NOT WORK**

## NOT WORK

On a change in `customerportal-cloud.yml` property we see the following `RemoteRefreshApplicationEvent` sent by the Spring Cloud Config Server
```
  {
    timestamp: 1490884282070,
    info: {
    signal: "spring.cloud.bus.sent",
    type: "RefreshRemoteApplicationEvent",
    id: "cac63deb-88b4-4762-b225-916eb44a40ff",
    origin: "pcfConfigServer:cloud:0",
    destination: "customerportal:cloud:**"
  }
```  
On the client  / consumer side the application context ID is 
`customerportal:dev,cloud:0`

The client does not get notified of this remote event.

_Notification does not work for any file that has the profile name in it._ 

## WORKS
However when the following files change `application.yml` and `customerportal.yml` are modified the the RemoteRefreshEvent destination `customerportal:**` matched the applicationContextID of `customerportal:dev,cloud:0` and the client/consumer apps are notified.

We have two active profiles for our consumer aka config client apps 
- dev 
- cloud

**Comment by dsyer** [comment]
I don't immediately see how a change in `customerportal-dev.yml` could produce an event with destination profile "cloud". The relevant code is here: https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-monitor/src/main/java/org/springframework/cloud/config/monitor/PropertyPathEndpoint.java#L110. Maybe you can clarify that?

**Comment by kelapure** [comment]
Sorry @dsyer  that was a typo. I edited the issue ... a change in `customerportal-cloud.yml` resulted in an event with the following destination `customerportal:cloud:**`

Our thinking at this point is that the ServiceMatcher in https://github.com/spring-cloud/spring-cloud-bus/blob/master/spring-cloud-bus/src/main/java/org/springframework/cloud/bus/ServiceMatcher.java#L31 is excluding the message.

**Comment by dsyer** [comment]
Yes, I see. It doesn't match one profile if many are active. You can override the matcher as a workaround.

**Comment by dsyer** [comment]
You should open a ticket in spring-cloud-bus I guess.

**Comment by kelapure** [comment]
@dsyer  this is how we worked around the issue https://gist.github.com/kelapure/61d3f948acf478cc95225ff1d7d239c4
