### ISSUE TITLE
unable to to load the git config after push the client application.

### ISSUE THREAD

**Issue by KalyanVudath** [spring-cloud/spring-cloud-config#680]
I am unable to to load the configurations from the git after push the client application.
I have set up the config server in the local and able to load the configuration from GIT in the local client application.

I have created the service instance for config server from market place and then bind-service the client application with client application that i have cf push.

commands that i have used
cf push ConfigClientApplication -p C:\work\STS_03MAR2017\ConfigClientApplication\target\ConfigClientApplication-0.0.1-SNAPSHOT.jar

cf create-service p-config-server standard mConfigServer -c "{\"git\": {\"uri\": \"https://github.com/KalyanVudath/app-config\"}}"

cf bind-service ConfigClientApplication myConfigService

**Comment by ryanjbaxter** [comment]
If this is a problem specific to Spring Cloud Services and PCF you should reach out to support.pivotal.io.
