### ISSUE TITLE
Encrypt properties couldn't be resolved from environment variables

### ISSUE THREAD

**Issue by mkanev** [spring-cloud/spring-cloud-config#684]
1. When I set environment variables (like `ENCRYPT_KEYSTORE_ALIAS`) they are resolved during `KeyCondition` resolution but are not set in `org.springframework.cloud.bootstrap.encrypt.KeyProperties` instance during `TextEncryptor` instantiation in `org.springframework.cloud.bootstrap.encrypt.EncryptionBootstrapConfiguration`. This works only if I explicitly write `encrypt` section in `bootstrap.yml`.
2. Key Management section in Docs says that I should place `encrypt` section in `application.yml` but `EncryptionBootstrapConfiguration` works with `bootstrap.yml`.

**Comment by mkanev** [comment]
Version `1.3.0.RELEASE`

**Comment by ryanjbaxter** [comment]
Just want to make sure I understand what you are doing...

Are you setting `encrypt.keyStore.alias` to `${ENCRYPT_KEYSTORE_ALIAS}` and this does not work when places in `application.properties` but works when places in `bootstrap.properties`?

**Comment by mkanev** [comment]
I can substitute `application.yml` properties with environment variables according to conversion rules (e.g. `SERVER_PORT`). And I can substitute for example Spring Cloud Config Client `bootstrap.yml` properties with environment variables (e.g. `SPRING_CLOUD_CONFIG_NAME` etc.). But I can't substitute encrypt properties in Spring Cloud Config server `bootstrap.yml`.

If I run application with `application.yml` like this:

````
server:
  port: 8888

security:
  user:
    name: root
    # password: 
````

`bootstrap.yml`:

````
encrypt:
  key-store:
    alias: key
    location: classpath:keystore.jks
    password: ${ENCRYPT_KEYSTORE_PASSWORD}
    # secret: 
````

and the following environment variables:

````
SECURITY_USER_PASSWORD=letmein
ENCRYPT_KEYSTORE_SECRET=secret
ENCRYPT_KEYSTORE_PASSWORD=letmein
````

Then application start would fail because keystore secret would be `null`.

Another question about [documentation](https://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_creating_a_key_store_for_testing). It says:

> Put the `server.jks` file in the classpath (for instance) and then in your `application.yml` for the Config Server...

followed by keystore configuration block. But these properties should be placed in `bootstrap.yml` not `application.yml`.

**Comment by ryanjbaxter** [comment]
I am not seeing either problem.  If I take the sample [config server app](https://github.com/spring-cloud-samples/configserver) and move the `encrypt.*` properties from `bootstrap.yml` to `application.yml` I can still encrypt values.  I can also set the environment variable `KEYSTORE_PASSWORD` and it will be used when trying to unlock the keystore (using bootstrap.yml).

**Comment by spencergibb** [comment]
At this point I think we need a sample project that recreates the problem.

**Comment by tipsytopsy** [comment]
@mkanev  - the properties you're using is incorrect for environment variables.. when there is a camel case - spring requires it to be split with an underscore to be able to use as environment variable.

So when you have these variables below, you'll not need to have any declaration of them in your yaml files.

ENCRYPT_KEY_STORE_PASSWORD=letmein
ENCRYPT_KEY_STORE_ALIAS=testalias
ENCRYPT_KEY_STORE_SECRET=changeme

**Comment by mkanev** [comment]
Tat works perfectly fine. Thanks.
