### ISSUE TITLE
spring.cloud.config.discovery.enabled and spring.cloud.config.enabled

### ISSUE THREAD

**Issue by obeyler** [spring-cloud/spring-cloud-config#686]
When I use spring.cloud.config.discovery.enabled=true, must I need to use also spring.cloud.config.enabled=true ?

**Comment by spencergibb** [comment]
No, true is the default for `spring.cloud.config.enabled`

**Comment by obeyler** [comment]
so when just discovery is enabled the application will do his configuration by first retrieve the config service from eureka and to his configuration regarding his profile ?

**Comment by spencergibb** [comment]
@obeyler sorry, I don't understand your question.

**Comment by obeyler** [comment]
Ok I'll try to explain better :-)

I've put into same component named "central-config" an eureka and config server.
eureka url is /eureka
and config server is /config

when I just have in boostrap.properties file for a component such as  "mycomponent" 
```
spring.application.name=mycomponent
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.serviceId=central-config
eureka.instance.metadataMap.configPath=/config
eureka.client.serviceUrl.defaultZone=http://ServeurEureka1/eureka,http://ServeurEureka2/eureka
spring.profiles.active=dev,paris
```

Is It enough to have my application "mycomponent" to discover his whole configuration (mycomponent-dev.properties and mycomponent-paris) on either ServerEureka1/config or ServerEureka2/config ?

**Comment by spencergibb** [comment]
I'm afraid it's still not clear. Where do `@EnableConfigServer` and `@EnableEurekaServer` live? `spring.cloud.config.discovery.enabled=true` means 'lookup config servers that have been registered with eureka.

**Comment by obeyler** [comment]
@EnableConfigServer and @EnableEurekaServer are present into ServerEureka1 and ServerEureka2

**Comment by spencergibb** [comment]
Is it working?

**Comment by obeyler** [comment]
Eureka and Config on same server works well togethers but others component have some difficulties to reach them

**Comment by obeyler** [comment]
In fact the component manage to find the "config-server" from eureka but I don't manage get the configuration of the component as it still look after is configuration at / level instead of /config

I've try to add env 
SPRING_APPLICATION_JSON='{"eureka":{"instance":"metadata-map":{"configPath":"/config"}}}'
as you mention in previous issue that  it doesn't like metadata in env

`INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at: http:/ServeurEureka1.mydomain:10000/`


i suppose I should have
`INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at: http://ServeurEureka1.mydomain:10000/config`

but I don't manage to have it yet.

**Comment by obeyler** [comment]
I succeed ! :-) In fact I used to add this property on component instead of put it on config server instance !
