### ISSUE TITLE
How can I get properties from github repository where the name of configuration file is not "application.properties/application.yml"? 

### ISSUE THREAD

**Issue by zhujiejun** [spring-cloud/spring-cloud-config#696]
I changed the default name of "application.properties"

**Comment by lowzj** [comment]
set `spring.cloud.config.name={your config name}` in your config client bootstrap.properties.

Here is the document: [Locating Remote Configuration Resources](http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_locating_remote_configuration_resources)
