### ISSUE TITLE
Unable to override JschConfigSessionFactory in latest Dalston.RELEASE

### ISSUE THREAD

**Issue by lassounski** [spring-cloud/spring-cloud-config#697]
Hey guys I have an id_rsa key, which I use to connect to GitHub and clone the repo.
This key is located in a custom location `/etc/config-server/id_rsa` which is created by ansible and the key is placed there in bake time. The path to the key is located in `applications.yml` and is injected in the class via @Value.
I have this code in a @Configuration class which I use to replace the default location `~/.ssh/id_rsa`.
```
@Configuration
public class ServerConfiguration {

    @Value("${ssh.key.path}")
    private String sshKeyPath;

    /**
     * Overrides the JGit SshSessionFactory with a customized ssh key path location.
     * This allows the server to connect to GitHub and pull the repository.
     */
    @PostConstruct
    public void postConstruct() {
        SshSessionFactory.setInstance(new JschConfigSessionFactory() {
            @Override
            protected void configure(Host host, Session session) { }

            @Override
            protected JSch getJSch(Host hc, FS fs) throws JSchException {
                JSch jsch = super.getJSch(hc, fs);
                jsch.removeAllIdentity();
                jsch.addIdentity(sshKeyPath);
                return jsch;
            }
        });
    }
}
```
Suddenly that stopped working when I updated to `Dalston.RELEASE`. After a lot of headache I figured out that this was working with `Camden.SR6`.
I debugged the code and realized that when I call an endpoint on the server like `curl localhost:8888/health` the code in `getJsch` method is not invoked.
 Any thoughts on why this happened?

**Comment by spencergibb** [comment]
What "stopped working"? Was upgrading to `Dalston` the only change (ie was there a boot change as well)? Does the `@PostConstruct` get called (have you set a breakpoint there)?

**Comment by lassounski** [comment]
The execution of `protected JSch getJSch(Host hc, FS fs)` stopped working. It's not being called. When I change from `Daltson.RELEASE` to `Camden.SR6`, it gets called.
I have a parent pom.xml like this:
```

**Comment by spencergibb** [comment]
Being called by config server?

**Comment by lassounski** [comment]
Yes, `@PostConstruct gets called`.

**Comment by spencergibb** [comment]
I wonder if this was the cause 405ebad792942c91d1ed60502df5b8cdc5ae7a70

**Comment by spencergibb** [comment]
If so, we'd need to enhance `JGitEnvironmentRepository` to find an optional `SshSessionFactory` bean and use it.

**Comment by ojhughes** [comment]
Hi @lassounski please see https://github.com/spring-cloud/spring-cloud-config/pull/741 I think this new functionality should handle your original use case of specifying a different private key
