### ISSUE TITLE
Is X-Config-Token a secure authentication channel for a config server backed by Vault  ?

### ISSUE THREAD

**Issue by alwaysastudent** [spring-cloud/spring-cloud-config#698]
It seems we will leak the vault token if we store that within the client configs by setting `spring.cloud.config.token`. Is there a best practice for doing this ? Do you suggest we encrypt the same and configure ?  Or do you provide other authentication schemes like [AppRole](http://cloud.spring.io/spring-cloud-vault/spring-cloud-vault.html#_approle_authentication) supported by spring-cloud-vault ?

**Comment by ryanjbaxter** [comment]
I think the best approach would be to encrypt it.  @mp911de any thoughts?

**Comment by mp911de** [comment]
Spring Cloud Config with Vault is an entry-level Vault integration if you don't want to deal too much with Vault and if your client needs to talk to a single server API without the need to adopt Vault's API.

Storing a token in the client config isn't ideal from various viewing angles, but config files are not the only way how to provide config data to an application. You can use system properties/environment properties to pass the token to your application. 

However, storing a static token in the config files can leak. Introducing encryption comes with the chicken-egg problem about decryption key management. Each question in the security space can be answered with another security question that propagates the problem just to another place to be solved.

From my perspective, if your security requirements to not tolerate an access token in a config file, then Spring Vault or Spring Cloud Vault is the tool you're looking for. Extending Spring Cloud Config server to support all auth mechanisms isn't the right approach.

**Comment by spencergibb** [comment]
I don't think you'd store the token in config, you'd read it from a java system property or env var.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
