### ISSUE TITLE
configuration inheritance?

### ISSUE THREAD

**Issue by efenderbosch** [spring-cloud/spring-cloud-config#70]
We have several applications that all use the same database/redis configuration. Is there a way to have the config for multiple apps inherit from a common config? I've looked through the examples and don't see that this is possible.

Something like:

/common.yml
/app1.yml
/app2.yml

common.yml has our spring.datasource and spring.redis config and app1.yml and app2.yml have properties specific to that project.

Apologies if this is available and I've just missed it.

**Comment by spencergibb** [comment]
all apps get the configuration in `application.{yml,properties}`, both `app1` and `app2` would override (or get default) properties from there.
