### ISSUE TITLE
Can you reference a private key on disk for the encrypt.key property

### ISSUE THREAD

**Issue by ulmermark** [spring-cloud/spring-cloud-config#701]
There is an example like such in the documentation:

```
$ spring encrypt mysecret --key @${HOME}/.ssh/id_rsa.pub
```

Can you do the same in the application yml file for the config server like:
```
encrypt.key: '@${HOME}/.ssh/id_rsa.pub'
```

**Comment by ryanjbaxter** [comment]
Did you try it?  Did you find it is not working?

**Comment by ulmermark** [comment]
Yes I tried it and it did not work.

The string used '@${HOME}....." was treated as a normal string and used as
the salt for the encryptor that was created.

**Comment by spencergibb** [comment]
`encrypt.key: ${HOME}/.ssh/id_rsa.pub` should work. Env vars are available to expand.

**Comment by imberda** [comment]
I think the above still gets read as a string. It would be great to get the get from a file instead of a plain string.

**Comment by marcingrzejszczak** [comment]
Is it still a problem with Finchley.RELEASE?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
