### ISSUE TITLE
@Scheduled doesn't work in @RefreshScope (after a refresh)

### ISSUE THREAD

**Issue by tomas0svk** [spring-cloud/spring-cloud-config#703]
If cron interval is configured by a config property, scheduling stops working (invoking) after /refresh is called on that property.

Tested up to spring-boot-starter-parent 1.5.2.RELEASE and spring-cloud-config-client 1.3.1.RELEASE
[mwe.zip](https://github.com/spring-cloud/spring-cloud-config/files/1028805/mwe.zip)

**Comment by ryanjbaxter** [comment]
Please provide a complete working sample in the zip

**Comment by tomas0svk** [comment]
Try this.
Regards
[full_mwe.zip](https://github.com/spring-cloud/spring-cloud-config/files/1031171/full_mwe.zip)

**Comment by dsyer** [comment]
`@Scheduled` doesn't work in `@RefreshScope` (never has done). The `@Scheduled` annotation is processed on startup, and never re-processed.

**Comment by tomas0svk** [comment]
> @Scheduled is never re-processed

Hovewer after that event (see complete scenario in full_mwe.zip) the action being scheduled is never invoked again.

**Comment by spencergibb** [comment]
@tomas0svk the point is, don't use `@Scheduled` on beans that are `@RefreshScope`.
