### ISSUE TITLE
Retrieving both properties and plain files from git repository.

### ISSUE THREAD

**Issue by nachetecanon** [spring-cloud/spring-cloud-config#706]
Hi all, I've made an exhaustive search but couldn't find the appropiated configuration and git repository distribution that allow me to serve both properties and plain files.
My git repository distribution is as follows:

   * basedir of repo (no subdirs, all files are at the same root level):
   * **appname1**_pro.yaml
   * **appname1**_stg.yaml
   * **appname2**_pro.yaml
   * **appname2**_stg.yaml
   * file1.txt

I'm able to use the properties of application1 and application2 with both profiles (pro and stg) in the standard way described at [official doc](http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_environment_repository).

But for me is not very clear the way I could get the plain text of _file1.txt_ from spring code, nor **curl** way, and how can I associate _file1.txt_ to _appname1_ or _appname2_.

And more important for me, how I should place at git repository and access from rest api or from application to different profiles (versions) of file1.txt.

I've tried to.
  * git base dir
     * file1_pro.txt
     * file1_stg.txt

Like _pro_ and _stg_ being different profiles of file1, and accessing them by 
   
   ```
curl http://localhost:8080/appname1/pro/master/file1.txt --> 404

   curl http://localhost:8080/appname1/pro/master/file1_pro.txt --> 404

   curl http://localhost:8080/appname1/default/master/file1.txt --> 404
```

I've even tried with subfolders inside git, but with no success, official doc does not show the case of several versions of the plain text files and how are them placed from root of git repo, and I'm not sure if I should use only one _file1.txt_ with placeholders inside... 

Please help me, I couldn't found any example...!

My configuration in cloud server is:

```
spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://git@52.17.154.1/icanon/apps_configuration-git.git
          username: icanon
          password: *****
``` 
Maven dependencies:

```
       <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-server</artifactId>
            <version>1.3.0</version>
        </dependency>
    
```

Thank you in advance and best regards.

**Comment by spencergibb** [comment]
Running a config server and pointing at https://github.com/spring-cloud-samples/config-repo/
Both
http://localhost:8888/foo/default/master/text-resource.txt
and 
http://localhost:8888/foo/default/master/subdir/test.txt
serve plain text files

This is the section on serving plain text http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_serving_plain_text

Serving plain text does not append the profile like it does for serving config files.

**Comment by spencergibb** [comment]
files aren't associated with an appname and profile, those are used for placeholder expansion.

**Comment by spencergibb** [comment]
Actually, looks like you can have a file per profile with `file-profile.ext`.

**Comment by nachetecanon** [comment]
Thank you for your answer @spencergibb !
I've been working on my own implementation of JGitRepository in order to provide rsa key files by configuration and not searching at ~/.ssh of the machine. Seems that I missed something, and reverting my changes make your endpoints work.
So I will have to take a deeper look to my customization, because seems that the fault of the missbehaviour is mine.

Thank you so much!
