### ISSUE TITLE
Retrieve properties description through Spring Config API

### ISSUE THREAD

**Issue by ismarslomic** [spring-cloud/spring-cloud-config#709]
I would like to include description of some properties directly in the configuration file (.properties / .yaml), as comment or similar, and be able to retrieve it through Config Server API (.properties/.yaml/JSON/plain text).

Is this possible?

**Comment by ryanjbaxter** [comment]
I don't think so, comments are ignored when processing the files.

**Comment by spencergibb** [comment]
Spring Boot has facilities for getting descriptions of properties from `@ConfigurationProperties` when metadata is generated. You could always have another meta property that lists descriptions.
