### ISSUE TITLE
how one service write infor to config server

### ISSUE THREAD

**Issue by hysGitHub** [spring-cloud/spring-cloud-config#710]
eg: one service instance write his infor to config server get 3Q

**Comment by ryanjbaxter** [comment]
Please provide more details on what you are trying to do.  Generally configuration is stored in a backend service (git, svn, valut, etc) and is not changed by services.

**Comment by hysGitHub** [comment]
my english is  poor,the  first  time  i  ask  so sorry. @ryanjbaxter . I have  Many app.  every app need some Micro service.i  want  one  app use  its Micro services.so i create  one docker what manage one app service.so  i want to  push  yml and  docker setting to git config  so that    one app can strong run.

**Comment by ryanjbaxter** [comment]
No problem. 

The configuration (properties or YAML) can be stored and git and served to the microservice using the config server.  However the docker settings cannot be served from the config server.

**Comment by hysGitHub** [comment]
@ryanjbaxter i donnot find the code where the  code can write  yaml to  push config  in the  project.i just write  some  code  that  can  push  to  git and now   i  can  simply  create  the docker by restful  api.

**Comment by ryanjbaxter** [comment]
The application will automatically make a request to the config server to get the configuration when it starts up.  You can cause the application to update its configuration by making a request to the `/refresh` endpoint.  There is also an option of informing the application that its configuration has updated.

If you want the application to update the YAML in Git for example than you need to do that yourself.  Spring Cloud Config does not provide APIs to do that.

**Comment by hysGitHub** [comment]
@ryanjbaxter tanks  verery much
