### ISSUE TITLE
folder /tmp/config-repo-* 755 permissions for git provider

### ISSUE THREAD

**Issue by golonzovsky** [spring-cloud/spring-cloud-config#711]
Temporary folder for git repository is created with 755 permissions.

```
$ ls -lah /tmp | grep config
drwxr-xr-x  3 alex alex 4.0K Jun  4 10:09 config-repo-4473973272322238678
```

It would be nice to have it 700.

The folder is initially created with 700 by [AbstractScmAccessor#L94](https://github.com/spring-cloud/spring-cloud-config/blob/b68a3eba6be85f5b8c1d9d9735369a1d713cc7de/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/AbstractScmAccessor.java#L94), but later deleted and recreated with 755 permissions by [JGitEnvironmentRepository#L366-L367](https://github.com/spring-cloud/spring-cloud-config/blob/b68a3eba6be85f5b8c1d9d9735369a1d713cc7de/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepository.java#L366-L367)

Maybe instead of deletion - baseDir cleanup would be sufficient

**Comment by spencergibb** [comment]
Why would 'It would be nice to have it 700.'?

**Comment by golonzovsky** [comment]
With 755 content of checked out git folder will be visible to all users/processes on same linux box. It could be private git repo with some sensitive information.

**Comment by spencergibb** [comment]
I'd suggest setting the `basedir` attribute, then you control access to the parent directory rather than a temp dir.
