### ISSUE TITLE
Logback FILE appender doesn't work with defined logging.path in configuration server

### ISSUE THREAD

**Issue by belon** [spring-cloud/spring-cloud-config#713]
I tried to configure FILE appender using config server but it doesn't work as I expected.

Config server contains application.yaml file with property `logging.path: '/tmp'`.

Application has logback-spring.xml file:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <property name="LOG_FILE" value="${LOG_PATH:-/other}/spring.log"/>

    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <include resource="org/springframework/boot/logging/logback/file-appender.xml"/>

    <root level="INFO">
        <appender-ref ref="FILE"/>
    </root>

</configuration>
```

When application startup before loading properties from config server all logs go to `/other/spring.log` file. After load properties from config server logs go to proper directory `/tmp/spring.log`.

The problem is that I cannot specify default value on production.
Is it possible to initialize appender after load properties from config server?

**Comment by ryanjbaxter** [comment]
I don't know there is much we can do to hold off the appended from being initialized.  Logging to file is not something we would recommend for cloud apps anyways.  If you find a solution that works for you please let us know.

**Comment by hairinwind** [comment]
For cloud apps, what is your suggestion for logging? Thanks
