### ISSUE TITLE
Property source ordering incorrect if env var spring_profiles_active overlaps with requested profiles

### ISSUE THREAD

**Issue by imberda** [spring-cloud/spring-cloud-config#714]
The issue relates to the ordering of the returned property sources when using the native repository and the profiles of the server itself overlap with the profiles requested via REST. 

For example suppose you have the following configuration files within the `spring.cloud.config.server.native.search-locations` directory:

* application.properties
* application-dev1.properties
* service1-dev1.properties
* service1-dev2.properties

Then if you start the Spring Cloud Config Server with the `native` profile enabled and issue the following command:

```
curl http://localhost:8080/service1/dev1,dev2|jq .propertySources[].name
```
You should (and do) get the following results:

```
"file:config-files/service1-dev2.properties"
"file:config-files/service1-dev1.properties"
"file:config-files/application-dev1.properties"
"file:config-files/application.properties"
```
However if you start the config server and set environment variable `spring_profiles_active` to include a profile also included in the `curl` request:

```
spring_profiles_active=dev1 mvn spring-boot:run
```
When you issue the curl request above you actually get the following results:

```
"file:config-files/service1-dev2.properties"
"file:config-files/application-dev1.properties"
"file:config-files/service1-dev1.properties"
"file:config-files/application.properties"
```

Notice that `application-dev1.properties` appears before `service1-dev1.properties`.

Interestingly the issue only seems to occur when the environment variable `spring_profiles_active` is set with a profile which overlaps with a profile supplied on a REST request. 

Moreover the issue does NOT occur if the environment variable is set using uppercase (i.e. SPRING_PROFILES_ACTIVE) or as a system property (i.e. `-Dspring.profiles.active=dev1`). So either of the following server start commands will NOT have the same problem:

```
SPRING_PROFILES_ACTIVE=dev1 mvn spring-boot:run
```
```
mvn spring-boot:run -Dspring.profiles.active=dev1
```

I've created a [sample repository](https://github.com/imberda/spring-cloud-profile-ordering-bug-example) which can be referenced to easily reproduce the described problem.

**Comment by marcingrzejszczak** [comment]
Is it still a problem with Finchley.RELEASE?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
