### ISSUE TITLE
Question : spring cloud config client deployed as war does not read boostrap.properties

### ISSUE THREAD

**Issue by yinan-liu** [spring-cloud/spring-cloud-config#715]
I got a question please.
I have both config server and config client deployed as war in jetty server. It seems the client is not reading the bootstrap.properties while being deployed. Any advise please ? thank you very much in advance

**Comment by ryanjbaxter** [comment]
You specifically mention that you are packaging the app as a war, do you have the same problem when you package the app as a jar?  Can you perhaps provide a sample that reproduces the issue?

**Comment by yinan-liu** [comment]
I firstly tried with this sample project(https://github.com/spring-guides/gs-centralized-configuration), config server and config client are running as a jar, it is working well. Then I tried to copy paste the config properties, etc. into our project. 

Basically, we package the spring boot projects as war and put them in a folder, we config and start the jetty server programmatically, all war files in this folder are going to be read by jetty and be deployed in jetty. The config server webapp seems working fine, as when i check the "/env" endpoint, everything seems ok. The config client doesn't work, because it uses the properties values in the src/main/resources/application.properties, not the centralized ones. When i tried to read  spring.cloud.config.uri and spring.application.name properties (they are defined in bootstrap.properties), their values are null.  

Then I read that the these properties could be also defined as environment variables, so i try to put them into web.xml (as the application is deployed as war), now i can read their values correctly from endpoint, they are initialized like
`@Value(${spring.cloud.config.uri})` in the controller, but the other properties values are still not good.

I will try to setup a sample, but it will take a little time i think. Thank you.

**Comment by yinan-liu** [comment]
Is there anyway else to ask a spring boot project load the bootstrap.properties?

**Comment by ryanjbaxter** [comment]
Do you have the correct dependency on the classpath?
```
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-config</artifactId>
</dependency>
```

**Comment by yinan-liu** [comment]
yes, i do. and since we still use the spring boot 1.3.3, i use the starter config version 1.2.0.RELEASE for the compatibility

**Comment by ryanjbaxter** [comment]
A sample that reproduces that problem would be useful at this point.

**Comment by yinan-liu** [comment]
yes, i will try to make a sample, thx

**Comment by yinan-liu** [comment]
Hi Ryanjbaxter

I managed to create a sample to reproduce the issue i have. Here below is the github link
https://github.com/yinan-liu/spring-cloud-issue/tree/master
the readme explains the project a bit. So to reproduce the issue, simply run the command to start the jetty server, the war files are already in the dist/war folder and will be deployed during the start process. You can change the configuration-service 's application.properties to change the searchLocation for sure, and then if you check the message endpoint of the configuration-client webapp, the message value is the default one, not the one from the centralized properties file

**Comment by yinan-liu** [comment]
can you confirm you can get the project and can reproduce the issue please. Thank you so much

**Comment by ryanjbaxter** [comment]
I was able to run the sample and see the problem, but I can't build `configuration-client` locally using Maven or Gradle.  Can you please look at that?

**Comment by yinan-liu** [comment]
sorry about that, i simply removed the test class, they are not useful to show the issue. You can pull and rebuild now. 
Thank you !!

**Comment by yinan-liu** [comment]
any finding please ?

**Comment by ryanjbaxter** [comment]
Sorry I have been busy with other tasks.  It is on my list to look at when i get a chance.

**Comment by dsyer** [comment]
@yinan-liu you seem to be using `ContextLoaderListener` in your apps, so Spring Boot is not being used to start the context. If you follow the normal process and remove your web.xml it should work. More details here: https://spring.io/guides/gs/convert-jar-to-war/ or here: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-traditional-deployment.html.

**Comment by yinan-liu** [comment]
@dsyer thank you for your reply, i am trying to do the change and see. I will let you know.

**Comment by yinan-liu** [comment]
@dsyer i removed the web.xml from both client and server. But it still does not work, no matter they are deployed in the jetty server included in the project, or a standalone tomcat server. 
The project was updated https://github.com/yinan-liu/spring-cloud-issue/tree/master, but the war files in the dist/war are not updated, so if you would like to reproduce the issue, you need to build the project to have the war.
Thank you very much

**Comment by dsyer** [comment]
The jetty server from the README is not starting up properly for me (the wars are not Spring Boot apps anyway, so I guess you started Jetty the wrong way or something). And you have hard-coded paths to your local file system in the config files, so nothing will work for anyone else locally. Also you are using _really_ old versions of spring boot. Why not upgrade, align the Spring Cloud version, try again, and then come back if it is still a problem?

**Comment by dsyer** [comment]
I changed the git config location inside the configserver war and it all worked fine for me in a standalone Tomcat (the configserver is secure and the client doesn't have the password, but that's expected). Can you please explain what you see that is unexpected?

**Comment by yinan-liu** [comment]
i am using old version, because my company has legacy projects using this old version, i have to make sure with this version, we can make it work. I checked the version compatibility and that's why i use the spring cloud version 1.2.0. I can test again with standalone tomcat. What i expected is that i put an application.properties in the config location defined in the server, with a different message value from the default one in the code. When i had them deployed, i checked the rest url to read the message, the value was the default one, not the one in the config location.

**Comment by yinan-liu** [comment]
configserver is secure and the client doesn't have the password ? i set management.security.enabled=false for configserver, so you mean it is secured by tomcat ? i will check that

**Comment by dsyer** [comment]
`management.security.enabled=false` only applies to the actuator endpoints. I think this is working as designed.

**Comment by yinan-liu** [comment]
@dsyer i cannot make it work yet with native profile having the properties files in disk not in the cloud, why you close this ? can you confirm that if you change the message value, you can have the same from the configclient rest endpoint ?

**Comment by dsyer** [comment]
I closed the issue because it relates to the bootstrap configuration in a deployed war. There is nothing that suggests to me that this is not working.

**Comment by yinan-liu** [comment]
but the fact is it does not work, that's why i created a sample in github so that you can reproduce or at least give me some advice on it. Your colleague @ryanjbaxter even confirmed that he can reproduce the issue. And you said you change the git config location, did you use git repository or a path in the disk. All the sample cloud projects on the internet are using jar, not war. I dont know how to find a solution if i cannot get help from you guys. very upset

**Comment by dsyer** [comment]
It works for me. I couldn't use the Jetty launcher you provided, but I deployed your wars to 2 tomcat instances and they both worked fine (with local and remote server config, using git and native profiles).

**Comment by yinan-liu** [comment]
it is not working for me when i deployed them in tomcat. thx

**Comment by dsyer** [comment]
It won't work if you deploy them both to the same tomcat instance - the client needs the server to be running before it can start cleanly.

**Comment by yinan-liu** [comment]
yes, you are right. I thought about this point, that's why i named the server project as application-config, as it starts with 'A', it will be deployed at first. But yes, if the tomcat server is not started completely yet,  the application is still not available to be used even it got deployed. Thank you very much.

**Comment by Dirk2018** [comment]
hi, i had the same problem when i moved the example from jar to war and deployed it to a standalone tomcat. 
i solved the issue by adding the application root from the config server to the bootstrap.properties entry.
In my case i changed 
spring.cloud.config.uri=http://localhost:8888/
to
spring.cloud.config.uri=http://localhost:8888/configuration-service/
perhaps this helps :)
