### ISSUE TITLE
Question：How could I refresh properties to Environment when local file backend changes.

### ISSUE THREAD

**Issue by regardfs** [spring-cloud/spring-cloud-config#716]
all: In my env, all configurations store in localfile，so my service configuration file stores in classpath:/.

So, when files in classpath:/ changes, needing refresh on the fly to provide latest properties, I need automatically refresh all values, How could i fulfill this demand?

Here is my configuration:

**application.yml**

> 
    
    endpoints:
        restart:
            enabled: true
        refresh:
            enabled: true
     spring:
        cloud:
           config:
              server:
                 native:
                     searchLocations: classpath:/
      etcd:
          conn:
             etcdPassword: 134
             etcdUrls:
             - http://localhost:2379
           etcdUsername: root
           enabled: true
           etcdServicePrefix: /congiguration/gaia/
           enabled: true
           timeout: 1
      
**entrypoint**

> @RefreshScope
   @Configuration
   @EnableAutoConfiguration
   @SpringBootApplication
  @RestController
public class EtcdTempTest {
@RequestMapping("/")
String home() {
    return "Hello World!";
}
@Value("${etcd.conn.etcdPassword}")
private String value;
@RequestMapping("/sayValue")
public String sayValue() {
    return value;
}
public static void main(String[] args) {
    SpringApplication application = new SpringApplication(EtcdTempTest.class);
    application.run(args);
}
}

It could print "134" when visit http://localhost:8000/sayValue/ in browser, but when i changed **etcdPassword** in **application.yml**, and curl -X POST  http://localhost:8000/refresh, it returned [] , thus could not refresh when application.yml changes.
How could i fulfill this demand?
Here is the url of SOF: [stackoverflow](https://stackoverflow.com/questions/44490664/spring-cloud-config-automatically-refresh-all-values-on-the-fly )

**Comment by regardfs** [comment]
Furthermore, ConfigurationProperties does not support yaml file, how could i pass properties in yaml file into Environment?

**Comment by regardfs** [comment]
Did spring-cloud-config support local-file backend refresh??????

**Comment by ryanjbaxter** [comment]
Please dont post in multiple locations.  I am going to close this and comment on your SO post.

**Comment by regardfs** [comment]
@ryanjbaxter hi, sorry for violating the issue rules，just because I had post one question someday ago , but none response... 
here is my question on SO  [https://stackoverflow.com/questions/44490664/spring-cloud-config-automatically-refresh-all-values-on-the-fly](https://stackoverflow.com/questions/44490664/spring-cloud-config-automatically-refresh-all-values-on-the-fly)

**Comment by regardfs** [comment]
@ryanjbaxter, Sorry to @u here, cause I am waiting for the answer ,does /refresh endpoint support local file backend? if no, I will figure out other workaround
