### ISSUE TITLE
Option to clone git submodule at start ? 

### ISSUE THREAD

**Issue by adelcourt** [spring-cloud/spring-cloud-config#717]
At start of the server, when git repository is clonned,  submoduler are not cloned / updated.

I havent find any option to   send  "--recussive"  option for git clone.  
Does the option exist ?
Do you have a way to clone the submodules ?

**Comment by ryanjbaxter** [comment]
I don't believe so.  This is a concept specific to git and not other backends so I dont think we have a way to do that.

**Comment by adelcourt** [comment]
it's seems that jgit have an option to clone Submodule ; http://download.eclipse.org/jgit/site/4.7.1.201706071930-r/apidocs/org/eclipse/jgit/api/CloneCommand.html

**Comment by ryanjbaxter** [comment]
Right, but the config server supports other backends besides git (SVN, filesystem, Vault).  That concept doesnt translate to those backends.

**Comment by spencergibb** [comment]
I think this would be an enhancement specific to git. We already have a `cloneOnStart` option that is specific to git.

**Comment by mkkeffeler** [comment]
this MR fixes our issue as well, would be a huge addition.

**Comment by spencergibb** [comment]
This is now an option `spring.cloud.config.server.git.clone-submodules=true`.
