### ISSUE TITLE
config.client.version no longer in Dalston

### ISSUE THREAD

**Issue by fecogc** [spring-cloud/spring-cloud-config#718]
I was using Camden.SR7 on my Spring Cloud Config Server and there's a config.client.version and it changes everytime the properties get refreshed.

{"name":"application.properties","profiles":["master"],"label":"master",**"version":"9ad0fd174feb0cdbc5ab73753e64be061af2ba3b"**,"state":null,"propertySources":[]}

But on Dalston, the version is null, is this a feature or a bug?

**Comment by ryanjbaxter** [comment]
This is a bug introduced when we started supporting composite environments repositories.

**Comment by ryanjbaxter** [comment]
FYI I created issue #720 to perhaps mover version to the property source level.
