### ISSUE TITLE
alternative to fail fast

### ISSUE THREAD

**Issue by Vad1mo** [spring-cloud/spring-cloud-config#72]
We start all the container and services at the same time. So it happens that some container that depend on a configuration from the config-server need to be refreshed after they started. In our case it is a manual work. 

It would be handy if there was an additional option in config client. Something like "retryBeforeFail" = 10 so it would retry to fetch the config 10 times with a 2 seconds pause and if in that time config-server is still not up and running the client would fail to start. 

if this feature is desired we can make contribution.

**Comment by roykachouh** [comment]
@dsyer Do you think utilizing the `RetryTemplate` in spring-retry (https://github.com/spring-projects/spring-retry) inside the `ConfigServicePropertySourceLocator` will make sense here?  If so, I can take a shot at implementing.

**Comment by dsyer** [comment]
Yes that's the way I would have done it. Open question is whether to make retry a mandatory dependency.

**Comment by Vad1mo** [comment]
nahh don't make it mandatory. Nobodys likes dependencies if they don't use them.

I would do a fail fast with property `spring.cloud.config.retry=true.` If there is no dependency available on start fail fast and tell the user that spring-retry  is needed.

**Comment by roykachouh** [comment]
An interesting hurdle that I'm facing is the fact that the `PropertySourceBootstrapConfiguration` is an `ApplicationContextInitializer` that executes both for the client and the server.  Is that the intent? It seems strange that the server tries to initialize a `CompositePropertySource` with itself as the backing config store.  Is there a clean way to delineate server bootstrap from client bootstrap?

**Comment by dsyer** [comment]
That was the intent. The server might want to be a client (i.e. pick up configuration from external sources). I suppose the problem is that it can never contact itself in its own bootstrap phase, so the fail fast flag doesn't make any sense for the server?  We could add a flag (or some logic) to disable the `ConfigServerProeprtySourceLocator` I guess, but I think the `PropertySourceBootstrapConfiguration` has to run.

**Comment by dsyer** [comment]
Should have been closed with #90. Fully supported now since 1.0.1.

**Comment by rubesMN** [comment]
Can someone describe how to use this?  I added spring-retry and behavior did not change.  I see from the code that a new config property retryBeforeFail is available -> tried setting to true (into bootstrap.yml) to no avail.  Combined it with failFast and just the failFast behavior works as it did.   I'm on 1.0.2 spring cloud.

**Comment by dsyer** [comment]
Is this for the config server (see notes above explaining why that doesn't have retry) or the client?

**Comment by rubesMN** [comment]
This is for the client.

**Comment by rubesMN** [comment]
So, could someone document how this works from the config client perspective?   Spent some further time on this and spring.cloud.config.retryBeforeFail has no affect.  @roykachouh - is this intended to be functioning?

**Comment by dsyer** [comment]
Works for me. Did you compare with the sample in spring-cloud-samples/tests?

**Comment by rubesMN** [comment]
The problem I had was lack of information outside of inspecting code.  I see now that my pom needed spring-boot-starter-aop, spring.cloud.config.failFast was required to be defined as true, spring-retry needed to be in the pom, and a Bean of type RetryOperationsInterceptor needed to be created (or corresponding properties in bootstrap).  Hope others benefit as I think this is the Doc now I suppose.

**Comment by dsyer** [comment]
For anyone else who is reading this thread, please go to #199. Next time, @rubesMN, please note that the best way to make a change is to suggest it in a feature request (where any uncertainty can always be debated before committing actual code), and if possible a pull request.

**Comment by juanwalker** [comment]
I configured fail fast for spring cloud configuration cliente well following the properties approaching take a look to #358
