### ISSUE TITLE
Error deploying two config clients in one container

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-config#73]
Each war tries to register 'org.springframework.cloud.context.environment.EnvironmentManager' in jmx but there should be only one.

Spring cloud version - 1.0.0.RC1

Refer below link for details:
http://stackoverflow.com/questions/28197414/spring-cloud-error-deploying-two-eureka-clients-in-one-container

Reported by @vibhaanshu https://github.com/spring-cloud-samples/eureka/issues/8

**Comment by dsyer** [comment]
I don't think this is a Spring Cloud question - it's just a feature of Spring Boot and JMX. You can set `spring.jmx.default-domain` to something different in each application or provide your own `ObjectNamingStrategy` or your own `@EnableMBeanExport` (with a unique `defaultDomain`).

**Comment by vibhaanshu** [comment]
Thanks, dyser. One observation..

In file ```https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/EndpointMBeanExportProperties.java``` property is ```${spring.jmx.default_domain:}``` instead of ```${spring.jmx.default-domain:}```. 

Can you please have the docs updated..

**Comment by dsyer** [comment]
Which docs? Actually that's a bug I think (it should be "-" everywhere). In any case can you raise an issue in Spring Boot, please? But maybe you can set `endpoints.jmx.domain` to fix your problem?

**Comment by vibhaanshu** [comment]
I tried with ``` endpoints.jmx.domain```, but it did not work. For now using ```spring.jmx.default_domain```
