### ISSUE TITLE
[Question] How to broadcast refresh through all clients without webhook

### ISSUE THREAD

**Issue by regardfs** [spring-cloud/spring-cloud-config#733]
I read the note from [Spring-cloud-config](http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_push_notifications_and_spring_cloud_bus)
> the default configuration also detects filesystem changes in local git repositories (the webhook is not used in that case but as soon as you edit a config file a refresh will be broadcast).

Does this mean no dependency of **spring-cloud-config-monitor** and no /endpoint of **/monitor**, just enable and config rabbitmq info it will refresh all spring-cloud-config client?
But indeed, it would not work..
Could u guys show me an example of how to fulfill this scenario??
Thanks a lot

**Comment by ryanjbaxter** [comment]
Have your tried adding spring-cloud-bus and spring-cloud-monitor to the classpath?  Does it work then?

**Comment by regardfs** [comment]
@ryanjbaxter 
hi, Sure, it works, I followed this page [asimio's toturial](http://tech.asimio.net/2017/02/02/Refreshable-Configuration-using-Spring-Cloud-Config-Server-Spring-Cloud-Bus-RabbitMQ-and-Git.html) and everything goes fine
when I saw the official site Note about absence of webhook of git, I want to use this pattern cause I have many repos for huge of projects, it is not a best practice for configure webhook on these repos.

> the default configuration also detects filesystem changes in local git repositories (the webhook is not used in that case but as soon as you edit a config file a refresh will be broadcast).

**Comment by regardfs** [comment]
@ryanjbaxter 
Does this **default configuration** means removing webhook  only?

**Comment by ryanjbaxter** [comment]
So you are editing the file in your local git repo and not seeing a refresh event broadcasted?

**Comment by regardfs** [comment]
@ryanjbaxter yes，so I posted a issue and question here.
Here is my configurations:

> application.yml
```
spring:
  cloud:
    config:
      server:
        git:
          uri: http://192.168.100.22/devops/spring-cloud-configs.git
          search-paths: test1/
          username: leo
          password: 1366662Ti
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: config-monitor
server:
  port: 8003
```
> bootstrap.yml
```
spring:
  application:
    name: configurations``


> and dependencies same as official

```
                 <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-monitor</artifactId>
			<version>1.3.1.RELEASE</version>
		</dependency>
                <dependency>
                       <groupId>org.springframework.cloud</groupId>
                       <artifactId>spring-cloud-starter-bus-amqp</artifactId>
                       <version>1.3.1.RELEASE</version>
                </dependency>`

When config web hock as http://192.168.100.201:8003/monitor, everything goes fine, when remove hook, could not refresh

**Comment by regardfs** [comment]
@dsyer, might u cc this issue？
I have hacked spring-cloud-bus and  found  it use this class RefreshRemoteApplicationEvent to refresh.

**Comment by spencergibb** [comment]
There is no way to broadcast refresh requests without `/monitor` or by triggering a manual refresh using `/bus/refresh` unless you code something by hand.

**Comment by regardfs** [comment]
@spencergibb , Yeah I saw the code, I try to make a curl request to simulate the request to monitor like 

> curl -v -X POST "http://localhost:8003/monitor" -H "Content-Type: application/json" -H "X-Event-Key: repo:push" -H "X-Hook-UUID: webhook-uuid" -d '{"push": {"changes": []} }'

**Comment by regardfs** [comment]
@spencergibb 
I have finish this task with urlconnection and simulate the request above.
Thanks all you guys, I will close this question.
