### ISSUE TITLE
the Git repository file is the .json suffix，spring cloud config client don't access the xxx.json file by spring cloud config server

### ISSUE THREAD

**Issue by xiaochangg** [spring-cloud/spring-cloud-config#736]
1.If the Git repository file is the .json suffix (as xxx.json)，not .yml or .properties suffix. The spring cloud config server can be accessed through the url (http://localhost:8888/application/default/master/xxx.json),
But How should the spring cloud config client access the spring cloud config server to get the xxx.json file content ?
2. How should a spring cloud config client access the Multiple Files（.json suffix）?

Thank you very much

**Comment by spencergibb** [comment]
The config client does not have any mechanism to get files, like a .json file.

**Comment by xiaochangg** [comment]
But the config server can get files content by browser. Can it be done by some way in config client？spring cloud config Only support the config client access the .yml or .properties by @Value("key") ?

**Comment by spencergibb** [comment]
You can use `@Resource("<urltofileinconfigserver>")`

**Comment by shouwangqing** [comment]
@xiaochangg  have you solved the muliple file now?

**Comment by marcingrzejszczak** [comment]
Is it still a problem with Finchley.RELEASE?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
