### ISSUE TITLE
Should we use multiple repositories or one repository with multiple branches per environment?

### ISSUE THREAD

**Issue by jaaduda** [spring-cloud/spring-cloud-config#738]
We have started exploring using Spring Cloud Config along with Zuul and Eureka in our environment.

I understand we can have multiple profile files maintained in a repository and based on the environment spring cloud config will provide the right configuration

What I want to know is  what is the recommendation from config team for creating repositories when using across environments like DEV,QA,STAGING and PROD.

Should we create separate repositories for each environment or use a single repository with per branch per environment.

I am not sure which one would make it easier to promote configuration when moving from one environment to another. Either way I believe there would be the manual work of merging the configurations.

I am not sure if there is a process to seamlessly move the configuration across the environment with less effort, whenever code is promoted to next higher environment.

Can you please provide me your recommendations  on this.

**Comment by spencergibb** [comment]
Any of the strategies will work. It depends on you CI/CD requirements (how does config get into production) and security requirements (ie don't let devs change prod).

**Comment by repos-jmp** [comment]
We have adopted the strategy of having dev, qa, staging in a single repository accessible to anybody logged in. Prod & DR are separate repos, accessible only to members of ops and principal dev.
Having a single repo with `application-environment-label` for non critical environments made most sense to us due to ease of use.
