### ISSUE TITLE
How to fetch properties in a client app which is connecting to a spring config server with composite backend (git and vault) 

### ISSUE THREAD

**Issue by sundarsrini** [spring-cloud/spring-cloud-config#743]
I am using spring-cloud-starter-config in my client app to bootstrap. I am currently facing could not resolve placeholder exception when I autowire a property. 

But I am able to get those values from the config server if only git profile is made as active. 

Below is my application.properties for the config server

spring.cloud.config.server.git.uri=/Users/Sundar/Desktop/config
spring.cloud.comfig.server.git.clone-on-start=true 
spring.profiles.active=git,vault
spring.cloud.config.server.git.order=1
spring.cloud.config.server.vault.order=1

**Comment by spencergibb** [comment]
Why did you set the order to the two repositories the same? This is in effect random.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
