### ISSUE TITLE
Are there any REST endpoints to update/delete existing properties in backend system through cloud config server ?

### ISSUE THREAD

**Issue by sujeet100** [spring-cloud/spring-cloud-config#744]
I would like to update/delete properties in backend system (git/subversion) directly through config-server REST api (instead of making commits through git/subversion).
Are there any REST api to achieve this?
If not, is there any specific reason for not supporting it?

**Comment by spencergibb** [comment]
It has been a non-goal of this project from the beginning. I think getting the write semantics across git/svn/vault would be difficult.

**Comment by spencergibb** [comment]
This is something we are not going to add at this time.
