### ISSUE TITLE
Restrict property visibility

### ISSUE THREAD

**Issue by ChrisCavegn** [spring-cloud/spring-cloud-config#745]
Hi

In my szenario, there are multiple Applications/Microservices which should be configured by spring cloud config. Each of these Applications requires some properties containing sensitive data (usernames, passwords).
The applications will access the config server with a separate user. Is there a way to restrict the properties a user is allowed to read? (The user A should be able to read the 'global' properties and the properties of application A, User B should be able to read the 'global' properties and the properties of application B, ...)

If there isn't currently a solution for this szenario: Do you think that this would be an worthwhile feature?

**Comment by ojhughes** [comment]
@ChrisCavegn I believe you can achieve this using HashiCorp Vault backend for Config Server if each app is assigned a different Vault token that has the appropriate ACLs (configured in Vault *not* Config Server)

**Comment by ChrisCavegn** [comment]
@ojhughes Thx for the suggestion. I'm aware of this possibility. However, I'd like to keep the setup as simple as possible and go for a Config Server-only solution. (Introducing Vault come's with unsealing after start/restart. I currently don't need that kind of security)

**Comment by spencergibb** [comment]
@ChrisCavegn this is something that has been implemented commercially http://docs.pivotal.io/spring-cloud-services/1-4/common/config-server/

**Comment by ChrisCavegn** [comment]
@spencergibb Thank you for the hint. Unfortunately, I'm unable to find this feature in the documentation / changelog / google. Is there a link to the description of this feature?

**Comment by spencergibb** [comment]
I'm afraid I all have to offer is the link to the documentation. @csterwa or @scottfrederick anything else?

**Comment by csterwa** [comment]
@ChrisCavegn there is currently no inherent support for segmenting authorization to Config Server properties as is currently supported in HashiCorp Vault. I believe this will not be implemented in Config Server but rather through other configuration backends in the future. Cloud Foundry has a fairly new project called CredHub that could become one of these solutions that would be available on the PCF platform for use as such a backend solution.

**Comment by ChrisCavegn** [comment]
Thx for all the replies and hints! I'll definitely take a look at CredHub.

It should be quite simple to add optional user/application based visibility restriction.
Please see https://github.com/ChrisCavegn/spring-cloud-config/commit/8f0f8112d0bc17a5c4aa032c52452ecbc5b8b9c3

I've added an 'AuthorizationValidator' to Environment- and ResorceController. In the default implementation, there is't any restriction in accessing the properties. A more advanced implementation of AuthorizationValidator could be implemented like this:

```
public class ApplicationBasedAuthorizationValidator implements AuthorizationValidator {
	private final Log logger = LogFactory.getLog(getClass());

    private final String rolePrefix;
    private final String rolePostfix;

    /**
     * @param rolePrefix prefix prefix of the role, can be null
     * @param rolePostfix postfix postfix of the role, can be null
     */
    public ApplicationBasedAuthorizationValidator(String rolePrefix, String rolePostfix){
        this.rolePrefix = rolePrefix;
        this.rolePostfix = rolePostfix;
    }

    @Override
    public void ensureCallerAuthorized(HttpServletRequest request, String name,
                                       String profile, String label) {
        String role = getRequiredRole(name, profile, label);

        if(!request.isUserInRole(role)){
            String message = "User " + request.getRemoteUser() +
                    " isn't allowed to read properties for Application " + name +
                    "(Missing role " + role + ")";

            logger.error(message);
            throw new SecurityException(message);
        }
    }

    String getRequiredRole(String name, String profile, String label) {
        return new StringBuilder(Objects.toString(rolePrefix, ""))
                .append(name)
                .append(Objects.toString(rolePostfix, ""))
                .toString();
    }
}
```

Is there a chance that this feature is added? (I'm quite new to spring/spring-boot and happy to rewrite this change if required)

**Comment by ryanjbaxter** [comment]
After talking with the team today the conclusion was to rely on Spring Security in combination with the Config Server in order to do what you are trying to accomplish rather than make any specific changes to the Config Server itself.
