### ISSUE TITLE
 'parent.relativePath' points at wrong local POM @ line 50, column 13

### ISSUE THREAD

**Issue by NukeYu** [spring-cloud/spring-cloud-config#756]
when downloading the run the command mvnw spring-boot:run
following issue comes out.

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.springframework.cloud:spring-cloud-con
fig-sample:[unknown-version]: Could not find artifact org.springframework.cloud:
spring-cloud-config:pom:1.4.0.BUILD-SNAPSHOT and 'parent.relativePath' points at
 wrong local POM @ line 12, column 10
[FATAL] Non-resolvable parent POM for org.springframework.cloud:spring-cloud-con
fig-docs:[unknown-version]: Could not find artifact org.springframework.cloud:sp
ring-cloud-config:pom:1.3.3.BUILD-SNAPSHOT and 'parent.relativePath' points at w
rong local POM @ line 50, column 13
 @
[ERROR] The build could not read 2 projects -> [Help 1]
[ERROR]
[ERROR]   The project org.springframework.cloud:spring-cloud-config-sample:[unkn
own-version] (C:\Project\springCloudPractice\spring-cloud-config-master\spring-c
loud-config-sample\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.springframework.cloud:spring-cloud
-config-sample:[unknown-version]: Could not find artifact org.springframework.cl
oud:spring-cloud-config:pom:1.4.0.BUILD-SNAPSHOT and 'parent.relativePath' point
s at wrong local POM @ line 12, column 10 -> [Help 2]
[ERROR]
[ERROR]   The project org.springframework.cloud:spring-cloud-config-docs:[unknow
n-version] (C:\Project\springCloudPractice\spring-cloud-config-master\docs\pom.x
ml) has 1 error
[ERROR]     Non-resolvable parent POM for org.springframework.cloud:spring-cloud
-config-docs:[unknown-version]: Could not find artifact org.springframework.clou
d:spring-cloud-config:pom:1.3.3.BUILD-SNAPSHOT and 'parent.relativePath' points
at wrong local POM @ line 50, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildin
gException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableMo
delException

**Comment by ryanjbaxter** [comment]
Are you running a config server or config client?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
