### ISSUE TITLE
How to force HTTPS for config server?

### ISSUE THREAD

**Issue by syr** [spring-cloud/spring-cloud-config#758]
Hello,
I want to use encrypted properties which should be decrypted on the config server upon client property request.
As far as I understand, the config server must run with HTTPS to prevent clear text passwords going from config server to the client.
How can I force https for the config server?
Didn't find it in the docs and issues by now.

**Comment by ryanjbaxter** [comment]
That is just a matter of forcing HTTPS in Spring Boot https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html#howto-configure-ssl
