### ISSUE TITLE
Config server should be able to reload its own, isolated settings

### ISSUE THREAD

**Issue by DimitriHautot** [spring-cloud/spring-cloud-config#76]
Currently, `application.[yml|properties]` is used as the common ancestor to all `Environment`'s served to client applications, and also used to setup the Config server. Right?

In order to hide these config. server settings to the client applications, one can put them in `bootstrap.[yml|properties]`, but then they cannot be refreshed by a POST to `http://<config-server>/admin/refresh`.

Is there a way to refresh the settings of the server without exposing them to the clients?

(Spring cloud version: 1.0.0.RC1 - Java 7 - Spring Boot 1.2.1.RELEASE)

**Comment by spencergibb** [comment]
you could put it in [configserver.yml](https://github.com/spring-cloud-samples/config-repo/blob/master/configserver.yml)

**Comment by dsyer** [comment]
The config server can load properties locally from its own classpath, and also update them with POSTs to the normal refresh/update endpoints. These should not leak into the client environment endpoints (and `bootstrap.yml` is part of the same `Environment` so if one is hidden the other is).

**Comment by DimitriHautot** [comment]
Thanks for the suggestions, I'll dig into these directions.
