### ISSUE TITLE
[Feature Request] Be able to use Spring Cloud Like cote.js

### ISSUE THREAD

**Issue by oleersoy** [spring-cloud/spring-cloud-config#761]
http://cote.js.org/

**Comment by spencergibb** [comment]
This is the wrong repo for this, but we'll take a look at cote as we look at our roadmap.

**Comment by oleersoy** [comment]
Awesome - Just thought it would be an interesting project for Spring to be aware of.

**Comment by spencergibb** [comment]
Yup, thanks for bringing it to our attention. The broadcast/multicast discovery is interesting.
