### ISSUE TITLE
Symmetrically encrypted properties without JCE?

### ISSUE THREAD

**Issue by syr** [spring-cloud/spring-cloud-config#763]
Hello,
we need to encrypt some properties with symmetric encryption.
However, in the target environment (Azure) we can neither replace local_policy.jar and US_export_policy.jar nor activate JCE.
That article already describes the problem precisely, but its fix didn't work:
https://stackoverflow.com/questions/1867494/using-alternative-of-library-loaded-by-java-bootstrap-class-loader?rq=1

Is there a way to get symmetric encryption to work without replacing the JARs?
Or maybe an alternative JCE implementation which might work?

**Comment by ryanjbaxter** [comment]
Not that I know of

**Comment by spencergibb** [comment]
@syr can you please open this in spring-cloud-commons where this would be implemented?
