### ISSUE TITLE
IBM SDK Problem

### ISSUE THREAD

**Issue by ayerix** [spring-cloud/spring-cloud-config#768]
There is a problem with IBM Sdk Base64.encode method (translated to spring's Base64Utils.encode): it unfortunately appends \r\n to the encoded string. The Base Authorization header sent with \r\n fails with "bad character" Exception. Actually this is not really big problem: I can fix it manually by removing these symbols, but the problem is that I can't simply override this method: it's private and the only way to change it is to copy ConfigServicePropertySourceLocator source and change it there. I guess it's a good idea to try to make it possibly configurable, without ctrl-c

**Comment by ryanjbaxter** [comment]
I think the problem should be addressed in the Spring Framework not with a change to `ConfigServicePropertySourceLocator`.  I suggest you open an issue with them.

**Comment by spencergibb** [comment]
You can also try using apache commons coded, which is supported by spring framework for decoding.
