### ISSUE TITLE
 @EnableSwagger2  make the spring.cloud.config.server.prefix not work

### ISSUE THREAD

**Issue by 91wangmeng** [spring-cloud/spring-cloud-config#770]
i am sorry that my english is not very well, but i found when i add  @EnableSwagger2 ,the
`@RequestMapping(method = RequestMethod.GET, path = "${spring.cloud.config.server.prefix:}")` in  `EnvironmentController` would not work.
i try to add 
 `@RequestMapping("${spring.cloud.config.server.prefix}")`
 and
  `@RequestMapping("${spring.cloud.config.server.prefix:}")`
on my controller,  The first one is valid,so what different between  `${spring.cloud.config.server.prefix:}` and
`${spring.cloud.config.server.prefix}`?

**Comment by ryanjbaxter** [comment]
Could you perhaps be more specific about what does not work?  Maybe provide an example project?  The colon `:` is a way of doing `if/else`.

**Comment by 91wangmeng** [comment]
yes, here is the [example project](https://github.com/91wangmeng/config-with-swagger),in this project prefix setting does no work

**Comment by ryanjbaxter** [comment]
I am not sure what is not working.  I ran your example project and it seemed to work fine.

**Comment by 91wangmeng** [comment]
@ryanjbaxter 
whith @EnableSwagger2
 the start log is 
`Mapped "{[/{name}-{profiles}.properties],methods=[GET]}" onto public`

whitout @EnableSwagger2,the log is
`Mapped "{[/control_config/{name}-{profiles}.properties],methods=[GET]}" onto public`.

so where is my prefix setting`control_config`???????

**Comment by spencergibb** [comment]
I don't think we're going to investigate what's wrong with the swagger 2 code.

**Comment by 91wangmeng** [comment]
@spencergibb ,ok i think it is fault with swagger2,i give it up.
but can you tell me what different between `${spring.cloud.config.server.prefix:}` and `${spring.cloud.config.server.prefix}` ,i found the last one could work with swagger2

**Comment by shakuzen** [comment]
> but can you tell me what different between `${spring.cloud.config.server.prefix:}` and `${spring.cloud.config.server.prefix}`

@91wangmeng That was answered by @ryanjbaxter in https://github.com/spring-cloud/spring-cloud-config/issues/770#issuecomment-320640433

> The colon `:` is a way of doing `if/else`.

Put another way, the right side of the `:` is the default value that will be used if the left side does not evaluate to a property with a value. In this case that means it will be the blank String since there is nothing after the `:`.

**Comment by 91wangmeng** [comment]
@shakuzen thank you very much!
