### ISSUE TITLE
Possible encrypt or decrypt without JCE installed?

### ISSUE THREAD

**Issue by smartwjw** [spring-cloud/spring-cloud-config#771]
Is it possible to use AES128 instead of AES256 for encrypt or decrypt(or at least make it a option)?Because none of our jvm deploments has jce installed.

**Comment by ryanjbaxter** [comment]
At the moment it is a requirement to have JCE installed.

**Comment by smartwjw** [comment]
@ryanjbaxter is there any plans ?

**Comment by ryanjbaxter** [comment]
not at the moment
