### ISSUE TITLE
Organization/Project-level abstraction for Git/BitBucket repositories

### ISSUE THREAD

**Issue by tomcruise81** [spring-cloud/spring-cloud-config#779]
Based on [Placeholders in Git Search Paths](http://cloud.spring.io/spring-cloud-static/spring-cloud-config/1.3.2.RELEASE/#_placeholders_in_git_uri), there's the ability to have placeholders for the `{application}`, `{profile}` and `{label}`. However, as the `uri` in that example identifies, there's also a higher level qualifier at Github and with BitBucket repos - namely organization/project. Our agency is broken into many organizations/projects, with each being given their own project within BitBucket to organize their repositories. This facilitates a micro-services design pattern better for our purposes. However, trying to implement **Spring Cloud Config Server** as an enterprise service would really benefit from supporting something like:
``` yaml
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/{organization}/{application}
```

with a corresponding URL from the **Spring Cloud Config Server** [`ResourceController`](https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/resource/ResourceController.java#L109):

`{organization}/{application}/{profile}/{label}/**`

It doesn't appear that there's a mechanism for doing this.  I've seen the [Pattern Matching and Multiple Repositories](http://cloud.spring.io/spring-cloud-static/spring-cloud-config/1.3.2.RELEASE/#_pattern_matching_and_multiple_repositories) approach, but this then requires changes to the **Spring Cloud Config Server**'s `application.yaml` for every single new organization/project to be on-boarded. Ideally, if the URL provided to **Spring Cloud Config Server** had the ability to identify the organization/project, then I'd think that it'd become a much more suitable product for enterprises that have higher level groupings than just `{application}`.

Thoughts/suggestions?

**Comment by tomcruise81** [comment]
Not sure if something like the use of `(_)` in `{label}` could also be applied to the `{application}` field (based on content from [Git Backend](http://cloud.spring.io/spring-cloud-static/spring-cloud-config/1.3.2.RELEASE/#_git_backend)). Or if it really makes more sense to break organization/project out into it's own set of properties/fields, as I'd think this would also be applicable to Vault and other back-ends beyond just Git.

**Comment by spencergibb** [comment]
So, the organization would have to be set in the client as well, correct? How often do you add organizations?

**Comment by tomcruise81** [comment]
Correct. The client knows about which organization it belongs to. 

We add organizations (more specifically, projects) multiple times a week.

**Comment by spencergibb** [comment]
Each project gets it own org?

**Comment by tomcruise81** [comment]
-ish... In the context of BitBucket Server (on-premise hosted), the grouping is really a _project_ grouping, whereas if we were using something like Github, I think that the notion of grouping is at the _organization_ level. Either way, it's one level higher than the repository (i.e. it's a grouping of repositories). It's just semantics whether you call that higher level _project_ or _organization_. We call it _project_.

**Comment by spencergibb** [comment]
@tomcruise81 does #814 close this?

**Comment by tomcruise81** [comment]
@spencergibb I believe so. I didn't make any changes to the asciidoc documentation to indicate this as an added feature.

**Comment by spencergibb** [comment]
Thanks.

Opened #827 for the docs.
