### ISSUE TITLE
JGit 4.6.0.201612231935-r requires java 8

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-config#780]
When jgit was upgraded here b2babf896179b47260e9d807e7b28ee5cdd8e587 jgit 4.6 requires java 8 :-(

**Comment by spencergibb** [comment]
To work around this
```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jgit</groupId>
			<artifactId>org.eclipse.jgit</artifactId>
			<version>3.6.1.201501031845-r</version>
		</dependency>
```

**Comment by spencergibb** [comment]
This applies to the 1.3.x branch and master

**Comment by spencergibb** [comment]
Looks like there is a breaking api change. My simple test above must have avoided that particular code. @dsyer @ryanjbaxter

**Comment by spencergibb** [comment]
Looks like there's a deprecated method that is in both versions.

**Comment by ryanjbaxter** [comment]
Meaning we now have code that is dependent on the new version?

**Comment by spencergibb** [comment]
That was my initial worry, there is a method that is deprecated in 4.x that is in 3.x as well. So changing to that will be fine. We can remove the deprecation in the 2.0.x branch, that way if a user needs jgit 4.x that can pin the version, but there won't be missing methods.

**Comment by spencergibb** [comment]
A test is failing
