### ISSUE TITLE
stop at "Unregistering JMX-exposed beans" when using SpringApplication.exit()

### ISSUE THREAD

**Issue by whg999** [spring-cloud/spring-cloud-config#781]
With Spring Cloud Config Server and Consul discovery，
when invoke SpringApplication.exit(), application stop at: o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
can not shutdown successfully.

**Comment by ryanjbaxter** [comment]
Can you provide more information?  A stacktrace and sample app would be good.

**Comment by whg999** [comment]
Sorry so late, I found if set spring.cloud.consul.discovery.heartbeat.enabled=false, then it is OK.
Is that consul heartbeat's connection thread can not be destroyed ?
[pool-3-thread-1] h.i.c.PoolingHttpClientConnectionManager : Connection [id: 0][route: {}->http://localhost:8500] can be kept alive indefinitely

**Comment by ryanjbaxter** [comment]
That is still not enough information for us to diagnose the issue.  Please provide a sample app.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
