### ISSUE TITLE
Provide a way to programmatically disable `ConfigServicePropertySourceLocator`

### ISSUE THREAD

**Issue by jabubake** [spring-cloud/spring-cloud-config#785]
[We](https://github.com/spring-cloud/spring-cloud-gcp/pull/106) are looking to bootstrap the configuration client using our own property source.
Unfortunately, `ConfigServicePropertySourceLocator' cannot be easily extended for our needs.
We would like to disable the default `ConfigServicePropertySourceLocator' and it looks like it requires our users to provide an additional `spring.cloud.config.enabled=false` in their configuration.
This seems confusing since it seems like a flag to enable /disable config. and we still expect users to provide `spring.cloud.config.name` and `spring.cloud.config.profile`. 

Is there a programmatic way that we can do this, so our users will not have to ?

**Comment by spencergibb** [comment]
Why would the use include spring-cloud-starter-config at that point?

**Comment by jabubake** [comment]
@spencergibb : 
I've tried with spring-cloud-config-client as well and ran into similar issues. Have I interpreted what you said correctly ? Do you have a recommendation on how we can avoid this ?

**Comment by spencergibb** [comment]
Why are you doing?
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-config</artifactId>
    <version>${spring-cloud-config.version}</version>
 </dependency>
```
