### ISSUE TITLE
Property source

### ISSUE THREAD

**Issue by ctatineni** [spring-cloud/spring-cloud-config#79]
apart from local and git property sources is it possible to use Redis as a property source?
i think with the archaius we can define the custom configuration manager so that it can read from Redis, i saw somewhere in the spring cloud documentation that it is not recommended to use.
Any suggestions would be appreciated.

**Comment by dsyer** [comment]
You can use whatever source for properties you like. Documentation is here: http://projects.spring.io/spring-cloud/spring-cloud.html#customizing-bootstrap-property-sources (source code [here](https://github.com/spring-cloud/spring-cloud-config/blob/master/docs/src/main/asciidoc/spring-cloud-config.adoc) if you want to improve it).
