### ISSUE TITLE
Invalid JSON RefreshRemoteApplicationEvent onto kafka from ConfigServer

### ISSUE THREAD

**Issue by bharatD11** [spring-cloud/spring-cloud-config#790]
I am trying to develop a config client in nodejs.In the process, I wanted to use RefreshRemoteApplication Event from Kafka to update config real-time.

After Successful integration with github config server.A GitHub push event results into Invalid JSON 
RefreshRemoteApplication Event as shown below .

�
 contentType
            "text/plain"originalContentType "application/json;charset=UTF-8"{"type":"RefreshRemoteApplicationEvent","timestamp":1505213392057,"originService":"ConfigServer:production,staging","destinationService":"**","id":"fac1ffeb-0075-4623-ace4-60f4580c0836"}

Please provide any information about this.Is the about message in the different format?

**Comment by ryanjbaxter** [comment]
Please learn how to format code in GitHub
https://help.github.com/articles/creating-and-highlighting-code-blocks/

This is what is published to Kafka?

**Comment by bharatD11** [comment]
@ryanjbaxter  thanks for helping out with the link.
On the issue, yes this is what I get when I directly use Kafka DefaultConsole consumer.

**Comment by ryanjbaxter** [comment]
I assume you are expecting just to get the JSON and not the header information?  That is what I would expect.  The JSON itself is valid but if the header information is included as well than I can see that being a problem.

**Comment by jdgiotta** [comment]
@ryanjbaxter can you point me at the reference of the payload used? I want to consume it with a non-Spring cloud project. You mentioned a header, but I'm looking to deserialize to actually obtain the JSON body.

**Comment by ryanjbaxter** [comment]
@jdgiotta your question is unrelated, please ask your question on StackOverflow or Gitter.  If you have an actual issue feel free to open another issue in this repo.
