### ISSUE TITLE
Secure sensible Configserver configuration

### ISSUE THREAD

**Issue by sburkard** [spring-cloud/spring-cloud-config#792]
Hi 

I built a configserver with Git backend and decryption of {cipher}-properties (e.g. passwords). The client apps receive the cleartext values. Therefore I have HTTPS and Authentication in place to protect the communication with the configserver.

So, on the client side, there are no more sensitive cleartext values - except the password to talk with the configserver.

On the configserver, I still have some sensitive config values in cleartext (Git password, encryption key password, auth-password for clients) because it is kind of a chicken and egg situation. I use the configserver to protect them, but I have to configure the configserver itself.

Does the Spring ecosystem offer any tools to protect such these values? 

I understand that I cannot protect them fully because at the end the server must be able to use these values. My goal is to protect them "at rest", i.e. in the static files that go into version control etc.

Alternatives would be password managers for the operating system or self-made encryption, but if there is a Spring solution I would favour this one.

Thanks

PS: I hesitate to use 2-way-SSL without Authentication or client side decryption of properties because there are also shell-scripts who need to query the configserver and I guess the scripts are getting complex if they have to handle one of them.

**Comment by ryanjbaxter** [comment]
A couple of suggestions.

1.  Instead of using basic auth for your Git authentication you could use SSH.  That would keep the username and password out of the configuration file http://cloud.spring.io/spring-cloud-static/Edgware.M1/#_authentication.

2.  Instead of supplying the encryption key in the configuration file, you can supply it via the environment variable `ENCRYPT_KEY`.

**Comment by sburkard** [comment]
Thanks for your answers. 

1. We can't use SSH, as far as I know we only have HTTPS access to the repository (given by operations dept)
2. But your suggestion about environment variables also works for the Git credentials. I currently don't know where such environment variables would be defined by operations. There would be no benefit at all if they write them cleartext into any deployment descriptor (and push them to the Git server). But I have to check this out. 


I also found pass (https://www.passwordstore.org). With it I could decrypt the sensible data in a bash script (application.conf) and pass them as Java parameters to the application and use them in the configuration.
Downside is that it is an additional software to install.

**Comment by ryanjbaxter** [comment]
I think the basic suggestion here is to remove the passwords from the configuration file so they are external to the app and then pass them either as parameters when starting the app or setting them as environment variables.
