### ISSUE TITLE
How can I decrypt a symmetrically encrypted properties programmatically?

### ISSUE THREAD

**Issue by cardona86** [spring-cloud/spring-cloud-config#793]
I have a suite of different applications that were not originally written in Spring. I'm in the process of implementing a config server to externalize the properties as well as moving legacy processes to Spring boot. I'd like to have the config server send the properties encrypted and have the clients (both converted Spring boot projects and legacy Java applications) decrypt the properties but can't seem to get symmetrical decryption working for the non spring boot applications.

**Comment by ryanjbaxter** [comment]
If the application is not using Spring Cloud Config than there is nothing we can do to help.  The Spring Cloud CLI could be used to decrypt it but I am not sure how much help that would be in you legacy Java apps.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
