### ISSUE TITLE
/{applicationName}/{profile} endpoint do not decrypt

### ISSUE THREAD

**Issue by hyojinbae** [spring-cloud/spring-cloud-config#795]
Im new to spring cloud.
I recently tried to write sample code, in order to know spring cloud config.
And when I configure the encryped value,  it seems not to decrypt in the latest version of spring-cloud-config (1.3.2.RELEASE). 
I tried to use spring-cloud-config-server of 1.3.1.RELEASE, it works as expected.
Do I have to do something additional in using the latest version?

![2017-09-22_12h37_19](https://user-images.githubusercontent.com/4329541/30728685-acf6892e-9f94-11e7-82df-efc8539a8210.png)

**Comment by ryanjbaxter** [comment]
Can you provide a sample that reproduces this?

**Comment by hyojinbae** [comment]
I made new branch to reproduce this.

https://github.com/hyojinbae-sample/hyojinbae-spring-cloud-sample/tree/spring-cloud-config-issue795

and configuration file in repository is
https://github.com/hyojinbae-sample/hyojinbae-spring-cloud-sample-config-repo/blob/master/application.yml

and run application in my local and if I access this URL, then this reproduces.
http://localhost:8888/configclient1/default

**Comment by ryanjbaxter** [comment]
Move the `encrypt.*` properties from `application.yml` to `bootstrap.yml`.

**Comment by hyojinbae** [comment]
Thanks. It works!

**Comment by w3blogfr** [comment]
Thanks. I was looking since few hours before to find this issue.
