### ISSUE TITLE
Align spring-cloud-config with JSR 382, contribute to JCP

### ISSUE THREAD

**Issue by ansgarkonermann** [spring-cloud/spring-cloud-config#798]
Guys around Eclipse MicroProfile started a JSR to standardize an API for Java Application / Micro Services Configuration recently:

JSR home: https://jcp.org/en/jsr/detail?id=382
Twitter: https://twitter.com/ConfigJSR https://twitter.com/MicroProfileIO
Google Groups JSR Status Update: https://groups.google.com/forum/m/#!topic/microprofile/LxyzVg3K2SU

Spring Cloud Config targets the same problem. I would love to see it in-line with this upcoming JSR standard, as much as feasible.

Who can participate in the JCP and provide expertise from Spring Cloud Config into that JCP?

What do you think about this?

**Comment by spencergibb** [comment]
[PropertySource](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/env/PropertySource.java#L59) is from spring-framework (Dec 2011), [ConfigurationProperties](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/properties/ConfigurationProperties.java) (and loading yaml/properties) is from spring boot (Apr 2014) and spring cloud handles the remote pieces (Mar 2015). I'm unsure of the effort across all the projects to do that would be. 

What are the dependencies on CDI?

I'm also unsure what the benefit for spring users would be.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
