### ISSUE TITLE
Encryption Issue: No Key was installed for encryption service

### ISSUE THREAD

**Issue by heyitsaakash** [spring-cloud/spring-cloud-config#800]
Referring to #767 
We are not using dalston but milestone release below. I am using windows and ran in to the same issue. Is this an issue with 2.0.0.M3Finchley.M1 too.

<java.version>1.8</java.version>
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
<spring.boot.version>2.0.0.M3</spring.boot.version>
<spring.cloud.version>Finchley.M1</spring.cloud.version>
<spring.cloud.stream.version>Elmhurst.BUILD-SNAPSHOT</spring.cloud.stream.version>

Please confirm.
I got the error below http://localhost:1010/encrypt/
{
    "description": "No key was installed for encryption service",
    "status": "NO_KEY"
}

I am setting the key correctly 
java -Xmx512m -Dconfiguration.store.path=D:/configuration-store -DENCRYPT_KEY=123xxxx -jar target/configuration-server-2.0.1.jar --spring.profiles.active=local

**Comment by spencergibb** [comment]
Spring boot 2 compatibility is a work in progress

**Comment by heyitsaakash** [comment]
thanks for prompt reply. So as i understand this is a known issue. Am i right?

**Comment by spencergibb** [comment]
Yes, actuator endpoints are broken

**Comment by heyitsaakash** [comment]
Will encryption/decryption JCE work fine though for Cloud config or is that also not supported as of now. Considering i can get encrypt keys of format {cipher}AQCLJG5FvxQrLAC6Q9iDmkegrIh1yJ4K2BeRzNdu3PkMZXv1cMSJ/C3 below through some other source.

**Comment by steveguoshao** [comment]
In Spring Cloud Edgware.RELEASE version，if the encrypt.key in application.yml the error always appear，when i move the encrypt.key into bootstrap.yml，is ok

**Comment by spencergibb** [comment]
That is the documented place for it
