### ISSUE TITLE
password encrypted with jasypt is breaking when "refreshed"

### ISSUE THREAD

**Issue by nagarajatantry** [spring-cloud/spring-cloud-config#808]
Hi,

I have Spring boot application (v1.5.7) with below 2 properties
- myapp.properties --> Properties of this file is getting loaded from the Spring Cloud Config server
- password.properties --> contains passwords encrypted using Jasypt. This is not managed by Spring Cloud config server. it is supplied at runtime using --spring.config.location attribute=file:<folder>/password.properties.
example of content within password.properties
 my.server.password=ENC(securepassword)

Problem: When i hit the /refresh API, it thinks that there is a change in "my.server.password"  and refreshes it with the encrypted value. This causes issue since I expect the key to contain decrypted value at runtime.
Did someone run into the issue?
Other thing I observed is, if I have password.properties packaged within the jar file, then I don't run into this issue.

Kindly let me know if any further information is required.

**Comment by ryanjbaxter** [comment]
I am not familiar with Jasypt.  I read through the README quickly.  From the description of your problem it sounds like `my.server.password` is not being decrypted after a refresh event occurs.  If that is the case it doesn't really sound like a Spring Cloud problem.  It sounds like whatever Jasypt is doing to decrypt the values is not happening on the refresh event.  I could be wrong though...

**Comment by nagarajatantry** [comment]
Let me remove the jasypt dependency for a moment.  
I have a Config client application, which has a property file  injected through Config server set up and another file from local directory (i.e. through --spring.config.location )
keys of these 2 files do not overlap.

What I observed is, if I modify the properties file in my local directory and then execute "/refresh" endpoint, I see that it detects the local file changes as well.
I was expecting the "/refresh" endpoint to detect changes only for the properties file managed by config server.

**Comment by spencergibb** [comment]
@nagarajatantry seems like an odd situation. How often do you modify the local config file and not want it updated?

**Comment by jnulwliang** [comment]
@spencergibb @nagarajatantry i am facing the similar issue. Actually i want to encrypt the password of the git repository in the application.yml of my spring cloud config server project. Could you show me how to encrypt the password or other properties in the application.yml of my spring cloud config server project.  Looking forward to your reply, thanks :)

**Comment by ryanjbaxter** [comment]
@jnulwliang it doesn't sound like your question is related.  You should read 
http://cloud.spring.io/spring-cloud-static/Edgware.SR1/single/spring-cloud.html#_encryption_and_decryption
and
http://cloud.spring.io/spring-cloud-static/Edgware.SR1/single/spring-cloud.html#_encryption_and_decryption_2

**Comment by nagarajatantry** [comment]
@spencergibb I use local file to specify password required for the applications. this is not stored in git.  The reason why I did not want /refresh to pick it up is that it was not decrypting the password again. I use jasypt encryptor in this project. I was able to then solve it by using com.ulisesbocchio.jasyptspringboot.environment.StandardEncryptableEnvironment

Ideally, since config server was not managing these files in the first place, I was expecting it to not refresh at all.

**Comment by spencergibb** [comment]
Refresh and configserver are separate concerns. Configserver takes advantage of it.

**Comment by nagarajatantry** [comment]
@spencergibb Understood. thank you 👍

**Comment by nagarajatantry** [comment]
@jnulwliang Your issue seems to be not related to this topic. Having said that, In case if you are using jasypt encryptor,  you can solve it by first creating a META-INF/spring.factories file in src/main/resources directory with below content

```
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
com.ulisesbocchio.jasyptspringboot.JasyptSpringBootAutoConfiguration
```

**Comment by jnulwliang** [comment]
thanks lot. I solved it by using com.ulisesbocchio.jasyptspringboot.environment.StandardEncryptableEnvironment  :)

**Comment by sathish593** [comment]
we are using spring boot version 1.5.9.RELEASE and cloud version Edgware.RELEASE and we are using jasypt for encrypted properties. on refresh property decryption is note working. i tried the StandardEncryptableEnvironment but still no use. can any one share the working example. TIA.

**Comment by krishna2025** [comment]
we are using spring boot version 2.1.10.RELEASE and cloud version  Greenwich.SR3 and we are using jasypt for encrypted passwords. I kept encrypted passwords on application.yml file. During configserver startup it is getting decripted properly and working fine. If I make any changes on application.yml file my decripted password automatically getting encrypted back and not decripting. Can some one help on this?

**Comment by bharathmit** [comment]
> thanks lot. I solved it by using com.ulisesbocchio.jasyptspringboot.environment.StandardEncryptableEnvironment :)

I added same into main method, when i hot the referesh endpoint i am gtting below error .

 "errorMessage": "PropertySource named 'springCloudServicesBootstrap' does not exist",

**Comment by samuelj90** [comment]
It seems to be the issue with `jasypt-spring-boot` which is fixed in the latest releases
https://github.com/ulisesbocchio/jasypt-spring-boot/releases

Issue thread:
https://github.com/ulisesbocchio/jasypt-spring-boot/issues/343
PR: 
https://github.com/ulisesbocchio/jasypt-spring-boot/pull/344/commits/2adb85caf0edaf64ae831744ea02daed317f8d4f
