### ISSUE TITLE
How to use the configuration server to dynamically serve files?

### ISSUE THREAD

**Issue by serious93** [spring-cloud/spring-cloud-config#809]
We have a configuration server with some .xsl files hosted. The idea is according to the flow of the application being invoked, get one of these files at runtime. What is the best way to reference them? In what format are they returned? If you can add a Java example of how resources are used, it would be great.

We tested from the browser by entering  `http://localhost:8888/name/profile/label/path-to-file.xsl`  and we can see it.

The same problem we have with resources such as .xml and bundles.

**Comment by ryanjbaxter** [comment]
Are you just wondering how to read the `.xsl` files in Java?

**Comment by serious93** [comment]
Yes, how to reference and use them from java

**Comment by spencergibb** [comment]
You would use something like `RestTemplate` with the url provided in the description.

**Comment by ryanjbaxter** [comment]
There are plenty of examples of how to do this on the internet.
