### ISSUE TITLE
Spring cloud config server for vault not supporting profiles

### ISSUE THREAD

**Issue by heyitsaakash** [spring-cloud/spring-cloud-config#813]
Spring cloud config when using vault server is not picking up the correct backend based on profiles for the application.

E.g I have backends secret/ttt-microservice, secret/ttt-microservice/default

If i give the profile=default and develop being the label
http://localhost:1010/ttt-microservice/default/develop
I see the backend for secret/ttt-microservice being mapped but it doesn't pick secret/ttt-microservice/default. Is is correct to deduce spring cloud config for vault doesn't support profiles. Is it something to expect in future. thanks aakash

**Comment by spencergibb** [comment]
It is not the case. Default is a special profile in spring

**Comment by heyitsaakash** [comment]
its only with the vault it doesnt map the vault source correctly with secret/ttt-microservice/{profile}. For git it picks up correctly as we have composite property sources. If i change the profile to dev  and create vault backend secret/microservicename/dev it still maps to secret/ttt-microservice

**Comment by heyitsaakash** [comment]
versions <spring.boot.version>2.0.0.M3</spring.boot.version>
		<spring.cloud.version>Finchley.M1</spring.cloud.version>

**Comment by heyitsaakash** [comment]
@spencergibb  @mp911de can you please confirm will help to move ahead. thanks

**Comment by spencergibb** [comment]
By default vault looks for profiles with a comma, so `ttt-microservice,default`. You can change it with `spring.cloud.config.server.vault.profile-separator`.

**Comment by heyitsaakash** [comment]
thanks it seems to work with ,
