### ISSUE TITLE
Missing Property File in the git server cause the Applition to keep retrying and putting load on git server

### ISSUE THREAD

**Issue by jprateekvmware** [spring-cloud/spring-cloud-config#818]
Hi All,
I am looking at the option for protecting the config server against multiple request from rogue app.
If the application property file is missing in the GIT Server, it will be retrying continuously. Do we have the option to stop retrying ? My understanding is failfast work in case config server is down. 

This has been causing issues and bombarding the git server with multiple calls continuously.

Can we have it wrapped as part of the hystrix and have circuit breaker enabled for such calls to limit the number of request hitting the git server.

**Comment by spencergibb** [comment]
I don't think config client retries on a missing property. Config client doesn't know if a property is missing or not. Something else is going on. Maybe a health check?

**Comment by jprateekvmware** [comment]
It's a container based application and keep restarting. But still let's assume I am hitting continuously through postman , Can we put some circuit breaker on it to stop same request from hitting again and again

**Comment by karl-ravn** [comment]
This one may help to protect the git server at least: https://github.com/spring-cloud/spring-cloud-config/pull/749

**Comment by spencergibb** [comment]
I don't know there's much we can do here. You can setup the retry along with fail-fast an exponential backoff.
