### ISSUE TITLE
JdbcEnvironmentRepository and spring.cloud.config.server.bootstrap=true won't work

### ISSUE THREAD

**Issue by denis111** [spring-cloud/spring-cloud-config#823]
Hello everybody,

I think this is the issue which should be fixed or any workaround suggested.
If we try to use JdbcEnvironmentRepository in embedded config server setting spring.cloud.config.server.bootstrap=true and spring.profiles.active=jdbc in bootstrap.properties then starting application fails because of no jdbcTemplate bean. Is it possible to create jdbcTemplate then at bootstrap phase before JdbcEnvironmentRepository or any other workaround? (maybe some listener at context creation but not after creation or so).

`2017-10-19 10:47:11.609  WARN 11204 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'propertySourceBootstrapConfiguration': Unsatisfied dependency expressed through field 'propertySourceLocators'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cloud.config.server.bootstrap.ConfigServerBootstrapConfiguration$LocalPropertySourceLocatorConfiguration': Unsatisfied dependency expressed through field 'repository'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jdbcEnvironmentRepository' defined in org.springframework.cloud.config.server.config.JdbcRepositoryConfiguration: Unsatisfied dependency expressed through method 'jdbcEnvironmentRepository' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.jdbc.core.JdbcTemplate' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}`

**Comment by nagarajatantry** [comment]
@denis111 I ran into the same issue. Were you able to get a solution for this?

**Comment by nagarajatantry** [comment]
I happen to give it a one more try and was successful.  User this as reference --> https://github.com/spring-cloud/spring-cloud-vault/tree/master/spring-cloud-vault-config-aws

Here are the steps...
1. create META-INF/spring.factories file
````
# Bootstrap Configuration
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
com.ntantry.CustomBootstrapConfiguration
````
2. Create JdbcTemplate instance in CustomBootstrapConfiguration 
````
@Configuration
public class CustomBootstrapConfiguration {

    @Autowired
    Environment environment;

    @Bean
    public JdbcTemplate jdbcTemplate() {
        DataSource dataSource = DataSourceBuilder.create().build();
        org.apache.tomcat.jdbc.pool.DataSource typedDS = (org.apache.tomcat.jdbc.pool.DataSource) dataSource;
        typedDS.setUrl(environment.getProperty("app.datasource.url"));
        typedDS.setUsername(environment.getProperty("app.datasource.username"));
        typedDS.setPassword(environment.getProperty("app.datasource.password"));
        typedDS.setDriverClassName(environment.getProperty("app.datasource.driver-class-name"));
        JdbcTemplate jdbcTemplate = new JdbcTemplate(typedDS);
        return jdbcTemplate;
    }

}
````

**Comment by marcingrzejszczak** [comment]
Is the problem still there in Finchley.RELEASE?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
