### ISSUE TITLE
ResourceController does not support server defined default label

### ISSUE THREAD

**Issue by daniellavoie** [spring-cloud/spring-cloud-config#824]
The `ResourceController` that exposes Plain Text files only supports `/{application}/{profiles}/{labels}/**` endpoint.

`EnvironmentController` on the other hand supports the `/{application}/{profile}` which defaults to the label to `spring.cloud.config.server.defaultLabel`.

Users may heavily rely on server defined label to prevent clients from having to explicitly declare which branch they are working on.

Exposing a `/{application}/{profiles}/**` for the `ResourceController` will be a challenge since it will conflict with `/{application}/{profiles}/{labels}`. 

Proposed solutions :
* Add an explicit `useDefaultLabel` parameter to the `ResourceController`. Spring MVC should consider `params` arguments on `@RequestMapping` as a distinctive criterion for request mapping. This option has to be tested.

**Comment by dsyer** [comment]
Isn't `/plain/foo/bar/spam` matched by both patterns (one with `application=plain` and one with `application=foo`)?

**Comment by daniellavoie** [comment]
Indeed, guess we can scrap the third option
