### ISSUE TITLE
Multiple root configs?

### ISSUE THREAD

**Issue by efenderbosch** [spring-cloud/spring-cloud-config#83]
We are investigating using Cloud Config. Use cases are standing up our various Spring Boot services and providing a single place to configure ngnix.

Is there a way to have multiple roots?

Something like:

```
application.yml
application-dev.yml
application-qa.yml
etc.

springboot1.yml
springboot1-dev.yml
springboot1-qa.yml
etc.

springboot2.yml
springboot2-dev.yml
springboot2-qa.yml
etc.

nginx.yml
ngnix-dev.yml
nginx-qa.yml
etc.
```
So when Spring Boot `springboot1` requests its config, it would get a mash up of "application.yml" and "springboot1.yml" with the proper profiles applied. Same for Sping Boot `springboot2`.

But when `ngnix` requests its config, it wouldn't get any settings from "application.yml" or the profile specific version.

**Comment by efenderbosch** [comment]
Looking at the code a bit, is the solution to create my own NgnixEnvironmentController that delegates to a NgnixEnvironmentRepository that uses "ngnix" as the root instead of "application"? I'd likely need another controller anyway to populate a freemarker template instead of simply returning yaml.

**Comment by efenderbosch** [comment]
I now have a ``NgnixEnvironmentController`` and ``PrefixedEnvironmentRepository`` which uses a specified prefix instead of "application" like ``SpringApplicationEnvironmentRepository``. I did end up copying a fair bit of code from ``SpringApplicationEnvironmentRepository``. I think a better solution would be to make ``SpringApplicationEnvironmentRepository`` accept a prefix that defaults to "application." It could then be reused for this purpose.

My controller populates a ``Map`` from the ``Environment`` and simply passes that on to Freemarker to render the ngnix.ftl template.

This might be nice to abstract away a bit so that this behavior could be enabled via configuration. Adding dynamic endpoints that render via Freemarker based on prefix.

Something like:

```yaml

spring:
  additional-root-contexts:
    - ngnix
    - foo
    - bar
```

Would expose a new endpoint /ngnix that reads from ngnix-{*}.yml and renders via ngnix.ftl without any additional code. If anyone has suggestions on how to dynamically add the endpoints, I could put the rest of this together in a pull request.

**Comment by dsyer** [comment]
This is probably also relevant (a way to separate your apps from each other a bit more): https://github.com/spring-cloud/spring-cloud-config/pull/82

**Comment by dsyer** [comment]
Question: what's the point of profile specific nginx config if "it wouldn't get any settings from application.yml or the profile specific version"?

**Comment by efenderbosch** [comment]
We're using gitlab and that doesn't seem to be playing nicely w/ JGit, so we've been testing using local config files w/ a "native" profile. I don't think we can use the solution from #82.

We do want our ngix config to be profile aware, it just should be completely separate from the application.yml tree.

**Comment by dsyer** [comment]
I don't think local files are a good solution for production applications. What is it with gitlab?

**Comment by efenderbosch** [comment]
Ideally we'd like to work similar to how gitlab and Jenkins work together. We simply added the ssh key that's on our CI box to the read-only deploy keys of our various projects.

Apparently I was doing something wrong before, because now I can fetch from our private gitlab instance just fine. #82 or something very similar should work for our use case, provided we can somehow configure it to populate a freemarker (or other supported templating engine) template instead of generating raw yaml.

**Comment by iceycake** [comment]
To clarify, our organization is using gitlab CC edition and it works well with JGit.  https://github.com/spring-cloud/spring-cloud-config/pull/82 was implemented and tested with gitlab.

**Comment by dsyer** [comment]
I don't see the need for templates yet. Can you make that a new issue, or morph this one (if we agree that #82 is sufficient for your needs), and explain a bit more?

**Comment by efenderbosch** [comment]
I'll see if I can get an example of what we are looking for from the guy who maintains the ngnix configs.

In the meantime, this is the controller I've put together to render using a template that's in the remote git repo.

https://gist.github.com/efenderbosch/c66f78fc5f7c1318ffe0

**Comment by dsyer** [comment]
There are multiple issues being discussed here now. Let's try and stick to one (the "multiple roots" from the summary). As I understand it the requirement was to optionally exclude the `application.yml` common configuration from an environment request? I'm not sure why that is summarized as "multiple roots" so maybe you could see if that is still correct?

The templating thing is also active in #147.

**Comment by efenderbosch** [comment]
Apologies for not responding to this sooner. This has just started to bubble up in our architectural timeline again.

We are also looking at spring-cloud-consul. It seems there's a bit of overlap as far as configuration goes, but it uses a different mechanism. Is that right? Can our services fetch configuration information from consul using spring-cloud-consul?

**Comment by spencergibb** [comment]
spring-cloud-consul provides configuration, but uses a lookup scheme similar to spring-cloud-config.  It won't get your 'multiple root configs' behavior.

**Comment by spencergibb** [comment]
@efenderbosch is this still an issue for you?

**Comment by dsyer** [comment]
Probably fixed in #147.

**Comment by efenderbosch** [comment]
I'll have to take a deeper look, but I don't think this solves our problem.

We plan on using zookeeper to store our configs. Applications will have their own property tree and there will also be a shared property tree for common settings such as database password, AWS keys, etc.

**Comment by dsyer** [comment]
If you are using zookeeper please look at spring-cloud-zookeeper and raise relevant issues there. Thanks.
