### ISSUE TITLE
why "spring.cloud.config.enabled:true" is required?

### ISSUE THREAD

**Issue by masque-fate** [spring-cloud/spring-cloud-config#830]
config client
 java code:
`new   SpringApplicationBuilder(Application.class).properties("spring.cloud.config.enabled:true").web(true).run(args);
 `
bootstrap.yml

![qq 20171027171428](https://user-images.githubusercontent.com/32303870/32096870-509fe38e-bb3a-11e7-9dfd-c790de495a6c.png)

when i was remove "spring.cloud.config.enabled:true" in the java file or yml file,it doesn't find the server!
i was try to find out why,but found enabled Default ‘true’ in the ConfigClientProperties.java

and find http://localhost:9999/env

configServerClient: {
spring.cloud.config.enabled: "false"
},

version:
```
<dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Brixton.SR5</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

**Comment by masque-fate** [comment]
i was debug the code, i found when i was remove "spring.cloud.config.enabled:true" in the java file.
the  bootstrap.yml could not load.
detail the main code:
`
@RestController
@SpringBootApplication
@RefreshScope
@Configuration
public class Application {

    @Autowired
    private Environment environment;

    @RequestMapping("/hello")
    public String query() throws Exception {
        return environment.getProperty("from", "no_config");
    }

    public static void main(String[] args) {
        new SpringApplicationBuilder(Application.class).properties("spring.cloud.config.enabled:true").web(true).run(args);
    }

}`

anything was wrong in the code?

**Comment by masque-fate** [comment]
```
 <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-server</artifactId>
        </dependency>
    </dependencies>
```
 **Client should not depend spring-cloud-config-server**
remove spring-cloud-config-server 
is OK now!!!

**Comment by pvspsmaheshkumar** [comment]
"Client should not depend spring-cloud-config-server"

I've been struggling with this and it worked for me after removing the dependency. Thanks a ton.
