### ISSUE TITLE
Spring-cloud-stream and spring-cloud-config messing up multiple binder config

### ISSUE THREAD

**Issue by HaVonTe1** [spring-cloud/spring-cloud-config#841]
**issue**
I found an issue when using spring-cloud-stream and spring-cloud-config using multiple binders.
Starting the demo app without config-service everything works perfect. All bindings are directed to their dedicated connection.

Activating the config-service results in false connections. All bindings are directed to the default connection. Erroneous exchanges/queues are created.

**how to reproduce**

I made a demo app to show it.
https://github.com/HaVonTe1/spring-cloud-stream-multiplebinder-config-issue-

In there is a `demoservice` with simple config in application.yml:

```json
spring:
  rabbitmq:
    host: localhost
    virtual-host: /defaultVH
    username: defaultUser
    password: defaultPassword
  cloud:
    stream:
      bindings:
        sampleQueueA:
          binder: rabbit-A
          contentType: application/x-java-object
          group: groupA
          destination: sampleQueueA
        sampleQueueB:
          binder: rabbit-B
          contentType: application/x-java-object
          group: groupB
          destination: sampleQueueB
      binders:
        rabbit-A:
          defaultCandidate: false
          inheritEnvironment: false
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                virtualHost: /vhA
                username: userA
                password: paswdA
                port: 5672
                connection-timeout: 10000
        rabbit-B:
          defaultCandidate: false
          inheritEnvironment: false
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                virtualHost: /vhB
                username: userB
                password: paswdB
                port: 5672
                connection-timeout: 10000
```

There is also a bootstrap.yml for using the config-service:
```json
spring:
  main:
    banner-mode: "off"
  application:
    name: demo-service
  cloud:
    config:
      enabled: true #change this to use config-service
      retry:
        maxAttempts: 3
      discovery:
        enabled: false
      fail-fast: true
```
When setting `spring.cloud.config.enabled=false` the rabbit connections are just fine:

[image_rabbit_good](https://github.com/HaVonTe1/spring-cloud-stream-multiplebinder-config-issue-/blob/master/rabbit_con_good.png)

But with `spring.cloud.config.enabled=true` the connections are messed up. 

[image_rabbit_bad](https://github.com/HaVonTe1/spring-cloud-stream-multiplebinder-config-issue-/blob/master/rabbit_con_bad.png)

I made 100% sure the config-service is delivering the exact same properties like the application.yml of the demoservice includes.

**expected behaviour**
Regardless of using the config-service. The connections should be the same.

**Comment by dsyer** [comment]
See also https://github.com/spring-cloud/spring-cloud-stream/issues/1124 (duplicate essentially)
