### ISSUE TITLE
Manifest.yml does not override application name in bootstrap.yml

### ISSUE THREAD

**Issue by ankool** [spring-cloud/spring-cloud-config#845]
1) manifest.yml (using inheritance, so separate manifest for each profile)

```
applications:
- name: application-v2
```

2) bootstrap.yml (same for each profile)

```
spring:
  application:
    name: application-v1
```

When I do cf push, I want (1) application name to be "application-prod" and (2) pcf to read"application-v2.yml" from my config server. The step (1) is good but pcf is looking for "application-v1.yml" in config server. 

However, if I remove application.name from bootstrap then pcf reads "application-v2.yml" from config server. But I need this property for local debug.

How can I keep application name in both but force PCF to pick config file from config server with name matching in manifest.yml file ? or how to override bootstrap.application.name from manifest.application.name to fetch config server files ?

**Comment by ryanjbaxter** [comment]
I am not sure this is a Spring Cloud Config problem.  I didnt even realize that specifying `application.name` in your manifest.yml would set the Spring application name.  Is that something the Java buildpack is doing?

**Comment by dsyer** [comment]
I think it's a bit weird to have a different application name locally and in CF. But anyway, you could set `spring.cloud.config.name` explicitly if you wanted to. Or just change the `spring.application.name` so it matches the CF app name, e.g. `spring.application.name=${vcap.application.name:application-v1}`.

**Comment by faissalwise** [comment]
Hi,
A have a similar question,how can i override the property spring.cloud.config.uri in manifest file to be able to use the property from manifest instead of bootstrap.yml.

**Comment by spencergibb** [comment]
@faissalwise in the future, please don't comment on old closed issues. In short, there's nothing we can do to assure that these match. Dave's comment https://github.com/spring-cloud/spring-cloud-config/issues/845#issuecomment-343830305 is the easiest thing you can do. Alternatively, you could set an environment variable in your manifest `SPRING_APPLICATION_NAME`.
