### ISSUE TITLE
When doing /bus/refresh only single instance gets refreshed

### ISSUE THREAD

**Issue by vivbaran** [spring-cloud/spring-cloud-config#853]
When doing /bus/refresh only single instance of my client app gets refreshed where expected is all instances of my client app should get refreshed , I am using below amqp version jar
org.springframework.cloud:spring-cloud-starter-bus-amqp:1.1.2.RELEASE

**Comment by ryanjbaxter** [comment]
We need more information.  A sample project to reproduce would be best.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
