### ISSUE TITLE
Dyamically Write to Configuration in spring cloud config

### ISSUE THREAD

**Issue by volijaadu** [spring-cloud/spring-cloud-config#854]
I see spring cloud config only provides supports for reading from git based repositories.

I have a requirement to write/update the values in the configuration through code instead of checking out and manually updating it and then finally refreshing it with actuator /refresh endpoint.

Is there any support or plan to support writing to configuration in spring cloud config?

**Comment by spencergibb** [comment]
There is no current plan to support writing configuration. Config Server can also read from jdbc or vault each of which (including jgit) have very different mechanisms for writing.
