### ISSUE TITLE
Question: Externalising configserver.yml for docker

### ISSUE THREAD

**Issue by mrcasablr** [spring-cloud/spring-cloud-config#856]
I would like to run config server in a container with my configserver.yml.  Currently, the configserver.yml is inside the src/main/resources folder. Is there a way I can pass the configserver.yml located elsewhere as parameters to the spring boot executable jar?

Something like this - https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

**Comment by spencergibb** [comment]
That is the answer to the question since it is a spring boot app
