### ISSUE TITLE
spring.cloud.config.server.encrypt.enabled not working

### ISSUE THREAD

**Issue by gongxusheng** [spring-cloud/spring-cloud-config#858]
With version Dalston.SR4 and spring boot 1.5.8.RELEASE，I set spring.cloud.config.server.encrypt.enabled=false, the password was still decrypted. It works with Camden.SR5 + spring boot 1.4.4.RELEASE

**Comment by ryanjbaxter** [comment]
Can you provide a sample that reproduces this?

**Comment by metaflow** [comment]
Hi @ryanjbaxter ! I have experienced the same issue while doing pluralsight course on Spring. Please check out file attached (replace `ssh://...` to some repo with file application.properties)
[application.properties.zip](https://github.com/spring-cloud/spring-cloud-config/files/1607179/application.properties.zip)
[cloud-config.zip](https://github.com/spring-cloud/spring-cloud-config/files/1607172/cloud-config.zip)
I expect the call to http://localhost:8888/s1rates/default to return encrypted string but it returns clear value.

**Comment by metaflow** [comment]
turned out that I have to set `spring.cloud.config.server.encrypt.enabled=false` in the `bootstrap.properties` file, not `application` one for it to work. Looks like this behavior has changed since the version in the course.

**Comment by sunnykaka** [comment]
I encounter same problem in v1.3.3.RELEASE.
The "spring.cloud.config.server.encrypt.enabled" is not work.
Config server still decrypt properties for me.

**Comment by hugosafilho** [comment]
Hi @spencergibb I'm using Edgware.SR1

**Comment by spencergibb** [comment]
@hugosafilho can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by hugosafilho** [comment]
Sure @spring-buildmaster!

Just import project inside zip file as Maven Project on Eclipse and execute using spring-boot:run then access http://localhost:8888/consultas-especies/local and you will see that property spring.datasource.password is shown decrypted even with `spring: application: name: retail-conf-svr cloud: config: server: encrypt: enabled: false setted on bootstrap.yml`

Thank you!

[conf-svr.zip](https://github.com/spring-cloud/spring-cloud-config/files/2099310/conf-svr.zip)

**Comment by spencergibb** [comment]
@hugosafilho please open a new issue and reference your comment above. The problem is specifically with disabling decrypting values in `spring.cloud.config.server.overrides`

**Comment by kkarnwal** [comment]
try to put that properties in  bootstrap.properties file 
spring.cloud.config.server.encrypt.enabled=false

**Comment by singhmahabir** [comment]
> try to put that properties in bootstrap.properties file
> spring.cloud.config.server.encrypt.enabled=false

It is now working Thanks

**Comment by jacksonjoseph** [comment]
I'm facing the same issue. I added the spring.cloud.config.server.encrypt.enabled=true in bootstrap.properties. Still it decrypting the values. I'm using Springboot 2.2.1.RELEASE and Spring cloud Hoxton.RELEASE.

**Comment by sunnykaka** [comment]
@jackdpeterson 
If you don't need decryption, you should use spring.cloud.config.server.encrypt.enabled=false

**Comment by jacksonjoseph** [comment]
@sunnykaka I used spring.cloud.config.server.encrypt.enabled=false as well. But faced the same issue.

**Comment by abhineshkr** [comment]
I am using

**Comment by kg1991** [comment]
I am using Hoxton.SR7 and spring boot 2.3.3.RELEASE. I added spring.cloud.config.server.encrypt.enabled=false in bootstrap.properties.But it is decrypting the property on cloud config server
