### ISSUE TITLE
Loading files from a directory

### ISSUE THREAD

**Issue by craigschmack** [spring-cloud/spring-cloud-config#861]
I have a need to support adding configuration by adding files to a directory. For example, if I have a 'datarepo/plugins' directory in git and can then add files 'mysql.properties', 'aerospike.properties', etc. as new plugins become available.

The hope is to be able to have the datarepo application access http://localhost:8888/datarepo/plugins and get a list of PropertySources that provide each plugin's data.

I want to avoid having one datarepo-plugins.properties that can be messed up if an install for a new plugin occurs.

After digging into this, I don't see much in the way that it would be supported without some surgery to the core logic. Does anyone have any thoughts on the viability of getting a set of resources from a directory? Any simpler approaches I should take? 

Thanks,

Craig

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
