### ISSUE TITLE
Prefered json in GenericRequestHeaderInterceptor

### ISSUE THREAD

**Issue by btpka3** [spring-cloud/spring-cloud-config#862]
# issue
- In my git conf repo, yaml config file using a map, key is a path:
    ```yaml
    path:
       "/application" : true
    ```
- With default spring cloud config server, when client GET `/{application}/{profile}`,  http request's 'Aceept' header is : 'application/xml, text/xml, application/json, application/*+xml, application/*+json', then reponse returned xml but invalid:
    ```xml
    <Environment>
    ...
    <source><path./application>true</path./application></source>
    ...
    ```
   The HttpMessageConverter fails.

- Checked the source of [ConfigClientProperties](https://github.com/spring-cloud/spring-cloud-config/blob/db63853853de3f3f5ae3d438bb4c9496d55d4c55/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigClientProperties.java#L104), and tried specify 'Accept: application/json' http heads in bootstrap.yml, without success, because [GenericRequestHeaderInterceptor](https://github.com/spring-cloud/spring-cloud-config/blob/cf1bdf647d24deaa212a68284bf4928e06eaf8ba/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java#L235) add second 'Accept' request header, but not override it.
    ```yaml
    spring.cloud.config:
      #...
      headers:
        Accept: application/json
    ```

#  suggestion

Modify GenericRequestHeaderInterceptor, `request.getHeaders().set(String,String)` instead.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
