### ISSUE TITLE
Config Server Reading from multiple property files

### ISSUE THREAD

**Issue by Nivedan3112** [spring-cloud/spring-cloud-config#863]
Hi , 

 I want to have one config server running 
Say i have one application A having a.properties, and Application B as b.properties in github , i want to know if i can use just one config server and both different client applications fetching appropriate properties?? Is there anyway i can do that using config server??

**Comment by spencergibb** [comment]
That is the most basic function of config server. Your clients just need `spring.application.name` set appropriately.

**Comment by ghoddg** [comment]
If my application have multiple tenant and each tenant have different configuration properties for same application.
Then how to fetch the tenant specific data for same application?

**Comment by ryanjbaxter** [comment]
@ghoddg your question is unrelated.  Please dont ask the same question on multiple issues.
