### ISSUE TITLE
Is it possible to decrypt some keys on server and other keys on client

### ISSUE THREAD

**Issue by KJoyner** [spring-cloud/spring-cloud-config#868]
My main use case is moving from server based encryption/decryption to client based decryption. I would like to do this a service at a time instead of having to do all services at once. From what I see, it is just a single enable/disable flag on the server to say whether it decrypts or not. It would be great if there was a way you can specify that some values are to only be decrypted by the client (e.g. {cipher:client}).

**Comment by ryanjbaxter** [comment]
I don't believe there is a way to do that today.  Is there a reason why everything couldnt be decrypted on the client?
