### ISSUE TITLE
VaultEnvironmentRepository should be annotated with @Validated

### ISSUE THREAD

**Issue by jearton** [spring-cloud/spring-cloud-config#871]
Or WARNING messaes will be printed.

**Comment by ryanjbaxter** [comment]
Are you referring to this? https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-validation.html

**Comment by jearton** [comment]
I'm referring to this: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes

>@ConfigurationProperties validation
If you have @ConfigurationProperties classes that use JSR-303 constraint annotations, you should now additionally annotate them with @Validated. Existing validation will currently continue to work, however, a warning will be logged. In the future, classes without @Validated will not be validated at all.
