### ISSUE TITLE
The DEFAULT_SQL of JdbcEnvironmentRepository 

### ISSUE THREAD

**Issue by carvinhappy** [spring-cloud/spring-cloud-config#876]
The DEFAULT_SQL of JdbcEnvironmentRepository is "SELECT KEY, VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?".  The KEY column is mysql's keyword , execute this sql will get an error "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'KEY, VALUE from PROPERTIES where APPLICATION='testing' and PROFILE='dev' and LAB' at line 1".

Thanks a lot .

**Comment by spencergibb** [comment]
You can change the SQL using `spring.cloud.config.server.jdbc.sql`

**Comment by carvinhappy** [comment]
I was changed it using the "spring.cloud.config.server.jdbc.sql" .
