### ISSUE TITLE
Multiple Git Repo Not Working

### ISSUE THREAD

**Issue by iceycake** [spring-cloud/spring-cloud-config#88]
It seems the repos.patterns are being replaced by the index value of the map.  For example,

<pre>
repos:
   - patterns: *pattern1
   - uri: https://github.com/pattern1/config-repo
</pre>

It turns out the Map object repos in MultipleJGitEnvironmentRepository becomes

{"1", "https://github.com/pattern1/config-repo"} instead of {"*pattern1","https://github.com/pattern1/config-repo"}

**Comment by iceycake** [comment]
It may be related to how Spring DataBinder works with Map properties?

**Comment by dsyer** [comment]
The YAML is wrong (it's a map not an array, and you need to provide a key). Look at the sample in the git log or in the user guide.

**Comment by iceycake** [comment]
May be the doc is not up to date after the merge?  It is still showing the same one I had contributed.

http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html

<pre>
spring:
  cloud:
    config:
	  server:
	    git:
	      uri: https://github.com/spring-cloud-samples/config-repo
	      repos:
	        - patterns: *pattern
	          uri: https://github.com/pattern1/config-repo
	        - patterns: pattern*,*pattern1*
	          uri: https://github.com/pattern2/config-repo
	        - patterns: local*
	          uri: file:/home/configsvc/config-repo
</pre>

**Comment by iceycake** [comment]
Confirmed.  The second example above should be the correct one.  The document for RC3 is out of dated.

**Comment by dsyer** [comment]
That's what is in master (https://github.com/spring-cloud/spring-cloud-config/blob/master/docs/src/main/asciidoc/spring-cloud-config.adoc), but I think you added some docs to the quickstart.adoc as well and that hadn't been updated (fixed in fc48659).
