### ISSUE TITLE
Document "spring.cloud.config.server.encrypt.enabled: false" should go in bootstrap.{properties|yml}

### ISSUE THREAD

**Issue by sunnykaka** [spring-cloud/spring-cloud-config#887]
I have some encrypted strings in application.yml, just like
` "{cipher}AQB3pYMRyzt61ANiBBUO7prB1C0NK/p3Mmv1D3IaVeDXOUNj1GxE/yTCthUNwZEMGFOJR+2Jmx/CdkUUJ6wr4w7zsA1C9JxSFUXTgNSZ3BJmgMiaeljn8jjedS/5IqyO2Nh4NqCDJ293evTCyU8vednxpuVF3qpbB+EHILEFThAukV3rzjXS/b3UiNMzsN5Gwo73tUo2akLHEamnXoNaDT/ioDwGJeGHGSP+mN95jUlhI5FqdSv9Qst+x5MzEbmTxjuju2Vir4rje4Ccp67W6CIIhu+JeWuz/lHIk3PZsQaHO+7qn7gDhKrJiCO6AEYT1Fzp+b9zRbpigH3PxQt4nlOE5FuqjDlDRR48sd76jHAY9bpLYk5od54kWiHx9CzLuy2clU7ldotJdJmpxDmVOnmB"`

I don't want this property decrypted by spring cloud config server, so I add
`spring.cloud.config.server.encrypt.enabled: true` in my configuration.

I use spring cloud config server v1.3.0.RELEASE for a while, everything works fine.
When I upgrade to v1.3.3.RELEASE, the `spring.cloud.config.server.encrypt.enabled: false` seems not work any more. The server decrypted strings for me, it's not what i want.

**Comment by spencergibb** [comment]
Can you try putting spring.cloud.config.server.encrypt.enabled: true in bootstrap.properties?

**Comment by sunnykaka** [comment]
@spencergibb it worked.
That's wired. Why it's not work in application.yml.
It's need to be mentioned in the document.

**Comment by spencergibb** [comment]
I think it is

**Comment by spencergibb** [comment]
Should also be documented in earlier releases (and release notes).

**Comment by ryanjbaxter** [comment]
Closed via  8da878
