### ISSUE TITLE
Getting Error Mapping Messages Via Spring Cloud Config

### ISSUE THREAD

**Issue by terancet** [spring-cloud/spring-cloud-config#893]
Currently, I have the the following properties files
`codes-mapping.properties`
`messages-mapping.properties`

that are located in the `src/main/resources/messages` folder for each application. 

In each application. yml I have explicitly configured to use these files in the following way: 
`error.mappings.messages: messages/messages-mapping`
`error.mappings.codes: messages/codes-mapping`

I would like to move these two files to Spring Cloud Config server under git repo so that each application would have the access to these two files. Simply speaking the following files `codes-mapping.properties` and `messages-mapping.properties` must be shared across all applications for all envs. 

How would I accomplish such task?
NB all applications are running inside PCF and they have the proper bindings to the PCF Spring Cloud Config Server.

**Comment by ryanjbaxter** [comment]
You can have the config server serve up plain text files from the config server if you want http://cloud.spring.io/spring-cloud-static/Edgware.SR1/single/spring-cloud.html#_serving_plain_text

**Comment by terancet** [comment]
@ryanjbaxter , thank for your reply. 

I am little bit confused. As far as I understood documentation, it is sufficient to create the properly named directory in the git repository where I have to place all resource bundles. 

However, https://github.com/spring-cloud/spring-cloud-config/issues/688 points that I have the explictly declare the bean 
`ReloadableResourceBundleMessageSource` and explicitly set the following property ` messageSource.setBasenames("classpath:messages", pathToGitUrl + "/master/messages");` 

Could you please elaborate on this?

**Comment by ryanjbaxter** [comment]
Can you point me to the documentation you are referring to?

**Comment by terancet** [comment]
Here is the link -- [Environment Repository](http://cloud.spring.io/spring-cloud-static/Edgware.SR1/single/spring-cloud.html#_environment_repository).

**Comment by ryanjbaxter** [comment]
I dont see anything in that documentation that relates to this problem.  

But yes you should create a bean of type `ReloadableResourceBundleMessageSource`

**Comment by ryanjbaxter** [comment]
Please comment if this is still an issue.
