### ISSUE TITLE
security.user.* properties with Spring Boot 2 / Finchley do not work anymore

### ISSUE THREAD

**Issue by mpalourdio** [spring-cloud/spring-cloud-config#896]
Hello,

From Spring Boot 2, when setting credentials in bootstrap.properties, the properties referenced in the documentation, ``security.user.password`` && ``security.user.name`` do not work anymore. (ie : an application with ``spring-cloud-starter-config`` can't connect the the Configuration server, credentials are rejected, if they are encrypted)

``spring-boot-properties-migrator`` warns us to replace those by ``spring.security.user.name``&& ``spring.security.user.password``, which works.

Documentation should be updated to reflect this change. I can submit a PR for it, but is there a particular documentation that targets Spring Boot 2 && Finchley ?

The actual documentation section to update is [here](https://github.com/spring-cloud/spring-cloud-config/blob/master/docs/src/main/asciidoc/spring-cloud-config.adoc#security)

Example of a bootstrap.properties at Configuration Server level :
```
spring.security.user.name=user  
spring.security.user.password={cipher}12c545c7e569d579c0b205bfebeef99dcbf07c0d079b4035ce2980ef6ef2301e
```

**Comment by ryanjbaxter** [comment]
This is the file you want to update in the master branch https://github.com/spring-cloud/spring-cloud-config/blob/master/docs/src/main/asciidoc/spring-cloud-config.adoc

**Comment by mpalourdio** [comment]
Thanks for feedback. PR here https://github.com/spring-cloud/spring-cloud-config/pull/900
