### ISSUE TITLE
does not support gitee webHooks

### ISSUE THREAD

**Issue by lly835** [spring-cloud/spring-cloud-config#898]
I use /monitor endpoint. 
```
                <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

                <dependency>
                         <groupId>org.springframework.cloud</groupId>
                         <artifactId>spring-cloud-starter-bus-amqp</artifactId>
                 </dependency>

                 <dependency>
                          <groupId>org.springframework.cloud</groupId>
                          <artifactId>spring-cloud-config-monitor</artifactId>
                 </dependency>
```
https://gitee.com is the most popular git server in China. Hoping to debug, I'll tell gitee result.

**Comment by ryanjbaxter** [comment]
Please provide more information about what the problem is.  Also provide a sample that reproduces the isse.

**Comment by spencergibb** [comment]
There's no handler for the gitee webhook format. This is an enhancement request.

**Comment by lly835** [comment]
@spencergibb Are you going to fit the gitee format?

**Comment by spencergibb** [comment]
At some point. Pull requests welcome. You can implement your own too

**Comment by lly835** [comment]
@spencergibb see https://github.com/spring-cloud/spring-cloud-config/pull/899

**Comment by lly835** [comment]
see https://github.com/spring-cloud/spring-cloud-config/pull/901

**Comment by Mrliangwenbin** [comment]
config配置中心，git是我修改配置文件，然后通过webhooks来请求，请求成功，但是本地的config配置中心配置文件没有改变，如果使用命令形式可以改变本地配置文件（ $ curl -v -X POST "http://localhost:8080/actuator/bus-refresh"）这是为什么呢？求助
