### ISSUE TITLE
Config Server Multiple Git Environmnet- Repos Limit

### ISSUE THREAD

**Issue by praveenkumar-9** [spring-cloud/spring-cloud-config#902]
i am trying to implement multiple git repositories, in my application properties i use repo configuration with patterns,
example : 
 cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          repos:
            - patterns: iceycake-*
              uri: https://github.com/iceycake/config-repo

how many maxiumm repos that i can configure?
please let me know is there any max limit for repos configure in properties?
Thanks for your help.

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

I dont believe there is a max limit.  How many repos are you thinking of configuring?

**Comment by praveenkumar-9** [comment]
Thanks Much @ryanjbaxter  . we would require at max of 20 repos to be configured.

**Comment by ryanjbaxter** [comment]
Like I said there is no limit.  If you want to maintain that configuration that is your choice.
