### ISSUE TITLE
/monitor still secured even with management.security.enabled=false

### ISSUE THREAD

**Issue by REME-AlarmTILT** [spring-cloud/spring-cloud-config#906]
I just updated my project to Spring Cloud Edgware.SR2 and Spring Boot in 1.5.10 (previously on Dalston.SR2 and S.B 1.5.6), now even putting `management.security.enabled=false`, the endpoint `/monitor` still secure (`spring-boot-starter-security`).
It's a new enhancement ? I didn't found anything on documentation about securing `/monitor` separately

**Comment by spencergibb** [comment]
It's not an actuator endpoint, therefore actuator security does not apply

**Comment by REME-AlarmTILT** [comment]
With the previous versions (S.C Dalston.SR2 and S.B 1.5.6) I had the config server secured by basic auth from spring security and the `/monitor` was reachable without the basic auth.
Can i deactivate the basic auth for this specific endpoint `/monitor` ?

**Comment by spencergibb** [comment]
It has never been an actuator endpoint https://github.com/spring-cloud/spring-cloud-config/blob/v1.3.0.RELEASE/spring-cloud-config-monitor/src/main/java/org/springframework/cloud/config/monitor/PropertyPathEndpoint.java#L53 

Normal spring security exclusions would do it.
