### ISSUE TITLE
Package name clash between cloud-connectors and cloud-config

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-config#91]
The "o.s.c.config" package is split between 2 jars. Yuck.

**Comment by spencergibb** [comment]
:-( config was so much more concise.

**Comment by dsyer** [comment]
I know, but someone beat us to it. Do you have another suggestion (it's easy to change now, not so easy after release)?

**Comment by spencergibb** [comment]
configure does seem a bit awkward.  It's not the Configure Server.  It's the Configuration Server.  Maybe `configuration` even though it's longer?
