### ISSUE TITLE
Edgware.SR2 decryption not working

### ISSUE THREAD

**Issue by pradpk** [spring-cloud/spring-cloud-config#910]
I built service and client application (https://github.com/pradpk/spring-cloud-encrypt) pointing to my git repo containing encrypted message. My client was not able to get decrypted message when having spring cloud version as Edgware.SR2.

When I changed to Brixton.SR7, it works fine and I get decrypted message. Can you please check.

**Comment by ryanjbaxter** [comment]
Can you post the repo with the config to use with your sample app?

**Comment by pradpk** [comment]
Repo just has this. I used git with below property file.

message={cipher}{key:mytestkey}AQA5vMmlNQzgFpyqc6LhjRrMiTGu5ShABxJyrEK0M9/muH08GjUHVi5IRiDV0G3Pr0KyUV6sV/uJT3B6KKioD5AuKQzkD9E0+iYxiZlBlvCjxcc2li2mdIZKTn1rpxCkT2QpN9uZfL2NBH/wdEu+w5OLufPo2krxgVd0AvcuaYCCxDPVLH7BMZNWQGiAm9eVAjJjyb52dtQ2WvkWMYlSlCOiA97XdAhuk3HYIwsUBUDYBE2W+8e0YSNGt8RyBrf0NN/YvQI6Bz8GGhW5hhC+pUa9a+oeFMxeLaSiASp4tbqyXF+3PKpl1Z03aU1VZV8M1G8oAnaHsVBTsyshbe5u3hSGsimRytJ3wQAvm6KAvkO9K6Gz6R+mrc2S8Xf5IuLYnsc=

**Comment by ryanjbaxter** [comment]
Move the `encrypt.*` properties in configuration-service to `bootstrap.properties`

**Comment by pradpk** [comment]
I already have encrypt.* properties in bootstrap.properties. I tried to comment them on configuration-service, but it didn't help.

**Comment by pradpk** [comment]
I need version Camden.SR7 since I want to connect to my git bucket using SSH. But the decryption is not working above Brixton.SR7 :(

**Comment by adamklemanovits** [comment]
I have the same problem with version Edgware.SR2. It seems to me that the problem is some kind of ordering issue. The `EnvironmentEncryptor` bean created before the `KeyStoreConfiguration` run. It causes, that the `EnvironmentEncryptor` using a `NoOpTextEncryptor`. 

There is a workaround, if you provide your own `EnvironmentEncryptor` bean like this:
```java
@Bean
public EnvironmentEncryptor environmentEncryptor(TextEncryptorLocator textEncryptorLocator) {
	return new CipherEnvironmentEncryptor(textEncryptorLocator);
}

@Bean
public TextEncryptorLocator textEncryptorLocator(KeyProperties key) {
	KeyProperties.KeyStore keyStore = key.getKeyStore();
	KeyStoreTextEncryptorLocator locator = new KeyStoreTextEncryptorLocator(
		new KeyStoreKeyFactory(keyStore.getLocation(), keyStore.getPassword().toCharArray()),
			keyStore.getSecret(), keyStore.getAlias());
	locator.setRsaAlgorithm(key.getRsa().getAlgorithm());
	locator.setSalt(key.getRsa().getSalt());
	locator.setStrong(key.getRsa().isStrong());
	return locator;
}
```
 which are the same beans as in the `EncryptionAutoConfiguration`, so this is definitely not a long term solution.

**Comment by ryanjbaxter** [comment]
@adamklemanovits can you provide a sample that reproduces the problem?  Again I have tried to reproduce it locally and cannot

**Comment by adamklemanovits** [comment]
yes of course, here the project that i'm working with. 
https://github.com/adamklemanovits/config-encrypt-demo

**Comment by ryanjbaxter** [comment]
After renaming `bootsrap.yml` in `config-server` to `bootstrap.yml` and running your app everything was decrypted fine.  Here is the result of hitting `http://localhost:8888/application/default`

```
{
	"name": "application",
	"profiles": ["default"],
	"label": null,
	"version": null,
	"state": null,
	"propertySources": [{
		"name": "classpath:config/application-default.properties",
		"source": {
			"my.message": "The cake is a lie"
		}
	}]
}
```

**Comment by aklemanovits** [comment]
I fixed the typo, now it's working fine for me too. That was a rookie mistake.
Thanks for the help.
