### ISSUE TITLE
Triggering RefreshEndpoint.refresh does not refresh RefreshScoped beans properly

### ISSUE THREAD

**Issue by raouldh** [spring-cloud/spring-cloud-config#917]
We are currently migrating our application from Spring-boot 1.5.10 and Spring-cloud Dalston.SR5 to Spring-boot 2.0.0.RC1 and Spring-cloud Finchley.M6.
At this moment it seems that the RefreshScoped beans are not getting refreshed properly after calling the RefreshEndpoint.

I created an small example project to test this. see attachment. I configured a spring.config.additional-location to be able change the properties from this location to test the refresh.
[refresh-example.zip](https://github.com/spring-cloud/spring-cloud-config/files/1744228/refresh-example.zip)
bootstrap.properties:
`spring.profiles.active=native
spring.config.location=classpath:/
spring.config.additional-location=file:///C:/conf/
spring.cloud.config.server.native.searchLocations=${spring.config.location},${spring.config.additional-location}
spring.cloud.config.server.bootstrap=true`

To test the refresh I created a Controller and registered an _localhost:8080/get_ methode to get the property value _message_ and a _localhost:8080/refresh_ methode to trigger the refreshEndpoint.refresh().

After triggering the refresh I can see in the log that the refresh is triggered for the property sources configured but my refresh command will timeout, after the timeout the application is closed.
I was expecting that my controller returned with the changed properties and that I am able to retrieve the changed property through: _localhost:8080/get_ 

When you change the spring-boot version to 1.5.10 and the spring-cloud version to Dalston.SR5 in my example project the refresh seems to works normally. I can retrieve my changed message property through _http://localhost:8080/get_

**Comment by ryanjbaxter** [comment]
Have your tried Edgware.SR2?

**Comment by raouldh** [comment]
Yes, same issue on Edgeware.SR2.
I noticed that after the refresh is triggered, the application "hangs" when it acquires a lock in the destroy methode of _org.springframework.cloud.context.scope.GenericScope.java_
This is because I trigger the _Refresh_ from a controller which has the _@RefreshScope_ annotation. When I remove the RefreshScope annotation for this controller the refresh works again.

So it seems that since Edgeware.SR1 you can no longer trigger a refresh from a class/component which has the RefreshScope annotation?

**Comment by ryanjbaxter** [comment]
I dont know if your example is particularly valid.  In a typical setup the controller would be in the config client and you would be calling `/refresh` on the client.  The client would then retrieve the values from the config server.  In you example the controller is inside the config server.  Have you tried separating the two?

**Comment by raouldh** [comment]
At this moment we do not have a separated config-client and config-server. Moving the Refresh endpoint solved the locking problem in the GenericScope class.

But now we are facing an other bug with refreshing properties, but this bug is already reported here: https://github.com/spring-cloud/spring-cloud-commons/issues/290 and https://github.com/spring-cloud/spring-cloud-commons/issues/328

**Comment by rajeshpks** [comment]
@raouldh thanks a lot. your suggestion of moving refresh to different bean solved the issue.
