### ISSUE TITLE
2.0.0.M6 not found in Maven Repository

### ISSUE THREAD

**Issue by mveitas** [spring-cloud/spring-cloud-config#921]
It looks like the 2.0.0.M6 milestone is not published to the spring milestones repo as described here: https://cloud.spring.io/spring-cloud-config/

https://repo.spring.io/libs-milestone/org/springframework/cloud/spring-cloud-consul/

```
<repository>
     <id>spring-milestones</id>
     <name>Spring Milestones</name>
     <url>https://repo.spring.io/libs-milestone</url>
     <snapshots>
         <enabled>false</enabled>
     </snapshots>
</repository>
```

**Comment by spencergibb** [comment]
consul?

https://repo.spring.io/libs-milestone/org/springframework/cloud/spring-cloud-config/
