### ISSUE TITLE
GitHub changed SSH ciphers older dependency on jsch no longer works

### ISSUE THREAD

**Issue by bplies-IAS** [spring-cloud/spring-cloud-config#922]
FYI there has been a change to GitHub's SSH supported crypto
https://www.securityweek.com/github-enforces-stronger-encryption

> retired the diffie-hellman-group1-sha1 and diffie-hellman-group14-sha1 encryption standards, a move that affects all SSH connections to github.com. This change follows the enabling of the diffie-hellman-group-exchange-sha256 standard

We began to see `[http-nio-8888-exec-5] .c.s.e.MultipleJGitEnvironmentRepository : Could not fetch remote for master remote: git@github.com:ACT/repo.git` and with a live debugger to inspect the actual Exception `git@github.com:ACT/repo.git: Algorithm negotiation fail`

Some spring-cloud-config-server pull in com.jcraft:jsch:0.1.50

http://www.jcraft.com/jsch/ChangeLog

> Changes since version 0.1.52:
> - bugfix: the rekey initiated by the remote may crash the session.
> - change: Logjam: use ecdh-sha2-nistp* if available,
>           ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,
>           diffie-hellman-group14-sha1,
>           diffie-hellman-group-exchange-sha256,
>           diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
> - change: Logjam: diffie-hellman-group-exchange-sha256 and
>           diffie-hellman-group-exchange-sha1 will use 2048-bit key on
>           Java8's SunJCE, thanks to JDK-6521495 and JDK-7044060.
> - change: key words for OpenSSH's config file should be case-insensitive.
> - change: there should be the host name in "WARNING: REMOTE HOST
>           IDENTIFICATION HAS CHANGED" message.

This addresses the ciphers referenced in the post.  I've been able to upgrade the jsch dependency and get everything working again.  This means that older builds of spring-cloud-config-server relying on SSH/GitHub will no longer function.

**Comment by doronl** [comment]
+1

**Comment by romach** [comment]
@bplies-IAS 

> I've been able to upgrade the jsch dependency and get everything working again.

Can you describe more detailed, how did you fix this error?

**Comment by bplies-IAS** [comment]
@romach If you're embedding the Config Server 
```
@EnableAutoConfiguration
@EnableConfigServer
@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
```

Then just adjust your `build.gradle` (or Maven pom.xml)
```
dependencies {
    compile "org.springframework.cloud:spring-cloud-config-server:${project.cloudVersion}"
    compile "org.springframework.cloud:spring-cloud-starter-config:${project.cloudVersion}"
    compile "org.springframework.boot:spring-boot-starter-actuator:${project.bootVersion}"
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-security', version:"${project.bootVersion}"
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-web', version:"${project.bootVersion}"
    runtime "org.springframework.boot:spring-boot-starter-tomcat:${project.bootVersion}"
    runtime "com.jcraft:jsch:0.1.53" // #922 Forced upgrade for changed GitHub cipher support
}
```
So if you build and deploy a fat executable Spring Boot jar, you're good to go.

**Comment by spencergibb** [comment]
The version of JSCH is already 0.1.54 in Dalston, Edgware, and Finchley.

**Comment by bplies-IAS** [comment]
Yes upgrading to a more recent `spring-cloud-dependencies` is obviously the best option.  If for _some_ reason that isn't immediately possible or is in any way problematic it appears that `jsch` can be safely overridden as far as `spring-cloud-config` is concerned.  In any case, older versions will no longer work without extra steps. Outside of being a PSA and updating any appropriate docs (deprecations? EOL?) there isn't anything to actually do here.  Thanks.

**Comment by spencergibb** [comment]
Angel and Brixton are already EOL. Camden will be when Finchley is released shortly.
