### ISSUE TITLE
spring cloud config server crashed when called /health endpoint frequently

### ISSUE THREAD

**Issue by zhu0516123** [spring-cloud/spring-cloud-config#923]
I deployed a spring cloud config server on PCF. To get its health  status in real time, I called its /health endpoint every minute. But after a few  days later, config server crashed(**out of memory**). The chart of  memory usage shows that the percentage of memory usage increased stably until it  reached 100%. If I set **spring.cloud.config.server.health.enabled=false**, it would only check the status of diskspace and  refreshscope. And then it ran normally in the way.  There seemed to be memory leak. Why did this happened?

this is the pom.xml file of config server maven project:
```xml
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.5.4.RELEASE</version>
</parent>
<dependencies>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-test</artifactId>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-config-server</artifactId>
    </dependency>
</dependencies>
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Dalston.SR1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```
this is the only java code in the config server project:
```xml
@EnableConfigServer
@SpringBootApplication
public class ConfigServerApplication {
    public static void main(String[] args) {
        SpringApplication.run(ConfigServerApplication.class, args);
    }
}
```
this is the application.properties file in the config server project:
```xml
spring.application.name=config-server

spring.cloud.config.server.git.uri=https://github.com/***/config-server-test
spring.cloud.config.server.git.username=zhu*****
spring.cloud.config.server.git.password=****
```

**Comment by ryanjbaxter** [comment]
Have you tried with Dalston.SR5 or Edgware.SR2?

**Comment by zhu0516123** [comment]
@ryanjbaxter 
Yes. All of them.

**Comment by spencergibb** [comment]
Can you show the chart? Can you tell what was growing? We recommend disabling the health indicator if you hit it that frequently.

**Comment by zhu0516123** [comment]
@spencergibb 
![img_1118](https://user-images.githubusercontent.com/20107856/36707005-60c3986e-1ba7-11e8-8fbc-2b11ad2a8aa0.JPG)
This is the chart of memory usage. It will increase to 100%, and then crash.
Sorry, I want to get the status of config server that need the health indicator.

**Comment by spencergibb** [comment]
Can you say with more precision what objects are leaking?

**Comment by ojhughes** [comment]
We experienced resource leaks with an SCS customer, it looks like there are potential leaks around Jgit's usage `java.util.zip.Inflater/Deflater`  

For example, looking at some of the Jgit code https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/file/PackFile.java#L351-L372 it seems plausible that `Inflater.end()` does not always get called and the heap won't be cleared until finalization.

**Comment by ryanjbaxter** [comment]
Please provide additional information and we will reopen the issue.
