### ISSUE TITLE
[BUG]spring.cloud.config.profile with more than one consecutive commas will fail to startup

### ISSUE THREAD

**Issue by nfd310963321** [spring-cloud/spring-cloud-config#924]
When some set the spring.cloud.config.profile accidently with more than one consecutive commas, the application will fail to startup
![image](https://user-images.githubusercontent.com/13862041/36639414-f1e78880-1a46-11e8-89ea-6fb0c5f2ffb2.png)

As I digg into the code found the following method will throw exception when the variable "label" is blank.
![image](https://user-images.githubusercontent.com/13862041/36639357-15ae646a-1a46-11e8-8a41-f522e69805d4.png)

So is it better that we should filter the blank "label" items?

**Comment by ryanjbaxter** [comment]
Please avoid using screenshots.

Can you provide the stacktrace?
