### ISSUE TITLE
SpringCloud Not encrypting special characters properly

### ISSUE THREAD

**Issue by remo408** [spring-cloud/spring-cloud-config#929]
Team,

I tried encrypting :
`   7  MLTEST m09286   Ya  p¨Ô}¨¤-'—ôÑ_¾«   G  MLTEST m09286   Ya   à Ó{‰é>µÆåó§$¨žÆ—«*þ¼â“mˆ	Ø   ?  MLTEST m09286   Ya  hì,¤‰þýI¼Ð^ºE7µWÄý%«b   7  MLTEST m09286   Ya  5é¥ê(þ'ÉN¡ûKB   /  MLTEST m09286   Ya  T#åŒ[¹€   /  MLTEST m09286   Ya  I—Üò1þ`

With Header :
`[{"key":"Content-Type","value":"text/plain","description":""}]`

But when i decrypt  with text/plain header i get:
`¨¤-'—ôÑ_¾«   G  MLTEST m09286   Ya   à Ó{‰é>µÆåó§$¨žÆ—«*þ¼â“mˆ	Ø   ?  MLTEST m09286   Ya  hì,¤‰þýI¼Ð^ºE7µWÄý%«b   7  MLTEST m09286   Ya  5é¥ê(þ'ÉN¡ûKB   /  MLTEST m09286   Ya  T#åŒ[¹€   /  MLTEST m09286   Ya  I—Üò1þ`

SpringCloud version :<spring-cloud.version>1.3.3.RELEASE</spring-cloud.version>	

Can you please let me know if this is a bug or something i am missing.

Really apprecitae your insight

**Comment by spencergibb** [comment]
needs to be urlencoded.
