### ISSUE TITLE
How to keep data consistent when using @RefreshScope in a execution?

### ISSUE THREAD

**Issue by charlietianx** [spring-cloud/spring-cloud-config#930]
I read this [Dynamic Configuration Properties in Spring Boot and Spring Cloud](https://gist.github.com/dsyer/a43fe5f74427b371519af68c5c4904c7) as @spencergibb  suggested. And it said that

> If your method execution is the one that triggers the initialization, then it all even happens in the same thread.

But in my code it doesn't work.
Here is my code:
**A configuration bean:**
```
package com.my.springdemo.chapter3.test;

import lombok.Data;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;

@component
@DaTa
@refreshscope
public class TestConfig {
@value("${name}")
private String name;

@PostConstruct
private void print(){
    System.out.println("配置为=" + name);
}
}
```

**A controller:**
```package com.my.springdemo.chapter3.test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.cloud.context.refresh.ContextRefresher;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@ConditionalOnClass(ContextRefresher.class)
@RestController
public class TestController {

    @Autowired
    private TestConfig config;

    @Autowired
    private  ContextRefresher contextRefresher;

    @RequestMapping("/config")
    public String config(){
        System.out.println("before config= " + config.getName() + ", hasCode=" + config.hashCode());
        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        contextRefresher.refresh();
        System.out.println("After config= " + config.getName() + ", hasCode=" + config.hashCode());
        return config.getName();
    }

}
```

Then get url: http://localhost:8080/config, and changed config "name" in my "application.properties" during the thread sleep time(which id 10 seconds as the code shows).

It turns out that the config "name" is changed before and after. Why?Does I take @RefreshScope the wrong way?

**Comment by ryanjbaxter** [comment]
Could you put your code in a github repo or in a zip?

**Comment by charlietianx** [comment]
@ryanjbaxter I want give u my code but the RefreshScope not working again since I modified it  to find new ways to solve my problem.Don't know why.
  Anyway my question is does RefreshScope can ensure a bean doesn't updated during the method execution.In my example the configuration 'name' changed after 

> contextRefresher.refresh()
  I asked someone, and they say that RefreshScope can't do this.Because the target is changed and a  new bean is generated after refreshing and therefore when invoke config.getName(), which config is the bean annotated with RefreshScope, it invokes the target bean's method actually.Does I understand it correctly?
  What I'm confusing now is if so, what's the difference between ConfigurationProperties and RefreshScope if I just want my configuration bean updated as soon as the refresh() is invoked?

**Comment by ryanjbaxter** [comment]
I believe that the properties would not be refreshed in the middle of a method execution because as you said a new bean will get created when the context is refreshed.

> What I'm confusing now is if so, what's the difference between ConfigurationProperties and RefreshScope if I just want my configuration bean updated as soon as the refresh() is invoked?

Not really sure what you are asking.  Your `ConfigurationProperties` would be updated when you refresh the context, assuming they have changed.

**Comment by charlietianx** [comment]
[test-refresh](https://github.com/charlietianx/demo-java/tree/master/test-refresh)
This is my test code.Just start the application, then get 'http://localhost:8080/config' and change the property 'name' in application.properties manually.It print different names before and after the refresh().

It means that if a bean is annotated by RefreshScope, it will be modified if the refres() method is invoked.

I want a config bean(like TestConfig in my code) doesn't change during the the same method execution to keep data consistent even if someone changes the configuration file and invokes the refresh().

**Comment by dsyer** [comment]
I think you are expecting too much of the refresh scope. You can't expect a method execution in a singleton bean (your controller) to know that its method calls are tied to a refresh scope lifecycle. To do that you would need to do some manual synchronization (e.g. to make a deep copy of the config bean).

**Comment by charlietianx** [comment]
Thanks for the answer.I think I should find another way to solve my problem.
