### ISSUE TITLE
Document new composite yml config

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-config#933]
See #616 
@pivotal-dylan-roberts

/cc @csterwa

**Comment by spencergibb** [comment]
Transpose SCS documentation from docs.pivotal.io/spring-cloud-services/1-5/common/config-server/composite-backends.html to OSS Config Server

**Comment by ojhughes** [comment]
⬆️ @fifthposition

**Comment by fifthposition** [comment]
@spencergibb I'm working on this but on a different issue: pivotal-cf/docs-spring-cloud-services#116.

If the old method for a composite backend (single backend of each type, using separate keys) is to be deprecated, I think we could mention that in this documentation. LMK how to approach that.

**Comment by spencergibb** [comment]
@fifthposition this documentation needs to go in open source where there was no previous concept. I don't know that it makes sense to reference the spring cloud services documentation here. The other way around makes sense.

**Comment by fifthposition** [comment]
@spencergibb Definitely agree. I've submitted #1041, which fixes this issue. We don't mention SCS in OSS with this PR; if we can put this info in OSS, I'm hoping for SCS to reference OSS instead.
