### ISSUE TITLE
Quickstart page should explain bootstrap.yml

### ISSUE THREAD

**Issue by davidje13** [spring-cloud/spring-cloud-config#937]
Hi, I've just lost multiple hours due to a confusion around how the Spring Cloud Config configuration works which I think could be fixed with a small documentation update.

The quickstart guide at https://cloud.spring.io/spring-cloud-config/ mentions "As long as Spring Boot Actuator and Spring Config Client are on the classpath any Spring Boot application will try to contact a config server on `http://localhost:8888` (the default value of `spring.cloud.config.uri`)" but does not mention that `spring.cloud.config.uri` lives in `bootstrap.yml` rather than `application.yml`.

I'm sure this is explained elsewhere but it's easy to make an incorrect assumption early on and difficult to spot it later. A brief note explaining where the configuration lives on this page would have saved me a lot of time.

**Comment by dsyer** [comment]
We can certainly change the quick start. Careful with the wording though - nothing “lives in bootstrap.yml”: it just gets parsed earlier than application.yml. Eg you could have used an env var or system property just as well.
