### ISSUE TITLE
Question: How do you decrypt properties fetched using MultipleJGitEnvironmentRepository

### ISSUE THREAD

**Issue by harshanair** [spring-cloud/spring-cloud-config#941]
Question: I've customized my config server to use MultipleJGitEnvironmentRepository  to fetch configurations based on custom search paths.  As a result the encrypted properties within the configurations are not being decrypted.(I understand the request to fetch properties through EnvironmentEncryptorEnvironmentRepository.findOne decrypts the values)

How do I decrypt the properties fetched through MultipleJGitEnvironmentRepository.findOne()

**Comment by ryanjbaxter** [comment]
You can just wrap `MultipleJGitEnvironmentRepository` in `EnvironmentEncryptorEnvironmentRepository`.
https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/ConfigServerMvcConfiguration.java#L71

**Comment by harshanair** [comment]
Thanks for the quick response Ryan. How would I be providing the EnvironmentEncryptor instance needed? Autowiring doesn't seem to work.

**Comment by ryanjbaxter** [comment]
It is kind of hard to give you a direct answer without seeing some code.  If you are providing your `EnvironmentRepository` as a bean than it should be injected into here https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/ConfigServerMvcConfiguration.java#L65 (Assuming there is a bean of type `ResourceRepository`)

**Comment by harshanair** [comment]
That worked Ryan. Thank you!
