### ISSUE TITLE
Config Server fails to fetch new file in Git.

### ISSUE THREAD

**Issue by dulimitta** [spring-cloud/spring-cloud-config#946]
I am using Spring Cloud Config server version Edgware.SR1, with Git URI.
It is failing to fetch the new configuration files that we add to Git. I had to restart the server.

Is there a configuration property I am missing?

**Comment by spencergibb** [comment]
You've provided nothing that will help us diagnose your problem. Please tell us what version you are using, what the steps are to recreate the problem and what the expected outcome is. If possible, 
can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?

**Comment by dulimitta** [comment]
I am using Spring Cloud Config server version Edgware.SR1.
I have added the following dependencies.

``
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
		</dependency>
``
My configuration is as below.
``
spring.cloud.config.server.git.uri=https://git-url
spring.cloud.config.server.git.username=<username>
spring.cloud.config.server.git.password=<password>

``
I have added @EnableConfigServer on the main class.

**Comment by spencergibb** [comment]
What version of spring boot?

> what the steps are to recreate the problem and what the expected outcome is. If possible,
can you provide a complete, minimal, verifiable sample that reproduces the problem?

**Comment by dulimitta** [comment]
Spring Boot 1.5.9.RELEASE

**Comment by spencergibb** [comment]
Ok. Without a project that recreates the issue, we won't be able to help

**Comment by dulimitta** [comment]
@spencergibb, the application is behaving well after a couple of restarts. I could not get the rot cause. I am closing the issue for now. Thank you.
