### ISSUE TITLE
/actuator/refresh Can't access

### ISSUE THREAD

**Issue by zhongzunfa** [spring-cloud/spring-cloud-config#950]
I use spring boot2.0 + spring cloud Finchley M7 to create config-server and config-client， when I visit /actuator/health return info, but when I visit /actuator/refresh having error.

{
    "timestamp": "2018-03-26T03:48:54.604+0000",
    "status": 403,
    "error": "Forbidden",
    "message": "Forbidden",
    "path": "/actuator/refresh"
}
![image](https://user-images.githubusercontent.com/14095698/37886226-4d331aae-30ec-11e8-87d8-09a312ff3258.png)

![image](https://user-images.githubusercontent.com/14095698/37886158-cf3a352e-30eb-11e8-96ea-9705e97d3b27.png)

my config 
![image](https://user-images.githubusercontent.com/14095698/37886177-f5f419fa-30eb-11e8-97ab-76b9629211d1.png)

![image](https://user-images.githubusercontent.com/14095698/37886184-0a7cf694-30ec-11e8-93b1-376bfa1ba8d8.png)

**Comment by spencergibb** [comment]
Hmm, I doubt this had anything to do with spring cloud. Can you provide a project that reproduces the problem?

**Comment by zhongzunfa** [comment]
Hello, this is the project address.
https://github.com/zhongzunfa/spring-cloud-test

**Comment by zhongzunfa** [comment]
@spencergibb  can you tell me whay?  and How do I solve this problem?

**Comment by spencergibb** [comment]
Not this week. I'm away from work

**Comment by tdanylchuk** [comment]
Try to add `management.security.enabled=false` as actuator's endpoints are restricted by default

**Comment by zhongzunfa** [comment]
@tdanylchuk The new version is not management.security.enabled。 this is spring boot 1.x 
![image](https://user-images.githubusercontent.com/14095698/38006148-6e84d70c-3276-11e8-812d-a7d71d8b9468.png)

**Comment by tdanylchuk** [comment]
Sorry, didn't notice about boot version.

As for issue - I guess it's better to move this to spring boot issues as it's not related to config.
In spring boot CsrfFilter does not allow POST requests. Only `GET", "HEAD", "TRACE", "OPTIONS` allowed.

For more info take a look on CsrfFilter.DefaultRequiresCsrfMatcher class.

**Comment by zhongzunfa** [comment]
Hmm, I already mentioned that before. this is address : https://github.com/spring-projects/spring-boot/issues/12536
but tell me, 
![image](https://user-images.githubusercontent.com/14095698/38029100-889335fc-32c7-11e8-8f25-d78b1d8f39c8.png)

**Comment by tdanylchuk** [comment]
try 
`@Bean
public SecurityWebFilterChain securityWebFilterChain(
  ServerHttpSecurity http) {
    return http.authorizeExchange()
      .pathMatchers("/actuator/**").permitAll()
      .anyExchange().authenticated()
      .and().build();
}`

**Comment by zhongzunfa** [comment]
I try to do it. but
![image](https://user-images.githubusercontent.com/14095698/38071887-7b27ef2c-3356-11e8-92e2-90999dd87202.png)

**Comment by tdanylchuk** [comment]
Well it was hard and not obvious, but I finally got the expected result with your source code.
You change ` protected void configure(HttpSecurity http)`
add `http.csrf().disable();`
And add:
`
      <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-rsa</artifactId>
            <version>1.0.5.RELEASE</version>
        </dependency>
`
to client-refresh pom.

**Comment by zhongzunfa** [comment]
@spencergibb can you tell me whay? and How do I solve this problem?

**Comment by zhongzunfa** [comment]
@spencergibb How should I configure it?

**Comment by spencergibb** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?

**Comment by zhongzunfa** [comment]
@spencergibb  this is the project address.
https://github.com/zhongzunfa/ch11-2.git

**Comment by spencergibb** [comment]
Finchley.M9 is the latest release, can you please update to it?

**Comment by zhongzunfa** [comment]
Ok, I'll give it a try.

**Comment by zhongzunfa** [comment]
I just tried it, but I can't.

![Uploading image.png…]()

I find post method ， can't acess. I don't known Where is the wrong configuration.

**Comment by spencergibb** [comment]
Did you try https://github.com/spring-cloud/spring-cloud-config/issues/950#issuecomment-377180581. This was the solution.

**Comment by zhongzunfa** [comment]
@tdanylchuk @spencergibb Thank you for the answer

**Comment by deepaumakanth** [comment]
@tdanylchuk tdanylchuk  I got it working the way you have but I would like to autneticate the /refresh url alone, 
and the server authenticates it giving me a 401, what would be the crendential that I will need to provide for the /refresh endpoint? 

http.authorizeExchange()
		    .pathMatchers("/actuator/refresh").authenticated()
	   		.anyExchange().permitAll().and().csrf().disable();
