### ISSUE TITLE
local propertity can't override remote propertity

### ISSUE THREAD

**Issue by wzshuang** [spring-cloud/spring-cloud-config#951]
config server:
in bootstrap.properties:
![3333333333333333](https://user-images.githubusercontent.com/8585771/37899801-16724e12-311f-11e8-9aac-0ef5b80d0cbc.png)

![1111111111111](https://user-images.githubusercontent.com/8585771/37899358-e63636ec-311d-11e8-9140-7dc0a0a955c3.png)

config client:
in application.properties:
![222222222](https://user-images.githubusercontent.com/8585771/37899431-161a4cc2-311e-11e8-9060-5a1f00789169.png)

property "file" exists in both local and remote, but its value is always "cloud-config-client-dev", 
I run command `java -jar app.jar --port=9999` and the port still not be overrided.

how to override local properties?

**Comment by ryanjbaxter** [comment]
Documentation is here
http://cloud.spring.io/spring-cloud-static/Finchley.M9/single/spring-cloud.html#overriding-bootstrap-properties

If you think it is not working then please provide actual code via a git repo or zip file instead of screenshots.

**Comment by wzshuang** [comment]
Thank you for your replay.
Before I open this issue, I have read the documents and other issues, and checked my code several times, but I can't figure out where went wrong.
I have upload my code to my git repo: [cloud-system](https://github.com/wzshuang/cloud-system.git)
first start cloud-config-server, then start cloud-config-client.
config-server: http://localhost:8000/foo/development
 config-client: http://localhost:9000
the "bar" value is expected equals to "localProperties", but shows "spam", which means client properties doesn't override server properties.
pls help me out, thank you very much.

**Comment by ryanjbaxter** [comment]
We no longer support the Brixton release train, please try with the latest Dalston or even better the latest Edgware release.

**Comment by wzshuang** [comment]
@ryanjbaxter 
thanks, I have updated the version to Edgware release and committed to my repo, but local propertity still can't override remote propertity.

**Comment by wzshuang** [comment]
@ryanjbaxter  Yes, it worked!
"allowOverride" should put in remote property source, not remote server's config source, that's what I misunderstand, sorry for wasting you so much time, thanks a lot.
