### ISSUE TITLE
ConfigServicePropertySourceLocator initialization fails when another Configuration enables RetryConfiguration 

### ISSUE THREAD

**Issue by tobiaswolf** [spring-cloud/spring-cloud-config#958]
Hi,

Setting the Property `spring.cloud.config.fail-fast=true` in my application will match the Configuration `org.springframework.cloud.config.client.ConfigServiceBootstrapConfiguration.RetryConfiguration`.
This Configuration enables the import of the more common `org.springframework.retry.annotation.RetryConfiguration`, which builds the featured Proxy around the `org.springframework.cloud.config.client.ConfigServicePropertySourceLocator`.

The Problem starts when another, custom configuration made use of `@EnableRetry`-Annotation, and the Property `spring.cloud.config.fail-fast` is not set.

**The application fails with:** `A component required a bean named 'configServerRetryInterceptor' that could not be found.` 
The ment component is the `org.springframework.cloud.config.client.ConfigServicePropertySourceLocator`.

I am using the `spring-cloud-config-client` in version `1.4.2` with `spring-retry` `1.2.2` (versions are managed from spring-cloud-dependencies I think)

Greetings
Tobias

**Comment by ryanjbaxter** [comment]
Can you please provide a sample that reproduces this?

**Comment by tobiaswolf** [comment]
Hi Ryan,

I reproduce the behavior with the `spring-cloud-config-sample` project as follows:

Added an configuration-file

```
@EnableRetry(proxyTargetClass = true)
@Configuration
public class MyConfiguration {
}
```

Added a `spring.factories` file with in a `META-INF` folder under `resources`
```
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
sample.MyConfiguration
```

And these two dependencies in the `pom.xml`
```
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-aop</artifactId>
</dependency>

<dependency>
<groupId>org.springframework.retry</groupId>
<artifactId>spring-retry</artifactId>
<version>1.2.2.RELEASE</version>
</dependency>
```

**Comment by spencergibb** [comment]
That's not a sample. 
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? (A full project).

**Comment by tobiaswolf** [comment]
Sorry, my fault. Commit can be found under https://github.com/tobiaswolf/spring-cloud-config-sample

**Comment by ryanjbaxter** [comment]
You POM is not configured correctly.  You parent should not be the config server, it should be spring boot.  You need a dependency management section to add the spring cloud pom.  Please generate a proper application that uses Spring Cloud and try again.  I suggest you start from start.spring.io.  Or from here http://projects.spring.io/spring-cloud/

**Comment by tobiaswolf** [comment]
Ok, here is a sample generated with start.spring.io, https://github.com/tobiaswolf/config-client-demo

**Comment by spencergibb** [comment]
I think I have a fix that I'll run by @dsyer

**Comment by spencergibb** [comment]
Why do you have in `META-INF/spring.factories`?
```
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
com.example.demo.MyConfiguration
```

**Comment by tobiaswolf** [comment]
I have written an `PropertySourceLocator` (for a custom property source) which has to be initialized in the bootstrap of the application. I follow the approach of the _spring-cloud-config-client_ or _spring-cloud-vaul_t which does the same. This is the short version of the story.

I am not 100% sure if this is the best way to integrate our config-server, but looking at the spring sources and reading more about the initialization phases of spring-boot applications in an cloud nativ environment - it made sense to me to implement an own `PropertySourceLocator` and initialize this component with the `org.springframework.cloud.bootstrap.BootstrapConfiguration` hook.

**Comment by spencergibb** [comment]
@tobiaswolf did you ever come to a satisfactory conclusion

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
