### ISSUE TITLE
spring-cloud-config can't work

### ISSUE THREAD

**Issue by 15838028035** [spring-cloud/spring-cloud-config#959]
HI, i have a project on github
https://github.com/15838028035/weixindev.git
there's a file READMe.md ,  when i run config-server project ,
http://localhost:9004/front-app/dev
but error,  can't fetch from 
https://github.com/15838028035/weixindev

could you help me ?

**Comment by spencergibb** [comment]
Unfortunately, that's too complicated, please create a minimal sample that recreates the problem.

**Comment by feinoah** [comment]
你自己添加了security控制
ps:优化下.gitignore文件，.class文件都传上来了
