### ISSUE TITLE
If @RefreshScope is added, @RabbitListener does not work

### ISSUE THREAD

**Issue by michelzanini** [spring-cloud/spring-cloud-config#96]
When I have my bean declared like this:

```java
@Component
public class Consumer {
	
	@RabbitListener(queues = { "queue" })
	public void process(Message message) {
		System.out.println(message.toString());
	}

}
````

It works and messages are delivered to the Cosumer.process() method.
But, if I include @RefreshScope then the Consumer does not receive messages anymore.

```java
@Component
@RefreshScope
public class Consumer {
	
	@RabbitListener(queues = { "queue" })
	public void process(Message message) {
		System.out.println(message.toString());
	}

}
````

I would like to know if this is a know limitation or a bug.

**Comment by dsyer** [comment]
Probably the proxy created by `@RefreshScope` is masking the `Consumer` methods because they aren't part of an interface. Did you try `@RefreshScope(proxyMode=TARGET_CLASS)`?

**Comment by michelzanini** [comment]
I tried @RefreshScope(proxyMode=TARGET_CLASS) and tried to create an interface as well, did not work. Also tried @RefreshScope(proxyMode=INTERFACES) and other combinations.
Maybe I am doing something wrong =/
I am using Spring Boot 1.2.2 and Cloud Config 1.0.0-BUILD-SNAPSHOT

**Comment by dsyer** [comment]
I think there's a problem with the way that Spring AMQP processes scoped proxies. I could work around it by adding a bean definition like this:

```
@Bean
public SmartInitializingSingleton smart(ApplicationContext context) {
	return () -> {context.getBean(Consumer.class).process(null);};
}	
```

(forcing the `Consumer` to initialize on start up but lazily). I'll continue to dig into the Spring AMQP implementation.

**Comment by michelzanini** [comment]
I tried the workaround and it did work. 

What I really want to do what something like this:

```java
@Component
@RefreshScope
@ConditionalOnProperty(name = "readOnlyMode", havingValue = "false")
public class Consumer {

    @RabbitListener(queues = { "queue" })
    public void process(Message message) {
        System.out.println(message.toString());
    }

}
```

So basically the idea was that I could, using Spring Cloud Config, disable my Rabbit consumers by setting a property `readOnlyMode`to `true`.
That will then make my application read-only, because the only thing that can write to a database it's when a message get's processed. So changing to `readOnlyMode` with no restart is really powerful.

But I am not quite sure if the `@ConditionalOnProperty` will be evaluated again when `/refresh` endpoint is called and the bean is refresh.

What do you think? Would that be possible?

**Comment by dsyer** [comment]
The purpose of `@RefreshScope` is to change the instance of a `@Bean` and you want to do more than that, really (the listener bean and the container that activates it). I think it's probably easier to just stop and start your listeners using the `Lifecycle` interface. Spring Cloud exposes it through the /pause and /resume endpoints, which stop and start all `Lifecycles`, or you could write your own component that responded to an `EnvironmentChangeEvent` if you prefer to do it through a property change. If you *really* want to use `@RefreshScope` then it's the `MessageListenerContainer` that you would need to concentrate on, not the listener itself.

**Comment by arypanda** [comment]
@michelzanini, Were you able to achieve this - Use `@RefreshScope` along with `@ConditionalOnProperty`?

I'm trying to do a similar thing for a `@RestController` so the endpoints can be turned on/off on demand.
