### ISSUE TITLE
spring.cloud.config.uri does not use KubeDNS to resolve the IP Address

### ISSUE THREAD

**Issue by cdavisafc** [spring-cloud/spring-cloud-config#967]
I am running SCCS as a pod in Kubernetes and in the configuration for my SCCS client include the following:

```
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://sccs-svc"
```
Unfortunately, it does not appear that Kube DNS is being consulted to resolve the name sccs-svc - the following line appears in the logs for my client application and then the pod terminates:

`2018-04-08 20:14:59.979  INFO 1 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://sccs-svc
`

Referring to the sccs directly by IP address works fine.

**Comment by cdavisafc** [comment]
It acts as any other DNS. For example, I can just give REST template a URI with a name in it, i.e. "http://posts-svc/posts" and it will get the IP address from KubeDNS.

I wondered whether because sccs is resolving the config URI very early in the bootstrapping process whether the address for Kube DNS is not yet available?

**Comment by spencergibb** [comment]
reading about it https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ it seems you need to provide the namespace as well, if it is outside current pod. @georgeharley or @jkschneider might know a bit more.

**Comment by georgeharley** [comment]
Hi @cdavisafc, I think you need to include the target config server service's port number in the injected `SPRING_CLOUD_CONFIG_URI` environment variable so it looks something like `http://sccs-svc:8080` or whatever the service's port number is.

**Comment by cdavisafc** [comment]
@spencergibb - agreed, if it's in a different namespace you need a longer name - but it's not in a different namespace in my deployment.

@georgeharley Very good point! I bet you are right. I will give it a shot and report back. Thank you!

**Comment by cdavisafc** [comment]
@georgeharley you were absolutely right! I just needed the port!

Thank you both for the help!
