### ISSUE TITLE
config server using vault but Unable to display source node

### ISSUE THREAD

**Issue by zhongzunfa** [spring-cloud/spring-cloud-config#968]
I use vault as the configuration. 
config-client can't show source node , but postman can show info.
client config : 
![image](https://user-images.githubusercontent.com/14095698/38490009-7e298d9e-3c1a-11e8-91fe-2831081fd6e8.png)

client launch:
![image](https://user-images.githubusercontent.com/14095698/38490085-a99d7e18-3c1a-11e8-8723-530b654e1d79.png)

postman show : 
![image](https://user-images.githubusercontent.com/14095698/38490131-cfc2271a-3c1a-11e8-93c1-a82eef83ab9e.png)

I am debug the config server having info , but client can't show source info.

**Comment by ryanjbaxter** [comment]
Why do you expect it to show the source in the logs?

**Comment by zhongzunfa** [comment]
How do I get the foo parameter? in config client ? 
becase I can't get parameter for this code.

![image](https://user-images.githubusercontent.com/14095698/38532214-56a7ecde-3ca6-11e8-86d7-8e1f83db029e.png)

when I start the config client.
![image](https://user-images.githubusercontent.com/14095698/38532276-a4db1d86-3ca6-11e8-9e26-9050296612f4.png)

**Comment by spencergibb** [comment]
Have you set `spring.application.name`? This is what config server uses to look up an application, not spring cloud config name.

**Comment by zhongzunfa** [comment]
this is config.
![image](https://user-images.githubusercontent.com/14095698/38533328-645fc04a-3cab-11e8-8134-8dbd9899b1f6.png)

![image](https://user-images.githubusercontent.com/14095698/38533341-6fb0e3de-3cab-11e8-9837-db2b0e3bb79a.png)

![image](https://user-images.githubusercontent.com/14095698/38533379-a2c2fe1a-3cab-11e8-9ed5-c42d1b72369c.png)


but, I start the config client , I cant debug config server.
![image](https://user-images.githubusercontent.com/14095698/38533581-96faf492-3cac-11e8-8baf-e9b6e0ba2ad6.png)
![image](https://user-images.githubusercontent.com/14095698/38533801-72b17510-3cad-11e8-9b1f-dc892d7646b2.png)

**Comment by spencergibb** [comment]
Unfortunately, there's not much we can do with the information and screenshot you've provided. 
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?

**Comment by zhongzunfa** [comment]
Hmm, I don't know why. I restart it cant work and cant get paramter.
![image](https://user-images.githubusercontent.com/14095698/38534750-71f30ee0-3cb2-11e8-8eb4-627905b973b6.png)

**Comment by zhongzunfa** [comment]
I haven't changed anything.

**Comment by spencergibb** [comment]
> Unfortunately, there's not much we can do with the information and screenshot you've provided.
> Can you provide a complete, minimal, verifiable sample that reproduces the problem?

**Comment by zhongzunfa** [comment]
this is the project address.
https://github.com/zhongzunfa/ch13-1.git

**Comment by spencergibb** [comment]
What about vault? Did you try setting `spring.application.name=myapp`?

**Comment by zhongzunfa** [comment]
Yes about vault , I don't try setting spring.application.name=myapp,  I am all setting in project 
https://github.com/zhongzunfa/ch13-1.git

**Comment by spencergibb** [comment]
try setting spring.application.name=myapp. That's how config server works.

**Comment by zhongzunfa** [comment]
the config server setting spring.application.name=myapp, or other , It still works. 
and I find changing spring.cloud.config.name=myapp or application, the config client can get different paramter.
![image](https://user-images.githubusercontent.com/14095698/38538089-d41fd9ec-3cc4-11e8-9f10-57b7e011e183.png)


I think it is right. Isn't my understanding wrong?

**Comment by ryanjbaxter** [comment]
`spring.application.name` should be set in the client not the server

**Comment by HarryEMartland** [comment]
Is this just confusion about which endpoint the application should hit? Rather than /<application name> you should hit /<application name>-<profile>.json (or .yaml or .properties)?

**Comment by spencergibb** [comment]
@HarryEMartland no, the is the config client.
