### ISSUE TITLE
Specifying only embedded password in the uri results in Index Out of Bounds Exception

### ISSUE THREAD

**Issue by indraneelb1903** [spring-cloud/spring-cloud-config#970]
So I have been reading  the spring cloud config client code recently and I think i might have stumbled upon a small bug in the code. If I specify only one embedded credential in the uri, this results in Index Out of Bounds Exception which is obvious after taking a look at extractCredentials() method inside the Class ConfigClientProperties. So something like this
```
spring.cloud.config.uri=http://abcd@localhost:8888

```
It also seems like the code seeks to support  if only password is mentioned in the uri(only one embedded credential) after looking at this small snippet.

```

// handle the password only case
if (!userInfo.contains(":")) {

userInfo = userInfo + ":";
			
}


```

If my understanding is correct, I am not sure it does, as it would throw the above exception. Feel free to Correct me If i am wrong.

**Comment by ryanjbaxter** [comment]
So in your example is `abcd` the password?

**Comment by indraneelb1903** [comment]
Yes, it can be considered to be. What my point was if you mention two words separated by : , then it is fine. But if you only mention one, and at least from the code it seems like we want to support only presence of one credential(as default for username is user), it is going to obviously fail.

**Comment by indraneelb1903** [comment]
Hmm, either way, the code needs some refactoring, so we don’t get that exception.

**Comment by indraneelb1903** [comment]
Would love to refactor, once we reach a consensus.

**Comment by spencergibb** [comment]
adding a colon to the url after the username will work around the problem

**Comment by spencergibb** [comment]
PRs welcome

**Comment by indraneelb1903** [comment]
Closing, as this has been rectified.
