### ISSUE TITLE
The default value of "ConfigClientProperties.name" can not work correctly

### ISSUE THREAD

**Issue by Evaim** [spring-cloud/spring-cloud-config#971]
hi, i use "spring cloud config" in non-springboot project, so i created a ConfigClientProperties instance as a default, like this:

```
public class CloudEnvironment extends StandardEnvironment {
    @Overide
    protected void customizePropertySources(MutablePropertySources propertySources) {
        super.customizePropertySources(propertySources);
        ConfigClientProperties configClientProperties = new ConfigClientProperties(this);
        configClientProperties.setName("myapp");
        configClientProperties.setLabel("master");
        configClientProperties.setProfile("rd");
        configClientProperties.setUri("http://localhost:8888/");
        ConfigServicePropertySourceLocator locator = new ConfigServicePropertySourceLocator(configClientProperties);
        propertySources.addLast(locator.locate(this));
    }
}
```

but the ConfigServicePropertySourceLocator.locate method override the default value,
the spring code:

```
public ConfigClientProperties override(
			org.springframework.core.env.Environment environment) {
		ConfigClientProperties override = new ConfigClientProperties();
		BeanUtils.copyProperties(this, override);
		override.setName(
				environment.resolvePlaceholders("${" + ConfigClientProperties.PREFIX
						+ ".name:${spring.application.name:application}}"));
		if (environment.containsProperty(ConfigClientProperties.PREFIX + ".profile")) {
			override.setProfile(
					environment.getProperty(ConfigClientProperties.PREFIX + ".profile"));
		}
		if (environment.containsProperty(ConfigClientProperties.PREFIX + ".label")) {
			override.setLabel(
					environment.getProperty(ConfigClientProperties.PREFIX + ".label"));
		}
		return override;
	}
```

if the environment has no "spring.cloud.config.name" and "spring.application.name" ,then the default value 'application' will be used but not the value 'myapp'  i set previously;
Shouldn't it be "myapp" rather than "application"?
It's bug?

**Comment by ryanjbaxter** [comment]
Spring Cloud is designed to be used with Spring Boot, we cant guarantee how things will work outside of that environment.

**Comment by Evaim** [comment]
@ryanjbaxter 
why the "name" property is overrided by "${spring.cloud.config.name}" or "spring.application.name" or "application" directly:

```
override.setName(
				environment.resolvePlaceholders("${" + ConfigClientProperties.PREFIX
						+ ".name:${spring.application.name:application}}"));
```
why not like :

```
if (environment.containsProperty(ConfigClientProperties.PREFIX + ".profile")) {
			override.setProfile(
					environment.getProperty(ConfigClientProperties.PREFIX + ".profile"));
		}
```

**Comment by ryanjbaxter** [comment]
Not sure what code you are looking at, I dont see that code in `ConfigServicePropertySourceLocator`
https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java#L75

**Comment by Evaim** [comment]
@ryanjbaxter hi, the code:
https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigClientProperties.java#L318

**Comment by Evaim** [comment]
@dsyer

**Comment by ryanjbaxter** [comment]
Its pretty much a requirement that config clients have either of those properties set.  You can achieve the same thing as long as `Environment.resolvePlaceholders` returns the right value.
