### ISSUE TITLE
Escaped variables not properly returned in .json responses

### ISSUE THREAD

**Issue by ogrodnek** [spring-cloud/spring-cloud-config#974]
With an escaped variable in a config file, e.g.

```
a=\${hello}
```

requesting the .yml or .properties will properly remove the `\` before returning the config, returning e.g. `a=${hello}`

requesting .json leaves a single `\` (i.e. `{"a": "\$hello"}` (which also ends up being invalid json (invalid escape sequence)).

I believe this is due to the jackson serialization that happens before the property resolution [EnvironmentController.labelledJsonPropertes](https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentController.java#L169).

[objectMapper.writeValueAsString](https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentController.java#L169) will double up the `\`s to make the resulting JSON valid (`\$` would be an invalid escape), so you end up with `\\${hello}`

[EnvironmentPropertySource.resolvePlaceholders](https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/EnvironmentPropertySource.java#L25) only deals with one `\`.

So, .yml/.properties end up with correct/unescaped vars, but .json will return the `\` (and possibly cause downstream errors).

**Comment by ryanjbaxter** [comment]
Want to submit a PR?

**Comment by ogrodnek** [comment]
@ryanjbaxter Yes, I can do that.
