### ISSUE TITLE
spring.cloud.config.server.git.basedir can not work in 1.3.0.RELEASE

### ISSUE THREAD

**Issue by sunnykaka** [spring-cloud/spring-cloud-config#979]
In Linux, config server uses `/tmp` directory as default to store repository.

According to the document: 
> WARNING: With VCS based backends (git, svn) files are checked out or cloned to the local filesystem. By default they are put in the system temporary directory with a prefix of `config-repo-`. On linux, for example it could be `/tmp/config-repo-<randomid>`. Some operating systems http://serverfault.com/questions/377348/when-does-tmp-get-cleared/377349#377349[routinely clean out] temporary directories. This can lead to unexpected behaviour such as missing properties. To avoid this problem, change the directory Config Server uses, by setting `spring.cloud.config.server.git.basedir` or `spring.cloud.config.server.svn.basedir` to a directory that does not reside in the system temp structure.

I wan't to change the default directory to '/data', so I add this configuration to application.yml:
```
spring.cloud.config.server.git.basedir: "/data"
```

But it can't work, config server still use '/tmp', anything wrong?
The program has access right to '/data'.

**Comment by sunnykaka** [comment]
I have checked the source code and found the problem in `AbstractScmAccessor`: 

```java
	protected File createBaseDir() {
		try {
			final Path basedir = Files.createTempDirectory("config-repo-");
			Runtime.getRuntime().addShutdownHook(new Thread() {
				@Override
				public void run() {
					try {
						FileSystemUtils.deleteRecursively(basedir);
					}
					catch (IOException e) {
						AbstractScmAccessor.this.logger.warn(
								"Failed to delete temporary directory on exit: " + e);
					}
				}
			});
			return basedir.toFile();
		}
		catch (IOException e) {
			throw new IllegalStateException("Cannot create temp dir", e);
		}
	}
```

This code use `/tmp` directly and ignore `spring.cloud.config.server.git.basedir` configuration.
`final Path basedir = Files.createTempDirectory("config-repo-");` 
If it's a bug, i would like to commit a patch to fix it.
@spencergibb

**Comment by spencergibb** [comment]
Can you try with the latest version 1.4.3?

**Comment by sunnykaka** [comment]
@spencergibb 
It's work in v1.4.3, the issue can be closed, thanks.

**Comment by sunnykaka** [comment]
@spencergibb 
Hi, it's another little problem.
I set to:
```
spring.cloud.config.server.git.basedir: "/data/config-server"
```

But the log output is: 
```
Adding property source: file:/D:/data/config-repo-2519517961885230366/application.yml
```
It looks like config server use '/data' rather than '/data/config-server'.

in version v1.4.3.RELEASE
