### ISSUE TITLE
Vault K/V Version 2 Secret Engine

### ISSUE THREAD

**Issue by HarryEMartland** [spring-cloud/spring-cloud-config#993]
I have just started playing around with Vault backend from what I understand there is a new version of the key value secret engine in vault which has changed the api. This has broken the integration with spring boot config server.

I tried setting `spring.cloud.config.server.vault.backend=secret/data` which pulled back the properties but they were all prefixed with data. I think this is due to the api change having two nested data fields.

Does anyone know a way to get the new version of vault working using the new secret engine?

I am happy to look into this and do a pull request. If so should the current VaultEnvironmentRepository support both versions or should a new Vault2EnvironmentRepository be created?

**Comment by ryanjbaxter** [comment]
@markpollack any ideas?  I was not aware of this.

**Comment by spencergibb** [comment]
@mp911de is the right one. He's been working on things in spring-vault and spring-cloud-vault. I wasn't aware that it wasn't backward compatible.

**Comment by ryanjbaxter** [comment]
Ooops my bad, to many Mark's :)

**Comment by mp911de** [comment]
Basically what @HarryEMartland said: Vault 0.10.0 introduced a versioned key-value backend (k/v backend version 2) that exposes a different API than earlier versions (Vault 0.9.6, k/v backend version 1). There are a couple of aspects that play into this Vault change:

1. The versioned key-value backend requires a `data/` segment between the mount path and the actual context path. So `secret/my-app/foo` (v1) becomes `secret/data/my-app/foo` (v2).
2. The versioned key-valued backend secrets are wrapped in a `data` JSON object. So `{"key": "foo"}` (v1) becomes `{"data": {"key": "foo"}}` (v2).
3. Vault 0.10.0 allows activation of the version 1 (non-versioned) and the version 2 (versioned) k/v backends. By default, a newly spun up Vault server mounts the versioned k/v backend at `secret/` which breaks all existing client implementations.
4. There's no way to discover which version is mounted by the request/response itself. Vault 0.10.0 had support for a request header where all requests were served in the new format. However, Vault 0.10.1 removes this request header/request downgrading (`X-Vault-Kv-Client: v2`) and so we're left with a broken change. 

The native Vault client performs a preflight request to mount metadata (`GET /v1/sys/internal/ui/mount/{path}`, read `options.version` from the JSON response) to use the proper API for key-value backends.

For Spring Cloud Config I suggest adding a config flag, that controls which API version is used and adapting the new API in a static way. I don't recommend using internal API as Vault is quite volatile in regard to API stability. For Spring Cloud Vault, I took the same approach, exposing dedicated support for Key Value version 2 (see [0], [1]). 


[0]: https://github.com/spring-cloud/spring-cloud-vault/issues/209
[1]: https://github.com/spring-cloud/spring-cloud-vault/commit/165f666141ae18ab3adfd0778f9c183430bf015f#diff-71747325874075ac2c4d9f5ad0e8c631R574

**Comment by HPacquee** [comment]
I've taken the liberty to create a small [pull request](https://github.com/spring-cloud/spring-cloud-config/pull/1018) using the suggestions made by @mp911de .

I'll gladly take any feedback on this.

**Comment by ryanjbaxter** [comment]
ping @mp911de

**Comment by mp911de** [comment]
I pushed a polishing commit to the **gh-993** branch on **HPacquee/spring-cloud-config**. @ryanjbaxter #1018 is ready to merge.
