### ISSUE TITLE
filesystem changes to local git repository not being detected

### ISSUE THREAD

**Issue by domi55** [spring-cloud/spring-cloud-config#996]
Hi

Using spring-cloud-config (Finchley.RC1) and defining a local git repository (for example `cloud.config.server.git.uri: file://${user.home}/projects/config-repo`) the refresh event is not broadcasted as mentioned in https://cloud.spring.io/spring-cloud-config/multi/multi__push_notifications_and_spring_cloud_bus.html (triggering the /monitor endpoint manually endpoint works as expected)

when taking a quick look at https://github.com/spring-cloud/spring-cloud-config/blob/171d2b261b8fe8ffff4cbd6d364eddbae311e935/spring-cloud-config-monitor/src/main/java/org/springframework/cloud/config/monitor/FileMonitorConfiguration.java#L190 I can see the `if (resource instanceof FileSystemResource)` check. Unfortunately my `file://` url is recognised as `FileUrlResource` and therefore this check is never true. [`FileUrlResource`](https://github.com/spring-projects/spring-framework/blob/4a57e26d76bf6263098785bcc050e4bf7c29212c/spring-core/src/main/java/org/springframework/core/io/FileUrlResource.java) was introduced with Spring Framework 5.0.2.

Cheers
Domi

**Comment by ryanjbaxter** [comment]
Based on what you have said, this works with Boot 1.5.x and Edgware.SR3?

**Comment by spencergibb** [comment]
I wonder if there was a change in framework that caused the new type we need to account for.

**Comment by ryanjbaxter** [comment]
Right that is what I am gathering from the description.  That is why I am wondering if you try the same thing with Edgware, if it works fine.

**Comment by domi55** [comment]
hi @ryanjbaxter 

with Boot 1.5.12 and Edgware.SR3? the `cloud.config.server.git.uri` is actually a [`UrlResource`](https://github.com/spring-projects/spring-framework/blob/9b7af8b5aaabbca31c6c89e635febd7577ba187a/spring-core/src/main/java/org/springframework/core/io/UrlResource.java) 
So the `instanceof` check still fails.

**Comment by marcingrzejszczak** [comment]
Is the problem still there in Finchley.RELEASE?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
