### ISSUE TITLE
Documentation Section 2.1 has incorrect substitution term for '/'

### ISSUE THREAD

**Issue by danapsimer** [spring-cloud/spring-cloud-config#997]
The Documentation states:

> If the git branch or tag name contains a slash (`/`), then the label in the HTTP URL should instead be specified with the special string `$$_$$` (to avoid ambiguity with other URL paths). For example, if the label is `foo/bar`, replacing the slash would result in the following label: `foo($$_$$)bar`.

The code, replaces the string `(_)` with `/` when handling application names and labels.

https://github.com/spring-cloud/spring-cloud-config/blob/852ec0a8cbb2a9295305f884fa57882f3978661c/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentController.java#L110-L127

When using cURL to test this out here are my results:

This works:
```
curl https://xxxxxxxx.com/app/development/feature\(_\)0-canary
```
But these don't:
```
curl https://xxxxxxxx.com/app/development/feature\($$_$$\)0-canary
curl https://xxxxxxxx.com/app/development/feature$$_$$0-canary
```
both of which seem to be right based on the documentation.

NOTE: I will be submitting an issue along with a pull request to make this `(_)`=`/` logic reciprocal in the cloud config client code.  So my suggested solution to this is to change the documentation rather than the code.

I wonder if a better way to handle this would be to use URL encoding instead.  Slash characters would be %2F instead.  I tried this at first, before reading this documentation, and it did not work for some unknown reason.  My guess is that something in Spring's RestController mechanisms is to blame.

**Comment by ryanjbaxter** [comment]
@spencergibb @dsyer do you know what the intended behavior was here?  Maybe this was some kind of bug that crept into the ASCII docs?  There is clearly a problem, just unsure what the correct behavior is.
